import type { Locale } from "@/lib/i18n";
import type { Localized } from "@/lib/blog/types";

/**
 * Copy della homepage estratto dagli ex-ternari inline `lc === "it" ? ... :
 * lc === "es" ? ... : "<english>"` (solo it/es/en) in un unico posto
 * tipizzato, riusando `Localized`/`tl()` già usato per `PRICING_SECTION` sulla
 * stessa pagina. Da questa versione tutti e 15 i locali sono tradotti
 * (`HOME_COMPLETE_LOCALES` in `lib/content/static-page-locales.ts` riflette lo
 * stesso set) — NON lasciare stringhe placeholder o copiate dall'inglese per
 * eventuali nuovi locali futuri, meglio ometterle (`tl()` fa fallback a `en`).
 */

type StepItem = { t: string; d: string };
type PrivacyPoint = { t: string; d: string };

type LocalizedItems<T> = { it: T; en: T } & Partial<Record<Locale, T>>;

export function tli<T>(l: LocalizedItems<T>, lc: Locale): T {
  return (l as Record<string, T | undefined>)[lc] ?? l.en;
}

export const HOMEPAGE_COPY = {
  leadSentence: {
    it: "FitMesh Sync è la dashboard che unisce i dati di Galaxy Watch, Wear OS, Mi Band, Garmin, Fitbit e altri wearable Android in un'unica vista privacy-first, con server in UE.",
    en: "FitMesh Sync is the dashboard that brings Galaxy Watch, Wear OS, Mi Band, Garmin, Fitbit and other Android wearables into one privacy-first view, with EU servers.",
    es: "FitMesh Sync es el panel que unifica los datos de Galaxy Watch, Wear OS, Mi Band, Garmin, Fitbit y otros wearables Android en una sola vista privacy-first, con servidores en la UE.",
    de: "FitMesh Sync ist das Dashboard, das Galaxy Watch, Wear OS, Mi Band, Garmin, Fitbit und andere Android-Wearables in einer datenschutzfreundlichen Ansicht vereint – mit Servern in der EU.",
    pt: "O FitMesh Sync é o dashboard que reúne o Galaxy Watch, Wear OS, Mi Band, Garmin, Fitbit e outros wearables Android numa única vista com privacidade em primeiro lugar, com servidores na UE.",
    fr: "FitMesh Sync est le tableau de bord qui réunit Galaxy Watch, Wear OS, Mi Band, Garmin, Fitbit et d'autres objets connectés Android dans une seule interface centrée sur la confidentialité, hébergée sur des serveurs européens.",
    pl: "FitMesh Sync to panel, który zbiera dane z Galaxy Watch, Wear OS, Mi Band, Garmin, Fitbit i innych opasek na Androida w jednym miejscu – z dbałością o prywatność i serwerami w UE.",
    tr: "FitMesh Sync; Galaxy Watch, Wear OS, Mi Band, Garmin, Fitbit ve diğer Android giyilebilir cihazlarınızı, AB sunucularında barındırılan ve gizliliği önceleyen tek bir panelde bir araya getiren gösterge panelidir.",
    nl: "FitMesh Sync is het dashboard dat Galaxy Watch, Wear OS, Mi Band, Garmin, Fitbit en andere Android-wearables samenbrengt in één privacyvriendelijk overzicht, met servers in de EU.",
    ja: "FitMesh Syncは、Galaxy Watch、Wear OS、Mi Band、Garmin、Fitbitなど各種Androidウェアラブルのデータをひとつにまとめ、EUサーバーでプライバシーを守りながら表示するダッシュボードです。",
    ko: "FitMesh Sync는 Galaxy Watch, Wear OS, Mi Band, Garmin, Fitbit 등 안드로이드 웨어러블 데이터를 하나의 화면에 모아, EU 서버에서 프라이버시를 최우선으로 안전하게 보여주는 대시보드입니다.",
    sv: "FitMesh Sync är instrumentpanelen som samlar Galaxy Watch, Wear OS, Mi Band, Garmin, Fitbit och andra Android-wearables i en enda integritetsfokuserad vy, med servrar i EU.",
    da: "FitMesh Sync er dashboardet, der samler Galaxy Watch, Wear OS, Mi Band, Garmin, Fitbit og andre Android-wearables i ét privatlivsvenligt overblik, med servere i EU.",
    no: "FitMesh Sync er dashbordet som samler Galaxy Watch, Wear OS, Mi Band, Garmin, Fitbit og andre wearables for Android i én personvernvennlig oversikt – med servere i EU.",
    fi: "FitMesh Sync on hallintapaneeli, joka kokoaa Galaxy Watchin, Wear OS:n, Mi Bandin, Garminin, Fitbitin ja muiden Android-puettavien tiedot yhteen näkymään, joka asettaa yksityisyyden etusijalle ja toimii EU-palvelimilla.",
  } satisfies Localized,

  founderCta: {
    it: "Diventa founder",
    en: "Become a founder",
    es: "Conviértete en founder",
    de: "Founder werden",
    pt: "Torna-te fundador",
    fr: "Devenir fondateur",
    pl: "Zostań founderem",
    tr: "Kurucu üye ol",
    nl: "Word founder",
    ja: "ファウンダーになる",
    ko: "파운더 되기",
    sv: "Bli founder",
    da: "Bliv founder",
    no: "Bli grunnlegger",
    fi: "Ryhdy perustajajäseneksi",
  } satisfies Localized,

  founderSeatsLabel: {
    it: "Founder slot",
    en: "Founder seats",
    es: "Plazas founder",
    de: "Founder-Plätze",
    pt: "Lugares de fundador",
    fr: "Places fondateurs",
    pl: "Miejsca founderskie",
    tr: "Kurucu üye kontenjanı",
    nl: "Founderplekken",
    ja: "ファウンダー枠",
    ko: "파운더 자리",
    sv: "Founder-platser",
    da: "Founder-pladser",
    no: "Grunnleggerplasser",
    fi: "Perustajapaikkaa",
  } satisfies Localized,

  wearablesSupportedLabel: {
    it: "Wearable supportati",
    en: "Wearables supported",
    es: "Wearables compatibles",
    de: "Unterstützte Wearables",
    pt: "Wearables suportados",
    fr: "Appareils compatibles",
    pl: "Obsługiwane urządzenia",
    tr: "Desteklenen giyilebilir cihaz",
    nl: "Ondersteunde wearables",
    ja: "対応ウェアラブル",
    ko: "지원 웨어러블",
    sv: "Wearables som stöds",
    da: "Understøttede wearables",
    no: "Støttede wearables",
    fi: "Tuettua puettavaa laitetta",
  } satisfies Localized,

  euServersLabel: {
    it: "Server in UE · GDPR",
    en: "EU servers · GDPR",
    es: "Servidores en la UE · GDPR",
    de: "EU-Server · DSGVO",
    pt: "Servidores na UE · RGPD",
    fr: "Serveurs UE · RGPD",
    pl: "Serwery w UE · RODO",
    tr: "AB sunucuları · KVKK",
    nl: "EU-servers · AVG",
    ja: "EUサーバー・GDPR",
    ko: "EU 서버 · GDPR",
    sv: "EU-servrar · GDPR",
    da: "EU-servere · GDPR",
    no: "EU-servere · GDPR",
    fi: "EU-palvelimet · GDPR",
  } satisfies Localized,

  worksWithKicker: {
    it: "Compatibile con",
    en: "Works with",
    es: "Compatible con",
    de: "Funktioniert mit",
    pt: "Compatível com",
    fr: "Compatible avec",
    pl: "Współpracuje z",
    tr: "Şunlarla Çalışır",
    nl: "Werkt met",
    ja: "対応",
    ko: "지원 기기",
    sv: "Fungerar med",
    da: "Fungerer med",
    no: "Fungerer med",
    fi: "Toimii näiden kanssa",
  } satisfies Localized,

  howItWorksKicker: {
    it: "Come funziona",
    en: "How it works",
    es: "Cómo funciona",
    de: "So funktioniert's",
    pt: "Como funciona",
    fr: "Comment ça marche",
    pl: "Jak to działa",
    tr: "Nasıl Çalışır",
    nl: "Hoe het werkt",
    ja: "使い方",
    ko: "이용 방법",
    sv: "Så funkar det",
    da: "Sådan fungerer det",
    no: "Slik fungerer det",
    fi: "Näin se toimii",
  } satisfies Localized,

  howItWorksHeading: {
    it: "Trenta secondi. Niente di più.",
    en: "Thirty seconds. Nothing more.",
    es: "Treinta segundos. Nada más.",
    de: "Dreißig Sekunden. Mehr nicht.",
    pt: "Trinta segundos. Nada mais.",
    fr: "Trente secondes. Pas une de plus.",
    pl: "Trzydzieści sekund. Nic więcej.",
    tr: "Otuz saniye. Hepsi bu kadar.",
    nl: "Dertig seconden. Meer niet.",
    ja: "30秒。それだけ。",
    ko: "30초. 그게 다예요.",
    sv: "Trettio sekunder. Inget mer.",
    da: "Tredive sekunder. Ikke mere.",
    no: "Tretti sekunder. Ikke mer.",
    fi: "30 sekuntia. Siinä kaikki.",
  } satisfies Localized,

  stepLabel: {
    it: "Step",
    en: "Step",
    es: "Paso",
    de: "Schritt",
    pt: "Passo",
    fr: "Étape",
    pl: "Krok",
    tr: "Adım",
    nl: "Stap",
    ja: "ステップ",
    ko: "단계",
    sv: "Steg",
    da: "Trin",
    no: "Steg",
    fi: "Vaihe",
  } satisfies Localized,

  steps: {
    it: [
      { t: "Scarica & autorizza", d: "Installa l'app dal Play Store, dai accesso a Health Connect." },
      { t: "FitMesh legge tutto", d: "Passi, battito, sonno, calorie. Anche in background, anche notte." },
      { t: "La tua dashboard è live", d: "Apri il browser da qualsiasi device. Niente account social, niente cloud opachi." },
    ],
    en: [
      { t: "Download & grant", d: "Install the app from Play Store, allow Health Connect access." },
      { t: "FitMesh reads it all", d: "Steps, heart rate, sleep, calories. In background, even overnight." },
      { t: "Your dashboard is live", d: "Open it in any browser. No social accounts, no opaque clouds." },
    ],
    es: [
      { t: "Descarga y autoriza", d: "Instala la app desde Play Store y permite el acceso a Health Connect." },
      { t: "FitMesh lo lee todo", d: "Pasos, frecuencia cardíaca, sueño, calorías. En segundo plano, incluso de noche." },
      { t: "Tu panel está en vivo", d: "Ábrelo desde cualquier navegador. Sin cuentas sociales, sin nubes opacas." },
    ],
    de: [
      { t: "Herunterladen & erlauben", d: "App im Play Store installieren und Zugriff auf Health Connect erlauben." },
      { t: "FitMesh liest alles aus", d: "Schritte, Herzfrequenz, Schlaf, Kalorien – im Hintergrund, auch über Nacht." },
      { t: "Dein Dashboard ist live", d: "Einfach im Browser öffnen. Keine Social-Media-Konten, keine undurchsichtigen Clouds." },
    ],
    pt: [
      { t: "Transferir e autorizar", d: "Instala a app na Play Store e permite o acesso ao Health Connect." },
      { t: "O FitMesh lê tudo", d: "Passos, frequência cardíaca, sono, calorias. Em segundo plano, mesmo durante a noite." },
      { t: "O teu dashboard está no ar", d: "Abre-o em qualquer navegador. Sem contas sociais, sem nuvens opacas." },
    ],
    fr: [
      { t: "Téléchargez et autorisez", d: "Installez l'application depuis le Play Store, autorisez l'accès à Health Connect." },
      { t: "FitMesh récupère tout", d: "Pas, fréquence cardiaque, sommeil, calories. En arrière-plan, même la nuit." },
      { t: "Votre tableau de bord est prêt", d: "Ouvrez-le depuis n'importe quel navigateur. Pas de compte social, pas de cloud opaque." },
    ],
    pl: [
      { t: "Pobierz i zezwól", d: "Zainstaluj aplikację z Google Play i zezwól na dostęp do Health Connect." },
      { t: "FitMesh odczytuje wszystko", d: "Kroki, tętno, sen, kalorie. W tle, nawet w nocy." },
      { t: "Twój panel jest gotowy", d: "Otwórz go w dowolnej przeglądarce. Bez kont społecznościowych, bez nieprzejrzystych chmur." },
    ],
    tr: [
      { t: "İndir ve izin ver", d: "Uygulamayı Play Store'dan yükleyin, Health Connect erişimine izin verin." },
      { t: "FitMesh hepsini okur", d: "Adım sayısı, nabız, uyku, kalori. Arka planda, gece boyunca bile." },
      { t: "Panelin yayında", d: "Herhangi bir tarayıcıda açın. Sosyal hesap yok, şeffaf olmayan bulut sistemleri yok." },
    ],
    nl: [
      { t: "Downloaden & toestaan", d: "Installeer de app via Play Store en geef toegang tot Health Connect." },
      { t: "FitMesh leest alles uit", d: "Stappen, hartslag, slaap, calorieën. Op de achtergrond, zelfs 's nachts." },
      { t: "Je dashboard staat live", d: "Open het in elke browser. Geen social accounts, geen ondoorzichtige clouds." },
    ],
    ja: [
      { t: "ダウンロードして許可", d: "Playストアからアプリをインストールし、Health Connectへのアクセスを許可します。" },
      { t: "FitMeshがすべてを読み取る", d: "歩数、心拍数、睡眠、カロリー。バックグラウンドで、就寝中も。" },
      { t: "ダッシュボードが今すぐ使える", d: "どのブラウザでも開けます。SNSアカウントも、不透明なクラウドも不要。" },
    ],
    ko: [
      { t: "다운로드 및 권한 허용", d: "Google Play 스토어에서 앱을 설치하고, Health Connect 접근을 허용하세요." },
      { t: "FitMesh가 전부 읽어옵니다", d: "걸음 수, 심박수, 수면, 칼로리까지. 백그라운드에서, 심지어 자는 동안에도." },
      { t: "대시보드가 바로 열립니다", d: "어떤 브라우저에서도 열어보세요. 소셜 계정도, 불투명한 클라우드도 필요 없습니다." },
    ],
    sv: [
      { t: "Ladda ner & godkänn", d: "Installera appen från Play Store, godkänn åtkomst till Health Connect." },
      { t: "FitMesh läser allt", d: "Steg, puls, sömn, kalorier. I bakgrunden, även över natten." },
      { t: "Din instrumentpanel är live", d: "Öppna den i vilken webbläsare som helst. Inga sociala konton, inga otydliga molntjänster." },
    ],
    da: [
      { t: "Download & giv adgang", d: "Installer appen fra Play Store, giv adgang til Health Connect." },
      { t: "FitMesh læser det hele", d: "Skridt, puls, søvn, kalorier. I baggrunden, også om natten." },
      { t: "Dit dashboard er live", d: "Åbn det i en hvilken som helst browser. Ingen sociale konti, ingen uigennemsigtige skyer." },
    ],
    no: [
      { t: "Last ned og godkjenn", d: "Installer appen fra Play Store, og gi tilgang til Health Connect." },
      { t: "FitMesh leser alt", d: "Skritt, puls, søvn, kalorier. I bakgrunnen, også om natten." },
      { t: "Dashbordet ditt er klart", d: "Åpne det i hvilken som helst nettleser. Ingen sosiale kontoer, ingen uklare skytjenester." },
    ],
    fi: [
      { t: "Lataa ja hyväksy", d: "Asenna sovellus Google Play -kaupasta ja salli Health Connect -käyttöoikeus." },
      { t: "FitMesh lukee kaiken", d: "Askeleet, syke, uni, kalorit. Taustalla, myös yön yli." },
      { t: "Hallintapaneelisi on käytössä", d: "Avaa se missä tahansa selaimessa. Ei sosiaalisen median tilejä, ei läpinäkymättömiä pilvipalveluita." },
    ],
  } as LocalizedItems<StepItem[]>,

  integrationsKicker: {
    it: "Integrazioni",
    en: "Integrations",
    es: "Integraciones",
    de: "Integrationen",
    pt: "Integrações",
    fr: "Intégrations",
    pl: "Integracje",
    tr: "Entegrasyonlar",
    nl: "Integraties",
    ja: "連携",
    ko: "연동",
    sv: "Integrationer",
    da: "Integrationer",
    no: "Integrasjoner",
    fi: "Integraatiot",
  } satisfies Localized,

  integrationsHeading: {
    it: "Funziona con quello che hai già.",
    en: "Works with what you already have.",
    es: "Funciona con lo que ya tienes.",
    de: "Funktioniert mit dem, was du schon hast.",
    pt: "Funciona com o que já tens.",
    fr: "Compatible avec ce que vous avez déjà.",
    pl: "Działa z tym, co już masz.",
    tr: "Elindekiyle çalışır.",
    nl: "Werkt met wat je al hebt.",
    ja: "今使っているものと、そのままつながる。",
    ko: "지금 쓰는 기기와 바로 연동됩니다.",
    sv: "Fungerar med det du redan har.",
    da: "Fungerer med det, du allerede har.",
    no: "Fungerer med det du allerede har.",
    fi: "Toimii sen kanssa, mikä sinulla jo on.",
  } satisfies Localized,

  seeAll: {
    it: "Vedi tutte",
    en: "See all",
    es: "Ver todas",
    de: "Alle anzeigen",
    pt: "Ver tudo",
    fr: "Tout voir",
    pl: "Zobacz wszystkie",
    tr: "Tümünü gör",
    nl: "Bekijk alles",
    ja: "すべて見る",
    ko: "전체 보기",
    sv: "Se alla",
    da: "Se alle",
    no: "Se alle",
    fi: "Katso kaikki",
  } satisfies Localized,

  /**
   * Sprint P0.2 Fase 6 (2026-07-12): teaser sotto integrationsHeading, link a
   * /fitness-data-sync. Tradotto solo it/en/de/es (stesso scope della
   * landing, vedi FITNESS_DATA_SYNC_COMPLETE_LOCALES) — le altre locale
   * cadono su en via tl().
   */
  integrationsDashboardTeaser: {
    it: "Vuoi sapere cosa è live e cosa è ancora in sviluppo?",
    en: "Want to know what's live and what's still in development?",
    es: "¿Quieres saber qué está en vivo y qué sigue en desarrollo?",
    de: "Möchtest du wissen, was live ist und was sich noch in Entwicklung befindet?",
  } satisfies Localized,

  privacyPoints: {
    it: [
      { t: "Server in UE", d: "Postgres su infrastruttura europea. Niente trasferimenti USA." },
      { t: "Zero tracker pubblicitari", d: "I tuoi dati salute non alimentano nessun algoritmo pubblicitario. Niente profilazione, niente dati condivisi con terzi." },
      { t: "Cancellazione in 48h", d: "Un click in app, e tutto è cancellato. Compliance GDPR completa." },
    ],
    en: [
      { t: "EU servers", d: "Postgres on European infrastructure. No US transfers." },
      { t: "Zero ad trackers", d: "Your health data feeds no advertising algorithm. No cross-site tracking, no third-party data sharing." },
      { t: "Delete in 48h", d: "One click in-app, everything gone. Full GDPR compliance." },
    ],
    es: [
      { t: "Servidores en la UE", d: "Postgres en infraestructura europea. Sin transferencias a EE. UU." },
      { t: "Cero rastreadores publicitarios", d: "Tus datos de salud no alimentan ningún algoritmo publicitario. Sin perfilado, sin datos compartidos con terceros." },
      { t: "Eliminación en 48 h", d: "Un clic en la app y todo desaparece. Cumplimiento total del RGPD." },
    ],
    de: [
      { t: "EU-Server", d: "Postgres auf europäischer Infrastruktur. Keine Datenübertragung in die USA." },
      { t: "Keine Werbetracker", d: "Deine Gesundheitsdaten fließen in keinen Werbealgorithmus. Kein seitenübergreifendes Tracking, keine Weitergabe an Dritte." },
      { t: "Löschung in 48 Std.", d: "Ein Klick in der App, alles verschwindet. Vollständig DSGVO-konform." },
    ],
    pt: [
      { t: "Servidores na UE", d: "Postgres em infraestrutura europeia. Sem transferências para os EUA." },
      { t: "Zero rastreadores publicitários", d: "Os teus dados de saúde não alimentam nenhum algoritmo publicitário. Sem rastreamento entre sites, sem partilha de dados com terceiros." },
      { t: "Elimina em 48h", d: "Um clique na app e está tudo apagado. Conformidade total com o RGPD." },
    ],
    fr: [
      { t: "Serveurs UE", d: "Postgres sur infrastructure européenne. Aucun transfert vers les États-Unis." },
      { t: "Zéro traceur publicitaire", d: "Vos données de santé n'alimentent aucun algorithme publicitaire. Pas de suivi entre sites, pas de partage avec des tiers." },
      { t: "Suppression en 48h", d: "Un clic dans l'application, tout disparaît. Conformité RGPD totale." },
    ],
    pl: [
      { t: "Serwery w UE", d: "Postgres na europejskiej infrastrukturze. Bez transferu danych do USA." },
      { t: "Zero trackerów reklamowych", d: "Twoje dane zdrowotne nie zasilają żadnego algorytmu reklamowego. Bez śledzenia między witrynami, bez udostępniania danych stronom trzecim." },
      { t: "Usunięcie w 48h", d: "Jedno kliknięcie w aplikacji i wszystko znika. Pełna zgodność z RODO." },
    ],
    tr: [
      { t: "AB sunucuları", d: "Avrupa altyapısında Postgres. ABD'ye veri aktarımı yok." },
      { t: "Sıfır reklam izleyicisi", d: "Sağlık verileriniz hiçbir reklam algoritmasını beslemez. Siteler arası takip yok, üçüncü taraflarla veri paylaşımı yok." },
      { t: "48 saatte sil", d: "Uygulama içinde tek tıkla her şey silinir. Tam KVKK uyumluluğu." },
    ],
    nl: [
      { t: "EU-servers", d: "Postgres op Europese infrastructuur. Geen overdracht naar de VS." },
      { t: "Geen advertentietrackers", d: "Je gezondheidsgegevens voeden geen advertentiealgoritme. Geen cross-site tracking, geen gegevensdeling met derden." },
      { t: "Verwijderd binnen 48u", d: "Eén klik in de app, alles verdwijnt. Volledig AVG-compliant." },
    ],
    ja: [
      { t: "EUサーバー", d: "欧州のインフラで稼働するPostgres。米国へのデータ移転はありません。" },
      { t: "広告トラッカーゼロ", d: "健康データが広告アルゴリズムに使われることはありません。クロスサイトトラッキングも、第三者へのデータ提供も一切なし。" },
      { t: "48時間で削除", d: "アプリ内でワンクリック、すべて消去されます。GDPRに完全準拠。" },
    ],
    ko: [
      { t: "EU 서버", d: "유럽 인프라의 Postgres. 미국으로의 데이터 전송 없음." },
      { t: "광고 트래커 없음", d: "건강 데이터가 광고 알고리즘에 쓰이지 않습니다. 교차 사이트 추적도, 제3자 데이터 공유도 없습니다." },
      { t: "48시간 내 완전 삭제", d: "앱 안에서 클릭 한 번이면 전부 삭제됩니다. GDPR을 완벽히 준수합니다." },
    ],
    sv: [
      { t: "EU-servrar", d: "Postgres på europeisk infrastruktur. Inga överföringar till USA." },
      { t: "Inga annonsspårare", d: "Din hälsodata matar ingen annonsalgoritm. Ingen spårning mellan webbplatser, ingen delning av data med tredje part." },
      { t: "Radera inom 48 timmar", d: "Ett klick i appen, allt försvinner. Fullt GDPR-kompatibel." },
    ],
    da: [
      { t: "EU-servere", d: "Postgres på europæisk infrastruktur. Ingen overførsler til USA." },
      { t: "Ingen annoncetrackere", d: "Dine sundhedsdata fodrer ingen reklamealgoritme. Ingen tracking på tværs af sider, ingen deling af data med tredjeparter." },
      { t: "Slet på 48 timer", d: "Ét klik i appen, og alt er væk. Fuld GDPR-overholdelse." },
    ],
    no: [
      { t: "EU-servere", d: "Postgres på europeisk infrastruktur. Ingen overføring til USA." },
      { t: "Ingen annonsesporing", d: "Helsedataene dine mater ingen annonsealgoritme. Ingen sporing på tvers av nettsteder, ingen deling med tredjeparter." },
      { t: "Slett på 48 timer", d: "Ett klikk i appen, og alt er borte. Fullt i tråd med GDPR." },
    ],
    fi: [
      { t: "EU-palvelimet", d: "Postgres eurooppalaisella infrastruktuurilla. Ei siirtoja Yhdysvaltoihin." },
      { t: "Nolla mainosseurantaa", d: "Terveystietosi eivät ruoki yhtään mainosalgoritmia. Ei sivustojen välistä seurantaa, ei tietojen jakamista kolmansille osapuolille." },
      { t: "Poisto 48 tunnissa", d: "Yksi klikkaus sovelluksessa, ja kaikki on poissa. Täysi GDPR-vaatimustenmukaisuus." },
    ],
  } as LocalizedItems<PrivacyPoint[]>,

  orLabel: {
    it: "oppure",
    en: "or",
    es: "o",
    de: "oder",
    pt: "ou",
    fr: "ou",
    pl: "lub",
    tr: "veya",
    nl: "of",
    ja: "または",
    ko: "또는",
    sv: "eller",
    da: "eller",
    no: "eller",
    fi: "tai",
  } satisfies Localized,

  readMoreKicker: {
    it: "Approfondisci",
    en: "Read more",
    es: "Más información",
    de: "Weiterlesen",
    pt: "Ler mais",
    fr: "En savoir plus",
    pl: "Czytaj więcej",
    tr: "Daha Fazla Oku",
    nl: "Meer lezen",
    ja: "もっと読む",
    ko: "더 알아보기",
    sv: "Läs mer",
    da: "Læs mere",
    no: "Les mer",
    fi: "Lue lisää",
  } satisfies Localized,

  readMoreHeading: {
    it: "Guide e confronti per scegliere bene.",
    en: "Guides and comparisons to choose well.",
    es: "Guías y comparativas para elegir bien.",
    de: "Ratgeber und Vergleiche für die richtige Wahl.",
    pt: "Guias e comparações para escolheres bem.",
    fr: "Des guides et comparatifs pour bien choisir.",
    pl: "Poradniki i porównania, dzięki którym dobrze wybierzesz.",
    tr: "Doğru seçim için rehberler ve karşılaştırmalar.",
    nl: "Gidsen en vergelijkingen om de juiste keuze te maken.",
    ja: "賢く選ぶための、ガイドと比較記事。",
    ko: "현명하게 고르도록 돕는 가이드와 비교.",
    sv: "Guider och jämförelser för att välja rätt.",
    da: "Guider og sammenligninger, så du vælger rigtigt.",
    no: "Guider og sammenligninger som hjelper deg å velge riktig.",
    fi: "Oppaat ja vertailut oikean valinnan tueksi.",
  } satisfies Localized,

  allArticles: {
    it: "Tutti gli articoli",
    en: "All articles",
    es: "Todos los artículos",
    de: "Alle Artikel",
    pt: "Todos os artigos",
    fr: "Tous les articles",
    pl: "Wszystkie artykuły",
    tr: "Tüm yazılar",
    nl: "Alle artikelen",
    ja: "すべての記事",
    ko: "전체 글 보기",
    sv: "Alla artiklar",
    da: "Alle artikler",
    no: "Alle artikler",
    fi: "Kaikki artikkelit",
  } satisfies Localized,

  mainGuideLabel: {
    it: "Guida principale",
    en: "Main guide",
    es: "Guía principal",
    de: "Hauptratgeber",
    pt: "Guia principal",
    fr: "Guide principal",
    pl: "Główny poradnik",
    tr: "Ana rehber",
    nl: "Hoofdgids",
    ja: "メインガイド",
    ko: "대표 가이드",
    sv: "Huvudguide",
    da: "Hovedguide",
    no: "Hovedguide",
    fi: "Pääopas",
  } satisfies Localized,

  guideLabel: {
    it: "Guida",
    en: "Guide",
    es: "Guía",
    de: "Ratgeber",
    pt: "Guia",
    fr: "Guide",
    pl: "Poradnik",
    tr: "Rehber",
    nl: "Gids",
    ja: "ガイド",
    ko: "가이드",
    sv: "Guide",
    da: "Guide",
    no: "Guide",
    fi: "Opas",
  } satisfies Localized,

  readLabel: {
    it: "Leggi",
    en: "Read",
    es: "Leer",
    de: "Lesen",
    pt: "Ler",
    fr: "Lire",
    pl: "Czytaj",
    tr: "Oku",
    nl: "Lezen",
    ja: "読む",
    ko: "읽기",
    sv: "Läs",
    da: "Læs",
    no: "Les",
    fi: "Lue",
  } satisfies Localized,

  finalCtaBadgeLive: {
    it: "Android e iOS · 1000 founder",
    en: "Android & iOS · 1000 founders",
    es: "Android e iOS · 1000 founders",
    de: "Android & iOS · 1000 Founder",
    pt: "Android e iOS · 1000 fundadores",
    fr: "Android et iOS · 1000 fondateurs",
    pl: "Android i iOS · 1000 founderów",
    tr: "Android ve iOS · 1000 kurucu üye",
    nl: "Android & iOS · 1000 founders",
    ja: "Android & iOS・ファウンダー1000名",
    ko: "Android & iOS · 파운더 1000명",
    sv: "Android och iOS · 1000 founder-platser",
    da: "Android & iOS · 1000 founders",
    no: "Android og iOS · 1000 grunnleggere",
    fi: "Android ja iOS · 1000 perustajaa",
  } satisfies Localized,


  finalCtaButton: {
    it: "Voglio essere founder",
    en: "I want to be a founder",
    es: "Quiero ser founder",
    de: "Ich will Founder werden",
    pt: "Quero ser fundador",
    fr: "Je veux être fondateur",
    pl: "Chcę zostać founderem",
    tr: "Kurucu üye olmak istiyorum",
    nl: "Ik wil founder worden",
    ja: "ファウンダーになりたい",
    ko: "파운더가 되고 싶어요",
    sv: "Jag vill bli founder",
    da: "Jeg vil være founder",
    no: "Jeg vil bli grunnlegger",
    fi: "Haluan perustajaksi",
  } satisfies Localized,

  finalCtaAfterLaunch: {
    it: "Dopo il lancio pubblico, acquisto unico",
    en: "After public launch, one-time",
    es: "Tras el lanzamiento público, pago único",
    de: "Nach dem offiziellen Launch, einmalig",
    pt: "Após o lançamento público, pagamento único",
    fr: "Après le lancement public, paiement unique",
    pl: "Po oficjalnej premierze, jednorazowo",
    tr: "Herkese açık lansmandan sonra, tek seferlik",
    nl: "Na publieke lancering, eenmalig",
    ja: "正式リリース後は買い切りで",
    ko: "정식 출시 후, 1회 결제",
    sv: "Efter lansering till allmänheten, engångskostnad",
    da: "Efter offentlig lancering, engangsbeløb",
    no: "Etter offentlig lansering, engangsbeløp",
    fi: "Julkisen lanseerauksen jälkeen, kertamaksu",
  } satisfies Localized,
} as const;
