// Slug URL localizzati per lingua (SEO). Chiave = slug canonico (= slug IT).
// L'italiano usa lo slug canonico (la chiave) e non è in mappa.
// Generato per la localizzazione slug 18/06.
type SlugSet = { en: string; es: string; de: string; pt: string; fr: string };

export const BLOG_SLUGS: Record<string, SlugSet> = {
  "alternative-app-sync-wearable-2026": {
    en: "wearable-sync-apps-alternatives-2026",
    es: "alternativas-apps-sincronizacion-wearable",
    de: "wearable-sync-apps-alternativen-2026",
    pt: "alternativas-apps-sincronizacao-wearable",
    fr: "alternatives-applications-synchronisation-wearable",
  },
  "anello-smart-guida-completa": {
    en: "smart-ring-complete-guide",
    es: "anillo-inteligente-guia-completa",
    de: "smart-ring-ratgeber",
    pt: "anel-inteligente-guia-completo",
    fr: "bague-connectee-guide-complet",
  },
  "anello-vs-smartwatch": {
    en: "smart-ring-vs-smartwatch",
    es: "anillo-inteligente-o-smartwatch",
    de: "smart-ring-oder-smartwatch",
    pt: "anel-inteligente-ou-smartwatch",
    fr: "bague-connectee-ou-montre-connectee",
  },
  "backup-galaxy-watch-pc": {
    en: "galaxy-watch-backup-pc",
    es: "copia-seguridad-galaxy-watch-pc",
    de: "galaxy-watch-backup-pc",
    pt: "backup-galaxy-watch-pc",
    fr: "sauvegarde-galaxy-watch-pc",
  },
  "best-health-data-sync-app-android": {
    en: "best-health-data-sync-app-android",
    es: "mejor-app-sincronizacion-datos-salud-android",
    de: "beste-gesundheitsdaten-sync-app-android",
    pt: "melhor-app-sincronizacao-dados-saude-android",
    fr: "meilleure-app-synchronisation-donnees-sante-android",
  },
  "best-smartwatch-for-elderly": {
    en: "best-smartwatch-for-elderly",
    es: "mejor-smartwatch-personas-mayores",
    de: "beste-smartwatch-fuer-senioren",
    pt: "melhor-smartwatch-para-idosos",
    fr: "meilleure-montre-connectee-personnes-agees",
  },
  "colmi-r02-setup": {
    en: "set-up-colmi-ring",
    es: "configurar-anillo-colmi",
    de: "colmi-ring-einrichten",
    pt: "configurar-anel-colmi",
    fr: "configurer-bague-connectee-colmi",
  },
  "colmi-ring-fitmesh": {
    en: "colmi-ring-app-data-dashboard",
    es: "colmi-r02-app-datos-panel",
    de: "colmi-ring-daten-dashboard",
    pt: "colmi-ring-app-dados-painel",
    fr: "colmi-ring-app-donnees-tableau-de-bord",
  },
  "come-funziona-health-connect": {
    en: "how-does-health-connect-work",
    es: "como-funciona-health-connect",
    de: "wie-funktioniert-health-connect",
    pt: "como-funciona-health-connect",
    fr: "comment-fonctionne-health-connect",
  },
  "dati-anello-smart-apple-salute": {
    en: "smart-ring-data-apple-health",
    es: "anillo-inteligente-datos-apple-salud",
    de: "smart-ring-daten-apple-health",
    pt: "anel-inteligente-dados-apple-saude",
    fr: "bague-connectee-donnees-sante-apple",
  },
  "esportare-dati-fitbit-google": {
    en: "export-fitbit-data-after-google",
    es: "exportar-datos-fitbit-despues-google",
    de: "fitbit-daten-exportieren-nach-google",
    pt: "exportar-dados-fitbit-depois-google",
    fr: "exporter-donnees-fitbit-apres-google",
  },
  "esportare-dati-garmin": {
    en: "export-garmin-data",
    es: "exportar-datos-garmin",
    de: "garmin-daten-exportieren",
    pt: "exportar-dados-garmin",
    fr: "exporter-donnees-garmin",
  },
  "fitbit-data-not-syncing-android": {
    en: "fitbit-data-not-syncing-android",
    es: "fitbit-no-sincroniza-datos-android",
    de: "fitbit-synchronisiert-nicht-android",
    pt: "fitbit-nao-sincroniza-dados-android",
    fr: "fitbit-ne-synchronise-pas-android",
  },
  "fitmesh-arriva-su-iphone": {
    en: "fitmesh-sync-arrives-iphone",
    es: "fitmesh-sync-llega-iphone",
    de: "fitmesh-sync-kommt-auf-iphone",
    pt: "fitmesh-sync-chega-no-iphone",
    fr: "fitmesh-sync-arrive-sur-iphone",
  },
  "fitmesh-sync-disponibile-google-play": {
    en: "fitmesh-sync-available-google-play",
    es: "fitmesh-sync-disponible-google-play",
    de: "fitmesh-sync-verfuegbar-google-play",
    pt: "fitmesh-sync-disponivel-google-play",
    fr: "fitmesh-sync-disponible-google-play",
  },
  "gdpr-dati-fitness-smartwatch": {
    en: "gdpr-fitness-data-smartwatch",
    es: "gdpr-datos-fitness-smartwatch",
    de: "dsgvo-fitnessdaten-smartwatch",
    pt: "lgpd-dados-fitness-smartwatch",
    fr: "rgpd-donnees-fitness-montre-connectee",
  },
  "google-fit-cierra-alternativas-health-connect": {
    en: "google-fit-shutting-down-alternative",
    es: "google-fit-cierra-alternativa-health-connect",
    de: "google-fit-eingestellt-alternative",
    pt: "google-fit-encerrando-alternativa",
    fr: "google-fit-fermeture-alternative",
  },
  "guida-sync-wearable-2026": {
    en: "sync-smartwatch-dashboard-2026",
    es: "sincronizar-smartwatch-panel-2026",
    de: "smartwatch-synchronisieren-dashboard-2026",
    pt: "sincronizar-smartwatch-painel-2026",
    fr: "synchroniser-montre-connectee-tableau-de-bord",
  },
  "health-connect-not-syncing": {
    en: "health-connect-not-syncing",
    es: "health-connect-no-sincroniza",
    de: "health-connect-synchronisiert-nicht",
    pt: "health-connect-nao-sincroniza",
    fr: "health-connect-ne-synchronise-pas",
  },
  "health-connect-vs-samsung-health": {
    en: "health-connect-vs-samsung-health",
    es: "health-connect-vs-samsung-health",
    de: "health-connect-vs-samsung-health",
    pt: "health-connect-vs-samsung-health",
    fr: "health-connect-vs-samsung-health",
  },
  "how-to-export-apple-health-data": {
    en: "how-to-export-apple-health-data",
    es: "exportar-datos-apple-health",
    de: "apple-health-daten-exportieren",
    pt: "exportar-dados-apple-health",
    fr: "exporter-donnees-apple-health",
  },
  "hrv-cose-significato-valori": {
    en: "what-is-hrv-meaning-values",
    es: "que-es-hrv-significado-valores",
    de: "was-ist-hrv-bedeutung-werte",
    pt: "o-que-e-hrv-significado-valores",
    fr: "quest-ce-que-hrv-signification-valeurs",
  },
  "migliori-anelli-economici": {
    en: "best-cheap-smart-rings",
    es: "mejores-anillos-inteligentes-economicos",
    de: "guenstige-smart-ringe-vergleich",
    pt: "melhores-aneis-inteligentes-baratos",
    fr: "meilleures-bagues-connectees-pas-cheres",
  },
  "novita-anello-colmi-sonno": {
    en: "colmi-ring-sleep-tracking",
    es: "anillo-colmi-monitoreo-sueno",
    de: "colmi-ring-schlaf-tracking",
    pt: "anel-colmi-monitoramento-sono",
    fr: "bague-colmi-suivi-sommeil",
  },
  "novita-dashboard-multi-device": {
    en: "multi-device-health-dashboard",
    es: "panel-multi-dispositivo-salud",
    de: "multi-geraete-gesundheits-dashboard",
    pt: "painel-multi-dispositivo-saude",
    fr: "tableau-de-bord-multi-appareils-sante",
  },
  "novita-fonte-del-dato": {
    en: "which-device-your-health-data-comes-from",
    es: "de-que-dispositivo-provienen-tus-datos",
    de: "von-welchem-geraet-kommen-deine-daten",
    pt: "de-qual-dispositivo-vem-seus-dados",
    fr: "de-quel-appareil-viennent-vos-donnees",
  },
  "passi-non-si-sincronizzano-galaxy-watch": {
    en: "steps-not-syncing-galaxy-watch",
    es: "pasos-no-se-sincronizan-galaxy-watch",
    de: "schritte-synchronisieren-galaxy-watch",
    pt: "passos-nao-sincronizam-galaxy-watch",
    fr: "pas-ne-synchronisent-pas-galaxy-watch",
  },
  "piu-smartwatch-insieme-dati-doppi": {
    en: "multiple-smartwatches-duplicate-data",
    es: "varios-smartwatches-datos-duplicados",
    de: "mehrere-smartwatches-doppelte-daten",
    pt: "varios-smartwatches-dados-duplicados",
    fr: "plusieurs-montres-connectees-donnees-dupliquees",
  },
  "scegliere-smartwatch-dati-2026": {
    en: "how-to-choose-smartwatch-personal-data",
    es: "como-elegir-smartwatch-control-datos",
    de: "smartwatch-nach-datenkontrolle-auswaehlen",
    pt: "como-escolher-smartwatch-controle-dados",
    fr: "comment-choisir-montre-connectee-donnees",
  },
  "smartwatch-estate-2026": {
    en: "smartwatch-summer-2026",
    es: "smartwatch-verano-2026",
    de: "smartwatch-sommer-2026",
    pt: "smartwatch-verao-2026",
    fr: "montre-connectee-ete-2026",
  },
  "smartwatch-per-anziani-guida": {
    en: "smartwatch-for-elderly-guide",
    es: "smartwatch-para-personas-mayores-guia",
    de: "smartwatch-fuer-senioren-ratgeber",
    pt: "smartwatch-para-pessoas-idosas-guia",
    fr: "montre-connectee-personnes-agees-guide",
  },
  "sync-samsung-health-google-fit": {
    en: "sync-samsung-health-google-fit",
    es: "sincronizar-samsung-health-google-fit",
    de: "samsung-health-google-fit-synchronisieren",
    pt: "sincronizar-samsung-health-google-fit",
    fr: "synchroniser-samsung-health-google-fit",
  },
  "sync-them-all": {
    en: "sync-all-wearables-app",
    es: "app-sincronizacion-todos-wearables",
    de: "alle-wearables-synchronisieren-app",
    pt: "app-sincronizar-todos-wearables",
    fr: "app-synchronisation-tous-appareils-connectes",
  },
  "tracciare-sonno-anello": {
    en: "track-sleep-with-smart-ring",
    es: "registrar-sueno-anillo-inteligente",
    de: "schlaf-aufzeichnen-smart-ring",
    pt: "monitorar-sono-anel-inteligente",
    fr: "suivre-sommeil-bague-connectee",
  },
  "vedere-dati-wearable-browser-pc": {
    en: "view-smartwatch-data-on-pc",
    es: "ver-datos-smartwatch-navegador-pc",
    de: "smartwatch-daten-im-browser-anzeigen",
    pt: "ver-dados-smartwatch-navegador-pc",
    fr: "voir-donnees-montre-connectee-navigateur-pc",
  },
  "esportare-dati-xiaomi-amazfit": {
    en: "xiaomi-amazfit-health-connect-data-dashboard",
    es: "xiaomi-amazfit-health-connect-datos-panel",
    de: "xiaomi-amazfit-daten-health-connect-dashboard",
    pt: "xiaomi-amazfit-dados-health-connect-painel",
    fr: "xiaomi-amazfit-donnees-health-connect-tableau-de-bord",
  },
  "sincronizzare-withings": {
    en: "sync-withings-data",
    es: "sincronizar-datos-withings",
    de: "withings-daten-synchronisieren",
    pt: "sincronizar-dados-withings",
    fr: "synchroniser-donnees-withings",
  },
  "dati-pixel-watch-dashboard": {
    en: "pixel-watch-data-personal-dashboard",
    es: "datos-pixel-watch-panel-personal",
    de: "pixel-watch-daten-persoenliches-dashboard",
    pt: "dados-pixel-watch-painel-pessoal",
    fr: "donnees-pixel-watch-tableau-de-bord-personnel",
  },
};

export const LANDING_SLUGS: Record<string, SlugSet> = {
  "backup-galaxy-watch": {
    en: "galaxy-watch-backup",
    es: "copia-seguridad-galaxy-watch",
    de: "galaxy-watch-backup",
    pt: "backup-galaxy-watch",
    fr: "sauvegarde-galaxy-watch",
  },
  "fitbit-export-google": {
    en: "export-fitbit-data-google",
    es: "exportar-datos-fitbit-google",
    de: "fitbit-daten-exportieren-google",
    pt: "exportar-dados-fitbit-google",
    fr: "exporter-donnees-fitbit-google",
  },
  "garmin-connect-pc": {
    en: "garmin-connect-pc",
    es: "garmin-connect-pc",
    de: "garmin-connect-pc",
    pt: "garmin-connect-pc",
    fr: "garmin-connect-pc",
  },
  "oura-ring-sync": {
    en: "sync-oura-ring-data",
    es: "sincronizar-datos-oura-ring",
    de: "oura-ring-synchronisieren",
    pt: "sincronizar-dados-oura-ring",
    fr: "synchroniser-donnees-oura-ring",
  },
  "polar-flow-sync": {
    en: "export-polar-flow-data",
    es: "exportar-datos-polar-flow",
    de: "polar-flow-daten-exportieren",
    pt: "exportar-dados-polar-flow",
    fr: "exporter-donnees-polar-flow",
  },
  "due-telefoni": {
    en: "fitmesh-two-phones-one-account",
    es: "fitmesh-dos-telefonos-una-cuenta",
    de: "fitmesh-zwei-handys-ein-konto",
    pt: "fitmesh-dois-celulares-uma-conta",
    fr: "fitmesh-deux-telephones-un-compte",
  },
  "anello-smart-sonno": {
    en: "colmi-smart-ring-sleep-fitmesh",
    es: "anillo-inteligente-sueno-colmi-fitmesh",
    de: "colmi-smart-ring-schlaf-fitmesh",
    pt: "anel-inteligente-sono-colmi-fitmesh",
    fr: "bague-connectee-sommeil-colmi-fitmesh",
  },
  "apple-health-export": {
    en: "apple-health-data-export-web",
    es: "exportar-datos-apple-health-web",
    de: "apple-health-daten-exportieren-web",
    pt: "exportar-dados-apple-health-web",
    fr: "exporter-donnees-apple-health-web",
  },
};
