import type { BlogPost } from "../types";

export const post: BlogPost = {
  slug: "backup-galaxy-watch-pc",
  category: "guides",
  publishedAt: "2026-05-21",
  updatedAt: "2026-05-21",
  readMinutes: 9,
  tldr: {
    it: [
      "L'export interno di Samsung Health (Impostazioni → Scarica dati personali) è il metodo più completo e gratuito: genera un pacchetto CSV con tutta la storia.",
      "Health Connect collegato a un'app terza è l'unica via con automazione reale, ma copre solo i tipi di dato che Samsung Health scrive su HC.",
      "La richiesta GDPR è più ampia dell'export interno (include metadati e log), ma richiede fino a 30 giorni: utile per l'archivio pre-chiusura account.",
      "ADB è per utenti tecnici: accesso diretto al database SQLite, massima completezza, alto rischio se non si sa cosa si fa.",
      "I dati proprietari Samsung (Body Composition, Stress Score continuo) non passano per Health Connect: per quelli serve sempre l'export manuale.",
    ],
    en: [
      "Samsung Health's internal export (Settings → Download personal data) is the most complete and free method: it generates a CSV package with your entire history.",
      "Health Connect linked to a third-party app is the only path with real automation, but covers only the data types Samsung Health writes to HC.",
      "The GDPR request is broader than the internal export (includes metadata and logs), but takes up to 30 days: useful for an archive before closing the account.",
      "ADB is for technical users: direct access to the SQLite database, maximum completeness, high risk if you don't know what you're doing.",
      "Samsung-proprietary data (Body Composition, continuous Stress Score) doesn't pass through Health Connect: manual export is always needed for those.",
    ],
    es: [
      "La exportación interna de Samsung Health (Ajustes → Descargar datos personales) es el método más completo y gratuito: genera un paquete CSV con todo tu historial.",
      "Health Connect vinculado a una app de terceros es la única opción con automatización real, pero solo cubre los tipos de datos que Samsung Health escribe en HC.",
      "La solicitud GDPR es más amplia que la exportación interna (incluye metadatos y registros), pero puede tardar hasta 30 días: útil como archivo antes de cerrar la cuenta.",
      "ADB es para usuarios técnicos: acceso directo a la base de datos SQLite, máxima completitud, riesgo alto si no sabes lo que haces.",
      "Los datos propietarios de Samsung (Body Composition, Stress Score continuo) no pasan por Health Connect: para ellos siempre necesitas la exportación manual.",
    ],
    de: [
      "Der interne Export von Samsung Health (Einstellungen → Persönliche Daten herunterladen) ist die vollständigste und kostenlose Methode: Er erstellt ein CSV-Paket mit deiner gesamten Datei.",
      "Health Connect, verbunden mit einer Drittanbieter-App, ist der einzige Weg mit echter Automatisierung, deckt aber nur die Datentypen ab, die Samsung Health in HC schreibt.",
      "Die DSGVO-Anfrage ist umfangreicher als der interne Export (enthält Metadaten und Logs), dauert aber bis zu 30 Tage: nützlich als Archiv vor dem Schließen des Kontos.",
      "ADB ist für technisch versierte Nutzer: direkter Zugriff auf die SQLite-Datenbank, maximale Vollständigkeit, hohes Risiko wenn man nicht weiß, was man tut.",
      "Proprietäre Samsung-Daten (Body Composition, kontinuierlicher Stress Score) laufen nicht über Health Connect: Für diese ist immer der manuelle Export erforderlich.",
    ],
    pt: [
      "A exportação interna do Samsung Health (Configurações → Baixar dados pessoais) é o método mais completo e gratuito: gera um pacote CSV com todo o seu histórico.",
      "O Health Connect vinculado a um app de terceiros é o único caminho com automação real, mas cobre apenas os tipos de dados que o Samsung Health grava no HC.",
      "A solicitação LGPD/GDPR é mais ampla do que a exportação interna (inclui metadados e logs), mas leva até 30 dias: útil como arquivo antes de encerrar a conta.",
      "O ADB é para usuários técnicos: acesso direto ao banco de dados SQLite, completude máxima, alto risco se você não sabe o que está fazendo.",
      "Os dados proprietários da Samsung (Body Composition, Stress Score contínuo) não passam pelo Health Connect: para eles, a exportação manual sempre será necessária.",
    ],
    fr: [
      "L'export interne de Samsung Health (Paramètres → Télécharger mes données personnelles) est la méthode la plus complète et gratuite : il génère un package CSV avec tout votre historique.",
      "Health Connect relié à une application tierce est le seul moyen avec une vraie automatisation, mais ne couvre que les types de données que Samsung Health écrit dans HC.",
      "La demande RGPD est plus large que l'export interne (inclut les métadonnées et les journaux), mais prend jusqu'à 30 jours : utile comme archive avant la fermeture du compte.",
      "ADB est destiné aux utilisateurs techniques : accès direct à la base de données SQLite, complétude maximale, risque élevé si vous ne savez pas ce que vous faites.",
      "Les données propriétaires Samsung (Body Composition, Stress Score continu) ne passent pas par Health Connect : pour celles-ci, l'export manuel reste toujours nécessaire.",
    ],
    pl: [
      "Wewnętrzny eksport Samsung Health (Ustawienia → Pobierz dane osobowe) to najbardziej kompletna i bezpłatna metoda: generuje pakiet CSV z całą historią.",
      "Health Connect połączony z aplikacją zewnętrzną to jedyna ścieżka z prawdziwą automatyzacją, ale obejmuje tylko typy danych, które Samsung Health zapisuje do HC.",
      "Wniosek RODO jest szerszy niż eksport wewnętrzny (obejmuje metadane i logi), ale wymaga do 30 dni: przydatny jako archiwum przed zamknięciem konta.",
      "ADB jest przeznaczony dla zaawansowanych użytkowników: bezpośredni dostęp do bazy danych SQLite, maksymalna kompletność, wysokie ryzyko dla niewtajemniczonych.",
      "Dane zastrzeżone Samsung (Body Composition, ciągły Stress Score) nie przechodzą przez Health Connect: do ich eksportu zawsze potrzebny jest ręczny eksport.",
    ],
    tr: [
      "Samsung Health dahili dışa aktarımı (Ayarlar → Kişisel verileri indir), tüm geçmişi içeren CSV paketi oluşturan en eksiksiz ve ücretsiz yöntemdir.",
      "Üçüncü taraf uygulamasına bağlı Health Connect, gerçek otomasyonun tek yoludur; ancak yalnızca Samsung Health'in HC'ye yazdığı veri türlerini kapsar.",
      "KVKK/GDPR talebi dahili dışa aktarımdan daha kapsamlıdır (meta veriler ve günlükler dahil), ancak 30 güne kadar sürebilir: hesap kapatılmadan önce arşiv için kullanışlıdır.",
      "ADB teknik kullanıcılar içindir: SQLite veritabanına doğrudan erişim, maksimum eksiksizlik, ne yaptığınızı bilmiyorsanız yüksek risk.",
      "Samsung'a özgü veriler (Body Composition, sürekli Stress Score) Health Connect üzerinden geçmez: bunlar için her zaman manuel dışa aktarım gereklidir.",
    ],
    nl: [
      "De interne export van Samsung Health (Instellingen → Persoonlijke gegevens downloaden) is de meest volledige en gratis methode: genereert een CSV-pakket met je volledige geschiedenis.",
      "Health Connect gekoppeld aan een app van derden is de enige optie met echte automatisering, maar dekt alleen de gegevenstypen die Samsung Health naar HC schrijft.",
      "Het GDPR-verzoek is uitgebreider dan de interne export (inclusief metadata en logboeken), maar duurt tot 30 dagen: handig als archief voor het sluiten van het account.",
      "ADB is voor technische gebruikers: directe toegang tot de SQLite-database, maximale volledigheid, hoog risico als je niet weet wat je doet.",
      "Samsungs eigen gegevens (Body Composition, continue Stress Score) gaan niet via Health Connect: daarvoor is altijd handmatige export nodig.",
    ],
    ja: [
      "Samsung Healthの内部エクスポート（設定 → 個人データをダウンロード）は最も完全で無料の方法です：全履歴を含むCSVパッケージを生成します。",
      "サードパーティアプリに接続されたHealth Connectは、真の自動化が可能な唯一の方法ですが、Samsung HealthがHCに書き込むデータタイプのみをカバーします。",
      "GDPRリクエストは内部エクスポートより広範囲です（メタデータとログを含む）が、最大30日かかります：アカウント閉鎖前のアーカイブとして便利です。",
      "ADBは技術ユーザー向けです：SQLiteデータベースへの直接アクセス、最大限の完全性、操作を理解していない場合は高リスクです。",
      "Samsung独自のデータ（Body Composition、継続的なStress Score）はHealth Connectを経由しません：それらには常に手動エクスポートが必要です。",
    ],
    ko: [
      "Samsung Health의 내부 내보내기(설정 → 개인 데이터 다운로드)는 가장 완전하고 무료인 방법입니다: 전체 기록이 담긴 CSV 패키지를 생성합니다.",
      "서드파티 앱에 연결된 Health Connect는 실제 자동화가 가능한 유일한 방법이지만, Samsung Health가 HC에 기록하는 데이터 유형만 커버합니다.",
      "GDPR 요청은 내부 내보내기보다 광범위합니다(메타데이터 및 로그 포함), 하지만 최대 30일이 걸립니다: 계정 삭제 전 아카이브로 유용합니다.",
      "ADB는 기술 사용자를 위한 것입니다: SQLite 데이터베이스에 직접 접근, 최대 완전성, 무엇을 하는지 모르면 높은 위험.",
      "Samsung 독점 데이터(Body Composition, 지속적인 Stress Score)는 Health Connect를 통과하지 않습니다: 해당 데이터는 항상 수동 내보내기가 필요합니다.",
    ],
  },
  primaryKeyword: {
    it: "backup galaxy watch pc",
    en: "galaxy watch backup pc",
    es: "copia de seguridad galaxy watch pc",
    de: "Galaxy Watch Backup PC",
    pt: "backup galaxy watch pc",
    fr: "sauvegarde galaxy watch pc",
    pl: "kopia zapasowa galaxy watch na pc",
    tr: "galaxy watch yedekleme pc",
    nl: "galaxy watch backup pc",
    ja: "Galaxy Watchバックアップ PC",
    ko: "갤럭시 워치 백업 PC",
  },
  secondaryKeywords: {
    it: [
      "scaricare dati samsung health",
      "esportare dati galaxy watch",
      "samsung health backup",
      "backup galaxy watch senza samsung cloud",
    ],
    en: [
      "download samsung health data",
      "export galaxy watch data",
      "samsung health backup",
      "galaxy watch backup without samsung cloud",
    ],
    pt: [
      "baixar dados samsung health",
      "exportar dados galaxy watch",
      "backup samsung health",
      "backup galaxy watch sem samsung cloud",
    ],
    fr: [
      "télécharger les données samsung health",
      "exporter les données galaxy watch",
      "sauvegarde samsung health",
      "backup galaxy watch sans samsung cloud",
    ],
    pl: [
      "pobieranie danych samsung health",
      "eksport danych galaxy watch",
      "kopia zapasowa samsung health",
      "kopia zapasowa galaxy watch bez samsung cloud",
    ],
    tr: [
      "samsung health verilerini indirme",
      "galaxy watch verilerini dışa aktarma",
      "samsung health yedekleme",
      "samsung cloud olmadan galaxy watch yedekleme",
    ],
    nl: [
      "samsung health gegevens downloaden",
      "galaxy watch gegevens exporteren",
      "samsung health backup",
      "galaxy watch backup zonder samsung cloud",
    ],
    ja: [
      "Samsung Healthデータをダウンロード",
      "Galaxy Watchデータをエクスポート",
      "Samsung Healthバックアップ",
      "Samsung CloudなしでGalaxy Watchをバックアップ",
    ],
    ko: [
      "Samsung Health 데이터 다운로드",
      "갤럭시 워치 데이터 내보내기",
      "Samsung Health 백업",
      "Samsung Cloud 없이 갤럭시 워치 백업",
    ],
  },
  metaDescription: {
    it: "Come fare backup dei dati Galaxy Watch su PC senza Samsung Cloud: esportazione Samsung Health, GDPR data request, dashboard alternative. Guida passo passo 2026.",
    en: "How to back up Galaxy Watch data on PC without Samsung Cloud: Samsung Health export, GDPR data request, alternative dashboards. Step-by-step 2026 guide.",
    es: "Cómo hacer una copia de seguridad del Galaxy Watch en el PC sin Samsung Cloud: exportación de Samsung Health, solicitud GDPR, paneles alternativos. Guía paso a paso 2026.",
    de: "Galaxy Watch Daten auf dem PC sichern ohne Samsung Cloud: Samsung Health Export, DSGVO-Datenanfrage, alternative Dashboards. Schritt-für-Schritt-Anleitung 2026.",
    pt: "Como fazer backup dos dados do Galaxy Watch no PC sem Samsung Cloud: exportação do Samsung Health, solicitação LGPD/GDPR, painéis alternativos. Guia passo a passo 2026.",
    fr: "Comment sauvegarder les données du Galaxy Watch sur PC sans Samsung Cloud : export Samsung Health, demande RGPD, tableaux de bord alternatifs. Guide pas à pas 2026.",
    pl: "Jak wykonać kopię zapasową danych Galaxy Watch na PC bez Samsung Cloud: eksport Samsung Health, wniosek RODO, alternatywne panele. Przewodnik krok po kroku 2026.",
    tr: "Samsung Cloud olmadan Galaxy Watch verilerini PC'ye yedekleme: Samsung Health dışa aktarımı, KVKK/GDPR talebi, alternatif paneller. 2026 adım adım kılavuz.",
    nl: "Hoe maak je een backup van Galaxy Watch-gegevens op je pc zonder Samsung Cloud: Samsung Health export, GDPR-verzoek, alternatieve dashboards. Stapsgewijze handleiding 2026.",
    ja: "Samsung CloudなしでパソコンにGalaxy Watchデータをバックアップする方法：Samsung Healthエクスポート、GDPRデータリクエスト、代替ダッシュボード。2026年ステップバイステップガイド。",
    ko: "Samsung Cloud 없이 PC에 Galaxy Watch 데이터를 백업하는 방법: Samsung Health 내보내기, GDPR 데이터 요청, 대체 대시보드. 2026년 단계별 가이드.",
  },
  hero: {
    kicker: {
      it: "Guida pratica",
      en: "Practical guide",
      es: "Guía práctica",
      de: "Praxisanleitung",
      pt: "Guia prático",
      fr: "Guide pratique",
      pl: "Przewodnik praktyczny",
      tr: "Pratik Kılavuz",
      nl: "Praktische gids",
      ja: "実践ガイド",
      ko: "실용 가이드",
    },
    title: {
      it: "Backup Galaxy Watch su PC senza Samsung Cloud",
      en: "How to back up Galaxy Watch data on PC without Samsung Cloud",
      es: "Cómo hacer una copia de seguridad del Galaxy Watch en el PC sin Samsung Cloud",
      de: "Galaxy Watch auf dem PC sichern ohne Samsung Cloud",
      pt: "Como fazer backup do Galaxy Watch no PC sem Samsung Cloud",
      fr: "Sauvegarder les données du Galaxy Watch sur PC sans Samsung Cloud",
      pl: "Kopia zapasowa Galaxy Watch na PC bez Samsung Cloud",
      tr: "Samsung Cloud Olmadan Galaxy Watch Verilerini PC'ye Yedekleme",
      nl: "Galaxy Watch-gegevens op pc opslaan zonder Samsung Cloud",
      ja: "Samsung CloudなしでパソコンにGalaxy Watchデータをバックアップする方法",
      ko: "Samsung Cloud 없이 PC에 Galaxy Watch 데이터를 백업하는 방법",
    },
    subtitle: {
      it: "Quattro vie reali per portare passi, BPM, sonno e allenamenti del Galaxy Watch fuori da Samsung Health. Pro e contro di ognuna.",
      en: "Four real ways to get steps, HR, sleep and workouts off your Galaxy Watch and outside Samsung Health. Pros and cons of each.",
      es: "Cuatro formas reales de sacar pasos, frecuencia cardíaca, sueño y entrenamientos del Galaxy Watch fuera de Samsung Health. Ventajas y desventajas de cada una.",
      de: "Vier echte Wege, um Schritte, Herzfrequenz, Schlaf und Trainings des Galaxy Watch aus Samsung Health herauszubekommen. Vor- und Nachteile jeder Option.",
      pt: "Quatro formas reais de exportar passos, frequência cardíaca, sono e treinos do seu Galaxy Watch para fora do Samsung Health. Prós e contras de cada uma.",
      fr: "Quatre méthodes concrètes pour extraire pas, fréquence cardiaque, sommeil et séances d'entraînement du Galaxy Watch hors de Samsung Health. Avantages et inconvénients de chacune.",
      pl: "Cztery realne sposoby na wyeksportowanie kroków, tętna, snu i treningów z Galaxy Watch poza Samsung Health. Zalety i wady każdego z nich.",
      tr: "Galaxy Watch'tan adım, nabız, uyku ve antrenman verilerini Samsung Health dışında almak için dört gerçekçi yol. Her birinin artıları ve eksileri.",
      nl: "Vier echte manieren om stappen, hartslag, slaap en trainingen van je Galaxy Watch buiten Samsung Health te krijgen. Voor- en nadelen van elk.",
      ja: "Galaxy WatchからSamsung Health外へ歩数、心拍数、睡眠、ワークアウトを取り出す4つの実践的な方法。それぞれのメリットとデメリット。",
      ko: "Galaxy Watch에서 Samsung Health 외부로 걸음 수, 심박수, 수면, 운동 데이터를 가져오는 4가지 실제 방법. 각각의 장단점.",
    },
  },
  body: [
    {
      type: "paragraph",
      text: {
        it: "Ci sono quattro modi reali per fare backup dei dati Galaxy Watch su PC, e scegliere quello giusto dipende da un solo fattore: hai bisogno di un archivio storico completo o di un flusso continuo automatizzato? Per archivio storico, l'export interno di Samsung Health genera un pacchetto CSV completo in pochi passaggi. Per flusso continuo, Health Connect collegato a un'app terza è l'unica strada che non richiede ripetizioni manuali.",
        en: "There are four real ways to back up Galaxy Watch data to PC, and choosing the right one depends on a single factor: do you need a complete historical archive or a continuous automated flow? For a historical archive, Samsung Health's internal export generates a complete CSV package in a few steps. For a continuous flow, Health Connect linked to a third-party app is the only path that doesn't require manual repetition.",
        es: "Hay cuatro formas reales de hacer una copia de seguridad de los datos del Galaxy Watch en el PC, y elegir la correcta depende de un solo factor: ¿necesitas un archivo histórico completo o un flujo continuo automatizado? Para un archivo histórico, la exportación interna de Samsung Health genera un paquete CSV completo en pocos pasos. Para un flujo continuo, Health Connect vinculado a una app de terceros es la única opción que no requiere repeticiones manuales.",
        de: "Es gibt vier echte Möglichkeiten, Galaxy Watch-Daten auf dem PC zu sichern, und die Wahl der richtigen hängt von einem einzigen Faktor ab: Benötigst du ein vollständiges historisches Archiv oder einen kontinuierlichen automatisierten Datenstrom? Für ein historisches Archiv erstellt der interne Samsung Health-Export ein vollständiges CSV-Paket in wenigen Schritten. Für einen kontinuierlichen Datenstrom ist Health Connect, verbunden mit einer Drittanbieter-App, der einzige Weg, der keine manuellen Wiederholungen erfordert.",
        pt: "Existem quatro formas reais de fazer backup dos dados do Galaxy Watch no PC, e escolher a certa depende de um único fator: você precisa de um arquivo histórico completo ou de um fluxo contínuo automatizado? Para um arquivo histórico, a exportação interna do Samsung Health gera um pacote CSV completo em poucos passos. Para um fluxo contínuo, o Health Connect vinculado a um app de terceiros é o único caminho que não exige repetições manuais.",
        fr: "Il existe quatre façons concrètes de sauvegarder les données du Galaxy Watch sur PC, et choisir la bonne dépend d'un seul facteur : avez-vous besoin d'une archive historique complète ou d'un flux continu automatisé ? Pour une archive historique, l'export interne de Samsung Health génère un package CSV complet en quelques étapes. Pour un flux continu, Health Connect relié à une application tierce est la seule voie qui ne nécessite pas de répétitions manuelles.",
        pl: "Istnieją cztery realne sposoby na wykonanie kopii zapasowej danych Galaxy Watch na PC, a wybór właściwego zależy od jednego czynnika: potrzebujesz kompletnego archiwum historycznego czy ciągłego zautomatyzowanego przepływu? W przypadku archiwum historycznego wewnętrzny eksport Samsung Health generuje kompletny pakiet CSV w kilku krokach. W przypadku ciągłego przepływu Health Connect połączony z zewnętrzną aplikacją to jedyna ścieżka, która nie wymaga ręcznego powtarzania.",
        tr: "Galaxy Watch verilerini PC'ye yedeklemenin dört gerçek yolu vardır ve doğru olanı seçmek tek bir faktöre bağlıdır: eksiksiz bir geçmiş arşivi mi yoksa sürekli otomatik akış mı istiyorsunuz? Geçmiş arşivi için Samsung Health dahili dışa aktarımı birkaç adımda eksiksiz bir CSV paketi oluşturur. Sürekli akış için üçüncü taraf uygulamasına bağlı Health Connect, manuel tekrar gerektirmeyen tek yoldur.",
        nl: "Er zijn vier echte manieren om Galaxy Watch-gegevens op de pc te back-uppen, en de juiste keuze hangt af van één factor: heb je een volledig historisch archief nodig of een continu geautomatiseerde stroom? Voor een historisch archief genereert de interne export van Samsung Health in een paar stappen een compleet CSV-pakket. Voor een continue stroom is Health Connect gekoppeld aan een app van derden de enige weg die geen handmatige herhaling vereist.",
        ja: "Galaxy WatchのデータをPCにバックアップする方法は4つあり、適切な方法の選択は一つの要素に依存します：完全な履歴アーカイブが必要か、継続的な自動フローが必要か？履歴アーカイブの場合、Samsung Healthの内部エクスポートで数ステップで完全なCSVパッケージが生成されます。継続的なフローの場合、サードパーティアプリに接続されたHealth Connectが手動の繰り返しを必要としない唯一の方法です。",
        ko: "Galaxy Watch 데이터를 PC에 백업하는 방법은 4가지가 있으며, 올바른 방법 선택은 하나의 요소에 달려 있습니다: 완전한 역사적 아카이브가 필요한가, 아니면 지속적인 자동화 흐름이 필요한가? 역사적 아카이브의 경우 Samsung Health의 내부 내보내기가 몇 단계만으로 완전한 CSV 패키지를 생성합니다. 지속적인 흐름의 경우 서드파티 앱에 연결된 Health Connect가 수동 반복이 필요 없는 유일한 방법입니다.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Opzione 1: esportazione interna di Samsung Health",
        en: "Option 1: Samsung Health's internal export",
        es: "Opción 1: exportación interna de Samsung Health",
        de: "Option 1: Interner Export von Samsung Health",
        pt: "Opção 1: exportação interna do Samsung Health",
        fr: "Option 1 : export interne de Samsung Health",
        pl: "Opcja 1: wewnętrzny eksport Samsung Health",
        tr: "Seçenek 1: Samsung Health dahili dışa aktarımı",
        nl: "Optie 1: interne export van Samsung Health",
        ja: "オプション1：Samsung Healthの内部エクスポート",
        ko: "옵션 1: Samsung Health의 내부 내보내기",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Samsung Health (Android) ha una funzione di esportazione integrata che genera un pacchetto di file con tutti i tuoi dati raw. Non è promossa nei tutorial, ma è lì da anni.",
        en: "Samsung Health (Android) has a built-in export function generating a package of files with all your raw data. It's not promoted in tutorials, but it's been there for years.",
        es: "Samsung Health (Android) tiene una función de exportación integrada que genera un paquete de archivos con todos tus datos en bruto. No aparece destacada en los tutoriales, pero lleva años disponible.",
        de: "Samsung Health (Android) verfügt über eine integrierte Exportfunktion, die ein Dateipaket mit allen deinen Rohdaten erstellt. Sie wird in Tutorials nicht beworben, existiert aber schon seit Jahren.",
        pt: "O Samsung Health (Android) possui uma função de exportação integrada que gera um pacote de arquivos com todos os seus dados brutos. Ela não aparece em destaque nos tutoriais, mas existe há anos.",
        fr: "Samsung Health (Android) dispose d'une fonction d'export intégrée qui génère un package de fichiers contenant toutes vos données brutes. Elle n'est pas mise en avant dans les tutoriels, mais elle existe depuis des années.",
        pl: "Samsung Health (Android) ma wbudowaną funkcję eksportu, która generuje pakiet plików ze wszystkimi surowymi danymi. Nie jest promowana w tutorialach, ale istnieje od lat.",
        tr: "Samsung Health (Android), tüm ham verilerinizi içeren bir dosya paketi oluşturan yerleşik dışa aktarma işlevine sahiptir. Eğitimlerde öne çıkarılmaz, ancak yıllardır oradadır.",
        nl: "Samsung Health (Android) heeft een ingebouwde exportfunctie die een pakket bestanden met al je ruwe gegevens genereert. Het wordt niet gepromoot in tutorials, maar bestaat al jaren.",
        ja: "Samsung Health（Android）にはすべての生データを含むファイルパッケージを生成する組み込みエクスポート機能があります。チュートリアルでは宣伝されていませんが、何年も前から存在しています。",
        ko: "Samsung Health(Android)에는 모든 원시 데이터가 담긴 파일 패키지를 생성하는 내장 내보내기 기능이 있습니다. 튜토리얼에서 홍보되지 않지만 수년 전부터 존재해 왔습니다.",
      },
    },
    {
      type: "list",
      ordered: true,
      items: {
        it: [
          "Apri Samsung Health sul telefono.",
          "Tocca l'icona ☰ menu in alto a sinistra → Impostazioni.",
          "Scorri fino a 'Scarica dati personali' (in inglese 'Download personal data').",
          "Conferma con password Samsung Account.",
          "Attendi (può richiedere 1–24 ore se hai anni di dati). Riceverai un ZIP via email.",
        ],
        en: [
          "Open Samsung Health on the phone.",
          "Tap ☰ menu top-left → Settings.",
          "Scroll to 'Download personal data'.",
          "Confirm with Samsung Account password.",
          "Wait (can take 1–24 hours if you have years of data). You'll receive a ZIP via email.",
        ],
        es: [
          "Abre Samsung Health en el teléfono.",
          "Toca el icono ☰ del menú arriba a la izquierda → Ajustes.",
          "Desplázate hasta 'Descargar datos personales' (en inglés 'Download personal data').",
          "Confirma con la contraseña de tu Samsung Account.",
          "Espera (puede tardar entre 1 y 24 horas si tienes años de datos). Recibirás un ZIP por correo electrónico.",
        ],
        de: [
          "Öffne Samsung Health auf dem Telefon.",
          "Tippe auf das ☰-Menü oben links, dann auf Einstellungen.",
          "Scrolle zu 'Persönliche Daten herunterladen'.",
          "Bestätige mit dem Samsung Account-Passwort.",
          "Warte (kann 1–24 Stunden dauern, wenn du jahrelange Daten hast). Du erhältst ein ZIP per E-Mail.",
        ],
        pt: [
          "Abra o Samsung Health no celular.",
          "Toque no ícone ☰ do menu no canto superior esquerdo, depois em Configurações.",
          "Role até 'Baixar dados pessoais'.",
          "Confirme com a senha do Samsung Account.",
          "Aguarde (pode levar de 1 a 24 horas se você tiver anos de dados). Você receberá um ZIP por e-mail.",
        ],
        fr: [
          "Ouvrez Samsung Health sur le téléphone.",
          "Appuyez sur l'icône ☰ du menu en haut à gauche, puis sur Paramètres.",
          "Faites défiler jusqu'à 'Télécharger mes données personnelles'.",
          "Confirmez avec le mot de passe du Samsung Account.",
          "Patientez (cela peut prendre de 1 à 24 heures si vous avez des années de données). Vous recevrez un ZIP par e-mail.",
        ],
        pl: [
          "Otwórz Samsung Health na telefonie.",
          "Dotknij ikony ☰ menu w lewym górnym rogu → Ustawienia.",
          "Przewiń do 'Pobierz dane osobowe'.",
          "Potwierdź hasłem do Samsung Account.",
          "Poczekaj (może potrwać 1-24 godziny przy wieloletnich danych). Otrzymasz ZIP na e-mail.",
        ],
        tr: [
          "Telefonda Samsung Health'i açın.",
          "Sol üstteki ☰ menü simgesine dokunun → Ayarlar.",
          "'Kişisel verileri indir' seçeneğine gidin.",
          "Samsung Account şifrenizle onaylayın.",
          "Bekleyin (yıllarca veri varsa 1-24 saat sürebilir). E-postayla bir ZIP alacaksınız.",
        ],
        nl: [
          "Open Samsung Health op je telefoon.",
          "Tik op het ☰ menu linksboven → Instellingen.",
          "Scroll naar 'Persoonlijke gegevens downloaden'.",
          "Bevestig met je Samsung Account-wachtwoord.",
          "Wacht (kan 1-24 uur duren als je jaren aan gegevens hebt). Je ontvangt een ZIP via e-mail.",
        ],
        ja: [
          "スマートフォンでSamsung Healthを開きます。",
          "左上の☰メニューをタップ → 設定。",
          "「個人データをダウンロード」までスクロールします。",
          "Samsung Accountのパスワードで確認します。",
          "待ちます（数年分のデータがある場合は1〜24時間かかることがあります）。ZIPファイルがメールで届きます。",
        ],
        ko: [
          "휴대폰에서 Samsung Health를 엽니다.",
          "왼쪽 상단의 ☰ 메뉴를 탭 → 설정.",
          "'개인 데이터 다운로드'까지 스크롤합니다.",
          "Samsung Account 비밀번호로 확인합니다.",
          "기다립니다(수년치 데이터가 있으면 1~24시간이 걸릴 수 있습니다). 이메일로 ZIP 파일을 받게 됩니다.",
        ],
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Il pacchetto contiene file CSV per ogni tipo di dato (steps_*.csv, heart_rate_*.csv, sleep_*.csv, exercise_*.csv, etc.) più file binari per dati ad alta frequenza come HR continuo durante allenamenti. È completo ma verboso. Per analizzare in Excel/Numbers basta importare i CSV; per visualizzazioni più sofisticate puoi usare Python pandas o R.",
        en: "The package contains CSV files for each data type (steps_*.csv, heart_rate_*.csv, sleep_*.csv, exercise_*.csv, etc.) plus binary files for high-frequency data like continuous HR during workouts. It's complete but verbose. To analyze in Excel/Numbers just import the CSVs; for more sophisticated visualizations use Python pandas or R.",
        es: "El paquete contiene archivos CSV para cada tipo de dato (steps_*.csv, heart_rate_*.csv, sleep_*.csv, exercise_*.csv, etc.) más archivos binarios para datos de alta frecuencia como la frecuencia cardíaca continua durante los entrenamientos. Es completo, aunque voluminoso. Para analizarlo en Excel o Numbers basta con importar los CSV; para visualizaciones más avanzadas puedes usar Python pandas o R.",
        de: "Das Paket enthält CSV-Dateien für jeden Datentyp (steps_*.csv, heart_rate_*.csv, sleep_*.csv, exercise_*.csv usw.) sowie Binärdateien für hochfrequente Daten wie die kontinuierliche Herzfrequenz während Trainings. Es ist vollständig, aber umfangreich. Zur Analyse in Excel/Numbers einfach die CSVs importieren; für anspruchsvollere Visualisierungen kannst du Python pandas oder R verwenden.",
        pt: "O pacote contém arquivos CSV para cada tipo de dado (steps_*.csv, heart_rate_*.csv, sleep_*.csv, exercise_*.csv, etc.) além de arquivos binários para dados de alta frequência, como a frequência cardíaca contínua durante treinos. É completo, mas volumoso. Para analisar no Excel/Numbers, basta importar os CSVs; para visualizações mais sofisticadas, use Python pandas ou R.",
        fr: "Le package contient des fichiers CSV pour chaque type de données (steps_*.csv, heart_rate_*.csv, sleep_*.csv, exercise_*.csv, etc.) ainsi que des fichiers binaires pour les données haute fréquence comme la fréquence cardiaque continue pendant les séances d'entraînement. Il est complet mais volumineux. Pour analyser dans Excel/Numbers, importez simplement les CSV ; pour des visualisations plus poussées, utilisez Python pandas ou R.",
        pl: "Pakiet zawiera pliki CSV dla każdego typu danych (steps_*.csv, heart_rate_*.csv, sleep_*.csv, exercise_*.csv itd.) oraz pliki binarne dla danych wysokiej częstotliwości, takich jak ciągłe tętno podczas treningów. Jest kompletny, ale obszerny. Do analizy w Excel/Numbers wystarczy zaimportować CSV; do bardziej zaawansowanych wizualizacji możesz użyć Python pandas lub R.",
        tr: "Paket her veri türü için CSV dosyaları (steps_*.csv, heart_rate_*.csv, sleep_*.csv, exercise_*.csv vb.) ve antrenmanlar sırasındaki sürekli nabız gibi yüksek frekanslı veriler için ikili dosyalar içerir. Eksiksizdir ama kapsamlıdır. Excel/Numbers'da analiz için CSV'leri içe aktarmanız yeterlidir; daha gelişmiş görselleştirmeler için Python pandas veya R kullanın.",
        nl: "Het pakket bevat CSV-bestanden voor elk gegevenstype (steps_*.csv, heart_rate_*.csv, sleep_*.csv, exercise_*.csv, etc.) plus binaire bestanden voor hoogfrequente gegevens zoals continue hartslag tijdens trainingen. Het is compleet maar uitgebreid. Om in Excel/Numbers te analyseren importeer je gewoon de CSV-bestanden; voor geavanceerdere visualisaties gebruik je Python pandas of R.",
        ja: "パッケージには各データタイプのCSVファイル（steps_*.csv、heart_rate_*.csv、sleep_*.csv、exercise_*.csv等）と、ワークアウト中の継続的な心拍数などの高頻度データ用のバイナリファイルが含まれています。完全ですが量が多いです。Excel/Numbersで分析するにはCSVをインポートするだけです。より高度な可視化にはPython pandasまたはRを使用してください。",
        ko: "패키지에는 각 데이터 유형의 CSV 파일(steps_*.csv, heart_rate_*.csv, sleep_*.csv, exercise_*.csv 등)과 운동 중 지속적인 심박수 등 고주파 데이터용 바이너리 파일이 포함되어 있습니다. 완전하지만 용량이 큽니다. Excel/Numbers에서 분석하려면 CSV를 가져오기만 하면 됩니다. 더 정교한 시각화에는 Python pandas나 R을 사용하세요.",
      },
    },
    {
      type: "callout",
      variant: "tip",
      title: {
        it: "Pro/contro Opzione 1",
        en: "Pros/cons Option 1",
        es: "Ventajas/desventajas Opción 1",
        de: "Vor-/Nachteile Option 1",
        pt: "Prós/contras Opção 1",
        fr: "Avantages/inconvénients Option 1",
        pl: "Zalety/wady Opcja 1",
        tr: "Artılar/eksiler Seçenek 1",
        nl: "Voordelen/nadelen Optie 1",
        ja: "メリット/デメリット オプション1",
        ko: "장단점 옵션 1",
      },
      body: {
        it: "**Pro**: completo, gratuito, formato standard. **Contro**: manuale (devi ripeterlo periodicamente), nessuna automazione, nessuna interfaccia di analisi inclusa.",
        en: "**Pros**: complete, free, standard format. **Cons**: manual (must repeat periodically), no automation, no analysis UI included.",
        es: "**Ventajas**: completo, gratuito, formato estándar. **Desventajas**: manual (debes repetirlo periódicamente), sin automatización, sin interfaz de análisis incluida.",
        de: "**Vorteile**: vollständig, kostenlos, Standardformat. **Nachteile**: manuell (muss regelmäßig wiederholt werden), keine Automatisierung, keine Analyseoberfläche enthalten.",
        pt: "**Prós**: completo, gratuito, formato padrão. **Contras**: manual (deve ser repetido periodicamente), sem automação, sem interface de análise incluída.",
        fr: "**Avantages** : complet, gratuit, format standard. **Inconvénients** : manuel (à répéter périodiquement), aucune automatisation, aucune interface d'analyse incluse.",
        pl: "**Zalety**: kompletny, bezpłatny, standardowy format. **Wady**: ręczny (trzeba powtarzać okresowo), brak automatyzacji, brak interfejsu analizy.",
        tr: "**Artılar**: eksiksiz, ücretsiz, standart format. **Eksiler**: manuel (periyodik olarak tekrarlanması gerekir), otomasyon yok, analiz arayüzü yok.",
        nl: "**Voordelen**: volledig, gratis, standaardformaat. **Nadelen**: handmatig (moet periodiek herhaald worden), geen automatisering, geen analyse-interface inbegrepen.",
        ja: "**メリット**: 完全、無料、標準フォーマット。**デメリット**: 手動（定期的に繰り返す必要あり）、自動化なし、分析UIなし。",
        ko: "**장점**: 완전함, 무료, 표준 형식. **단점**: 수동(주기적으로 반복해야 함), 자동화 없음, 분석 UI 없음.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Opzione 2: richiesta GDPR diritto di accesso",
        en: "Option 2: GDPR right-of-access request",
        es: "Opción 2: solicitud GDPR de derecho de acceso",
        de: "Option 2: DSGVO-Auskunftsersuchen",
        pt: "Opção 2: solicitação de acesso LGPD/GDPR",
        fr: "Option 2 : demande d'accès RGPD",
        pl: "Opcja 2: wniosek RODO o dostęp do danych",
        tr: "Seçenek 2: KVKK/GDPR veri erişim talebi",
        nl: "Optie 2: AVG-verzoek om recht van inzage",
        ja: "オプション2：GDPRアクセス権リクエスト",
        ko: "옵션 2: GDPR 접근권 요청",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Se sei in UE, puoi scrivere a Samsung chiedendo formalmente tutti i dati raccolti su di te (art. 15 e 20 GDPR). Per dati salute il punto di contatto è privacy.eu@samsung.com (o il modulo dedicato su privacy.samsung.com/it/privacy-rights). Hanno 30 giorni per rispondere, gratuitamente. Il dataset che ricevi è tipicamente più ampio di quello dell'esportazione interna (include anche metadati, log di accesso, info account).",
        en: "If you're in the EU, you can formally write to Samsung asking for all data collected about you (GDPR art. 15 and 20). For health data the contact is privacy.eu@samsung.com (or the dedicated form at privacy.samsung.com/en/privacy-rights). They have 30 days to respond, free of charge. The dataset you receive is typically broader than the internal export (includes metadata, access logs, account info).",
        es: "Si estás en la UE, puedes escribir formalmente a Samsung solicitando todos los datos recopilados sobre ti (RGPD art. 15 y 20). Para datos de salud el contacto es privacy.eu@samsung.com (o el formulario dedicado en privacy.samsung.com/en/privacy-rights). Tienen 30 días para responder, de forma gratuita. El conjunto de datos que recibes es normalmente más amplio que el de la exportación interna (incluye metadatos, registros de acceso e información de la cuenta).",
        de: "Wenn du in der EU bist, kannst du Samsung formell um alle über dich gesammelten Daten bitten (DSGVO Art. 15 und 20). Für Gesundheitsdaten ist der Ansprechpartner privacy.eu@samsung.com (oder das dedizierte Formular auf privacy.samsung.com/en/privacy-rights). Sie haben 30 Tage Zeit zu antworten, kostenlos. Der erhaltene Datensatz ist typischerweise umfangreicher als der interne Export (enthält auch Metadaten, Zugriffsprotokolle, Kontoinformationen).",
        pt: "Se você estiver na UE ou em países com legislação equivalente, pode escrever formalmente à Samsung solicitando todos os dados coletados sobre você (art. 15 e 20 do GDPR). Para dados de saúde, o contato é privacy.eu@samsung.com (ou o formulário dedicado em privacy.samsung.com/en/privacy-rights). Eles têm 30 dias para responder, gratuitamente. O conjunto de dados recebido é geralmente mais amplo do que a exportação interna (inclui metadados, logs de acesso e informações da conta).",
        fr: "Si vous êtes dans l'UE, vous pouvez écrire formellement à Samsung pour demander toutes les données collectées vous concernant (RGPD art. 15 et 20). Pour les données de santé, le contact est privacy.eu@samsung.com (ou le formulaire dédié sur privacy.samsung.com/en/privacy-rights). Ils disposent de 30 jours pour répondre, gratuitement. Le jeu de données reçu est généralement plus large que l'export interne (inclut aussi les métadonnées, les journaux d'accès et les informations du compte).",
        pl: "Jeśli przebywasz w UE, możesz formalnie napisać do Samsunga z prośbą o wszystkie zebrane na Twój temat dane (RODO art. 15 i 20). W przypadku danych zdrowotnych punktem kontaktowym jest privacy.eu@samsung.com (lub dedykowany formularz na privacy.samsung.com/en/privacy-rights). Mają 30 dni na odpowiedź, bezpłatnie. Otrzymany zestaw danych jest zazwyczaj szerszy niż eksport wewnętrzny (obejmuje metadane, logi dostępu, informacje o koncie).",
        tr: "AB'deyseniz, hakkınızda toplanan tüm veriler için Samsung'a resmi olarak yazabilirsiniz (GDPR mad. 15 ve 20). Sağlık verileri için iletişim adresi privacy.eu@samsung.com'dur (veya privacy.samsung.com/en/privacy-rights adresindeki özel form). 30 gün içinde ücretsiz yanıt vermek zorundadırlar. Aldığınız veri kümesi genellikle dahili dışa aktarımdan daha geniştir (meta veriler, erişim günlükleri ve hesap bilgilerini içerir).",
        nl: "Als je in de EU bent, kun je Samsung formeel schrijven om alle over jou verzamelde gegevens op te vragen (AVG art. 15 en 20). Voor gezondheidsgegevens is het contactadres privacy.eu@samsung.com (of het speciaal formulier op privacy.samsung.com/en/privacy-rights). Ze hebben 30 dagen om gratis te antwoorden. De dataset die je ontvangt is doorgaans uitgebreider dan de interne export (bevat ook metadata, toegangslogboeken en accountgegevens).",
        ja: "EUに居住している場合、あなたについて収集されたすべてのデータをSamsungに正式に要求することができます（GDPR第15条および第20条）。健康データの連絡先はprivacy.eu@samsung.com（またはprivacy.samsung.com/en/privacy-rightsの専用フォーム）です。30日以内に無料で回答する義務があります。受け取るデータセットは通常、内部エクスポートよりも広範囲です（メタデータ、アクセスログ、アカウント情報も含む）。",
        ko: "EU에 거주하는 경우 Samsung에 귀하에 대해 수집된 모든 데이터를 공식적으로 요청할 수 있습니다(GDPR 제15조 및 제20조). 건강 데이터의 연락처는 privacy.eu@samsung.com입니다(또는 privacy.samsung.com/en/privacy-rights의 전용 양식). 30일 이내에 무료로 응답해야 합니다. 받는 데이터세트는 일반적으로 내부 내보내기보다 더 광범위합니다(메타데이터, 접근 로그, 계정 정보 포함).",
      },
    },
    {
      type: "callout",
      variant: "info",
      title: {
        it: "Quando vale la richiesta GDPR",
        en: "When the GDPR request is worth it",
        es: "Cuándo vale la pena la solicitud GDPR",
        de: "Wann das DSGVO-Ersuchen sinnvoll ist",
        pt: "Quando vale a pena a solicitação LGPD/GDPR",
        fr: "Quand la demande RGPD vaut la peine",
        pl: "Kiedy warto złożyć wniosek RODO",
        tr: "KVKK/GDPR talebi ne zaman değer",
        nl: "Wanneer het AVG-verzoek de moeite waard is",
        ja: "GDPRリクエストが有効な場合",
        ko: "GDPR 요청이 가치 있는 경우",
      },
      body: {
        it: "Soprattutto se stai per chiudere l'account Samsung e vuoi una copia completa per archivio. Per backup ricorrente è scomoda (un mese di attesa). Per controllo totale è insostituibile.",
        en: "Especially if you're about to close your Samsung account and want a full copy for archive. For recurring backup it's clunky (a month of waiting). For total control it's irreplaceable.",
        es: "Especialmente si vas a cerrar tu cuenta Samsung y quieres una copia completa para el archivo. Para copias de seguridad recurrentes resulta incómoda (un mes de espera). Para un control total, es insustituible.",
        de: "Besonders wenn du dein Samsung-Konto schließen möchtest und eine vollständige Kopie für das Archiv willst. Für regelmäßige Backups ist es umständlich (ein Monat Wartezeit). Für totale Kontrolle ist es unersetzlich.",
        pt: "Especialmente se você está prestes a encerrar sua conta Samsung e quer uma cópia completa para arquivo. Para backup recorrente é incômoda (um mês de espera). Para controle total, é insubstituível.",
        fr: "Surtout si vous êtes sur le point de fermer votre compte Samsung et souhaitez une copie complète pour archive. Pour un backup récurrent, c'est peu pratique (un mois d'attente). Pour un contrôle total, elle est irremplaçable.",
        pl: "Przede wszystkim jeśli zamierzasz zamknąć konto Samsung i chcesz pełną kopię na archiwum. Do cyklicznego tworzenia kopii zapasowych jest niewygodny (miesiąc oczekiwania). Dla pełnej kontroli jest niezastąpiony.",
        tr: "Özellikle Samsung hesabınızı kapatmak üzereyseniz ve arşiv için tam bir kopya istiyorsanız. Düzenli yedekleme için kullanışsızdır (bir ay bekleme). Tam kontrol için vazgeçilmezdir.",
        nl: "Vooral als je je Samsung-account wilt sluiten en een volledige kopie voor het archief wilt. Voor regelmatige backups is het omslachtig (een maand wachten). Voor totale controle is het onvervangbaar.",
        ja: "特にSamsungアカウントを閉鎖しようとしていて、アーカイブ用の完全なコピーが必要な場合に最適です。定期的なバックアップには不向きです（1ヶ月の待機）。完全なコントロールには欠かせません。",
        ko: "특히 Samsung 계정을 닫으려 하고 아카이브용 전체 복사본이 필요한 경우에 특히 유용합니다. 정기적인 백업에는 불편합니다(한 달 대기). 완전한 제어를 위해서는 대체 불가합니다.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Opzione 3: leggere via Health Connect su app terza",
        en: "Option 3: read via Health Connect on a third-party app",
        es: "Opción 3: leer a través de Health Connect con una app de terceros",
        de: "Option 3: Daten über Health Connect mit einer Drittanbieter-App lesen",
        pt: "Opção 3: ler via Health Connect com um app de terceiros",
        fr: "Option 3 : lecture via Health Connect avec une application tierce",
        pl: "Opcja 3: odczyt przez Health Connect w aplikacji zewnętrznej",
        tr: "Seçenek 3: üçüncü taraf uygulamayla Health Connect üzerinden okuma",
        nl: "Optie 3: lezen via Health Connect met een app van derden",
        ja: "オプション3：サードパーティアプリでHealth Connect経由で読み取る",
        ko: "옵션 3: 서드파티 앱으로 Health Connect를 통해 읽기",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Dal 2024 Samsung Health scrive su Health Connect, che è la API ufficiale Android. Puoi installare un'app terza che legga via Health Connect ed esponga i dati nel formato che vuoi: dashboard web, file JSON, sync con altri ecosistemi. È il modo più automatizzato.",
        en: "Since 2024 Samsung Health writes to Health Connect, Android's official API. You can install a third-party app reading via Health Connect and exposing data in the format you want: web dashboard, JSON files, sync with other ecosystems. It's the most automated way.",
        es: "Desde 2024, Samsung Health escribe en Health Connect, la API oficial de Android. Puedes instalar una app de terceros que lea a través de Health Connect y exponga los datos en el formato que prefieras: panel web, archivos JSON, sincronización con otros ecosistemas. Es la opción más automatizada.",
        de: "Seit 2024 schreibt Samsung Health in Health Connect, Androids offizielle API. Du kannst eine Drittanbieter-App installieren, die über Health Connect liest und die Daten in dem Format bereitstellt, das du willst: Web-Dashboard, JSON-Dateien, Synchronisierung mit anderen Ökosystemen. Das ist der automatisierteste Weg.",
        pt: "Desde 2024, o Samsung Health grava no Health Connect, a API oficial do Android. Você pode instalar um app de terceiros que leia via Health Connect e exponha os dados no formato que preferir: painel web, arquivos JSON, sincronização com outros ecossistemas. É a forma mais automatizada.",
        fr: "Depuis 2024, Samsung Health écrit dans Health Connect, l'API officielle d'Android. Vous pouvez installer une application tierce qui lit via Health Connect et expose les données dans le format souhaité : tableau de bord web, fichiers JSON, synchronisation avec d'autres écosystèmes. C'est la méthode la plus automatisée.",
        pl: "Od 2024 roku Samsung Health zapisuje do Health Connect, oficjalnego API Androida. Możesz zainstalować zewnętrzną aplikację odczytującą przez Health Connect i udostępniającą dane w wybranym formacie: panel web, pliki JSON, synchronizacja z innymi ekosystemami. To najbardziej zautomatyzowany sposób.",
        tr: "2024'ten beri Samsung Health, Android'in resmi API'si olan Health Connect'e yazmaktadır. Health Connect üzerinden okuyan ve verileri istediğiniz formatta sunan bir üçüncü taraf uygulaması kurabilirsiniz: web paneli, JSON dosyaları, diğer ekosistemlerle senkronizasyon. Bu en otomatik yöntemdir.",
        nl: "Sinds 2024 schrijft Samsung Health naar Health Connect, de officiële Android API. Je kunt een app van derden installeren die via Health Connect leest en de gegevens weergeeft in het formaat dat je wilt: web-dashboard, JSON-bestanden, synchroniseren met andere ecosystemen. Dit is de meest geautomatiseerde methode.",
        ja: "2024年以降、Samsung HealthはAndroidの公式APIであるHealth Connectに書き込んでいます。Health Connect経由で読み取り、希望するフォーマットでデータを提供するサードパーティアプリをインストールできます：Webダッシュボード、JSONファイル、他のエコシステムとの同期。これが最も自動化された方法です。",
        ko: "2024년부터 Samsung Health는 Android 공식 API인 Health Connect에 데이터를 기록합니다. Health Connect를 통해 읽고 원하는 형식으로 데이터를 제공하는 서드파티 앱을 설치할 수 있습니다: 웹 대시보드, JSON 파일, 다른 에코시스템과의 동기화. 이것이 가장 자동화된 방법입니다.",
      },
    },
    {
      type: "list",
      items: {
        it: [
          "**Per dashboard web**: FitMesh Sync legge da Health Connect e mostra tutto su una web app accessibile da PC.",
          "**Per export tecnico**: app come Health Connect Toolbox (open source) producono dump JSON manuali.",
          "**Per analytics avanzati**: app come Welltory o Bearable leggono HC e fanno coaching/journaling.",
        ],
        en: [
          "**For web dashboard**: FitMesh Sync reads from Health Connect and shows everything on a PC-accessible web app.",
          "**For technical export**: apps like Health Connect Toolbox (open source) produce manual JSON dumps.",
          "**For advanced analytics**: apps like Welltory or Bearable read HC and provide coaching/journaling.",
        ],
        es: [
          "**Para panel web**: FitMesh Sync lee desde Health Connect y muestra todo en una aplicación web accesible desde el PC.",
          "**Para exportación técnica**: apps como Health Connect Toolbox (código abierto) generan volcados JSON manuales.",
          "**Para analíticas avanzadas**: apps como Welltory o Bearable leen HC y ofrecen seguimiento y diario de bienestar.",
        ],
        de: [
          "**Für Web-Dashboard**: FitMesh Sync liest aus Health Connect und zeigt alles in einer vom PC zugänglichen Web-App.",
          "**Für technischen Export**: Apps wie Health Connect Toolbox (Open Source) erstellen manuelle JSON-Dumps.",
          "**Für erweiterte Analysen**: Apps wie Welltory oder Bearable lesen HC und bieten Coaching und Journaling.",
        ],
        pt: [
          "**Para painel web**: FitMesh Sync lê do Health Connect e mostra tudo em um app web acessível pelo PC.",
          "**Para exportação técnica**: apps como Health Connect Toolbox (código aberto) produzem dumps JSON manuais.",
          "**Para análises avançadas**: apps como Welltory ou Bearable leem do HC e oferecem coaching e journaling.",
        ],
        fr: [
          "**Pour un tableau de bord web** : FitMesh Sync lit depuis Health Connect et affiche tout sur une application web accessible depuis le PC.",
          "**Pour un export technique** : des applications comme Health Connect Toolbox (open source) produisent des dumps JSON manuels.",
          "**Pour des analyses avancées** : des applications comme Welltory ou Bearable lisent HC et proposent coaching et journal de bien-être.",
        ],
        pl: [
          "**Panel web**: FitMesh Sync odczytuje z Health Connect i pokazuje wszystko w aplikacji web dostępnej z PC.",
          "**Eksport techniczny**: aplikacje takie jak Health Connect Toolbox (open source) tworzą ręczne zrzuty JSON.",
          "**Zaawansowane analizy**: aplikacje takie jak Welltory lub Bearable odczytują HC i oferują coaching oraz journaling.",
        ],
        tr: [
          "**Web paneli için**: FitMesh Sync, Health Connect'ten okur ve her şeyi PC'den erişilebilen bir web uygulamasında gösterir.",
          "**Teknik dışa aktarım için**: Health Connect Toolbox (açık kaynak) gibi uygulamalar manuel JSON dökümleri üretir.",
          "**Gelişmiş analizler için**: Welltory veya Bearable gibi uygulamalar HC'den okur ve koçluk ile günlük tutma sunar.",
        ],
        nl: [
          "**Voor web-dashboard**: FitMesh Sync leest van Health Connect en toont alles op een via pc toegankelijke web-app.",
          "**Voor technische export**: apps zoals Health Connect Toolbox (open source) produceren handmatige JSON-dumps.",
          "**Voor geavanceerde analyses**: apps zoals Welltory of Bearable lezen HC en bieden coaching en journaling.",
        ],
        ja: [
          "**Webダッシュボード用**: FitMesh SyncはHealth Connectから読み取り、PCからアクセス可能なWebアプリにすべてを表示します。",
          "**技術的なエクスポート用**: Health Connect Toolbox（オープンソース）などのアプリが手動JSONダンプを作成します。",
          "**高度な分析用**: WelltoryやBearableなどのアプリがHCから読み取り、コーチングとジャーナリングを提供します。",
        ],
        ko: [
          "**웹 대시보드용**: FitMesh Sync는 Health Connect에서 읽어 PC에서 접근 가능한 웹 앱에 모든 것을 표시합니다.",
          "**기술적 내보내기용**: Health Connect Toolbox(오픈 소스) 같은 앱이 수동 JSON 덤프를 생성합니다.",
          "**고급 분석용**: Welltory나 Bearable 같은 앱이 HC에서 읽어 코칭과 저널링을 제공합니다.",
        ],
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Vincolo: questa via funziona per dati che Samsung Health scrive su Health Connect (quindi passi, BPM, sonno, calorie, distanza, allenamenti). Per dati proprietari Samsung come Body Composition o Stress Score continuo serve sempre l'export interno di Samsung Health.",
        en: "Caveat: this path works for data Samsung Health writes to Health Connect (so steps, HR, sleep, calories, distance, workouts). For Samsung-proprietary data like Body Composition or continuous Stress Score you'll always need Samsung Health's internal export.",
        es: "Limitación: esta opción funciona para los datos que Samsung Health escribe en Health Connect (pasos, frecuencia cardíaca, sueño, calorías, distancia, entrenamientos). Para datos propietarios de Samsung como Body Composition o Stress Score continuo siempre necesitarás la exportación interna de Samsung Health.",
        de: "Einschränkung: Dieser Weg funktioniert für Daten, die Samsung Health in Health Connect schreibt (also Schritte, Herzfrequenz, Schlaf, Kalorien, Distanz, Trainings). Für proprietäre Samsung-Daten wie Body Composition oder kontinuierlichen Stress Score wirst du immer den internen Samsung Health-Export benötigen.",
        pt: "Limitação: este caminho funciona para os dados que o Samsung Health grava no Health Connect (passos, frequência cardíaca, sono, calorias, distância, treinos). Para dados proprietários da Samsung como Body Composition ou Stress Score contínuo, você sempre precisará da exportação interna do Samsung Health.",
        fr: "Limite : cette voie fonctionne pour les données que Samsung Health écrit dans Health Connect (pas, fréquence cardiaque, sommeil, calories, distance, séances d'entraînement). Pour les données propriétaires Samsung comme Body Composition ou le Stress Score continu, l'export interne de Samsung Health reste toujours nécessaire.",
        pl: "Ograniczenie: ta ścieżka działa dla danych, które Samsung Health zapisuje do Health Connect (kroki, tętno, sen, kalorie, dystans, treningi). Dla zastrzeżonych danych Samsung, takich jak Body Composition czy ciągły Stress Score, zawsze będzie potrzebny wewnętrzny eksport Samsung Health.",
        tr: "Kısıtlama: bu yol Samsung Health'in Health Connect'e yazdığı veriler için çalışır (adım, nabız, uyku, kalori, mesafe, antrenmanlar). Body Composition veya sürekli Stress Score gibi Samsung'a özgü veriler için Samsung Health dahili dışa aktarımına her zaman ihtiyaç duyacaksınız.",
        nl: "Beperking: dit pad werkt voor gegevens die Samsung Health naar Health Connect schrijft (stappen, hartslag, slaap, calorieën, afstand, trainingen). Voor Samsung-propriëtaire gegevens zoals Body Composition of continue Stress Score heb je altijd de interne Samsung Health-export nodig.",
        ja: "注意点：この方法はSamsung HealthがHealth Connectに書き込むデータ（歩数、心拍数、睡眠、カロリー、距離、ワークアウト）に対してのみ機能します。Body CompositionやSamsung固有の継続的なStress Scoreなどのデータには、常にSamsung Healthの内部エクスポートが必要です。",
        ko: "주의: 이 방법은 Samsung Health가 Health Connect에 기록하는 데이터(걸음 수, 심박수, 수면, 칼로리, 거리, 운동)에만 작동합니다. Body Composition이나 지속적인 Stress Score 같은 Samsung 독점 데이터에는 항상 Samsung Health의 내부 내보내기가 필요합니다.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Opzione 4: ADB backup (avanzato)",
        en: "Option 4: ADB backup (advanced)",
        es: "Opción 4: copia de seguridad con ADB (avanzado)",
        de: "Option 4: ADB-Backup (für Fortgeschrittene)",
        pt: "Opção 4: backup via ADB (avançado)",
        fr: "Option 4 : sauvegarde ADB (avancé)",
        pl: "Opция 4: ADB backup (zaawansowane)",
        tr: "Seçenek 4: ADB yedeklemesi (gelişmiş)",
        nl: "Optie 4: ADB-backup (geavanceerd)",
        ja: "オプション4：ADBバックアップ（上級者向け）",
        ko: "옵션 4: ADB 백업 (고급)",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Per i più tecnici: i dati Samsung Health risiedono sul telefono in un database SQLite. Con un cavo USB, ADB attivato in opzioni sviluppatore, e un tool come adb backup oppure root puoi estrarre il file e leggerlo direttamente. Sconsigliato a chi non sa cosa significa 'developer options': è facile fare danni e c'è rischio di violare i ToS.",
        en: "For the more technical: Samsung Health data lives on the phone in a SQLite database. With a USB cable, ADB enabled in developer options, and a tool like adb backup or root you can extract the file and read it directly. Not recommended if you don't know what 'developer options' means: easy to break things and risks violating ToS.",
        es: "Para los más técnicos: los datos de Samsung Health residen en el teléfono en una base de datos SQLite. Con un cable USB, ADB activado en las opciones de desarrollador y una herramienta como adb backup o acceso root puedes extraer el archivo y leerlo directamente. No se recomienda si no sabes lo que significa 'opciones de desarrollador': es fácil causar problemas y existe riesgo de incumplir los Términos de Servicio.",
        de: "Für die Technisch-Versierten: Samsung Health-Daten liegen auf dem Telefon in einer SQLite-Datenbank. Mit einem USB-Kabel, aktiviertem ADB in den Entwickleroptionen und einem Tool wie adb backup oder Root-Zugriff kannst du die Datei extrahieren und direkt lesen. Nicht empfohlen, wenn du nicht weißt, was 'Entwickleroptionen' bedeutet: leicht, etwas kaputtzumachen, und es besteht das Risiko, gegen die Nutzungsbedingungen zu verstoßen.",
        pt: "Para os mais técnicos: os dados do Samsung Health ficam no celular em um banco de dados SQLite. Com um cabo USB, ADB ativado nas opções do desenvolvedor e uma ferramenta como adb backup ou root, você pode extrair o arquivo e lê-lo diretamente. Não recomendado para quem não sabe o que significam 'opções do desenvolvedor': é fácil causar problemas e há risco de violar os Termos de Serviço.",
        fr: "Pour les plus techniques : les données Samsung Health résident sur le téléphone dans une base de données SQLite. Avec un câble USB, ADB activé dans les options développeur, et un outil comme adb backup ou un accès root, vous pouvez extraire le fichier et le lire directement. Déconseillé si vous ne savez pas ce que signifient les 'options développeur' : risque de casser des choses et de violer les Conditions d'utilisation.",
        pl: "Dla bardziej technicznych użytkowników: dane Samsung Health są przechowywane na telefonie w bazie danych SQLite. Korzystając z kabla USB, aktywowanych opcji deweloperskich ADB, oraz narzędzia takiego jak adb backup lub root, można wydobyć plik i czytać go bezpośrednio. Nie zalecamy tego dla osób nieposiadających wiedzy na temat 'opcji deweloperskich': jest łatwo spowodować uszkodzenia i istnieje ryzyko naruszenia warunków użytkowania.",
        tr: "Para daha teknolojik kuranlar: Samsung Health veriler telefon üzerinde SQLite bir veritabanında saklanmaktadır. USB kabuğunu kullanarak, Geliştirici Seçenekleri içinde ADB'yi etkinleştirerek ve adb backup gibi bir araçla veya kök erişimi olan bir tool ile bu dosyayı çıkarabilir ve doğrudan okuyabilirsiniz. 'Geliştirici Seçenekleri' ne demek bilmeden bunu yapmak önerilmez: kolayca zararlı durumlara düşebilir ve ToS'i ihlal etme riski vardır.",
        nl: "Voor de meer technische gebruikers: Samsung Health-gegevens staan op de telefoon in een SQLite-database. Met een USB-kabel, ADB ingeschakeld in ontwikkelaarsopties, en een tool zoals adb backup of root kun je het bestand extraheren en direct lezen. Niet aanbevolen als je niet weet wat 'ontwikkelaarsopties' betekent: makkelijk om dingen te breken en risico op schending van de servicevoorwaarden.",
        ja: "より技術的なユーザー向け：Samsung Healthのデータはスマートフォン上のSQLiteデータベースに保存されています。USBケーブル、開発者オプションでADBを有効にし、adb backupなどのツールまたはrootを使ってファイルを抽出し直接読み取ることができます。「開発者オプション」の意味がわからない場合は推奨しません：問題が生じやすく、利用規約に違反するリスクがあります。",
        ko: "더 기술적인 사용자를 위해: Samsung Health 데이터는 스마트폰의 SQLite 데이터베이스에 저장되어 있습니다. USB 케이블, 개발자 옵션에서 ADB 활성화, adb backup 같은 도구나 루트를 사용하면 파일을 추출하여 직접 읽을 수 있습니다. '개발자 옵션'이 무엇인지 모른다면 권장하지 않습니다: 쉽게 문제가 발생할 수 있고 서비스 약관 위반 위험이 있습니다.",
      },
    },
    {
      type: "callout",
      variant: "tip",
      title: {
        it: "La scelta che consigliamo",
        en: "Our recommended choice",
        es: "Nuestra elección recomendada",
        de: "Unsere Empfehlung",
        pt: "Nossa recomendação",
        fr: "Notre choix recommandé",
        pl: "Rozwód, który polecamy",
        tr: "Recomandılan seçim",
        nl: "Onze aanbevolen keuze",
        ja: "私たちの推奨する選択",
        ko: "우리가 추천하는 선택",
      },
      body: {
        it: "Per la maggior parte degli utenti Galaxy Watch, la combinazione giusta è: export Samsung Health una volta l'anno per archivio storico completo, più Health Connect collegato a FitMesh Sync per il monitoraggio continuo. L'ADB e la richiesta GDPR sono strumenti per casi limite, non per uso quotidiano. Non cercare la soluzione 'perfetta' con automazione totale: per i dati proprietari Samsung (Body Composition, Stress Score continuo) l'export manuale periodico è e resterà necessario.",
        en: "For most Galaxy Watch users, the right combination is: Samsung Health export once a year for complete historical archive, plus Health Connect linked to FitMesh Sync for continuous monitoring. ADB and GDPR requests are tools for edge cases, not daily use. Don't look for the 'perfect' fully automated solution: for Samsung-proprietary data (Body Composition, continuous Stress Score), periodic manual export is and will remain necessary.",
        es: "Para la mayoría de usuarios del Galaxy Watch, la combinación correcta es: exportación de Samsung Health una vez al año para el archivo histórico completo, más Health Connect vinculado a FitMesh Sync para el seguimiento continuo. ADB y la solicitud GDPR son herramientas para casos excepcionales, no para el uso diario. No busques la solución 'perfecta' con automatización total: para los datos propietarios de Samsung (Body Composition, Stress Score continuo), la exportación manual periódica es y seguirá siendo necesaria.",
        de: "Für die meisten Galaxy Watch-Nutzer ist die richtige Kombination: Samsung Health-Export einmal pro Jahr für das vollständige historische Archiv, plus Health Connect verbunden mit FitMesh Sync für das kontinuierliche Monitoring. ADB und DSGVO-Anfragen sind Werkzeuge für Ausnahmefälle, nicht für den täglichen Gebrauch. Suche nicht nach der 'perfekten' vollautomatisierten Lösung: Für proprietäre Samsung-Daten (Body Composition, kontinuierlicher Stress Score) ist der periodische manuelle Export notwendig und wird es bleiben.",
        pt: "Para a maioria dos usuários do Galaxy Watch, a combinação certa é: exportação do Samsung Health uma vez por ano para o arquivo histórico completo, mais Health Connect vinculado ao FitMesh Sync para monitoramento contínuo. ADB e solicitações LGPD/GDPR são ferramentas para casos extremos, não para uso diário. Não busque a solução 'perfeita' com automação total: para os dados proprietários da Samsung (Body Composition, Stress Score contínuo), a exportação manual periódica é e continuará sendo necessária.",
        fr: "Pour la plupart des utilisateurs du Galaxy Watch, la bonne combinaison est : export Samsung Health une fois par an pour l'archive historique complète, plus Health Connect relié à FitMesh Sync pour le suivi continu. ADB et les demandes RGPD sont des outils pour les cas limites, pas pour un usage quotidien. Ne cherchez pas la solution 'parfaite' entièrement automatisée : pour les données propriétaires Samsung (Body Composition, Stress Score continu), l'export manuel périodique est et restera nécessaire.",
        pl: "Dla większości użytkowników Galaxy Watch, idealna kombinacja to: eksport Samsung Health raz w roku do archiwum pełnego, oraz połączenie z FitMesh Sync Health Connect do monitorowania ciągłego. ADB i żądanie GDPR są narzędziami do sytuacji ekstremalnych, nie do codziennego użytku. Nie szukaj idealnej rozwiązania poprzez całkowitą automatyzację: regularne eksporty ręczne dla danych własnych Samsung (kompozycji ciała, ciągłego oceny stresu) pozostaną konieczne.",
        tr: "KVKK için çoğu kullanıcının Galaxy Watch için uygun kombinasyon: export Samsung Health yıllık aralıklarla tarihli veri saklamak, daha sonra ise Health Connect ile FitMesh Sync arasında sürekli izleme. ADB ve GDPR talebi araçları sınır durumları için kullanılır, günlük kullanım için uygun değildir. Tam otomatizasyonla ‘mükemmel’ bir çözüm aramayın: Samsung verileri (Keskinlik Analizi, Süreç Skoru) için düzenli manuel export gerekliliklerini iptal etmeyecektir.",
        nl: "Voor de meeste Galaxy Watch-gebruikers is de juiste combinatie: Samsung Health-export eens per jaar voor een volledig historisch archief, plus Health Connect gekoppeld aan FitMesh Sync voor continue monitoring. ADB en AVG-verzoeken zijn tools voor randgevallen, niet voor dagelijks gebruik. Zoek niet naar de ‘perfecte’ volledig geautomatiseerde oplossing: voor Samsung-propriëtaire gegevens (Body Composition, continue Stress Score) is en blijft periodieke handmatige export noodzakelijk.",
        ja: "ほとんどのGalaxy Watchユーザーにとって、適切な組み合わせは：完全な履歴アーカイブのためにSamsung Healthを年1回エクスポートし、継続的なモニタリングのためにFitMesh Syncに接続されたHealth Connectを使用することです。ADBとGDPRリクエストはエッジケース用のツールであり、日常使用には向きません。完全に自動化された「完璧な」ソリューションを求めないでください：Samsung独自のデータ（Body Composition、継続的なStress Score）には、定期的な手動エクスポートが必要であり続けます。",
        ko: "대부분의 Galaxy Watch 사용자에게 올바른 조합은: 완전한 역사적 아카이브를 위해 Samsung Health를 연 1회 내보내기하고, 지속적인 모니터링을 위해 FitMesh Sync에 연결된 Health Connect를 사용하는 것입니다. ADB와 GDPR 요청은 엣지 케이스를 위한 도구이지 일상 사용을 위한 것이 아닙니다. 완전히 자동화된 ‘완벽한’ 솔루션을 찾지 마세요: Samsung 독점 데이터(Body Composition, 지속적인 Stress Score)에는 주기적인 수동 내보내기가 앞으로도 필요합니다.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Tabella riepilogativa",
        en: "Summary table",
        es: "Tabla resumen",
        de: "Übersichtstabelle",
        pt: "Tabela resumo",
        fr: "Tableau récapitulatif",
        pl: "Tabela podsumowująca",
        tr: "Rösum tablosu",
        nl: "Samenvattingstabel",
        ja: "まとめ表",
        ko: "요약 표",
      },
    },
    {
      type: "table",
      headers: {
        it: ["Opzione", "Difficoltà", "Completezza", "Automazione"],
        en: ["Option", "Difficulty", "Completeness", "Automation"],
        es: ["Opción", "Dificultad", "Completitud", "Automatización"],
        de: ["Option", "Schwierigkeit", "Vollständigkeit", "Automatisierung"],
        pt: ["Opção", "Dificuldade", "Completude", "Automação"],
        fr: ["Option", "Difficulté", "Complétude", "Automatisation"],
        pl: [
          "Opcja",
          "Trudności",
          "Całoscność",
          "Automatyzacja",
        ],
        tr: [
          "Seçenek",
          "Zorluklar",
          "Tamgüzelik",
          "Otomasyon",
        ],
        nl: ["Optie", "Moeilijkheid", "Volledigheid", "Automatisering"],
        ja: ["オプション", "難易度", "完全性", "自動化"],
        ko: ["옵션", "난이도", "완전성", "자동화"],
      },
      rows: [
        {
          it: ["Export Samsung Health", "Bassa", "Alta", "No"],
          en: ["Samsung Health export", "Low", "High", "No"],
          es: ["Exportación Samsung Health", "Baja", "Alta", "No"],
          de: ["Samsung Health-Export", "Niedrig", "Hoch", "Nein"],
          pt: ["Exportação Samsung Health", "Baixa", "Alta", "Não"],
          fr: ["Export Samsung Health", "Faible", "Élevée", "Non"],
          pl: [
            "Eksport Samsung Health",
            "Niska",
            "Wysoka",
            "Nie",
          ],
          tr: [
            "Export Samsung Health",
            "Basa",
            "Üst",
            "No",
          ],
          nl: ["Samsung Health export", "Laag", "Hoog", "Nee"],
          ja: ["Samsung Healthエクスポート", "低", "高", "なし"],
          ko: ["Samsung Health 내보내기", "낮음", "높음", "아니요"],
        },
        {
          it: ["GDPR request", "Bassa", "Massima", "No (30gg)"],
          en: ["GDPR request", "Low", "Maximum", "No (30 days)"],
          es: ["Solicitud GDPR", "Baja", "Máxima", "No (30 días)"],
          de: ["DSGVO-Anfrage", "Niedrig", "Maximal", "Nein (30 Tage)"],
          pt: ["Solicitação LGPD/GDPR", "Baixa", "Máxima", "Não (30 dias)"],
          fr: ["Demande RGPD", "Faible", "Maximale", "Non (30 jours)"],
          pl: [
            "prośba o GDPR",
            "Niska",
            "Maksymalna",
            "Bez (30dn)",
          ],
          tr: [
            "KVKK talebi",
            "Basa",
            "Massima",
            "No (30 gün)",
          ],
          nl: ["AVG-verzoek", "Laag", "Maximaal", "Nee (30 dagen)"],
          ja: ["GDPRリクエスト", "低", "最大", "なし (30日)"],
          ko: ["GDPR 요청", "낮음", "최대", "아니요 (30일)"],
        },
        {
          it: ["Health Connect + app terza", "Bassa", "Media", "Sì"],
          en: ["Health Connect + 3rd party", "Low", "Medium", "Yes"],
          es: ["Health Connect + app de terceros", "Baja", "Media", "Sí"],
          de: ["Health Connect + Drittanbieter-App", "Niedrig", "Mittel", "Ja"],
          pt: ["Health Connect + app de terceiros", "Baixa", "Média", "Sim"],
          fr: ["Health Connect + app tierce", "Faible", "Moyenne", "Oui"],
          pl: [
            "RODO + app trzecia",
            "Niska",
            "Media",
            "Tak",
          ],
          tr: [
            "KVKK + uygulama üçüncü parti",
            "Basa",
            "Medya",
            "Evet",
          ],
          nl: ["Health Connect + app van derden", "Laag", "Gemiddeld", "Ja"],
          ja: ["Health Connect + サードパーティ", "低", "中", "あり"],
          ko: ["Health Connect + 서드파티", "낮음", "중간", "예"],
        },
        {
          it: ["ADB / SQLite", "Alta", "Massima", "Con script"],
          en: ["ADB / SQLite", "High", "Maximum", "With scripts"],
          es: ["ADB / SQLite", "Alta", "Máxima", "Con scripts"],
          de: ["ADB / SQLite", "Hoch", "Maximal", "Mit Skripten"],
          pt: ["ADB / SQLite", "Alta", "Máxima", "Com scripts"],
          fr: ["ADB / SQLite", "Élevée", "Maximale", "Avec scripts"],
          pl: [
            "ADB / SQLite",
            "Wysoka",
            "Maksymalna",
            "Z skryptem",
          ],
          tr: [
            "ADB / SQLite",
            "Yüksek",
            "Massima",
            "Kon script",
          ],
          nl: ["ADB / SQLite", "Hoog", "Maximaal", "Met scripts"],
          ja: ["ADB / SQLite", "高", "最大", "スクリプトで可"],
          ko: ["ADB / SQLite", "높음", "최대", "스크립트로 가능"],
        },
      ],
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "In sintesi",
        en: "In summary",
        es: "En resumen",
        de: "Zusammenfassung",
        pt: "Em resumo",
        fr: "En résumé",
        pl: "W syntezie",
        tr: "Özetle",
        nl: "Samengevat",
        ja: "まとめ",
        ko: "요약",
      },
    },
    {
      type: "list",
      items: {
        it: [
          "L'export interno di Samsung Health (Impostazioni → Scarica dati personali) è il metodo più completo e gratuito: genera un pacchetto CSV con tutta la storia.",
          "Health Connect collegato a un'app terza è l'unica opzione con automazione reale: i dati fluiscono senza intervento manuale, ma copre solo i tipi di dato che Samsung Health scrive su HC.",
          "La richiesta GDPR è più ampia dell'export interno (include metadati e log), ma richiede fino a 30 giorni: usarla solo per archivio pre-chiusura account.",
          "ADB è per utenti tecnici: accesso diretto al database SQLite, massima completezza, alto rischio se non si sa cosa si fa.",
          "I dati proprietari Samsung (Body Composition, Stress Score continuo) non passano per Health Connect: per quelli serve sempre l'export manuale.",
        ],
        en: [
          "Samsung Health's internal export (Settings → Download personal data) is the most complete and free method: generates a CSV package with your entire history.",
          "Health Connect linked to a third-party app is the only option with real automation: data flows without manual intervention, but covers only data types Samsung Health writes to HC.",
          "The GDPR request is broader than the internal export (includes metadata and access logs), but takes up to 30 days: use it only for archive before closing an account.",
          "ADB is for technical users: direct access to the SQLite database, maximum completeness, high risk if you don't know what you're doing.",
          "Samsung-proprietary data (Body Composition, continuous Stress Score) doesn't pass through Health Connect: manual export is always needed for those.",
        ],
        es: [
          "La exportación interna de Samsung Health (Ajustes → Descargar datos personales) es el método más completo y gratuito: genera un paquete CSV con todo tu historial.",
          "Health Connect vinculado a una app de terceros es la única opción con automatización real: los datos fluyen sin intervención manual, pero solo cubre los tipos de datos que Samsung Health escribe en HC.",
          "La solicitud GDPR es más amplia que la exportación interna (incluye metadatos y registros de acceso), pero puede tardar hasta 30 días: úsala solo como archivo antes de cerrar una cuenta.",
          "ADB es para usuarios técnicos: acceso directo a la base de datos SQLite, máxima completitud, riesgo alto si no sabes lo que haces.",
          "Los datos propietarios de Samsung (Body Composition, Stress Score continuo) no pasan por Health Connect: para ellos siempre necesitas la exportación manual.",
        ],
        de: [
          "Der interne Samsung Health-Export (Einstellungen → Persönliche Daten herunterladen) ist die vollständigste und kostenlose Methode: erstellt ein CSV-Paket mit deiner gesamten Datei.",
          "Health Connect, verbunden mit einer Drittanbieter-App, ist die einzige Option mit echter Automatisierung: Daten fließen ohne manuellen Eingriff, deckt aber nur Datentypen ab, die Samsung Health in HC schreibt.",
          "Die DSGVO-Anfrage ist umfangreicher als der interne Export (enthält Metadaten und Zugriffsprotokolle), dauert aber bis zu 30 Tage: nur für das Archiv vor dem Kontoschließen verwenden.",
          "ADB ist für technisch versierte Nutzer: direkter Zugriff auf die SQLite-Datenbank, maximale Vollständigkeit, hohes Risiko wenn man nicht weiß, was man tut.",
          "Proprietäre Samsung-Daten (Body Composition, kontinuierlicher Stress Score) laufen nicht über Health Connect: Für diese ist immer der manuelle Export erforderlich.",
        ],
        pt: [
          "A exportação interna do Samsung Health (Configurações → Baixar dados pessoais) é o método mais completo e gratuito: gera um pacote CSV com todo o seu histórico.",
          "O Health Connect vinculado a um app de terceiros é a única opção com automação real: os dados fluem sem intervenção manual, mas cobre apenas os tipos de dados que o Samsung Health grava no HC.",
          "A solicitação LGPD/GDPR é mais ampla do que a exportação interna (inclui metadados e logs de acesso), mas leva até 30 dias: use apenas como arquivo antes de encerrar uma conta.",
          "O ADB é para usuários técnicos: acesso direto ao banco de dados SQLite, completude máxima, alto risco se você não sabe o que está fazendo.",
          "Os dados proprietários da Samsung (Body Composition, Stress Score contínuo) não passam pelo Health Connect: para eles, a exportação manual sempre será necessária.",
        ],
        fr: [
          "L'export interne de Samsung Health (Paramètres → Télécharger mes données personnelles) est la méthode la plus complète et gratuite : génère un package CSV avec tout votre historique.",
          "Health Connect relié à une application tierce est la seule option avec une vraie automatisation : les données circulent sans intervention manuelle, mais ne couvre que les types de données que Samsung Health écrit dans HC.",
          "La demande RGPD est plus large que l'export interne (inclut les métadonnées et les journaux d'accès), mais prend jusqu'à 30 jours : à utiliser uniquement pour l'archive avant la fermeture d'un compte.",
          "ADB est destiné aux utilisateurs techniques : accès direct à la base de données SQLite, complétude maximale, risque élevé si vous ne savez pas ce que vous faites.",
          "Les données propriétaires Samsung (Body Composition, Stress Score continu) ne passent pas par Health Connect : pour celles-ci, l'export manuel reste toujours nécessaire.",
        ],
        pl: [
          "Wyeksportowanie wewnętrzne Samsung Health (Ustawienia → Pobierz dane osobowe) to najbardziej kompleksowy i darmowy sposób: generuje pakiet CSV z całą historią.",
          "Health Connect połączony z trzecią aplikacją jest jedyną opcją z rzeczywistą automatyzacją: dane przepływają bez interwencji manualnej, ale obejmuje tylko typy danych, które Samsung Health zapisuje na HC.",
          "Zażądanie GDPR obejmuje wyeksportowanie wewnętrzne (zakłada metadane i logi), ale wymaga do 30 dni: używaj tylko do zapisu przed-zamknięcia konta.",
          "ADB jest dla technicznych użytkowników: bezpośredni dostęp do bazy danych SQLite, najwyższa kompletność, wysoki ryzyko w przypadku braku wiedzy o działaniu.",
          "Dane własne Samsung (kompozycja ciała, ciągła ocena stresu) nie przechodzą przez Health Connect: dla nich zawsze wymagany jest ręczny eksport.",
        ],
        tr: [
          "İç aktarma (Samsung Health ayarları → kişisel verileri indir) en kapsamlı ve ücretsiz yöntemdir: tüm tarihi bir CSV paketini oluşturur.",
          "Health Connect bir üçüncü taraf uygulamasına bağlıysa, gerçek otomasyonun tek seçenekidir: veriler manuel müdahale gerekmeden kendiliğinden akar, ancak yalnızca Samsung Health'in HC'ye yazdığı veri tiplerini kapsar.",
          "Güvenlik GDPR isteği içeren export yerel (metadataları ve logları da içerir) ancak bu işlem için en fazla 30 gün gerekebilir: sadece hesap kapatma öncesi arşivlemek amaçlı kullanın.",
          "ADB için teknik kullanıcılar için: SQLite veritabanına doğrudan erişim, en kapsamlı ama yanlış kullanılmasıyla yüksek risk.",
          "Veri sahip Samsung (Kütle Üzeyi Analizi, Sürekli Basınç Puanı) KVKK: için geçmez: o verilere her zaman el ile export yapılması gerekmektedir.",
        ],
        nl: [
          "De interne export van Samsung Health (Instellingen → Persoonlijke gegevens downloaden) is de meest volledige en gratis methode: genereert een CSV-pakket met je volledige geschiedenis.",
          "Health Connect gekoppeld aan een app van derden is de enige optie met echte automatisering: gegevens stromen zonder handmatige tussenkomst, maar dekt alleen gegevenstypen die Samsung Health naar HC schrijft.",
          "Het AVG-verzoek is uitgebreider dan de interne export (bevat metadata en toegangslogboeken), maar duurt tot 30 dagen: gebruik het alleen als archief vóór het sluiten van een account.",
          "ADB is voor technische gebruikers: directe toegang tot de SQLite-database, maximale volledigheid, hoog risico als je niet weet wat je doet.",
          "Samsungs eigen gegevens (Body Composition, continue Stress Score) gaan niet via Health Connect: daarvoor is altijd handmatige export nodig.",
        ],
        ja: [
          "Samsung Healthの内部エクスポート（設定 → 個人データをダウンロード）は最も完全で無料の方法です：全履歴を含むCSVパッケージを生成します。",
          "サードパーティアプリに接続されたHealth Connectは真の自動化が可能な唯一のオプションです：データが手動操作なしで流れますが、Samsung HealthがHCに書き込むデータタイプのみをカバーします。",
          "GDPRリクエストは内部エクスポートより広範囲です（メタデータとアクセスログを含む）が、最大30日かかります：アカウント閉鎖前のアーカイブとしてのみ使用してください。",
          "ADBは技術ユーザー向けです：SQLiteデータベースへの直接アクセス、最大限の完全性、操作を理解していない場合は高リスクです。",
          "Samsung独自のデータ（Body Composition、継続的なStress Score）はHealth Connectを経由しません：それらには常に手動エクスポートが必要です。",
        ],
        ko: [
          "Samsung Health의 내부 내보내기(설정 → 개인 데이터 다운로드)는 가장 완전하고 무료인 방법입니다: 전체 기록이 담긴 CSV 패키지를 생성합니다.",
          "서드파티 앱에 연결된 Health Connect는 실제 자동화가 가능한 유일한 옵션입니다: 수동 개입 없이 데이터가 흐르지만, Samsung Health가 HC에 기록하는 데이터 유형만 커버합니다.",
          "GDPR 요청은 내부 내보내기보다 광범위합니다(메타데이터 및 접근 로그 포함), 하지만 최대 30일이 걸립니다: 계정 삭제 전 아카이브로만 사용하세요.",
          "ADB는 기술 사용자를 위한 것입니다: SQLite 데이터베이스에 직접 접근, 최대 완전성, 무엇을 하는지 모르면 높은 위험.",
          "Samsung 독점 데이터(Body Composition, 지속적인 Stress Score)는 Health Connect를 통과하지 않습니다: 해당 데이터는 항상 수동 내보내기가 필요합니다.",
        ],
      },
    },
    {
      type: "cta",
      title: {
        it: "Cerchi una dashboard web pronta per i dati Galaxy Watch?",
        en: "Looking for a ready web dashboard for Galaxy Watch data?",
        es: "¿Buscas un panel web listo para los datos del Galaxy Watch?",
        de: "Suchst du ein fertiges Web-Dashboard für Galaxy Watch-Daten?",
        pt: "Procurando um painel web pronto para os dados do Galaxy Watch?",
        fr: "Vous cherchez un tableau de bord web prêt pour les données du Galaxy Watch ?",
        pl: "Czy szukasz panelu kontrolnego w sieci dla danych Galaxy Watch?",
        tr: "Araştırmalarınız için uygun bir veri Galaxy Watch panosu arıyorsunuz?",
        nl: "Op zoek naar een kant-en-klaar web-dashboard voor Galaxy Watch-gegevens?",
        ja: "Galaxy Watchデータのすぐに使えるWebダッシュボードをお探しですか？",
        ko: "Galaxy Watch 데이터를 위한 바로 사용 가능한 웹 대시보드를 찾고 있나요?",
      },
      body: {
        it: "FitMesh Sync legge da Samsung Health via Health Connect e mostra passi, BPM, sonno e allenamenti su una dashboard web accessibile da qualsiasi browser. Setup di 30 secondi sul telefono.",
        en: "FitMesh Sync reads from Samsung Health via Health Connect and shows steps, HR, sleep and workouts on a browser-accessible web dashboard. 30-second phone setup.",
        es: "FitMesh Sync lee de Samsung Health a través de Health Connect y muestra pasos, frecuencia cardíaca, sueño y entrenamientos en un panel web accesible desde cualquier navegador. Configuración en 30 segundos desde el teléfono.",
        de: "FitMesh Sync liest aus Samsung Health über Health Connect und zeigt Schritte, Herzfrequenz, Schlaf und Trainings auf einem Web-Dashboard, das über jeden Browser zugänglich ist. Einrichtung in 30 Sekunden auf dem Telefon.",
        pt: "FitMesh Sync lê do Samsung Health via Health Connect e mostra passos, frequência cardíaca, sono e treinos em um painel web acessível por qualquer navegador. Configuração em 30 segundos no celular.",
        fr: "FitMesh Sync lit depuis Samsung Health via Health Connect et affiche pas, fréquence cardiaque, sommeil et séances d'entraînement sur un tableau de bord web accessible depuis n'importe quel navigateur. Configuration en 30 secondes sur le téléphone.",
        pl: "FitMesh Sync odczytuje z Samsung Health przez Health Connect i wyświetla kroki, BPM, sen i treningi na webowej dashboardie dostępnej z dowolnego przeglądarki. Konfiguracja w 30 sekund na telefonie.",
        tr: "FitMesh Sync KVKK'ye uygun olarak Samsung Health üzerinden Health Connect ile ve gösterir pasları, BPM, uyku ve egzersizleri bir web tabanlı panelde. Telefondan 30 saniye setup'u.",
        nl: "FitMesh Sync leest van Samsung Health via Health Connect en toont stappen, hartslag, slaap en trainingen op een via elke browser toegankelijk web-dashboard. Instelling in 30 seconden op de telefoon.",
        ja: "FitMesh SyncはHealth Connect経由でSamsung Healthから読み取り、歩数、心拍数、睡眠、ワークアウトをブラウザからアクセス可能なWebダッシュボードに表示します。スマートフォンで30秒でセットアップ。",
        ko: "FitMesh Sync는 Health Connect를 통해 Samsung Health에서 읽어 걸음 수, 심박수, 수면, 운동을 모든 브라우저에서 접근 가능한 웹 대시보드에 표시합니다. 휴대폰에서 30초 설정.",
      },
      ctaLabel: {
        it: "Vedi Galaxy Watch su FitMesh →",
        en: "See Galaxy Watch on FitMesh →",
        es: "Ver Galaxy Watch en FitMesh →",
        de: "Galaxy Watch auf FitMesh ansehen →",
        pt: "Ver Galaxy Watch no FitMesh →",
        fr: "Voir Galaxy Watch sur FitMesh →",
        pl: "Zobacz Galaxy Watch na FitMesh →",
        tr: "Gör Galaxy Watch'i FitMesh →",
        nl: "Zie Galaxy Watch op FitMesh →",
        ja: "FitMeshでGalaxy Watchを見る →",
        ko: "FitMesh에서 Galaxy Watch 보기 →",
      },
      ctaHref: { it: "/it/sync/galaxy-watch", en: "/en/sync/galaxy-watch" },
    },
  ],
  faq: [
    {
      q: {
        it: "L'esportazione include lo storico completo?",
        en: "Does the export include the full history?",
        es: "¿La exportación incluye el historial completo?",
        de: "Enthält der Export die vollständige Datei?",
        pt: "A exportação inclui o histórico completo?",
        fr: "L'export inclut-il l'historique complet ?",
        pl: "Czy eksport obejmuje pełny historik?",
        tr: "Geri aktarma içeriyor mu tam geçmiş?",
        nl: "Bevat de export de volledige geschiedenis?",
        ja: "エクスポートには完全な履歴が含まれますか？",
        ko: "내보내기에 전체 기록이 포함되나요?",
      },
      a: {
        it: "Sì: l'export Samsung Health interno include tutti i dati associati al tuo account, anche pluriennali. Se hai cambiato account in passato, lo storico legato al vecchio account non è incluso e va recuperato separatamente.",
        en: "Yes: the Samsung Health internal export includes all data linked to your account, multi-year too. If you changed account in the past, the history tied to the old account isn't included and must be recovered separately.",
        es: "Sí: la exportación interna de Samsung Health incluye todos los datos asociados a tu cuenta, incluso los de varios años. Si cambiaste de cuenta en el pasado, el historial vinculado a la cuenta anterior no está incluido y debes recuperarlo por separado.",
        de: "Ja: Der interne Samsung Health-Export enthält alle mit deinem Konto verknüpften Daten, auch mehrjährige. Wenn du in der Vergangenheit das Konto gewechselt hast, ist die Datei des alten Kontos nicht enthalten und muss separat wiederhergestellt werden.",
        pt: "Sim: a exportação interna do Samsung Health inclui todos os dados vinculados à sua conta, mesmo os de vários anos. Se você trocou de conta no passado, o histórico vinculado à conta antiga não está incluído e precisa ser recuperado separadamente.",
        fr: "Oui : l'export interne Samsung Health inclut toutes les données liées à votre compte, même pluriannuelles. Si vous avez changé de compte par le passé, l'historique lié à l'ancien compte n'est pas inclus et doit être récupéré séparément.",
        pl: "Tak: eksport Samsung Health wewnętrzny zawiera wszystkie dane powiązane z Twoim kontem, nawet długoterminowe. Jeśli zmieniłeś konto w przeszłości, historia związana z poprzednim kontem nie jest uwzględniona i musi być odzyskana oddzielnie.",
        tr: "Evet: İç Samsung Health export tüm hesapla ilişkili verileri içerir, bileşenliklere de dahil. Eski hesabın ile ilgili tarihi eski hesaptan dahil değildir ve ayrı olarak geri yüklenebilir.",
        nl: "Ja: de interne Samsung Health-export bevat alle gegevens die aan je account zijn gekoppeld, ook meerdere jaren. Als je in het verleden van account bent gewisseld, is de geschiedenis van het oude account niet inbegrepen en moet apart worden opgehaald.",
        ja: "はい：Samsung Healthの内部エクスポートにはアカウントに関連するすべてのデータが含まれており、複数年分も対象です。過去にアカウントを変更した場合、古いアカウントの履歴は含まれておらず、別途取得する必要があります。",
        ko: "예: Samsung Health 내부 내보내기에는 계정에 연결된 모든 데이터가 포함되며, 여러 해 분량도 포함됩니다. 과거에 계정을 변경했다면 이전 계정과 연결된 기록은 포함되지 않으며 별도로 복구해야 합니다.",
      },
    },
    {
      q: {
        it: "Posso fare il backup senza autenticarmi con Samsung Account?",
        en: "Can I back up without authenticating with Samsung Account?",
        es: "¿Puedo hacer la copia de seguridad sin autenticarme con Samsung Account?",
        de: "Kann ich ein Backup erstellen ohne mich mit dem Samsung Account zu authentifizieren?",
        pt: "Posso fazer o backup sem me autenticar com o Samsung Account?",
        fr: "Puis-je sauvegarder sans m'authentifier avec Samsung Account ?",
        pl: "Czy mogę wykonać kopię zapasową bez logowania się za pomocą konta Samsung Account?",
        tr: "Güvenlik içinSamsung Hesabım ile kimlik doğrulama yapmadan yine de zesik alma yapabilirim mi?",
        nl: "Kan ik een backup maken zonder authenticatie met Samsung Account?",
        ja: "Samsung Accountで認証せずにバックアップできますか？",
        ko: "Samsung Account 인증 없이 백업할 수 있나요?",
      },
      a: {
        it: "Per l'export interno di Samsung Health la password è richiesta. Per la via Health Connect + app terza no: basta il permesso Android. È l'unica strada che non passa dall'account Samsung.",
        en: "For Samsung Health's internal export the password is required. For the Health Connect + third-party app path no: Android permission is enough. It's the only route bypassing the Samsung account.",
        es: "Para la exportación interna de Samsung Health se requiere la contraseña. Para la opción Health Connect + app de terceros no: basta con el permiso de Android. Es la única opción que no pasa por la cuenta Samsung.",
        de: "Für den internen Samsung Health-Export ist das Passwort erforderlich. Für den Weg über Health Connect + Drittanbieter-App nicht: Die Android-Berechtigung reicht aus. Es ist der einzige Weg, der nicht über das Samsung-Konto läuft.",
        pt: "Para a exportação interna do Samsung Health, a senha é necessária. Para o caminho via Health Connect + app de terceiros, não: basta a permissão do Android. É o único caminho que não passa pela conta Samsung.",
        fr: "Pour l'export interne de Samsung Health, le mot de passe est requis. Pour la voie Health Connect + application tierce, non : la permission Android suffit. C'est la seule voie qui ne passe pas par le compte Samsung.",
        pl: "Dla eksportu wewnętrznego Samsung Health wymagana jest hasło. Dla ścieżki Health Connect + aplikacja trzecia nie: wystarczy zezwolenie Android. To jest jedyna ścieżka, która nie przechodzi przez konto Samsung.",
        tr: "KVKK için Samsung Health exportu için şifre gereklidir. Diğer yollar Health Connect + üçüncü taraf uygulama: sadece Android izni yeterlidir. Bu yol da Samsung hesabından geçmez.",
        nl: "Voor de interne Samsung Health-export is het wachtwoord vereist. Voor Health Connect + app van derden niet: Android-toestemming is voldoende. Het is de enige route die het Samsung-account omzeilt.",
        ja: "Samsung Healthの内部エクスポートにはパスワードが必要です。Health Connect + サードパーティアプリの方法では不要です：Android権限で十分です。Samsungアカウントを経由しない唯一のルートです。",
        ko: "Samsung Health의 내부 내보내기에는 비밀번호가 필요합니다. Health Connect + 서드파티 앱 방법에는 필요하지 않습니다: Android 권한만으로 충분합니다. Samsung 계정을 우회하는 유일한 경로입니다.",
      },
    },
    {
      q: {
        it: "I file esportati funzionano in Excel?",
        en: "Do exported files work in Excel?",
        es: "¿Los archivos exportados funcionan en Excel?",
        de: "Funktionieren die exportierten Dateien in Excel?",
        pt: "Os arquivos exportados funcionam no Excel?",
        fr: "Les fichiers exportés fonctionnent-ils dans Excel ?",
        pl: "Czy wyeksportowane pliki funcionują w Excel?",
        tr: "İçe aktarılan dosyalar Excel'de çalışır mı?",
        nl: "Werken geexporteerde bestanden in Excel?",
        ja: "エクスポートされたファイルはExcelで使えますか？",
        ko: "내보낸 파일이 Excel에서 작동하나요?",
      },
      a: {
        it: "Sì, i CSV sono compatibili con Excel/Numbers/Google Sheets. Apri il file, scegli virgola come separatore se richiesto. Per file molto grandi (>1M righe per dati come HR continuo annuali) conviene usare strumenti specifici (Python pandas, R, DuckDB).",
        en: "Yes, CSVs are compatible with Excel/Numbers/Google Sheets. Open the file, choose comma as separator if asked. For very large files (>1M rows for things like annual continuous HR) use specific tools (Python pandas, R, DuckDB).",
        es: "Sí, los CSV son compatibles con Excel, Numbers y Google Sheets. Abre el archivo y elige coma como separador si se te pide. Para archivos muy grandes (más de 1 millón de filas, como la frecuencia cardíaca continua anual) conviene usar herramientas específicas (Python pandas, R, DuckDB).",
        de: "Ja, CSV-Dateien sind mit Excel/Numbers/Google Sheets kompatibel. Öffne die Datei und wähle Komma als Trennzeichen, wenn gefragt. Für sehr große Dateien (mehr als 1 Million Zeilen, wie bei jährlicher kontinuierlicher Herzfrequenz) empfehlen sich spezifische Tools (Python pandas, R, DuckDB).",
        pt: "Sim, os CSVs são compatíveis com Excel/Numbers/Google Sheets. Abra o arquivo e escolha vírgula como separador se solicitado. Para arquivos muito grandes (mais de 1 milhão de linhas, como frequência cardíaca contínua anual) é melhor usar ferramentas específicas (Python pandas, R, DuckDB).",
        fr: "Oui, les CSV sont compatibles avec Excel/Numbers/Google Sheets. Ouvrez le fichier et choisissez la virgule comme séparateur si demandé. Pour les fichiers très volumineux (plus d'1 million de lignes, comme la fréquence cardiaque continue annuelle), préférez des outils spécifiques (Python pandas, R, DuckDB).",
        pl: "Tak, CSV są kompatybilne z Excel/Numbers/Google Sheets. Otwórz plik i wybierz przecinek jako separatory, jeśli będzie to potrzebne. Dla bardzo dużych plików (>1M wierszy dla danych takich jak HR kontinuowane roczne) polecam używanie specjalistycznych narzędzi (np. Python pandas, R, DuckDB).",
        tr: "Evet, CSV Excel/Numbers/Google Sayfalar ile uyumludur. Dosyayı açın ve gerekirse virgülü ayırt edici olarak seçin. Çok büyük dosyalar için (>1M satır veri gibi HR sürekli yıllık) özel araçlar kullanmak faydalıdır (Python pandas, R, DuckDB).",
        nl: "Ja, CSV-bestanden zijn compatibel met Excel/Numbers/Google Sheets. Open het bestand en kies komma als scheidingsteken indien gevraagd. Voor zeer grote bestanden (meer dan 1 miljoen rijen voor zaken als jaarlijkse continue hartslag) gebruik je specifieke tools (Python pandas, R, DuckDB).",
        ja: "はい、CSVはExcel/Numbers/Google Sheetsと互換性があります。ファイルを開き、求められた場合はカンマを区切り文字として選択してください。非常に大きなファイル（年間継続心拍数など100万行超）の場合は、専用ツール（Python pandas、R、DuckDB）を使用してください。",
        ko: "예, CSV는 Excel/Numbers/Google Sheets와 호환됩니다. 파일을 열고 요청시 쉼표를 구분자로 선택하세요. 매우 큰 파일(연간 지속적인 심박수 등 100만 행 초과)의 경우 전용 도구(Python pandas, R, DuckDB)를 사용하세요.",
      },
    },
  ],
  related: [
    "guida-sync-wearable-2026",
    "health-connect-vs-samsung-health",
    "vedere-dati-wearable-browser-pc",
  ],
  brandsMentioned: ["Samsung", "Google"],
  ldType: "BlogPosting",
};
