import type { BlogPost } from "../types";

/**
 * MOFU/BOFU: al momento dell'acquisto di un nuovo wearable. Cambio di
 * marca/modello (NON cambio di sistema operativo, quello è
 * da-android-a-iphone-dati-fitness). Value prop centrale: uno storico
 * unificato nel cloud UE che sopravvive al cambio hardware e unisce marche
 * diverse. it + en; gli altri locali si aggiungono dopo.
 */
export const post: BlogPost = {
  slug: "cambiare-smartwatch-senza-perdere-dati",
  category: "guides",
  publishedAt: "2026-07-02",
  updatedAt: "2026-07-03",
  readMinutes: 8,
  hero: {
    kicker: {
      it: "Guida",
      en: "Guide",
      es: "Guía",
      de: "Anleitung",
      pt: "Guia",
      fr: "Guide",
    },
    title: {
      it: "Cambiare smartwatch senza perdere lo storico dei dati",
      en: "How to switch smartwatch without losing your data history",
      es: "Cómo cambiar de smartwatch sin perder tu historial de datos",
      de: "Smartwatch wechseln, ohne deinen Datenverlauf zu verlieren",
      pt: "Como trocar de smartwatch sem perder o histórico de dados",
      fr: "Comment changer de montre connectée sans perdre son historique de données",
    },
    subtitle: {
      it: "Compri un orologio nuovo o passi a un anello e temi di lasciare indietro anni di passi, sonno e battito? Il problema è che ogni marca chiude lo storico nella propria app. FitMesh lo tiene fuori dal dispositivo e unisce marche diverse in un'unica dashboard che sopravvive a ogni cambio.",
      en: "Buying a new watch, or moving to a ring, and worried about leaving years of steps, sleep and heart rate behind? The problem is that every brand locks your history inside its own app. FitMesh keeps it off the device and merges different brands into one dashboard that survives every switch.",
      es: "¿Compras un reloj nuevo o te pasas a un anillo y temes dejar atrás años de pasos, sueño y ritmo cardíaco? El problema es que cada marca encierra tu historial dentro de su propia app. FitMesh lo mantiene fuera del dispositivo y une marcas distintas en un único panel que sobrevive a cada cambio.",
      de: "Du kaufst eine neue Uhr oder steigst auf einen Ring um und hast Angst, Jahre an Schritten, Schlaf und Herzfrequenz zurückzulassen? Das Problem ist, dass jede Marke deinen Verlauf in ihrer eigenen App einsperrt. FitMesh hält ihn außerhalb des Geräts und führt verschiedene Marken in einem Dashboard zusammen, das jeden Wechsel übersteht.",
      pt: "Comprou um relógio novo, ou está passando para um anel, e tem medo de deixar para trás anos de passos, sono e frequência cardíaca? O problema é que cada marca tranca o seu histórico dentro do próprio app. O FitMesh o mantém fora do dispositivo e reúne marcas diferentes em um único painel que sobrevive a cada troca.",
      fr: "Vous achetez une nouvelle montre, ou vous passez à une bague connectée, et vous craignez de laisser derrière vous des années de pas, de sommeil et de fréquence cardiaque ? Le problème, c'est que chaque marque enferme votre historique dans sa propre application. FitMesh le garde hors de l'appareil et réunit des marques différentes dans un seul tableau de bord qui survit à chaque changement.",
    },
  },
  metaDescription: {
    it: "Cambiare smartwatch senza perdere lo storico: FitMesh tiene i dati indipendenti dal dispositivo e unisce marche diverse in un'unica dashboard.",
    en: "Switch smartwatch without losing your history: FitMesh keeps data independent of the device and merges different brands into one dashboard.",
    es: "Cambia de smartwatch sin perder tu historial: FitMesh guarda los datos independientes del dispositivo y une marcas distintas en un único panel.",
    de: "Smartwatch wechseln, ohne deinen Verlauf zu verlieren: FitMesh speichert die Daten unabhängig vom Gerät und führt verschiedene Marken in einem Dashboard zusammen.",
    pt: "Trocar de smartwatch sem perder o histórico: o FitMesh mantém os dados independentes do dispositivo e reúne marcas diferentes em um único painel.",
    fr: "Changer de montre connectée sans perdre son historique : FitMesh garde les données indépendantes de l'appareil et réunit des marques différentes dans un seul tableau de bord.",
  },
  primaryKeyword: {
    it: "cambiare smartwatch senza perdere dati",
    en: "switch smartwatch without losing data",
    es: "cambiar de smartwatch sin perder datos",
    de: "smartwatch wechseln ohne daten zu verlieren",
    pt: "trocar de smartwatch sem perder dados",
    fr: "changer de montre connectée sans perdre ses données",
  },
  secondaryKeywords: {
    it: [
      "cambiare orologio fitness senza perdere storico",
      "trasferire dati smartwatch nuovo",
      "storico dati fitness nel cloud",
      "unire dati smartwatch marche diverse",
      "cambiare marca smartwatch dati",
      "passare da orologio ad anello dati",
      "dashboard unica wearable",
    ],
    en: [
      "change fitness watch keep history",
      "transfer smartwatch data to new device",
      "unified fitness history cloud",
      "merge data from different smartwatch brands",
      "keep health history switching wearable",
      "switch from watch to ring data",
      "single wearable dashboard",
    ],
    es: [
      "cambiar reloj fitness sin perder historial",
      "transferir datos smartwatch a nuevo dispositivo",
      "historial fitness unificado en la nube",
      "unir datos de marcas de smartwatch distintas",
      "conservar historial de salud al cambiar wearable",
      "pasar de reloj a anillo datos",
      "panel único wearable",
    ],
    de: [
      "fitnessuhr wechseln verlauf behalten",
      "smartwatch daten auf neues gerät übertragen",
      "einheitlicher fitnessverlauf cloud",
      "daten verschiedener smartwatch marken zusammenführen",
      "gesundheitsverlauf beim wearable wechsel behalten",
      "von uhr auf ring daten",
      "einheitliches wearable dashboard",
    ],
    pt: [
      "trocar de relógio fitness sem perder histórico",
      "transferir dados do smartwatch para novo dispositivo",
      "histórico fitness unificado na nuvem",
      "unir dados de marcas de smartwatch diferentes",
      "manter histórico de saúde ao trocar de wearable",
      "passar de relógio para anel dados",
      "painel único wearable",
    ],
    fr: [
      "changer de montre fitness garder l'historique",
      "transférer les données de la montre vers un nouvel appareil",
      "historique fitness unifié cloud",
      "fusionner les données de différentes marques de montres",
      "garder l'historique santé en changeant de wearable",
      "passer de la montre à la bague données",
      "tableau de bord wearable unique",
    ],
  },
  tldr: {
    it: [
      "Cambiare marca di wearable di solito spezza lo storico: ogni app del produttore riparte da un grafico vuoto.",
      "FitMesh tiene lo storico sul tuo account, indipendente dal dispositivo.",
      "Unisce marche diverse in una dashboard deduplicata: via Health Connect su Android, Apple Salute su iPhone (disponibile, incluse tutte le storefront dell'Unione Europea), e l'anello Colmi via Bluetooth.",
      "Collega FitMesh prima del cambio per portare dentro la base storica; tieni i due dispositivi in parallelo qualche giorno per una transizione senza buchi.",
      "Cambi orologio o anello quante volte vuoi: i dati restano tuoi.",
    ],
    en: [
      "Changing wearable brand usually breaks your history: every manufacturer app restarts from an empty chart.",
      "FitMesh keeps your history on your account, independent of the device.",
      "It merges different brands into one deduplicated dashboard: via Health Connect on Android, Apple Health on iPhone (available, including all European Union storefronts), and the Colmi ring over Bluetooth.",
      "Connect FitMesh before the switch to pull in your recent baseline; run both devices in parallel for a few days for a gap-free transition.",
      "Change watch or ring as many times as you like: the data stays yours.",
    ],
    es: [
      "Cambiar de marca de wearable suele romper tu historial: cada app del fabricante vuelve a empezar desde un gráfico vacío.",
      "FitMesh conserva tu historial en tu cuenta, independiente del dispositivo.",
      "Une marcas distintas en un único panel sin duplicados: vía Health Connect en Android, Apple Health en iPhone (disponible, incluidas todas las tiendas de la Unión Europea) y el anillo Colmi por Bluetooth.",
      "Conecta FitMesh antes del cambio para incorporar tu base reciente; mantén ambos dispositivos en paralelo unos días para una transición sin huecos.",
      "Cambia de reloj o de anillo tantas veces como quieras: los datos siguen siendo tuyos.",
    ],
    de: [
      "Ein Markenwechsel beim Wearable zerreißt meist deinen Verlauf: Jede Hersteller-App startet wieder bei einem leeren Diagramm.",
      "FitMesh bewahrt deinen Verlauf in deinem Konto, unabhängig vom Gerät.",
      "Es führt verschiedene Marken in einem Dashboard ohne Dubletten zusammen: über Health Connect unter Android, Apple Health auf dem iPhone (verfügbar, einschließlich aller Storefronts der Europäischen Union) und den Colmi-Ring über Bluetooth.",
      "Verbinde FitMesh vor dem Wechsel, um deine jüngste Basis mitzunehmen; nutze beide Geräte einige Tage parallel für einen lückenlosen Übergang.",
      "Wechsle Uhr oder Ring so oft du willst: Die Daten bleiben deine.",
    ],
    pt: [
      "Trocar de marca de wearable geralmente quebra o seu histórico: cada app do fabricante recomeça de um gráfico vazio.",
      "O FitMesh mantém o seu histórico na sua conta, independente do dispositivo.",
      "Ele reúne marcas diferentes em um único painel sem duplicatas: via Health Connect no Android, Apple Health no iPhone (disponível, incluindo todas as lojas da União Europeia) e o anel Colmi por Bluetooth.",
      "Conecte o FitMesh antes da troca para trazer a sua base recente; use os dois dispositivos em paralelo por alguns dias para uma transição sem lacunas.",
      "Troque de relógio ou de anel quantas vezes quiser: os dados continuam sendo seus.",
    ],
    fr: [
      "Changer de marque de wearable casse en général votre historique : chaque application de fabricant repart d'un graphique vide.",
      "FitMesh garde votre historique sur votre compte, indépendamment de l'appareil.",
      "Il réunit des marques différentes dans un seul tableau de bord dédoublonné : via Health Connect sur Android, Apple Health sur iPhone (disponible, y compris dans toutes les boutiques de l'Union européenne) et la bague Colmi par Bluetooth.",
      "Connectez FitMesh avant le changement pour récupérer votre base récente ; utilisez les deux appareils en parallèle pendant quelques jours pour une transition sans trous.",
      "Changez de montre ou de bague autant de fois que vous voulez : les données restent les vôtres.",
    ],
  },
  body: [
    {
      type: "paragraph",
      text: {
        it: "Hai appena ordinato un orologio nuovo, o stai passando dall'orologio a un anello. La domanda che spesso frena l'acquisto è sempre la stessa: e tutto lo storico che ho accumulato in questi anni? Passi, sonno, battito, allenamenti, mesi o anni di dati che vivono dentro l'app del vecchio dispositivo. Cambiare marca di solito significa ricominciare da un grafico vuoto. Attenzione a non confondere i due casi: qui non parliamo del passaggio da Android a iPhone (quello è un cambio di sistema operativo, lo trattiamo in [Da Android a iPhone: come non perdere i dati fitness](/blog/da-android-a-iphone-dati-fitness)). Qui parliamo del cambio di marca o modello del wearable: resti sullo stesso telefono, ma il tuo orologio Garmin diventa un Galaxy Watch, o il tuo Fitbit diventa un anello Colmi. Vediamo perché lo storico si spezza e come tenerlo unito.",
        en: "You just ordered a new watch, or you are moving from a watch to a ring. The question that often stalls the purchase is always the same: what about all the history I have built up over the years? Steps, sleep, heart rate, workouts, months or years of data living inside the old device's app. Changing brand usually means starting over from an empty chart. Be careful not to mix up two different cases: this is not about going from Android to iPhone (that is an operating-system change, covered in [From Android to iPhone: how not to lose your fitness data](/blog/da-android-a-iphone-dati-fitness)). This is about changing the brand or model of the wearable itself: you stay on the same phone, but your Garmin watch becomes a Galaxy Watch, or your Fitbit becomes a Colmi ring. Let's look at why the history breaks and how to keep it whole.",
        es: "Acabas de pedir un reloj nuevo, o estás pasando del reloj a un anillo. La pregunta que a menudo frena la compra es siempre la misma: ¿y todo el historial que he acumulado en estos años? Pasos, sueño, ritmo cardíaco, entrenamientos, meses o años de datos que viven dentro de la app del dispositivo antiguo. Cambiar de marca suele significar empezar de nuevo desde un gráfico vacío. Cuidado con no confundir dos casos distintos: aquí no hablamos del paso de Android a iPhone (eso es un cambio de sistema operativo, lo tratamos en [De Android a iPhone: cómo no perder los datos de fitness](/blog/da-android-a-iphone-dati-fitness)). Aquí hablamos de cambiar de marca o de modelo del wearable: sigues con el mismo teléfono, pero tu reloj Garmin se convierte en un Galaxy Watch, o tu Fitbit se convierte en un anillo Colmi. Veamos por qué el historial se rompe y cómo mantenerlo unido.",
        de: "Du hast gerade eine neue Uhr bestellt oder wechselst von der Uhr zu einem Ring. Die Frage, die den Kauf oft bremst, ist immer dieselbe: Was ist mit dem ganzen Verlauf, den ich über die Jahre gesammelt habe? Schritte, Schlaf, Herzfrequenz, Trainings, Monate oder Jahre an Daten, die in der App des alten Geräts leben. Ein Markenwechsel bedeutet meist, wieder bei einem leeren Diagramm anzufangen. Achte darauf, zwei verschiedene Fälle nicht zu verwechseln: Hier geht es nicht um den Wechsel von Android zu iPhone (das ist ein Wechsel des Betriebssystems, den wir in [Von Android zu iPhone: So verlierst du keine Fitnessdaten](/blog/da-android-a-iphone-dati-fitness) behandeln). Hier geht es um den Wechsel der Marke oder des Modells des Wearables selbst: Du bleibst beim selben Telefon, aber deine Garmin-Uhr wird zu einer Galaxy Watch oder dein Fitbit zu einem Colmi-Ring. Schauen wir, warum der Verlauf zerreißt und wie du ihn zusammenhältst.",
        pt: "Você acabou de encomendar um relógio novo, ou está passando do relógio para um anel. A pergunta que muitas vezes trava a compra é sempre a mesma: e todo o histórico que acumulei nesses anos? Passos, sono, frequência cardíaca, treinos, meses ou anos de dados que vivem dentro do app do dispositivo antigo. Trocar de marca geralmente significa recomeçar de um gráfico vazio. Cuidado para não confundir dois casos diferentes: aqui não estamos falando da mudança de Android para iPhone (isso é uma troca de sistema operacional, que tratamos em [De Android para iPhone: como não perder os dados de fitness](/blog/da-android-a-iphone-dati-fitness)). Aqui falamos da troca de marca ou de modelo do próprio wearable: você continua no mesmo telefone, mas o seu relógio Garmin vira um Galaxy Watch, ou o seu Fitbit vira um anel Colmi. Vamos ver por que o histórico se quebra e como mantê-lo inteiro.",
        fr: "Vous venez de commander une nouvelle montre, ou vous passez de la montre à une bague connectée. La question qui freine souvent l'achat est toujours la même : et tout l'historique que j'ai accumulé au fil des années ? Pas, sommeil, fréquence cardiaque, séances d'entraînement, des mois ou des années de données qui vivent dans l'application de l'ancien appareil. Changer de marque signifie en général recommencer à partir d'un graphique vide. Attention à ne pas confondre deux cas différents : il ne s'agit pas ici de passer d'Android à iPhone (ça, c'est un changement de système d'exploitation, que nous traitons dans [D'Android à iPhone : comment ne pas perdre ses données de fitness](/blog/da-android-a-iphone-dati-fitness)). Il s'agit ici de changer la marque ou le modèle du wearable lui-même : vous restez sur le même téléphone, mais votre montre Garmin devient une Galaxy Watch, ou votre Fitbit devient une bague Colmi. Voyons pourquoi l'historique se casse et comment le garder d'un seul tenant.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Perché cambiando marca lo storico si spezza",
        en: "Why changing brand breaks your history",
        es: "Por qué cambiar de marca rompe tu historial",
        de: "Warum ein Markenwechsel deinen Verlauf zerreißt",
        pt: "Por que trocar de marca quebra o seu histórico",
        fr: "Pourquoi changer de marque casse votre historique",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Ogni produttore tiene i tuoi dati dentro la propria app e i propri server. Garmin nel suo ecosistema, Fitbit nel suo, Samsung nel suo, Xiaomi e Amazfit nelle rispettive app companion. Sono silos: progettati per funzionare bene finché resti nella stessa marca, non per farti uscire con tutto lo storico in mano. Quando compri un dispositivo di un'altra marca, la nuova app parte da zero. Il vecchio storico non si trasferisce: resta congelato nell'app precedente, quella che pian piano smetterai di aprire. Nessuna delle due app ti mostra la linea continua della tua storia, prima e dopo il cambio.",
        en: "Every manufacturer keeps your data inside its own app and its own servers. Garmin in its ecosystem, Fitbit in its own, Samsung in its own, Xiaomi and Amazfit in their respective companion apps. They are silos: designed to work well as long as you stay within the same brand, not to let you walk out with your whole history in hand. When you buy a device from another brand, the new app starts from scratch. The old history does not transfer: it stays frozen in the previous app, the one you will slowly stop opening. Neither app shows you the continuous line of your story, before and after the switch.",
        es: "Cada fabricante guarda tus datos dentro de su propia app y sus propios servidores. Garmin en su ecosistema, Fitbit en el suyo, Samsung en el suyo, Xiaomi y Amazfit en sus respectivas apps complementarias. Son silos: pensados para funcionar bien mientras te quedes dentro de la misma marca, no para dejarte salir con todo el historial en la mano. Cuando compras un dispositivo de otra marca, la nueva app empieza de cero. El historial antiguo no se transfiere: se queda congelado en la app anterior, la que poco a poco dejarás de abrir. Ninguna de las dos apps te muestra la línea continua de tu historia, antes y después del cambio.",
        de: "Jeder Hersteller bewahrt deine Daten in seiner eigenen App und auf seinen eigenen Servern auf. Garmin in seinem Ökosystem, Fitbit in seinem, Samsung in seinem, Xiaomi und Amazfit in ihren jeweiligen Begleit-Apps. Das sind Silos: dafür gemacht, gut zu funktionieren, solange du bei derselben Marke bleibst, nicht dafür, dich mit deinem gesamten Verlauf in der Hand hinauszulassen. Wenn du ein Gerät einer anderen Marke kaufst, startet die neue App bei null. Der alte Verlauf wandert nicht mit: Er bleibt in der vorherigen App eingefroren, die du nach und nach nicht mehr öffnest. Keine der beiden Apps zeigt dir die durchgehende Linie deiner Geschichte, vor und nach dem Wechsel.",
        pt: "Cada fabricante guarda os seus dados dentro do próprio app e dos próprios servidores. A Garmin no seu ecossistema, a Fitbit no dela, a Samsung no dela, a Xiaomi e a Amazfit nos respectivos apps complementares. São silos: feitos para funcionar bem enquanto você fica dentro da mesma marca, não para deixar você sair com todo o histórico na mão. Quando você compra um dispositivo de outra marca, o novo app começa do zero. O histórico antigo não é transferido: fica congelado no app anterior, aquele que aos poucos você vai deixar de abrir. Nenhum dos dois apps mostra a linha contínua da sua história, antes e depois da troca.",
        fr: "Chaque fabricant garde vos données dans sa propre application et sur ses propres serveurs. Garmin dans son écosystème, Fitbit dans le sien, Samsung dans le sien, Xiaomi et Amazfit dans leurs applications compagnons respectives. Ce sont des silos : conçus pour bien fonctionner tant que vous restez dans la même marque, pas pour vous laisser repartir avec tout votre historique en main. Quand vous achetez un appareil d'une autre marque, la nouvelle application démarre de zéro. L'ancien historique ne se transfère pas : il reste figé dans l'application précédente, celle que vous cesserez peu à peu d'ouvrir. Aucune des deux applications ne vous montre la ligne continue de votre histoire, avant et après le changement.",
      },
    },
    {
      type: "list",
      items: {
        it: [
          "La cronologia dei passi e delle calorie si spezza in due grafici separati, uno per app.",
          "Il sonno con le fasi (leggero, profondo, REM) riparte da zero nella nuova app.",
          "Battito a riposo e andamento dell'HRV perdono la base di confronto con i mesi precedenti.",
          "Gli allenamenti registrati con il vecchio dispositivo restano nell'app vecchia, non nella nuova.",
          "Se in futuro cambi di nuovo marca, il problema si ripete e i pezzi da consultare diventano tre.",
        ],
        en: [
          "Your steps and calories history splits into two separate charts, one per app.",
          "Sleep with its stages (light, deep, REM) restarts from zero in the new app.",
          "Resting heart rate and HRV trends lose their point of comparison with the previous months.",
          "Workouts recorded with the old device stay in the old app, not the new one.",
          "If you switch brands again later, the problem repeats and you now have three places to check.",
        ],
        es: [
          "El historial de pasos y calorías se parte en dos gráficos separados, uno por app.",
          "El sueño con sus fases (ligero, profundo, REM) vuelve a empezar desde cero en la nueva app.",
          "El ritmo cardíaco en reposo y la tendencia de la HRV pierden la base de comparación con los meses anteriores.",
          "Los entrenamientos registrados con el dispositivo antiguo se quedan en la app antigua, no en la nueva.",
          "Si en el futuro vuelves a cambiar de marca, el problema se repite y las piezas por consultar pasan a ser tres.",
        ],
        de: [
          "Der Verlauf von Schritten und Kalorien zerfällt in zwei getrennte Diagramme, eines pro App.",
          "Der Schlaf mit seinen Phasen (leicht, tief, REM) startet in der neuen App wieder bei null.",
          "Ruheherzfrequenz und der HRV-Verlauf verlieren ihre Vergleichsbasis zu den vorherigen Monaten.",
          "Die mit dem alten Gerät aufgezeichneten Trainings bleiben in der alten App, nicht in der neuen.",
          "Wechselst du später erneut die Marke, wiederholt sich das Problem und du hast drei Stellen zum Nachschauen.",
        ],
        pt: [
          "O histórico de passos e de calorias se divide em dois gráficos separados, um por app.",
          "O sono com as suas fases (leve, profundo, REM) recomeça do zero no novo app.",
          "A frequência cardíaca em repouso e a tendência da VFC perdem a base de comparação com os meses anteriores.",
          "Os treinos registrados com o dispositivo antigo ficam no app antigo, não no novo.",
          "Se no futuro você trocar de marca de novo, o problema se repete e passam a ser três os lugares para consultar.",
        ],
        fr: [
          "L'historique de vos pas et de vos calories se scinde en deux graphiques distincts, un par application.",
          "Le sommeil avec ses phases (léger, profond, paradoxal) repart de zéro dans la nouvelle application.",
          "La fréquence cardiaque au repos et la tendance de la VFC perdent leur point de comparaison avec les mois précédents.",
          "Les séances enregistrées avec l'ancien appareil restent dans l'ancienne application, pas dans la nouvelle.",
          "Si vous changez de nouveau de marque plus tard, le problème se répète et vous avez désormais trois endroits à consulter.",
        ],
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "La continuità vive nel cloud, non nel dispositivo",
        en: "Continuity lives in the cloud, not in the device",
        es: "La continuidad vive en la nube, no en el dispositivo",
        de: "Die Kontinuität lebt in der Cloud, nicht im Gerät",
        pt: "A continuidade vive na nuvem, não no dispositivo",
        fr: "La continuité vit dans le cloud, pas dans l'appareil",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "FitMesh ribalta la logica: invece di legare lo storico a un dispositivo, lo tiene sul tuo account. L'orologio o l'anello sono soltanto la fonte del dato del momento; se domani cambi hardware, la fonte cambia ma lo storico resta lo stesso, sullo stesso account. FitMesh Sync legge i dati salute dei tuoi wearable e li mostra in un pannello web unificato, deduplicati: lo stesso passo non viene contato due volte, anche se per qualche giorno tieni due dispositivi in parallelo. Puoi consultare tutto da qualsiasi browser, come spieghiamo in [Vedere i dati del wearable dal browser del PC](/blog/vedere-dati-wearable-browser-pc), e se indossi più dispositivi insieme la dashboard li unisce senza [contare i dati doppi](/blog/piu-smartwatch-insieme-dati-doppi).",
        en: "FitMesh flips the logic: instead of tying your history to a device, it keeps it on your account. The watch or ring is only the source of the moment's data; if you change hardware tomorrow, the source changes but the history stays the same, on the same account. FitMesh Sync reads the health data from your wearables and shows it in a unified web panel, deduplicated: the same step is not counted twice, even if you run two devices in parallel for a few days. You can view everything from any browser, as we explain in [See your wearable data from a PC browser](/blog/vedere-dati-wearable-browser-pc), and if you wear several devices at once the dashboard merges them without [counting the data twice](/blog/piu-smartwatch-insieme-dati-doppi).",
        es: "FitMesh le da la vuelta a la lógica: en lugar de atar tu historial a un dispositivo, lo conserva en tu cuenta. El reloj o el anillo son solo la fuente del dato del momento; si mañana cambias de hardware, la fuente cambia pero el historial sigue siendo el mismo, en la misma cuenta. FitMesh Sync lee los datos de salud de tus wearables y los muestra en un panel web unificado, sin duplicados: el mismo paso no se cuenta dos veces, aunque durante unos días lleves dos dispositivos en paralelo. Puedes consultarlo todo desde cualquier navegador, como explicamos en [Ver los datos del wearable desde el navegador del PC](/blog/vedere-dati-wearable-browser-pc), y si llevas varios dispositivos a la vez el panel los une sin [contar los datos por duplicado](/blog/piu-smartwatch-insieme-dati-doppi).",
        de: "FitMesh dreht die Logik um: Statt deinen Verlauf an ein Gerät zu binden, bewahrt es ihn in deinem Konto auf. Die Uhr oder der Ring sind nur die Quelle des aktuellen Werts; wechselst du morgen die Hardware, ändert sich die Quelle, aber der Verlauf bleibt derselbe, im selben Konto. FitMesh Sync liest die Gesundheitsdaten deiner Wearables und zeigt sie in einem einheitlichen Web-Dashboard, ohne Dubletten: Derselbe Schritt wird nicht doppelt gezählt, selbst wenn du einige Tage lang zwei Geräte parallel nutzt. Du kannst alles von jedem Browser aus ansehen, wie wir in [Wearable-Daten im PC-Browser ansehen](/blog/vedere-dati-wearable-browser-pc) erklären, und wenn du mehrere Geräte gleichzeitig trägst, führt das Dashboard sie zusammen, ohne [die Daten doppelt zu zählen](/blog/piu-smartwatch-insieme-dati-doppi).",
        pt: "O FitMesh inverte a lógica: em vez de amarrar o seu histórico a um dispositivo, ele o mantém na sua conta. O relógio ou o anel são apenas a fonte do dado do momento; se amanhã você trocar de hardware, a fonte muda, mas o histórico continua o mesmo, na mesma conta. O FitMesh Sync lê os dados de saúde dos seus wearables e os mostra em um painel web unificado, sem duplicatas: o mesmo passo não é contado duas vezes, mesmo que por alguns dias você use dois dispositivos em paralelo. Você pode consultar tudo de qualquer navegador, como explicamos em [Ver os dados do wearable pelo navegador do PC](/blog/vedere-dati-wearable-browser-pc), e se você usar vários dispositivos ao mesmo tempo o painel os reúne sem [contar os dados em dobro](/blog/piu-smartwatch-insieme-dati-doppi).",
        fr: "FitMesh inverse la logique : au lieu de lier votre historique à un appareil, il le garde sur votre compte. La montre ou la bague ne sont que la source de la donnée du moment ; si vous changez de matériel demain, la source change mais l'historique reste le même, sur le même compte. FitMesh Sync lit les données de santé de vos wearables et les affiche dans un tableau de bord web unifié, dédoublonné : le même pas n'est pas compté deux fois, même si vous utilisez deux appareils en parallèle pendant quelques jours. Vous pouvez tout consulter depuis n'importe quel navigateur, comme nous l'expliquons dans [Voir les données de son wearable depuis le navigateur du PC](/blog/vedere-dati-wearable-browser-pc), et si vous portez plusieurs appareils à la fois, le tableau de bord les réunit sans [compter les données en double](/blog/piu-smartwatch-insieme-dati-doppi).",
      },
    },
    {
      type: "callout",
      variant: "info",
      title: {
        it: "Come FitMesh legge i tuoi dispositivi",
        en: "How FitMesh reads your devices",
        es: "Cómo lee FitMesh tus dispositivos",
        de: "Wie FitMesh deine Geräte ausliest",
        pt: "Como o FitMesh lê os seus dispositivos",
        fr: "Comment FitMesh lit vos appareils",
      },
      body: {
        it: "Su Android, FitMesh Sync è disponibile su Google Play e legge i dati via Health Connect, l'hub salute del telefono a cui la maggior parte delle app dei produttori scrive. Legge anche l'anello Colmi (serie R Colmi (R02–R10) e modelli compatibili) direttamente via Bluetooth, senza bisogno dell'app companion. Su iPhone l'app è disponibile sull'App Store, incluse tutte le storefront dell'Unione Europea, legge Apple Salute nativamente e si collega allo stesso modo via Bluetooth al Colmi Ring — mai tramite Health Connect, che è specifico di Android. Se una marca alimenta Health Connect o Apple Salute, il suo storico entra nel tuo account FitMesh insieme a quello delle altre. Approfondiamo il meccanismo in [Come funziona Health Connect](/blog/come-funziona-health-connect).",
        en: "On Android, FitMesh Sync is available on Google Play and reads data via Health Connect, the phone's health hub that most manufacturer apps write to. It also reads the Colmi ring (Colmi R-series (R02–R10) and compatible models) directly over Bluetooth, with no companion app needed. On iPhone the app is live on the App Store, including all European Union storefronts, reads Apple Health natively, and connects the same way over Bluetooth to the Colmi Ring — never through Health Connect, which is Android-specific. If a brand feeds Health Connect or Apple Health, its history flows into your FitMesh account alongside the others. We go deeper in [How Health Connect works](/blog/come-funziona-health-connect).",
        es: "En Android, FitMesh Sync está disponible en Google Play y lee los datos vía Health Connect, el centro de salud del teléfono al que escribe la mayoría de las apps de los fabricantes. También lee el anillo Colmi (serie R de Colmi (R02–R10) y modelos compatibles) directamente por Bluetooth, sin necesidad de la app complementaria. En iPhone la app está activa en la App Store, incluidas todas las tiendas de la Unión Europea, lee Apple Salud de forma nativa y se conecta del mismo modo por Bluetooth al anillo Colmi — nunca a través de Health Connect, que es específico de Android. Si una marca alimenta Health Connect o Apple Health, su historial entra en tu cuenta de FitMesh junto con el de las demás. Lo explicamos a fondo en [Cómo funciona Health Connect](/blog/come-funziona-health-connect).",
        de: "Unter Android ist FitMesh Sync bei Google Play verfügbar und liest die Daten über Health Connect, den Gesundheits-Hub des Telefons, in den die meisten Hersteller-Apps schreiben. Es liest außerdem den Colmi-Ring (Colmi R-Serie (R02–R10) und kompatible Modelle) direkt über Bluetooth, ohne Begleit-App. Auf dem iPhone ist die App im App Store live, einschließlich aller Storefronts der Europäischen Union, liest Apple Health nativ aus und verbindet sich auf dieselbe Weise per Bluetooth mit dem Colmi-Ring — niemals über Health Connect, das Android-spezifisch ist. Wenn eine Marke Health Connect oder Apple Health speist, fließt ihr Verlauf zusammen mit den anderen in dein FitMesh-Konto. Mehr dazu in [Wie Health Connect funktioniert](/blog/come-funziona-health-connect).",
        pt: "No Android, o FitMesh Sync está disponível no Google Play e lê os dados via Health Connect, o hub de saúde do telefone no qual a maioria dos apps dos fabricantes escreve. Ele também lê o anel Colmi (série R da Colmi (R02–R10) e modelos compatíveis) diretamente por Bluetooth, sem precisar do app complementar. No iPhone o app está ativo na App Store, incluindo todas as lojas da União Europeia, lê o Apple Saúde nativamente e se conecta da mesma forma por Bluetooth ao anel Colmi — nunca via Health Connect, que é específico do Android. Se uma marca alimenta o Health Connect ou o Apple Health, o histórico dela entra na sua conta FitMesh junto com o das outras. Explicamos o mecanismo a fundo em [Como funciona o Health Connect](/blog/come-funziona-health-connect).",
        fr: "Sur Android, FitMesh Sync est disponible sur Google Play et lit les données via Health Connect, le hub santé du téléphone dans lequel la plupart des applications de fabricants écrivent. Il lit aussi la bague Colmi (série R Colmi (R02–R10) et modèles compatibles) directement par Bluetooth, sans application compagnon. Sur iPhone, l'application est active sur l'App Store, y compris dans toutes les boutiques de l'Union européenne, lit Apple Santé nativement et se connecte de la même façon en Bluetooth à la bague Colmi — jamais via Health Connect, qui est spécifique à Android. Si une marque alimente Health Connect ou Apple Health, son historique arrive dans votre compte FitMesh aux côtés des autres. Nous détaillons le mécanisme dans [Comment fonctionne Health Connect](/blog/come-funziona-health-connect).",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Checklist: prima, durante e dopo il cambio",
        en: "Checklist: before, during and after the switch",
        es: "Checklist: antes, durante y después del cambio",
        de: "Checkliste: vor, während und nach dem Wechsel",
        pt: "Checklist: antes, durante e depois da troca",
        fr: "Checklist : avant, pendant et après le changement",
      },
    },
    {
      type: "list",
      ordered: true,
      items: {
        it: [
          "**Prima:** installa FitMesh Sync su Android mentre usi ancora il vecchio dispositivo e collegalo, così lo storico recente entra subito nel tuo account.",
          "**Prima:** verifica che il vecchio orologio scriva su Health Connect e lascia sincronizzare qualche giorno, per portare dentro la base storica.",
          "**Durante:** ricevuto il nuovo wearable, collegalo alla sua app companion (o, per l'anello Colmi, direttamente a FitMesh via Bluetooth) e concedi i permessi a Health Connect.",
          "**Durante:** tieni entrambi i dispositivi attivi per qualche giorno se vuoi una transizione morbida; la deduplicazione evita i doppi conteggi.",
          "**Dopo:** apri la dashboard web e controlla che la linea di passi, sonno e battito prosegua senza buchi attraverso la data del cambio.",
          "**Dopo:** quando sei sicuro, puoi smettere di indossare il vecchio dispositivo; lo storico resta comunque nel tuo account, indipendente dall'hardware.",
        ],
        en: [
          "**Before:** install FitMesh Sync on Android while you are still using the old device and connect it, so your recent history enters your account right away.",
          "**Before:** check that the old watch writes to Health Connect and let it sync for a few days, to pull in the historical baseline.",
          "**During:** once the new wearable arrives, connect it to its companion app (or, for the Colmi ring, directly to FitMesh over Bluetooth) and grant the Health Connect permissions.",
          "**During:** keep both devices active for a few days if you want a soft transition; deduplication prevents double counting.",
          "**After:** open the web dashboard and check that the line of steps, sleep and heart rate continues with no gaps across the switch date.",
          "**After:** once you are confident, you can stop wearing the old device; the history stays in your account anyway, independent of the hardware.",
        ],
        es: [
          "**Antes:** instala FitMesh Sync en Android mientras aún usas el dispositivo antiguo y conéctalo, así el historial reciente entra enseguida en tu cuenta.",
          "**Antes:** comprueba que el reloj antiguo escribe en Health Connect y déjalo sincronizar unos días, para incorporar la base histórica.",
          "**Durante:** cuando recibas el nuevo wearable, conéctalo a su app complementaria (o, para el anillo Colmi, directamente a FitMesh por Bluetooth) y concede los permisos de Health Connect.",
          "**Durante:** mantén ambos dispositivos activos unos días si quieres una transición suave; la eliminación de duplicados evita los conteos dobles.",
          "**Después:** abre el panel web y comprueba que la línea de pasos, sueño y ritmo cardíaco continúa sin huecos a través de la fecha del cambio.",
          "**Después:** cuando estés seguro, puedes dejar de llevar el dispositivo antiguo; el historial se queda igualmente en tu cuenta, independiente del hardware.",
        ],
        de: [
          "**Vorher:** Installiere FitMesh Sync unter Android, während du das alte Gerät noch nutzt, und verbinde es, damit dein jüngster Verlauf sofort in dein Konto gelangt.",
          "**Vorher:** Prüfe, dass die alte Uhr in Health Connect schreibt, und lass sie einige Tage synchronisieren, um die historische Basis mitzunehmen.",
          "**Während:** Sobald das neue Wearable ankommt, verbinde es mit seiner Begleit-App (oder, beim Colmi-Ring, direkt mit FitMesh über Bluetooth) und erteile die Health-Connect-Berechtigungen.",
          "**Während:** Halte beide Geräte einige Tage aktiv, wenn du einen sanften Übergang willst; die Entfernung von Dubletten verhindert doppeltes Zählen.",
          "**Danach:** Öffne das Web-Dashboard und prüfe, dass die Linie aus Schritten, Schlaf und Herzfrequenz über das Wechseldatum hinweg ohne Lücken weiterläuft.",
          "**Danach:** Wenn du sicher bist, kannst du das alte Gerät ablegen; der Verlauf bleibt ohnehin in deinem Konto, unabhängig von der Hardware.",
        ],
        pt: [
          "**Antes:** instale o FitMesh Sync no Android enquanto ainda usa o dispositivo antigo e conecte-o, assim o histórico recente já entra na sua conta.",
          "**Antes:** verifique se o relógio antigo escreve no Health Connect e deixe sincronizar por alguns dias, para trazer a base histórica.",
          "**Durante:** ao receber o novo wearable, conecte-o ao seu app complementar (ou, no caso do anel Colmi, diretamente ao FitMesh por Bluetooth) e conceda as permissões do Health Connect.",
          "**Durante:** mantenha os dois dispositivos ativos por alguns dias se quiser uma transição suave; a remoção de duplicatas evita a contagem em dobro.",
          "**Depois:** abra o painel web e confira se a linha de passos, sono e frequência cardíaca continua sem lacunas ao longo da data da troca.",
          "**Depois:** quando estiver seguro, você pode parar de usar o dispositivo antigo; o histórico permanece na sua conta de qualquer forma, independente do hardware.",
        ],
        fr: [
          "**Avant :** installez FitMesh Sync sur Android pendant que vous utilisez encore l'ancien appareil et connectez-le, pour que votre historique récent entre tout de suite dans votre compte.",
          "**Avant :** vérifiez que l'ancienne montre écrit dans Health Connect et laissez-la synchroniser pendant quelques jours, pour récupérer la base historique.",
          "**Pendant :** dès que le nouveau wearable arrive, connectez-le à son application compagnon (ou, pour la bague Colmi, directement à FitMesh par Bluetooth) et accordez les autorisations Health Connect.",
          "**Pendant :** gardez les deux appareils actifs pendant quelques jours si vous voulez une transition en douceur ; le dédoublonnage évite le double comptage.",
          "**Après :** ouvrez le tableau de bord web et vérifiez que la courbe des pas, du sommeil et de la fréquence cardiaque se poursuit sans trous au fil de la date du changement.",
          "**Après :** quand vous êtes sûr de vous, vous pouvez cesser de porter l'ancien appareil ; l'historique reste de toute façon dans votre compte, indépendamment du matériel.",
        ],
      },
    },
    {
      type: "comparison",
      aTitle: {
        it: "Con la sola app del produttore",
        en: "With the manufacturer app alone",
        es: "Solo con la app del fabricante",
        de: "Nur mit der Hersteller-App",
        pt: "Só com o app do fabricante",
        fr: "Avec la seule application du fabricant",
      },
      aItems: {
        it: [
          "Lo storico è legato alla marca: cambi dispositivo, riparti da un grafico vuoto.",
          "Ogni cambio aggiunge un'app da tenere solo per consultare il passato.",
          "Confronti prima/dopo impossibili: i dati vivono in silos separati.",
          "Se chiudi il vecchio account, rischi di perdere lo storico.",
        ],
        en: [
          "History is tied to the brand: change device, start from an empty chart.",
          "Every switch adds one more app kept around just to look at the past.",
          "Before/after comparisons are impossible: the data lives in separate silos.",
          "If you close the old account, you risk losing the history.",
        ],
        es: [
          "El historial está atado a la marca: cambias de dispositivo, empiezas desde un gráfico vacío.",
          "Cada cambio añade una app que conservas solo para consultar el pasado.",
          "Las comparaciones antes/después son imposibles: los datos viven en silos separados.",
          "Si cierras la cuenta antigua, corres el riesgo de perder el historial.",
        ],
        de: [
          "Der Verlauf ist an die Marke gebunden: Gerät wechseln heißt, bei einem leeren Diagramm anfangen.",
          "Jeder Wechsel fügt eine weitere App hinzu, die du nur zum Nachschauen der Vergangenheit behältst.",
          "Vorher/nachher-Vergleiche sind unmöglich: Die Daten liegen in getrennten Silos.",
          "Wenn du das alte Konto schließt, riskierst du, den Verlauf zu verlieren.",
        ],
        pt: [
          "O histórico está preso à marca: troca de dispositivo, recomeça de um gráfico vazio.",
          "Cada troca acrescenta mais um app que você guarda só para consultar o passado.",
          "Comparações antes/depois são impossíveis: os dados vivem em silos separados.",
          "Se você fechar a conta antiga, corre o risco de perder o histórico.",
        ],
        fr: [
          "L'historique est lié à la marque : on change d'appareil, on repart d'un graphique vide.",
          "Chaque changement ajoute une application de plus, gardée juste pour consulter le passé.",
          "Les comparaisons avant/après sont impossibles : les données vivent dans des silos séparés.",
          "Si vous fermez l'ancien compte, vous risquez de perdre l'historique.",
        ],
      },
      bTitle: {
        it: "Con FitMesh",
        en: "With FitMesh",
        es: "Con FitMesh",
        de: "Mit FitMesh",
        pt: "Com o FitMesh",
        fr: "Avec FitMesh",
      },
      bItems: {
        it: [
          "Lo storico è sul tuo account, non sul dispositivo.",
          "Marche diverse confluiscono in un'unica dashboard, deduplicate.",
          "La linea temporale prosegue attraverso il cambio hardware.",
          "Cambi orologio o anello quante volte vuoi, i dati restano tuoi.",
        ],
        en: [
          "History lives on your account, not on the device.",
          "Different brands flow into one dashboard, deduplicated.",
          "The timeline continues across the hardware change.",
          "Change watch or ring as often as you like, the data stays yours.",
        ],
        es: [
          "El historial vive en tu cuenta, no en el dispositivo.",
          "Marcas distintas confluyen en un único panel, sin duplicados.",
          "La línea temporal continúa a través del cambio de hardware.",
          "Cambia de reloj o de anillo tantas veces como quieras, los datos siguen siendo tuyos.",
        ],
        de: [
          "Der Verlauf lebt in deinem Konto, nicht auf dem Gerät.",
          "Verschiedene Marken fließen in einem Dashboard zusammen, ohne Dubletten.",
          "Die Zeitachse läuft über den Hardware-Wechsel hinweg weiter.",
          "Wechsle Uhr oder Ring so oft du willst, die Daten bleiben deine.",
        ],
        pt: [
          "O histórico fica na sua conta, não no dispositivo.",
          "Marcas diferentes convergem em um único painel, sem duplicatas.",
          "A linha do tempo continua ao longo da troca de hardware.",
          "Troque de relógio ou de anel quantas vezes quiser, os dados continuam sendo seus.",
        ],
        fr: [
          "L'historique vit sur votre compte, pas sur l'appareil.",
          "Des marques différentes convergent dans un seul tableau de bord, dédoublonnées.",
          "La chronologie se poursuit au fil du changement de matériel.",
          "Changez de montre ou de bague aussi souvent que vous voulez, les données restent les vôtres.",
        ],
      },
    },
    {
      type: "table",
      caption: {
        it: "Cosa succede allo storico in alcuni scenari di cambio",
        en: "What happens to your history in a few switch scenarios",
        es: "Qué le pasa a tu historial en algunos escenarios de cambio",
        de: "Was in einigen Wechselszenarien mit deinem Verlauf passiert",
        pt: "O que acontece com o histórico em alguns cenários de troca",
        fr: "Ce qu'il advient de l'historique dans quelques scénarios de changement",
      },
      headers: {
        it: ["Cambio", "Con la sola app del produttore", "Con FitMesh"],
        en: ["Switch", "With the manufacturer app alone", "With FitMesh"],
        es: ["Cambio", "Solo con la app del fabricante", "Con FitMesh"],
        de: ["Wechsel", "Nur mit der Hersteller-App", "Mit FitMesh"],
        pt: ["Troca", "Só com o app do fabricante", "Com o FitMesh"],
        fr: ["Changement", "Avec la seule application du fabricant", "Avec FitMesh"],
      },
      rows: [
        {
          it: ["Da Garmin a Galaxy Watch", "Due storici separati", "Storico unico e continuo"],
          en: ["Garmin to Galaxy Watch", "Two separate histories", "One continuous history"],
          es: ["De Garmin a Galaxy Watch", "Dos historiales separados", "Un historial único y continuo"],
          de: ["Von Garmin zu Galaxy Watch", "Zwei getrennte Verläufe", "Ein durchgehender Verlauf"],
          pt: ["De Garmin para Galaxy Watch", "Dois históricos separados", "Um histórico único e contínuo"],
          fr: ["De Garmin à Galaxy Watch", "Deux historiques séparés", "Un historique continu"],
        },
        {
          it: ["Da Fitbit ad anello Colmi", "Riparti da zero sul sonno", "Sonno e passi proseguono"],
          en: ["Fitbit to Colmi ring", "Sleep restarts from zero", "Sleep and steps continue"],
          es: ["De Fitbit a anillo Colmi", "El sueño vuelve a empezar de cero", "El sueño y los pasos continúan"],
          de: ["Von Fitbit zu Colmi-Ring", "Der Schlaf startet wieder bei null", "Schlaf und Schritte laufen weiter"],
          pt: ["De Fitbit para anel Colmi", "O sono recomeça do zero", "Sono e passos continuam"],
          fr: ["De Fitbit à la bague Colmi", "Le sommeil repart de zéro", "Le sommeil et les pas se poursuivent"],
        },
        {
          it: ["Da Xiaomi o Amazfit a Pixel Watch", "Grafici spezzati", "Un'unica linea temporale"],
          en: ["Xiaomi or Amazfit to Pixel Watch", "Split charts", "A single timeline"],
          es: ["De Xiaomi o Amazfit a Pixel Watch", "Gráficos partidos", "Una única línea temporal"],
          de: ["Von Xiaomi oder Amazfit zu Pixel Watch", "Zerrissene Diagramme", "Eine einzige Zeitachse"],
          pt: ["De Xiaomi ou Amazfit para Pixel Watch", "Gráficos quebrados", "Uma única linha do tempo"],
          fr: ["De Xiaomi ou Amazfit à Pixel Watch", "Graphiques scindés", "Une seule chronologie"],
        },
        {
          it: ["Da orologio ad anello (o viceversa)", "App diverse, nessun confronto", "Fusione giorno/notte in un pannello"],
          en: ["Watch to ring (or the other way)", "Different apps, no comparison", "Day/night fusion in one panel"],
          es: ["De reloj a anillo (o al revés)", "Apps distintas, sin comparación", "Fusión día/noche en un panel"],
          de: ["Von Uhr zu Ring (oder umgekehrt)", "Verschiedene Apps, kein Vergleich", "Tag/Nacht-Fusion in einem Panel"],
          pt: ["De relógio para anel (ou o contrário)", "Apps diferentes, sem comparação", "Fusão dia/noite em um painel"],
          fr: ["De la montre à la bague (ou l'inverse)", "Applications différentes, aucune comparaison", "Fusion jour/nuit dans un seul tableau de bord"],
        },
        {
          it: ["Secondo cambio in un anno", "Tre app, tre storici", "Sempre lo stesso account"],
          en: ["Second switch within a year", "Three apps, three histories", "Always the same account"],
          es: ["Segundo cambio en un año", "Tres apps, tres historiales", "Siempre la misma cuenta"],
          de: ["Zweiter Wechsel innerhalb eines Jahres", "Drei Apps, drei Verläufe", "Immer dasselbe Konto"],
          pt: ["Segunda troca em um ano", "Três apps, três históricos", "Sempre a mesma conta"],
          fr: ["Deuxième changement dans l'année", "Trois applications, trois historiques", "Toujours le même compte"],
        },
      ],
    },
    {
      type: "cta",
      title: {
        it: "Cambi wearable? Porta lo storico con te",
        en: "Switching wearable? Take your history with you",
        es: "¿Cambias de wearable? Llévate tu historial contigo",
        de: "Wearable wechseln? Nimm deinen Verlauf mit",
        pt: "Vai trocar de wearable? Leve o histórico com você",
        fr: "Vous changez de wearable ? Emportez votre historique avec vous",
      },
      body: {
        it: "FitMesh Sync è disponibile ora su Android e su iPhone (live sull'App Store, incluse tutte le storefront dell'Unione Europea), con dashboard web inclusa. I primi 1000 iscritti founder (entro il 31 luglio 2026) hanno ricevuto il Pro a vita gratis; oggi c'è una prova completa di 14 giorni, poi lo tieni con un piccolo abbonamento o con lo sblocco a vita (circa un caffè ogni sei mesi, o meno di una pizza). Scaricala oggi e inizia a costruire uno storico che sopravvive al prossimo cambio di orologio.",
        en: "FitMesh Sync is available now on Android and on iPhone (live on the App Store, including all European Union storefronts), with the web dashboard included. The first 1,000 founder sign-ups (by July 31, 2026) got lifetime Pro free; today there is a full 14-day trial, then you keep it with a small subscription or a one-time lifetime unlock (about a coffee every six months, or less than a pizza). Download it today and start building a history that survives your next change of watch.",
        es: "FitMesh Sync ya está disponible en Android y en iPhone (activo en la App Store, incluidas todas las tiendas de la Unión Europea), con el panel web incluido. Los primeros 1000 registrados founder (hasta el 31 de julio de 2026) consiguieron el Pro de por vida gratis; hoy hay una prueba completa de 14 días, y luego lo mantienes con una pequeña suscripción o con el desbloqueo de por vida (como un café cada seis meses, o menos que una pizza). Descárgala hoy y empieza a construir un historial que sobreviva a tu próximo cambio de reloj.",
        de: "FitMesh Sync ist ab sofort für Android und für iPhone verfügbar (im App Store live, einschließlich aller Storefronts der Europäischen Union), inklusive Web-Dashboard. Die ersten 1.000 founder-Anmeldungen (bis 31. Juli 2026) haben Pro lebenslang gratis erhalten; heute gibt es eine volle 14-tägige Testphase, und anschließend behältst du es mit einem kleinen Abo oder der einmaligen Freischaltung fürs Leben (weniger als ein Kaffee alle sechs Monate oder weniger als eine Pizza). Lade sie dir noch heute herunter und beginne einen Verlauf aufzubauen, der deinen nächsten Uhrenwechsel übersteht.",
        pt: "O FitMesh Sync já está disponível no Android e no iPhone (ativo na App Store, incluindo todas as lojas da União Europeia), com o painel web incluído. Os primeiros 1000 inscritos founder (até 31 de julho de 2026) ganharam o Pro vitalício de graça; hoje há uma avaliação completa de 14 dias e, em seguida, você o mantém com uma pequena assinatura ou com o desbloqueio vitalício (como um café a cada seis meses, ou menos que uma pizza). Baixe-o hoje e comece a construir um histórico que sobrevive à sua próxima troca de relógio.",
        fr: "FitMesh Sync est disponible dès maintenant sur Android et sur iPhone (actif sur l'App Store, y compris dans toutes les boutiques de l'Union européenne), avec le tableau de bord web inclus. Les 1000 premiers inscrits founder (jusqu'au 31 juillet 2026) ont obtenu le Pro à vie gratuitement ; aujourd'hui, il y a un essai complet de 14 jours, puis vous le gardez avec un petit abonnement ou un déblocage à vie en un seul paiement (moins qu'un café tous les six mois, ou moins qu'une pizza). Téléchargez-la dès aujourd'hui et commencez à bâtir un historique qui survit à votre prochain changement de montre.",
      },
      ctaLabel: {
        it: "Prova FitMesh gratuitamente →",
        en: "Try FitMesh free →",
        es: "Prueba FitMesh gratis →",
        de: "Teste FitMesh kostenlos →",
        pt: "Experimente o FitMesh gratuitamente →",
        fr: "Essayez FitMesh gratuitement →",
      },
      ctaHref: {
        it: "/it#download",
        en: "/en#download",
        es: "/es#download",
        de: "/de#download",
        pt: "/pt#download",
        fr: "/fr#download",
      },
    },
  ],
  faq: [
    {
      q: {
        it: "Cambiando marca di smartwatch perdo lo storico dei dati?",
        en: "If I change smartwatch brand, do I lose my data history?",
        es: "Si cambio de marca de smartwatch, ¿pierdo el historial de datos?",
        de: "Verliere ich meinen Datenverlauf, wenn ich die Smartwatch-Marke wechsle?",
        pt: "Se eu trocar de marca de smartwatch, perco o histórico de dados?",
        fr: "Si je change de marque de montre connectée, est-ce que je perds mon historique de données ?",
      },
      a: {
        it: "Con le sole app dei produttori, di fatto sì: ogni app parte da zero e il passato resta nella vecchia. Con FitMesh no: lo storico è legato al tuo account, non al dispositivo, quindi resta lì anche quando cambi orologio o anello.",
        en: "With the manufacturer apps alone, effectively yes: each app starts from zero and the past stays in the old one. With FitMesh, no: your history is tied to your account, not to the device, so it stays there even when you change watch or ring.",
        es: "Solo con las apps de los fabricantes, en la práctica sí: cada app empieza desde cero y el pasado se queda en la antigua. Con FitMesh, no: tu historial está atado a tu cuenta, no al dispositivo, así que se queda ahí incluso cuando cambias de reloj o de anillo.",
        de: "Nur mit den Hersteller-Apps praktisch ja: Jede App startet bei null und die Vergangenheit bleibt in der alten. Mit FitMesh nicht: Dein Verlauf ist an dein Konto gebunden, nicht an das Gerät, und bleibt daher erhalten, auch wenn du Uhr oder Ring wechselst.",
        pt: "Só com os apps dos fabricantes, na prática sim: cada app começa do zero e o passado fica no antigo. Com o FitMesh, não: o seu histórico está ligado à sua conta, não ao dispositivo, então ele permanece lá mesmo quando você troca de relógio ou de anel.",
        fr: "Avec les seules applications des fabricants, en pratique oui : chaque application démarre de zéro et le passé reste dans l'ancienne. Avec FitMesh, non : votre historique est lié à votre compte, pas à l'appareil, il reste donc en place même quand vous changez de montre ou de bague.",
      },
    },
    {
      q: {
        it: "Funziona tra marche diverse?",
        en: "Does it work across different brands?",
        es: "¿Funciona entre marcas distintas?",
        de: "Funktioniert es markenübergreifend?",
        pt: "Funciona entre marcas diferentes?",
        fr: "Est-ce que ça marche entre marques différentes ?",
      },
      a: {
        it: "Sì. Su Android FitMesh legge i dati via Health Connect, a cui scrive la maggior parte delle app dei produttori, e legge l'anello Colmi direttamente via Bluetooth. Marche diverse confluiscono così nella stessa dashboard, deduplicate. Su iPhone l'app (già live sull'App Store) legge Apple Salute nativamente e si collega direttamente via Bluetooth al Colmi Ring — mai tramite Health Connect, che è specifico di Android.",
        en: "Yes. On Android FitMesh reads data via Health Connect, which most manufacturer apps write to, and reads the Colmi ring directly over Bluetooth. Different brands thus flow into the same dashboard, deduplicated. On iPhone the app (already live on the App Store) reads Apple Health natively and connects directly over Bluetooth to the Colmi Ring — never through Health Connect, which is Android-specific.",
        es: "Sí. En Android FitMesh lee los datos vía Health Connect, al que escribe la mayoría de las apps de los fabricantes, y lee el anillo Colmi directamente por Bluetooth. Así, marcas distintas confluyen en el mismo panel, sin duplicados. En iPhone la app (ya activa en la App Store) lee Apple Salud de forma nativa y se conecta directamente por Bluetooth al anillo Colmi, nunca a través de Health Connect, que es específico de Android.",
        de: "Ja. Unter Android liest FitMesh die Daten über Health Connect, in das die meisten Hersteller-Apps schreiben, und liest den Colmi-Ring direkt über Bluetooth. So fließen verschiedene Marken in dasselbe Dashboard, ohne Dubletten. Auf dem iPhone liest die App (bereits live im App Store) Apple Health nativ aus und verbindet sich direkt per Bluetooth mit dem Colmi-Ring — niemals über Health Connect, das Android-spezifisch ist.",
        pt: "Sim. No Android o FitMesh lê os dados via Health Connect, no qual a maioria dos apps dos fabricantes escreve, e lê o anel Colmi diretamente por Bluetooth. Assim, marcas diferentes convergem no mesmo painel, sem duplicatas. No iPhone o app (já ativo na App Store) lê o Apple Saúde nativamente e se conecta diretamente por Bluetooth ao anel Colmi — nunca via Health Connect, que é específico do Android.",
        fr: "Oui. Sur Android, FitMesh lit les données via Health Connect, dans lequel la plupart des applications de fabricants écrivent, et lit la bague Colmi directement par Bluetooth. Des marques différentes convergent ainsi dans le même tableau de bord, dédoublonnées. Sur iPhone, l'application (déjà active sur l'App Store) lit Apple Santé nativement et se connecte directement en Bluetooth à la bague Colmi — jamais via Health Connect, qui est spécifique à Android.",
      },
    },
    {
      q: {
        it: "Cosa succede allo storico del vecchio dispositivo?",
        en: "What happens to the old device's history?",
        es: "¿Qué pasa con el historial del dispositivo antiguo?",
        de: "Was passiert mit dem Verlauf des alten Geräts?",
        pt: "O que acontece com o histórico do dispositivo antigo?",
        fr: "Qu'advient-il de l'historique de l'ancien appareil ?",
      },
      a: {
        it: "Lo storico già entrato nel tuo account FitMesh resta lì, che tu smetta di usare il vecchio dispositivo o disinstalli la sua app. Per questo conviene collegare FitMesh prima del cambio, così porti dentro anche la base storica recente.",
        en: "The history already pulled into your FitMesh account stays there, whether you stop using the old device or uninstall its app. That is why it pays to connect FitMesh before the switch, so you also bring in the recent baseline.",
        es: "El historial que ya ha entrado en tu cuenta de FitMesh se queda ahí, tanto si dejas de usar el dispositivo antiguo como si desinstalas su app. Por eso conviene conectar FitMesh antes del cambio, así incorporas también la base histórica reciente.",
        de: "Der Verlauf, der bereits in dein FitMesh-Konto gelangt ist, bleibt dort, ob du das alte Gerät nicht mehr nutzt oder seine App deinstallierst. Deshalb lohnt es sich, FitMesh vor dem Wechsel zu verbinden, damit du auch die jüngste historische Basis mitnimmst.",
        pt: "O histórico que já entrou na sua conta FitMesh permanece lá, quer você pare de usar o dispositivo antigo, quer desinstale o app dele. Por isso vale a pena conectar o FitMesh antes da troca, assim você traz também a base histórica recente.",
        fr: "L'historique déjà récupéré dans votre compte FitMesh y reste, que vous cessiez d'utiliser l'ancien appareil ou que vous désinstalliez son application. C'est pourquoi il vaut mieux connecter FitMesh avant le changement, pour récupérer aussi la base récente.",
      },
    },
    {
      q: {
        it: "Devo tenere due dispositivi insieme durante la transizione?",
        en: "Do I need to keep two devices together during the transition?",
        es: "¿Tengo que llevar dos dispositivos a la vez durante la transición?",
        de: "Muss ich während des Übergangs zwei Geräte gleichzeitig tragen?",
        pt: "Preciso usar dois dispositivos ao mesmo tempo durante a transição?",
        fr: "Dois-je porter deux appareils en même temps pendant la transition ?",
      },
      a: {
        it: "Non è obbligatorio, ma può aiutare. Se tieni vecchio e nuovo attivi per qualche giorno, la deduplicazione evita di contare due volte gli stessi passi e la transizione risulta senza buchi. Quando sei pronto, smetti di indossare il vecchio.",
        en: "It is not required, but it can help. If you keep the old and the new active for a few days, deduplication avoids counting the same steps twice and the transition comes out gap-free. When you are ready, stop wearing the old one.",
        es: "No es obligatorio, pero puede ayudar. Si mantienes activos el antiguo y el nuevo unos días, la eliminación de duplicados evita contar dos veces los mismos pasos y la transición sale sin huecos. Cuando estés listo, deja de llevar el antiguo.",
        de: "Es ist nicht zwingend, kann aber helfen. Wenn du das alte und das neue Gerät einige Tage aktiv hältst, verhindert die Entfernung von Dubletten, dass dieselben Schritte doppelt gezählt werden, und der Übergang verläuft lückenlos. Wenn du bereit bist, legst du das alte ab.",
        pt: "Não é obrigatório, mas pode ajudar. Se você mantiver o antigo e o novo ativos por alguns dias, a remoção de duplicatas evita contar os mesmos passos duas vezes e a transição fica sem lacunas. Quando estiver pronto, pare de usar o antigo.",
        fr: "Ce n'est pas obligatoire, mais ça peut aider. Si vous gardez l'ancien et le nouveau actifs pendant quelques jours, le dédoublonnage évite de compter deux fois les mêmes pas et la transition se fait sans trous. Quand vous êtes prêt, cessez de porter l'ancien.",
      },
    },
    {
      q: {
        it: "Serve un abbonamento?",
        en: "Do I need a subscription?",
        es: "¿Hace falta una suscripción?",
        de: "Brauche ich ein Abo?",
        pt: "É preciso ter uma assinatura?",
        fr: "Faut-il un abonnement ?",
      },
      a: {
        it: "L'app Android è disponibile ora con dashboard web inclusa. I primi 1000 iscritti founder (entro il 31 luglio 2026) hanno ricevuto il Pro a vita gratis. Oggi c'è una prova completa di 14 giorni, poi tieni FitMesh con un piccolo abbonamento (circa un caffè ogni sei mesi) o con lo sblocco a vita (meno di una pizza). Non c'è un piano gratuito permanente; il prezzo aggiornato per il tuo Paese è mostrato nell'app.",
        en: "The Android app is available now with the web dashboard included. The first 1,000 founder sign-ups (by July 31, 2026) got lifetime Pro free. Today there is a full 14-day trial, then you keep FitMesh with a small subscription (about a coffee every six months) or a one-time lifetime unlock (less than a pizza). There is no permanent free plan; the current price for your country is shown in the app.",
        es: "La app de Android ya está disponible con el panel web incluido. Los primeros 1000 registrados founder (hasta el 31 de julio de 2026) recibieron el Pro de por vida gratis. Hoy hay una prueba completa de 14 días, y luego mantienes FitMesh con una pequeña suscripción (como un café cada seis meses) o con el desbloqueo de por vida (menos que una pizza). No hay un plan gratuito permanente; el precio actualizado para tu país se muestra en la app.",
        de: "Die Android-App ist ab sofort verfügbar, inklusive Web-Dashboard. Die ersten 1.000 founder-Anmeldungen (bis 31. Juli 2026) haben Pro lebenslang gratis erhalten. Heute gibt es eine volle 14-tägige Testphase, und anschließend behältst du FitMesh mit einem kleinen Abo (weniger als ein Kaffee alle sechs Monate) oder der einmaligen Freischaltung fürs Leben (weniger als eine Pizza). Es gibt keinen dauerhaft kostenlosen Tarif; der aktuelle Preis für dein Land wird in der App angezeigt.",
        pt: "O app de Android já está disponível com o painel web incluído. Os primeiros 1000 inscritos founder (até 31 de julho de 2026) receberam o Pro vitalício de graça. Hoje, há uma avaliação completa de 14 dias e, em seguida, você mantém o FitMesh com uma pequena assinatura (como um café a cada seis meses) ou com o desbloqueio vitalício (menos que uma pizza). Não existe um plano gratuito permanente; o preço atualizado para o seu país aparece no app.",
        fr: "L'application Android est disponible dès maintenant, avec le tableau de bord web inclus. Les 1000 premiers inscrits founder (jusqu'au 31 juillet 2026) ont reçu le Pro à vie gratuitement. Aujourd'hui, il y a un essai complet de 14 jours, puis vous gardez FitMesh avec un petit abonnement (moins qu'un café tous les six mois) ou un déblocage à vie en un seul paiement (moins qu'une pizza). Il n'y a pas de forfait gratuit permanent ; le prix à jour pour votre pays est affiché dans l'application.",
      },
    },
    {
      q: {
        it: "I dati dell'anello o dell'orologio sono a livello medico?",
        en: "Is the ring or watch data medical grade?",
        es: "¿Los datos del anillo o del reloj son de nivel médico?",
        de: "Sind die Daten des Rings oder der Uhr medizinisch verwertbar?",
        pt: "Os dados do anel ou do relógio são de nível médico?",
        fr: "Les données de la bague ou de la montre sont-elles de niveau médical ?",
      },
      a: {
        it: "No. Passi, battito, SpO2, sonno e stress sono misure di consumo per il benessere, non strumenti diagnostici. Servono a vedere tendenze nel tempo, non a interpretare valori clinici.",
        en: "No. Steps, heart rate, SpO2, sleep and stress are consumer wellness measurements, not diagnostic tools. They are there to show trends over time, not to interpret clinical values.",
        es: "No. Pasos, ritmo cardíaco, SpO2, sueño y estrés son mediciones de consumo para el bienestar, no herramientas de diagnóstico. Sirven para ver tendencias a lo largo del tiempo, no para interpretar valores clínicos.",
        de: "Nein. Schritte, Herzfrequenz, SpO2, Schlaf und Stress sind Consumer-Wohlfühlmesswerte, keine Diagnosewerkzeuge. Sie sind dafür da, Tendenzen im Zeitverlauf zu zeigen, nicht dazu, klinische Werte zu deuten.",
        pt: "Não. Passos, frequência cardíaca, SpO2, sono e estresse são medições de consumo para o bem-estar, não ferramentas de diagnóstico. Servem para ver tendências ao longo do tempo, não para interpretar valores clínicos.",
        fr: "Non. Les pas, la fréquence cardiaque, la SpO2, le sommeil et le stress sont des mesures grand public pour le bien-être, pas des outils de diagnostic. Ils servent à voir des tendances dans le temps, pas à interpréter des valeurs cliniques.",
      },
    },
  ],
  related: [
    "scegliere-smartwatch-dati-2026",
    "piu-smartwatch-insieme-dati-doppi",
    "da-android-a-iphone-dati-fitness",
    "guida-sync-wearable-2026",
    "vedere-dati-wearable-browser-pc",
  ],
  brandsMentioned: ["Garmin", "Fitbit", "Samsung", "Xiaomi", "Amazfit", "Colmi", "Apple", "Google"],
  ldType: "BlogPosting",
};
