import type { BlogPost } from "../types";

/**
 * Supporting guide: Colmi R02 setup step-by-step: come indossarlo, caricarlo
 * e collegarlo a FitMesh Sync. Target: utenti che hanno appena ricevuto l'anello
 * e cercano istruzioni pratiche in italiano/inglese.
 * Pillar collegato: colmi-ring-fitmesh
 */
export const post: BlogPost = {
  slug: "colmi-r02-setup",
  category: "guides",
  publishedAt: "2026-06-13",
  updatedAt: "2026-06-13",
  ldType: "BlogPosting",
  readMinutes: 7,
  hero: {
    kicker: {
      it: "Guida",
      en: "Guide",
      es: "Guía",
      de: "Anleitung",
      pt: "Guia",
      fr: "Guide",
      pl: "Przewodnik",
      tr: "Kılavuz",
    },
    title: {
      it: "Colmi R02: come configurarlo e leggerne i dati",
      en: "Colmi R02 setup guide: how to use it and read your data",
      es: "Colmi R02: cómo configurarlo y entender tus datos",
      de: "Colmi R02: Einrichtung und Auswertung deiner Daten",
      pt: "Colmi R02: como configurar e entender seus dados",
      fr: "Colmi R02: comment le configurer et lire vos données",
      pl: "Konfiguracja Colmi R02: jak go używać i czytać dane",
      tr: "Colmi R02 kurulum kılavuzu: nasıl kullanılır ve veriler nasıl okunur",
    },
    subtitle: {
      it: "Hai appena ricevuto il Colmi R02 e vuoi capire come funziona, come indossarlo correttamente, e come far confluire i dati in FitMesh insieme al tuo smartwatch. Questa guida copre tutto, dall'apertura della scatola alla prima dashboard unificata.",
      en: "You just received your Colmi R02 and want to understand how it works, how to wear it properly, and how to get the data into FitMesh alongside your smartwatch. This guide covers everything from opening the box to your first unified dashboard.",
      es: "Acabas de recibir el Colmi R02 y quieres entender cómo funciona, cómo llevarlo correctamente y cómo ver todos los datos en FitMesh junto con tu smartwatch. Esta guía cubre todo: desde abrir la caja hasta tu primer panel unificado.",
      de: "Du hast gerade deinen Colmi R02 erhalten und möchtest verstehen, wie er funktioniert, wie du ihn richtig trägst und wie die Daten zusammen mit deinem Smartwatch in FitMesh landen. Diese Anleitung deckt alles ab: von der Verpackung bis zum ersten einheitlichen Dashboard.",
      pt: "Você acabou de receber o Colmi R02 e quer entender como ele funciona, como usá-lo corretamente e como fazer os dados chegarem ao FitMesh junto com o seu smartwatch. Este guia cobre tudo: da abertura da caixa ao seu primeiro painel unificado.",
      fr: "Vous venez de recevoir votre Colmi R02 et souhaitez comprendre comment il fonctionne, comment le porter correctement et comment faire remonter les données dans FitMesh avec votre montre connectée. Ce guide couvre tout: de l'ouverture de la boîte à votre premier tableau de bord unifié.",
      pl: "Właśnie otrzymałeś Colmi R02 i chcesz zrozumieć, jak działa, jak go prawidłowo nosić i jak przesłać dane do FitMesh razem ze swoim smartwatchem. Ten przewodnik obejmuje wszystko: od otwarcia pudełka po pierwszy ujednolicony panel.",
      tr: "Colmi R02'nizi aldınız ve nasıl çalıştığını, doğru nasıl takılacağını ve FitMesh'e smartwatch'ınızla birlikte nasıl veri aktaracağınızı öğrenmek istiyorsunuz. Bu kılavuz kutuyu açmaktan ilk birleşik panele kadar her şeyi kapsar.",
    },
  },
  metaDescription: {
    it: "Colmi R02: come indossarlo, caricarlo e collegarlo a FitMesh per vedere tutti i dati in un'unica dashboard. Guida pratica passo-passo in italiano.",
    en: "Colmi R02 setup: how to wear it, charge it, and connect it to FitMesh for a unified health dashboard. Step-by-step practical guide.",
    es: "Configurar el anillo Colmi R02: cómo llevarlo, cargarlo y conectarlo a FitMesh para ver todos tus datos de salud en un panel unificado. Guía práctica paso a paso.",
    de: "Colmi R02 einrichten: wie du ihn trägst, lädst und mit FitMesh verbindest, um alle Gesundheitsdaten in einem einzigen Dashboard zu sehen. Praktische Schritt-für-Schritt-Anleitung.",
    pt: "Colmi R02: como usar, carregar e conectar ao FitMesh para ver todos os seus dados em um único painel. Guia prático passo a passo.",
    fr: "Colmi R02: comment le porter, le charger et le connecter à FitMesh pour voir toutes vos données de santé dans un tableau de bord unifié. Guide pratique étape par étape.",
    pl: "Konfiguracja Colmi R02: jak go nosić, ładować i połączyć z FitMesh, aby zobaczyć wszystkie dane w jednym panelu. Praktyczny przewodnik krok po kroku.",
    tr: "Colmi R02 kurulumu: nasıl takılır, şarj edilir ve tüm verilerinizi tek bir panelde görmek için FitMesh'e nasıl bağlanır. Adım adım pratik kılavuz.",
  },
  primaryKeyword: {
    it: "configurare anello Colmi",
    en: "set up Colmi ring",
    es: "configurar anillo Colmi",
    de: "Colmi Ring einrichten",
    pt: "configurar anel Colmi",
    fr: "configurer bague connectée Colmi",
    pl: "konfiguracja pierscienia Colmi",
    tr: "Colmi yüzük kurulumu",
  },
  secondaryKeywords: {
    it: [
      "colmi r02 configurazione",
      "colmi r02 istruzioni italiano",
      "colmi r02 come si usa",
      "colmi r02 setup",
      "colmi r02 come funziona",
      "anello colmi fitmesh",
    ],
    en: [
      "colmi r02 setup guide",
      "how to use colmi r02",
      "colmi r02 instructions",
      "colmi r02 configuration",
      "colmi ring fitmesh",
      "colmi r02 how it works",
    ],
    pt: [
      "colmi r02 configuração",
      "colmi r02 instruções em português",
      "colmi r02 como usar",
      "colmi r02 setup",
      "colmi r02 como funciona",
      "anel colmi fitmesh",
    ],
    fr: [
      "colmi r02 configuration",
      "colmi r02 instructions en français",
      "colmi r02 comment utiliser",
      "colmi r02 paramétrage",
      "colmi r02 comment ça marche",
      "bague colmi fitmesh",
    ],
    pl: [
      "colmi r02 konfiguracja",
      "colmi r02 instrukcja po polsku",
      "colmi r02 jak używać",
      "colmi r02 setup",
      "colmi r02 jak działa",
      "pierscień colmi fitmesh",
    ],
    tr: [
      "colmi r02 kurulum kılavuzu",
      "colmi r02 nasıl kullanılır",
      "colmi r02 türkçe talimatlar",
      "colmi r02 yapılandırma",
      "colmi r02 nasıl çalışır",
      "colmi yüzük fitmesh",
    ],
  },
  tldr: {
    it: [
      "Indossa l'anello Colmi sull'anulare o il medio della mano non dominante, sensore verso il palmo.",
      "La batteria dura 5-7 giorni; carica con il disco magnetico collegato a qualsiasi caricatore USB standard.",
      "La connessione a FitMesh Sync avviene su Android in 6 passi: nessuna app del produttore richiesta.",
      "Una volta configurato, i dati del tuo account FitMesh si vedono anche su iPhone (app iOS in arrivo) e possono passare in Apple Salute.",
      "I dati notturni (HRV, SpO2, fasi del sonno) arrivano automaticamente ogni mattina dopo la prima sincronizzazione.",
    ],
    en: [
      "Wear the Colmi ring on the ring or middle finger of your non-dominant hand, sensor facing your palm.",
      "Battery lasts 5-7 days; charge with the magnetic disc connected to any standard USB adapter.",
      "Connecting to FitMesh Sync on Android takes 6 steps and requires no manufacturer app.",
      "Once set up, your FitMesh account data is also viewable on iPhone (iOS app coming soon) and can flow into Apple Health.",
      "Overnight data (HRV, SpO2, sleep stages) arrives automatically each morning after the first sync.",
    ],
    es: [
      "Lleva el anillo Colmi en el dedo anular o corazón de la mano no dominante, con el sensor orientado hacia la palma.",
      "La batería dura entre 5 y 7 días; cárgalo con el disco magnético conectado a cualquier cargador USB estándar.",
      "Conectar el anillo a FitMesh Sync en Android requiere 6 pasos y no necesitas ninguna app del fabricante.",
      "Una vez configurado, los datos de tu cuenta FitMesh también se pueden ver en iPhone (app iOS próximamente) y pueden pasar a Apple Health.",
      "Los datos nocturnos (HRV, SpO2, fases del sueño) llegan automáticamente cada mañana tras la primera sincronización.",
    ],
    de: [
      "Trage den Colmi Ring am Ring- oder Mittelfinger der nicht-dominanten Hand, mit dem Sensor zur Handfläche hin.",
      "Die Akkulaufzeit beträgt 5 bis 7 Tage. Lade den Ring mit der magnetischen Ladescheibe an einem beliebigen Standard-USB-Netzteil.",
      "Die Verbindung mit FitMesh Sync unter Android erfordert 6 Schritte und keine App des Herstellers.",
      "Nach der Einrichtung sind deine FitMesh-Kontodaten auch auf dem iPhone abrufbar (iOS-App demnächst verfügbar) und können in Apple Health fließen.",
      "Nächtliche Daten (HRV, SpO2, Schlafphasen) werden jeden Morgen nach der ersten Synchronisierung automatisch übertragen.",
    ],
    pt: [
      "Use o anel Colmi no dedo anelar ou médio da mão não dominante, com o sensor voltado para a palma.",
      "A bateria dura de 5 a 7 dias. Carregue com o disco magnético conectado a qualquer carregador USB padrão.",
      "Conectar o anel ao FitMesh Sync no Android leva 6 passos e não exige nenhum app do fabricante.",
      "Depois de configurado, os dados da sua conta FitMesh também ficam visíveis no iPhone (app iOS em breve) e podem ser enviados ao Apple Health.",
      "Os dados noturnos (HRV, SpO2, fases do sono) chegam automaticamente toda manhã após a primeira sincronização.",
    ],
    fr: [
      "Portez la bague connectée Colmi à l'annulaire ou au majeur de la main non dominante, capteur tourné vers la paume.",
      "L'autonomie est de 5 à 7 jours. Rechargez avec le disque magnétique branché sur n'importe quel adaptateur USB standard.",
      "La connexion à FitMesh Sync sur Android se fait en 6 étapes, sans application du fabricant.",
      "Une fois configuré, vos données de compte FitMesh sont également consultables sur iPhone (application iOS bientôt disponible) et peuvent être envoyées vers Apple Health.",
      "Les données nocturnes (HRV, SpO2, phases du sommeil) arrivent automatiquement chaque matin après la première synchronisation.",
    ],
    pl: [
      "Noś pierscień Colmi na serdecznym lub środkowym palcu niedominującej ręki, czujnikiem skierowanym w stronę dłoni.",
      "Bateria wytrzymuje 5-7 dni; ładuj za pomocą dysku magnetycznego podłączonego do dowolnej standardowej ładowarki USB.",
      "Połączenie z FitMesh Sync na Androidzie wymaga 6 kroków i nie potrzebuje aplikacji producenta.",
      "Po skonfigurowaniu dane z konta FitMesh są dostępne również na iPhonie (aplikacja iOS wkrótce) i mogą trafić do Apple Health.",
      "Dane nocne (HRV, SpO2, fazy snu) pojawiają się automatycznie każdego ranka po pierwszej synchronizacji.",
    ],
    tr: [
      "Colmi yüzüğü, baskın olmayan elinizin yüzük parmağına veya orta parmağına takın, sensör avucunuza doğru baksın.",
      "Pil 5-7 gün dayanır; herhangi bir standart USB adaptörüne bağlı manyetik diskle şarj edin.",
      "Android'de FitMesh Sync'e bağlanmak 6 adım alır ve üretici uygulaması gerektirmez.",
      "Kurulduktan sonra FitMesh hesabı verileriniz iPhone'da da görüntülenebilir (iOS uygulaması yakında) ve Apple Health'e aktarılabilir.",
      "Gece verileri (HRV, SpO2, uyku evreleri) ilk senkronizasyondan sonra her sabah otomatik olarak gelir.",
    ],
  },
  body: [
    // --- WHAT'S IN THE BOX ---
    {
      type: "heading",
      level: 2,
      text: {
        it: "Cosa trovi nella scatola del Colmi R02",
        en: "What's in the Colmi R02 box",
        es: "Qué hay dentro de la caja del Colmi R02",
        de: "Was im Lieferumfang des Colmi R02 enthalten ist",
        pt: "O que vem na caixa do Colmi R02",
        fr: "Contenu de la boîte du Colmi R02",
        pl: "Co znajdziesz w pudełku Colmi R02",
        tr: "Colmi R02 kutusunda neler var",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "La confezione del Colmi R02 è essenziale. All'interno trovi:",
        en: "The Colmi R02 packaging is minimal. Inside you'll find:",
        es: "El empaque del Colmi R02 es sencillo. Dentro encontrarás:",
        de: "Die Verpackung des Colmi R02 ist schlicht gehalten. Im Lieferumfang findest du:",
        pt: "A embalagem do Colmi R02 é simples. Dentro você encontrará:",
        fr: "Le packaging du Colmi R02 est minimaliste. À l'intérieur, vous trouverez:",
        pl: "Opakowanie Colmi R02 jest minimalistyczne. W środku znajdziesz:",
        tr: "Colmi R02 ambalajı oldukça sade. İçinde şunları bulacaksınız:",
      },
    },
    {
      type: "list",
      items: {
        it: [
          "**L'anello** nelle dimensioni che hai ordinato.",
          "**Il caricatore magnetico**: un dischetto con magnete che si attacca al lato piatto dell'anello.",
          "**Cavo USB-A** (alcuni bundle includono anche il cavo USB-C; l'alimentatore non è incluso, va bene qualsiasi caricatore USB standard).",
          "**Manualino di istruzioni** in più lingue (il contenuto è essenziale: per tutti i dettagli rimanda all'app).",
          "**Kit di taglie di prova** (se lo hai ordinato), per trovare la misura giusta prima di indossare l'anello definitivo.",
        ],
        en: [
          "**The ring** in the size you ordered.",
          "**The magnetic charger**: a small disc with a magnet that attaches to the flat side of the ring.",
          "**USB-A cable** (some bundles include USB-C; the power adapter is not included, any standard USB charger works).",
          "**Quick-start booklet** in multiple languages (content is very basic; for full details it defers to the app).",
          "**Sizing kit** (if you ordered it), to find the right fit before committing to the actual ring.",
        ],
        es: [
          "**El anillo** en la talla que pediste.",
          "**El cargador magnético**: un pequeño disco con imán que se adhiere al lado plano del anillo.",
          "**Cable USB-A** (algunos paquetes incluyen también cable USB-C; el adaptador de corriente no está incluido, cualquier cargador USB estándar funciona).",
          "**Manual de inicio rápido** en varios idiomas (el contenido es muy básico; para todos los detalles remite a la app).",
          "**Kit de tallas de prueba** (si lo pediste), para encontrar la medida correcta antes de quedarte con el anillo definitivo.",
        ],
        de: [
          "**Den Ring** in der von dir bestellten Größe.",
          "**Das Magnetladegerät**: eine kleine Scheibe mit Magnet, die an der flachen Seite des Rings befestigt wird.",
          "**USB-A-Kabel** (manche Bundles enthalten auch ein USB-C-Kabel; das Netzteil ist nicht im Lieferumfang, jedes Standard-USB-Netzteil funktioniert).",
          "**Kurzanleitung** in mehreren Sprachen (der Inhalt ist sehr knapp gehalten; für alle Details wird auf die App verwiesen).",
          "**Größen-Testset** (falls bestellt), um die richtige Größe zu finden, bevor du den endgültigen Ring trägst.",
        ],
        pt: [
          "**O anel** no tamanho que você pediu.",
          "**O carregador magnético**: um pequeno disco com ímã que se encaixa no lado plano do anel.",
          "**Cabo USB-A** (alguns pacotes incluem também cabo USB-C; o adaptador de tomada não está incluído, qualquer carregador USB padrão funciona).",
          "**Guia de início rápido** em vários idiomas (o conteúdo é bem básico; para todos os detalhes, remete ao app).",
          "**Kit de tamanhos de teste** (se você pediu), para encontrar o tamanho certo antes de usar o anel definitivo.",
        ],
        fr: [
          "**La bague** dans la taille que vous avez commandée.",
          "**Le chargeur magnétique**: un petit disque aimanté qui s'attache au côté plat de la bague.",
          "**Câble USB-A** (certains packs incluent aussi un câble USB-C; l'adaptateur secteur n'est pas fourni, tout chargeur USB standard convient).",
          "**Guide de démarrage rapide** en plusieurs langues (le contenu est très sommaire; pour tous les détails, il renvoie à l'application).",
          "**Kit d'essai de tailles** (si vous l'avez commandé), pour trouver la bonne taille avant de porter la bague définitive.",
        ],
        pl: [
          "**Pierścień** w rozmiarze, który zamówiłeś.",
          "**Ładowarka magnetyczna**: mały dysk z magnesem, który przykleja się do płaskiej strony pierścienia.",
          "**Kabel USB-A** (niektóre zestawy zawierają też kabel USB-C; zasilacz nie jest dołączony, wystarczy dowolna standardowa ładowarka USB).",
          "**Skrócona instrukcja obsługi** w kilku językach (treść jest bardzo podstawowa; po pełne szczegóły odsyła do aplikacji).",
          "**Zestaw próbnych rozmiarów** (jeśli go zamówiłeś), aby znaleźć właściwy rozmiar przed założeniem docelowego pierścienia.",
        ],
        tr: [
          "**Yüzük**, sipariş ettiğiniz boyutta.",
          "**Manyetik şarj cihazı**: yüzüğün düz tarafına yapışan küçük bir mıknatıslı disk.",
          "**USB-A kablosu** (bazı paketlerde USB-C kablosu da bulunur; güç adaptörü dahil değildir, herhangi bir standart USB şarj cihazı çalışır).",
          "**Hızlı başlangıç kılavuzu** birden fazla dilde (içerik çok temeldir; tüm ayrıntılar için uygulamaya yönlendirir).",
          "**Boyut deneme kiti** (sipariş ettiyseniz), asıl yüzüğü takmadan önce doğru boyutu bulmak için.",
        ],
      },
    },
    {
      type: "callout",
      variant: "tip",
      title: {
        it: "Hai il kit di taglie di prova?",
        en: "Got the sizing kit?",
        es: "¿Tienes el kit de tallas de prueba?",
        de: "Hast du das Größen-Testset?",
        pt: "Tem o kit de tamanhos de teste?",
        fr: "Vous avez le kit d'essai de tailles?",
        pl: "Masz zestaw próbnych rozmiarów?",
        tr: "Boyut deneme kitiniz var mı?",
      },
      body: {
        it: "Prova ogni anello per 10-15 minuti. L'anello non deve lasciare segni rossi sulla pelle (troppo stretto) e non deve ruotare liberamente (troppo largo). Le dita cambiano leggermente di diametro durante la giornata: misura di pomeriggio per un risultato più rappresentativo.",
        en: "Try each size for 10-15 minutes. The ring should not leave red marks on the skin (too tight) and should not rotate freely (too loose). Fingers change slightly in diameter throughout the day: measure in the afternoon for a more representative result.",
        es: "Prueba cada talla durante 10-15 minutos. El anillo no debe dejar marcas rojas en la piel (demasiado apretado) ni girar libremente (demasiado suelto). Los dedos cambian ligeramente de diámetro a lo largo del día: mídelos por la tarde para obtener un resultado más representativo.",
        de: "Trage jede Größe 10 bis 15 Minuten. Der Ring sollte keine roten Male auf der Haut hinterlassen (zu eng) und sich nicht frei drehen lassen (zu weit). Die Finger verändern ihren Durchmesser im Tagesverlauf leicht: Miss am Nachmittag für ein repräsentativeres Ergebnis.",
        pt: "Experimente cada tamanho por 10 a 15 minutos. O anel não deve deixar marcas vermelhas na pele (muito apertado) nem girar livremente (muito largo). Os dedos mudam ligeiramente de diâmetro ao longo do dia: meça à tarde para um resultado mais representativo.",
        fr: "Essayez chaque taille pendant 10 à 15 minutes. La bague ne doit pas laisser de marques rouges sur la peau (trop serrée) et ne doit pas tourner librement (trop large). Les doigts changent légèrement de diamètre au fil de la journée: mesurez l'après-midi pour un résultat plus représentatif.",
        pl: "Wypróbuj każdy rozmiar przez 10-15 minut. Pierścień nie powinien pozostawiać czerwonych śladów na skórze (zbyt ciasny) ani obracać się swobodnie (zbyt luźny). Palce nieznacznie zmieniają obwód w ciągu dnia: mierz po południu, aby uzyskać bardziej reprezentatywny wynik.",
        tr: "Her boyutu 10-15 dakika takın. Yüzük ciltte kırmızı iz bırakmamalı (çok sıkı) ve serbestçe dönmemeli (çok geniş). Parmaklar gün içinde hafifçe şişer ve daralır: daha temsili bir sonuç için öğleden sonra ölçün.",
      },
    },
    // --- HOW TO WEAR IT ---
    {
      type: "heading",
      level: 2,
      text: {
        it: "Come indossare il Colmi R02 correttamente",
        en: "How to wear the Colmi R02 correctly",
        es: "Cómo llevar el Colmi R02 correctamente",
        de: "Den Colmi R02 richtig tragen",
        pt: "Como usar o Colmi R02 corretamente",
        fr: "Comment porter le Colmi R02 correctement",
        pl: "Jak prawidłowo nosić Colmi R02",
        tr: "Colmi R02 nasıl doğru takılır",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "**Quale dito**: il Colmi R02 funziona meglio sull'**anulare** o sul **medio** della mano non dominante. Questi diti hanno un flusso sanguigno regolare e sono meno esposti a movimenti bruschi durante la giornata. Evita l'indice (troppo movimento) e il mignolo (circolazione spesso meno regolare).",
        en: "**Which finger**: the Colmi R02 works best on the **ring finger** or **middle finger** of your non-dominant hand. These fingers have consistent blood flow and are less exposed to sudden movements during the day. Avoid the index finger (too much movement) and the pinky (often less consistent circulation).",
        es: "**Qué dedo usar**: el Colmi R02 funciona mejor en el **dedo anular** o en el **dedo corazón** de la mano no dominante. Estos dedos tienen un flujo sanguíneo regular y están menos expuestos a movimientos bruscos durante el día. Evita el índice (demasiado movimiento) y el meñique (circulación a menudo menos regular).",
        de: "**Welcher Finger**: Der Colmi R02 funktioniert am besten am **Ringfinger** oder **Mittelfinger** der nicht-dominanten Hand. Diese Finger haben eine gleichmäßige Durchblutung und sind tagsüber weniger starken Bewegungen ausgesetzt. Vermeide den Zeigefinger (zu viel Bewegung) und den kleinen Finger (oft unregelmäßigere Durchblutung).",
        pt: "**Qual dedo**: o Colmi R02 funciona melhor no **dedo anelar** ou no **dedo médio** da mão não dominante. Esses dedos têm fluxo sanguíneo regular e ficam menos expostos a movimentos bruscos durante o dia. Evite o indicador (movimento excessivo) e o mínimo (circulação muitas vezes menos regular).",
        fr: "**Quel doigt**: le Colmi R02 fonctionne mieux à l'**annulaire** ou au **majeur** de la main non dominante. Ces doigts ont un flux sanguin régulier et sont moins exposés aux mouvements brusques au cours de la journée. Évitez l'index (trop de mouvement) et l'auriculaire (circulation souvent moins régulière).",
        pl: "**Który palec**: Colmi R02 działa najlepiej na **serdecznym** lub **środkowym** palcu niedominującej ręki. Te palce mają równomierne krążenie krwi i są mniej narażone na gwałtowne ruchy w ciągu dnia. Unikaj palca wskazującego (zbyt dużo ruchu) i małego palca (często mniej regularne krążenie).",
        tr: "**Hangi parmak**: Colmi R02, baskın olmayan elinizin **yüzük parmağında** veya **orta parmağında** en iyi çalışır. Bu parmaklar düzenli kan akışına sahiptir ve gün içinde ani hareketlere daha az maruz kalır. İşaret parmağından (çok fazla hareket) ve serçe parmaktan (genellikle daha düzensiz dolaşım) kaçının.",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "**Orientamento**: il lato con il sensore ottico (la parte piatta o leggermente convessa all'interno dell'anello) deve stare sulla parte **inferiore del dito**, quella rivolta verso il palmo della mano. Questo assicura il contatto diretto tra il sensore e la pelle. Se l'anello ha un piccolo punto o una scanalatura indicatrice, posizionalo sul lato inferiore.",
        en: "**Orientation**: the side with the optical sensor (the flat or slightly curved inner surface of the ring) should sit on the **underside of your finger**, the side facing your palm. This ensures direct contact between the sensor and your skin. If the ring has a small dot or groove as a position indicator, place that on the underside.",
        es: "**Orientación**: el lado con el sensor óptico (la parte plana o ligeramente curva del interior del anillo) debe quedar en la **parte inferior del dedo**, la que mira hacia la palma. Esto garantiza el contacto directo entre el sensor y la piel. Si el anillo tiene un pequeño punto o ranura indicadora de posición, colócalo en la parte inferior.",
        de: "**Ausrichtung**: Die Seite mit dem optischen Sensor (die flache oder leicht gewölbte Innenseite des Rings) muss auf der **Unterseite des Fingers** liegen, also zur Handfläche hin. So ist der direkte Kontakt zwischen Sensor und Haut gewährleistet. Hat der Ring einen kleinen Punkt oder eine Kerbe als Positionsmarkierung, bringe diese auf der Unterseite an.",
        pt: "**Orientação**: o lado com o sensor óptico (a parte plana ou levemente curva do interior do anel) deve ficar na **parte inferior do dedo**, voltada para a palma da mão. Isso garante o contato direto entre o sensor e a pele. Se o anel tiver um pequeno ponto ou ranhura indicadora de posição, coloque-o na parte inferior.",
        fr: "**Orientation**: le côté avec le capteur optique (la surface intérieure plate ou légèrement courbée de la bague) doit se trouver sur la **face inférieure du doigt**, celle qui est tournée vers la paume. Cela garantit le contact direct entre le capteur et la peau. Si la bague comporte un petit point ou une rainure comme indicateur de position, placez-le sur la face inférieure.",
        pl: "**Orientacja**: strona z czujnikiem optycznym (płaska lub lekko zakrzywiona wewnętrzna powierzchnia pierścienia) powinna znajdować się na **spodniej stronie palca**, tej skierowanej w stronę dłoni. Zapewnia to bezpośredni kontakt czujnika ze skórą. Jeśli pierścień ma małą kropkę lub wgłębienie jako wskaźnik pozycji, umieść go na spodniej stronie.",
        tr: "**Yön**: optik sensörün bulunduğu taraf (yüzüğün düz veya hafifçe kavisli iç yüzeyi) **parmağın alt tarafında**, avucunuza bakan tarafta durmalıdır. Bu, sensör ile cilt arasında doğrudan temas sağlar. Yüzükte küçük bir nokta veya oluk varsa, bunu alt tarafa yerleştirin.",
      },
    },
    {
      type: "callout",
      variant: "info",
      title: {
        it: "Test rapido per la misura",
        en: "Quick fit check",
        es: "Comprobación rápida del ajuste",
        de: "Schnelle Passformprüfung",
        pt: "Verificação rápida do tamanho",
        fr: "Vérification rapide de l'ajustement",
        pl: "Szybkie sprawdzenie dopasowania",
        tr: "Hızlı uyum kontrolü",
      },
      body: {
        it: "Dopo 5 minuti di usura, guarda se ci sono segni rossi sulla pelle: se sì, la misura è troppo piccola. Se l'anello ruota o scivola facilmente, considera una taglia più piccola. Le dita si gonfiano con il caldo e si restringono al freddo: una lieve differenza a orari diversi della giornata è normale.",
        en: "After wearing it for 5 minutes, look for red marks on the skin: if you see them, the size is too small. If the ring spins or slides off easily, go one size smaller. Fingers swell in heat and shrink when cold: a slight difference at different times of day is normal.",
        es: "Después de llevarlo 5 minutos, fíjate si aparecen marcas rojas en la piel: si es así, la talla es demasiado pequeña. Si el anillo gira o se sale fácilmente, prueba una talla menos. Los dedos se hinchan con el calor y se encogen con el frío: una pequeña diferencia a distintas horas del día es normal.",
        de: "Schau nach 5 Minuten Tragezeit, ob rote Abdrücke auf der Haut sichtbar sind: Falls ja, ist die Größe zu klein. Dreht sich der Ring oder rutscht er leicht ab, nimm eine Nummer kleiner. Die Finger schwellen bei Wärme an und ziehen sich bei Kälte zusammen: geringe Unterschiede zu verschiedenen Tageszeiten sind normal.",
        pt: "Após 5 minutos de uso, verifique se há marcas vermelhas na pele: se houver, o tamanho é muito pequeno. Se o anel girar ou sair facilmente, experimente um tamanho menor. Os dedos incham com o calor e encolhem com o frio: uma pequena diferença em horários distintos do dia é normal.",
        fr: "Après 5 minutes de port, regardez si des marques rouges apparaissent sur la peau: si oui, la taille est trop petite. Si la bague tourne ou glisse facilement, prenez une taille en dessous. Les doigts gonflent avec la chaleur et se rétractent avec le froid: une légère différence à différentes heures de la journée est normale.",
        pl: "Po 5 minutach noszenia sprawdź, czy na skórze pojawiają się czerwone ślady: jeśli tak, rozmiar jest za mały. Jeśli pierścień obraca się lub łatwo spada, wybierz rozmiar mniejszy. Palce puchną w cieple i kurczą się na zimnie: niewielka różnica o różnych porach dnia jest normalna.",
        tr: "5 dakika taktıktan sonra ciltte kırmızı iz oluşup oluşmadığına bakın: oluşuyorsa boyut çok küçüktür. Yüzük dönüyor veya kolayca çıkıyorsa bir boyut küçük alın. Parmaklar sıcakta şişer ve soğukta daralır: günün farklı saatlerinde küçük bir fark normaldir.",
      },
    },
    // --- CHARGING ---
    {
      type: "heading",
      level: 2,
      text: {
        it: "Ricarica: quanto dura la batteria e come caricarla",
        en: "Charging: how long the battery lasts and how to charge",
        es: "Carga: cuánto dura la batería y cómo cargarla",
        de: "Laden: Akkulaufzeit und Ladevorgang",
        pt: "Carregamento: quanto dura a bateria e como carregar",
        fr: "Charge: autonomie de la batterie et comment recharger",
        pl: "Ładowanie: jak długo trzyma bateria i jak ładować",
        tr: "Şarj: pil ne kadar dayanır ve nasıl şarj edilir",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Con il monitoraggio continuo attivo (battito cardiaco, SpO2 notturno, passi), il Colmi R02 dura tipicamente **5-7 giorni**. Con il monitoraggio SpO2 continuo molto attivo la durata può scendere a 3-4 giorni.",
        en: "With continuous monitoring active (heart rate, overnight SpO2, steps), the Colmi R02 typically lasts **5-7 days**. With aggressive continuous overnight SpO2 monitoring it can drop to 3-4 days.",
        es: "Con el monitoreo continuo activo (frecuencia cardíaca, SpO2 nocturno, pasos), el Colmi R02 dura normalmente **entre 5 y 7 días**. Con un monitoreo muy intensivo de SpO2 nocturno continuo, puede bajar a 3-4 días.",
        de: "Bei aktivem Dauermonitoring (Herzfrequenz, nächtliche SpO2, Schritte) hält der Colmi R02 typischerweise **5 bis 7 Tage**. Bei sehr intensivem kontinuierlichem SpO2-Monitoring kann die Laufzeit auf 3 bis 4 Tage sinken.",
        pt: "Com o monitoramento contínuo ativo (frequência cardíaca, SpO2 noturno, passos), o Colmi R02 dura normalmente **5 a 7 dias**. Com monitoramento de SpO2 noturno muito intensivo, a duração pode cair para 3 a 4 dias.",
        fr: "Avec le suivi continu activé (fréquence cardiaque, SpO2 nocturne, pas), le Colmi R02 dure généralement **5 à 7 jours**. Avec un suivi SpO2 nocturne continu très intensif, l'autonomie peut descendre à 3 à 4 jours.",
        pl: "Przy aktywnym ciągłym monitorowaniu (tętno, nocne SpO2, kroki) Colmi R02 wytrzymuje typowo **5-7 dni**. Przy bardzo intensywnym ciągłym nocnym monitorowaniu SpO2 czas pracy może spaść do 3-4 dni.",
        tr: "Sürekli izleme etkinken (kalp atış hızı, gece SpO2, adımlar) Colmi R02 tipik olarak **5-7 gün** dayanır. Çok yoğun sürekli gece SpO2 izlemesiyle bu süre 3-4 güne düşebilir.",
      },
    },
    {
      type: "list",
      items: {
        it: [
          "**Come caricare**: aggancia il caricatore magnetico al lato piatto dell'anello. Il magnete lo mantiene in posizione. Collega il cavo a qualsiasi alimentatore USB standard (5V/1A è sufficiente, non serve il caricatore rapido).",
          "**Come sapere che sta caricando**: la maggior parte dei modelli R02 mostra un LED che lampeggia durante la carica. Quando il LED si spegne o smette di lampeggiare, la carica è completa.",
          "**Tempo di ricarica completa**: circa 1-2 ore da vuoto.",
          "**Routine consigliata**: caricalo ogni 4-5 giorni la mattina, durante la doccia o la colazione. Così non rischi di restare senza batteria di notte, il momento in cui i dati sono più preziosi.",
        ],
        en: [
          "**How to charge**: attach the magnetic charger to the flat side of the ring. The magnet holds it in place. Connect the cable to any standard USB adapter (5V/1A is enough, no fast charger needed).",
          "**How to know it's charging**: most R02 models show an LED that blinks during charging. When the LED turns off or stops blinking, charging is complete.",
          "**Full charge time**: approximately 1-2 hours from empty.",
          "**Recommended routine**: charge every 4-5 days in the morning during your shower or over breakfast. This way you never risk running out of battery overnight, when your data matters most.",
        ],
        es: [
          "**Cómo cargar**: acopla el cargador magnético al lado plano del anillo. El imán lo mantiene en su sitio. Conecta el cable a cualquier adaptador USB estándar (5V/1A es suficiente, no necesitas carga rápida).",
          "**Cómo saber que está cargando**: la mayoría de los modelos R02 muestran un LED que parpadea durante la carga. Cuando el LED se apaga o deja de parpadear, la carga ha terminado.",
          "**Tiempo de carga completa**: aproximadamente 1-2 horas desde cero.",
          "**Rutina recomendada**: cárgalo cada 4-5 días por la mañana, mientras te duchas o desayunas. Así nunca corres el riesgo de quedarte sin batería por la noche, que es cuando los datos son más valiosos.",
        ],
        de: [
          "**Aufladen**: Befestige das Magnetladegerät an der flachen Seite des Rings. Der Magnet hält es an Ort und Stelle. Schließe das Kabel an ein beliebiges Standard-USB-Netzteil an (5V/1A genügt, kein Schnellladegerät erforderlich).",
          "**Ladestand erkennen**: Die meisten R02-Modelle zeigen eine blinkende LED während des Ladevorgangs. Wenn die LED erlischt oder aufhört zu blinken, ist der Akku voll.",
          "**Ladezeit (voll)**: etwa 1 bis 2 Stunden ab leerem Akku.",
          "**Empfohlene Routine**: Lade den Ring alle 4 bis 5 Tage morgens, zum Beispiel während der Dusche oder beim Frühstück. So riskierst du nicht, nachts ohne Akku dazustehen, wenn deine Daten am wertvollsten sind.",
        ],
        pt: [
          "**Como carregar**: encaixe o carregador magnético no lado plano do anel. O ímã o mantém no lugar. Conecte o cabo a qualquer adaptador USB padrão (5V/1A é suficiente, não precisa de carregamento rápido).",
          "**Como saber se está carregando**: a maioria dos modelos R02 mostra um LED piscando durante o carregamento. Quando o LED apaga ou para de piscar, o carregamento está completo.",
          "**Tempo de carga completa**: aproximadamente 1 a 2 horas a partir do zero.",
          "**Rotina recomendada**: carregue a cada 4 a 5 dias pela manhã, durante o banho ou o café da manhã. Assim você nunca corre o risco de ficar sem bateria à noite, que é quando os dados são mais valiosos.",
        ],
        fr: [
          "**Comment recharger**: attachez le chargeur magnétique sur le côté plat de la bague. L'aimant le maintient en place. Connectez le câble à n'importe quel adaptateur USB standard (5V/1A suffit, pas besoin de charge rapide).",
          "**Comment savoir qu'elle se charge**: la plupart des modèles R02 affichent une LED clignotante pendant la charge. Quand la LED s'éteint ou cesse de clignoter, la charge est terminée.",
          "**Temps de charge complet**: environ 1 à 2 heures à partir de zéro.",
          "**Routine recommandée**: rechargez tous les 4 à 5 jours le matin, pendant la douche ou le petit-déjeuner. Vous ne risquez ainsi jamais de tomber en panne de batterie la nuit, quand vos données sont les plus précieuses.",
        ],
        pl: [
          "**Jak ładować**: przymocuj ładowarkę magnetyczną do płaskiej strony pierścienia. Magnes utrzyma ją na miejscu. Podłącz kabel do dowolnego standardowego zasilacza USB (wystarczy 5V/1A, szybkie ładowanie nie jest potrzebne).",
          "**Jak sprawdzić, czy się ładuje**: większość modeli R02 wyświetla mrugającą diodę LED podczas ładowania. Gdy dioda zgaśnie lub przestanie migać, ładowanie jest zakończone.",
          "**Czas pełnego naładowania**: około 1-2 godziny od zera.",
          "**Zalecana rutyna**: ładuj co 4-5 dni rano, podczas prysznica lub śniadania. W ten sposób nigdy nie ryzykujesz, że bateria wyczerpie się w nocy, kiedy dane są najcenniejsze.",
        ],
        tr: [
          "**Nasıl şarj edilir**: manyetik şarj cihazını yüzüğün düz tarafına takın. Mıknatıs yerinde tutacaktır. Kabloyu herhangi bir standart USB adaptörüne bağlayın (5V/1A yeterlidir, hızlı şarj gerekmez).",
          "**Şarj olduğunu nasıl anlarsınız**: çoğu R02 modeli şarj sırasında yanıp sönen bir LED gösterir. LED sönünce veya yanıp sönmeyi bırakınca şarj tamamdır.",
          "**Tam şarj süresi**: sıfırdan yaklaşık 1-2 saat.",
          "**Önerilen rutin**: her 4-5 günde bir sabah, duş sırasında veya kahvaltıda şarj edin. Böylece verilerinizin en değerli olduğu gece boyunca pil bitmesi riskini ortadan kaldırırsınız.",
        ],
      },
    },
    // --- FIRST SYNC ---
    {
      type: "heading",
      level: 2,
      text: {
        it: "Prima sincronizzazione con FitMesh Sync: passo dopo passo",
        en: "First sync with FitMesh Sync: step by step",
        es: "Primera sincronización con FitMesh Sync: paso a paso",
        de: "Erste Synchronisierung mit FitMesh Sync: Schritt für Schritt",
        pt: "Primeira sincronização com FitMesh Sync: passo a passo",
        fr: "Première synchronisation avec FitMesh Sync: étape par étape",
        pl: "Pierwsza synchronizacja z FitMesh Sync: krok po kroku",
        tr: "FitMesh Sync ile ilk senkronizasyon: adım adım",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "FitMesh Sync si connette al Colmi R02 via Bluetooth diretto, senza passare dall'app del produttore. Non ti serve scaricare l'app companion Colmi per usare FitMesh: anche se puoi tenerla installata se lo preferisci, non è necessaria.",
        en: "FitMesh Sync connects to the Colmi R02 over direct Bluetooth, without going through the manufacturer's companion app. You don't need to download the Colmi companion app to use FitMesh: you can keep it installed if you prefer, but it is not required.",
        es: "FitMesh Sync se conecta al Colmi R02 por Bluetooth directo, sin pasar por la app del fabricante. No necesitas descargar la app companion de Colmi para usar FitMesh: puedes tenerla instalada si lo prefieres, pero no es necesaria.",
        de: "FitMesh Sync verbindet sich per direktem Bluetooth mit dem Colmi R02, ohne die Begleit-App des Herstellers zu nutzen. Die Colmi-Companion-App muss nicht heruntergeladen werden, um FitMesh zu verwenden: Du kannst sie installiert lassen, wenn du möchtest, sie ist aber nicht erforderlich.",
        pt: "O FitMesh Sync conecta-se ao Colmi R02 via Bluetooth direto, sem precisar do app do fabricante. Não é necessário baixar o app companion da Colmi para usar o FitMesh: você pode mantê-lo instalado se preferir, mas não é obrigatório.",
        fr: "FitMesh Sync se connecte au Colmi R02 via Bluetooth direct, sans passer par l'application du fabricant. Vous n'avez pas besoin de télécharger l'application Colmi pour utiliser FitMesh: vous pouvez la garder installée si vous le souhaitez, mais ce n'est pas nécessaire.",
        pl: "FitMesh Sync łączy się z Colmi R02 przez bezpośrednie Bluetooth, bez pośrednictwa aplikacji producenta. Nie musisz pobierać aplikacji companion Colmi, aby korzystać z FitMesh: możesz ją zachować zainstalowaną, jeśli wolisz, ale nie jest wymagana.",
        tr: "FitMesh Sync, üreticinin eşlik uygulaması olmadan Colmi R02'ye doğrudan Bluetooth üzerinden bağlanır. FitMesh'i kullanmak için Colmi eşlik uygulamasını indirmeniz gerekmez: tercih ederseniz kurulu bırakabilirsiniz, ancak zorunlu değildir.",
      },
    },
    {
      type: "list",
      ordered: true,
      items: {
        it: [
          "**Installa FitMesh Sync**: se non l'hai già fatto, scaricala dal Google Play Store. La versione beta è accessibile tramite link di invito dalla pagina [/it/beta](/it/beta).",
          "**Apri FitMesh e vai su \"Dispositivi\"**: nella schermata principale, seleziona il menu dispositivi o tocca il tasto \"+\" per aggiungere un nuovo device.",
          "**Seleziona \"Anello smart\" e poi \"Colmi R02/R03\"**: FitMesh avvia la scansione Bluetooth. Assicurati che il Bluetooth del telefono sia attivo e che l'anello sia vicino (entro 50 cm).",
          "**Abbina l'anello**: quando il Colmi R02 appare nella lista dei dispositivi rilevati, selezionalo. L'abbinamento richiede pochi secondi. Non ti viene chiesto nessun PIN.",
          "**Prima sincronizzazione dati**: dopo l'abbinamento, FitMesh scarica automaticamente i dati storici presenti nella memoria dell'anello (tipicamente gli ultimi 7 giorni). Questa prima sincronizzazione può richiedere da 30 secondi a qualche minuto.",
          "**Sincronizzazioni successive**: le sincronizzazioni seguenti avvengono in automatico ogni volta che l'anello è in range del telefono. Non devi fare nulla manualmente.",
        ],
        en: [
          "**Install FitMesh Sync**: if you haven't already, download it from the Google Play Store. The beta version is accessible via an invite link from the [/en/beta](/en/beta) page.",
          "**Open FitMesh and go to \"Devices\"**: from the main screen, select the devices menu or tap the \"+\" button to add a new device.",
          "**Select \"Smart ring\" then \"Colmi R02/R03\"**: FitMesh starts a Bluetooth scan. Make sure your phone's Bluetooth is on and the ring is nearby (within 50 cm).",
          "**Pair the ring**: when the Colmi R02 appears in the detected devices list, select it. Pairing takes a few seconds. No PIN is required.",
          "**First data sync**: after pairing, FitMesh automatically downloads the historical data stored in the ring's memory (typically the past 7 days). This first sync can take anywhere from 30 seconds to a few minutes.",
          "**Subsequent syncs**: future syncs happen automatically every time the ring is in range of your phone. You don't need to do anything manually.",
        ],
        es: [
          "**Instala FitMesh Sync**: si aún no lo has hecho, descárgala desde Google Play Store. La versión beta es accesible mediante un enlace de invitación desde la página [/es/beta](/es/beta).",
          "**Abre FitMesh y ve a \"Dispositivos\"**: desde la pantalla principal, selecciona el menú de dispositivos o toca el botón \"+\" para agregar un nuevo dispositivo.",
          "**Selecciona \"Anillo inteligente\" y luego \"Colmi R02/R03\"**: FitMesh inicia el escaneo Bluetooth. Asegúrate de que el Bluetooth de tu teléfono esté activado y de que el anillo esté cerca (a menos de 50 cm).",
          "**Vincula el anillo**: cuando el Colmi R02 aparezca en la lista de dispositivos detectados, selecciónalo. La vinculación tarda unos segundos. No se te pedirá ningún PIN.",
          "**Primera sincronización de datos**: tras la vinculación, FitMesh descarga automáticamente los datos históricos almacenados en la memoria del anillo (normalmente los últimos 7 días). Esta primera sincronización puede tardar entre 30 segundos y varios minutos.",
          "**Sincronizaciones posteriores**: las siguientes sincronizaciones se realizan de forma automática cada vez que el anillo está al alcance del teléfono. No tienes que hacer nada manualmente.",
        ],
        de: [
          "**FitMesh Sync installieren**: Falls noch nicht geschehen, lade die App aus dem Google Play Store herunter. Die Beta-Version ist über einen Einladungslink auf der Seite [/de/beta](/de/beta) zugänglich.",
          "**FitMesh öffnen und zu \"Geräte\" navigieren**: Wähle im Hauptbildschirm das Geräte-Menü oder tippe auf \"+\", um ein neues Gerät hinzuzufügen.",
          "**\"Smart-Ring\" und dann \"Colmi R02/R03\" auswählen**: FitMesh startet die Bluetooth-Suche. Stelle sicher, dass Bluetooth am Telefon aktiviert ist und der Ring in der Nähe liegt (innerhalb von 50 cm).",
          "**Ring koppeln**: Wenn der Colmi R02 in der Liste der erkannten Geräte erscheint, wähle ihn aus. Das Koppeln dauert wenige Sekunden. Es wird keine PIN benötigt.",
          "**Erste Datensynchronisierung**: Nach dem Koppeln lädt FitMesh automatisch die im Ring-Speicher gespeicherten historischen Daten herunter (typischerweise die letzten 7 Tage). Diese erste Synchronisierung kann zwischen 30 Sekunden und einigen Minuten dauern.",
          "**Folgende Synchronisierungen**: Weitere Synchronisierungen erfolgen automatisch, sobald der Ring in Reichweite des Telefons ist. Du musst nichts manuell tun.",
        ],
        pt: [
          "**Instale o FitMesh Sync**: se ainda não fez isso, baixe o app no Google Play Store. A versão beta está acessível por meio de link de convite na página [/pt/beta](/pt/beta).",
          "**Abra o FitMesh e vá em \"Dispositivos\"**: na tela principal, selecione o menu de dispositivos ou toque no botão \"+\" para adicionar um novo dispositivo.",
          "**Selecione \"Anel inteligente\" e depois \"Colmi R02/R03\"**: o FitMesh inicia a varredura Bluetooth. Certifique-se de que o Bluetooth do celular está ativado e que o anel está próximo (até 50 cm).",
          "**Emparelhe o anel**: quando o Colmi R02 aparecer na lista de dispositivos detectados, selecione-o. O emparelhamento leva alguns segundos. Nenhum PIN é solicitado.",
          "**Primeira sincronização de dados**: após o emparelhamento, o FitMesh baixa automaticamente os dados históricos armazenados na memória do anel (normalmente os últimos 7 dias). Essa primeira sincronização pode levar de 30 segundos a alguns minutos.",
          "**Sincronizações seguintes**: as próximas sincronizações acontecem automaticamente sempre que o anel estiver no alcance do celular. Não é preciso fazer nada manualmente.",
        ],
        fr: [
          "**Installez FitMesh Sync**: si ce n'est pas encore fait, téléchargez-le depuis le Google Play Store. La version bêta est accessible via un lien d'invitation depuis la page [/fr/beta](/fr/beta).",
          "**Ouvrez FitMesh et accédez à \"Appareils\"**: depuis l'écran principal, sélectionnez le menu appareils ou appuyez sur \"+\" pour ajouter un nouvel appareil.",
          "**Sélectionnez \"Bague connectée\" puis \"Colmi R02/R03\"**: FitMesh lance un scan Bluetooth. Assurez-vous que le Bluetooth de votre téléphone est activé et que la bague est à proximité (dans un rayon de 50 cm).",
          "**Associez la bague**: quand le Colmi R02 apparaît dans la liste des appareils détectés, sélectionnez-le. L'association prend quelques secondes. Aucun code PIN n'est demandé.",
          "**Première synchronisation des données**: après l'association, FitMesh télécharge automatiquement les données historiques stockées dans la mémoire de la bague (généralement les 7 derniers jours). Cette première synchronisation peut prendre entre 30 secondes et quelques minutes.",
          "**Synchronisations suivantes**: les synchronisations ultérieures s'effectuent automatiquement chaque fois que la bague est à portée de votre téléphone. Vous n'avez rien à faire manuellement.",
        ],
        pl: [
          "**Zainstaluj FitMesh Sync**: jeśli jeszcze tego nie zrobiłeś, pobierz aplikację z Google Play Store. Wersja beta jest dostępna przez link z zaproszeniem ze strony [/pl/beta](/pl/beta).",
          "**Otwórz FitMesh i przejdź do 'Urządzenia'**: na ekranie głównym wybierz menu urządzeń lub naciśnij '+', aby dodać nowe urządzenie.",
          "**Wybierz 'Pierścień smart', a następnie 'Colmi R02/R03'**: FitMesh uruchamia skanowanie Bluetooth. Upewnij się, że Bluetooth w telefonie jest włączony, a pierścień jest w pobliżu (w odległości do 50 cm).",
          "**Sparuj pierścień**: gdy Colmi R02 pojawi się na liście wykrytych urządzeń, wybierz go. Parowanie trwa kilka sekund. Nie jest wymagany PIN.",
          "**Pierwsza synchronizacja danych**: po sparowaniu FitMesh automatycznie pobiera dane historyczne z pamięci pierścienia (zazwyczaj ostatnie 7 dni). Pierwsza synchronizacja może trwać od 30 sekund do kilku minut.",
          "**Kolejne synchronizacje**: następne synchronizacje odbywają się automatycznie za każdym razem, gdy pierścień znajdzie się w zasięgu telefonu. Nie musisz nic robić ręcznie.",
        ],
        tr: [
          "**FitMesh Sync'i yükleyin**: henüz yapmadıysanız Google Play Store'dan indirin. Beta sürümüne [/tr/beta](/tr/beta) sayfasındaki davet bağlantısı üzerinden erişebilirsiniz.",
          "**FitMesh'i açın ve \"Cihazlar\"a gidin**: ana ekrandan cihazlar menüsünü seçin veya yeni cihaz eklemek için \"+\" düğmesine dokunun.",
          "**\"Akıllı yüzük\", ardından \"Colmi R02/R03\" seçin**: FitMesh Bluetooth taraması başlatır. Telefonunuzun Bluetooth'unun açık olduğundan ve yüzüğün yakında (50 cm içinde) olduğundan emin olun.",
          "**Yüzüğü eşleştirin**: Colmi R02 algılanan cihazlar listesinde göründüğünde seçin. Eşleştirme birkaç saniye alır. PIN girilmesi gerekmez.",
          "**İlk veri senkronizasyonu**: eşleştirmeden sonra FitMesh, yüzüğün belleğindeki geçmiş verileri (genellikle son 7 gün) otomatik olarak indirir. Bu ilk senkronizasyon 30 saniye ile birkaç dakika arasında sürebilir.",
          "**Sonraki senkronizasyonlar**: sonraki senkronizasyonlar, yüzük telefonunuzun menzilinde olduğu her seferinde otomatik olarak gerçekleşir. Elle bir şey yapmanız gerekmez.",
        ],
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Per i dettagli tecnici completi su come funziona la connessione Bluetooth, cosa succede durante la sincronizzazione e come avviene la fusione dei dati con il tuo smartwatch, leggi la [guida completa all'anello Colmi](/it/blog/colmi-ring-fitmesh).",
        en: "For the full technical details on how the Bluetooth connection works, what happens during a sync, and how data fusion with your smartwatch is handled, read the [full Colmi ring guide](/en/blog/colmi-ring-fitmesh).",
        es: "Para conocer todos los detalles técnicos sobre cómo funciona la conexión Bluetooth, qué ocurre durante la sincronización y cómo se fusionan los datos con tu smartwatch, lee la [guía completa del anillo Colmi](/es/blog/colmi-ring-fitmesh).",
        de: "Alle technischen Details zur Bluetooth-Verbindung, zum Ablauf der Synchronisierung und zur Datenzusammenführung mit deinem Smartwatch findest du in der [vollständigen Colmi-Ring-Anleitung](/de/blog/colmi-ring-fitmesh).",
        pt: "Para todos os detalhes técnicos sobre como funciona a conexão Bluetooth, o que acontece durante a sincronização e como é feita a fusão de dados com o seu smartwatch, leia o [guia completo do anel Colmi](/pt/blog/colmi-ring-fitmesh).",
        fr: "Pour tous les détails techniques sur le fonctionnement de la connexion Bluetooth, ce qui se passe lors d'une synchronisation et comment la fusion des données avec votre montre connectée est gérée, lisez le [guide complet de la bague Colmi](/fr/blog/colmi-ring-fitmesh).",
        pl: "Pełne szczegóły techniczne dotyczące działania połączenia Bluetooth, przebiegu synchronizacji i łączenia danych ze smartwatchem znajdziesz w [pełnym przewodniku po pierścieniu Colmi](/pl/blog/colmi-ring-fitmesh).",
        tr: "Bluetooth bağlantısının nasıl çalıştığı, senkronizasyon sırasında neler olduğu ve smartwatch ile veri birleştirmenin nasıl yapıldığına ilişkin tüm teknik ayrıntılar için [Colmi yüzük tam kılavuzunu](/tr/blog/colmi-ring-fitmesh) okuyun.",
      },
    },
    // --- iOS NOTE ---
    {
      type: "heading",
      level: 2,
      text: {
        it: "iPhone e Apple Salute: cosa succede una volta configurato",
        en: "iPhone and Apple Health: what happens once you're set up",
        es: "iPhone y Apple Health: qué ocurre una vez configurado",
        de: "iPhone und Apple Health: Was nach der Einrichtung passiert",
        pt: "iPhone e Apple Health: o que acontece depois da configuração",
        fr: "iPhone et Apple Health: ce qui se passe une fois configuré",
        pl: "iPhone i Apple Health: co się dzieje po konfiguracji",
        tr: "iPhone ve Apple Health: kurulumdan sonra ne olur",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "La connessione Bluetooth tra FitMesh Sync e l'anello Colmi avviene su Android, dove i dati vengono raccolti e caricati sul tuo account FitMesh. Una volta che i dati sono nel tuo account, però, li puoi vedere ovunque: l'app FitMesh per iPhone (iOS) e il ponte verso Apple Salute sono in arrivo con lancio imminente.",
        en: "The Bluetooth connection between FitMesh Sync and the Colmi ring happens on Android, where the data is collected and uploaded to your FitMesh account. Once the data is in your account, however, you can access it anywhere: the FitMesh app for iPhone (iOS) and the Apple Health bridge are coming soon.",
        es: "La conexión Bluetooth entre FitMesh Sync y el anillo Colmi se realiza en Android, donde los datos se recopilan y se suben a tu cuenta FitMesh. Una vez que los datos están en tu cuenta, puedes acceder a ellos desde cualquier lugar: la app FitMesh para iPhone (iOS) y el puente hacia Apple Health están próximamente disponibles.",
        de: "Die Bluetooth-Verbindung zwischen FitMesh Sync und dem Colmi Ring läuft über Android, wo die Daten erfasst und in dein FitMesh-Konto hochgeladen werden. Sind die Daten einmal in deinem Konto, kannst du sie überall abrufen: Die FitMesh-App für iPhone (iOS) und die Apple-Health-Anbindung sind demnächst verfügbar.",
        pt: "A conexão Bluetooth entre o FitMesh Sync e o anel Colmi acontece no Android, onde os dados são coletados e enviados para a sua conta FitMesh. Uma vez que os dados estão na sua conta, você pode acessá-los de qualquer lugar: o app FitMesh para iPhone (iOS) e a integração com o Apple Health chegam em breve.",
        fr: "La connexion Bluetooth entre FitMesh Sync et la bague Colmi s'effectue sur Android, où les données sont collectées et téléversées sur votre compte FitMesh. Une fois les données dans votre compte, vous pouvez y accéder partout: l'application FitMesh pour iPhone (iOS) et le pont vers Apple Health sont bientôt disponibles.",
        pl: "Połączenie Bluetooth między FitMesh Sync a pierścieniem Colmi odbywa się na Androidzie, gdzie dane są zbierane i przesyłane na konto FitMesh. Gdy dane znajdą się na koncie, możesz uzyskać do nich dostęp z dowolnego miejsca: aplikacja FitMesh na iPhone'a (iOS) i most do Apple Health wkrótce będą dostępne.",
        tr: "FitMesh Sync ile Colmi yüzüğü arasındaki Bluetooth bağlantısı Android'de gerçekleşir; veriler burada toplanır ve FitMesh hesabınıza yüklenir. Veriler hesabınıza girdikten sonra her yerden erişebilirsiniz: iPhone için FitMesh uygulaması (iOS) ve Apple Health köprüsü yakında geliyor.",
      },
    },
    {
      type: "callout",
      variant: "info",
      title: {
        it: "Uso su iPhone (app iOS in arrivo)",
        en: "Using on iPhone (iOS app coming soon)",
        es: "Uso en iPhone (app iOS próximamente)",
        de: "Nutzung auf dem iPhone (iOS-App demnächst verfügbar)",
        pt: "Uso no iPhone (app iOS em breve)",
        fr: "Utilisation sur iPhone (application iOS bientôt disponible)",
        pl: "Użycie na iPhonie (aplikacja iOS wkrótce)",
        tr: "iPhone'da kullanım (iOS uygulaması yakında)",
      },
      body: {
        it: "Se usi iPhone, configura l'anello Colmi tramite FitMesh Sync su un dispositivo Android (il tuo, o quello di un familiare). I dati vengono caricati sul tuo account FitMesh e saranno accessibili dall'app iOS non appena disponibile. In aggiunta, il ponte opzionale verso Apple Salute ti permettera' di far confluire le metriche dell'anello (sonno, battito, SpO2) direttamente nell'app Salute di Apple. L'app iOS di FitMesh Sync non e' ancora scaricabile su App Store: iscriviti alla beta per essere tra i primi ad accedervi.",
        en: "If you use iPhone, set up the Colmi ring via FitMesh Sync on an Android device (yours or a family member's). The data is uploaded to your FitMesh account and will be accessible from the iOS app as soon as it becomes available. Additionally, the optional Apple Health bridge will let ring metrics (sleep, heart rate, SpO2) flow directly into Apple's Health app. The FitMesh Sync iOS app is not yet available on the App Store: sign up for the beta to be among the first to access it.",
        es: "Si usas iPhone, configura el anillo Colmi a través de FitMesh Sync en un dispositivo Android (el tuyo o el de un familiar). Los datos se suben a tu cuenta FitMesh y estarán accesibles desde la app iOS en cuanto esté disponible. Además, el puente opcional hacia Apple Health permitirá que las métricas del anillo (sueño, frecuencia cardíaca, SpO2) lleguen directamente a la app Salud de Apple. La app iOS de FitMesh Sync todavía no está disponible en el App Store: regístrate en la beta para ser de los primeros en acceder.",
        de: "Wenn du ein iPhone verwendest, richte den Colmi Ring über FitMesh Sync auf einem Android-Gerät ein (deinem eigenen oder dem eines Familienmitglieds). Die Daten werden in dein FitMesh-Konto hochgeladen und stehen über die iOS-App zur Verfügung, sobald diese erscheint. Zusätzlich ermöglicht die optionale Apple-Health-Anbindung, dass die Ringmetriken (Schlaf, Herzfrequenz, SpO2) direkt in die Apple-Health-App fließen. Die FitMesh Sync iOS-App ist noch nicht im App Store erhältlich: Melde dich für die Beta an, um zu den Ersten zu gehören.",
        pt: "Se você usa iPhone, configure o anel Colmi via FitMesh Sync em um dispositivo Android (o seu ou de um familiar). Os dados são enviados para a sua conta FitMesh e ficarão acessíveis pelo app iOS assim que estiver disponível. Além disso, a integração opcional com o Apple Health permitirá que as métricas do anel (sono, frequência cardíaca, SpO2) cheguem diretamente ao app Saúde da Apple. O app iOS do FitMesh Sync ainda não está disponível na App Store: inscreva-se na beta para ser um dos primeiros a ter acesso.",
        fr: "Si vous utilisez un iPhone, configurez la bague Colmi via FitMesh Sync sur un appareil Android (le vôtre ou celui d'un proche). Les données sont téléversées sur votre compte FitMesh et seront accessibles depuis l'application iOS dès qu'elle sera disponible. De plus, le pont optionnel vers Apple Health permettra aux métriques de la bague (sommeil, fréquence cardiaque, SpO2) d'arriver directement dans l'application Santé d'Apple. L'application iOS FitMesh Sync n'est pas encore disponible sur l'App Store: inscrivez-vous à la bêta pour être parmi les premiers à y accéder.",
        pl: "Jeśli używasz iPhone'a, skonfiguruj pierścień Colmi przez FitMesh Sync na urządzeniu z Androidem (swoim lub rodziny). Dane zostaną przesłane na konto FitMesh i będą dostępne w aplikacji iOS, gdy tylko stanie się dostępna. Dodatkowo opcjonalny most do Apple Health pozwoli metrycznym pierścienia (sen, tętno, SpO2) trafiać bezpośrednio do aplikacji Zdrowie Apple. Aplikacja iOS FitMesh Sync nie jest jeszcze dostępna w App Store: zapisz się do bety, aby być wśród pierwszych.",
        tr: "iPhone kullanıyorsanız, Colmi yüzüğünü bir Android cihazda (sizin veya bir aile üyenizin) FitMesh Sync aracılığıyla kurun. Veriler FitMesh hesabınıza yüklenir ve iOS uygulaması çıkar çıkmaz erişilebilir olur. Ayrıca isteğe bağlı Apple Health köprüsü, yüzük metriklerinin (uyku, kalp atış hızı, SpO2) doğrudan Apple Sağlık uygulamasına akmasını sağlar. FitMesh Sync iOS uygulaması henüz App Store'da mevcut değildir: ilk erişenler arasında olmak için betaya kaydolun.",
      },
    },
    // --- UNDERSTANDING THE DATA ---
    {
      type: "heading",
      level: 2,
      text: {
        it: "Capire i dati nella dashboard FitMesh",
        en: "Understanding the data in the FitMesh dashboard",
        es: "Entender los datos en el panel de FitMesh",
        de: "Die Daten im FitMesh-Dashboard verstehen",
        pt: "Entendendo os dados no painel do FitMesh",
        fr: "Comprendre les données dans le tableau de bord FitMesh",
        pl: "Rozumienie danych w panelu FitMesh",
        tr: "FitMesh panosundaki verileri anlamak",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Una volta sincronizzato, nella dashboard FitMesh trovi le metriche dell'anello Colmi organizzate per tipologia.",
        en: "Once synced, the FitMesh dashboard shows your Colmi ring metrics organized by type.",
        es: "Una vez sincronizado, el panel de FitMesh muestra las métricas del anillo Colmi organizadas por tipo.",
        de: "Nach der Synchronisierung zeigt das FitMesh-Dashboard die Colmi-Ring-Metriken nach Typ geordnet an.",
        pt: "Após a sincronização, o painel do FitMesh exibe as métricas do anel Colmi organizadas por tipo.",
        fr: "Une fois synchronisé, le tableau de bord FitMesh affiche les métriques de la bague Colmi organisées par type.",
        pl: "Po synchronizacji panel FitMesh pokazuje metryki pierścienia Colmi posortowane według typu.",
        tr: "Senkronize edildikten sonra FitMesh panosu, Colmi yüzük metriklerini türe göre düzenlenmiş biçimde gösterir.",
      },
    },
    {
      type: "heading",
      level: 3,
      text: {
        it: "Dati giornalieri",
        en: "Daily data",
        es: "Datos diarios",
        de: "Tagesdaten",
        pt: "Dados diários",
        fr: "Données quotidiennes",
        pl: "Dane dzienne",
        tr: "Günlük veriler",
      },
    },
    {
      type: "list",
      items: {
        it: [
          "Passi e distanza",
          "Calorie stimate",
          "Minuti attivi",
          "Frequenza cardiaca media e frequenza cardiaca a riposo",
        ],
        en: [
          "Steps and distance",
          "Estimated calories",
          "Active minutes",
          "Average heart rate and resting heart rate",
        ],
        es: [
          "Pasos y distancia",
          "Calorías estimadas",
          "Minutos activos",
          "Frecuencia cardíaca media y frecuencia cardíaca en reposo",
        ],
        de: [
          "Schritte und Distanz",
          "Geschätzte Kalorien",
          "Aktive Minuten",
          "Durchschnittliche Herzfrequenz und Ruheherzfrequenz",
        ],
        pt: [
          "Passos e distância",
          "Calorias estimadas",
          "Minutos ativos",
          "Frequência cardíaca média e frequência cardíaca em repouso",
        ],
        fr: [
          "Pas et distance",
          "Calories estimées",
          "Minutes actives",
          "Fréquence cardiaque moyenne et fréquence cardiaque au repos",
        ],
        pl: [
          "Kroki i dystans",
          "Szacowane kalorie",
          "Aktywne minuty",
          "Średnie tętno i tętno spoczynkowe",
        ],
        tr: [
          "Adımlar ve mesafe",
          "Tahmini kalori",
          "Aktif dakikalar",
          "Ortalama kalp atış hızı ve dinlenme kalp atış hızı",
        ],
      },
    },
    {
      type: "heading",
      level: 3,
      text: {
        it: "Dati notturni",
        en: "Overnight data",
        es: "Datos nocturnos",
        de: "Nächtliche Daten",
        pt: "Dados noturnos",
        fr: "Données nocturnes",
        pl: "Dane nocne",
        tr: "Gece verileri",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Disponibili ogni mattina dopo la prima sincronizzazione:",
        en: "Available each morning after the first sync:",
        es: "Disponibles cada mañana tras la primera sincronización:",
        de: "Jeden Morgen nach der ersten Synchronisierung verfügbar:",
        pt: "Disponíveis toda manhã após a primeira sincronização:",
        fr: "Disponibles chaque matin après la première synchronisation:",
        pl: "Dostępne każdego ranka po pierwszej synchronizacji:",
        tr: "İlk senkronizasyondan sonra her sabah mevcut:",
      },
    },
    {
      type: "list",
      items: {
        it: [
          "Ore di sonno totali",
          "Distribuzione delle fasi (sonno leggero, profondo, REM, veglia)",
          "HRV notturno (variabilità della frequenza cardiaca)",
          "SpO2 notturno (saturazione stimata dell'ossigeno)",
          "Frequenza cardiaca minima notturna (battito a riposo)",
        ],
        en: [
          "Total sleep hours",
          "Sleep stage breakdown (light, deep, REM, awake)",
          "Overnight HRV (heart rate variability)",
          "Overnight SpO2 (estimated oxygen saturation)",
          "Overnight minimum heart rate (resting HR)",
        ],
        es: [
          "Horas totales de sueño",
          "Distribución de las fases del sueño (ligero, profundo, REM, vigilia)",
          "HRV nocturno (variabilidad de la frecuencia cardíaca)",
          "SpO2 nocturno (saturación estimada de oxígeno)",
          "Frecuencia cardíaca mínima nocturna (frecuencia cardíaca en reposo)",
        ],
        de: [
          "Gesamte Schlafdauer",
          "Verteilung der Schlafphasen (Leichtschlaf, Tiefschlaf, REM, Wachphasen)",
          "Nächtliche HRV (Herzfrequenzvariabilität)",
          "Nächtliche SpO2 (geschätzte Sauerstoffsättigung)",
          "Nächtliche minimale Herzfrequenz (Ruheherzfrequenz)",
        ],
        pt: [
          "Total de horas de sono",
          "Distribuição das fases do sono (leve, profundo, REM, acordado)",
          "HRV noturno (variabilidade da frequência cardíaca)",
          "SpO2 noturno (saturação estimada de oxigênio)",
          "Frequência cardíaca mínima noturna (frequência cardíaca em repouso)",
        ],
        fr: [
          "Heures de sommeil totales",
          "Répartition des phases du sommeil (léger, profond, REM, éveil)",
          "HRV nocturne (variabilité de la fréquence cardiaque)",
          "SpO2 nocturne (saturation en oxygène estimée)",
          "Fréquence cardiaque minimale nocturne (fréquence cardiaque au repos)",
        ],
        pl: [
          "Łączna liczba godzin snu",
          "Podział faz snu (lekki, głęboki, REM, przebudzenia)",
          "Nocny HRV (zmienność rytmu serca)",
          "Nocny SpO2 (szacowane nasycenie tlenem)",
          "Minimalne nocne tętno (tętno spoczynkowe)",
        ],
        tr: [
          "Toplam uyku saatleri",
          "Uyku evresi dağılımı (hafif, derin, REM, uyanık)",
          "Gece HRV (kalp atış hızı değişkenliği)",
          "Gece SpO2 (tahmini oksijen satürasyonu)",
          "Gece minimum kalp atış hızı (dinlenme nabzı)",
        ],
      },
    },
    {
      type: "heading",
      level: 3,
      text: {
        it: "Vista unificata con il tuo smartwatch",
        en: "Unified view with your smartwatch",
        es: "Vista unificada con tu smartwatch",
        de: "Einheitliche Ansicht mit deinem Smartwatch",
        pt: "Visão unificada com o seu smartwatch",
        fr: "Vue unifiée avec votre montre connectée",
        pl: "Ujednolicony widok ze smartwatchem",
        tr: "Smartwatch ile birleşik görünüm",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Se hai gia' collegato uno smartwatch a FitMesh (Galaxy Watch, Pixel Watch, Garmin, Amazfit e altri), i dati dell'anello Colmi si integrano automaticamente con quelli del watch sulla stessa timeline. Di notte le metriche vengono dall'anello; le sessioni di allenamento e le metriche diurne vengono dal watch. Non ci sono doppi conteggi.",
        en: "If you have already connected a smartwatch to FitMesh (Galaxy Watch, Pixel Watch, Garmin, Amazfit, and others), the Colmi ring data integrates automatically with watch data on the same timeline. At night the metrics come from the ring; workout sessions and daytime metrics come from the watch. There is no double counting.",
        es: "Si ya conectaste un smartwatch a FitMesh (Galaxy Watch, Pixel Watch, Garmin, Amazfit y otros), los datos del anillo Colmi se integran automáticamente con los del reloj en la misma línea de tiempo. Por la noche las métricas provienen del anillo; las sesiones de entrenamiento y las métricas diurnas provienen del reloj. No hay duplicados.",
        de: "Wenn du bereits einen Smartwatch mit FitMesh verbunden hast (Galaxy Watch, Pixel Watch, Garmin, Amazfit und andere), werden die Colmi-Ring-Daten automatisch mit den Uhrendaten auf derselben Zeitachse zusammengeführt. Nachts kommen die Metriken vom Ring; Trainingseinheiten und Tagesmetriken kommen von der Uhr. Es gibt keine Doppelzählung.",
        pt: "Se você já conectou um smartwatch ao FitMesh (Galaxy Watch, Pixel Watch, Garmin, Amazfit e outros), os dados do anel Colmi são integrados automaticamente com os dados do relógio na mesma linha do tempo. À noite, as métricas vêm do anel; as sessões de treino e as métricas diurnas vêm do relógio. Não há contagem dupla.",
        fr: "Si vous avez déjà connecté une montre connectée à FitMesh (Galaxy Watch, Pixel Watch, Garmin, Amazfit et autres), les données de la bague Colmi s'intègrent automatiquement aux données de la montre sur la même chronologie. La nuit, les métriques proviennent de la bague; les séances d'entraînement et les métriques diurnes proviennent de la montre. Il n'y a pas de double comptage.",
        pl: "Jeśli już połączyłeś smartwatcha z FitMesh (Galaxy Watch, Pixel Watch, Garmin, Amazfit i inne), dane pierścienia Colmi integrują się automatycznie z danymi zegarka na tej samej osi czasu. W nocy metryki pochodzą z pierścienia; sesje treningowe i dzienne metryki pochodzą z zegarka. Nie ma podwójnego liczenia.",
        tr: "FitMesh'e zaten bir smartwatch bağladıysanız (Galaxy Watch, Pixel Watch, Garmin, Amazfit ve diğerleri), Colmi yüzük verileri saat verileriyle aynı zaman çizelgesinde otomatik olarak birleşir. Geceleri metrikler yüzükten gelir; antrenman seansları ve gündüz metrikleri saattan gelir. Çift sayım yapılmaz.",
      },
    },
    // --- FAQ ---
    // --- CTA ---
    {
      type: "cta",
      title: {
        it: "Hai un anello Colmi e vuoi iniziare?",
        en: "Got a Colmi ring and ready to start?",
        es: "¿Tienes un anillo Colmi y quieres empezar?",
        de: "Hast du einen Colmi Ring und möchtest loslegen?",
        pt: "Tem um anel Colmi e quer começar?",
        fr: "Vous avez une bague Colmi et vous êtes prêt à commencer?",
        pl: "Masz pierścień Colmi i chcesz zacząć?",
        tr: "Colmi yüzüğünüz var ve başlamaya hazır mısınız?",
      },
      body: {
        it: "FitMesh Sync e' in beta privata. I primi 1000 utenti ottengono 1 anno di Pro gratis, incluso l'accesso alla funzione anello Colmi non appena rilasciata. Iscriviti ora per tenere il posto.",
        en: "FitMesh Sync is in private beta. The first 1,000 users get 1 year of Pro for free, including access to the Colmi ring feature as soon as it ships. Sign up now to keep your spot.",
        es: "FitMesh Sync está en beta privada. Los primeros 1.000 usuarios obtienen 1 año de Pro gratis, incluido el acceso a la función del anillo Colmi en cuanto esté disponible. Regístrate ahora para reservar tu lugar.",
        de: "FitMesh Sync befindet sich in der geschlossenen Beta. Die ersten 1.000 Nutzer erhalten 1 Jahr Pro kostenlos, einschließlich Zugang zur Colmi-Ring-Funktion sobald diese verfügbar ist. Melde dich jetzt an, um deinen Platz zu sichern.",
        pt: "O FitMesh Sync está em beta privada. Os primeiros 1.000 usuários ganham 1 ano de Pro grátis, incluindo acesso à função do anel Colmi assim que for lançada. Inscreva-se agora para garantir sua vaga.",
        fr: "FitMesh Sync est en bêta privée. Les 1 000 premiers utilisateurs bénéficient de 1 an de Pro gratuit, incluant l'accès à la fonctionnalité bague Colmi dès sa disponibilité. Inscrivez-vous maintenant pour garder votre place.",
        pl: "FitMesh Sync jest w prywatnej wersji beta. Pierwsze 1000 użytkowników otrzymuje 1 rok Pro za darmo, w tym dostęp do funkcji pierścienia Colmi od razu po jej wydaniu. Zapisz się teraz, aby zachować swoje miejsce.",
        tr: "FitMesh Sync özel beta aşamasındadır. İlk 1.000 kullanıcı, Colmi yüzük özelliğine çıkar çıkmaz erişim dahil olmak üzere 1 yıl Pro ücretsiz alır. Yerinizi ayırtmak için şimdi kaydolun.",
      },
      ctaLabel: {
        it: "Iscriviti alla beta",
        en: "Sign up for beta",
        es: "Regístrate en la beta",
        de: "Zur Beta anmelden",
        pt: "Inscreva-se na beta",
        fr: "S'inscrire à la bêta",
        pl: "Zapisz się do bety",
        tr: "Betaya kaydol",
      },
      ctaHref: {
        it: "/it/beta",
        en: "/en/beta",
        pl: "/pl/beta",
        tr: "/tr/beta",
      },
    },
  ],
  faq: [
    {
      q: {
        it: "Il Colmi R02 e' impermeabile?",
        en: "Is the Colmi R02 waterproof?",
        es: "¿El Colmi R02 es resistente al agua?",
        de: "Ist der Colmi R02 wasserdicht?",
        pt: "O Colmi R02 é à prova d'água?",
        fr: "Le Colmi R02 est-il étanche?",
        pl: "Czy Colmi R02 jest wodoodporny?",
        tr: "Colmi R02 su geçirmez mi?",
      },
      a: {
        it: "Si', il Colmi R02 ha una certificazione IP68: resiste all'immersione fino a 50 metri in acqua dolce secondo le specifiche del produttore. Puoi tenerlo durante la doccia e il lavaggio delle mani. Evita comunque immersioni prolungate in acqua salata o in piscina, che possono deteriorare i materiali nel tempo.",
        en: "Yes. The Colmi R02 carries an IP68 rating: it resists immersion up to 50 meters in fresh water according to the manufacturer's specifications. You can wear it in the shower and while washing your hands. Avoid prolonged immersion in salt water or chlorinated pools, which can degrade the materials over time.",
        es: "Sí. El Colmi R02 tiene certificación IP68: resiste la inmersión hasta 50 metros en agua dulce según las especificaciones del fabricante. Puedes llevarlo en la ducha y al lavarte las manos. Evita la inmersión prolongada en agua salada o en piscinas con cloro, ya que pueden deteriorar los materiales con el tiempo.",
        de: "Ja. Der Colmi R02 besitzt eine IP68-Zertifizierung: Er hält laut Herstellerangaben Tauchgängen bis zu 50 Metern in Süßwasser stand. Du kannst ihn beim Duschen und beim Händewaschen tragen. Vermeide längeres Untertauchen in Salzwasser oder Chlorpools, da dies die Materialien mit der Zeit beschädigen kann.",
        pt: "Sim. O Colmi R02 possui certificação IP68: resiste à imersão de até 50 metros em água doce, de acordo com as especificações do fabricante. Você pode usá-lo no banho e ao lavar as mãos. Evite imersão prolongada em água salgada ou piscinas com cloro, pois podem deteriorar os materiais ao longo do tempo.",
        fr: "Oui. Le Colmi R02 possède une certification IP68: il résiste à l'immersion jusqu'à 50 mètres en eau douce selon les spécifications du fabricant. Vous pouvez le porter sous la douche et lors du lavage des mains. Évitez l'immersion prolongée en eau salée ou en piscine chlorée, qui peuvent dégrader les matériaux avec le temps.",
        pl: "Tak. Colmi R02 posiada certyfikat IP68: według specyfikacji producenta wytrzymuje zanurzenie do 50 metrów w słodkiej wodzie. Możesz go nosić pod prysznicem i podczas mycia rąk. Unikaj dłuższego zanurzenia w słonej wodzie lub basenie z chlorem, co może z czasem degradować materiały.",
        tr: "Evet. Colmi R02, IP68 sertifikasına sahiptir: üretici özelliklerine göre tatlı suda 50 metreye kadar dalmaya dayanır. Duşta ve el yıkamada takabilirsiniz. Zamanla malzemeleri bozabilecek tuzlu suda veya klorlu havuzda uzun süre ıslatmaktan kaçının.",
      },
    },
    {
      q: {
        it: "Devo tenere installata l'app QRing o Colmi per usare FitMesh?",
        en: "Do I need the QRing or Colmi app to use FitMesh?",
        es: "¿Necesito tener instalada la app QRing o Colmi para usar FitMesh?",
        de: "Muss ich die QRing- oder Colmi-App installiert haben, um FitMesh zu nutzen?",
        pt: "Preciso ter o app QRing ou Colmi instalado para usar o FitMesh?",
        fr: "Dois-je garder l'application QRing ou Colmi installée pour utiliser FitMesh?",
        pl: "Muszę mieć zainstalowaną app QRing lub Colmi aby korzystać z FitMesh?",
        tr: "Giyilebilir cihazda QRing uygulaması veya Colmi'i kurmam gerekiyor mu FitMesh kullanmak için?",
      },
      a: {
        it: "No. FitMesh Sync si connette direttamente all'anello Colmi via Bluetooth e non richiede l'app companion del produttore. Puoi disinstallarla se non la usi. Se preferisci tenerla per confronto, non crea conflitti: i due sistemi operano in modo indipendente.",
        en: "No. FitMesh Sync connects directly to the Colmi ring over Bluetooth and does not require the manufacturer's companion app. You can uninstall it if you don't use it. If you prefer to keep it for comparison, there's no conflict: the two systems operate independently.",
        es: "No. FitMesh Sync se conecta directamente al anillo Colmi por Bluetooth y no requiere la app companion del fabricante. Puedes desinstalarla si no la usas. Si prefieres conservarla para comparar, no hay ningún conflicto: los dos sistemas funcionan de forma independiente.",
        de: "Nein. FitMesh Sync verbindet sich direkt per Bluetooth mit dem Colmi Ring und benötigt die Begleit-App des Herstellers nicht. Du kannst sie deinstallieren, wenn du sie nicht verwendest. Möchtest du sie zum Vergleich behalten, gibt es keine Konflikte: Beide Systeme arbeiten unabhängig voneinander.",
        pt: "Não. O FitMesh Sync conecta-se diretamente ao anel Colmi via Bluetooth e não exige o app companion do fabricante. Você pode desinstalá-lo se não usa. Se preferir mantê-lo para comparação, não haverá conflitos: os dois sistemas funcionam de forma independente.",
        fr: "Non. FitMesh Sync se connecte directement à la bague Colmi via Bluetooth et ne nécessite pas l'application du fabricant. Vous pouvez la désinstaller si vous ne l'utilisez pas. Si vous préférez la conserver pour comparer, il n'y a aucun conflit: les deux systèmes fonctionnent de manière indépendante.",
        pl: "No. FitMesh Sync się bezpośrednio łączy z pętlą Colmi poprzez Bluetooth i nie wymaga aplikacji towarzyszącej producenta. Możesz ją odinstalować, jeśli jej nie używasz. Jeśli chcesz zachować obie, nie powstają one konfliktów: dwa systemy działają samodzielnie.",
        tr: "No. FitMesh Sync giyilebilir cihaz Colmi'e doğrudan Bluetooth üzerinden bağlanır ve üretici companion uygulaması gerektirmez. Kullanmıyorsanız kaldırabilirsiniz. Eğer karşılaştırma yapmak istiyorsanız da, iki sistem çatışmaz: her ikisi de bağımsız olarak çalışır.",
      },
    },
    {
      q: {
        it: "L'anello Colmi funziona con iPhone?",
        en: "Does the Colmi ring work with iPhone?",
        es: "¿El anillo Colmi funciona con iPhone?",
        de: "Funktioniert der Colmi Ring mit dem iPhone?",
        pt: "O anel Colmi funciona com iPhone?",
        fr: "La bague Colmi fonctionne-t-elle avec iPhone?",
        pl: "Anellito Colmi działa z iPhone?",
        tr: "Anel Colmi işleyişinde iPhone nedir?",
      },
      a: {
        it: "La connessione Bluetooth tra FitMesh Sync e l'anello Colmi richiede Android. Una volta configurato su Android, pero', i dati vengono caricati sul tuo account FitMesh e saranno visibili anche su iPhone tramite l'app iOS di FitMesh (in arrivo a breve) e facoltativamente su Apple Salute. Se usi solo iPhone, iscriviti alla beta: sarai avvisato al lancio dell'app iOS.",
        en: "The Bluetooth connection between FitMesh Sync and the Colmi ring requires Android. Once set up on Android, however, the data is uploaded to your FitMesh account and will be viewable on iPhone through the FitMesh iOS app (coming soon) and optionally in Apple Health. If you only have an iPhone, sign up for the beta: you will be notified at the iOS app launch.",
        es: "La conexión Bluetooth entre FitMesh Sync y el anillo Colmi requiere Android. Una vez configurado en Android, los datos se suben a tu cuenta FitMesh y podrás verlos en iPhone a través de la app iOS de FitMesh (próximamente) y, de forma opcional, en Apple Health. Si solo tienes iPhone, regístrate en la beta: te avisaremos cuando se lance la app iOS.",
        de: "Die Bluetooth-Verbindung zwischen FitMesh Sync und dem Colmi Ring erfordert Android. Nach der Einrichtung auf Android werden die Daten in dein FitMesh-Konto hochgeladen und sind auf dem iPhone über die FitMesh iOS-App (demnächst verfügbar) und optional in Apple Health abrufbar. Wenn du nur ein iPhone hast, melde dich für die Beta an: Du wirst beim Launch der iOS-App benachrichtigt.",
        pt: "A conexão Bluetooth entre o FitMesh Sync e o anel Colmi requer Android. Uma vez configurado no Android, os dados são enviados para a sua conta FitMesh e ficarão visíveis no iPhone pelo app iOS do FitMesh (em breve) e, opcionalmente, no Apple Health. Se você usa apenas iPhone, inscreva-se na beta: você será avisado no lançamento do app iOS.",
        fr: "La connexion Bluetooth entre FitMesh Sync et la bague Colmi nécessite Android. Une fois configurée sur Android, les données sont téléversées sur votre compte FitMesh et seront consultables sur iPhone via l'application iOS FitMesh (bientôt disponible) et optionnellement dans Apple Health. Si vous n'avez qu'un iPhone, inscrivez-vous à la bêta: vous serez notifié au lancement de l'application iOS.",
        pl: "Połączenie Bluetooth między FitMesh Sync a pęczkiem Colmi wymaga Android. Po skonfigurowaniu na Android, jednakże, dane zostaną załadowane do Twojego konta FitMesh i będą widoczne również w iPhone poprzez aplikację iOS z FitMesh (wkrótce dostępna) oraz opcjonalnie na Apple Salute. Jeśli używasz tylko iPhone, zapisz się do bêta: zostaniesz powiadomiony o wydaniu aplikacji iOS.",
        tr: "Bağlantı Bluetooth arasında FitMesh Sync ve lüks halka Colmi için Android gereklidir. Android'e yapılandırıldıktan sonra, veriler hesabınıza FitMesh'in web sitesine yüklenir ve iPhone üzerinden de görünecektir. iOS adlı FitMesh uygulaması (yakında çıkıyor) ile de görebilirsiniz, ancak isteğe bağlı olarak. Sadece iPhone kullanıyorsanız, beta grubuna katılın: uygulama iOS'nın piyasaya sürülmesiyle ilgili bilgi alacağınızı bildireceksiniz.",
      },
    },
    {
      q: {
        it: "Quanti dati storici vengono scaricati al primo abbinamento?",
        en: "How much historical data is downloaded on first pairing?",
        es: "¿Cuántos datos históricos se descargan al vincular el anillo por primera vez?",
        de: "Wie viele historische Daten werden beim ersten Koppeln heruntergeladen?",
        pt: "Quantos dados históricos são baixados no primeiro emparelhamento?",
        fr: "Combien de données historiques sont téléchargées lors du premier couplage?",
        pl: "Jaki rodzaj danych historycznych jest pobierany podczas pierwszego dopasowania?",
        tr: "Kaç tarihsel veri ilk eşlemede indirilir?",
      },
      a: {
        it: "FitMesh scarica tipicamente gli ultimi 7 giorni di dati dalla memoria dell'anello Colmi. I dati piu' vecchi potrebbero non essere disponibili perche' la memoria interna dell'anello ha capacita' limitata e sovrascrive i dati piu' datati.",
        en: "FitMesh typically downloads the last 7 days of data from the Colmi ring's memory. Older data may not be available because the ring's internal memory is limited and overwrites older records.",
        es: "FitMesh descarga normalmente los últimos 7 días de datos de la memoria del anillo Colmi. Los datos más antiguos pueden no estar disponibles porque la memoria interna del anillo tiene capacidad limitada y sobreescribe los registros más viejos.",
        de: "FitMesh lädt typischerweise die letzten 7 Tage Daten aus dem Ring-Speicher des Colmi herunter. Ältere Daten sind möglicherweise nicht verfügbar, da der interne Speicher des Rings begrenzt ist und ältere Einträge überschreibt.",
        pt: "O FitMesh normalmente baixa os últimos 7 dias de dados da memória do anel Colmi. Dados mais antigos podem não estar disponíveis porque a memória interna do anel tem capacidade limitada e sobrescreve os registros mais antigos.",
        fr: "FitMesh télécharge généralement les 7 derniers jours de données depuis la mémoire de la bague Colmi. Les données plus anciennes peuvent ne pas être disponibles car la mémoire interne de la bague est limitée et écrase les enregistrements plus anciens.",
        pl: "FitMesh pobiera zazwyczaj dane z ostatnich 7 dni z pamięci anegda Colmi. Starsze dane mogą nie być dostępne, ponieważ pamięć wewnętrzna anegdy ma ograniczoną pojemność i nadpisuje starsze dane.",
        tr: "FitMesh giyilebilir cihaz Colmi tipik olarak son 7 günün verisini anlakta indirir. Eski verilerin mevcut olup olmaması, çünkü anlakta sınırlı yer kapasitesi nedeniyle daha eski veriler yenilenir.",
      },
    },
  ],
  related: ["colmi-ring-fitmesh", "tracciare-sonno-anello", "anello-vs-smartwatch"],
  brandsMentioned: ["Colmi"],
};
