import type { BlogPost } from "../types";

export const post: BlogPost = {
  slug: "dati-pixel-watch-dashboard",
  category: "guides",
  publishedAt: "2026-06-18",
  updatedAt: "2026-06-18",
  readMinutes: 8,
  tldr: {
    it: [
      "Il Pixel Watch registra passi, frequenza cardiaca, sonno e calorie su Fitbit; queste metriche finiscono automaticamente in Health Connect su Android.",
      "Da Health Connect, FitMesh Sync legge i tuoi dati e li mostra in una dashboard web personale, senza esportare file a mano.",
      "Se usi anche un anello smart o un altro smartwatch, FitMesh li unisce in un unico pannello: vedi tutto insieme, da un solo posto.",
      "Cosa funziona oggi: passi, frequenza cardiaca, sonno, calorie. Limite onesto: le attività GPS dettagliate non passano via Health Connect.",
      "Il tuo storico rimane privato: FitMesh non rivende i tuoi dati.",
    ],
    en: [
      "Pixel Watch records steps, heart rate, sleep, and calories to Fitbit; these metrics land automatically in Health Connect on Android.",
      "From Health Connect, FitMesh Sync reads your data and shows it in a personal web dashboard, no manual file export needed.",
      "If you also use a smart ring or another smartwatch, FitMesh merges them into one panel: everything in one place.",
      "What works today: steps, heart rate, sleep, calories. Honest limit: detailed GPS activities do not pass through Health Connect.",
      "Your history stays private: FitMesh does not sell your data.",
    ],
    es: [
      "El Pixel Watch registra pasos, frecuencia cardíaca, sueño y calorías en Fitbit; estas métricas llegan automáticamente a Health Connect en Android.",
      "Desde Health Connect, FitMesh Sync lee tus datos y los muestra en un panel personal web, sin exportar archivos a mano.",
      "Si también usas un anillo inteligente u otro smartwatch, FitMesh los une en un único panel: todo en un solo lugar.",
      "Qué funciona hoy: pasos, frecuencia cardíaca, sueño, calorías. Límite honesto: las actividades GPS detalladas no pasan por Health Connect.",
      "Tu historial es privado: FitMesh no vende tus datos.",
    ],
    de: [
      "Die Pixel Watch zeichnet Schritte, Herzfrequenz, Schlaf und Kalorien in Fitbit auf; diese Metriken landen automatisch in Health Connect auf Android.",
      "Aus Health Connect liest FitMesh Sync deine Daten und zeigt sie in einem persönlichen Web-Dashboard an, ohne manuelle Dateiexporte.",
      "Wenn du auch einen Smart-Ring oder eine weitere Smartwatch verwendest, fasst FitMesh alles in einem einzigen Panel zusammen.",
      "Was heute funktioniert: Schritte, Herzfrequenz, Schlaf, Kalorien. Ehrliche Einschränkung: Detaillierte GPS-Aktivitäten laufen nicht über Health Connect.",
      "Deine Daten bleiben privat: FitMesh verkauft sie nicht weiter.",
    ],
    pt: [
      "O Pixel Watch registra passos, frequência cardíaca, sono e calorias no Fitbit; essas métricas chegam automaticamente ao Health Connect no Android.",
      "A partir do Health Connect, o FitMesh Sync lê seus dados e os mostra em um painel pessoal na web, sem exportar arquivos manualmente.",
      "Se você também usa um anel inteligente ou outro smartwatch, o FitMesh os une em um único painel: tudo em um só lugar.",
      "O que funciona hoje: passos, frequência cardíaca, sono, calorias. Limite honesto: atividades GPS detalhadas não passam pelo Health Connect.",
      "Seu histórico fica privado: o FitMesh não vende seus dados.",
    ],
    fr: [
      "La Pixel Watch enregistre les pas, la fréquence cardiaque, le sommeil et les calories dans Fitbit; ces métriques arrivent automatiquement dans Health Connect sur Android.",
      "Depuis Health Connect, FitMesh Sync lit vos données et les affiche dans un tableau de bord personnel en ligne, sans export de fichiers manuel.",
      "Si vous utilisez aussi une bague connectée ou une autre montre connectée, FitMesh les regroupe dans un seul panneau: tout au même endroit.",
      "Ce qui fonctionne aujourd'hui: pas, fréquence cardiaque, sommeil, calories. Limite honnête: les activités GPS détaillées ne passent pas par Health Connect.",
      "Votre historique reste privé: FitMesh ne revend pas vos données.",
    ],
    pl: [
      "Pixel Watch rejestruje kroki, tętno, sen i kalorie na Fitbit; te metryki trafiają automatycznie do Health Connect na Androidzie.",
      "Z Health Connect, FitMesh Sync odczytuje Twoje dane i wyświetla je w osobistym panelu webowym, bez ręcznego eksportowania plików.",
      "Jeśli używasz też inteligentnego pierścienia lub innego smartwatcha, FitMesh łączy je w jednym panelu: wszystko w jednym miejscu.",
      "Co działa dziś: kroki, tętno, sen, kalorie. Uczciwe ograniczenie: szczegółowe aktywności GPS nie przechodzą przez Health Connect.",
      "Twoja historia pozostaje prywatna: FitMesh nie sprzedaje Twoich danych.",
    ],
    tr: [
      "Pixel Watch, adımları, kalp hızını, uykuyu ve kalorileri Fitbit'e kaydeder; bu metrikler Android'de Health Connect'e otomatik olarak ulaşır.",
      "Health Connect'ten FitMesh Sync, verilerinizi okur ve kişisel bir web panosunda gösterir, manuel dosya dışa aktarımı gerekmez.",
      "Ayrıca bir akıllı yüzük veya başka bir smartwatch kullanıyorsanız, FitMesh bunları tek bir panelde birleştirir: her şey tek bir yerde.",
      "Bugün çalışan: adımlar, kalp hızı, uyku, kalori. Dürüst sınırlama: ayrıntılı GPS aktiviteleri Health Connect üzerinden geçmez.",
      "Geçmişiniz gizli kalır: FitMesh verilerinizi satmaz.",
    ],
  },
  primaryKeyword: {
    it: "dati Pixel Watch dashboard personale",
    en: "Pixel Watch data personal dashboard",
    es: "datos Pixel Watch panel personal",
    de: "Pixel Watch Daten persönliches Dashboard",
    pt: "dados Pixel Watch painel pessoal",
    fr: "données Pixel Watch tableau de bord personnel",
    pl: "dane Pixel Watch panel osobisty",
    tr: "veri Pixel Watch kişisel panel",
  },
  secondaryKeywords: {
    it: [
      "Pixel Watch Health Connect",
      "Fitbit Health Connect dashboard",
      "dati Wear OS Health Connect",
      "unire smartwatch dashboard",
      "visualizzare dati salute Android",
    ],
    en: [
      "Pixel Watch Health Connect",
      "Fitbit Health Connect dashboard",
      "Wear OS health data dashboard",
      "merge smartwatch data dashboard",
      "view Android health data",
    ],
    es: [
      "Pixel Watch Health Connect",
      "Fitbit Health Connect panel",
      "datos Wear OS Health Connect",
      "unir smartwatch panel salud",
      "ver datos de salud Android",
    ],
    de: [
      "Pixel Watch Health Connect",
      "Fitbit Health Connect Dashboard",
      "Wear OS Gesundheitsdaten Dashboard",
      "Smartwatch Daten zusammenführen",
      "Android Gesundheitsdaten anzeigen",
    ],
    pt: [
      "Pixel Watch Health Connect",
      "Fitbit Health Connect painel",
      "dados Wear OS Health Connect",
      "unir smartwatch painel saúde",
      "visualizar dados de saúde Android",
    ],
    fr: [
      "Pixel Watch Health Connect",
      "Fitbit Health Connect tableau de bord",
      "données Wear OS Health Connect",
      "fusionner données montre connectée",
      "afficher données santé Android",
    ],
    pl: [
      "__RODO__ __FOUNDERS__",
      "pulp Health Connect panel",
      "dane Health Connect Wear OS",
      "unięcie smartwatch dashboard",
      "wyświetla dane zdrowotne Android",
    ],
    tr: [
      "KVKK Health Connect",
      "KVKK Health Connect pano",
      "veriler Wear OS Health Connect",
      "unire akıllı saat paneli",
      "sağlık verilerini gösterebilir Android",
    ],
  },
  metaDescription: {
    it: "Come vedere i dati del Pixel Watch (Wear OS, Fitbit) su una dashboard personale via Health Connect e unirli ad altri dispositivi con FitMesh Sync. Cosa funziona e limiti onesti.",
    en: "How to view Pixel Watch data (Wear OS, Fitbit) on a personal dashboard via Health Connect and combine it with other devices using FitMesh Sync. What works and honest limits.",
    es: "Cómo ver los datos del Pixel Watch (Wear OS, Fitbit) en un panel personal vía Health Connect y combinarlos con otros dispositivos usando FitMesh Sync. Qué funciona y sus límites reales.",
    de: "Pixel Watch Daten (Wear OS, Fitbit) auf einem persönlichen Dashboard via Health Connect anzeigen und mit anderen Geräten in FitMesh Sync zusammenführen. Was funktioniert und ehrliche Grenzen.",
    pt: "Como ver os dados do Pixel Watch (Wear OS, Fitbit) em um painel pessoal via Health Connect e combiná-los com outros dispositivos usando o FitMesh Sync. O que funciona e os limites reais.",
    fr: "Comment visualiser les données de la Pixel Watch (Wear OS, Fitbit) dans un tableau de bord personnel via Health Connect et les combiner avec d'autres appareils dans FitMesh Sync. Ce qui fonctionne et les vraies limites.",
    pl: "Jak zobaczyć dane z Pixel Watch (Wear OS, Fitbit) na osobistym panelu wykresów poprzez Health Connect i połączyć je z innymi urządzeniami za pomocą FitMesh Sync. Co działa i szczerze określone ograniczenia.",
    tr: "KVKK uyumluluğunu kontrol etmek ve Pixel Watch (Wear OS, Fitbit) verilerini kişisel bir görselleştirme panelinde görmek için Health Connect kullanın. Diğer cihazlara da bu verileri ekleyin. Nasıl çalıştığı ve gerçek limitleri anlayın.",
  },
  hero: {
    kicker: {
      it: "Guida",
      en: "Guide",
      es: "Guía",
      de: "Anleitung",
      pt: "Guia",
      fr: "Guide",
      pl: "Wskazówki",
      tr: "Rehber",
    },
    title: {
      it: "Dati Pixel Watch su una dashboard tua: come funziona con Health Connect",
      en: "Pixel Watch data on your own dashboard: how it works with Health Connect",
      es: "Datos del Pixel Watch en tu propio panel: cómo funciona con Health Connect",
      de: "Pixel Watch Daten auf deinem eigenen Dashboard: so funktioniert es mit Health Connect",
      pt: "Dados do Pixel Watch no seu próprio painel: como funciona com o Health Connect",
      fr: "Données Pixel Watch dans votre propre tableau de bord: comment ca fonctionne avec Health Connect",
      pl: "Dane Pixel Watch na Twojej panelu kontrolnym: jak działa z Health Connect",
      tr: "Veriler Pixel Watch bir kendi panelinde: nasıl çalıştığı ile Health Connect'la beraber",
    },
    subtitle: {
      it: "Il Pixel Watch registra tutto su Fitbit, che poi scrive in Health Connect. Da lì FitMesh Sync raccoglie passi, battito, sonno e calorie e li mette in un unico pannello tuo, insieme agli altri dispositivi che usi.",
      en: "Pixel Watch records everything to Fitbit, which then writes to Health Connect. From there, FitMesh Sync collects steps, heart rate, sleep, and calories and puts them in your own single panel, together with the other devices you use.",
      es: "El Pixel Watch registra todo en Fitbit, que luego escribe en Health Connect. Desde allí, FitMesh Sync recoge pasos, frecuencia cardíaca, sueño y calorías, y los muestra en un panel único tuyo, junto con los otros dispositivos que usas.",
      de: "Die Pixel Watch zeichnet alles in Fitbit auf, das dann in Health Connect schreibt. Von dort sammelt FitMesh Sync Schritte, Herzfrequenz, Schlaf und Kalorien und zeigt sie in deinem eigenen, einzigen Panel an, zusammen mit den anderen Geräten, die du nutzt.",
      pt: "O Pixel Watch registra tudo no Fitbit, que depois escreve no Health Connect. A partir daí, o FitMesh Sync coleta passos, frequência cardíaca, sono e calorias e os coloca em um painel único seu, junto com os outros dispositivos que você usa.",
      fr: "La Pixel Watch enregistre tout dans Fitbit, qui ecrit ensuite dans Health Connect. De la, FitMesh Sync collecte les pas, la frequence cardiaque, le sommeil et les calories et les regroupe dans votre propre panneau unique, avec les autres appareils que vous utilisez.",
      pl: "Rejestruje wszystko na Fitbit, które następnie zapisuje w Health Connect. Od tam FitMesh Sync zbiera kroki, puls, sen i kalorie i umieszcza je w jednym panelu osobistym, razem z innymi urządzeniami, których używasz.",
      tr: "KVKK Pixel Watch tüm bilgileri kaydeder, sonra da Fitbit tarafından yazılır. Buradan FitMesh Sync adı verilen cihaz adım sayısını, kalp atışını, uyku ve klorin miktarını toplar ve bunları tek bir panelde diğer kullandığın giyilebilir cihazlarla bir arada sunar.",
    },
  },
  body: [
    {
      type: "paragraph",
      text: {
        it: "Se hai un Pixel Watch, i tuoi dati di salute fanno un percorso preciso: il dispositivo li registra e li sincronizza su Fitbit (l'app Google per la salute su Pixel). Fitbit li scrive poi su Health Connect, il repository centralizzato di Android. Da Health Connect, qualsiasi app autorizzata può leggerli. FitMesh Sync è una di queste: raccoglie le tue metriche, le visualizza in una dashboard web e, se hai altri dispositivi, le unisce in un unico punto.",
        en: "If you have a Pixel Watch, your health data follows a specific path: the device records it and syncs it to Fitbit (Google's health app on Pixel). Fitbit then writes it to Health Connect, Android's centralized repository. From Health Connect, any authorized app can read it. FitMesh Sync is one of them: it collects your metrics, displays them in a web dashboard, and if you have other devices, merges them into one single place.",
        es: "Si tienes un Pixel Watch, tus datos de salud siguen un camino concreto: el dispositivo los registra y los sincroniza en Fitbit (la app de salud de Google en Pixel). Fitbit los escribe luego en Health Connect, el repositorio centralizado de Android. Desde Health Connect, cualquier app autorizada puede leerlos. FitMesh Sync es una de ellas: recoge tus métricas, las muestra en un panel web y, si tienes otros dispositivos, las une en un solo lugar.",
        de: "Wenn du eine Pixel Watch hast, nimmt deine Gesundheitsdaten einen bestimmten Weg: Das Gerät zeichnet sie auf und synchronisiert sie mit Fitbit (Googles Gesundheits-App auf Pixel). Fitbit schreibt sie dann in Health Connect, das zentrale Repository von Android. Aus Health Connect kann jede autorisierte App sie lesen. FitMesh Sync ist eine davon: Sie sammelt deine Metriken, zeigt sie in einem Web-Dashboard an und fasst sie, wenn du weitere Geräte hast, an einem einzigen Ort zusammen.",
        pt: "Se você tem um Pixel Watch, seus dados de saúde seguem um caminho específico: o dispositivo os registra e os sincroniza com o Fitbit (o app de saúde do Google no Pixel). O Fitbit os escreve então no Health Connect, o repositório centralizado do Android. A partir do Health Connect, qualquer app autorizado pode lê-los. O FitMesh Sync é um deles: coleta suas métricas, as exibe em um painel web e, se você tiver outros dispositivos, as une em um único lugar.",
        fr: "Si vous avez une Pixel Watch, vos données de sante suivent un chemin precis: l'appareil les enregistre et les synchronise sur Fitbit (l'application sante de Google sur Pixel). Fitbit les ecrit ensuite dans Health Connect, le referentiel centralise d'Android. Depuis Health Connect, toute application autorisee peut les lire. FitMesh Sync en fait partie: elle collecte vos metriques, les affiche dans un tableau de bord web et, si vous avez d'autres appareils, les regroupe en un seul endroit.",
        pl: "Jeśli masz Pixel Watch, Twoje dane zdrowotne podążają precyzyjnej ścieżce: urządzenie je zapisuje i synchronizuje na Fitbit (aplikacji zdrowia Google dla Pixel). Następnie Fitbit zapisuje je w Health Connect, centralnym magazynie Android. Z Health Connect, każda zautoryzowana aplikacja może je czytać. FitMesh Sync jest jedną z nich: zbiera Twoje metryki, prezentuje je na panelu web i, jeśli masz inne urządzenia, łączy je w jednym miejscu.",
        tr: "Eğer bir Pixel Watchiniz varsa, sağlık verileriniz belirli bir yolda ilerler: cihaz bu verileri kaydeder ve Google Cloud'a (Fitbit) (Google adlı sağlık uygulaması) ile senkronize eder. Daha sonra Google Cloud, Health Connect (KVKK'ya uygun merkezi depolama alanına) bu verileri yazar. Herhangi bir yetkilendirilmiş uygulama bunları okuyabilir. FitMesh Sync da bunlardan biridir: sağlık metriklerinizi toplar, web tabanlı bir panelde gösterir ve diğer cihazlarla birlikte tek bir noktada birleştirir.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Come arrivano i dati del Pixel Watch a Health Connect",
        en: "How Pixel Watch data reaches Health Connect",
        es: "Cómo llegan los datos del Pixel Watch a Health Connect",
        de: "Wie Pixel Watch Daten zu Health Connect gelangen",
        pt: "Como os dados do Pixel Watch chegam ao Health Connect",
        fr: "Comment les donnees de la Pixel Watch arrivent dans Health Connect",
        pl: "Jak dotarują dane z Pixel Watch do Health Connect",
        tr: "Nasıl Pixel Watch verileri Health Connect'a ulaşıyorlar",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Il Pixel Watch funziona con Wear OS e usa Fitbit come piattaforma principale per registrare le metriche di salute. L'app Fitbit su Android ha il permesso di scrivere in Health Connect: questo significa che ogni sincronizzazione tra il tuo Pixel Watch e il telefono porta i dati anche nel repository comune di Android.",
        en: "Pixel Watch runs Wear OS and uses Fitbit as its primary platform for recording health metrics. The Fitbit app on Android has permission to write to Health Connect: this means every sync between your Pixel Watch and phone also brings data into Android's common repository.",
        es: "El Pixel Watch funciona con Wear OS y usa Fitbit como plataforma principal para registrar las métricas de salud. La app de Fitbit en Android tiene permiso para escribir en Health Connect: esto significa que cada sincronización entre tu Pixel Watch y el teléfono lleva los datos también al repositorio común de Android.",
        de: "Die Pixel Watch laeuft mit Wear OS und nutzt Fitbit als Hauptplattform zur Erfassung von Gesundheitsmetriken. Die Fitbit-App auf Android hat die Berechtigung, in Health Connect zu schreiben: Das bedeutet, dass jede Synchronisierung zwischen deiner Pixel Watch und dem Telefon die Daten auch in das gemeinsame Repository von Android bringt.",
        pt: "O Pixel Watch funciona com Wear OS e usa o Fitbit como plataforma principal para registrar métricas de saúde. O app Fitbit no Android tem permissão para escrever no Health Connect: isso significa que cada sincronização entre o Pixel Watch e o telefone leva os dados também ao repositório comum do Android.",
        fr: "La Pixel Watch fonctionne sous Wear OS et utilise Fitbit comme plateforme principale pour enregistrer les metriques de sante. L'application Fitbit sur Android a l'autorisation d'ecrire dans Health Connect: cela signifie que chaque synchronisation entre votre Pixel Watch et votre telephone apporte les donnees dans le referentiel commun d'Android.",
        pl: "Rozwiązanie działa z Wear OS i wykorzystuje Fitbit jako główną platformę do rejestracji metryk zdrowia. Aplikacja Fitbit na Android ma uprawnienia do zapisu w Health Connect: co oznacza, że każda synchronizacja między Twoim Pixel Watch a telefonem przekazuje dane do wspólnego magazynu Android.",
        tr: "KVKK Pixel Watch ile çalışır ve sağlık metriklerini kaydetmek için ana platform olarak Fitbit kullanır. Uygulama Fitbit'ün Android üzerindeki izinleri şunları içerir: yazma erişimi: bu, Pixel Watch'inizin telefonuna bağlandığında verilerin genel Android deposuna taşınması anlamına gelir.",
      },
    },
    {
      type: "callout",
      variant: "info",
      title: {
        it: "Il percorso dei dati in sintesi",
        en: "The data path in brief",
        es: "El recorrido de los datos en resumen",
        de: "Der Datenweg kurz zusammengefasst",
        pt: "O caminho dos dados em resumo",
        fr: "Le chemin des donnees en bref",
        pl: "Synteza trasy danych",
        tr: "Verişim verilerinin yolculuğu özetlebilir olarak:",
      },
      body: {
        it: "Pixel Watch registra i dati sul dispositivo. L'app Fitbit su Android li sincronizza. Fitbit scrive in Health Connect. FitMesh Sync legge da Health Connect con il tuo permesso e li visualizza nella dashboard.",
        en: "Pixel Watch records data on the device. The Fitbit app on Android syncs them. Fitbit writes to Health Connect. FitMesh Sync reads from Health Connect with your permission and displays them in the dashboard.",
        es: "El Pixel Watch registra los datos en el dispositivo. La app de Fitbit en Android los sincroniza. Fitbit escribe en Health Connect. FitMesh Sync lee de Health Connect con tu permiso y los muestra en el panel.",
        de: "Die Pixel Watch zeichnet Daten auf dem Gerät auf. Die Fitbit-App auf Android synchronisiert sie. Fitbit schreibt in Health Connect. FitMesh Sync liest mit deiner Genehmigung aus Health Connect und zeigt die Daten im Dashboard an.",
        pt: "O Pixel Watch registra os dados no dispositivo. O app Fitbit no Android os sincroniza. O Fitbit escreve no Health Connect. O FitMesh Sync lê do Health Connect com a sua permissão e os exibe no painel.",
        fr: "La Pixel Watch enregistre les donnees sur l'appareil. L'application Fitbit sur Android les synchronise. Fitbit ecrit dans Health Connect. FitMesh Sync lit dans Health Connect avec votre autorisation et les affiche dans le tableau de bord.",
        pl: "Pixel Watch rejestruje dane na urządzeniu. Aplikacja Fitbit na Android synchronizuje je. Fitbit zapisuje w Health Connect. FitMesh Sync odczytuje z Health Connect z Twojej zgody i wyświetla je na panelu głównym.",
        tr: "Pixel Watch veriler cihazda kaydeder. Uygulama Fitbit üzerinde Android üzerinden bu verileri synkronlaştırır. Fitbit Health Connect'den okuyar. FitMesh Syncizin verdiğiniz takdirde Health Connect'den verileri okuyup panelde gösterir.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Cosa funziona oggi: le metriche disponibili",
        en: "What works today: the available metrics",
        es: "Qué funciona hoy: las métricas disponibles",
        de: "Was heute funktioniert: die verfuegbaren Metriken",
        pt: "O que funciona hoje: as métricas disponíveis",
        fr: "Ce qui fonctionne aujourd'hui: les metriques disponibles",
        pl: "Czego działa dzisiaj: dostępne metryki",
        tr: "Bugün ne çalışıyor: mevcut metrikler",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Health Connect ha un elenco preciso di tipi di dati che le app possono leggere e scrivere. Il Pixel Watch, tramite Fitbit, scrive correttamente le seguenti metriche che FitMesh Sync può raccogliere e mostrare:",
        en: "Health Connect has a precise list of data types that apps can read and write. Pixel Watch, via Fitbit, correctly writes the following metrics that FitMesh Sync can collect and display:",
        es: "Health Connect tiene una lista precisa de tipos de datos que las apps pueden leer y escribir. El Pixel Watch, a través de Fitbit, escribe correctamente las siguientes métricas que FitMesh Sync puede recoger y mostrar:",
        de: "Health Connect hat eine genaue Liste von Datentypen, die Apps lesen und schreiben koennen. Die Pixel Watch schreibt ueber Fitbit korrekt die folgenden Metriken, die FitMesh Sync erfassen und anzeigen kann:",
        pt: "O Health Connect tem uma lista precisa de tipos de dados que os apps podem ler e escrever. O Pixel Watch, via Fitbit, escreve corretamente as seguintes métricas que o FitMesh Sync pode coletar e exibir:",
        fr: "Health Connect dispose d'une liste precise de types de donnees que les applications peuvent lire et ecrire. La Pixel Watch, via Fitbit, ecrit correctement les metriques suivantes que FitMesh Sync peut collecter et afficher:",
        pl: "Health Connect mał jak dokładny wymiar typów danych, które mogą czytać i pisać aplikacje. Pixel Watch, poprzez Fitbit, poprawnie zapisuje następujące metryki, które FitMesh Sync może zbierać i prezentować:",
        tr: "Health Connect有一份精确列出应用程序可以读取和写入的数据类型的清单。通过Pixel Watch，Fitbit正确地记录了以下指标，这些指标是FitMesh Sync可以收集并展示的：",
      },
    },
    {
      type: "table",
      caption: {
        it: "Metriche Pixel Watch disponibili via Health Connect",
        en: "Pixel Watch metrics available via Health Connect",
        es: "Métricas del Pixel Watch disponibles vía Health Connect",
        de: "Pixel Watch Metriken verfuegbar ueber Health Connect",
        pt: "Métricas do Pixel Watch disponíveis via Health Connect",
        fr: "Metriques Pixel Watch disponibles via Health Connect",
        pl: "Metryki Pixel Watch dostępne przez Health Connect",
        tr: "Metrikler Pixel Watch ile Health Connect üzerinden kullanılabilir",
      },
      headers: {
        it: ["Metrica", "Disponibile", "Note"],
        en: ["Metric", "Available", "Notes"],
        es: ["Métrica", "Disponible", "Notas"],
        de: ["Metrik", "Verfuegbar", "Hinweise"],
        pt: ["Métrica", "Disponível", "Observações"],
        fr: ["Metrique", "Disponible", "Remarques"],
        pl: [
          "Metrika",
          "Dostępny",
          "Uwagi",
        ],
        tr: [
          "Metrika",
          "Mevcut",
          "Notel",
        ],
      },
      rows: [
        {
          it: ["Passi giornalieri", "Si", "Conta passi completa, aggiornata durante il giorno"],
          en: ["Daily steps", "Yes", "Full step count, updated throughout the day"],
          es: ["Pasos diarios", "Si", "Conteo completo, actualizado durante el dia"],
          de: ["Taegliche Schritte", "Ja", "Vollstaendige Schrittzahl, wird tagesuebergreifend aktualisiert"],
          pt: ["Passos diários", "Sim", "Contagem completa, atualizada ao longo do dia"],
          fr: ["Pas quotidiens", "Oui", "Comptage complet, mis a jour en cours de journee"],
          pl: [
            "Dziennie przechodnie",
            "Si",
            "Zlicz kroki całe, aktualizowane podczas dnia",
          ],
          tr: [
            "Günlük adımlar",
            "Eğer",
            "Adım sayısını tam ve güncel bir şekilde gün boyunca kaydedin",
          ],
        },
        {
          it: ["Frequenza cardiaca", "Si", "Campionamenti continui e valori a riposo"],
          en: ["Heart rate", "Yes", "Continuous samples and resting values"],
          es: ["Frecuencia cardiaca", "Si", "Muestras continuas y valores en reposo"],
          de: ["Herzfrequenz", "Ja", "Kontinuierliche Messungen und Ruhewerte"],
          pt: ["Frequência cardíaca", "Sim", "Amostras contínuas e valores em repouso"],
          fr: ["Frequence cardiaque", "Oui", "Echantillons continus et valeurs au repos"],
          pl: [
            "Częstotliwość serca",
            "Si",
            "Campionamenti kontynuowane i wartości spoczynkowe",
          ],
          tr: [
            "Sekilmesi",
            "Eğer",
            "Devam eden campümler ve dinamik değerler",
          ],
        },
        {
          it: ["Sonno", "Si", "Ore totali e fasi (leggero, profondo, REM) se registrate"],
          en: ["Sleep", "Yes", "Total hours and phases (light, deep, REM) if recorded"],
          es: ["Sueno", "Si", "Horas totales y fases (ligero, profundo, REM) si se registran"],
          de: ["Schlaf", "Ja", "Gesamtstunden und Schlafphasen (Leicht, Tief, REM) wenn aufgezeichnet"],
          pt: ["Sono", "Sim", "Horas totais e fases (leve, profundo, REM) se registradas"],
          fr: ["Sommeil", "Oui", "Heures totales et phases (leger, profond, REM) si enregistrees"],
          pl: [
            "Sono",
            "Si",
            "Ogólny czas oraz fazы (lékcyjny, głęboki, REM) jeśli zarejestrowane",
          ],
          tr: [
            "Uykuyu",
            "Eğer",
            "Toplam saatler ve aşamalar (REM, akıç, derin) kaydedildi",
          ],
        },
        {
          it: ["Calorie", "Si", "Calorie totali giornaliere (attive + basali)"],
          en: ["Calories", "Yes", "Total daily calories (active + basal)"],
          es: ["Calorias", "Si", "Calorias diarias totales (activas + basales)"],
          de: ["Kalorien", "Ja", "Gesamte Tageskalorien (aktive + Grundumsatz)"],
          pt: ["Calorias", "Sim", "Calorias diárias totais (ativas + basais)"],
          fr: ["Calories", "Oui", "Calories quotidiennes totales (actives + de base)"],
          pl: [
            "Kalorie",
            "Si",
            "Kalorii dzienne (aktywne + bazowe)",
          ],
          tr: [
            "Kalorije",
            "Eğer",
            "Günlük toplam kaloriler (__FM_PH_0__ + temel__) __FM_HTML_0__",
          ],
        },
        {
          it: ["Attivita GPS dettagliate", "No", "Le rotte GPS non transitano via Health Connect"],
          en: ["Detailed GPS activities", "No", "GPS routes do not pass through Health Connect"],
          es: ["Actividades GPS detalladas", "No", "Las rutas GPS no pasan por Health Connect"],
          de: ["Detaillierte GPS-Aktivitaeten", "Nein", "GPS-Routen laufen nicht ueber Health Connect"],
          pt: ["Atividades GPS detalhadas", "Nao", "As rotas GPS não passam pelo Health Connect"],
          fr: ["Activites GPS detaillees", "Non", "Les itineraires GPS ne passent pas par Health Connect"],
          pl: [
            "Detale zadaní GPS",
            "Nie",
            "Rotdy nie przechodzą przez Health Connect",
          ],
          tr: [
            "Detaylı GPS aktiviteler",
            "No",
            "Le rotiller GPS geçmiyor Health Connect aracılığıyla",
          ],
        },
      ],
    },
    {
      type: "callout",
      variant: "warning",
      title: {
        it: "Il limite onesto sulle attività GPS",
        en: "The honest limit on GPS activities",
        es: "El limite honesto sobre las actividades GPS",
        de: "Die ehrliche Einschraenkung bei GPS-Aktivitaeten",
        pt: "O limite honesto sobre as atividades GPS",
        fr: "La limite honnete sur les activites GPS",
        pl: "Limit rodo na działalności GPS",
        tr: "Sınıflandırma gerçekçi olarak belirlenen faaliyetler GPS",
      },
      body: {
        it: "Se fai una corsa o un'uscita in bici con il Pixel Watch, la traccia GPS completa e i dettagli dell'attività rimangono su Fitbit ma non transitano in Health Connect (a giugno 2026). FitMesh Sync vedrà la durata e le calorie dell'attività, ma non il percorso né i dati di potenza o cadenza. Questo non è un limite di FitMesh: è come funziona Health Connect oggi per questo tipo di dati.",
        en: "If you go for a run or bike ride with Pixel Watch, the full GPS track and activity details stay on Fitbit but do not pass through Health Connect (as of June 2026). FitMesh Sync will see the activity duration and calories, but not the route or power and cadence data. This is not a FitMesh limit: it is how Health Connect works today for this type of data.",
        es: "Si haces una carrera o salida en bicicleta con el Pixel Watch, la ruta GPS completa y los detalles de la actividad permanecen en Fitbit pero no pasan por Health Connect (a junio de 2026). FitMesh Sync vera la duracion y las calorias de la actividad, pero no el recorrido ni los datos de potencia o cadencia. Esto no es un limite de FitMesh: asi es como funciona Health Connect hoy para este tipo de datos.",
        de: "Wenn du mit der Pixel Watch laufen gehst oder Rad faehrst, bleiben der vollstaendige GPS-Track und die Aktivitaetsdetails in Fitbit, gelangen aber nicht in Health Connect (Stand Juni 2026). FitMesh Sync sieht die Aktivitaetsdauer und die Kalorien, aber nicht die Route oder Leistungs- und Kadenzdaten. Das ist keine FitMesh-Einschraenkung: So funktioniert Health Connect heute fuer diese Art von Daten.",
        pt: "Se você fizer uma corrida ou passeio de bicicleta com o Pixel Watch, a rota GPS completa e os detalhes da atividade ficam no Fitbit, mas não passam pelo Health Connect (em junho de 2026). O FitMesh Sync verá a duração e as calorias da atividade, mas não o percurso nem os dados de potência ou cadência. Isso não é um limite do FitMesh: é assim que o Health Connect funciona hoje para esse tipo de dado.",
        fr: "Si vous partez courir ou faire du velo avec la Pixel Watch, la trace GPS complete et les details de l'activite restent sur Fitbit mais ne passent pas par Health Connect (en juin 2026). FitMesh Sync verra la duree et les calories de l'activite, mais pas le parcours ni les donnees de puissance ou de cadence. Ce n'est pas une limite de FitMesh: c'est ainsi que fonctionne Health Connect aujourd'hui pour ce type de donnees.",
        pl: "Je korzystając z Pixel Watch podczas biegu lub jazdy na rowerze, ścieżka GPS jest kompletna i szczegóły aktywności pozostają w Fitbit, ale nie przekształcają się do Health Connect (do czerwca 2026). FitMesh Sync zna trwałość i kalorie spalone podczas aktywności, ale nie ścieżkę ani dane mocy ani częstotliwości. To nie jest ograniczenie FitMesh: to jak działa Health Connect dzisiaj dla tych rodzajów danych.",
        tr: "Se bir koşusu ya da bisiklet yürüyüşü yaparsınız Pixel Watch ile, izlenen GPS tamam ve faizli etkinlik detayları Fitbit üzerinde kalır ancak transit etmez Health Connect (Haziran 2026'a kadar). FitMesh Sync etkinliğin süresini ve yakılan kalorileri görecektir, ancak yolu veya güç ya da hız verilerini göremez. Bu, FitMesh'in bir sınırı değildir: bu tür veriler için bugün nasıl işlediği gibi Health Connect'de işlemektedir.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Unire il Pixel Watch agli altri tuoi dispositivi",
        en: "Merging Pixel Watch with your other devices",
        es: "Unir el Pixel Watch con tus otros dispositivos",
        de: "Pixel Watch mit deinen anderen Geraeten zusammenfuehren",
        pt: "Unir o Pixel Watch aos seus outros dispositivos",
        fr: "Fusionner la Pixel Watch avec vos autres appareils",
        pl: "Połączyć Pixel Watch z innymi Twoimi urządzeniami",
        tr: "Diğer😉 cihazlara Pixel Watch'i birleştirin",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Molte persone usano più di un dispositivo: magari un Pixel Watch di giorno e un anello smart di notte per il sonno, oppure lo smartwatch in settimana e un altro dispositivo nel fine settimana. Il problema classico è che ogni app mostra solo il suo pezzo di dati. FitMesh Sync risolve questo: legge da Health Connect e da altre fonti autorizzate, poi mostra tutto nella stessa dashboard.",
        en: "Many people use more than one device: perhaps a Pixel Watch during the day and a smart ring at night for sleep, or a smartwatch during the week and another device on weekends. The classic problem is that each app only shows its own piece of data. FitMesh Sync solves this: it reads from Health Connect and other authorized sources, then shows everything in the same dashboard.",
        es: "Muchas personas usan mas de un dispositivo: quiza un Pixel Watch durante el dia y un anillo inteligente de noche para el sueno, o el smartwatch entre semana y otro dispositivo el fin de semana. El problema clasico es que cada app solo muestra su parte de los datos. FitMesh Sync lo resuelve: lee de Health Connect y otras fuentes autorizadas, y luego muestra todo en el mismo panel.",
        de: "Viele Menschen nutzen mehr als ein Geraet: vielleicht eine Pixel Watch tagesueber und einen Smart-Ring nachts fuer den Schlaf, oder die Smartwatch unter der Woche und ein anderes Geraet am Wochenende. Das klassische Problem ist, dass jede App nur ihren eigenen Datenteil anzeigt. FitMesh Sync loest das: Es liest aus Health Connect und anderen autorisierten Quellen und zeigt dann alles im gleichen Dashboard an.",
        pt: "Muitas pessoas usam mais de um dispositivo: talvez um Pixel Watch durante o dia e um anel inteligente à noite para o sono, ou o smartwatch durante a semana e outro dispositivo nos fins de semana. O problema clássico é que cada app mostra apenas o seu pedaço de dados. O FitMesh Sync resolve isso: lê do Health Connect e de outras fontes autorizadas e exibe tudo no mesmo painel.",
        fr: "Beaucoup de personnes utilisent plus d'un appareil: peut-etre une Pixel Watch pendant la journee et une bague connectee la nuit pour le sommeil, ou la montre connectee en semaine et un autre appareil le week-end. Le probleme classique est que chaque application n'affiche que ses propres donnees. FitMesh Sync resout cela: il lit depuis Health Connect et d'autres sources autorisees, puis affiche tout dans le meme tableau de bord.",
        pl: "Wiele osób używa wielu urządzeń: może na przykład Pixel Watch podczas dnia i pętelkę smart w nocy do śledzenia snu, lub smartwatch w tygodniu oraz inną instalację w weekendy. Klasyka problemu polega na tym, że każda aplikacja pokazuje tylko swoje dane. FitMesh Sync rozwiązuje to: czyta z Health Connect i innych zaufanych źródeł, a następnie prezentuje wszystko w jednej panelu nawigacyjnym.",
        tr: "Çoğu kişi birden fazla cihaz kullanıyor: belki bir Pixel Watch gün içinde ve uyku için bir giyilebilir cihaz smart aksesuarı, veya hafta içi akıllı saat ve haftasonu başka bir cihaz. Klasik sorun her uygulama sadece kendi verilerini göstermesidir. FitMesh Sync bu soruyu çözer: verileri Health Connect ve diğer yetkili kaynaklardan okur, sonra aynı panelde gösterir.",
      },
    },
    {
      type: "comparison",
      aTitle: {
        it: "Senza FitMesh Sync",
        en: "Without FitMesh Sync",
        es: "Sin FitMesh Sync",
        de: "Ohne FitMesh Sync",
        pt: "Sem FitMesh Sync",
        fr: "Sans FitMesh Sync",
        pl: "Bez FitMesh Sync",
        tr: "Tanpa FitMesh Sync",
      },
      aItems: {
        it: [
          "I passi del Pixel Watch sono nell'app Fitbit",
          "I dati del sonno dell'anello smart sono nella sua app dedicata",
          "Ogni app mostra solo il proprio dispositivo",
          "Confrontare dati tra dispositivi richiede di aprire app diverse",
        ],
        en: [
          "Pixel Watch steps are in the Fitbit app",
          "Smart ring sleep data is in its dedicated app",
          "Each app only shows its own device",
          "Comparing data across devices requires opening different apps",
        ],
        es: [
          "Los pasos del Pixel Watch estan en la app de Fitbit",
          "Los datos de sueno del anillo inteligente estan en su app dedicada",
          "Cada app solo muestra su propio dispositivo",
          "Comparar datos entre dispositivos requiere abrir apps distintas",
        ],
        de: [
          "Pixel Watch Schritte sind in der Fitbit-App",
          "Schlafdaten des Smart-Rings sind in seiner eigenen App",
          "Jede App zeigt nur ihr eigenes Geraet",
          "Daten geraeteuebergreifend zu vergleichen erfordert das Oeffnen verschiedener Apps",
        ],
        pt: [
          "Os passos do Pixel Watch ficam no app Fitbit",
          "Os dados de sono do anel inteligente ficam no seu app dedicado",
          "Cada app mostra apenas o seu dispositivo",
          "Comparar dados entre dispositivos exige abrir apps diferentes",
        ],
        fr: [
          "Les pas de la Pixel Watch sont dans l'application Fitbit",
          "Les donnees de sommeil de la bague connectee sont dans son application dedie",
          "Chaque application n'affiche que son propre appareil",
          "Comparer les donnees entre appareils necessite d'ouvrir differentes applications",
        ],
        pl: [
          "Kroki dotyczące Pixel Watch są w aplikacji Fitbit",
          "Dane snułu smart są w jego dedykowanej aplikacji",
          "Każda aplikacja pokazuje tylko swój urządzenie",
          "Porównywanie danych między urządzeniami wymaga otwarcia różnych aplikacji",
        ],
        tr: [
          "Ad Pixel Watch adımlarınız Fitbit uygulamasında yer alıyor.",
          "Uyku verisi cihazınızdaki akıllı anelloğrafa kaydedilmiştir",
          "Herapp gösteriyor sadece kendi cihazını",
          "Giyilebilir cihazlar arasında verileri karşılaştırmak için farklı uygulamaları açmanız gerekmektedir.",
        ],
      },
      bTitle: {
        it: "Con FitMesh Sync",
        en: "With FitMesh Sync",
        es: "Con FitMesh Sync",
        de: "Mit FitMesh Sync",
        pt: "Com FitMesh Sync",
        fr: "Avec FitMesh Sync",
        pl: "Z FitMesh Sync",
        tr: "Con FitMesh Sync",
      },
      bItems: {
        it: [
          "Passi, battito, sonno e calorie di tutti i dispositivi in un unico pannello",
          "Dati del Pixel Watch e dell'anello smart affiancati sulla stessa schermata",
          "Storico consultabile da browser, senza aprire app diverse",
          "Se i dati si sovrappongono (stesso giorno, stesso tipo), FitMesh gestisce i duplicati",
        ],
        en: [
          "Steps, heart rate, sleep, and calories from all devices in one panel",
          "Pixel Watch and smart ring data side by side on the same screen",
          "History accessible from browser, without opening different apps",
          "If data overlaps (same day, same type), FitMesh handles duplicates",
        ],
        es: [
          "Pasos, frecuencia cardiaca, sueno y calorias de todos los dispositivos en un solo panel",
          "Datos del Pixel Watch y del anillo inteligente en la misma pantalla",
          "Historial accesible desde el navegador, sin abrir apps distintas",
          "Si los datos se solapan (mismo dia, mismo tipo), FitMesh gestiona los duplicados",
        ],
        de: [
          "Schritte, Herzfrequenz, Schlaf und Kalorien aller Geraete in einem Panel",
          "Pixel Watch und Smart-Ring Daten nebeneinander auf dem gleichen Bildschirm",
          "Verlauf per Browser zugaenglich, ohne verschiedene Apps oeffnen zu muessen",
          "Wenn Daten ueberlappen (gleicher Tag, gleicher Typ), bearbeitet FitMesh Duplikate",
        ],
        pt: [
          "Passos, frequência cardíaca, sono e calorias de todos os dispositivos em um painel único",
          "Dados do Pixel Watch e do anel inteligente lado a lado na mesma tela",
          "Histórico acessível pelo navegador, sem abrir apps diferentes",
          "Se os dados se sobrepõem (mesmo dia, mesmo tipo), o FitMesh gerencia os duplicados",
        ],
        fr: [
          "Pas, frequence cardiaque, sommeil et calories de tous les appareils dans un seul panneau",
          "Donnees de la Pixel Watch et de la bague connectee cote a cote sur le meme ecran",
          "Historique accessible depuis le navigateur, sans ouvrir differentes applications",
          "Si les donnees se chevauchent (meme jour, meme type), FitMesh gere les doublons",
        ],
        pl: [
          "Kroki, rytm serca, sen i kalorie z wszystkich urządzeń w jednym panelu",
          "Dane Pixel Watch i zegarka smart umieszczonych na tej samej ekranie",
          "Historyczny dostępny w przeglądarce, bez otwierania innych aplikacji",
          "Jeżeli dane się nakładają (ten sam dzień, ten sam typ), FitMesh zarządza duplikatami",
        ],
        tr: [
          "Adım, atış, uyku ve tüm cihazlardaki kaloriler bir arada aynı panelde",
          "Veriler ve yanSMART anelgesi aynı ekran üzerinde gösterilir",
          "Tarihçe, farklı uygulamalar açılmadan tarayıcıdan görüntülenebilir",
          "Eğer veriler çakışmaktadır (aynı gün, aynı tür), FitMesh eşlik edenleri yönetir",
        ],
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Come collegare il Pixel Watch a FitMesh Sync: i passi",
        en: "How to connect Pixel Watch to FitMesh Sync: the steps",
        es: "Cómo conectar el Pixel Watch a FitMesh Sync: los pasos",
        de: "Pixel Watch mit FitMesh Sync verbinden: die Schritte",
        pt: "Como conectar o Pixel Watch ao FitMesh Sync: os passos",
        fr: "Comment connecter la Pixel Watch a FitMesh Sync: les etapes",
        pl: "Spospolite Pixel Watch do FitMesh Sync: kroki",
        tr: "Giyilebilir cihazınızı FitMesh Sync ile bağlamak için adımlar:",
      },
    },
    {
      type: "list",
      ordered: true,
      items: {
        it: [
          "Assicurati che l'app Fitbit sul tuo telefono Android sia aggiornata e che il Pixel Watch si sincronizzi regolarmente.",
          "Apri le Impostazioni del telefono e cerca 'Health Connect'. Controlla che Fitbit sia nella lista delle app con accesso in scrittura.",
          "Scarica FitMesh Sync dal Google Play Store e crea il tuo account.",
          "Al primo avvio, FitMesh chiede il permesso di leggere da Health Connect. Concedi i permessi per le metriche che vuoi vedere: passi, frequenza cardiaca, sonno, calorie.",
          "Dopo aver autorizzato, la tua dashboard si popola con i dati storici disponibili in Health Connect.",
          "Se hai altri dispositivi (un anello smart, un secondo smartwatch), puoi aggiungerli dallo stesso pannello: i dati vengono mostrati insieme.",
        ],
        en: [
          "Make sure the Fitbit app on your Android phone is updated and that Pixel Watch syncs regularly.",
          "Open your phone Settings and search for 'Health Connect'. Check that Fitbit is in the list of apps with write access.",
          "Download FitMesh Sync from the Google Play Store and create your account.",
          "On first launch, FitMesh asks for permission to read from Health Connect. Grant permissions for the metrics you want to see: steps, heart rate, sleep, calories.",
          "After authorizing, your dashboard populates with historical data available in Health Connect.",
          "If you have other devices (a smart ring, a second smartwatch), you can add them from the same panel: the data is shown together.",
        ],
        es: [
          "Asegurate de que la app de Fitbit en tu teléfono Android esté actualizada y de que el Pixel Watch se sincronice con regularidad.",
          "Abre los Ajustes del teléfono y busca 'Health Connect'. Comprueba que Fitbit aparece en la lista de apps con acceso de escritura.",
          "Descarga FitMesh Sync desde Google Play Store y crea tu cuenta.",
          "Al primer inicio, FitMesh pide permiso para leer de Health Connect. Concede los permisos para las métricas que quieres ver: pasos, frecuencia cardiaca, sueno, calorias.",
          "Tras autorizar, tu panel se rellena con los datos históricos disponibles en Health Connect.",
          "Si tienes otros dispositivos (un anillo inteligente, otro smartwatch), puedes añadirlos desde el mismo panel: los datos se muestran juntos.",
        ],
        de: [
          "Stelle sicher, dass die Fitbit-App auf deinem Android-Telefon aktuell ist und dass die Pixel Watch regelmaessig synchronisiert.",
          "Oeffne die Telefoneinstellungen und suche nach 'Health Connect'. Pruefe, dass Fitbit in der Liste der Apps mit Schreibzugriff steht.",
          "Lade FitMesh Sync aus dem Google Play Store herunter und erstelle dein Konto.",
          "Beim ersten Start bittet FitMesh um Erlaubnis, aus Health Connect zu lesen. Erteile die Berechtigungen fuer die Metriken, die du sehen moechtest: Schritte, Herzfrequenz, Schlaf, Kalorien.",
          "Nach der Autorisierung fuellt sich dein Dashboard mit den in Health Connect verfuegbaren Verlaufsdaten.",
          "Wenn du weitere Geraete hast (einen Smart-Ring, eine zweite Smartwatch), kannst du sie ueber das gleiche Panel hinzufuegen: Die Daten werden gemeinsam angezeigt.",
        ],
        pt: [
          "Certifique-se de que o app Fitbit no seu celular Android está atualizado e que o Pixel Watch sincroniza regularmente.",
          "Abra as Configurações do celular e procure por 'Health Connect'. Verifique que o Fitbit está na lista de apps com acesso de escrita.",
          "Baixe o FitMesh Sync na Google Play Store e crie sua conta.",
          "Na primeira abertura, o FitMesh pede permissão para ler do Health Connect. Conceda as permissões para as métricas que deseja ver: passos, frequência cardíaca, sono, calorias.",
          "Após autorizar, seu painel é preenchido com os dados históricos disponíveis no Health Connect.",
          "Se você tem outros dispositivos (um anel inteligente, um segundo smartwatch), pode adicioná-los no mesmo painel: os dados são exibidos juntos.",
        ],
        fr: [
          "Assurez-vous que l'application Fitbit sur votre telephone Android est a jour et que la Pixel Watch se synchronise regulierement.",
          "Ouvrez les Parametres du telephone et recherchez 'Health Connect'. Verifiez que Fitbit figure dans la liste des applications avec acces en ecriture.",
          "Telechargez FitMesh Sync depuis le Google Play Store et creez votre compte.",
          "Au premier lancement, FitMesh demande l'autorisation de lire depuis Health Connect. Accordez les autorisations pour les metriques que vous souhaitez voir: pas, frequence cardiaque, sommeil, calories.",
          "Apres autorisation, votre tableau de bord se remplit avec les donnees historiques disponibles dans Health Connect.",
          "Si vous avez d'autres appareils (une bague connectee, une deuxieme montre connectee), vous pouvez les ajouter depuis le meme panneau: les donnees sont affichees ensemble.",
        ],
        pl: [
          "Upewnij się, że aplikacja Fitbit na Twoim telefonie Android jest aktualizowana i że Pixel Watch synchronizuje się regularnie.",
          "Otwórz Ustawienia telefonu i wyszukaj 'Health Connect'. Upewnij się, że Fitbit znajduje się na liście aplikacji otrzymujących dostęp do zapisu.",
          "Pobierz FitMesh Sync z Magazynu Google Play i utwórz swój konto.",
          "Podczas pierwszego uruchomienia, FitMesh pyta o zgody na odczyty z Health Connect. Zezwól na zgody dotyczące pomiarów, które chcesz zobaczyć: kroki, częstotliwość serca, sen, kalorie.",
          "Po podzieleniu się z nami swoimi danymi, twoja panel kontroli wypełnia się dostępnymi historycznymi danymi z Health Connect.",
          "Jeśli masz inne urządzenia (smartannele, drugie smartwatch), można je dodać z tego samego panelu: dane są wyświetlane razem.",
        ],
        tr: [
          "KVKK uyumluluğunu kontrol et ve Fitbit uygulaması telefonun Android üzerinde güncel olduğundan emin ol. Ayrıca, Pixel Watch regular olarak synkronize edilmeli.",
          "Arama telefonunuzun Ayarları ve 'Health Connect''u arayın. Fitbit'nin yazım iznine sahip uygulamalar listesinde olup olmadığını kontrol edin.",
          "İndir FitMesh Sync'u Google Play Mağazasından ve hesabını oluşturun.",
          "İlk çalıştırıldığında, FitMesh Health Connectden okuma izni isteyebilir. İstediğiniz metrikler için izin verin: adımlar, kalp atış hızı, uyku, kalsiyum.",
          "Sonra izin verdiğinizde, profil paneliniz tarihsel olarak mevcut olan Health Connect verileriyle doldurulur.",
          "Eğer başka&display_name=(bir giyilebilir cihaz, ikinci akıllı saat) varsa, bunları aynı panelden ekleyebilirsiniz: veriler birlikte gösterilip gösterilmeyecektir.",
        ],
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Privacy: i tuoi dati rimangono tuoi",
        en: "Privacy: your data stays yours",
        es: "Privacidad: tus datos siguen siendo tuyos",
        de: "Datenschutz: Deine Daten bleiben deine Daten",
        pt: "Privacidade: seus dados continuam sendo seus",
        fr: "Confidentialite: vos donnees restent les votres",
        pl: "prywatność: Twoje dane pozostają Twoimi",
        tr: "Gizlilik: verileriniz kendi sizin kalır",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "FitMesh Sync legge i dati da Health Connect con i permessi espliciti che concedi all'installazione. Non vende lo storico, non lo usa per pubblicità, non lo condivide con terze parti. La dashboard è tua: serve a darti una visione chiara dei tuoi dati, non a monetizzarli.",
        en: "FitMesh Sync reads data from Health Connect with the explicit permissions you grant at installation. It does not sell your history, does not use it for advertising, does not share it with third parties. The dashboard is yours: it is there to give you a clear view of your data, not to monetize it.",
        es: "FitMesh Sync lee los datos de Health Connect con los permisos explícitos que concedes al instalarlo. No vende tu historial, no lo usa para publicidad, no lo comparte con terceros. El panel es tuyo: está para darte una visión clara de tus datos, no para monetizarlos.",
        de: "FitMesh Sync liest Daten aus Health Connect mit den ausdruecklichen Berechtigungen, die du bei der Installation erteilst. Es verkauft deinen Verlauf nicht, nutzt ihn nicht fuer Werbung und gibt ihn nicht an Dritte weiter. Das Dashboard gehoert dir: Es ist dazu da, dir einen klaren Ueberblick ueber deine Daten zu geben, nicht um sie zu vermarkten.",
        pt: "O FitMesh Sync lê os dados do Health Connect com as permissões explícitas que você concede na instalação. Não vende seu histórico, não o usa para publicidade, não o compartilha com terceiros. O painel é seu: serve para dar a você uma visão clara dos seus dados, não para monetizá-los.",
        fr: "FitMesh Sync lit les donnees de Health Connect avec les autorisations explicites que vous accordez lors de l'installation. Il ne vend pas votre historique, ne l'utilise pas pour la publicite, ne le partage pas avec des tiers. Le tableau de bord est le votre: il est la pour vous donner une vision claire de vos donnees, pas pour les monetiser.",
        pl: "FitMesh Sync odczytuje dane z Health Connect na podstawie wyraźnie udzielonych przez Ciebie uprawnień. Nie sprzedaje historii, nie korzysta z niej do celów reklamowych i nie udostępnia jej trzecim stronom. Panel sterowania jest Twoje: służy do zapewnienia Ci jasnego obrazu Twoich danych, a nie do ich monetyzacji.",
        tr: "FitMesh Sync verileri Health Connect ile açık şekilde verdiğiniz izinlerle okuyor. Geçmiş satmayı yapmıyor, reklam için kullanmıyor ve üçüncü taraflarla paylaşıyor değil. Panel senin için: verilerinize net bir bakış açısı sağlar, bunları monetize etmez.",
      },
    },
    {
      type: "cta",
      title: {
        it: "Vuoi provare la dashboard con i dati del tuo Pixel Watch?",
        en: "Want to try the dashboard with your Pixel Watch data?",
        es: "¿Quieres probar el panel con los datos de tu Pixel Watch?",
        de: "Moechtest du das Dashboard mit deinen Pixel Watch Daten ausprobieren?",
        pt: "Quer experimentar o painel com os dados do seu Pixel Watch?",
        fr: "Vous souhaitez essayer le tableau de bord avec les donnees de votre Pixel Watch?",
        pl: "Czy chcesz spróbować panelu dashbard z danymi Twojego Pixel Watch?",
        tr: "İstediğinizde Pixel Watch verilerle deneme panelini deneyebilirsiniz?",
      },
      body: {
        it: "FitMesh Sync è in fase fondatore: accesso anticipato, prezzo bloccato a vita, possibilità di dare forma al prodotto. Se hai un Pixel Watch (o qualsiasi dispositivo che scrive su Health Connect) e vuoi una dashboard web personale, questo è il momento.",
        en: "FitMesh Sync is in founder phase: early access, lifetime locked price, chance to shape the product. If you have a Pixel Watch (or any device that writes to Health Connect) and want a personal web dashboard, this is the moment.",
        es: "FitMesh Sync está en fase fundador: acceso anticipado, precio bloqueado de por vida, posibilidad de dar forma al producto. Si tienes un Pixel Watch (o cualquier dispositivo que escriba en Health Connect) y quieres un panel web personal, este es el momento.",
        de: "FitMesh Sync befindet sich in der Gruender-Phase: Fruehzugang, lebenslang festgesetzter Preis, Moeglichkeit, das Produkt mitzugestalten. Wenn du eine Pixel Watch (oder ein beliebiges Geraet, das in Health Connect schreibt) hast und ein persoenliches Web-Dashboard moechtest, ist jetzt der richtige Zeitpunkt.",
        pt: "O FitMesh Sync está na fase fundador: acesso antecipado, preço bloqueado para sempre, chance de moldar o produto. Se você tem um Pixel Watch (ou qualquer dispositivo que escreve no Health Connect) e quer um painel web pessoal, este é o momento.",
        fr: "FitMesh Sync est en phase fondateur: acces anticipe, prix bloque a vie, possibilite de contribuer a la forme du produit. Si vous avez une Pixel Watch (ou tout appareil qui ecrit dans Health Connect) et souhaitez un tableau de bord web personnel, c'est le moment.",
        pl: "FitMesh Sync jest w fazie foundera: dostęp przedwcześni, cena zablokowana na całe życie, szansa na kształtowanie produktu. Jeśli masz Pixel Watch (lub dowolny urządzenie piszące do Health Connect) i chcesz osobistą panelową widokówkę, to teraz jest idealnie.",
        tr: "FitMesh Sync KVKK'da: erken erişim, fiyat hayat boyu sabit kalmış, ürününüzü şekillendirebilmeniz mümkün. Eğer Pixel Watch'ye sahipsiniz (veya herhangi bir Health Connect cihazına yazan herhangi bir cihaz) ve kişiselleştirilmiş bir web pанelini istiyorsunuz, bu an idealdir.",
      },
      ctaLabel: {
        it: "Entra come fondatore",
        en: "Join as a founder",
        es: "Unete como fundador",
        de: "Als Gruender einsteigen",
        pt: "Entre como fundador",
        fr: "Rejoindre en tant que fondateur",
        pl: "Wejście jako founder",
        tr: "Giriş yap kurucu olarak",
      },
      ctaHref: {
        it: "/it/beta",
        en: "/en/beta",
        es: "/es/beta",
        de: "/de/beta",
        pt: "/pt/beta",
        fr: "/fr/beta",
      },
    },
  ],
  faq: [
    {
      q: {
        it: "Il Pixel Watch scrive automaticamente in Health Connect?",
        en: "Does Pixel Watch automatically write to Health Connect?",
        es: "¿El Pixel Watch escribe automaticamente en Health Connect?",
        de: "Schreibt die Pixel Watch automatisch in Health Connect?",
        pt: "O Pixel Watch escreve automaticamente no Health Connect?",
        fr: "La Pixel Watch ecrit-elle automatiquement dans Health Connect?",
        pl: "Czy Pixel Watch zapisuje się automatycznie w Health Connect?",
        tr: "Pixel Watch KVKK'ye otomatik olarak uygular mı?\nGiyilebilir cihazlarda Health Connect kaydı yapar mı?",
      },
      a: {
        it: "Si, tramite l'app Fitbit. Quando il Pixel Watch si sincronizza con il telefono Android e Fitbit ha il permesso di scrittura su Health Connect abilitato, passi, frequenza cardiaca, sonno e calorie vengono scritti nel repository condiviso. Puoi verificare questo dalle Impostazioni del telefono cercando 'Health Connect' e controllando i permessi dell'app Fitbit.",
        en: "Yes, via the Fitbit app. When Pixel Watch syncs with the Android phone and Fitbit has write permission to Health Connect enabled, steps, heart rate, sleep, and calories are written to the shared repository. You can verify this from phone Settings by searching for 'Health Connect' and checking Fitbit app permissions.",
        es: "Si, a través de la app de Fitbit. Cuando el Pixel Watch se sincroniza con el teléfono Android y Fitbit tiene activado el permiso de escritura en Health Connect, los pasos, la frecuencia cardiaca, el sueno y las calorias se escriben en el repositorio compartido. Puedes verificarlo desde los Ajustes del teléfono buscando 'Health Connect' y revisando los permisos de la app de Fitbit.",
        de: "Ja, ueber die Fitbit-App. Wenn die Pixel Watch mit dem Android-Telefon synchronisiert und Fitbit die Schreibberechtigung fuer Health Connect aktiviert hat, werden Schritte, Herzfrequenz, Schlaf und Kalorien in das gemeinsame Repository geschrieben. Du kannst dies ueber die Telefoneinstellungen pruefen, indem du nach 'Health Connect' suchst und die Berechtigungen der Fitbit-App ueberpruefst.",
        pt: "Sim, via app Fitbit. Quando o Pixel Watch sincroniza com o celular Android e o Fitbit tem a permissão de escrita no Health Connect ativada, passos, frequência cardíaca, sono e calorias são gravados no repositório compartilhado. Você pode verificar isso nas Configurações do celular procurando por 'Health Connect' e verificando as permissões do app Fitbit.",
        fr: "Oui, via l'application Fitbit. Lorsque la Pixel Watch se synchronise avec le telephone Android et que Fitbit dispose de l'autorisation d'ecriture dans Health Connect activee, les pas, la frequence cardiaque, le sommeil et les calories sont ecrits dans le referentiel partage. Vous pouvez le verifier depuis les Parametres du telephone en recherchant 'Health Connect' et en verifiant les autorisations de l'application Fitbit.",
        pl: "Tak, poprzez aplikację Fitbit. Gdy Pixel Watch synchronizuje się z telefonem Android i Fitbit ma włączony dopuszczający zapis do Health Connect, kroki, częstotliwość serca, sen i kalorie są zapisywane w udostępnionym magazynie. Możesz sprawdzić to w Ustawieniach telefonu wyszukując 'Health Connect' i sprawdzając uprawnienia aplikacji Fitbit.",
        tr: "Evet, bu işlem Fitbit aracılığıyla gerçekleşir. Pixel Watch cihazınızın telefon Android ile ve Fitbit'ün Health Connect üzerinde yazma izni aktive edilmiş olduğunda, adımlar, kalp atış hızı, uyku ve kaloriler bu paylaşılan depoya kaydedilir. Bu bilgileri kontrol etmek için telefonun Ayarları'nda 'Health Connect' arayarak ve Fitbit uygulamasının izinlerini kontrol edebilirsiniz.",
      },
    },
    {
      q: {
        it: "Posso vedere le corse GPS del Pixel Watch su FitMesh?",
        en: "Can I see Pixel Watch GPS runs on FitMesh?",
        es: "¿Puedo ver las carreras GPS del Pixel Watch en FitMesh?",
        de: "Kann ich GPS-Laeufe der Pixel Watch auf FitMesh sehen?",
        pt: "Posso ver as corridas GPS do Pixel Watch no FitMesh?",
        fr: "Puis-je voir les courses GPS de la Pixel Watch sur FitMesh?",
        pl: "Czy mogę zobaczyć wyścigi GPS z Pixel Watch na FitMesh?",
        tr: "Görüyorum ki GPS Pixel Watch'in FitMesh'da yarışmalar __FM_PH_0__.",
      },
      a: {
        it: "Le attività GPS dettagliate (traccia completa del percorso, velocità, dati di potenza) non transitano via Health Connect a giugno 2026: rimangono nell'ecosistema Fitbit. FitMesh vedrà l'attività come evento (durata, calorie, tipo di sport) ma non la rotta GPS. Per visualizzare le rotte complete, l'app Fitbit rimane il punto di riferimento oggi.",
        en: "Detailed GPS activities (full route track, speed, power data) do not pass through Health Connect as of June 2026: they remain in the Fitbit ecosystem. FitMesh will see the activity as an event (duration, calories, sport type) but not the GPS route. To view full routes, the Fitbit app remains the reference point today.",
        es: "Las actividades GPS detalladas (ruta completa, velocidad, datos de potencia) no pasan por Health Connect a junio de 2026: permanecen en el ecosistema de Fitbit. FitMesh vera la actividad como un evento (duracion, calorias, tipo de deporte) pero no la ruta GPS. Para ver las rutas completas, la app de Fitbit sigue siendo el punto de referencia hoy.",
        de: "Detaillierte GPS-Aktivitaeten (vollstaendiger Routentrack, Geschwindigkeit, Leistungsdaten) laufen Stand Juni 2026 nicht ueber Health Connect: Sie verbleiben im Fitbit-Oekosystem. FitMesh sieht die Aktivitaet als Ereignis (Dauer, Kalorien, Sportart), aber nicht die GPS-Route. Um vollstaendige Routen anzuzeigen, bleibt die Fitbit-App heute der Referenzpunkt.",
        pt: "Atividades GPS detalhadas (rota completa, velocidade, dados de potência) não passam pelo Health Connect em junho de 2026: ficam no ecossistema do Fitbit. O FitMesh verá a atividade como um evento (duração, calorias, tipo de esporte), mas não a rota GPS. Para visualizar rotas completas, o app Fitbit continua sendo o ponto de referência hoje.",
        fr: "Les activites GPS detaillees (trace complete de l'itineraire, vitesse, donnees de puissance) ne passent pas par Health Connect en juin 2026: elles restent dans l'ecosysteme Fitbit. FitMesh verra l'activite comme un evenement (duree, calories, type de sport) mais pas l'itineraire GPS. Pour afficher les itineraires complets, l'application Fitbit reste aujourd'hui le point de reference.",
        pl: "Aktywności GPS szczegółowo opisane (całkowita trasa, prędkość, dane mocy) nie przekształcają się w Health Connect do czerwca 2026: pozostają one w ekosystemie Fitbit. FitMesh zasięgnie aktywności jako zdarzenie (czas trwania, kalorie, rodzaj sportu), ale nie trasę GPS. Aby zobaczyć pełne trasy, aplikacja Fitbit pozostaje obecnie punktem odniesienia.",
        tr: "Le detaylı GPS aktiviteleri (tam yoldaşlaştırmayı, hızı, güç verilerini) Haziran 2026'dan sonraki tarihlerde Health Connect üzerinden geçmeyecektir: kalıcı ecosisteme kalmaya devam edecek. FitMesh aktivitenizi (süresi, yakılan kalori miktarı, spor türü) görecektir ancak yoldan haberdar olmayacaktır GPS. Tam yolların görüntülenmesi için hala Fitbit uygulamasının kaynak noktası olarak kullanılmaktadır.",
      },
    },
    {
      q: {
        it: "Funziona anche se ho sia un Pixel Watch sia un anello smart?",
        en: "Does it work if I have both a Pixel Watch and a smart ring?",
        es: "¿Funciona si tengo tanto un Pixel Watch como un anillo inteligente?",
        de: "Funktioniert es, wenn ich sowohl eine Pixel Watch als auch einen Smart-Ring habe?",
        pt: "Funciona se eu tiver tanto um Pixel Watch quanto um anel inteligente?",
        fr: "Cela fonctionne-t-il si j'ai a la fois une Pixel Watch et une bague connectee?",
        pl: "Czy działa zarówno przy Pixel Watch, jak i smartbandzie?",
        tr: "Functiyon eğer hem bir Pixel Watch hem de akıllı ağıb olursam da mı?",
      },
      a: {
        it: "Si, ed è uno dei casi d'uso principali di FitMesh Sync. Se entrambi i dispositivi scrivono in Health Connect (il Pixel Watch via Fitbit, l'anello smart via la sua app), FitMesh legge entrambi e li mostra nella stessa dashboard. Nei giorni in cui entrambi registrano gli stessi dati (per esempio i passi), FitMesh gestisce la sovrapposizione evitando duplicati nella visualizzazione.",
        en: "Yes, and it is one of the main use cases for FitMesh Sync. If both devices write to Health Connect (Pixel Watch via Fitbit, the smart ring via its app), FitMesh reads both and shows them in the same dashboard. On days when both record the same data (for example steps), FitMesh handles the overlap to avoid duplicates in the display.",
        es: "Si, y es uno de los casos de uso principales de FitMesh Sync. Si ambos dispositivos escriben en Health Connect (el Pixel Watch a traves de Fitbit, el anillo inteligente a traves de su app), FitMesh lee ambos y los muestra en el mismo panel. En los dias en que ambos registran los mismos datos (por ejemplo los pasos), FitMesh gestiona la superposicion para evitar duplicados en la visualizacion.",
        de: "Ja, und das ist einer der Hauptanwendungsfaelle von FitMesh Sync. Wenn beide Geraete in Health Connect schreiben (Pixel Watch ueber Fitbit, der Smart-Ring ueber seine App), liest FitMesh beide und zeigt sie im gleichen Dashboard an. An Tagen, an denen beide dieselben Daten aufzeichnen (z. B. Schritte), bearbeitet FitMesh die Ueberlappung, um Duplikate in der Anzeige zu vermeiden.",
        pt: "Sim, e é um dos principais casos de uso do FitMesh Sync. Se ambos os dispositivos escrevem no Health Connect (o Pixel Watch via Fitbit, o anel inteligente via seu app), o FitMesh lê ambos e os exibe no mesmo painel. Nos dias em que ambos registram os mesmos dados (por exemplo, passos), o FitMesh gerencia a sobreposição para evitar duplicatas na exibição.",
        fr: "Oui, et c'est l'un des principaux cas d'utilisation de FitMesh Sync. Si les deux appareils ecrivent dans Health Connect (la Pixel Watch via Fitbit, la bague connectee via son application), FitMesh lit les deux et les affiche dans le meme tableau de bord. Les jours ou les deux enregistrent les memes donnees (par exemple les pas), FitMesh gere le chevauchement pour eviter les doublons dans l'affichage.",
        pl: "Tak, i to jest jednym z głównych przypadków użycia dla FitMesh Sync. Gdy oba urządzenia piszą do Health Connect (dane Pixel Watch są wysyłane przez Fitbit, a anel smart przez swoją app), FitMesh odczytuje je oba i wyświetla w tej samej dashboard. W dniach, gdy oba zapisują te same dane (na przykład kroki), FitMesh zarządza połączeniem tych danych, unikając powtarzalnych elementów na ekranie.",
        tr: "Evet, ve bu temel kullanım durumlarından biridir. Her iki cihaz da Health Connect'da yazınca (birincil Pixel Watch'ten Fitbit'e, akıllı anello ise uygulamasından), FitMesh her ikisini okuyar ve aynı panelde gösterir. Her iki cihaz da aynı verileri kaydederken (örneğin adımlar) durunca (FitMesh), verilerin çakışmasını önler ve göstergede tekrarlardan kaçınır.",
      },
    },
    {
      q: {
        it: "Devo avere Fitbit installato per usare FitMesh con il Pixel Watch?",
        en: "Do I need Fitbit installed to use FitMesh with Pixel Watch?",
        es: "¿Necesito tener Fitbit instalado para usar FitMesh con el Pixel Watch?",
        de: "Muss ich Fitbit installiert haben, um FitMesh mit der Pixel Watch zu nutzen?",
        pt: "Preciso ter o Fitbit instalado para usar o FitMesh com o Pixel Watch?",
        fr: "Dois-je avoir Fitbit installe pour utiliser FitMesh avec la Pixel Watch?",
        pl: "Muszę mieć Fitbit zainstalowany, aby korzystać z FitMesh wraz z Pixel Watch?",
        tr: "Gerebilir bir cihazda Fitbit kurmam gerekiyor mu kullanarak FitMesh ile Pixel Watch kullanmak için?",
      },
      a: {
        it: "Si, perché è Fitbit che fa da ponte tra il Pixel Watch e Health Connect. FitMesh Sync legge da Health Connect, non direttamente da Fitbit. Quindi il percorso richiede che Fitbit sia installato, sincronizzi con il Pixel Watch e abbia i permessi di scrittura su Health Connect abilitati. Una volta che questo percorso è attivo, FitMesh può leggere i dati.",
        en: "Yes, because Fitbit bridges the Pixel Watch and Health Connect. FitMesh Sync reads from Health Connect, not directly from Fitbit. So the path requires Fitbit to be installed, syncing with Pixel Watch, and having Health Connect write permissions enabled. Once this path is active, FitMesh can read the data.",
        es: "Si, porque es Fitbit el que hace de puente entre el Pixel Watch y Health Connect. FitMesh Sync lee de Health Connect, no directamente de Fitbit. Por eso el recorrido requiere que Fitbit esté instalado, que sincronice con el Pixel Watch y que tenga activados los permisos de escritura en Health Connect. Una vez que este recorrido está activo, FitMesh puede leer los datos.",
        de: "Ja, weil Fitbit die Bruecke zwischen der Pixel Watch und Health Connect bildet. FitMesh Sync liest aus Health Connect, nicht direkt aus Fitbit. Daher erfordert der Weg, dass Fitbit installiert ist, mit der Pixel Watch synchronisiert und die Schreibberechtigungen fuer Health Connect aktiviert sind. Sobald dieser Weg aktiv ist, kann FitMesh die Daten lesen.",
        pt: "Sim, porque é o Fitbit que faz a ponte entre o Pixel Watch e o Health Connect. O FitMesh Sync lê do Health Connect, não diretamente do Fitbit. Portanto, o caminho exige que o Fitbit esteja instalado, sincronizando com o Pixel Watch e com as permissões de escrita no Health Connect ativas. Uma vez que esse caminho está ativo, o FitMesh pode ler os dados.",
        fr: "Oui, car c'est Fitbit qui fait le pont entre la Pixel Watch et Health Connect. FitMesh Sync lit depuis Health Connect, pas directement depuis Fitbit. Le chemin requiert donc que Fitbit soit installe, qu'il se synchronise avec la Pixel Watch et que les autorisations d'ecriture dans Health Connect soient activees. Une fois ce chemin actif, FitMesh peut lire les donnees.",
        pl: "Tak, ponieważ to jest Fitbit, które służy jako mostek między Pixel Watch a Health Connect. FitMesh Sync czyta z Health Connect, nie bezpośrednio z Fitbit. Zatem ścieżka wymaga, aby Fitbit był zainstalowany, skonfigurowany do synchronizacji z Pixel Watch i miał uprawnienia do zapisu na Health Connect. Po tym, jak ta ścieżka jest aktywna, FitMesh może czytać dane.",
        tr: "Evet, çünkü bu Fitbit Pixel Watch ve Health Connect arasında köprü görevini görür. FitMesh Sync direkt olarak Health Connect den okuyar, ancak Fitbit de bulunmalı, Pixel Watch ile senkronize olmalıdır ve Health Connect 'ye yazma yetkisi aktive edilmiş olmalıdır. Bu yoldan geçiş yapıldıktan sonra, FitMesh verileri okuyabilir.",
      },
    },
    {
      q: {
        it: "Quanto storico vedo nella dashboard dopo aver collegato il Pixel Watch?",
        en: "How much history do I see in the dashboard after connecting Pixel Watch?",
        es: "¿Cuánto historial veo en el panel después de conectar el Pixel Watch?",
        de: "Wie viel Verlauf sehe ich im Dashboard nachdem ich die Pixel Watch verbunden habe?",
        pt: "Quanto histórico vejo no painel depois de conectar o Pixel Watch?",
        fr: "Combien d'historique vois-je dans le tableau de bord apres avoir connecte la Pixel Watch?",
        pl: "Jaka historia widzę w panelu after po podłączeniu Pixel Watch?",
        tr: "Kaç tarihsel veri görsem Pixel Watch bağlandıktan sonra panodala?",
      },
      a: {
        it: "Health Connect conserva i dati per un periodo che dipende dalle impostazioni del telefono e dallo spazio disponibile (di default 30 giorni per la maggior parte dei tipi di dati, ma configurabile fino a 3 anni). FitMesh mostra tutto ciò che Health Connect ha disponibile al momento del collegamento. Per vedere uno storico più lungo, puoi aumentare il periodo di conservazione nelle impostazioni di Health Connect prima di collegare FitMesh.",
        en: "Health Connect stores data for a period depending on phone settings and available space (default 30 days for most data types, but configurable up to 3 years). FitMesh shows everything Health Connect has available at the time of connection. To see a longer history, you can increase the retention period in Health Connect settings before connecting FitMesh.",
        es: "Health Connect almacena los datos durante un periodo que depende de los ajustes del teléfono y del espacio disponible (30 dias por defecto para la mayoria de los tipos de datos, pero configurable hasta 3 anos). FitMesh muestra todo lo que Health Connect tiene disponible en el momento de la conexion. Para ver un historial mas largo, puedes aumentar el periodo de retencion en los ajustes de Health Connect antes de conectar FitMesh.",
        de: "Health Connect speichert Daten fuer einen Zeitraum, der von den Telefoneinstellungen und dem verfuegbaren Speicherplatz abhaengt (standardmaessig 30 Tage fuer die meisten Datentypen, aber bis zu 3 Jahre konfigurierbar). FitMesh zeigt alles, was Health Connect zum Zeitpunkt der Verbindung verfuegbar hat. Um einen laengeren Verlauf zu sehen, kannst du den Aufbewahrungszeitraum in den Health Connect Einstellungen erhoehen, bevor du FitMesh verbindest.",
        pt: "O Health Connect armazena os dados por um período que depende das configurações do celular e do espaço disponível (padrão de 30 dias para a maioria dos tipos de dados, mas configurável até 3 anos). O FitMesh mostra tudo o que o Health Connect tem disponível no momento da conexão. Para ver um histórico mais longo, você pode aumentar o período de retenção nas configurações do Health Connect antes de conectar o FitMesh.",
        fr: "Health Connect stocke les donnees pour une periode dependant des parametres du telephone et de l'espace disponible (30 jours par defaut pour la plupart des types de donnees, mais configurable jusqu'a 3 ans). FitMesh affiche tout ce que Health Connect a disponible au moment de la connexion. Pour voir un historique plus long, vous pouvez augmenter la periode de conservation dans les parametres de Health Connect avant de connecter FitMesh.",
        pl: "Health Connect zapisuje dane na czas zależny od ustawień telefonu i dostępnej przestrzeni (domyślnie 30 dni dla większości typów danych, ale konfigurowalne do 3 lat). FitMesh pokazuje wszystko, co Health Connect ma dostępne w momencie połączenia. Aby zobaczyć dłuższy historik, możesz zwiększyć okres przechowywania w ustawieniach Health Connect przed połączeniem FitMesh.",
        tr: "Health Connect veriye bir süre tutar, bu süre telefon ayarlarına ve mevcut yerel alanın bağımlılığına bağlıdır (varsayılan olarak çoğu verinin 30 gün, ancak 3 yıl kadar yapılandırılabilir). FitMesh bağlanırken Health Connect tarafından sağlanan tüm bilgiyi gösterir. daha uzun bir tarih aralığı görüntülemek için Health Connect ayarlarında bağlanmadan önce veri tutma süresini artırabilirsiniz.",
      },
    },
    {
      q: {
        it: "Il Pixel Watch di prima generazione funziona come quello di seconda o terza?",
        en: "Does first generation Pixel Watch work the same as second or third gen?",
        es: "¿El Pixel Watch de primera generacion funciona igual que el de segunda o tercera?",
        de: "Funktioniert die Pixel Watch der ersten Generation genauso wie die zweite oder dritte?",
        pt: "O Pixel Watch de primeira geração funciona igual ao de segunda ou terceira?",
        fr: "La Pixel Watch de premiere generation fonctionne-t-elle comme la deuxieme ou troisieme?",
        pl: "Czy pierwsze pokolenie Pixel Watch działa jak drugie lub trzecie?",
        tr: "İlk Pixel Watch nesneden ikinci veya üçüncü nesneye nasıl çalışır?",
      },
      a: {
        it: "Per le metriche di base che passano via Health Connect (passi, frequenza cardiaca, sonno, calorie) si, il meccanismo è lo stesso. Tutte le generazioni di Pixel Watch usano Fitbit come piattaforma e scrivono in Health Connect tramite l'app Fitbit su Android. Potrebbero esserci differenze nelle metriche più avanzate disponibili su ciascun modello, ma il collegamento con FitMesh via Health Connect funziona per tutte le generazioni.",
        en: "For the basic metrics that pass through Health Connect (steps, heart rate, sleep, calories) yes, the mechanism is the same. All Pixel Watch generations use Fitbit as their platform and write to Health Connect via the Fitbit app on Android. There may be differences in the more advanced metrics available on each model, but the connection with FitMesh via Health Connect works for all generations.",
        es: "Para las metricas basicas que pasan por Health Connect (pasos, frecuencia cardiaca, sueno, calorias) si, el mecanismo es el mismo. Todas las generaciones del Pixel Watch usan Fitbit como plataforma y escriben en Health Connect a traves de la app de Fitbit en Android. Puede haber diferencias en las metricas mas avanzadas disponibles en cada modelo, pero la conexion con FitMesh via Health Connect funciona para todas las generaciones.",
        de: "Fuer die Basismetriken, die ueber Health Connect laufen (Schritte, Herzfrequenz, Schlaf, Kalorien), ja, der Mechanismus ist derselbe. Alle Pixel Watch Generationen nutzen Fitbit als Plattform und schreiben ueber die Fitbit-App auf Android in Health Connect. Es kann Unterschiede bei den fortgeschritteneren Metriken geben, die fuer jedes Modell verfuegbar sind, aber die Verbindung mit FitMesh ueber Health Connect funktioniert fuer alle Generationen.",
        pt: "Para as métricas básicas que passam pelo Health Connect (passos, frequência cardíaca, sono, calorias), sim, o mecanismo é o mesmo. Todas as gerações do Pixel Watch usam o Fitbit como plataforma e escrevem no Health Connect via o app Fitbit no Android. Pode haver diferenças nas métricas mais avançadas disponíveis em cada modelo, mas a conexão com o FitMesh via Health Connect funciona para todas as gerações.",
        fr: "Pour les metriques de base qui passent par Health Connect (pas, frequence cardiaque, sommeil, calories) oui, le mecanisme est le meme. Toutes les generations de Pixel Watch utilisent Fitbit comme plateforme et ecrivent dans Health Connect via l'application Fitbit sur Android. Il peut y avoir des differences dans les metriques plus avancees disponibles sur chaque modele, mais la connexion avec FitMesh via Health Connect fonctionne pour toutes les generations.",
        pl: "Dla podstawowych miar, które przechodzą przez Health Connect (kroki, częstotliwość serca, sen, kalorie), tak, mechanizm jest taki sam. Wszystkie generacje Pixel Watch używają Fitbit jako platformy i zapisują się w Health Connect poprzez aplikację Fitbit na Android. Mogą istnieć różnice w zaawansowanych miarach dostępnych na każdym modelu, ale łączenie się z FitMesh poprzez Health Connect działa dla wszystkich generacji.",
        tr: "Temel istatiksel veriler (Health Connect adımları, kalp atış hızı, uyku, kalsiyum) için evet, mekanizma aynı. Tüm Pixel Watch pheşenliklerinin her nesilinde Fitbit platformu kullanılır ve Health Connect ile Android üzerindeki uygulama Fitbit üzerinden yazılır. Her modelde mevcut olmayan gelişmiş istatistiklerde farklılıklar olabilir, ancak Health Connect ile FitMesh arasında bağlantı her nesilden geçerli.",
      },
    },
  ],
  related: [
    "come-funziona-health-connect",
    "sync-them-all",
    "piu-smartwatch-insieme-dati-doppi",
  ],
  brandsMentioned: ["Google", "Pixel Watch", "Health Connect"],
  ldType: "BlogPosting",
};
