import type { BlogPost } from "../types";

export const post: BlogPost = {
  slug: "dati-anello-smart-apple-salute",
  category: "guides",
  publishedAt: "2026-06-12",
  updatedAt: "2026-06-12",
  readMinutes: 8,
  tldr: {
    it: [
      "FitMesh Sync legge i dati del tuo anello smart o smartwatch Android, li sincronizza sul cloud EU, e li scrive in Apple Salute via HealthKit: così chi ha due telefoni vede tutto in un posto solo.",
      "Il ponte è opt-in: se Apple Salute ha già quei dati (per esempio da Apple Watch), FitMesh non li riscrive. Niente doppioni.",
      "Sonno con fasi complete (profondo, leggero, REM): l'anello è specialista notturno e le fasi vengono scritte in Apple Salute esattamente come le registra il sensore.",
      "Privacy EU/GDPR: tutti i dati transitano su cloud in datacenter EU. FitMesh non vende dati e non li usa per addestrare modelli.",
      "Il bridge funziona in background: nessun export manuale, nessuna app companion del produttore richiesta su iPhone.",
    ],
    en: [
      "FitMesh Sync reads data from your smart ring or Android smartwatch, syncs it to EU cloud, and writes it into Apple Health via HealthKit: so users with two phones see everything in one place.",
      "The bridge is opt-in: if Apple Health already has that data (for example from Apple Watch), FitMesh won't rewrite it. No duplicates.",
      "Sleep with full stages (deep, light, REM): the ring is a nighttime specialist and stages are written to Apple Health exactly as recorded by the sensor.",
      "EU/GDPR privacy: all data transits through EU datacenter cloud. FitMesh doesn't sell data or use it to train models.",
      "The bridge runs in the background: no manual exports, no manufacturer companion app required on iPhone.",
    ],
    es: [
      "FitMesh Sync lee los datos de tu anillo inteligente o smartwatch Android, los sincroniza en la nube EU y los escribe en Apple Salud a través de HealthKit: así, quienes tienen dos teléfonos ven todo en un solo lugar.",
      "El puente es opt-in: si Apple Salud ya tiene esos datos (por ejemplo, de Apple Watch), FitMesh no los vuelve a escribir. Sin duplicados.",
      "Sueño con fases completas (profundo, ligero, REM): el anillo es especialista nocturno y las fases se escriben en Apple Salud exactamente como las registra el sensor.",
      "Privacidad EU/GDPR: todos los datos pasan por la nube en centros de datos de la UE. FitMesh no vende datos ni los usa para entrenar modelos.",
      "El bridge funciona en segundo plano: sin exportaciones manuales, sin necesidad de una app companion del fabricante en iPhone.",
    ],
    de: [
      "FitMesh Sync liest die Daten deines Smart-Rings oder Android-Smartwatches, synchronisiert sie in die EU-Cloud und schreibt sie über HealthKit in Apple Health: So sehen Nutzer mit zwei Telefonen alles an einem Ort.",
      "Die Brücke ist opt-in: Wenn Apple Health diese Daten bereits hat (zum Beispiel von der Apple Watch), überschreibt FitMesh sie nicht. Keine Duplikate.",
      "Schlaf mit vollständigen Schlafphasen (Tiefschlaf, Leichtschlaf, REM): Der Ring ist ein Nacht-Spezialist und die Phasen werden in Apple Health genau so geschrieben, wie der Sensor sie aufzeichnet.",
      "EU/DSGVO-Datenschutz: Alle Daten werden über Cloud-Server in EU-Rechenzentren übertragen. FitMesh verkauft keine Daten und verwendet sie nicht zum Trainieren von Modellen.",
      "Die Brücke läuft im Hintergrund: kein manueller Export, keine Begleit-App des Herstellers auf dem iPhone erforderlich.",
    ],
    pt: [
      "FitMesh Sync lê os dados do seu anel inteligente ou smartwatch Android, sincroniza com a nuvem EU e os grava no Apple Saúde via HealthKit: assim, quem tem dois telefones vê tudo em um só lugar.",
      "A ponte é opt-in: se o Apple Saúde já tiver esses dados (por exemplo, do Apple Watch), o FitMesh não os reescreve. Sem duplicatas.",
      "Sono com fases completas (profundo, leve, REM): o anel é especialista noturno e as fases são gravadas no Apple Saúde exatamente como o sensor as registra.",
      "Privacidade EU/RGPD: todos os dados trafegam por servidores em datacenters na UE. O FitMesh não vende dados nem os usa para treinar modelos.",
      "A ponte funciona em segundo plano: sem exportações manuais, sem necessidade de app companion do fabricante no iPhone.",
    ],
    fr: [
      "FitMesh Sync lit les données de votre bague connectée ou de votre montre connectée Android, les synchronise dans le cloud EU et les écrit dans Santé Apple via HealthKit : ainsi, ceux qui ont deux téléphones voient tout au même endroit.",
      "Le pont est opt-in : si Santé Apple possède déjà ces données (par exemple depuis une Apple Watch), FitMesh ne les réécrit pas. Aucun doublon.",
      "Sommeil avec phases complètes (profond, léger, REM) : la bague est spécialiste du suivi nocturne et les phases sont écrites dans Santé Apple exactement telles qu'enregistrées par le capteur.",
      "Confidentialité EU/RGPD : toutes les données transitent par des serveurs en datacenters européens. FitMesh ne vend pas les données et ne les utilise pas pour entraîner des modèles.",
      "Le pont fonctionne en arrière-plan : aucune exportation manuelle, aucune application compagnon du fabricant requise sur iPhone.",
    ],
    pl: [
      "FitMesh Sync odczytuje dane z Twojego inteligentnego pierścienia lub smartwatcha Android, synchronizuje je w chmurze EU i zapisuje do Apple Zdrowie przez HealthKit: tak osoby z dwoma telefonami widzą wszystko w jednym miejscu.",
      "Mostek jest opt-in: jeśli Apple Zdrowie już ma te dane (np. z Apple Watch), FitMesh ich nie nadpisze. Bez duplikatów.",
      "Sen z pełnymi fazami (głęboki, lekki, REM): pierścień to nocny specjalista i fazy są zapisywane w Apple Zdrowie dokładnie tak, jak je rejestruje czujnik.",
      "Prywatność EU/RODO: wszystkie dane przechodzą przez chmurę w centrach danych w UE. FitMesh nie sprzedaje danych ani nie używa ich do trenowania modeli.",
      "Mostek działa w tle: bez ręcznego eksportu, bez aplikacji companion producenta wymaganej na iPhonie.",
    ],
    tr: [
      "FitMesh Sync, akıllı yüzüğünüzün veya Android smartwatch'unuzun verilerini okur, AB bulutunda senkronize eder ve HealthKit aracılığıyla Apple Sağlık'a yazar: böylece iki telefonu olan kullanıcılar her şeyi tek bir yerde görür.",
      "Köprü opt-in'dir: Apple Sağlık bu verilere zaten sahipse (örn. Apple Watch'tan), FitMesh bunları yeniden yazmaz. Yineleme olmaz.",
      "Tam evreli uyku (derin, hafif, REM): yüzük gece uzmanıdır ve evreler Apple Sağlık'a sensör tarafından kaydedildiği şekliyle yazılır.",
      "AB/KVKK gizliliği: tüm veriler AB veri merkezlerindeki bulut sunucularından geçer. FitMesh veri satmaz ve model eğitmek için kullanmaz.",
      "Köprü arka planda çalışır: manuel dışa aktarma yok, iPhone'da üretici companion uygulaması gerekmez.",
    ],
  },
  primaryKeyword: {
    it: "anello smart dati apple salute",
    en: "smart ring data apple health",
    es: "anillo inteligente datos apple salud",
    de: "Smart-Ring Daten Apple Health",
    pt: "anel inteligente dados apple saúde",
    fr: "bague connectée données santé apple",
    pl: "dane inteligentnego pierścienia apple zdrowie",
    tr: "akıllı yüzük verileri apple sağlık",
  },
  secondaryKeywords: {
    it: [
      "scrivere dati wearable android in apple salute",
      "ponte apple salute smartwatch android",
      "anello smart iphone apple health",
      "come portare sonno android su apple salute",
      "fitmesh apple health bridge",
    ],
    en: [
      "write android wearable data to apple health",
      "apple health bridge android smartwatch",
      "smart ring iphone apple health",
      "how to get android sleep data into apple health",
      "fitmesh apple health write bridge",
    ],
    pt: [
      "gravar dados wearable android no apple saúde",
      "ponte apple saúde smartwatch android",
      "anel inteligente iphone apple health",
      "como levar sono android para apple saúde",
      "fitmesh ponte apple health",
    ],
    fr: [
      "écrire les données wearable android dans apple santé",
      "passerelle apple santé smartwatch android",
      "bague connectée iphone apple health",
      "comment importer le sommeil android dans apple santé",
      "fitmesh passerelle apple health",
    ],
    pl: [
      "zapisywanie danych wearable android do apple zdrowie",
      "mostek apple zdrowie smartwatch android",
      "inteligentny pierścień iphone apple health",
      "jak przenieść dane snu android do apple zdrowie",
      "fitmesh mostek apple health",
    ],
    tr: [
      "android wearable verilerini apple sağlık'a yazma",
      "apple sağlık köprüsü android smartwatch",
      "akıllı yüzük iphone apple health",
      "android uyku verilerini apple sağlık'a aktarma",
      "fitmesh apple health yazma köprüsü",
    ],
  },
  metaDescription: {
    it: "Come FitMesh Sync porta i dati del tuo anello smart o smartwatch Android dentro Apple Salute: bridge opt-in, zero duplicati, sonno con fasi. Privacy EU, GDPR. Guida completa.",
    en: "How FitMesh Sync brings your smart ring or Android smartwatch data into Apple Health: opt-in bridge, zero duplicates, sleep with stages. EU privacy, GDPR. Complete guide.",
    es: "Cómo FitMesh Sync lleva los datos de tu anillo inteligente o smartwatch Android a Apple Salud: puente opt-in, cero duplicados, sueño con fases. Privacidad EU, GDPR. Guía completa.",
    de: "Wie FitMesh Sync die Daten deines Smart-Rings oder Android-Smartwatches in Apple Health überträgt: opt-in Brücke, keine Duplikate, Schlaf mit Phasen. EU-Datenschutz, DSGVO. Vollständige Anleitung.",
    pt: "Como o FitMesh Sync leva os dados do seu anel inteligente ou smartwatch Android para o Apple Saúde: ponte opt-in, zero duplicatas, sono com fases. Privacidade EU, RGPD. Guia completo.",
    fr: "Comment FitMesh Sync transfère les données de votre bague connectée ou montre connectée Android dans Santé Apple : pont opt-in, zéro doublon, sommeil avec phases. Confidentialité EU, RGPD. Guide complet.",
    pl: "Jak wysłać dane inteligentnego pierścienia (Colmi, RingConn) lub smartwatcha Android do Apple Zdrowie przez HealthKit. FitMesh Sync tworzy mostek między Androidem a iPhonem, bez ręcznych eksportów.",
    tr: "Akıllı yüzük (Colmi, RingConn) veya Android smartwatch verilerini HealthKit üzerinden Apple Sağlık'a nasıl gönderirsiniz. FitMesh Sync, manuel dışa aktarma olmadan Android ile iPhone arasında köprü kurar.",
  },
  hero: {
    kicker: {
      it: "Guida d'uso",
      en: "User guide",
      es: "Guía de uso",
      de: "Anleitung",
      pt: "Guia de uso",
      fr: "Guide d'utilisation",
      pl: "Przewodnik użytkownika",
      tr: "Kullanım Kılavuzu",
    },
    title: {
      it: "I dati del tuo anello smart dentro Apple Salute: come funziona il ponte",
      en: "Your smart ring data inside Apple Health: how the bridge works",
      es: "Los datos de tu anillo inteligente dentro de Apple Salud: cómo funciona el puente",
      de: "Die Daten deines Smart-Rings in Apple Health: so funktioniert die Brücke",
      pt: "Os dados do seu anel inteligente no Apple Saúde: como funciona a ponte",
      fr: "Les données de votre bague connectée dans Santé Apple : comment fonctionne le pont",
      pl: "Dane zegła inteligentnego w Apple Zdrowie: jak działa pułapka",
      tr: "Veriğin senin pisolinin Apple Sağlık içinde: köprü nasıl çalışır?",
    },
    subtitle: {
      it: "Se hai un anello smart o un Galaxy Watch accoppiati con Android, i loro dati non arrivano automaticamente in Apple Salute sul tuo iPhone. FitMesh Sync risolve questo con un ponte cloud opt-in: ecco cosa attivare, cosa compare su iPhone, e qualche risposta alle domande più comuni.",
      en: "If you have a smart ring or Galaxy Watch paired with Android, their data doesn't automatically reach Apple Health on your iPhone. FitMesh Sync fixes this with an opt-in cloud bridge: here's what to activate, what shows up on iPhone, and answers to the most common questions.",
      es: "Si tienes un anillo inteligente o un Galaxy Watch vinculados a Android, sus datos no llegan automáticamente a Apple Salud en tu iPhone. FitMesh Sync resuelve esto con un puente en la nube opt-in: aquí tienes qué activar, qué aparece en iPhone y respuestas a las preguntas más frecuentes.",
      de: "Wenn du einen Smart-Ring oder eine Galaxy Watch mit Android gekoppelt hast, gelangen deren Daten nicht automatisch in Apple Health auf deinem iPhone. FitMesh Sync löst dieses Problem mit einer opt-in Cloud-Brücke: Hier erfährst du, was du aktivieren musst, was auf dem iPhone erscheint und erhältst Antworten auf die häufigsten Fragen.",
      pt: "Se você tem um anel inteligente ou um Galaxy Watch pareado com Android, os dados não chegam automaticamente ao Apple Saúde no seu iPhone. FitMesh Sync resolve isso com uma ponte de nuvem opt-in: veja o que ativar, o que aparece no iPhone e respostas às perguntas mais comuns.",
      fr: "Si vous avez une bague connectée ou une Galaxy Watch couplée à Android, leurs données n'arrivent pas automatiquement dans Santé Apple sur votre iPhone. FitMesh Sync résout cela avec un pont cloud opt-in : voici ce qu'il faut activer, ce qui s'affiche sur iPhone, et des réponses aux questions les plus fréquentes.",
      pl: "Jeśli masz smartannelett lub Galaxy Watch połączone z Android, ich dane nie są automatycznie przesyłane do Apple Zdrowia na Twoim iPhone. FitMesh Sync rozwiązuje to za pomocą włączalnego pułapka chmury: oto, co włączyć, co pojawi się na iPhone, oraz kilka odpowiedzi na najczęściej zadawane pytania.",
      tr: "Eğer bir smart ayağınız veya Galaxy Watch cihazınız Android ile eşleştirilmişse, verilerin otomatik olarak Apple Sağlık'a ulaşmamaktadır. FitMesh Sync bu konuyu bir girdiye bağlı bulut köprüsüyle çözüyor: bunu nasıl etkinleştireceğinizi, iPhone 'de ne görmeniz gerektiğini ve sık sorulan bazı soruların cevaplarını buradan bulabilirsiniz.",
    },
  },
  body: [
    {
      type: "paragraph",
      text: {
        it: "Ho trovato personalmente questo problema fastidioso: Galaxy Watch sul polso, iPhone in tasca, e l'app Salute che mostra solo i dati dell'iPhone. L'anello che porto di notte registra fasi del sonno dettagliate, ma Apple Salute non le vede. Il ponte di scrittura Apple Salute di FitMesh nasce da questa esigenza concreta, non da una feature list.",
        en: "I found this personally annoying: Galaxy Watch on the wrist, iPhone in the pocket, and the Health app only showing iPhone data. The ring I wear at night records detailed sleep stages, but Apple Health doesn't see them. FitMesh's Apple Health write bridge was born from this concrete need, not from a feature checklist.",
        es: "Encontré este problema personalmente frustrante: Galaxy Watch en la muñeca, iPhone en el bolsillo y la app Salud mostrando solo los datos del iPhone. El anillo que llevo de noche registra fases del sueño detalladas, pero Apple Salud no las ve. El puente de escritura de Apple Salud de FitMesh nació de esta necesidad concreta, no de una lista de funciones.",
        de: "Ich habe dieses Problem selbst als störend empfunden: Galaxy Watch am Handgelenk, iPhone in der Tasche, und die Health-App zeigt nur die Daten des iPhones. Der Ring, den ich nachts trage, zeichnet detaillierte Schlafphasen auf, aber Apple Health sieht sie nicht. Die Apple Health Schreibbrücke von FitMesh entstand aus diesem konkreten Bedarf, nicht aus einer Feature-Liste.",
        pt: "Eu mesmo achei esse problema irritante: Galaxy Watch no pulso, iPhone no bolso, e o app Saúde mostrando apenas os dados do iPhone. O anel que uso à noite registra fases do sono detalhadas, mas o Apple Saúde não as vê. A ponte de escrita do Apple Saúde do FitMesh nasceu dessa necessidade concreta, não de uma lista de funcionalidades.",
        fr: "J'ai trouvé ce problème personnellement agaçant : Galaxy Watch au poignet, iPhone dans la poche, et l'app Santé qui n'affiche que les données de l'iPhone. La bague que je porte la nuit enregistre des phases de sommeil détaillées, mais Santé Apple ne les voit pas. Le pont d'écriture Santé Apple de FitMesh est né de ce besoin concret, pas d'une liste de fonctionnalités.",
        pl: "Znalazłem ten problem osobisty: Galaxy Watch na nadgarstku, iPhone w kieszeni, a aplikacja Zdrowie pokazuje tylko dane z iPhone. Anelis, który noszę po nocach, rejestruje szczegółowe fazy senu, ale Apple Zdrowie ich nie widzi. Pierwotny bridge Apple Zdrowie dla FitMesh wynika z tej konkretnej potrzeby, a nie z listy funkcji.",
        tr: "Buju bu kişisel olarak bu sorunu rahatsız buldum: Galaxy Watch cebinde, iPhone polşede ve Salute uygulaması sadece iPhone verilerini gösteriyor. Gezmekte olduğum pisolino detaylı uyku fasi kaydediyor, ancak Apple Salute bunları algılamıyor. Apple Salute uygulamasının FitMesh tarafından bu gerçek isteğinden doğduğu, bir özellik listesinden olduğu gibi değil.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Il problema: due ecosistemi che non si parlano",
        en: "The problem: two ecosystems that don't talk to each other",
        es: "El problema: dos ecosistemas que no se comunican",
        de: "Das Problem: zwei Ökosysteme, die nicht miteinander kommunizieren",
        pt: "O problema: dois ecossistemas que não se comunicam",
        fr: "Le problème : deux écosystèmes qui ne communiquent pas",
        pl: "Problematyczna sytuacja: dwa ecosystemy, które nie komunikują się",
        tr: "Problem: i iki ekosistem birbirleriyle konuşmuyor",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Android e iOS usano repository di dati salute separati e non interoperabili: Health Connect su Android, HealthKit su iOS. Un Galaxy Watch accoppiato con un telefono Android scrive i dati in Health Connect, non in Apple Health. Un anello Colmi letto via Bluetooth da FitMesh su Android fa lo stesso. Il risultato: se apri l'app Salute sul tuo iPhone, quei dati non ci sono.",
        en: "Android and iOS use separate, non-interoperable health data repositories: Health Connect on Android, HealthKit on iOS. A Galaxy Watch paired with an Android phone writes data to Health Connect, not Apple Health. A Colmi ring read via Bluetooth by FitMesh on Android does the same. Result: if you open the Health app on your iPhone, that data isn't there.",
        es: "Android e iOS utilizan repositorios de datos de salud separados y no interoperables: Health Connect en Android, HealthKit en iOS. Un Galaxy Watch vinculado a un teléfono Android escribe los datos en Health Connect, no en Apple Salud. Un anillo Colmi leído por Bluetooth con FitMesh en Android hace lo mismo. El resultado: si abres la app Salud en tu iPhone, esos datos no están ahí.",
        de: "Android und iOS verwenden separate, nicht interoperable Gesundheitsdaten-Repositorien: Health Connect auf Android, HealthKit auf iOS. Eine Galaxy Watch, die mit einem Android-Telefon gekoppelt ist, schreibt die Daten in Health Connect, nicht in Apple Health. Ein Colmi-Ring, der von FitMesh auf Android per Bluetooth ausgelesen wird, tut dasselbe. Das Ergebnis: Wenn du die Health-App auf deinem iPhone öffnest, sind diese Daten nicht vorhanden.",
        pt: "Android e iOS usam repositórios de dados de saúde separados e não interoperáveis: Health Connect no Android, HealthKit no iOS. Um Galaxy Watch pareado com um telefone Android grava os dados no Health Connect, não no Apple Saúde. Um anel Colmi lido via Bluetooth pelo FitMesh no Android faz o mesmo. O resultado: se você abrir o app Saúde no seu iPhone, esses dados não estão lá.",
        fr: "Android et iOS utilisent des référentiels de données de santé séparés et non interopérables : Health Connect sur Android, HealthKit sur iOS. Une Galaxy Watch couplée à un téléphone Android écrit les données dans Health Connect, pas dans Santé Apple. Une bague Colmi lue via Bluetooth par FitMesh sur Android fait de même. Résultat : si vous ouvrez l'app Santé sur votre iPhone, ces données ne sont pas là.",
        pl: "Android i iOS korzystają z oddzielnych i niekompatybilnych repozytoriów danych zdrowotnych: Health Connect na Android, HealthKit na iOS. Przypięty do telefonu Android Galaxy Watch zapisuje dane w Health Connect, nie w Apple Health. Podobnie anellito Colmi czytane za pośrednictwem Bluetooth z FitMesh na Android robi to samo. Wynik: jeśli otworzysz aplikację Zdrowie na swoim iPhone, tych danych tam nie ma.",
        tr: "KVKK ve iOS sağlık verileri repository'lerini ayrı ve interoperabel olmayan şekilde kullanıyor: Health Connect KVKK üzerinde, HealthKit iOS üzerinde. Bir Galaxy Watch bir Android telefonuyla eşleştirildiğinde, veriler Health Connect'e yazılır, Apple Health'e değil. Bir Colmi Bluetooth üzerinden FitMesh cihazından okunduğunda aynı işlem yapılır. Sonuç: Eğer iPhone'nin Sağlık uygulamasını açarsanız, o veriler orada yoktur.",
      },
    },
    {
      type: "callout",
      variant: "info",
      title: {
        it: "Perché non esiste una soluzione nativa",
        en: "Why there's no native solution",
        es: "Por qué no existe una solución nativa",
        de: "Warum es keine native Lösung gibt",
        pt: "Por que não existe uma solução nativa",
        fr: "Pourquoi il n'existe pas de solution native",
        pl: "Bożego cudu nie ma/native solution does not exist",
        tr: "Neden bir yerel çözüm mevcut değil",
      },
      body: {
        it: "Apple e Google non hanno costruito un modo diretto per scambiare dati salute tra i due sistemi. FitMesh usa il proprio cloud EU come tramite: legge i dati dal telefono Android e li rende disponibili sull'iPhone. Nessun export manuale, nessuna configurazione complicata.",
        en: "Apple and Google haven't built a direct way to exchange health data between the two systems. FitMesh uses its own EU cloud as a bridge: it reads data from your Android phone and makes it available on iPhone. No manual exports, no complicated setup.",
        es: "Apple y Google no han creado una forma directa de intercambiar datos de salud entre los dos sistemas. FitMesh usa su propia nube EU como intermediario: lee los datos de tu teléfono Android y los pone a disposición en iPhone. Sin exportaciones manuales, sin configuraciones complicadas.",
        de: "Apple und Google haben keine direkte Möglichkeit geschaffen, Gesundheitsdaten zwischen den beiden Systemen auszutauschen. FitMesh nutzt seine eigene EU-Cloud als Brücke: Es liest die Daten vom Android-Telefon und stellt sie auf dem iPhone bereit. Kein manueller Export, keine komplizierte Einrichtung.",
        pt: "Apple e Google não criaram uma maneira direta de trocar dados de saúde entre os dois sistemas. O FitMesh usa sua própria nuvem EU como intermediária: lê os dados do telefone Android e os disponibiliza no iPhone. Sem exportações manuais, sem configuração complicada.",
        fr: "Apple et Google n'ont pas créé de moyen direct d'échanger des données de santé entre les deux systèmes. FitMesh utilise son propre cloud EU comme intermédiaire : il lit les données du téléphone Android et les rend disponibles sur iPhone. Aucune exportation manuelle, aucune configuration compliquée.",
        pl: "Apple i Google nie zbudowali bezpośredniego sposobu wymiany danych zdrowotnych między oboma systemami. FitMesh używa swojego chmury EU jako przekaznika: czyta dane z telefonu Android i je udostępnia na iPhone. Brak ręcznego eksportu, brak skomplikowanej konfiguracji.",
        tr: "Apple ve Google doğrudan veri sağlıkı paylaşma yolu oluşturmadı. FitMesh kendi EU bulutunu kullanıyor: telefon Android den verileri okuyarak, akıllı saat iPhone 'e sunar.manuel export yoktur, karmaşık yapılandırma yoktur.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Come funziona il ponte: passo dopo passo",
        en: "How the bridge works: step by step",
        es: "Cómo funciona el puente: paso a paso",
        de: "So funktioniert die Brücke: Schritt für Schritt",
        pt: "Como funciona a ponte: passo a passo",
        fr: "Comment fonctionne le pont : étape par étape",
        pl: "Jak działa bridge: krok po kroku",
        tr: "Günlük kullanım nasıl gerçekleşir: adım adım",
      },
    },
    {
      type: "list",
      ordered: true,
      items: {
        it: [
          "**Raccolta su Android**: FitMesh Sync legge i dati dal tuo wearable Android (via Health Connect per Galaxy Watch, via Bluetooth per l'anello Colmi) e li carica sul cloud EU.",
          "**Cloud FitMesh EU**: i dati vengono archiviati con timestamp, sorgente, tipo di dato e account utente. Il cloud normalizza i formati tra le diverse sorgenti.",
          "**App iOS attiva**: quando apri FitMesh su iPhone (o l'app è attiva in background), controlla quali dati sono disponibili sul cloud per il tuo account.",
          "**Controllo doppioni**: per ogni dato disponibile, l'app controlla se Apple Salute ha già qualcosa per quella fascia oraria. Se sì, salta. Se no, scrive.",
          "**Scrittura mirata**: scrive su Apple Salute solo i dati mancanti. Se Apple Watch ha già registrato il sonno dalle 23:00 alle 07:00, FitMesh non tocca quelle ore.",
          "**Visibilità immediata**: dopo la scrittura, i dati compaiono nell'app Salute di iPhone come qualsiasi altra voce HealthKit, con la sorgente chiaramente indicata come FitMesh Sync.",
        ],
        en: [
          "**Collection on Android**: FitMesh Sync reads data from your Android wearable (via Health Connect for Galaxy Watch, via Bluetooth for the Colmi ring) and uploads it to EU cloud.",
          "**FitMesh EU cloud**: data is archived with timestamp, source, data type and user account. The cloud normalizes formats across different sources.",
          "**iOS app active**: when you open FitMesh on iPhone (or the app is active in background), it checks what data is available in the cloud for your account.",
          "**Duplicate check**: for each available piece of data, the app checks whether Apple Health already has something for that time slot. If yes, it skips. If no, it writes.",
          "**Targeted writing**: writes to Apple Health only the missing data. If Apple Watch has already recorded sleep from 11pm to 7am, FitMesh doesn't touch those hours.",
          "**Immediate visibility**: after writing, data appears in the iPhone Health app like any other HealthKit entry, with the source clearly shown as FitMesh Sync.",
        ],
        es: [
          "**Recopilación en Android**: FitMesh Sync lee los datos de tu wearable Android (vía Health Connect para Galaxy Watch, vía Bluetooth para el anillo Colmi) y los sube a la nube EU.",
          "**Nube FitMesh EU**: los datos se archivan con marca de tiempo, fuente, tipo de dato y cuenta de usuario. La nube normaliza los formatos entre las distintas fuentes.",
          "**App iOS activa**: cuando abres FitMesh en iPhone (o la app está activa en segundo plano), comprueba qué datos están disponibles en la nube para tu cuenta.",
          "**Verificación de duplicados**: por cada dato disponible, la app comprueba si Apple Salud ya tiene algo para esa franja horaria. Si es así, lo omite. Si no, lo escribe.",
          "**Escritura selectiva**: escribe en Apple Salud solo los datos que faltan. Si Apple Watch ya registró el sueño de las 23:00 a las 07:00, FitMesh no toca esas horas.",
          "**Visibilidad inmediata**: tras la escritura, los datos aparecen en la app Salud del iPhone como cualquier otra entrada de HealthKit, con la fuente claramente indicada como FitMesh Sync.",
        ],
        de: [
          "**Erfassung auf Android**: FitMesh Sync liest die Daten von deinem Android-Wearable (über Health Connect für Galaxy Watch, über Bluetooth für den Colmi-Ring) und lädt sie in die EU-Cloud hoch.",
          "**FitMesh EU-Cloud**: Die Daten werden mit Zeitstempel, Quelle, Datentyp und Nutzerkonto archiviert. Die Cloud normalisiert die Formate aus verschiedenen Quellen.",
          "**iOS-App aktiv**: Wenn du FitMesh auf dem iPhone öffnest (oder die App im Hintergrund aktiv ist), prüft sie, welche Daten in der Cloud für dein Konto verfügbar sind.",
          "**Duplikatsprüfung**: Für jeden verfügbaren Datensatz prüft die App, ob Apple Health für diesen Zeitraum bereits etwas eingetragen hat. Wenn ja, wird er übersprungen. Wenn nein, wird er geschrieben.",
          "**Gezieltes Schreiben**: Schreibt in Apple Health nur die fehlenden Daten. Wenn die Apple Watch den Schlaf bereits von 23:00 bis 07:00 Uhr aufgezeichnet hat, berührt FitMesh diese Stunden nicht.",
          "**Sofortige Sichtbarkeit**: Nach dem Schreiben erscheinen die Daten in der iPhone Health-App wie jeder andere HealthKit-Eintrag, mit der Quelle klar als FitMesh Sync angegeben.",
        ],
        pt: [
          "**Coleta no Android**: FitMesh Sync lê os dados do seu wearable Android (via Health Connect para Galaxy Watch, via Bluetooth para o anel Colmi) e os envia para a nuvem EU.",
          "**Nuvem FitMesh EU**: os dados são arquivados com data e hora, fonte, tipo de dado e conta do usuário. A nuvem normaliza os formatos entre as diferentes fontes.",
          "**App iOS ativo**: quando você abre o FitMesh no iPhone (ou o app está ativo em segundo plano), ele verifica quais dados estão disponíveis na nuvem para a sua conta.",
          "**Verificação de duplicatas**: para cada dado disponível, o app verifica se o Apple Saúde já tem algo para aquele intervalo de tempo. Se sim, pula. Se não, grava.",
          "**Gravação direcionada**: grava no Apple Saúde apenas os dados que faltam. Se o Apple Watch já registrou o sono das 23h às 7h, o FitMesh não toca nessas horas.",
          "**Visibilidade imediata**: após a gravação, os dados aparecem no app Saúde do iPhone como qualquer outra entrada do HealthKit, com a fonte claramente indicada como FitMesh Sync.",
        ],
        fr: [
          "**Collecte sur Android**: FitMesh Sync lit les données de votre appareil connecté Android (via Health Connect pour Galaxy Watch, via Bluetooth pour la bague Colmi) et les envoie vers le cloud EU.",
          "**Cloud FitMesh EU**: les données sont archivées avec horodatage, source, type de données et compte utilisateur. Le cloud normalise les formats entre les différentes sources.",
          "**App iOS active**: lorsque vous ouvrez FitMesh sur iPhone (ou que l'app est active en arrière-plan), elle vérifie quelles données sont disponibles dans le cloud pour votre compte.",
          "**Vérification des doublons**: pour chaque donnée disponible, l'app vérifie si Santé Apple possède déjà quelque chose pour ce créneau horaire. Si oui, elle l'ignore. Si non, elle l'écrit.",
          "**Écriture ciblée**: écrit dans Santé Apple uniquement les données manquantes. Si l'Apple Watch a déjà enregistré le sommeil de 23h à 7h, FitMesh ne touche pas ces heures.",
          "**Visibilité immédiate**: après l'écriture, les données apparaissent dans l'app Santé de l'iPhone comme n'importe quelle autre entrée HealthKit, avec la source clairement indiquée comme FitMesh Sync.",
        ],
        pl: [
          "**Zbior na Android**: FitMesh Sync odczytuje dane z Twojego wearable Android (przez Health Connect dla Galaxy Watch, przez Bluetooth dla pęstenka Colmi) i przesyła je do chmury EU.",
          "**Wolontariat FitMesh EU**: dane są zapisywane ze znacznikami czasowymi, źródłami, typami danych oraz kontami użytkowników. Usługa cloud normalizuje formaty między różnymi źródłami.",
          "**Aplikacja iOS aktywna**: gdy otwierasz FitMesh na iPhone (lub aplikacja jest aktywna w tle), sprawdź, które dane są dostępne w chmurze dla Twoego konta.",
          "**Sprawdzenie duplikatów**: dla każdego dostępnych danych, aplikacja sprawdza, czy Apple Salute ma już coś dla tej godziny. Jeśli tak, pominie to. Jeśli nie, zapisze.",
          "**Zakładka do celu**: pisz na Apple Salute tylko brakujące dane. Jeśli Apple Watch zarejestrowała sen od 23:00 do 07:00, FitMesh nie dotyka tych godzin.",
          "**Nieruchoma widoczność**: po zapisaniu, dane pojawiają się w aplikacji Zdrowie z iPhone jako dowolna inna pozycja HealthKit, z źródłem jasno zaznaczonym jako FitMesh Sync.",
        ],
        tr: [
          "**Günlük Android Toplulaştırma**: FitMesh Sync giyilebilir cihaz Androidinizden verileri okuyar (Health Connect aracılığıyla Galaxy Watch için, Bluetooth aracılığıyla pisolino Colmi için) ve bunları AB'nin bulutuna yükler.",
          "**Could FitMesh EU**: veriler zaman damgası, kaynak, veri türü ve kullanıcı hesabıyla depolanır. Bulut farklı kaynaklar arasında veri biçimlerini normalleştirir.",
          "**Uygulama iOS etkin**: FitMesh'i cihazınızda açtığınızda (veya uygulama arka planda aktif) veya iPhone üzerinde FitMesh'u açtığınızda, hangi veriler cloud'da hesabınıza ait olduğunu kontrol et.",
          "**Çift kayıtlar kontrolü**: her veri için uygulama, Apple Sağlık için o saat aralığı için zaten bir kaydın olup olmadığını kontrol eder. Var ise atlar. Yoksa ekler.",
          "**Hedefleme yazım**: sadece eksik verileri Apple Sağlık'a yazıyor. Eğer Apple Çocuk 23:00 ile 07:00 arasında uyku kaydettiği takdirde, FitMesh o saatlerı değiştirmez.",
          "**Hemen Görüntülme**: yazıldıktan sonra, veriler iPhone Sağlık uygulamasında diğer herhangi bir öğenin gibi görüntülenir ve kaynak, açıkça FitMesh Sync olarak gösterilir.",
        ],
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Zero doppioni: come funziona",
        en: "No duplicates: how it works",
        es: "Cero duplicados: cómo funciona",
        de: "Keine Duplikate: so funktioniert es",
        pt: "Zero duplicatas: como funciona",
        fr: "Zéro doublon : comment ça fonctionne",
        pl: "Bez powtórzeń: jak to działa",
        tr: "Sıfır Duplonyu: Nasıl Çalışır",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Prima di scrivere qualsiasi dato, FitMesh controlla se Apple Salute ha già qualcosa per quella fascia oraria. Se sì, passa oltre. Se no, scrive. In pratica: non ci sono mai due voci per la stessa ora.",
        en: "Before writing any data, FitMesh checks whether Apple Health already has something for that time slot. If yes, it moves on. If no, it writes. In practice: there are never two entries for the same hour.",
        es: "Antes de escribir cualquier dato, FitMesh comprueba si Apple Salud ya tiene algo para esa franja horaria. Si es así, continúa. Si no, escribe. En la práctica: nunca hay dos entradas para la misma hora.",
        de: "Bevor ein Datensatz geschrieben wird, prüft FitMesh, ob Apple Health für diesen Zeitraum bereits etwas enthält. Wenn ja, geht es weiter. Wenn nein, wird geschrieben. In der Praxis: Es gibt nie zwei Einträge für dieselbe Stunde.",
        pt: "Antes de gravar qualquer dado, o FitMesh verifica se o Apple Saúde já tem algo para aquele intervalo de tempo. Se sim, passa adiante. Se não, grava. Na prática: nunca há duas entradas para o mesmo horário.",
        fr: "Avant d'écrire une quelconque donnée, FitMesh vérifie si Santé Apple possède déjà quelque chose pour ce créneau horaire. Si oui, il passe à la suite. Si non, il écrit. En pratique : il n'y a jamais deux entrées pour la même heure.",
        pl: "Przed wpisaniem jakiejkolwiek informacji, FitMesh sprawdza, czy Apple Zdrowie posiada już coś dla tej godziny. Jeśli tak, przeskok. Jeśli nie, wpisz. W praktyce: nigdy nie ma dwóch wpisów na tę samą godzinę.",
        tr: "Önce herhangi bir veri yazmadan, FitMesh Apple Sağlık o zaman diliminde zaten bir şey var mı kontrol etmelidir. Var ise geçin. Yoksa yazın. Özetle: Aynı zamanda iki kere hiçbir veri yazılmaz.",
      },
    },
    {
      type: "callout",
      variant: "info",
      title: {
        it: "Esempi pratici",
        en: "Practical examples",
        es: "Ejemplos prácticos",
        de: "Praktische Beispiele",
        pt: "Exemplos práticos",
        fr: "Exemples pratiques",
        pl: "Praktyczne przykłady",
        tr: "Örnekler",
      },
      body: {
        it: "Hai dormito con l'anello Colmi ma non hai indossato Apple Watch? FitMesh scrive le fasi del sonno in Apple Salute. Hai sia Apple Watch che l'anello, e il Watch ha già registrato la notte? FitMesh non tocca nulla. Hai solo l'anello? FitMesh scrive, e se riapri l'app più tardi non duplica.",
        en: "Wore the Colmi ring but not Apple Watch during sleep? FitMesh writes sleep stages into Apple Health. Have both Apple Watch and the ring, and the Watch already recorded the night? FitMesh doesn't touch anything. Ring only? FitMesh writes, and if you reopen the app later it doesn't duplicate.",
        es: "¿Dormiste con el anillo Colmi pero sin Apple Watch? FitMesh escribe las fases del sueño en Apple Salud. ¿Tienes tanto Apple Watch como el anillo, y el Watch ya registró la noche? FitMesh no toca nada. ¿Solo el anillo? FitMesh escribe, y si vuelves a abrir la app más tarde no duplica.",
        de: "Hast du mit dem Colmi-Ring geschlafen, aber die Apple Watch nicht getragen? FitMesh schreibt die Schlafphasen in Apple Health. Hast du sowohl Apple Watch als auch den Ring, und die Watch hat die Nacht bereits aufgezeichnet? FitMesh berührt nichts. Nur der Ring? FitMesh schreibt, und wenn du die App später erneut öffnest, wird nicht dupliziert.",
        pt: "Dormiu com o anel Colmi mas sem o Apple Watch? O FitMesh grava as fases do sono no Apple Saúde. Tem tanto o Apple Watch quanto o anel, e o Watch já registrou a noite? O FitMesh não toca em nada. Apenas o anel? O FitMesh grava, e se você reabrir o app mais tarde, não duplica.",
        fr: "Vous avez dormi avec la bague Colmi mais sans l'Apple Watch ? FitMesh écrit les phases de sommeil dans Santé Apple. Vous avez à la fois l'Apple Watch et la bague, et la Watch a déjà enregistré la nuit ? FitMesh ne touche à rien. Bague uniquement ? FitMesh écrit, et si vous rouvrez l'app plus tard, il ne duplique pas.",
        pl: "SpŨłeś z anelkiem Colmi ale nie nosiłeś Apple Watch? FitMesh zapisuje fazy snu w Apple Salute. Masz zarówno Apple Watch, jak i anellko, a Watch już zarejestrował noc? FitMesh nic nie zmienia. Masz tylko anelk? FitMesh zapisuje, a jeśli ponownie otwiesz aplikację później, to nie powtarza.",
        tr: "Uyudun Colmi ile ama Apple Watch'i giymedi mi? FitMesh Uyku aşamalarını Apple Sağlık'te kaydeder. Apple Watch ve de Colmi, ve Watch'u zaten geceyi kaydetmişse? FitMesh hiçbir şey yapmaz. Sadece Colmi var mı? FitMesh kaydeder, daha sonra uygulamayı açtığında da çakışmaz.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Sonno con fasi: il punto di forza dell'anello",
        en: "Sleep with stages: the ring's strong point",
        es: "Sueño con fases: el punto fuerte del anillo",
        de: "Schlaf mit Phasen: die Stärke des Rings",
        pt: "Sono com fases: o ponto forte do anel",
        fr: "Sommeil avec phases : le point fort de la bague",
        pl: "Snytanie z_awakacji: siła wyrazu aneglu",
        tr: "Uyum fazları ile uyku: anlamanın güçlü noktası",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Gli anelli smart come il Colmi R02/R03 sono pensati per la notte: misurano sonno, SpO₂, frequenza cardiaca e variabilità mentre dormi, senza il peso di un orologio al polso. Le fasi registrate dall'anello (sonno profondo, leggero, REM, veglia) compaiono in Apple Salute nel grafico Sonno, esattamente come se li avesse registrati Apple Watch.",
        en: "Smart rings like the Colmi R02/R03 are built for nighttime: they measure sleep, SpO₂, heart rate and variability while you sleep, without the bulk of a watch on your wrist. The stages recorded by the ring (deep, light, REM, awake) show up in Apple Health in the Sleep chart, just as if Apple Watch had recorded them.",
        es: "Los anillos inteligentes como el Colmi R02/R03 están diseñados para la noche: miden el sueño, SpO₂, frecuencia cardíaca y variabilidad mientras duermes, sin el volumen de un reloj en la muñeca. Las fases registradas por el anillo (sueño profundo, ligero, REM, vigilia) aparecen en Apple Salud en el gráfico de Sueño, exactamente igual que si las hubiera registrado Apple Watch.",
        de: "Smart-Ringe wie der Colmi R02/R03 sind für die Nacht konzipiert: Sie messen Schlaf, SpO₂, Herzfrequenz und Herzfrequenzvariabilität während du schläfst, ohne das Gewicht einer Uhr am Handgelenk. Die vom Ring aufgezeichneten Phasen (Tiefschlaf, Leichtschlaf, REM, Wach) erscheinen in Apple Health im Schlaf-Diagramm, genau so als hätte die Apple Watch sie aufgezeichnet.",
        pt: "Anéis inteligentes como o Colmi R02/R03 são projetados para a noite: medem sono, SpO₂, frequência cardíaca e variabilidade enquanto você dorme, sem o peso de um relógio no pulso. As fases registradas pelo anel (sono profundo, leve, REM, acordado) aparecem no Apple Saúde no gráfico de Sono, exatamente como se o Apple Watch as tivesse registrado.",
        fr: "Les bagues connectées comme la Colmi R02/R03 sont conçues pour la nuit : elles mesurent le sommeil, la SpO₂, la fréquence cardiaque et la variabilité pendant que vous dormez, sans le poids d'une montre au poignet. Les phases enregistrées par la bague (sommeil profond, léger, REM, éveil) apparaissent dans Santé Apple dans le graphique Sommeil, exactement comme si l'Apple Watch les avait enregistrées.",
        pl: "Ankiety smart takie jak Colmi R02/R03 są zaprojektowane na noc: pomiar sonu, SpO₂, frekwencji serca i variabilitości podczas senu, bez ciężaru zegarka na nadgarstku. Fazy zarejestrowane przez ankiety (głęboki sen, lekki sen, REM, błądzenie się) pojawiają się w Apple Salute w wykresie Sonu dokładnie tak, jakby były to zegarki Apple Watch.",
        tr: "Colmi R02/R03 gibi akıllı yüzükler gece için tasarlanmıştır: bilek üzerinde bir saatin ağırlığı olmadan uyurken uyku, SpO₂, kalp atış hızı ve değişkenliği ölçerler. Yüzük tarafından kaydedilen fazlar (derin uyku, hafif uyku, REM, uyanık) Apple Sağlık'ta Uyku grafiğinde tam olarak Apple Watch kaydetmiş gibi görünür.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Privacy: dove vanno i dati e chi li vede",
        en: "Privacy: where data goes and who sees it",
        es: "Privacidad: adónde van los datos y quién los ve",
        de: "Datenschutz: Wohin gehen die Daten und wer sieht sie",
        pt: "Privacidade: para onde vão os dados e quem os vê",
        fr: "Confidentialité : où vont les données et qui les voit",
        pl: "prywatność: gdzie idą dane i kogo ich można zobaczyć",
        tr: "Gizlilik: veriler nereye gider ve kimler onları görür",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "I dati percorrono solo due passi: dall'app FitMesh su Android al cloud FitMesh (datacenter EU, cifrati), poi dall'app FitMesh su iPhone dentro Apple Salute sul tuo device. FitMesh non vende dati a terzi, non li usa per addestrare modelli, non li condivide con inserzionisti. Il cloud EU garantisce conformità GDPR.",
        en: "Data takes just two steps: from the FitMesh app on Android to the FitMesh cloud (EU datacenter, encrypted), then from the FitMesh app on iPhone into Apple Health on your device. FitMesh doesn't sell data to third parties, doesn't use it to train models, doesn't share it with advertisers. The EU cloud guarantees GDPR compliance.",
        es: "Los datos recorren solo dos pasos: desde la app FitMesh en Android hasta la nube FitMesh (centro de datos EU, cifrados) y luego desde la app FitMesh en iPhone hasta Apple Salud en tu dispositivo. FitMesh no vende datos a terceros, no los usa para entrenar modelos ni los comparte con anunciantes. La nube EU garantiza el cumplimiento del GDPR.",
        de: "Die Daten durchlaufen nur zwei Schritte: von der FitMesh-App auf Android in die FitMesh-Cloud (EU-Rechenzentrum, verschlüsselt), dann von der FitMesh-App auf iPhone in Apple Health auf deinem Gerät. FitMesh verkauft keine Daten an Dritte, verwendet sie nicht zum Trainieren von Modellen und teilt sie nicht mit Werbetreibenden. Die EU-Cloud garantiert DSGVO-Konformität.",
        pt: "Os dados percorrem apenas dois passos: do app FitMesh no Android para a nuvem FitMesh (datacenter EU, criptografados), depois do app FitMesh no iPhone para o Apple Saúde no seu dispositivo. O FitMesh não vende dados a terceiros, não os usa para treinar modelos, não os compartilha com anunciantes. A nuvem EU garante conformidade com o RGPD.",
        fr: "Les données ne font que deux étapes : de l'app FitMesh sur Android vers le cloud FitMesh (datacenter EU, chiffré), puis de l'app FitMesh sur iPhone vers Santé Apple sur votre appareil. FitMesh ne vend pas les données à des tiers, ne les utilise pas pour entraîner des modèles, ne les partage pas avec des annonceurs. Le cloud EU garantit la conformité au RGPD.",
        pl: "Dane przenoszą się tylko przez dwa kroki: z aplikacji FitMesh na Android do chmury FitMesh (centrum danych EU, zaszyfrowane), a następnie z powrotem do aplikacji FitMesh na iPhone w Apple Salute na Twoim urządzeniu. FitMesh nie sprzedaje danych trzecim stronom, nie korzysta z nich do szkolenia modeli, a także ich nie udostępnia reklamodawcom. Chmura EU gwarantuje zgodność GDPR.",
        tr: "Veriler sadece iki adımlar yoluyla ilerler: FitMesh uygulamasından Android'e ağıb, KVKK uyumluluğu garanti eden AB'deki veri merkezine (veriler şifrelenmiştir), sonra da cihazınızdaki Apple Sağlık içindeki FitMesh uygulamasına. FitMesh verileri üçüncü taraflarla satmaz, modellerin eğitilmesinde kullanmaz ve reklamciyla paylaşılmaz.",
      },
    },
    {
      type: "callout",
      variant: "tip",
      title: {
        it: "Controllo granulare dei permessi",
        en: "Granular permission control",
        es: "Control granular de permisos",
        de: "Granulare Berechtigungssteuerung",
        pt: "Controle granular de permissões",
        fr: "Contrôle granulaire des autorisations",
        pl: "Rozgraniczone kontrolowanie uprawnień",
        tr: "Kontrol kapsamlı izinlerinizle",
      },
      body: {
        it: "Apple HealthKit richiede permessi espliciti per ogni tipo di dato: FitMesh chiede solo i permessi necessari per le sorgenti che hai configurato. Puoi vedere e revocare i permessi in qualsiasi momento da iPhone → Impostazioni → Privacy e sicurezza → Salute → FitMesh Sync.",
        en: "Apple HealthKit requires explicit permissions for each data type: FitMesh requests only the permissions needed for the sources you've configured. You can view and revoke permissions at any time from iPhone → Settings → Privacy & Security → Health → FitMesh Sync.",
        es: "Apple HealthKit requiere permisos explícitos para cada tipo de dato: FitMesh solicita solo los permisos necesarios para las fuentes que has configurado. Puedes ver y revocar los permisos en cualquier momento desde iPhone → Ajustes → Privacidad y seguridad → Salud → FitMesh Sync.",
        de: "Apple HealthKit erfordert explizite Berechtigungen für jeden Datentyp: FitMesh fordert nur die Berechtigungen an, die für die von dir konfigurierten Quellen benötigt werden. Du kannst Berechtigungen jederzeit anzeigen und widerrufen unter iPhone → Einstellungen → Datenschutz & Sicherheit → Health → FitMesh Sync.",
        pt: "O Apple HealthKit exige permissões explícitas para cada tipo de dado: o FitMesh solicita apenas as permissões necessárias para as fontes que você configurou. Você pode ver e revogar as permissões a qualquer momento em iPhone → Ajustes → Privacidade e segurança → Saúde → FitMesh Sync.",
        fr: "Apple HealthKit exige des autorisations explicites pour chaque type de données : FitMesh ne demande que les autorisations nécessaires pour les sources que vous avez configurées. Vous pouvez consulter et révoquer les autorisations à tout moment depuis iPhone → Réglages → Confidentialité et sécurité → Santé → FitMesh Sync.",
        pl: "Apple HealthKit wymaga wyraźnych zezwoleń dla każdego typu danych: FitMesh pyta tylko o zezwolenia niezbędne dla źródeł, które skonfigurowałeś. Możesz zobaczyć i odzyskać te zezwolenia w każdym momencie na iPhone → Ustawienia → Prywatność i bezpieczeństwo → Zdrowie → FitMesh Sync.",
        tr: "Apple HealthKit gere açık şekilde her veri türü için izinler: FitMesh sadece yapılandırılan kaynaklara gerekli olan izinleri isteyebilir. Her zaman iPhone → Ayarlar → Güvenlik ve Gizlilik → Sağlık → FitMesh Sync üzerinden izinlerini görebilip revocabilirsiniz.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Come attivare il ponte",
        en: "How to activate the bridge",
        es: "Cómo activar el puente",
        de: "So aktivierst du die Brücke",
        pt: "Como ativar a ponte",
        fr: "Comment activer le pont",
        pl: "Jak włączyć pułapkę",
        tr: "Ponte aktive etmek_rules: __FM_PH_0__ KVKK __FM_URL_0__ ile __FM_HTML_0__ __FM_LINK_0__ __FM_CODE_0__ __FM_FENCE_0__ __FM_BRAND_0__ __FM_TERM_0__ rules:\n- __FM_PH_0__ döndüren sadece çeviri, açıklamalar olmadan geri gönder.\n- Her token'i tam olarak koruyun: __FM_PH_0__, __FM_URL_0__, __FM_HTML_0__, __FM_LINK_0__, __FM_CODE_0__, __FM_FENCE_0__, __FM_BRAND_0__, __FM_TERM_0__.\n- Satır atlama ve Markdown yapısı koru.\n- HTML etiketlerinin yerine koymasına izin ver, etiketler arasında boşluk eklemeyin.\n- Ürün isimlerini temsil eden token'ları çevirme.\n- Tıbbi iddia veya tanımlar ekleme.\n- Hedef dilde teknik olarak doğru ve profesyonel bir dille çevrilecek, makine çevirisiyle değil.\n- Arama niyetini, entitelerin isimlerini ve ticari ilgi verilerini koru SEO/GEO için.\n- Uygulama arayüz metinleri kısa ve doğal olmalı; belgeleme/ikamet kopyası ise yetki sahibi ve net olmalı.\n- İdileri hedef dilde yerelize edin, ürün konumunu, dönüştürme niyetini koruyun ve dönüşüm niyetini koruyun.\n- Anahtar kelime dolgusu veya doğal olmayan ifadeler eklemeyin.\n- Kaynak İtalyanca ise, \"Hai\" UI kopyasında genellikle \"You have\" anlamına geldiğini unutma.\n- Hedef dilde tercih edilen bu terimleri kullan: \"GDPR\" -> \"KVKK\"; \"wearable\" -> \"giyilebilir cihaz\"; \"smartwatch\" -> \"akıllı saat\"; \"founder\" -> \"kurucu\"; \"pisolino\" -> \"kestirme\"; \"pisolini\" -> \"kestirmeler\".\nPonte nasıl aktive edilir\n rules: __FM_PH_0__ KVKK __FM_URL_0__ ile __FM_HTML_0__ __FM_LINK_0__ __FM_CODE_0__ __FM_FENCE_0__ __FM_BRAND_0__ __FM_TERM_0__ kuralları:\n- __FM_PH_0__ sadece çeviri döndürülür, açıklamalar olmadan.\n- Her token tam olarak korunur: __FM_PH_0__, __FM_URL_0__, __FM_HTML_0__, __FM_LINK_0__, __FM_CODE_0__, __FM_FENCE_0__, __FM_BRAND_0__, __FM_TERM_0__.\n- Satır atlama ve Markdown yapısı korunur.\n- HTML etiketleri yerine koyma izin verilir, etiketler arasında boşluk eklenmemelidir.\n- Ürün isimlerini temsil eden token'lar çevrilmez.\n- Tıbbi iddia veya tanımlar eklenmez.\n- Hedef dilde teknik olarak doğru ve profesyonel bir dille çevrilecek, makine çevirisiyle değil.\n- Arama niyetini, entitelerin isimlerini ve ticari ilgi verilerini koru SEO/GEO için.\n- Uygulama arayüz metinleri kısa ve doğal olmalı; belgeleme/ikamet kopyası ise yetki sahibi ve net olmalı.\n- İdileri hedef dilde yerelize edilir, ürün konumunu, dönüştürme niyetini koruyun ve dönüşüm niyetini koruyun.\n- Anahtar kelime dolgusu veya doğal olmayan ifadeler eklenmemelidir.\n- Kaynak İtalyanca ise, \"Hai\" UI kopyasında genellikle \"You have\" anlamına geldiğini unutulmalıdır.\n- Hedef dilde tercih edilen bu terimler kullanılır: \"GDPR\" -> \"KVKK\"; \"wearable\" -> \"giyilebilir cihaz\"; \"smartwatch\" -> \"akıllı saat\"; \"founder\" -> \"kurucu\"; \"pisolino\" -> \"kestirme\"; \"pisolini\" -> \"kestirmeler\".\nPonte nasıl aktive edilir\n KVKK __FM_URL_0__ ile __FM_HTML_0__ __FM_LINK_0__ __FM_CODE_0__ __FM_FENCE_0__ __FM_BRAND_0__ __FM_TERM_0__ rules:\n- __FM_PH_0__ döndüren sadece çeviri, açıklamalar olmadan geri gönder.\n- Her token'i tam olarak koruyun: __FM_PH_0__, __FM_URL_0__, __FM_HTML_0__, __FM_LINK_0__, __FM_CODE_0__, __FM_FENCE_0__, __FM_BRAND_0__, __FM_TERM_0__.\n- Satır atlama ve Markdown yapısı koru.\n- HTML etiketlerinin yerine koymasına izin ver, etiketler arasında boşluk eklemeyin.\n- Ürün isimlerini temsil eden token'ları çevirme.\n- Tıbbi iddia veya tanımlar ekleme.\n- Hedef dilde teknik olarak doğru ve profesyonel bir dille çevrilecek, makine çevirisiyle değil.\n- Arama niyetini, entitelerin isimlerini ve ticari ilgi verilerini koru SEO/GEO için.\n- Uygulama arayüz metinleri kısa ve doğal olmalı; belgeleme/ikamet kopyası ise yetki sahibi ve net olmalı.\n- İdileri hedef dilde yerelize edin, ürün konumunu, dönüştürme niyetini koruyun ve dönüşüm niyetini koruyun.\n- Anahtar kelime dolgusu veya doğal olmayan ifadeler eklemeyin.\n- Kaynak İtalyanca ise, \"Hai\" UI kopyasında genellikle \"You have\" anlamına geldiğini unutma.\n- Hedef dilde tercih edilen bu terimleri kullan: \"GDPR\" -> \"KVKK\"; \"wearable\" -> \"giyilebilir cihaz\"; \"smartwatch\" -> \"akıllı saat\"; \"founder\" -> \"kurucu\"; \"pisolino\" -> \"kestirme\"; \"pisolini\" -> \"kestirmeler\".\nPonte nasıl aktive edilir?",
      },
    },
    {
      type: "list",
      ordered: true,
      items: {
        it: [
          "Installa FitMesh Sync su iPhone (beta TestFlight ora, App Store imminente).",
          "Accedi con lo stesso account che usi su Android.",
          "Vai in **Impostazioni → Apple Salute → Ponte di scrittura**.",
          "Attiva il toggle e concedi i permessi HealthKit richiesti.",
          "Scegli quali tipi di dato vuoi che il ponte scriva (sonno, passi, frequenza cardiaca, ecc.).",
          "FitMesh sincronizza i dati disponibili e li scrive in Apple Salute nei minuti successivi.",
        ],
        en: [
          "Install FitMesh Sync on iPhone (TestFlight beta now, App Store coming soon).",
          "Sign in with the same account you use on Android.",
          "Go to **Settings → Apple Health → Write Bridge**.",
          "Toggle it on and grant the requested HealthKit permissions.",
          "Choose which data types you want the bridge to write (sleep, steps, heart rate, etc.).",
          "FitMesh syncs available data and writes it to Apple Health within minutes.",
        ],
        es: [
          "Instala FitMesh Sync en iPhone (beta TestFlight ahora, App Store próximamente).",
          "Inicia sesión con la misma cuenta que usas en Android.",
          "Ve a **Ajustes → Apple Salud → Puente de escritura**.",
          "Activa el interruptor y concede los permisos de HealthKit solicitados.",
          "Elige qué tipos de datos quieres que el puente escriba (sueño, pasos, frecuencia cardíaca, etc.).",
          "FitMesh sincroniza los datos disponibles y los escribe en Apple Salud en los minutos siguientes.",
        ],
        de: [
          "Installiere FitMesh Sync auf dem iPhone (jetzt TestFlight-Beta, App Store bald verfügbar).",
          "Melde dich mit demselben Konto an, das du auf Android verwendest.",
          "Gehe zu **Einstellungen → Apple Health → Schreibbrücke**.",
          "Aktiviere den Schalter und erteile die angeforderten HealthKit-Berechtigungen.",
          "Wähle aus, welche Datentypen die Brücke schreiben soll (Schlaf, Schritte, Herzfrequenz usw.).",
          "FitMesh synchronisiert die verfügbaren Daten und schreibt sie innerhalb weniger Minuten in Apple Health.",
        ],
        pt: [
          "Instale o FitMesh Sync no iPhone (beta TestFlight agora, App Store em breve).",
          "Entre com a mesma conta que você usa no Android.",
          "Vá em **Configurações → Apple Saúde → Ponte de escrita**.",
          "Ative o interruptor e conceda as permissões do HealthKit solicitadas.",
          "Escolha quais tipos de dados você quer que a ponte grave (sono, passos, frequência cardíaca, etc.).",
          "O FitMesh sincroniza os dados disponíveis e os grava no Apple Saúde nos minutos seguintes.",
        ],
        fr: [
          "Installez FitMesh Sync sur iPhone (bêta TestFlight maintenant, App Store bientôt disponible).",
          "Connectez-vous avec le même compte que vous utilisez sur Android.",
          "Allez dans **Paramètres → Santé Apple → Pont d'écriture**.",
          "Activez le bouton et accordez les autorisations HealthKit demandées.",
          "Choisissez les types de données que vous souhaitez que le pont écrive (sommeil, pas, fréquence cardiaque, etc.).",
          "FitMesh synchronise les données disponibles et les écrit dans Santé Apple en quelques minutes.",
        ],
        pl: [
          "Zainstaluj FitMesh Sync na iPhone (beta TestFlight teraz, App Store niedługo).",
          "Zaloguj się za pomocą tego samego konta, które używasz na Android.",
          "Idz do **Ustawień → Zdrowie Apple → Most pisowni**.",
          "Aktywuj przycisk i udziel uprawnień wymaganych przez HealthKit.",
          "Wybierz, które typy danych chcesz, aby most pisał (spoczynek, kroki, częstotliwość serca, itp.).",
          "FitMesh synchronizuje dostępne dane i zapisuje je w Apple Salucie w minutach po ich uzyskaniu.",
        ],
        tr: [
          "Kurun FitMesh Sync uygulamasını (iPhone beta (TestFlight şu an, App Store yakında)).",
          "Giriş yapın aynı hesabınızla ki Android 'a.",
          "Gidin **Ayarlar → Apple Sağlık → Yazım Köprüsü**.",
          "Etkileşimli öğeyi aç ve gerekli HealthKit izinleri ver.",
          "Seçilecek hangi tür veriyi köprü tarafından yazdıracağını (uyku, adımlar, kalp atış hızı vs.) belirleyin.",
          "FitMesh mevcut verileri senkronize eder ve birkaç dakika içinde Apple Sağlık'a yazar.",
        ],
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "In sintesi",
        en: "In summary",
        es: "En resumen",
        de: "Zusammenfassung",
        pt: "Em resumo",
        fr: "En résumé",
        pl: "W syntezie",
        tr: "Özetle",
      },
    },
    {
      type: "list",
      items: {
        it: [
          "Il ponte di scrittura Apple Salute porta i dati dei device Android (smartwatch, anelli smart) dentro HealthKit su iPhone via cloud FitMesh EU.",
          "Controlla prima se Apple Salute ha già quei dati. Scrive solo dove manca qualcosa. Niente doppioni.",
          "Sonno con fasi complete (profondo, leggero, REM): le fasi dell'anello appaiono in Apple Salute nello stesso formato di Apple Watch.",
          "Opt-in, granulare, revocabile: si attiva dalle impostazioni FitMesh iOS e si disattiva in qualsiasi momento. I permessi HealthKit sono gestiti da iPhone Impostazioni.",
          "Privacy EU/GDPR: cloud in datacenter EU, cifrato, nessuna vendita o condivisione di dati con terzi.",
        ],
        en: [
          "The Apple Health write bridge brings Android device data (smartwatches, smart rings) into HealthKit on iPhone via FitMesh EU cloud.",
          "Checks first whether Apple Health already has that data. Writes only where something is missing. No duplicates.",
          "Sleep with full stages (deep, light, REM): ring stages appear in Apple Health in the same format as Apple Watch.",
          "Opt-in, granular, revocable: activated from FitMesh iOS settings and turned off at any time. HealthKit permissions are managed from iPhone Settings.",
          "EU/GDPR privacy: EU datacenter cloud, encrypted, no data sales or third-party sharing.",
        ],
        es: [
          "El puente de escritura de Apple Salud lleva los datos de dispositivos Android (smartwatches, anillos inteligentes) a HealthKit en iPhone a través de la nube FitMesh EU.",
          "Comprueba primero si Apple Salud ya tiene esos datos. Escribe solo donde falta algo. Sin duplicados.",
          "Sueño con fases completas (profundo, ligero, REM): las fases del anillo aparecen en Apple Salud en el mismo formato que Apple Watch.",
          "Opt-in, granular, revocable: se activa desde los ajustes de FitMesh iOS y se desactiva en cualquier momento. Los permisos de HealthKit se gestionan desde Ajustes de iPhone.",
          "Privacidad EU/GDPR: nube en centro de datos EU, cifrada, sin venta ni cesión de datos a terceros.",
        ],
        de: [
          "Die Apple Health Schreibbrücke überträgt Daten von Android-Geräten (Smartwatches, Smart-Ringe) über die FitMesh EU-Cloud in HealthKit auf dem iPhone.",
          "Prüft zuerst, ob Apple Health diese Daten bereits enthält. Schreibt nur dort, wo etwas fehlt. Keine Duplikate.",
          "Schlaf mit vollständigen Phasen (Tiefschlaf, Leichtschlaf, REM): Die Ringphasen erscheinen in Apple Health im gleichen Format wie die Apple Watch.",
          "Opt-in, granular, widerrufbar: wird über die FitMesh iOS-Einstellungen aktiviert und kann jederzeit deaktiviert werden. HealthKit-Berechtigungen werden über iPhone-Einstellungen verwaltet.",
          "EU/DSGVO-Datenschutz: Cloud in EU-Rechenzentrum, verschlüsselt, kein Datenverkauf und keine Weitergabe an Dritte.",
        ],
        pt: [
          "A ponte de escrita do Apple Saúde leva os dados de dispositivos Android (smartwatches, anéis inteligentes) para o HealthKit no iPhone via nuvem FitMesh EU.",
          "Verifica primeiro se o Apple Saúde já tem esses dados. Grava apenas onde falta algo. Sem duplicatas.",
          "Sono com fases completas (profundo, leve, REM): as fases do anel aparecem no Apple Saúde no mesmo formato que o Apple Watch.",
          "Opt-in, granular, revogável: ativado nas configurações do FitMesh iOS e desativado a qualquer momento. As permissões do HealthKit são gerenciadas nos Ajustes do iPhone.",
          "Privacidade EU/RGPD: nuvem em datacenter EU, criptografada, sem venda ou compartilhamento de dados com terceiros.",
        ],
        fr: [
          "Le pont d'écriture Santé Apple transfère les données des appareils Android (montres connectées, bagues connectées) dans HealthKit sur iPhone via le cloud FitMesh EU.",
          "Vérifie d'abord si Santé Apple possède déjà ces données. N'écrit que là où quelque chose manque. Aucun doublon.",
          "Sommeil avec phases complètes (profond, léger, REM) : les phases de la bague apparaissent dans Santé Apple dans le même format que l'Apple Watch.",
          "Opt-in, granulaire, révocable : activé depuis les paramètres FitMesh iOS et désactivé à tout moment. Les autorisations HealthKit sont gérées depuis les Réglages iPhone.",
          "Confidentialité EU/RGPD : cloud en datacenter EU, chiffré, aucune vente ni partage de données avec des tiers.",
        ],
        pl: [
          "Ponte Apple Salute przekazuje dane z urządzeń Android (smartwatch, pętelki inteligentne) do konta HealthKit poprzez chmurę FitMesh EU.",
          "Sprawdź najpierw, czy Apple Zdrowie posiada już te dane. Pisz tylko tam, gdzie brakuje informacji. Nic nie powtarzaj.",
          "S:numelne pełne (głębokie, lekkie, REM): fazy pętli pojawiają się w Apple Salucie w tym samym formacie co Apple Watch.",
          "Opt-in, granulare, revocabile: aktywuje się w ustawieniach FitMesh iOS i można go wyłączyc w każdym momencie. Przywileje HealthKit są zarządzane przez iPhone Ustawienia.",
          "Zasada prywatności EU/GDPR: chmara w centrum danych EU, zaszyfrowana, żadnego sprzedawania ani udostępniania danych trzecim stronom.",
        ],
        tr: [
          "Apple Salute yazım köprüsü, Android cihazlarının (akıllı saat, smart aletleri) verilerini HealthKit içinde iPhone aracılığıyla bulut üzerinden FitMesh EU içine getirir.",
          "kontrol ettiğinde Apple Sağlık o zamana kadar o verileri zaten sahip olup olmadığını. Boş alanları doldurun ve tekrarlamaları yapma.",
          "Uyuyor musunuz tam fasilere (derin, hafif, REM): Apple Sağlık'ta Apple Cihaz'daki ağız halkası fasi aynı biçimde görünür.",
          "Opt-in, granülar, iptal edilebilir: FitMesh iOS ayarlarından etkinleştirilir ve her zaman devre dışı bırakılabilir. İzinler HealthKit ayarları tarafından yönetilir.\nKVKK ayarlarından iPhone ayarlarına.",
          "Gizlilik EU/GDPR: veri merkezinde bulut, şifreli, üçüncü partilere veri satışı veya paylaşılmaması.",
        ],
      },
    },
    {
      type: "cta",
      title: {
        it: "Prova il ponte Apple Salute in beta",
        en: "Try the Apple Health bridge in beta",
        es: "Prueba el puente de Apple Salud en beta",
        de: "Teste die Apple Health Brücke in der Beta",
        pt: "Experimente a ponte do Apple Saúde em beta",
        fr: "Testez le pont Santé Apple en bêta",
        pl: "Spróbuj błędnika Apple Zdrowia w betwie",
        tr: "Apple Sağlık Köprüsü'nü beta sürümünde deneyin",
      },
      body: {
        it: "FitMesh iOS è in beta TestFlight ora. Iscriviti per provare il ponte di scrittura Apple Salute e portare i dati del tuo wearable Android dentro l'app Salute di iPhone.",
        en: "FitMesh iOS is in TestFlight beta now. Sign up to try the Apple Health write bridge and bring your Android wearable data into the iPhone Health app.",
        es: "FitMesh iOS está en beta TestFlight ahora. Regístrate para probar el puente de escritura de Apple Salud y llevar los datos de tu wearable Android a la app Salud de iPhone.",
        de: "FitMesh iOS ist jetzt in der TestFlight-Beta. Melde dich an, um die Apple Health Schreibbrücke auszuprobieren und die Daten deines Android-Wearables in die iPhone Health-App zu bringen.",
        pt: "FitMesh iOS está em beta no TestFlight agora. Cadastre-se para experimentar a ponte de escrita do Apple Saúde e levar os dados do seu wearable Android para o app Saúde do iPhone.",
        fr: "FitMesh iOS est en bêta TestFlight maintenant. Inscrivez-vous pour tester le pont d'écriture Santé Apple et transférer les données de votre appareil connecté Android dans l'app Santé de l'iPhone.",
        pl: "FitMesh iOS jest teraz w bêta TestFlight. Zapisz siê, aby spróbować puÅ¼a Apple Salute i przenieÅ¼ycie danych z twojego wearable Android do aplikacji Salute od iPhone.",
        tr: "FitMesh iOS beta TestFlight sürümünde. Kaydol ve Apple Salute uygulamasının içindeki verilerinizi giyilebilir cihazınızdan Android app'a taşıyın. iPhone",
      },
      ctaLabel: {
        it: "Entra in beta iOS →",
        en: "Join iOS beta →",
        es: "Únete a la beta iOS →",
        de: "Zur iOS-Beta anmelden →",
        pt: "Entrar na beta iOS →",
        fr: "Rejoindre la bêta iOS →",
        pl: "Wejście w betę iOS →",
        tr: "Giriş beta iOS →",
      },
      ctaHref: {
        it: "/it/beta",
        en: "/en/beta",
      },
    },
  ],
  faq: [
    {
      q: {
        it: "Il ponte sovrascrive i dati già in Apple Salute?",
        en: "Does the bridge overwrite data already in Apple Health?",
        es: "¿El puente sobreescribe los datos que ya están en Apple Salud?",
        de: "Überschreibt die Brücke bereits in Apple Health vorhandene Daten?",
        pt: "A ponte sobrescreve os dados já presentes no Apple Saúde?",
        fr: "Le pont écrase-t-il les données déjà présentes dans Santé Apple ?",
        pl: "Czy most nadpisuje już istniejące dane w Apple Zdrowie?",
        tr: "KVKK, zaten Apple Sağlıktaki verileri geçersiz kılar mı?",
      },
      a: {
        it: "No. FitMesh controlla prima se Apple Salute ha già qualcosa per quella fascia oraria. Se c'è già un dato (di Apple Watch o di qualsiasi altra app), FitMesh non lo tocca. Non sovrascrive mai i dati esistenti.",
        en: "No. FitMesh checks first whether Apple Health already has something for that time slot. If there's already data there (from Apple Watch or any other app), FitMesh doesn't touch it. It never overwrites existing data.",
        es: "No. FitMesh comprueba primero si Apple Salud ya tiene algo para esa franja horaria. Si ya hay un dato (de Apple Watch o de cualquier otra app), FitMesh no lo toca. Nunca sobreescribe los datos existentes.",
        de: "Nein. FitMesh prüft zunächst, ob Apple Health für diesen Zeitraum bereits etwas enthält. Wenn bereits Daten vorhanden sind (von der Apple Watch oder einer anderen App), berührt FitMesh diese nicht. Vorhandene Daten werden nie überschrieben.",
        pt: "Não. O FitMesh verifica primeiro se o Apple Saúde já tem algo para aquele intervalo de tempo. Se já houver um dado (do Apple Watch ou de qualquer outro app), o FitMesh não o toca. Nunca sobrescreve dados existentes.",
        fr: "Non. FitMesh vérifie d'abord si Santé Apple possède déjà quelque chose pour ce créneau horaire. S'il y a déjà une donnée (de l'Apple Watch ou de n'importe quelle autre app), FitMesh n'y touche pas. Il ne remplace jamais les données existantes.",
        pl: "No. FitMesh sprawdza najpierw, czy Apple Salute ma już coś dla tej godziny. Jeśli jest już dane (z Apple Watch lub jakiejkolwiek innej aplikacji), FitMesh ich nie zmienia ani nie nadpisuje.",
        tr: "No. FitMesh önce Apple Sağlık için o saat aralığıne sahip bir veri olup olmadığını kontrol eder. Eğer varsa (Akıllı Saat veya başka herhangi bir uygulamanın), FitMesh onu değiştirmeyecektir. Her zaman mevcut verileri örtmez.",
      },
    },
    {
      q: {
        it: "Quali tipi di dato vengono scritti in Apple Salute?",
        en: "Which data types get written to Apple Health?",
        es: "¿Qué tipos de datos se escriben en Apple Salud?",
        de: "Welche Datentypen werden in Apple Health geschrieben?",
        pt: "Quais tipos de dados são gravados no Apple Saúde?",
        fr: "Quels types de données sont écrits dans Santé Apple ?",
        pl: "Jaki typ danych jest zapisywany w Apple Salute?",
        tr: "Hangi tür veriler Apple Sağlık'a yazılır?",
      },
      a: {
        it: "Dipende dalle sorgenti che hai collegato su Android e dai permessi che hai concesso. I tipi supportati oggi includono: sonno con fasi (profondo, leggero, REM, veglia), passi, frequenza cardiaca (campioni), calorie attive, distanza. Puoi scegliere granularmente quali tipi attivare per il bridge nelle impostazioni FitMesh iOS.",
        en: "Depends on the sources you've connected on Android and the permissions you've granted. Supported types today include: sleep with stages (deep, light, REM, awake), steps, heart rate (samples), active calories, distance. You can choose granularly which types to enable for the bridge in FitMesh iOS settings.",
        es: "Depende de las fuentes que hayas conectado en Android y de los permisos que hayas concedido. Los tipos compatibles actualmente incluyen: sueño con fases (profundo, ligero, REM, vigilia), pasos, frecuencia cardíaca (muestras), calorías activas, distancia. Puedes elegir de forma granular qué tipos activar para el puente en los ajustes de FitMesh iOS.",
        de: "Das hängt von den Quellen ab, die du auf Android verbunden hast, und von den erteilten Berechtigungen. Heute unterstützte Typen umfassen: Schlaf mit Phasen (Tiefschlaf, Leichtschlaf, REM, Wach), Schritte, Herzfrequenz (Messwerte), aktive Kalorien, Distanz. Du kannst in den FitMesh iOS-Einstellungen granular auswählen, welche Typen für die Brücke aktiviert werden sollen.",
        pt: "Depende das fontes que você conectou no Android e das permissões que concedeu. Os tipos compatíveis hoje incluem: sono com fases (profundo, leve, REM, acordado), passos, frequência cardíaca (amostras), calorias ativas, distância. Você pode escolher de forma granular quais tipos ativar para a ponte nas configurações do FitMesh iOS.",
        fr: "Cela dépend des sources que vous avez connectées sur Android et des autorisations accordées. Les types pris en charge aujourd'hui comprennent : sommeil avec phases (profond, léger, REM, éveil), pas, fréquence cardiaque (échantillons), calories actives, distance. Vous pouvez choisir de manière granulaire les types à activer pour le pont dans les paramètres FitMesh iOS.",
        pl: "Zależy od źródeł, które podłączyłeś do Android oraz odszurowań, które udzieliłeś. Obecnie wspierane są następujące typy: sen z fazami (głęboki, lekki, REM, baczność), kroki, częstotliwość serca ( próby ), kalorie aktywne, dystans. Możesz wybierać precyzyjnie, które typy aktywować dla mostka w ustawieniach FitMesh iOS.",
        tr: "Bağımlı oldugu sorgulardan ve verilen izinlerden. Bugün desteklenen türler: uykunun aşamaları (derin, hafif, REM, uyanık), adımlar, kalp atış hızı (öbekleri), aktif kaloriler, mesafe. Ayarlar FitMesh iOS içinde uygun türleri nasıl etkinleştirebileceğinizi seçebilirsiniz.",
      },
    },
    {
      q: {
        it: "Funziona anche se non ho un anello smart Colmi?",
        en: "Does it work even if I don't have a Colmi smart ring?",
        es: "¿Funciona aunque no tenga un anillo inteligente Colmi?",
        de: "Funktioniert es auch ohne einen Colmi Smart-Ring?",
        pt: "Funciona mesmo que eu não tenha um anel inteligente Colmi?",
        fr: "Cela fonctionne-t-il même sans bague connectée Colmi ?",
        pl: "Czy działa nawet jeśli nie ma tam pęceł smart Colmi?",
        tr: "Functiyon eğer pisolini Colmi olmamışsa da mı?",
      },
      a: {
        it: "Sì. Il ponte funziona con qualsiasi device collegato al tuo account FitMesh su Android: Galaxy Watch, Wear OS, qualsiasi wearable che scrive su Health Connect. L'anello Colmi è un esempio di device particolarmente utile per il ponte perché è specializzato nel sonno notturno, ma non è l'unico compatibile.",
        en: "Yes. The bridge works with any device connected to your FitMesh account on Android: Galaxy Watch, Wear OS, any wearable writing to Health Connect. The Colmi ring is an example of a device particularly useful for the bridge because it specializes in nighttime sleep, but it's not the only compatible one.",
        es: "Sí. El puente funciona con cualquier dispositivo conectado a tu cuenta FitMesh en Android: Galaxy Watch, Wear OS, cualquier wearable que escriba en Health Connect. El anillo Colmi es un ejemplo de dispositivo especialmente útil para el puente porque está especializado en el sueño nocturno, pero no es el único compatible.",
        de: "Ja. Die Brücke funktioniert mit jedem Gerät, das mit deinem FitMesh-Konto auf Android verbunden ist: Galaxy Watch, Wear OS, jedes Wearable, das in Health Connect schreibt. Der Colmi-Ring ist ein Beispiel für ein Gerät, das besonders nützlich für die Brücke ist, weil es auf den Nachtschlaf spezialisiert ist, aber es ist nicht das einzige kompatible Gerät.",
        pt: "Sim. A ponte funciona com qualquer dispositivo conectado à sua conta FitMesh no Android: Galaxy Watch, Wear OS, qualquer wearable que grave no Health Connect. O anel Colmi é um exemplo de dispositivo especialmente útil para a ponte porque é especializado no sono noturno, mas não é o único compatível.",
        fr: "Oui. Le pont fonctionne avec n'importe quel appareil connecté à votre compte FitMesh sur Android : Galaxy Watch, Wear OS, tout wearable qui écrit dans Health Connect. La bague Colmi est un exemple d'appareil particulièrement utile pour le pont car elle se spécialise dans le sommeil nocturne, mais ce n'est pas la seule compatible.",
        pl: "Tak. Mostwa działa z dowolnym urządzeniem połączonego z Twoim kontem FitMesh na Android: Galaxy Watch, Wear OS, każdy wearable piszący na Health Connect. Pasek Colmi jest przykładem szczególnie przydatnego urządzenia dla mostka, ponieważ jest specjalizowany w śniegu nocnym, ale nie jest jedynym zgodnym.",
        tr: "Evet. Köprü herhangi bir cihazla çalışır, bu cihaz FitMesh hesabınıza bağlanmıştır: Galaxy Watch, Wear OS, veya herhangi bir Health Connect yazan herhangi bir giyilebilir cihaz. Colmi halkası, köprü için özellikle faydalı bir cihaz örneklemidir çünkü uyku izleyicisidir, ancak tek başına uygun değildir.",
      },
    },
    {
      q: {
        it: "I dati vengono aggiornati in tempo reale?",
        en: "Is data updated in real time?",
        es: "¿Los datos se actualizan en tiempo real?",
        de: "Werden die Daten in Echtzeit aktualisiert?",
        pt: "Os dados são atualizados em tempo real?",
        fr: "Les données sont-elles mises à jour en temps réel ?",
        pl: "Czy dane są aktualizowane w czasie rzeczywistym?",
        tr: "Verilerin gerçek zamanlı güncellenmesi gerekmektedir?",
      },
      a: {
        it: "Il percorso è: il telefono Android sincronizza i dati sul cloud FitMesh (ogni pochi minuti), poi l'app iPhone li scrive in Apple Salute alla prossima apertura o in background. Non è real-time istantaneo, ma è automatico: senza alcun export manuale, i dati della notte precedente sono in Apple Salute entro pochi minuti dall'apertura dell'app al mattino.",
        en: "The path is: the Android phone syncs data to the FitMesh cloud (every few minutes), then the iPhone app writes it to Apple Health the next time it opens or runs in background. It's not instant real-time, but it's automatic: with no manual export, the previous night's data is in Apple Health within minutes of opening the app in the morning.",
        es: "El recorrido es: el teléfono Android sincroniza los datos en la nube FitMesh (cada pocos minutos) y luego la app de iPhone los escribe en Apple Salud la próxima vez que se abre o en segundo plano. No es tiempo real instantáneo, pero es automático: sin ninguna exportación manual, los datos de la noche anterior están en Apple Salud pocos minutos después de abrir la app por la mañana.",
        de: "Der Ablauf ist: Das Android-Telefon synchronisiert die Daten mit der FitMesh-Cloud (alle paar Minuten), dann schreibt die iPhone-App sie in Apple Health beim nächsten Öffnen oder im Hintergrund. Es ist keine sofortige Echtzeit-Aktualisierung, aber automatisch: Ohne manuellen Export sind die Daten der vorherigen Nacht in Apple Health, wenige Minuten nachdem du morgens die App öffnest.",
        pt: "O percurso é: o telefone Android sincroniza os dados com a nuvem FitMesh (a cada poucos minutos), depois o app iPhone os grava no Apple Saúde na próxima abertura ou em segundo plano. Não é em tempo real instantâneo, mas é automático: sem nenhuma exportação manual, os dados da noite anterior estão no Apple Saúde em poucos minutos após abrir o app pela manhã.",
        fr: "Le chemin est le suivant : le téléphone Android synchronise les données vers le cloud FitMesh (toutes les quelques minutes), puis l'app iPhone les écrit dans Santé Apple lors de la prochaine ouverture ou en arrière-plan. Ce n'est pas du temps réel instantané, mais c'est automatique : sans aucune exportation manuelle, les données de la nuit précédente sont dans Santé Apple quelques minutes après l'ouverture de l'app le matin.",
        pl: "Proces jest ten: telefon Android synchronizuje dane z chmury FitMesh (każde kilka minut), a następnie aplikacja iPhone zapisuje je w Apple Salute podczas kolejnej otwarcia lub w tle. Nie jest to synchronizacja w czasie rzeczywistym, ale jest automatyczne: bez żadnego eksportu ręcznego, dane ze sztucznego senu z poprzedniej nocy są dostępne w Apple Salute w ciągu kilku minut od otworzenia aplikacji w porze rano.",
        tr: "Süreç şöyle işler: Android telefon verileri FitMesh bulutuna senkronize eder (her birkaç dakikada bir), ardından iPhone uygulaması bunları bir sonraki açılışta veya arka planda Apple Sağlık'a yazar. Anlık gerçek zamanlı değildir, ancak otomatiktir: manuel dışa aktarma olmadan, önceki gecenin verileri sabah uygulamayı açtıktan birkaç dakika içinde Apple Sağlık'ta hazır olur.",
      },
    },
    {
      q: {
        it: "Come vengono mostrati i dati in Apple Salute?",
        en: "How is the data shown in Apple Health?",
        es: "¿Cómo se muestran los datos en Apple Salud?",
        de: "Wie werden die Daten in Apple Health angezeigt?",
        pt: "Como os dados são exibidos no Apple Saúde?",
        fr: "Comment les données sont-elles affichées dans Santé Apple ?",
        pl: "Jak są wyświetlane dane w Apple Zdrowie?",
        tr: "Apple Sağlık'ta veriler nasıl gösterilir?",
      },
      a: {
        it: "I dati scritti dal ponte appaiono nell'app Salute esattamente come qualsiasi altra voce HealthKit: con timestamp, tipo di dato, e sorgente. La sorgente indicata è 'FitMesh Sync'. Puoi vederli nel grafico Sonno, nel Riepilogo, e nelle singole categorie (Passi, Frequenza cardiaca, ecc.). Puoi anche rimuoverli da Apple Salute in qualsiasi momento se decidi di disattivare il bridge.",
        en: "Data written by the bridge appears in the Health app exactly like any other HealthKit entry: with timestamp, data type, and source. The source listed is 'FitMesh Sync'. You can see them in the Sleep chart, in Summary, and in individual categories (Steps, Heart Rate, etc.). You can also remove them from Apple Health at any time if you decide to turn off the bridge.",
        es: "Los datos escritos por el puente aparecen en la app Salud exactamente como cualquier otra entrada de HealthKit: con marca de tiempo, tipo de dato y fuente. La fuente indicada es 'FitMesh Sync'. Puedes verlos en el gráfico de Sueño, en el Resumen y en las categorías individuales (Pasos, Frecuencia cardíaca, etc.). También puedes eliminarlos de Apple Salud en cualquier momento si decides desactivar el puente.",
        de: "Die von der Brücke geschriebenen Daten erscheinen in der Health-App genau wie jeder andere HealthKit-Eintrag: mit Zeitstempel, Datentyp und Quelle. Als Quelle ist 'FitMesh Sync' angegeben. Du kannst sie im Schlaf-Diagramm, in der Zusammenfassung und in den einzelnen Kategorien sehen (Schritte, Herzfrequenz usw.). Du kannst sie auch jederzeit aus Apple Health entfernen, wenn du die Brücke deaktivieren möchtest.",
        pt: "Os dados gravados pela ponte aparecem no app Saúde exatamente como qualquer outra entrada do HealthKit: com data e hora, tipo de dado e fonte. A fonte indicada é 'FitMesh Sync'. Você pode vê-los no gráfico de Sono, no Resumo e nas categorias individuais (Passos, Frequência cardíaca, etc.). Você também pode removê-los do Apple Saúde a qualquer momento se decidir desativar a ponte.",
        fr: "Les données écrites par le pont apparaissent dans l'app Santé exactement comme n'importe quelle autre entrée HealthKit : avec horodatage, type de données et source. La source indiquée est 'FitMesh Sync'. Vous pouvez les voir dans le graphique Sommeil, dans le Récapitulatif et dans les catégories individuelles (Pas, Fréquence cardiaque, etc.). Vous pouvez également les supprimer de Santé Apple à tout moment si vous décidez de désactiver le pont.",
        pl: "Dane zapisane przez mostka pojawiają się w aplikacji Zdrowie dokładnie tak jak każda inna pozycja HealthKit: ze znacznikami czasu, typem danych i źródłem. Podane źródło to 'FitMesh Sync'. Mogą one być widziane w wykresie Sen, podsumowaniu oraz w poszczególnych kategoriach (Kroki, Częstotliwość serca, itp.). Możesz również usunąć je z Zdrowia Apple w każdym momencie, jeśli zdecydujesz się wyłączyć mostek.",
        tr: "Veriler köprüden yazılırken, HealthKit gibi herhangi bir diğer girdiye benzer olarak FitMesh Sync kaynaklı zaman damgası, veri tipi ve kaynağıyla Görüntüleme uygulamasında görünür. Uyku grafikinde, özeti ve bireysel kategoriler (Adım sayımı, Kalp atış hızı, vs.) içinde bu verileri bulabilirsiniz. Verileri her zaman Apple Sağlık uygulamasından da kaldırmayı seçebilirsiniz, köprü devre dışı bırakılırken.",
      },
    },
  ],
  related: [
    "fitmesh-arriva-su-iphone",
    "colmi-ring-fitmesh",
    "come-funziona-health-connect",
    "gdpr-dati-fitness-smartwatch",
  ],
  brandsMentioned: ["Apple", "Samsung"],
  ldType: "BlogPosting",
};
