import type { BlogPost } from "../types";

export const post: BlogPost = {
  slug: "fitbit-data-not-syncing-android",
  category: "guides",
  publishedAt: "2026-06-08",
  updatedAt: "2026-06-08",
  readMinutes: 7,
  tldr: {
    it: [
      "Nel 95% dei casi il problema non è Fitbit ma un permesso mancante in Health Connect.",
      "Fitbit scrive su Health Connect solo se abiliti la scrittura manualmente nelle sue impostazioni.",
      "L'app di destinazione ha bisogno di un permesso di lettura separato e indipendente da quello di Fitbit.",
      "Health Connect non sincronizza i dati storici: solo dal momento dell'autorizzazione in avanti.",
      "Alcuni Fitbit di vecchia generazione scrivono su Google Fit, non su Health Connect: aggiorna il firmware o verifica la compatibilità.",
    ],
    en: [
      "In 95% of cases the problem isn't Fitbit but a missing permission in Health Connect.",
      "Fitbit writes to Health Connect only if you enable writing manually in its settings.",
      "The destination app needs its own read permission, separate and independent from Fitbit's.",
      "Health Connect doesn't sync historical data: only from the moment of authorization onwards.",
      "Some older Fitbit models write to Google Fit, not Health Connect: update the firmware or check compatibility.",
    ],
    es: [
      "En el 95% de los casos el problema no es Fitbit, sino un permiso faltante en Health Connect.",
      "Fitbit escribe en Health Connect solo si habilitas la escritura manualmente en sus ajustes.",
      "La app de destino necesita su propio permiso de lectura, separado e independiente del de Fitbit.",
      "Health Connect no sincroniza datos históricos: solo desde el momento de la autorización en adelante.",
      "Algunos modelos antiguos de Fitbit escriben en Google Fit, no en Health Connect: actualiza el firmware o verifica la compatibilidad.",
    ],
    de: [
      "In 95 % der Fälle liegt das Problem nicht bei Fitbit, sondern an einem fehlenden Berechtigungseintrag in Health Connect.",
      "Fitbit schreibt nur dann in Health Connect, wenn du die Schreibberechtigung manuell in den Einstellungen aktivierst.",
      "Die Ziel-App benötigt eine eigene Leseberechtigung, die unabhängig von der Fitbit-Berechtigung ist.",
      "Health Connect synchronisiert keine historischen Daten: nur Daten ab dem Zeitpunkt der Autorisierung.",
      "Einige ältere Fitbit-Modelle schreiben in Google Fit, nicht in Health Connect. Aktualisiere die Firmware oder prüfe die Kompatibilität.",
    ],
    pt: [
      "Em 95% dos casos, o problema não é o Fitbit, mas uma permissão ausente no Health Connect.",
      "O Fitbit grava no Health Connect apenas se você ativar a escrita manualmente nas configurações.",
      "O app de destino precisa de sua própria permissão de leitura, separada e independente da do Fitbit.",
      "O Health Connect não sincroniza dados históricos: apenas a partir do momento da autorização.",
      "Alguns modelos mais antigos do Fitbit gravam no Google Fit, não no Health Connect. Atualize o firmware ou verifique a compatibilidade.",
    ],
    fr: [
      "Dans 95 % des cas, le problème ne vient pas de Fitbit mais d'une autorisation manquante dans Health Connect.",
      "Fitbit n'écrit dans Health Connect que si vous activez manuellement l'écriture dans ses paramètres.",
      "L'application de destination a besoin de sa propre autorisation de lecture, indépendante de celle de Fitbit.",
      "Health Connect ne synchronise pas les données historiques : seulement à partir du moment de l'autorisation.",
      "Certains anciens modèles Fitbit écrivent dans Google Fit et non dans Health Connect. Mettez à jour le firmware ou vérifiez la compatibilité.",
    ],
    pl: [
      "W 95% przypadków problem nie leży po stronie Fitbit, lecz w brakującym uprawnieniu w Health Connect.",
      "Fitbit zapisuje dane do Health Connect tylko wtedy, gdy ręcznie włączysz tę opcję w ustawieniach aplikacji.",
      "Aplikacja docelowa potrzebuje własnego uprawnienia do odczytu, niezależnego od uprawnień Fitbit.",
      "Health Connect nie synchronizuje danych historycznych: tylko od momentu udzielenia zgody.",
      "Niektóre starsze modele Fitbit zapisują dane do Google Fit, a nie do Health Connect. Zaktualizuj firmware lub sprawdź zgodność.",
    ],
    tr: [
      "%95 durumda sorun Fitbit'te değil, Health Connect'te eksik bir izindedir.",
      "Fitbit, Health Connect'e yalnızca uygulama ayarlarından yazmayı manuel olarak etkinleştirirseniz veri yazar.",
      "Hedef uygulamanın, Fitbit izninden bağımsız olarak kendi okuma iznine ihtiyacı vardır.",
      "Health Connect geçmiş verileri eşitlemez: yalnızca yetkilendirme anından itibaren.",
      "Bazı eski Fitbit modelleri Health Connect yerine Google Fit'e yazar. Firmware'i güncelleyin veya uyumluluğu kontrol edin.",
    ],
    nl: [
      "In 95% van de gevallen ligt het probleem niet bij Fitbit, maar bij een ontbrekende toestemming in Health Connect.",
      "Fitbit schrijft alleen naar Health Connect als je schrijven handmatig inschakelt in de instellingen.",
      "De doelapp heeft zijn eigen leestoestemming nodig, los en onafhankelijk van die van Fitbit.",
      "Health Connect synchroniseert geen historische gegevens: alleen vanaf het moment van autorisatie.",
      "Sommige oudere Fitbit-modellen schrijven naar Google Fit, niet naar Health Connect. Update de firmware of controleer de compatibiliteit.",
    ],
    ja: [
      "95%のケースで、問題はFitbitではなくHealth Connectの権限が不足していることです。",
      "FitbitがHealth Connectにデータを書き込むには、設定で手動で書き込みを有効にする必要があります。",
      "宛先アプリにはFitbitとは別に独自の読み取り権限が必要です。",
      "Health Connectは過去のデータを同期しません。認証した時点以降のデータのみが対象です。",
      "一部の古いFitbitモデルはHealth ConnectではなくGoogle Fitに書き込みます。ファームウェアを更新するか、互換性を確認してください。",
    ],
    ko: [
      "95%의 경우 문제는 Fitbit이 아니라 Health Connect의 권한 누락입니다.",
      "Fitbit은 설정에서 쓰기를 수동으로 활성화해야만 Health Connect에 데이터를 씁니다.",
      "대상 앱은 Fitbit과 별개로 독립적인 읽기 권한이 필요합니다.",
      "Health Connect는 과거 데이터를 동기화하지 않습니다. 권한 부여 시점 이후의 데이터만 해당됩니다.",
      "일부 구형 Fitbit 모델은 Health Connect가 아닌 Google Fit에 씁니다. 펌웨어를 업데이트하거나 호환성을 확인하세요.",
    ],
  },
  primaryKeyword: {
    it: "fitbit non si sincronizza android",
    en: "fitbit data not syncing android",
    es: "fitbit no sincroniza datos android",
    pt: "fitbit não sincroniza dados android",
    fr: "fitbit ne se synchronise pas android",
    pl: "fitbit nie synchronizuje danych android",
    tr: "fitbit verileri android'de senkronize olmuyor",
    nl: "fitbit gegevens synchroniseren niet android",
    ja: "fitbit データ 同期しない android",
    ko: "fitbit 데이터 동기화 안됨 android",
  },
  secondaryKeywords: {
    it: [
      "fitbit health connect android",
      "fitbit non sincronizza dati",
      "fitbit permessi health connect",
      "fitbit google fit android",
      "fitbit sync non funziona",
    ],
    en: [
      "fitbit health connect android",
      "fitbit not syncing data",
      "fitbit health connect permissions",
      "fitbit google fit android",
      "fitbit sync not working",
    ],
    pt: [
      "fitbit health connect android",
      "fitbit não sincroniza dados",
      "permissões fitbit health connect",
      "fitbit google fit android",
      "sincronização fitbit não funciona",
    ],
    fr: [
      "fitbit health connect android",
      "fitbit ne synchronise pas les données",
      "autorisations fitbit health connect",
      "fitbit google fit android",
      "synchronisation fitbit ne fonctionne pas",
    ],
    pl: [
      "fitbit health connect android",
      "fitbit nie synchronizuje danych",
      "uprawnienia fitbit health connect",
      "fitbit google fit android",
      "synchronizacja fitbit nie działa",
    ],
    tr: [
      "fitbit health connect android",
      "fitbit veri senkronizasyonu çalışmıyor",
      "fitbit health connect izinleri",
      "fitbit google fit android",
      "fitbit senkronizasyonu çalışmıyor",
    ],
    nl: [
      "fitbit health connect android",
      "fitbit synchroniseert geen gegevens",
      "fitbit health connect toestemmingen",
      "fitbit google fit android",
      "fitbit synchronisatie werkt niet",
    ],
    ja: [
      "fitbit health connect android",
      "fitbit データ同期しない",
      "fitbit health connect 権限",
      "fitbit google fit android",
      "fitbit 同期 動かない",
    ],
    ko: [
      "fitbit health connect android",
      "fitbit 데이터 동기화 안됨",
      "fitbit health connect 권한",
      "fitbit google fit android",
      "fitbit 동기화 작동 안함",
    ],
  },
  metaDescription: {
    it: "Se i dati Fitbit non appaiono nelle app Android, il problema quasi sempre non è Fitbit: è un permesso mancante in Health Connect. Ecco dove guardare e come risolverlo in 30 secondi.",
    en: "When Fitbit data isn't showing up in Android apps, the fix is almost always a missing permission in Health Connect, not a Fitbit problem. Here's where to look and how to fix it in 30 seconds.",
    es: "Si los datos de Fitbit no aparecen en tus apps de Android, casi siempre el problema no es Fitbit: es un permiso faltante en Health Connect. Aquí te explicamos dónde mirar y cómo solucionarlo en 30 segundos.",
    de: "Wenn Fitbit-Daten in Android-Apps nicht erscheinen, liegt es fast immer an einer fehlenden Berechtigung in Health Connect. Hier erfährst du, wo du suchen und wie du es in 30 Sekunden beheben kannst.",
    pt: "Se os dados do Fitbit não aparecem nos apps Android, o problema quase sempre não é o Fitbit: é uma permissão ausente no Health Connect. Veja onde procurar e como resolver em 30 segundos.",
    fr: "Si les données Fitbit n'apparaissent pas dans vos applications Android, le problème vient presque toujours d'une autorisation manquante dans Health Connect. Voici où chercher et comment résoudre cela en 30 secondes.",
    pl: "Gdy dane Fitbit nie pojawiają się w aplikacjach Android, problem to prawie zawsze brakujące uprawnienie w Health Connect, nie błąd Fitbit. Sprawdź, gdzie szukać i jak to naprawić w 30 sekund.",
    tr: "Android uygulamalarında Fitbit verileri görünmüyorsa sorun neredeyse her zaman Health Connect'te eksik bir izindir, Fitbit sorunu değil. Nereye bakacağınızı ve 30 saniyede nasıl düzelteceğinizi öğrenin.",
    nl: "Als Fitbit-gegevens niet verschijnen in Android-apps, is de oorzaak bijna altijd een ontbrekende toestemming in Health Connect, geen Fitbit-probleem. Hier leest u waar u moet kijken en hoe u het in 30 seconden oplost.",
    ja: "AndroidアプリにFitbitのデータが表示されない場合、原因はほぼ常にHealth Connectの権限不足であり、Fitbitの問題ではありません。どこを確認すれば30秒で解決できるかを説明します。",
    ko: "Android 앱에 Fitbit 데이터가 표시되지 않는다면, 원인은 거의 항상 Health Connect의 권한 누락이지 Fitbit 문제가 아닙니다. 어디를 확인해야 하는지, 30초 안에 해결하는 방법을 알아보세요.",
  },
  hero: {
    kicker: { it: "Guida", en: "Guide", es: "Guía", de: "Anleitung", pt: "Guia", fr: "Guide", pl: "Poradnik", tr: "Kılavuz", nl: "Gids", ja: "ガイド", ko: "가이드" },
    title: {
      it: "Fitbit non si sincronizza su Android: la causa vera (e la soluzione)",
      en: "Fitbit data not syncing on Android: the real cause (and the fix)",
      es: "Fitbit no sincroniza en Android: la causa real (y la solución)",
      de: "Fitbit synchronisiert nicht auf Android: die eigentliche Ursache (und die Lösung)",
      pt: "Fitbit não sincroniza no Android: a causa real (e a solução)",
      fr: "Fitbit ne se synchronise pas sur Android : la vraie cause (et la solution)",
      pl: "Fitbit nie synchronizuje się na Androidzie: prawdziwa przyczyna (i rozwiązanie)",
      tr: "Android'de Fitbit verileri senkronize olmuyor: gerçek neden (ve çözüm)",
      nl: "Fitbit-gegevens synchroniseren niet op Android: de echte oorzaak (en de oplossing)",
      ja: "AndroidでFitbitデータが同期しない：本当の原因（と解決策）",
      ko: "Android에서 Fitbit 데이터가 동기화되지 않음: 진짜 원인 (그리고 해결책)",
    },
    subtitle: {
      it: "Il 95% dei casi ha una sola causa: i permessi Health Connect. Non Bluetooth, non una reinstallazione. Ecco dove guardare.",
      en: "95% of cases have one root cause: Health Connect permissions. Not Bluetooth, not a reinstall. Here's where to look.",
      es: "El 95% de los casos tiene una sola causa: los permisos de Health Connect. No es el Bluetooth ni una reinstalación. Aquí te mostramos dónde buscar.",
      de: "95 % der Fälle haben eine einzige Ursache: die Health Connect-Berechtigungen. Nicht Bluetooth, keine Neuinstallation. Hier erfährst du, wo du suchen musst.",
      pt: "95% dos casos têm uma única causa: as permissões do Health Connect. Não é o Bluetooth nem uma reinstalação. Veja onde procurar.",
      fr: "95 % des cas ont une seule cause : les autorisations Health Connect. Pas le Bluetooth, pas une réinstallation. Voici où chercher.",
      pl: "W 95% przypadków jest jedna przyczyna: uprawnienia Health Connect. Nie Bluetooth, nie reinstalacja. Oto gdzie szukać.",
      tr: "%95 durumda tek bir kök neden vardır: Health Connect izinleri. Bluetooth değil, yeniden kurulum değil. İşte nereye bakmanız gerektiği.",
      nl: "95% van de gevallen heeft één oorzaak: Health Connect-toestemmingen. Niet Bluetooth, geen herinstallatie. Dit is waar u moet kijken.",
      ja: "95%のケースで根本原因は一つ：Health Connectの権限です。Bluetoothでも再インストールでもありません。確認すべき場所を説明します。",
      ko: "95%의 경우 근본 원인은 하나입니다: Health Connect 권한. Bluetooth도 아니고, 재설치도 아닙니다. 확인해야 할 곳을 알아보세요.",
    },
  },
  body: [
    {
      type: "paragraph",
      text: {
        it: "Quando i dati Fitbit non compaiono nelle app Android, il problema è quasi sempre un permesso mancante in Health Connect, non un bug di Fitbit. Ho visto questa situazione decine di volte: l'app Fitbit funziona perfettamente, il wearable sincronizza, ma una terza app non vede nulla. La colpa non è di Fitbit. Fitbit ha già fatto la sua parte.",
        en: "When Fitbit data isn't showing up in Android apps, the fix is almost always a missing permission in Health Connect, not a Fitbit problem. I've seen this situation dozens of times: the Fitbit app works perfectly, the wearable syncs, but a third-party app sees nothing. It's not Fitbit's fault. Fitbit already did its part.",
        es: "Cuando los datos de Fitbit no aparecen en las apps de Android, la solución casi siempre es un permiso faltante en Health Connect, no un problema de Fitbit. He visto esta situación decenas de veces: la app Fitbit funciona perfectamente, el wearable sincroniza, pero una app de terceros no ve nada. No es culpa de Fitbit. Fitbit ya hizo su parte.",
        de: "Wenn Fitbit-Daten in Android-Apps nicht angezeigt werden, liegt es fast immer an einer fehlenden Berechtigung in Health Connect und nicht an einem Fehler in Fitbit. Ich habe diese Situation dutzende Male gesehen: Die Fitbit-App funktioniert einwandfrei, das Wearable synchronisiert, aber eine Drittanbieter-App sieht nichts. Es ist nicht Fitbits Schuld. Fitbit hat seinen Teil bereits erledigt.",
        pt: "Quando os dados do Fitbit não aparecem nos apps Android, o problema quase sempre é uma permissão ausente no Health Connect, não um erro do Fitbit. Já vi essa situação dezenas de vezes: o app Fitbit funciona perfeitamente, o wearable sincroniza, mas um app de terceiros não vê nada. A culpa não é do Fitbit. O Fitbit já fez a sua parte.",
        fr: "Quand les données Fitbit n'apparaissent pas dans les applications Android, le problème vient presque toujours d'une autorisation manquante dans Health Connect, et non d'un bug Fitbit. J'ai vu cette situation des dizaines de fois : l'application Fitbit fonctionne parfaitement, le wearable se synchronise, mais une application tierce ne voit rien. Ce n'est pas la faute de Fitbit. Fitbit a déjà fait sa part.",
        pl: "Gdy dane Fitbit nie pojawiają się w aplikacjach Android, problem to prawie zawsze brakujące uprawnienie w Health Connect, a nie błąd Fitbit. Widziałem tę sytuację dziesiątki razy: aplikacja Fitbit działa perfekcyjnie, urządzenie synchronizuje się, ale aplikacja innego producenta nic nie widzi. To nie wina Fitbit. Fitbit już wykonał swoją część.",
        tr: "Android uygulamalarında Fitbit verileri görünmüyorsa sorun neredeyse her zaman Health Connect'te eksik bir izindir, Fitbit sorunu değil. Bu durumu onlarca kez gördüm: Fitbit uygulaması mükemmel çalışıyor, giyilebilir cihaz eşitleniyor, ancak üçüncü taraf uygulama hiçbir şey görmüyor. Bu Fitbit'in hatası değil. Fitbit zaten üzerine düşeni yaptı.",
        nl: "Wanneer Fitbit-gegevens niet verschijnen in Android-apps, is de oplossing bijna altijd een ontbrekende toestemming in Health Connect, geen Fitbit-probleem. Ik heb deze situatie tientallen keren gezien: de Fitbit-app werkt perfect, het wearable synchroniseert, maar een app van derden ziet niets. Het is niet de schuld van Fitbit. Fitbit heeft zijn deel al gedaan.",
        ja: "AndroidアプリにFitbitのデータが表示されない場合、解決策はほぼ常にHealth Connectの権限不足であり、Fitbitの問題ではありません。この状況を何十回も見てきました。Fitbitアプリは完璧に動作し、ウェアラブルは同期していますが、サードパーティアプリには何も表示されません。Fitbitのせいではありません。Fitbitはすでに自分の役割を果たしています。",
        ko: "Android 앱에 Fitbit 데이터가 표시되지 않을 때, 해결책은 거의 항상 Health Connect의 권한 누락이지 Fitbit 문제가 아닙니다. 저는 이런 상황을 수십 번 봐왔습니다. Fitbit 앱은 완벽하게 작동하고, 웨어러블은 동기화되지만, 서드파티 앱은 아무것도 보지 못합니다. Fitbit의 잘못이 아닙니다. Fitbit은 이미 자신의 역할을 다했습니다.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Perché succede: come funziona lo scambio dati su Android",
        en: "Why it happens: how data exchange works on Android",
        es: "Por qué ocurre: cómo funciona el intercambio de datos en Android",
        de: "Warum es passiert: wie der Datenaustausch auf Android funktioniert",
        pt: "Por que isso acontece: como funciona a troca de dados no Android",
        fr: "Pourquoi cela arrive : comment fonctionne l'échange de données sur Android",
        pl: "Dlaczego tak się dzieje: jak działa wymiana danych na Androidzie",
        tr: "Neden oluyor: Android'de veri alışverişi nasıl çalışır",
        nl: "Waarom het gebeurt: hoe gegevensuitwisseling werkt op Android",
        ja: "なぜ起きるのか：Androidにおけるデータ交換の仕組み",
        ko: "왜 발생하는가: Android에서 데이터 교환이 작동하는 방식",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Su Android, Fitbit non condivide i dati direttamente con le altre app. Li deposita in Health Connect, un database locale sul tuo telefono che fa da intermediario. Pensa a Health Connect come a una cassetta postale condivisa: Fitbit ci lascia dentro i tuoi passi, la frequenza cardiaca, i dati del sonno. Le altre app possono leggere quella posta, ma solo se hanno una chiave per aprire la cassetta. Se un'app non ha quel permesso esplicito, non vede nulla. E Fitbit non ha modo di sapere che la posta non è stata ritirata.",
        en: "On Android, Fitbit doesn't share data directly with other apps. It drops data into Health Connect, a local database on your phone that acts as an intermediary. Think of Health Connect like a shared mailbox: Fitbit drops your steps, heart rate, and sleep data inside. Other apps can read that mail, but only if they have a key to open the mailbox. If an app doesn't have that explicit permission, it sees nothing. And Fitbit has no way of knowing the mail wasn't picked up.",
        es: "En Android, Fitbit no comparte los datos directamente con otras apps. Los deposita en Health Connect, una base de datos local en tu teléfono que actúa como intermediario. Piensa en Health Connect como un buzón compartido: Fitbit deja dentro tus pasos, tu frecuencia cardíaca y los datos de sueño. Las demás apps pueden leer ese contenido, pero solo si tienen una clave para abrir el buzón. Si una app no tiene ese permiso explícito, no ve nada. Y Fitbit no tiene forma de saber que el contenido no fue recogido.",
        de: "Auf Android teilt Fitbit Daten nicht direkt mit anderen Apps. Es legt sie in Health Connect ab, einer lokalen Datenbank auf deinem Telefon, die als Vermittler fungiert. Stell dir Health Connect wie einen gemeinsamen Briefkasten vor: Fitbit legt deine Schritte, die Herzfrequenz und die Schlafdaten hinein. Andere Apps können diese Daten lesen, aber nur wenn sie einen Schlüssel zum Öffnen des Briefkastens haben. Hat eine App diese explizite Berechtigung nicht, sieht sie nichts. Und Fitbit hat keine Möglichkeit zu wissen, dass die Daten nicht abgeholt wurden.",
        pt: "No Android, o Fitbit não compartilha dados diretamente com outros apps. Ele deposita as informações no Health Connect, um banco de dados local no seu telefone que funciona como intermediário. Pense no Health Connect como uma caixa de correio compartilhada: o Fitbit deposita seus passos, frequência cardíaca e dados de sono lá dentro. Outros apps podem ler essas informações, mas apenas se tiverem uma chave para abrir a caixa. Se um app não tem essa permissão explícita, não vê nada. E o Fitbit não tem como saber que os dados não foram retirados.",
        fr: "Sur Android, Fitbit ne partage pas les données directement avec les autres applications. Il les dépose dans Health Connect, une base de données locale sur votre téléphone qui sert d'intermédiaire. Imaginez Health Connect comme une boîte aux lettres partagée : Fitbit y dépose vos pas, votre fréquence cardiaque et vos données de sommeil. Les autres applications peuvent lire ce contenu, mais seulement si elles ont une clé pour ouvrir la boîte. Si une application ne dispose pas de cette autorisation explicite, elle ne voit rien. Et Fitbit n'a aucun moyen de savoir que les données n'ont pas été récupérées.",
        pl: "Na Androidzie Fitbit nie udostępnia danych bezpośrednio innym aplikacjom. Przekazuje je do Health Connect, lokalnej bazy danych na telefonie, która pełni rolę pośrednika. Pomyśl o Health Connect jak o wspólnej skrzynce pocztowej: Fitbit zostawia tam Twoje kroki, tętno i dane snu. Inne aplikacje mogą odczytać tę zawartość, ale tylko jeśli mają klucz do skrzynki. Jeśli aplikacja nie ma takiego uprawnienia, nic nie widzi. A Fitbit nie ma możliwości sprawdzenia, czy poczta została odebrana.",
        tr: "Android'de Fitbit verileri diğer uygulamalarla doğrudan paylaşmaz. Telefonunuzdaki yerel bir veritabanı olan Health Connect'e bırakır; bu veritabanı aracı görevi görür. Health Connect'i ortak bir posta kutusu gibi düşünün: Fitbit adımlarınızı, kalp atış hızınızı ve uyku verilerinizi oraya bırakır. Diğer uygulamalar bu içeriği okuyabilir, ancak yalnızca kutuyu açacak anahtarları varsa. Bir uygulamanın açık izni yoksa hiçbir şey görmez. Fitbit ise postanın alınıp alınmadığını bilmenin bir yolunu bulamaz.",
        nl: "Op Android deelt Fitbit gegevens niet rechtstreeks met andere apps. Het plaatst de gegevens in Health Connect, een lokale database op uw telefoon die als tussenpersoon fungeert. Zie Health Connect als een gedeelde brievenbus: Fitbit legt uw stappen, hartslag en slaapgegevens erin. Andere apps kunnen die inhoud lezen, maar alleen als ze een sleutel hebben om de brievenbus te openen. Als een app die expliciete toestemming niet heeft, ziet hij niets. En Fitbit heeft geen manier om te weten dat de post niet is opgehaald.",
        ja: "AndroidではFitbitはデータを他のアプリと直接共有しません。仲介役を担う電話上のローカルデータベース、Health Connectにデータを預けます。Health Connectを共有のメールボックスのようなものと考えてください。Fitbitはあなたの歩数、心拍数、睡眠データをそこに入れます。他のアプリはその内容を読み取れますが、メールボックスを開く鍵を持っている場合に限ります。アプリが明示的な権限を持っていなければ、何も見えません。そしてFitbitには、データが受け取られたかどうかを知る方法がありません。",
        ko: "Android에서 Fitbit은 데이터를 다른 앱과 직접 공유하지 않습니다. 중개자 역할을 하는 휴대폰의 로컬 데이터베이스인 Health Connect에 데이터를 저장합니다. Health Connect를 공유 우편함으로 생각하세요. Fitbit은 걸음 수, 심박수, 수면 데이터를 그 안에 넣습니다. 다른 앱은 그 내용을 읽을 수 있지만, 우편함을 열 수 있는 열쇠가 있을 때만 가능합니다. 앱이 명시적인 권한을 갖고 있지 않으면 아무것도 볼 수 없습니다. 그리고 Fitbit은 데이터가 수신되었는지 알 방법이 없습니다.",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Il meccanismo è intenzionale: Health Connect è progettato per dare all'utente il controllo granulare su chi legge cosa. Ma questa granularità crea un punto di configurazione in più che molti non sanno esista. Risultato: l'utente vede un'app che 'non funziona', mentre in realtà è semplicemente senza permesso di lettura.",
        en: "The mechanism is intentional: Health Connect is designed to give users granular control over who reads what. But that granularity creates an extra configuration point that most people don't know exists. Result: the user sees an app that 'doesn't work', when really it's simply missing a read permission.",
        es: "El mecanismo es intencional: Health Connect está diseñado para darte un control detallado sobre quién lee qué. Pero esa granularidad crea un punto de configuración adicional que la mayoría desconoce. El resultado es que el usuario ve una app que 'no funciona', cuando en realidad simplemente le falta el permiso de lectura.",
        de: "Der Mechanismus ist beabsichtigt: Health Connect ist darauf ausgelegt, dem Nutzer eine granulare Kontrolle darüber zu geben, wer was liest. Diese Granularität schafft jedoch einen zusätzlichen Konfigurationspunkt, von dem die meisten Menschen nicht wissen, dass er existiert. Ergebnis: Der Nutzer sieht eine App, die 'nicht funktioniert', obwohl ihr eigentlich nur die Leseberechtigung fehlt.",
        pt: "O mecanismo é intencional: o Health Connect foi projetado para dar ao usuário controle granular sobre quem lê o quê. Mas essa granularidade cria um ponto de configuração extra que a maioria das pessoas não sabe que existe. Resultado: o usuário vê um app que 'não funciona', quando na verdade está simplesmente sem permissão de leitura.",
        fr: "Ce mécanisme est intentionnel : Health Connect est conçu pour donner à l'utilisateur un contrôle précis sur qui lit quoi. Mais cette granularité crée un point de configuration supplémentaire que la plupart des gens ignorent. Résultat : l'utilisateur voit une application qui \"ne fonctionne pas\", alors qu'en réalité il lui manque simplement une autorisation de lecture.",
        pl: "Ten mechanizm jest celowy: Health Connect został zaprojektowany, aby dać użytkownikom szczegółową kontrolę nad tym, kto co czyta. Ale ta szczegółowość tworzy dodatkowy punkt konfiguracyjny, o którym większość osób nie wie. Efekt: użytkownik widzi aplikację, która 'nie działa', podczas gdy w rzeczywistości po prostu brakuje jej uprawnienia do odczytu.",
        tr: "Bu mekanizma kasıtlıdır: Health Connect, kullanıcılara kimin ne okuduğu üzerinde ayrıntılı kontrol sağlamak için tasarlanmıştır. Ancak bu ayrıntı düzeyi, çoğu insanın varlığından haberdar olmadığı ekstra bir yapılandırma noktası oluşturur. Sonuç: kullanıcı 'çalışmayan' bir uygulama görür, oysa aslında yalnızca okuma izni eksiktir.",
        nl: "Het mechanisme is opzettelijk: Health Connect is ontworpen om gebruikers gedetailleerde controle te geven over wie wat leest. Maar die gedetailleerdheid creëert een extra configuratiepunt dat de meeste mensen niet weten dat het bestaat. Resultaat: de gebruiker ziet een app die 'niet werkt', terwijl hij eigenlijk gewoon een leestoestemming mist.",
        ja: "このメカニズムは意図的なものです。Health Connectは誰が何を読むかについてユーザーが細かく制御できるように設計されています。しかしその細かさが、ほとんどの人が存在を知らない追加の設定ポイントを生み出します。結果：ユーザーは「動かない」アプリを見ますが、実際には単に読み取り権限がないだけです。",
        ko: "이 메커니즘은 의도적입니다. Health Connect는 사용자가 누가 무엇을 읽는지 세밀하게 제어할 수 있도록 설계되었습니다. 하지만 그 세밀함이 대부분의 사람들이 존재하는지 모르는 추가 설정 지점을 만들어냅니다. 결과: 사용자는 '작동하지 않는' 앱을 보게 되지만, 실제로는 단순히 읽기 권한이 없는 것입니다.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "La soluzione passo per passo",
        en: "The step-by-step fix",
        es: "La solución paso a paso",
        de: "Die Schritt-für-Schritt-Lösung",
        pt: "A solução passo a passo",
        fr: "La solution étape par étape",
        pl: "Rozwiązanie krok po kroku",
        tr: "Adım adım çözüm",
        nl: "De stapsgewijze oplossing",
        ja: "ステップバイステップの解決策",
        ko: "단계별 해결 방법",
      },
    },
    {
      type: "list",
      ordered: true,
      items: {
        it: [
          "Apri l'app **Fitbit** sul telefono. Vai su **Impostazioni account** (icona profilo in alto a sinistra) → **Impostazioni app** → **Health Connect**. Qui trovi l'interruttore per abilitare la scrittura dei dati su Health Connect. Se è disattivato, abilitalo. Questo passaggio manca su quasi tutte le guide online.",
          "Apri **Health Connect** (la trovi nelle Impostazioni Android → Privacy → Health Connect, oppure cerca 'Health Connect' nel cassetto app). Vai su **Autorizzazioni app**.",
          "Trova l'app che non riceve i dati Fitbit (es. FitMesh Sync, o qualsiasi altra app che stai usando). Aprila e verifica che i tipi di dato che ti servono (passi, frequenza cardiaca, sonno, etc.) siano attivati in **Lettura**.",
          "Torna nella lista principale di **Autorizzazioni app** e cerca anche **Fitbit**. Verifica che Fitbit abbia il permesso di **Scrittura** per quei tipi di dato. Senza scrittura da parte di Fitbit, non c'è nulla da leggere.",
          "Se i permessi erano già tutti attivi ma i dati non arrivano ancora, prova a revocare e riattivare il permesso di lettura nell'app di destinazione. Su alcuni dispositivi il refresh dei permessi sblocca un'inizializzazione in sospeso.",
        ],
        en: [
          "Open the **Fitbit** app on your phone. Go to **Account Settings** (profile icon, top left) → **App Settings** → **Health Connect**. Here you'll find the toggle to enable writing data to Health Connect. If it's off, enable it. This step is missing from almost every guide online.",
          "Open **Health Connect** (find it in Android Settings → Privacy → Health Connect, or search 'Health Connect' in the app drawer). Go to **App permissions**.",
          "Find the app that isn't receiving Fitbit data (e.g. FitMesh Sync, or whatever app you're using). Open it and verify that the data types you need (steps, heart rate, sleep, etc.) are enabled for **Read**.",
          "Back in the main **App permissions** list, also find **Fitbit**. Verify that Fitbit has **Write** permission for those data types. Without Fitbit writing, there's nothing to read.",
          "If all permissions were already active but data still isn't showing, try revoking and re-enabling the read permission in the destination app. On some devices, refreshing permissions unblocks a stuck initialization.",
        ],
        es: [
          "Abre la app **Fitbit** en tu teléfono. Ve a **Ajustes de cuenta** (icono de perfil, arriba a la izquierda) → **Ajustes de la app** → **Health Connect**. Aquí encontrarás el interruptor para habilitar la escritura de datos en Health Connect. Si está desactivado, actívalo. Este paso falta en casi todas las guías en línea.",
          "Abre **Health Connect** (encuéntralo en Ajustes de Android → Privacidad → Health Connect, o busca 'Health Connect' en el cajón de apps). Ve a **Permisos de apps**.",
          "Encuentra la app que no está recibiendo los datos de Fitbit (por ejemplo, FitMesh Sync, o cualquier app que estés usando). Ábrela y verifica que los tipos de datos que necesitas (pasos, frecuencia cardíaca, sueño, etc.) estén activados en **Lectura**.",
          "Vuelve a la lista principal de **Permisos de apps** y busca también **Fitbit**. Verifica que Fitbit tenga permiso de **Escritura** para esos tipos de datos. Sin escritura por parte de Fitbit, no hay nada que leer.",
          "Si todos los permisos ya estaban activos pero los datos aún no aparecen, prueba a revocar y volver a activar el permiso de lectura en la app de destino. En algunos dispositivos, actualizar los permisos desbloquea una inicialización pendiente.",
        ],
        de: [
          "Öffne die **Fitbit**-App auf deinem Telefon. Gehe zu **Kontoeinstellungen** (Profilsymbol oben links) → **App-Einstellungen** → **Health Connect**. Hier findest du den Schalter zum Aktivieren der Datenschreibung in Health Connect. Wenn er deaktiviert ist, aktiviere ihn. Dieser Schritt fehlt in fast allen Online-Anleitungen.",
          "Öffne **Health Connect** (zu finden unter Android-Einstellungen → Datenschutz → Health Connect, oder suche 'Health Connect' im App-Drawer). Gehe zu **App-Berechtigungen**.",
          "Suche die App, die keine Fitbit-Daten empfängt (z. B. FitMesh Sync oder welche App du auch verwendest). Öffne sie und prüfe, ob die benötigten Datentypen (Schritte, Herzfrequenz, Schlaf usw.) für **Lesen** aktiviert sind.",
          "Gehe zurück zur **App-Berechtigungen**-Hauptliste und suche auch **Fitbit**. Prüfe, ob Fitbit die **Schreibberechtigung** für diese Datentypen hat. Ohne Schreibzugriff durch Fitbit gibt es nichts zu lesen.",
          "Wenn alle Berechtigungen bereits aktiv waren, die Daten aber immer noch nicht erscheinen, versuche die Leseberechtigung in der Ziel-App zu widerrufen und erneut zu aktivieren. Auf einigen Geräten entsperrt das Aktualisieren der Berechtigungen eine hängende Initialisierung.",
        ],
        pt: [
          "Abra o app **Fitbit** no seu telefone. Vá em **Configurações da conta** (ícone de perfil, canto superior esquerdo) → **Configurações do app** → **Health Connect**. Aqui você encontra o botão para ativar a gravação de dados no Health Connect. Se estiver desativado, ative-o. Esse passo está ausente em quase todos os guias online.",
          "Abra o **Health Connect** (encontre em Configurações do Android → Privacidade → Health Connect, ou pesquise 'Health Connect' na gaveta de apps). Vá em **Permissões de apps**.",
          "Encontre o app que não está recebendo os dados do Fitbit (por exemplo, FitMesh Sync, ou qualquer app que você esteja usando). Abra-o e verifique se os tipos de dados que você precisa (passos, frequência cardíaca, sono, etc.) estão ativados em **Leitura**.",
          "Volte à lista principal de **Permissões de apps** e procure também o **Fitbit**. Verifique se o Fitbit tem permissão de **Gravação** para esses tipos de dados. Sem a gravação pelo Fitbit, não há nada a ser lido.",
          "Se todas as permissões já estavam ativas mas os dados ainda não aparecem, tente revogar e reativar a permissão de leitura no app de destino. Em alguns dispositivos, atualizar as permissões desbloqueia uma inicialização pendente.",
        ],
        fr: [
          "Ouvrez l'application **Fitbit** sur votre téléphone. Allez dans **Paramètres du compte** (icône de profil en haut à gauche) → **Paramètres de l'application** → **Health Connect**. Vous y trouverez le bouton pour activer l'écriture des données dans Health Connect. S'il est désactivé, activez-le. Cette étape est absente de presque tous les guides en ligne.",
          "Ouvrez **Health Connect** (accessible dans Paramètres Android → Confidentialité → Health Connect, ou recherchez 'Health Connect' dans le tiroir d'applications). Allez dans **Autorisations des applications**.",
          "Trouvez l'application qui ne reçoit pas les données Fitbit (par exemple FitMesh Sync, ou l'application que vous utilisez). Ouvrez-la et vérifiez que les types de données dont vous avez besoin (pas, fréquence cardiaque, sommeil, etc.) sont activés en **Lecture**.",
          "Revenez à la liste principale des **Autorisations des applications** et recherchez également **Fitbit**. Vérifiez que Fitbit dispose de l'autorisation **Écriture** pour ces types de données. Sans écriture de la part de Fitbit, il n'y a rien à lire.",
          "Si toutes les autorisations étaient déjà actives mais que les données n'apparaissent toujours pas, essayez de révoquer puis de réactiver l'autorisation de lecture dans l'application de destination. Sur certains appareils, actualiser les autorisations débloque une initialisation bloquée.",
        ],
        pl: [
          "Otwórz aplikację **Fitbit** na telefonie. Przejdź do **Ustawień konta** (ikona profilu, lewy górny róg) → **Ustawienia aplikacji** → **Health Connect**. Znajdziesz tam przełącznik do włączenia zapisywania danych w Health Connect. Jeśli jest wyłączony, włącz go. Ten krok brakuje w prawie każdym poradniku online.",
          "Otwórz **Health Connect** (znajdziesz w Ustawieniach Androida → Prywatność → Health Connect lub wyszukaj 'Health Connect' w szufladzie aplikacji). Przejdź do **Uprawnień aplikacji**.",
          "Znajdź aplikację, która nie otrzymuje danych Fitbit (np. FitMesh Sync lub cokolwiek innego używasz). Otwórz ją i sprawdź, czy typy danych, których potrzebujesz (kroki, tętno, sen itp.), są włączone dla **Odczytu**.",
          "Wróć do głównej listy **Uprawnień aplikacji** i znajdź też **Fitbit**. Sprawdź, czy Fitbit ma uprawnienie **Zapisu** dla tych typów danych. Bez zapisu przez Fitbit nie ma nic do odczytu.",
          "Jeśli wszystkie uprawnienia były już aktywne, a dane nadal nie pojawiają się, spróbuj cofnąć i ponownie włączyć uprawnienie do odczytu w aplikacji docelowej. Na niektórych urządzeniach odświeżenie uprawnień odblokowuje zablokowaną inicjalizację.",
        ],
        tr: [
          "Telefonunuzda **Fitbit** uygulamasını açın. **Hesap Ayarları**'na gidin (sol üstteki profil simgesi) → **Uygulama Ayarları** → **Health Connect**. Burada Health Connect'e veri yazmayı etkinleştiren bir geçiş düğmesi bulacaksınız. Kapalıysa açın. Bu adım neredeyse hiçbir çevrimiçi kılavuzda yer almaz.",
          "**Health Connect**'i açın (Android Ayarları → Gizlilik → Health Connect'te bulabilir ya da uygulama çekmecesinde 'Health Connect' arayabilirsiniz). **Uygulama izinleri**'ne gidin.",
          "Fitbit verilerini almayan uygulamayı bulun (ör. FitMesh Sync ya da kullandığınız başka bir uygulama). Açın ve ihtiyacınız olan veri türlerinin (adımlar, kalp atış hızı, uyku vb.) **Okuma** için etkinleştirildiğini doğrulayın.",
          "**Uygulama izinleri** ana listesine dönün ve **Fitbit**'i de bulun. Fitbit'in o veri türleri için **Yazma** iznine sahip olduğunu doğrulayın. Fitbit yazmadan okunacak hiçbir şey yoktur.",
          "Tüm izinler zaten etkinse ancak veriler hala görünmüyorsa hedef uygulamadaki okuma iznini iptal edip yeniden etkinleştirmeyi deneyin. Bazı cihazlarda izinleri yenilemek takılı kalan bir başlatmayı çözebilir.",
        ],
        nl: [
          "Open de **Fitbit**-app op uw telefoon. Ga naar **Accountinstellingen** (profielpictogram, linksboven) → **App-instellingen** → **Health Connect**. Hier vindt u de schakelaar om schrijven naar Health Connect in te schakelen. Als deze uit staat, schakel hem in. Deze stap ontbreekt in bijna elke online gids.",
          "Open **Health Connect** (te vinden in Android-instellingen → Privacy → Health Connect, of zoek 'Health Connect' in de app-lade). Ga naar **App-toestemmingen**.",
          "Zoek de app die geen Fitbit-gegevens ontvangt (bijv. FitMesh Sync, of welke app u ook gebruikt). Open hem en controleer of de gewenste gegevenstypen (stappen, hartslag, slaap, etc.) zijn ingeschakeld voor **Lezen**.",
          "Ga terug naar de hoofdlijst van **App-toestemmingen** en zoek ook **Fitbit**. Controleer of Fitbit **Schrijf**-toestemming heeft voor die gegevenstypen. Zonder dat Fitbit schrijft, is er niets te lezen.",
          "Als alle toestemmingen al actief waren maar de gegevens nog steeds niet verschijnen, probeer dan de leestoestemming in de doelapp in te trekken en opnieuw in te schakelen. Op sommige apparaten ontgrendelt het vernieuwen van toestemmingen een vastgelopen initialisatie.",
        ],
        ja: [
          "スマートフォンで**Fitbit**アプリを開きます。**アカウント設定**（左上のプロフィールアイコン）→**アプリ設定**→**Health Connect**に進みます。ここでHealth Connectへのデータ書き込みを有効にする切り替えスイッチがあります。オフの場合は有効にしてください。このステップはほぼすべてのオンラインガイドに記載されていません。",
          "**Health Connect**を開きます（Android設定→プライバシー→Health Connect、またはアプリドロワーで「Health Connect」と検索）。**アプリの権限**に進みます。",
          "Fitbitデータを受信していないアプリ（例：FitMesh Sync、またはお使いのアプリ）を見つけます。開いて、必要なデータタイプ（歩数、心拍数、睡眠など）が**読み取り**で有効になっているか確認します。",
          "**アプリの権限**メインリストに戻り、**Fitbit**も確認します。Fitbitがそれらのデータタイプに対して**書き込み**権限を持っているか確認します。Fitbitが書き込まなければ、読み取るデータがありません。",
          "すべての権限がすでに有効だがデータがまだ表示されない場合は、宛先アプリの読み取り権限を取り消して再度有効にしてみてください。一部のデバイスでは権限を更新することで停止した初期化が解除されます。",
        ],
        ko: [
          "스마트폰에서 **Fitbit** 앱을 엽니다. **계정 설정**(왼쪽 상단 프로필 아이콘) → **앱 설정** → **Health Connect**로 이동합니다. 여기서 Health Connect에 데이터 쓰기를 활성화하는 토글을 찾을 수 있습니다. 꺼져 있으면 활성화하세요. 이 단계는 거의 모든 온라인 가이드에 빠져 있습니다.",
          "**Health Connect**를 엽니다(Android 설정 → 개인정보 보호 → Health Connect에서 찾거나 앱 서랍에서 'Health Connect' 검색). **앱 권한**으로 이동합니다.",
          "Fitbit 데이터를 받지 못하는 앱(예: FitMesh Sync 또는 사용 중인 앱)을 찾습니다. 열어서 필요한 데이터 유형(걸음 수, 심박수, 수면 등)이 **읽기**로 활성화되어 있는지 확인합니다.",
          "**앱 권한** 메인 목록으로 돌아가서 **Fitbit**도 찾습니다. Fitbit이 해당 데이터 유형에 대한 **쓰기** 권한을 갖고 있는지 확인합니다. Fitbit이 쓰지 않으면 읽을 데이터가 없습니다.",
          "모든 권한이 이미 활성화되어 있지만 데이터가 여전히 표시되지 않는다면, 대상 앱의 읽기 권한을 취소하고 다시 활성화해 보세요. 일부 기기에서는 권한을 새로 고치면 멈춰 있던 초기화가 해제됩니다.",
        ],
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Insidie comuni che bloccano la sincronizzazione",
        en: "Common gotchas that trip people up",
        es: "Errores comunes que bloquean la sincronización",
        de: "Häufige Stolperfallen bei der Synchronisierung",
        pt: "Armadilhas comuns que bloqueiam a sincronização",
        fr: "Erreurs fréquentes qui bloquent la synchronisation",
        pl: "Częste pułapki, na które warto uważać",
        tr: "Sık yapılan hatalar",
        nl: "Veelvoorkomende valkuilen die mensen struikelen",
        ja: "よくある落とし穴",
        ko: "사람들이 자주 걸리는 함정",
      },
    },
    {
      type: "list",
      items: {
        it: [
          "**Health Connect non sincronizza i dati storici.** Se autorizzi un'app oggi, vedrà solo i dati Fitbit scritti da quel momento in avanti. I dati del mese scorso, dell'anno scorso: non li vedrà mai via Health Connect. Questa è una scelta di design, non un bug. Se hai bisogno di dati storici, devi esportarli direttamente dall'app Fitbit (Impostazioni account → Esporta dati account).",
          "**La scrittura su Health Connect non è attiva di default in Fitbit.** A differenza di Samsung Health (che su molti dispositivi chiede di configurare Health Connect durante il setup), Fitbit richiede un'attivazione manuale esplicita nella sezione impostazioni. Se non l'hai mai toccata, è quasi certamente disattivata.",
          "**Il rapporto Fitbit-Google è complicato.** Google ha acquisito Fitbit nel 2021. Alcuni modelli Fitbit più vecchi scrivono su Google Fit ma non su Health Connect, dipende dalla versione del firmware. Se hai un Fitbit di vecchia generazione e non vedi l'opzione Health Connect nell'app, verifica che il firmware sia aggiornato. In alternativa, potrebbe non essere supportato.",
          "**La lettura da parte dell'app terza è un permesso separato da quello di scrittura di Fitbit.** Molti pensano: 'ho autorizzato Fitbit, quindi l'altra app deve vedere i dati'. No: i due permessi sono completamente indipendenti. Fitbit scrive, l'app terza legge, ma per leggere serve un permesso esplicito rilasciato all'app terza. Devono essere entrambi attivi.",
        ],
        en: [
          "**Health Connect does NOT retroactively sync data.** If you authorize an app today, it will only see Fitbit data written from that moment onwards. Last month's data, last year's data: it will never see it via Health Connect. This is a design choice, not a bug. If you need historical data, you must export it directly from the Fitbit app (Account Settings → Export Account Data).",
          "**Writing to Health Connect is not active by default in Fitbit.** Unlike Samsung Health (which on many devices asks you to configure Health Connect during setup), Fitbit requires an explicit manual activation in the app's settings section. If you've never touched it, it's almost certainly off.",
          "**The Fitbit-Google relationship is complicated.** Google acquired Fitbit in 2021. Some older Fitbit models write to Google Fit but not Health Connect, depending on firmware version. If you have an older Fitbit and don't see the Health Connect option in the app, verify that firmware is up to date. Alternatively, it may simply not be supported.",
          "**The third-party app's read permission is separate from Fitbit's write permission.** Many people think: 'I authorized Fitbit, so the other app must see the data.' No: the two permissions are completely independent. Fitbit writes, the third-party app reads, but reading requires an explicit permission granted to the third-party app. Both must be active.",
        ],
        es: [
          "**Health Connect NO sincroniza datos históricos.** Si autorizas una app hoy, solo verá los datos de Fitbit escritos a partir de ese momento. Los datos del mes pasado o del año pasado no los verá nunca a través de Health Connect. Es una decisión de diseño, no un error. Si necesitas datos históricos, debes exportarlos directamente desde la app Fitbit (Ajustes de cuenta → Exportar datos de la cuenta).",
          "**La escritura en Health Connect no está activa por defecto en Fitbit.** A diferencia de Samsung Health (que en muchos dispositivos pide configurar Health Connect durante la instalación), Fitbit requiere una activación manual explícita en la sección de ajustes de la app. Si nunca la has tocado, casi con certeza está desactivada.",
          "**La relación Fitbit-Google es complicada.** Google adquirió Fitbit en 2021. Algunos modelos más antiguos de Fitbit escriben en Google Fit pero no en Health Connect, según la versión del firmware. Si tienes un Fitbit de generación anterior y no ves la opción Health Connect en la app, verifica que el firmware esté actualizado. Si ya está actualizado y la opción no aparece, es posible que ese modelo no sea compatible.",
          "**El permiso de lectura de la app de terceros es independiente del permiso de escritura de Fitbit.** Muchos piensan: 'ya autoricé Fitbit, así que la otra app debería ver los datos'. No: los dos permisos son completamente independientes. Fitbit escribe, la app de terceros lee, pero para leer se necesita un permiso explícito concedido a esa app. Ambos deben estar activos.",
        ],
        de: [
          "**Health Connect synchronisiert KEINE historischen Daten.** Wenn du eine App heute autorisierst, sieht sie nur Fitbit-Daten, die ab diesem Zeitpunkt geschrieben wurden. Daten vom letzten Monat oder letzten Jahr werden nie über Health Connect sichtbar sein. Das ist eine Design-Entscheidung, kein Fehler. Wenn du historische Daten benötigst, musst du sie direkt aus der Fitbit-App exportieren (Kontoeinstellungen → Kontodaten exportieren).",
          "**Das Schreiben in Health Connect ist in Fitbit nicht standardmäßig aktiv.** Im Unterschied zu Samsung Health (das auf vielen Geräten während der Einrichtung zur Konfiguration von Health Connect auffordert) erfordert Fitbit eine explizite manuelle Aktivierung im App-Einstellungsbereich. Wenn du das noch nie angepasst hast, ist es mit großer Wahrscheinlichkeit deaktiviert.",
          "**Die Beziehung zwischen Fitbit und Google ist komplex.** Google hat Fitbit 2021 übernommen. Einige ältere Fitbit-Modelle schreiben in Google Fit, aber nicht in Health Connect, abhängig von der Firmware-Version. Wenn du ein älteres Fitbit hast und die Health Connect-Option in der App nicht siehst, prüfe ob die Firmware aktuell ist. Alternativ könnte das Modell schlicht nicht unterstützt werden.",
          "**Die Leseberechtigung der Drittanbieter-App ist unabhängig von Fitbits Schreibberechtigung.** Viele denken: 'Ich habe Fitbit autorisiert, also muss die andere App die Daten sehen können.' Nein: Die beiden Berechtigungen sind völlig unabhängig voneinander. Fitbit schreibt, die Drittanbieter-App liest, aber zum Lesen ist eine explizite Berechtigung erforderlich, die der Drittanbieter-App erteilt wurde. Beide müssen aktiv sein.",
        ],
        pt: [
          "**O Health Connect NÃO sincroniza dados históricos.** Se você autorizar um app hoje, ele verá apenas os dados do Fitbit gravados a partir desse momento. Os dados do mês passado ou do ano passado nunca serão vistos via Health Connect. Essa é uma escolha de design, não um erro. Se precisar de dados históricos, você deve exportá-los diretamente do app Fitbit (Configurações da conta → Exportar dados da conta).",
          "**A gravação no Health Connect não está ativa por padrão no Fitbit.** Ao contrário do Samsung Health (que em muitos dispositivos pede para configurar o Health Connect durante a configuração inicial), o Fitbit exige uma ativação manual explícita na seção de configurações do app. Se você nunca tocou nessa opção, ela quase certamente está desativada.",
          "**A relação Fitbit-Google é complexa.** O Google adquiriu o Fitbit em 2021. Alguns modelos mais antigos do Fitbit gravam no Google Fit, mas não no Health Connect, dependendo da versão do firmware. Se você tem um Fitbit mais antigo e não vê a opção Health Connect no app, verifique se o firmware está atualizado. Se já estiver atualizado e a opção não aparecer, o modelo pode simplesmente não ser compatível.",
          "**A permissão de leitura do app de terceiros é separada da permissão de gravação do Fitbit.** Muitas pessoas pensam: 'já autorizei o Fitbit, então o outro app deve ver os dados'. Não: as duas permissões são completamente independentes. O Fitbit grava, o app de terceiros lê, mas para ler é necessária uma permissão explícita concedida ao app de terceiros. Ambas precisam estar ativas.",
        ],
        fr: [
          "**Health Connect ne synchronise PAS les données historiques.** Si vous autorisez une application aujourd'hui, elle ne verra que les données Fitbit écrites à partir de ce moment. Les données du mois dernier ou de l'année dernière ne seront jamais visibles via Health Connect. C'est un choix de conception, pas un bug. Si vous avez besoin de données historiques, vous devez les exporter directement depuis l'application Fitbit (Paramètres du compte → Exporter les données du compte).",
          "**L'écriture dans Health Connect n'est pas active par défaut dans Fitbit.** Contrairement à Samsung Health (qui sur de nombreux appareils propose de configurer Health Connect lors de l'installation), Fitbit nécessite une activation manuelle explicite dans la section paramètres de l'application. Si vous n'avez jamais modifié ce réglage, il est presque certainement désactivé.",
          "**La relation Fitbit-Google est complexe.** Google a acquis Fitbit en 2021. Certains anciens modèles Fitbit écrivent dans Google Fit mais pas dans Health Connect, selon la version du firmware. Si vous avez un ancien Fitbit et ne voyez pas l'option Health Connect dans l'application, vérifiez que le firmware est à jour. Si le firmware est déjà à jour et que l'option n'apparaît pas, le modèle n'est peut-être tout simplement pas pris en charge.",
          "**L'autorisation de lecture de l'application tierce est indépendante de l'autorisation d'écriture de Fitbit.** Beaucoup pensent : 'j'ai autorisé Fitbit, donc l'autre application doit voir les données'. Non : les deux autorisations sont totalement indépendantes. Fitbit écrit, l'application tierce lit, mais la lecture nécessite une autorisation explicite accordée à l'application tierce. Les deux doivent être actives.",
        ],
        pl: [
          "**Health Connect NIE synchronizuje danych historycznych.** Jeśli autoryzujesz aplikację dziś, zobaczy tylko dane Fitbit zapisane od tego momentu. Dane z zeszłego miesiąca czy roku nigdy nie będą widoczne przez Health Connect. To wybór projektowy, nie błąd. Jeśli potrzebujesz danych historycznych, musisz je wyeksportować bezpośrednio z aplikacji Fitbit (Ustawienia konta → Eksportuj dane konta).",
          "**Zapis do Health Connect nie jest domyślnie aktywny w Fitbit.** W przeciwieństwie do Samsung Health (który na wielu urządzeniach prosi o konfigurację Health Connect podczas konfiguracji), Fitbit wymaga ręcznej aktywacji w sekcji ustawień aplikacji. Jeśli nigdy tego nie robiłeś, prawie na pewno jest wyłączone.",
          "**Relacja Fitbit-Google jest skomplikowana.** Google przejął Fitbit w 2021 roku. Niektóre starsze modele Fitbit zapisują do Google Fit, ale nie do Health Connect - zależy to od wersji firmware. Jeśli masz starszego Fitbita i nie widzisz opcji Health Connect w aplikacji, sprawdź, czy firmware jest aktualny. Alternatywnie model może po prostu nie być obsługiwany.",
          "**Uprawnienie do odczytu przez aplikację innego producenta jest odrębne od uprawnienia do zapisu Fitbit.** Wiele osób myśli: 'Autoryzowałem Fitbit, więc inna aplikacja powinna widzieć dane'. Nie: oba uprawnienia są całkowicie niezależne. Fitbit zapisuje, aplikacja innego producenta czyta, ale do odczytu potrzebne jest jawne uprawnienie przyznane tej aplikacji. Oba muszą być aktywne.",
        ],
        tr: [
          "**Health Connect geçmiş verileri GERİYE DÖNÜK olarak eşitlemez.** Bir uygulamayı bugün yetkilendirirseniz yalnızca o andan itibaren yazılan Fitbit verilerini görür. Geçen aydaki veya geçen yıldaki veriler Health Connect üzerinden hiçbir zaman görünmez. Bu bir tasarım tercihidir, hata değil. Geçmiş verilere ihtiyacınız varsa bunları doğrudan Fitbit uygulamasından dışa aktarmanız gerekir (Hesap Ayarları → Hesap Verilerini Dışa Aktar).",
          "**Fitbit'te Health Connect'e yazmak varsayılan olarak etkin değildir.** Samsung Health'in aksine (birçok cihazda kurulum sırasında Health Connect'i yapılandırmanızı ister), Fitbit uygulama ayarları bölümünde açık bir manuel etkinleştirme gerektirir. Bunu hiç yapmadıysanız neredeyse kesinlikle kapalıdır.",
          "**Fitbit-Google ilişkisi karmaşıktır.** Google, Fitbit'i 2021'de satın aldı. Bazı eski Fitbit modelleri firmware sürümüne bağlı olarak Health Connect yerine Google Fit'e yazar. Eski bir Fitbit'iniz varsa ve uygulamada Health Connect seçeneğini görmüyorsanız firmware'in güncel olup olmadığını kontrol edin. Güncel olmasına rağmen seçenek yoksa model desteklenmeyebilir.",
          "**Üçüncü taraf uygulamanın okuma izni, Fitbit'in yazma izninden bağımsızdır.** Pek çok kişi şöyle düşünür: 'Fitbit'i yetkilendirdim, dolayısıyla diğer uygulama verileri görebilir.' Hayır: iki izin tamamen bağımsızdır. Fitbit yazar, üçüncü taraf uygulama okur, ancak okumak için üçüncü taraf uygulamaya verilmiş açık bir izin gerekir. Her ikisi de etkin olmalıdır.",
        ],
        nl: [
          "**Health Connect synchroniseert gegevens NIET met terugwerkende kracht.** Als u een app vandaag autoriseert, ziet die alleen Fitbit-gegevens die vanaf dat moment zijn geschreven. Gegevens van vorige maand, van vorig jaar: die ziet hij nooit via Health Connect. Dit is een ontwerpkeuze, geen bug. Als u historische gegevens nodig heeft, moet u deze rechtstreeks vanuit de Fitbit-app exporteren (Accountinstellingen → Accountgegevens exporteren).",
          "**Schrijven naar Health Connect is standaard niet actief in Fitbit.** In tegenstelling tot Samsung Health (dat op veel apparaten vraagt om Health Connect te configureren tijdens de installatie), vereist Fitbit een expliciete handmatige activering in de app-instellingen. Als u dit nooit heeft aangeraakt, staat het vrijwel zeker uit.",
          "**De Fitbit-Google relatie is ingewikkeld.** Google heeft Fitbit in 2021 overgenomen. Sommige oudere Fitbit-modellen schrijven naar Google Fit maar niet naar Health Connect, afhankelijk van de firmwareversie. Als u een oudere Fitbit heeft en de Health Connect-optie in de app niet ziet, controleer dan of de firmware up-to-date is. Als dat het geval is en de optie er niet is, wordt het model mogelijk gewoon niet ondersteund.",
          "**De leestoestemming van de app van derden staat los van de schrijftoestemming van Fitbit.** Veel mensen denken: 'Ik heb Fitbit geautoriseerd, dus de andere app moet de gegevens zien.' Nee: de twee toestemmingen zijn volledig onafhankelijk. Fitbit schrijft, de app van derden leest, maar lezen vereist een expliciete toestemming die aan de app van derden is verleend. Beide moeten actief zijn.",
        ],
        ja: [
          "**Health Connectはデータをさかのぼって同期しません。** 今日アプリを承認すると、それ以降に書き込まれたFitbitデータのみが表示されます。先月や昨年のデータはHealth Connect経由では表示されません。これはバグではなく設計上の選択です。過去のデータが必要な場合はFitbitアプリから直接エクスポートする必要があります（アカウント設定→アカウントデータのエクスポート）。",
          "**FitbitではHealth Connectへの書き込みはデフォルトで有効になっていません。** Samsung Health（多くのデバイスでセットアップ時にHealth Connectの設定を求める）とは異なり、Fitbitはアプリ設定セクションで明示的な手動有効化が必要です。一度も触れたことがなければ、ほぼ確実にオフになっています。",
          "**Fitbit-Googleの関係は複雑です。** GoogleはFitbitを2021年に買収しました。一部の古いFitbitモデルはファームウェアバージョンによってHealth Connectではなく古いGoogle Fitに書き込みます。古いFitbitをお持ちでアプリにHealth Connectオプションが表示されない場合は、ファームウェアが最新かどうか確認してください。最新でもオプションがなければ、そのモデルは単純にサポートされていない可能性があります。",
          "**サードパーティアプリの読み取り権限はFitbitの書き込み権限とは別物です。** 多くの人が「Fitbitを承認したから他のアプリはデータを見られるはず」と思います。違います：二つの権限は完全に独立しています。Fitbitが書き込み、サードパーティアプリが読み取りますが、読み取りにはサードパーティアプリに付与された明示的な権限が必要です。両方が有効である必要があります。",
        ],
        ko: [
          "**Health Connect는 데이터를 소급하여 동기화하지 않습니다.** 오늘 앱을 승인하면 그 시점 이후에 기록된 Fitbit 데이터만 볼 수 있습니다. 지난달, 작년 데이터는 Health Connect를 통해서는 절대 볼 수 없습니다. 이것은 버그가 아닌 설계 선택입니다. 과거 데이터가 필요하다면 Fitbit 앱에서 직접 내보내야 합니다(계정 설정 → 계정 데이터 내보내기).",
          "**Fitbit에서 Health Connect에 쓰기는 기본적으로 활성화되어 있지 않습니다.** Samsung Health(많은 기기에서 설정 중 Health Connect 구성을 요청)와 달리, Fitbit은 앱 설정 섹션에서 명시적인 수동 활성화가 필요합니다. 한 번도 건드리지 않았다면 거의 확실히 꺼져 있습니다.",
          "**Fitbit-Google 관계는 복잡합니다.** Google은 2021년에 Fitbit을 인수했습니다. 일부 구형 Fitbit 모델은 펌웨어 버전에 따라 Health Connect가 아닌 Google Fit에 씁니다. 구형 Fitbit이 있고 앱에서 Health Connect 옵션이 보이지 않는다면 펌웨어가 최신인지 확인하세요. 최신임에도 옵션이 없다면 해당 모델이 지원되지 않을 수 있습니다.",
          "**서드파티 앱의 읽기 권한은 Fitbit의 쓰기 권한과 별개입니다.** 많은 사람들이 'Fitbit을 승인했으니 다른 앱도 데이터를 볼 수 있다'고 생각합니다. 아닙니다. 두 권한은 완전히 독립적입니다. Fitbit이 쓰고, 서드파티 앱이 읽지만, 읽기를 위해서는 서드파티 앱에 부여된 명시적인 권한이 필요합니다. 둘 다 활성화되어 있어야 합니다.",
        ],
      },
    },
    {
      type: "callout",
      variant: "tip",
      title: {
        it: "La mia opinione diretta",
        en: "My direct opinion",
        es: "Mi opinión directa",
        de: "Meine direkte Einschätzung",
        pt: "Minha opinião direta",
        fr: "Mon avis direct",
        pl: "Moja bezpośrednia opinia",
        tr: "Doğrudan görüşüm",
        nl: "Mijn directe mening",
        ja: "私の率直な意見",
        ko: "나의 직접적인 의견",
      },
      body: {
        it: "La maggior parte delle guide su questo problema dice 'reinstalla l'app' o 'riavvia il Bluetooth'. È sbagliato. Il problema è nei permessi di Health Connect nel 95% dei casi, e una volta che sai dove guardare ci vuole meno di 30 secondi per trovarlo. Non perdere tempo con passaggi drastici: controlla prima i permessi, poi eventualmente il resto.",
        en: "Most troubleshooting guides say 'reinstall the app' or 'restart Bluetooth.' That's wrong. The problem is in Health Connect permissions 95% of the time, and once you know where to look it takes less than 30 seconds to find it. Don't waste time on drastic steps: check permissions first, then everything else if needed.",
        es: "La mayoría de las guías sobre este problema dicen 'reinstala la app' o 'reinicia el Bluetooth'. Eso está mal. El problema está en los permisos de Health Connect en el 95% de los casos, y una vez que sabes dónde mirar, encontrarlo lleva menos de 30 segundos. No pierdas tiempo con pasos drásticos: revisa primero los permisos y, si es necesario, el resto después.",
        de: "Die meisten Anleitungen zur Fehlerbehebung empfehlen 'installiere die App neu' oder 'starte Bluetooth neu'. Das ist falsch. In 95 % der Fälle liegt das Problem an den Health Connect-Berechtigungen, und wenn du weißt, wo du suchen musst, findest du es in weniger als 30 Sekunden. Verschwende keine Zeit mit drastischen Maßnahmen: Überprüfe zuerst die Berechtigungen, dann bei Bedarf alles andere.",
        pt: "A maioria dos guias de solução de problemas diz 'reinstale o app' ou 'reinicie o Bluetooth'. Isso está errado. O problema está nas permissões do Health Connect em 95% dos casos, e quando você sabe onde procurar, leva menos de 30 segundos para encontrá-lo. Não perca tempo com passos drásticos: verifique as permissões primeiro, depois o resto se necessário.",
        fr: "La plupart des guides de dépannage conseillent de 'réinstaller l'application' ou de 'redémarrer le Bluetooth'. C'est une erreur. Le problème vient des autorisations Health Connect dans 95 % des cas, et une fois que vous savez où chercher, il faut moins de 30 secondes pour le trouver. Ne perdez pas de temps avec des étapes drastiques : vérifiez d'abord les autorisations, puis le reste si nécessaire.",
        pl: "Większość poradników dotyczących tego problemu mówi 'zainstaluj aplikację ponownie' lub 'uruchom Bluetooth ponownie'. To błąd. Problem leży w uprawnieniach Health Connect w 95% przypadków, a gdy już wiesz, gdzie szukać, znalezienie go zajmuje mniej niż 30 sekund. Nie trać czasu na drastyczne działania: najpierw sprawdź uprawnienia, potem ewentualnie resztę.",
        tr: "Sorun giderme kılavuzlarının çoğu 'uygulamayı yeniden yükle' veya 'Bluetooth'u yeniden başlat' der. Bu yanlış. Sorun %95 durumda Health Connect izinlerindedir ve nereye bakacağınızı öğrendikten sonra bulmak 30 saniyeden az sürer. Aşırı adımlara zaman harcamayın: önce izinleri kontrol edin, gerekirse diğerlerine bakın.",
        nl: "De meeste probleemoplossingsgidsen zeggen 'herinstalleer de app' of 'herstart Bluetooth.' Dat is verkeerd. Het probleem zit in Health Connect-toestemmingen in 95% van de gevallen, en als je eenmaal weet waar je moet kijken duurt het minder dan 30 seconden om het te vinden. Verspil geen tijd aan drastische stappen: controleer eerst de toestemmingen, dan al het andere indien nodig.",
        ja: "ほとんどのトラブルシューティングガイドは「アプリを再インストールする」または「Bluetoothを再起動する」と言います。それは間違いです。95%のケースでは問題はHealth Connectの権限にあり、どこを確認すればよいかわかれば30秒以内に見つかります。思い切った手段に時間を無駄にしないでください。まず権限を確認し、必要であれば他を確認しましょう。",
        ko: "대부분의 문제 해결 가이드는 '앱을 재설치하라' 또는 'Bluetooth를 재시작하라'고 합니다. 그것은 잘못된 것입니다. 95%의 경우 문제는 Health Connect 권한에 있으며, 어디를 봐야 하는지 알면 30초 안에 찾을 수 있습니다. 극단적인 단계에 시간을 낭비하지 마세요. 먼저 권한을 확인하고, 필요하다면 다른 것들을 확인하세요.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "In sintesi",
        en: "In summary",
        es: "En resumen",
        de: "Zusammenfassung",
        pt: "Em resumo",
        fr: "En résumé",
        pl: "Podsumowanie",
        tr: "Özet",
        nl: "Samenvatting",
        ja: "まとめ",
        ko: "요약",
      },
    },
    {
      type: "list",
      items: {
        it: [
          "Fitbit scrive i dati in Health Connect solo se lo abiliti manualmente: Fitbit app → Impostazioni → Health Connect → attiva la scrittura.",
          "L'app che vuoi usare deve avere il permesso di lettura in Health Connect, separato e indipendente da quello di Fitbit.",
          "Health Connect non sincronizza mai dati passati: solo dal momento dell'autorizzazione in avanti.",
          "Alcuni Fitbit di vecchia generazione scrivono su Google Fit, non su Health Connect. Aggiorna il firmware o controlla la compatibilità del tuo modello.",
        ],
        en: [
          "Fitbit writes data to Health Connect only if you enable it manually: Fitbit app → Settings → Health Connect → enable writing.",
          "The app you want to use needs its own read permission in Health Connect, separate and independent from Fitbit's permission.",
          "Health Connect never syncs past data: only from the moment of authorization onwards.",
          "Some older Fitbit models write to Google Fit, not Health Connect. Update the firmware or check your model's compatibility.",
        ],
        es: [
          "Fitbit escribe datos en Health Connect solo si lo habilitas manualmente: app Fitbit → Ajustes → Health Connect → activa la escritura.",
          "La app que quieres usar necesita su propio permiso de lectura en Health Connect, separado e independiente del permiso de Fitbit.",
          "Health Connect nunca sincroniza datos pasados: solo desde el momento de la autorización en adelante.",
          "Algunos modelos antiguos de Fitbit escriben en Google Fit, no en Health Connect. Actualiza el firmware o verifica la compatibilidad de tu modelo.",
        ],
        de: [
          "Fitbit schreibt Daten nur dann in Health Connect, wenn du es manuell aktivierst: Fitbit-App → Einstellungen → Health Connect → Schreibzugriff aktivieren.",
          "Die App, die du verwenden möchtest, benötigt eine eigene Leseberechtigung in Health Connect, unabhängig von der Fitbit-Berechtigung.",
          "Health Connect synchronisiert nie vergangene Daten: nur ab dem Zeitpunkt der Autorisierung.",
          "Einige ältere Fitbit-Modelle schreiben in Google Fit, nicht in Health Connect. Aktualisiere die Firmware oder prüfe die Kompatibilität deines Modells.",
        ],
        pt: [
          "O Fitbit grava dados no Health Connect apenas se você ativar manualmente: app Fitbit → Configurações → Health Connect → ativar gravação.",
          "O app que você quer usar precisa de sua própria permissão de leitura no Health Connect, separada e independente da permissão do Fitbit.",
          "O Health Connect nunca sincroniza dados passados: apenas a partir do momento da autorização.",
          "Alguns modelos mais antigos do Fitbit gravam no Google Fit, não no Health Connect. Atualize o firmware ou verifique a compatibilidade do seu modelo.",
        ],
        fr: [
          "Fitbit n'écrit des données dans Health Connect que si vous l'activez manuellement : application Fitbit → Paramètres → Health Connect → activer l'écriture.",
          "L'application que vous souhaitez utiliser doit disposer de sa propre autorisation de lecture dans Health Connect, indépendante de celle de Fitbit.",
          "Health Connect ne synchronise jamais les données passées : seulement à partir du moment de l'autorisation.",
          "Certains anciens modèles Fitbit écrivent dans Google Fit et non dans Health Connect. Mettez à jour le firmware ou vérifiez la compatibilité de votre modèle.",
        ],
        pl: [
          "Fitbit zapisuje dane do Health Connect tylko wtedy, gdy włączysz to ręcznie: aplikacja Fitbit → Ustawienia → Health Connect → włącz zapis.",
          "Aplikacja, której chcesz używać, potrzebuje własnego uprawnienia do odczytu w Health Connect, niezależnego od uprawnienia Fitbit.",
          "Health Connect nigdy nie synchronizuje danych z przeszłości: tylko od momentu udzielenia zgody.",
          "Niektóre starsze modele Fitbit zapisują do Google Fit, a nie do Health Connect. Zaktualizuj firmware lub sprawdź zgodność swojego modelu.",
        ],
        tr: [
          "Fitbit verileri Health Connect'e yalnızca manuel olarak etkinleştirirseniz yazar: Fitbit uygulaması → Ayarlar → Health Connect → yazmayı etkinleştir.",
          "Kullanmak istediğiniz uygulamanın Health Connect'te kendi okuma iznine ihtiyacı vardır; bu Fitbit izninden bağımsızdır.",
          "Health Connect geçmiş verileri hiçbir zaman eşitlemez: yalnızca yetkilendirme anından itibaren.",
          "Bazı eski Fitbit modelleri Health Connect yerine Google Fit'e yazar. Firmware'i güncelleyin veya modelinizin uyumluluğunu kontrol edin.",
        ],
        nl: [
          "Fitbit schrijft gegevens naar Health Connect alleen als u het handmatig inschakelt: Fitbit-app → Instellingen → Health Connect → schrijven inschakelen.",
          "De app die u wilt gebruiken heeft zijn eigen leestoestemming nodig in Health Connect, los en onafhankelijk van de toestemming van Fitbit.",
          "Health Connect synchroniseert nooit historische gegevens: alleen vanaf het moment van autorisatie.",
          "Sommige oudere Fitbit-modellen schrijven naar Google Fit, niet naar Health Connect. Update de firmware of controleer de compatibiliteit van uw model.",
        ],
        ja: [
          "FitbitがHealth Connectにデータを書き込むには手動で有効にする必要があります：Fitbitアプリ→設定→Health Connect→書き込みを有効にする。",
          "使用したいアプリはHealth ConnectでFitbitの権限とは別に独自の読み取り権限が必要です。",
          "Health Connectは過去のデータを同期しません：認証した時点以降のデータのみです。",
          "一部の古いFitbitモデルはHealth ConnectではなくGoogle Fitに書き込みます。ファームウェアを更新するか、お使いのモデルの互換性を確認してください。",
        ],
        ko: [
          "Fitbit은 수동으로 활성화해야만 Health Connect에 데이터를 씁니다: Fitbit 앱 → 설정 → Health Connect → 쓰기 활성화.",
          "사용하려는 앱은 Health Connect에서 Fitbit의 권한과 별개로 독립적인 읽기 권한이 필요합니다.",
          "Health Connect는 과거 데이터를 동기화하지 않습니다: 권한 부여 시점 이후의 데이터만 해당됩니다.",
          "일부 구형 Fitbit 모델은 Health Connect가 아닌 Google Fit에 씁니다. 펌웨어를 업데이트하거나 모델의 호환성을 확인하세요.",
        ],
      },
    },
    {
      type: "cta",
      title: {
        it: "Vuoi vedere i dati Fitbit in una dashboard web, senza configurazioni complesse?",
        en: "Want to see your Fitbit data in a web dashboard, without complex configuration?",
        es: "¿Quieres ver tus datos de Fitbit en un panel web, sin configuraciones complejas?",
        de: "Möchtest du deine Fitbit-Daten in einem Web-Dashboard sehen, ohne komplexe Konfiguration?",
        pt: "Quer ver seus dados do Fitbit em um painel web, sem configurações complexas?",
        fr: "Vous souhaitez voir vos données Fitbit dans un tableau de bord web, sans configuration complexe ?",
        pl: "Chcesz zobaczyć dane Fitbit w panelu web bez skomplikowanej konfiguracji?",
        tr: "Fitbit verilerinizi karmaşık yapılandırma olmadan bir web panelinde görmek ister misiniz?",
        nl: "Wilt u uw Fitbit-gegevens zien in een webdashboard, zonder complexe configuratie?",
        ja: "複雑な設定なしにFitbitデータをウェブダッシュボードで確認したいですか？",
        ko: "복잡한 설정 없이 웹 대시보드에서 Fitbit 데이터를 보고 싶으신가요?",
      },
      body: {
        it: "FitMesh Sync si integra con Fitbit via la sua API ufficiale e mostra passi, frequenza cardiaca, sonno e allenamenti in una dashboard accessibile da browser. Nessun problema di permessi Health Connect: la connessione Fitbit è diretta e guidata passo passo.",
        en: "FitMesh Sync integrates with Fitbit via its official API and shows steps, heart rate, sleep, and workouts in a browser-accessible dashboard. No Health Connect permission headaches: the Fitbit connection is direct and guided step by step.",
        es: "FitMesh Sync se integra con Fitbit a través de su API oficial y muestra pasos, frecuencia cardíaca, sueño y entrenamientos en un panel accesible desde el navegador. Sin problemas de permisos en Health Connect: la conexión con Fitbit es directa y guiada paso a paso.",
        de: "FitMesh Sync verbindet sich mit Fitbit über die offizielle API und zeigt Schritte, Herzfrequenz, Schlaf und Trainings in einer browser-zugänglichen Dashboard an. Keine Probleme mit Health Connect-Berechtigungen: Die Fitbit-Verbindung ist direkt und wird Schritt für Schritt geführt.",
        pt: "FitMesh Sync integra com o Fitbit via API oficial e exibe passos, frequência cardíaca, sono e treinos em um painel acessível pelo navegador. Sem problemas de permissões do Health Connect: a conexão com o Fitbit é direta e guiada passo a passo.",
        fr: "FitMesh Sync s'intègre à Fitbit via son API officielle et affiche pas, fréquence cardiaque, sommeil et séances d'entraînement dans un tableau de bord accessible depuis un navigateur. Aucun problème d'autorisation Health Connect : la connexion Fitbit est directe et guidée étape par étape.",
        pl: "FitMesh Sync integruje się z Fitbit przez oficjalne API i wyświetla kroki, tętno, sen i treningi w panelu dostępnym z przeglądarki. Żadnych problemów z uprawnieniami Health Connect: połączenie z Fitbit jest bezpośrednie i prowadzone krok po kroku.",
        tr: "FitMesh Sync, Fitbit ile resmi API üzerinden entegre olur ve adımları, kalp atış hızını, uykuyu ve antrenmanları tarayıcıdan erişilebilen bir panelde gösterir. Health Connect izin sorunları yok: Fitbit bağlantısı doğrudan ve adım adım rehberli.",
        nl: "FitMesh Sync integreert met Fitbit via de officiële API en toont stappen, hartslag, slaap en trainingen in een dashboard toegankelijk via de browser. Geen gedoe met Health Connect-toestemmingen: de Fitbit-verbinding is direct en stap voor stap begeleid.",
        ja: "FitMesh Syncは公式APIを通じてFitbitと連携し、ブラウザからアクセスできるダッシュボードで歩数、心拍数、睡眠、ワークアウトを表示します。Health Connectの権限問題はありません：Fitbitの接続は直接的でステップバイステップでガイドされます。",
        ko: "FitMesh Sync는 공식 API를 통해 Fitbit과 연동되며 브라우저에서 접근 가능한 대시보드에서 걸음 수, 심박수, 수면, 운동을 표시합니다. Health Connect 권한 문제 없음: Fitbit 연결은 직접적이고 단계별로 안내됩니다.",
      },
      ctaLabel: {
        it: "Scopri le integrazioni FitMesh →",
        en: "Explore FitMesh integrations →",
        es: "Descubre las integraciones de FitMesh →",
        de: "FitMesh-Integrationen entdecken →",
        pt: "Explore as integrações do FitMesh →",
        fr: "Découvrir les intégrations FitMesh →",
        pl: "Odkryj integracje FitMesh →",
        tr: "FitMesh entegrasyonlarını keşfet →",
        nl: "Ontdek FitMesh-integraties →",
        ja: "FitMeshの連携機能を見る →",
        ko: "FitMesh 연동 살펴보기 →",
      },
      ctaHref: {
        it: "/it/integrations",
        en: "/en/integrations",
        pl: "/pl/integrations",
        tr: "/tr/integrations",
        nl: "/nl/integrations",
        ja: "/ja/integrations",
        ko: "/ko/integrations",
      },
    },
  ],
  faq: [
    {
      q: {
        it: "Perché Fitbit non appare in Health Connect come app autorizzata?",
        en: "Why doesn't Fitbit appear in Health Connect as an authorized app?",
        es: "¿Por qué Fitbit no aparece en Health Connect como app autorizada?",
        de: "Warum erscheint Fitbit in Health Connect nicht als autorisierte App?",
        pt: "Por que o Fitbit não aparece no Health Connect como app autorizado?",
        fr: "Pourquoi Fitbit n'apparaît-il pas dans Health Connect comme application autorisée ?",
        pl: "Dlaczego Fitbit nie pojawia się w Health Connect jako autoryzowana aplikacja?",
        tr: "Neden Fitbit, Health Connect'te yetkili uygulama olarak görünmüyor?",
        nl: "Waarom verschijnt Fitbit niet als een geautoriseerde app in Health Connect?",
        ja: "なぜFitbitはHealth Connectで承認済みアプリとして表示されないのですか？",
        ko: "왜 Fitbit이 Health Connect에서 승인된 앱으로 표시되지 않나요?",
      },
      a: {
        it: "Fitbit non si registra automaticamente in Health Connect al momento dell'installazione. Devi andare in Fitbit → Impostazioni account → Impostazioni app → Health Connect e avviare tu il processo di autorizzazione. Solo dopo quel passaggio Fitbit apparirà nella lista di Health Connect.",
        en: "Fitbit doesn't automatically register in Health Connect when installed. You need to go to Fitbit → Account Settings → App Settings → Health Connect and initiate the authorization process yourself. Only after that step will Fitbit appear in Health Connect's list.",
        es: "Fitbit no se registra automáticamente en Health Connect al instalarse. Debes ir a Fitbit → Ajustes de cuenta → Ajustes de la app → Health Connect e iniciar tú el proceso de autorización. Solo después de ese paso aparecerá Fitbit en la lista de Health Connect.",
        de: "Fitbit registriert sich bei der Installation nicht automatisch in Health Connect. Du musst zu Fitbit → Kontoeinstellungen → App-Einstellungen → Health Connect gehen und den Autorisierungsprozess selbst starten. Erst nach diesem Schritt erscheint Fitbit in der Health Connect-Liste.",
        pt: "O Fitbit não se registra automaticamente no Health Connect no momento da instalação. Você precisa ir em Fitbit → Configurações da conta → Configurações do app → Health Connect e iniciar você mesmo o processo de autorização. Só depois desse passo o Fitbit aparecerá na lista do Health Connect.",
        fr: "Fitbit ne s'enregistre pas automatiquement dans Health Connect lors de l'installation. Vous devez aller dans Fitbit → Paramètres du compte → Paramètres de l'application → Health Connect et lancer vous-même le processus d'autorisation. Ce n'est qu'après cette étape que Fitbit apparaîtra dans la liste de Health Connect.",
        pl: "Fitbit nie rejestruje się automatycznie w Health Connect po instalacji. Musisz przejść do Fitbit → Ustawienia konta → Ustawienia aplikacji → Health Connect i samodzielnie rozpocząć proces autoryzacji. Dopiero po tym kroku Fitbit pojawi się na liście Health Connect.",
        tr: "Fitbit, kurulduğunda Health Connect'e otomatik olarak kaydolmaz. Fitbit → Hesap Ayarları → Uygulama Ayarları → Health Connect'e gitmeniz ve yetkilendirme sürecini kendiniz başlatmanız gerekir. Yalnızca bu adımdan sonra Fitbit, Health Connect listesinde görünür.",
        nl: "Fitbit registreert zich niet automatisch in Health Connect bij installatie. U moet naar Fitbit → Accountinstellingen → App-instellingen → Health Connect gaan en het autorisatieproces zelf starten. Pas na die stap verschijnt Fitbit in de lijst van Health Connect.",
        ja: "FitbitはインストールされてもHealth Connectに自動的に登録されません。Fitbit→アカウント設定→アプリ設定→Health Connectに進み、自分で承認プロセスを開始する必要があります。そのステップの後にのみ、FitbitはHealth Connectのリストに表示されます。",
        ko: "Fitbit은 설치 시 Health Connect에 자동으로 등록되지 않습니다. Fitbit → 계정 설정 → 앱 설정 → Health Connect로 이동하여 직접 승인 프로세스를 시작해야 합니다. 그 단계 이후에만 Fitbit이 Health Connect 목록에 표시됩니다.",
      },
    },
    {
      q: {
        it: "Posso recuperare i dati Fitbit storici dopo aver configurato Health Connect?",
        en: "Can I recover historical Fitbit data after setting up Health Connect?",
        es: "¿Puedo recuperar datos históricos de Fitbit después de configurar Health Connect?",
        de: "Kann ich historische Fitbit-Daten nach der Einrichtung von Health Connect abrufen?",
        pt: "Posso recuperar dados históricos do Fitbit depois de configurar o Health Connect?",
        fr: "Puis-je récupérer les données Fitbit historiques après avoir configuré Health Connect ?",
        pl: "Czy mogę odzyskać historyczne dane Fitbit po skonfigurowaniu Health Connect?",
        tr: "Health Connect'i kurduktan sonra geçmiş Fitbit verilerini kurtarabilir miyim?",
        nl: "Kan ik historische Fitbit-gegevens terughalen nadat ik Health Connect heb ingesteld?",
        ja: "Health Connectを設定した後、過去のFitbitデータを取得できますか？",
        ko: "Health Connect를 설정한 후 과거 Fitbit 데이터를 복구할 수 있나요?",
      },
      a: {
        it: "No, non via Health Connect. Per design, Health Connect non importa dati precedenti all'autorizzazione. Per accedere ai dati storici devi usare la funzione di esportazione di Fitbit (Impostazioni account → Esporta dati account), che genera un archivio con tutti i dati storici in formato CSV/JSON.",
        en: "No, not via Health Connect. By design, Health Connect doesn't import data that predates the authorization. To access historical data you need to use Fitbit's export feature (Account Settings → Export Account Data), which generates an archive with all historical data in CSV/JSON format.",
        es: "No, no a través de Health Connect. Por diseño, Health Connect no importa datos anteriores a la autorización. Para acceder a los datos históricos debes usar la función de exportación de Fitbit (Ajustes de cuenta → Exportar datos de la cuenta), que genera un archivo con todos los datos históricos en formato CSV/JSON.",
        de: "Nein, nicht über Health Connect. Per Design importiert Health Connect keine Daten, die vor der Autorisierung liegen. Um auf historische Daten zuzugreifen, musst du die Exportfunktion von Fitbit verwenden (Kontoeinstellungen → Kontodaten exportieren), die ein Archiv mit allen historischen Daten im CSV/JSON-Format erstellt.",
        pt: "Não, não via Health Connect. Por design, o Health Connect não importa dados anteriores à autorização. Para acessar dados históricos, você precisa usar a função de exportação do Fitbit (Configurações da conta → Exportar dados da conta), que gera um arquivo com todos os dados históricos em formato CSV/JSON.",
        fr: "Non, pas via Health Connect. Par conception, Health Connect n'importe pas les données antérieures à l'autorisation. Pour accéder aux données historiques, vous devez utiliser la fonction d'exportation de Fitbit (Paramètres du compte → Exporter les données du compte), qui génère une archive avec toutes les données historiques au format CSV/JSON.",
        pl: "Nie, nie przez Health Connect. Z założenia Health Connect nie importuje danych sprzed momentu autoryzacji. Aby uzyskać dostęp do danych historycznych, musisz skorzystać z funkcji eksportu Fitbit (Ustawienia konta → Eksportuj dane konta), która generuje archiwum ze wszystkimi danymi historycznymi w formacie CSV/JSON.",
        tr: "Hayır, Health Connect üzerinden değil. Health Connect tasarımı gereği yetkilendirmeden önceki verileri içe aktarmaz. Geçmiş verilere erişmek için Fitbit'in dışa aktarma özelliğini kullanmanız gerekir (Hesap Ayarları → Hesap Verilerini Dışa Aktar); bu özellik tüm geçmiş verileri CSV/JSON formatında bir arşiv olarak oluşturur.",
        nl: "Nee, niet via Health Connect. Health Connect importeert per ontwerp geen gegevens die dateren van voor de autorisatie. Om toegang te krijgen tot historische gegevens moet u de exportfunctie van Fitbit gebruiken (Accountinstellingen → Accountgegevens exporteren), die een archief genereert met alle historische gegevens in CSV/JSON-formaat.",
        ja: "いいえ、Health Connect経由ではできません。設計上、Health Connectは承認前のデータをインポートしません。過去のデータにアクセスするにはFitbitのエクスポート機能を使用する必要があります（アカウント設定→アカウントデータのエクスポート）。これにより、すべての過去データがCSV/JSON形式のアーカイブとして生成されます。",
        ko: "아니요, Health Connect를 통해서는 불가능합니다. Health Connect는 설계상 승인 이전 데이터를 가져오지 않습니다. 과거 데이터에 접근하려면 Fitbit의 내보내기 기능을 사용해야 합니다(계정 설정 → 계정 데이터 내보내기). 이를 통해 모든 과거 데이터가 CSV/JSON 형식의 아카이브로 생성됩니다.",
      },
    },
    {
      q: {
        it: "Il mio Fitbit sincronizza con Google Fit ma non con Health Connect: perché?",
        en: "My Fitbit syncs with Google Fit but not Health Connect: why?",
        es: "Mi Fitbit sincroniza con Google Fit pero no con Health Connect: ¿por qué?",
        de: "Mein Fitbit synchronisiert mit Google Fit, aber nicht mit Health Connect: warum?",
        pt: "Meu Fitbit sincroniza com o Google Fit, mas não com o Health Connect: por quê?",
        fr: "Mon Fitbit se synchronise avec Google Fit mais pas avec Health Connect : pourquoi ?",
        pl: "Mój Fitbit synchronizuje się z Google Fit, ale nie z Health Connect: dlaczego?",
        tr: "Fitbit'im Google Fit ile eşitleniyor ama Health Connect ile eşitlenmiyor: neden?",
        nl: "Mijn Fitbit synchroniseert met Google Fit maar niet met Health Connect: waarom?",
        ja: "私のFitbitはGoogle Fitとは同期するのにHealth Connectとは同期しません：なぜですか？",
        ko: "제 Fitbit은 Google Fit과는 동기화되는데 Health Connect와는 동기화되지 않습니다: 왜 그런가요?",
      },
      a: {
        it: "Alcuni modelli Fitbit più vecchi hanno il supporto per Google Fit ma non per Health Connect, per via del firmware. Google Fit è la vecchia API (ora deprecata); Health Connect è quella nuova. Se il tuo modello non supporta Health Connect, aggiorna il firmware dall'app Fitbit e controlla se l'opzione compare. Se il firmware è già aggiornato e l'opzione non c'è, il modello potrebbe non essere supportato: in quel caso la connessione diretta via API Fitbit (come quella di FitMesh Sync) è un'alternativa valida.",
        en: "Some older Fitbit models support Google Fit but not Health Connect, due to firmware. Google Fit is the old API (now deprecated); Health Connect is the new one. If your model doesn't support Health Connect, update the firmware from the Fitbit app and check if the option appears. If firmware is already updated and the option isn't there, the model may not be supported: in that case a direct API connection via Fitbit's API (like FitMesh Sync uses) is a valid alternative.",
        es: "Algunos modelos más antiguos de Fitbit tienen soporte para Google Fit pero no para Health Connect, por limitaciones del firmware. Google Fit es la API antigua (ahora obsoleta); Health Connect es la nueva. Si tu modelo no es compatible con Health Connect, actualiza el firmware desde la app Fitbit y comprueba si aparece la opción. Si el firmware ya está actualizado y la opción no aparece, es posible que ese modelo no sea compatible: en ese caso, la conexión directa mediante la API de Fitbit (como la que usa FitMesh Sync) es una alternativa válida.",
        de: "Einige ältere Fitbit-Modelle unterstützen Google Fit, aber nicht Health Connect, aufgrund der Firmware. Google Fit ist die alte API (jetzt veraltet); Health Connect ist die neue. Wenn dein Modell Health Connect nicht unterstützt, aktualisiere die Firmware über die Fitbit-App und prüfe, ob die Option erscheint. Wenn die Firmware bereits aktuell ist und die Option fehlt, wird das Modell möglicherweise nicht unterstützt: In diesem Fall ist eine direkte Verbindung über die Fitbit-API (wie sie FitMesh Sync verwendet) eine valide Alternative.",
        pt: "Alguns modelos mais antigos do Fitbit têm suporte para o Google Fit, mas não para o Health Connect, devido ao firmware. O Google Fit é a API antiga (agora descontinuada); o Health Connect é a nova. Se o seu modelo não é compatível com o Health Connect, atualize o firmware pelo app Fitbit e verifique se a opção aparece. Se o firmware já estiver atualizado e a opção não aparecer, o modelo pode não ser compatível: nesse caso, a conexão direta via API do Fitbit (como a que o FitMesh Sync usa) é uma alternativa válida.",
        fr: "Certains anciens modèles Fitbit prennent en charge Google Fit mais pas Health Connect, en raison du firmware. Google Fit est l'ancienne API (désormais obsolète) ; Health Connect est la nouvelle. Si votre modèle ne prend pas en charge Health Connect, mettez à jour le firmware depuis l'application Fitbit et vérifiez si l'option apparaît. Si le firmware est déjà à jour et que l'option n'est pas disponible, le modèle n'est peut-être pas pris en charge. Dans ce cas, une connexion directe via l'API Fitbit (comme celle qu'utilise FitMesh Sync) est une alternative valable.",
        pl: "Niektóre starsze modele Fitbit obsługują Google Fit, ale nie Health Connect ze względu na firmware. Google Fit to stare API (teraz wycofane), Health Connect to nowe. Jeśli Twój model nie obsługuje Health Connect, zaktualizuj firmware z aplikacji Fitbit i sprawdź, czy pojawi się opcja. Jeśli firmware jest już aktualny, a opcji nie ma, model może po prostu nie być obsługiwany - w takim przypadku bezpośrednie połączenie przez API Fitbit (jak to, którego używa FitMesh Sync) jest prawidłową alternatywą.",
        tr: "Bazı eski Fitbit modelleri firmware nedeniyle Google Fit'i destekler ama Health Connect'i desteklemez. Google Fit eski API'dir (artık kullanımdan kaldırılıyor); Health Connect yeni olandır. Modeliniz Health Connect'i desteklemiyorsa Fitbit uygulamasından firmware'i güncelleyin ve seçeneğin görünüp görünmediğini kontrol edin. Firmware güncel olmasına rağmen seçenek yoksa model desteklenmeyebilir: bu durumda Fitbit API'si üzerinden doğrudan bağlantı (FitMesh Sync'in kullandığı gibi) geçerli bir alternatiftir.",
        nl: "Sommige oudere Fitbit-modellen ondersteunen Google Fit maar niet Health Connect, vanwege de firmware. Google Fit is de oude API (nu verouderd); Health Connect is de nieuwe. Als uw model Health Connect niet ondersteunt, update dan de firmware via de Fitbit-app en kijk of de optie verschijnt. Als de firmware al up-to-date is en de optie er niet is, wordt het model mogelijk gewoon niet ondersteund: in dat geval is een directe API-verbinding via Fitbit's API (zoals FitMesh Sync gebruikt) een geldig alternatief.",
        ja: "一部の古いFitbitモデルはファームウェアの理由でGoogle Fitをサポートしていますが、Health Connectはサポートしていません。Google Fitは古いAPI（現在は廃止予定）であり、Health Connectは新しいものです。お使いのモデルがHealth Connectをサポートしていない場合は、FitbitアプリからファームウェアをアップデートしてオプションΩが表示されるか確認してください。ファームウェアが既に最新でオプションがなければ、そのモデルはサポートされていない可能性があります。その場合、Fitbit APIを介した直接接続（FitMesh Syncが使用するような）が有効な代替手段です。",
        ko: "일부 구형 Fitbit 모델은 펌웨어 문제로 Google Fit은 지원하지만 Health Connect는 지원하지 않습니다. Google Fit은 이전 API(현재 지원 중단 예정)이고, Health Connect는 새로운 것입니다. 모델이 Health Connect를 지원하지 않는다면 Fitbit 앱에서 펌웨어를 업데이트하고 옵션이 나타나는지 확인하세요. 펌웨어가 이미 최신인데도 옵션이 없다면 해당 모델이 지원되지 않을 수 있습니다. 이 경우 Fitbit API를 통한 직접 연결(FitMesh Sync가 사용하는 방식)이 유효한 대안입니다.",
      },
    },
    {
      q: {
        it: "Devo tenere installata l'app Fitbit per la sincronizzazione?",
        en: "Do I need to keep the Fitbit app installed for syncing?",
        es: "¿Necesito tener instalada la app Fitbit para la sincronización?",
        de: "Muss ich die Fitbit-App installiert haben, damit die Synchronisierung funktioniert?",
        pt: "Preciso manter o app Fitbit instalado para a sincronização?",
        fr: "Dois-je garder l'application Fitbit installée pour la synchronisation ?",
        pl: "Czy muszę mieć zainstalowaną aplikację Fitbit, aby synchronizacja działała?",
        tr: "Senkronizasyon çalışması için Fitbit uygulamasının kurulu olması gerekiyor mu?",
        nl: "Moet ik de Fitbit-app geinstalleerd houden voor synchronisatie?",
        ja: "同期のためにFitbitアプリをインストールしたままにしておく必要がありますか？",
        ko: "동기화를 위해 Fitbit 앱을 설치된 상태로 유지해야 하나요?",
      },
      a: {
        it: "Se usi Health Connect come canale, sì: l'app Fitbit deve essere installata e attiva, perché è lei che scrive i dati su Health Connect. Se invece usi un'app che si connette direttamente all'API Fitbit (come FitMesh Sync), la dipendenza cambia: in quel caso l'app comunica con i server Fitbit via OAuth, indipendentemente dall'app companion installata sul telefono.",
        en: "If you use Health Connect as the channel, yes: the Fitbit app must be installed and active, because it's the one writing data to Health Connect. If instead you use an app that connects directly to the Fitbit API (like FitMesh Sync), the dependency changes: in that case the app communicates with Fitbit's servers via OAuth, independently of the companion app installed on the phone.",
        es: "Si usas Health Connect como canal, sí: la app Fitbit debe estar instalada y activa, porque es ella quien escribe los datos en Health Connect. Si en cambio usas una app que se conecta directamente a la API de Fitbit (como FitMesh Sync), la dependencia cambia: en ese caso la app se comunica con los servidores de Fitbit mediante OAuth, con independencia de la app companion instalada en el teléfono.",
        de: "Wenn du Health Connect als Kanal verwendest, ja: Die Fitbit-App muss installiert und aktiv sein, weil sie die Daten in Health Connect schreibt. Wenn du stattdessen eine App verwendest, die sich direkt mit der Fitbit-API verbindet (wie FitMesh Sync), ändert sich die Abhängigkeit: In diesem Fall kommuniziert die App über OAuth mit den Fitbit-Servern, unabhängig von der Companion-App, die auf dem Telefon installiert ist.",
        pt: "Se você usar o Health Connect como canal, sim: o app Fitbit precisa estar instalado e ativo, pois é ele que grava os dados no Health Connect. Se você usar um app que se conecta diretamente à API do Fitbit (como o FitMesh Sync), a dependência muda: nesse caso, o app se comunica com os servidores do Fitbit via OAuth, independentemente do app companion instalado no telefone.",
        fr: "Si vous utilisez Health Connect comme canal, oui : l'application Fitbit doit être installée et active, car c'est elle qui écrit les données dans Health Connect. Si vous utilisez à la place une application qui se connecte directement à l'API Fitbit (comme FitMesh Sync), la dépendance change : dans ce cas, l'application communique avec les serveurs Fitbit via OAuth, indépendamment de l'application companion installée sur le téléphone.",
        pl: "Jeśli używasz Health Connect jako kanału, tak: aplikacja Fitbit musi być zainstalowana i aktywna, ponieważ to ona zapisuje dane do Health Connect. Jeśli natomiast używasz aplikacji łączącej się bezpośrednio z API Fitbit (jak FitMesh Sync), zależność się zmienia: w takim przypadku aplikacja komunikuje się z serwerami Fitbit przez OAuth, niezależnie od aplikacji towarzyszącej zainstalowanej na telefonie.",
        tr: "Health Connect'i kanal olarak kullanıyorsanız evet: Fitbit uygulamasının kurulu ve etkin olması gerekir, çünkü verileri Health Connect'e yazan odur. Bunun yerine doğrudan Fitbit API'sine bağlanan bir uygulama kullanıyorsanız (FitMesh Sync gibi), bağımlılık değişir: bu durumda uygulama, telefona kurulu yardımcı uygulamadan bağımsız olarak OAuth üzerinden Fitbit sunucularıyla iletişim kurar.",
        nl: "Als u Health Connect als kanaal gebruikt, ja: de Fitbit-app moet geinstalleerd en actief zijn, omdat het degene is die gegevens naar Health Connect schrijft. Als u in plaats daarvan een app gebruikt die direct verbinding maakt met de Fitbit API (zoals FitMesh Sync), verandert de afhankelijkheid: in dat geval communiceert de app via OAuth met Fitbit's servers, onafhankelijk van de companion-app op de telefoon.",
        ja: "Health Connectをチャネルとして使用する場合、はい：FitbitアプリはHealth Connectにデータを書き込むものなので、インストールされてアクティブである必要があります。代わりにFitbit APIに直接接続するアプリ（FitMesh Syncなど）を使用する場合は、依存関係が変わります。その場合、アプリは電話にインストールされたコンパニオンアプリとは独立して、OAuthを通じてFitbitのサーバーと通信します。",
        ko: "Health Connect를 채널로 사용한다면, 예: Fitbit 앱은 Health Connect에 데이터를 쓰는 주체이므로 설치되어 있고 활성화되어 있어야 합니다. 대신 Fitbit API에 직접 연결하는 앱(FitMesh Sync 등)을 사용한다면 의존성이 바뀝니다. 그 경우 앱은 전화에 설치된 컴패니언 앱과 독립적으로 OAuth를 통해 Fitbit 서버와 통신합니다.",
      },
    },
  ],
  related: [
    "come-funziona-health-connect",
    "health-connect-not-syncing",
    "esportare-dati-fitbit-google",
  ],
  brandsMentioned: ["Fitbit", "Google", "Samsung"],
  ldType: "BlogPosting",
};
