import type { BlogPost } from "../types";

export const post: BlogPost = {
  slug: "fitmesh-arriva-su-iphone",
  category: "ecosystem",
  publishedAt: "2026-06-12",
  updatedAt: "2026-06-12",
  readMinutes: 6,
  tldr: {
    it: [
      "FitMesh Sync è ora in beta TestFlight su iPhone: login Google o Apple, lettura Apple Health/HealthKit, sync cloud, anello Colmi via Bluetooth. Uscita App Store imminente.",
      "Un solo account funziona su Android e iPhone insieme: la dashboard è identica su entrambi i telefoni, i dati vengono dallo stesso cloud EU.",
      "Feature di punta: il ponte di scrittura Apple Salute (opt-in). I dati del tuo smartwatch Android o anello smart arrivano via cloud FitMesh e vengono scritti in Apple Salute, senza duplicati.",
      "Chi ha due telefoni (es. Android + iPhone) vede il sonno dell'anello e i passi del watch direttamente dentro l'app Apple Salute/Fitness.",
      "Dati in cloud EU, GDPR, zero vendita a terzi. Il ponte è opt-in: se Apple Salute ha già quei dati, FitMesh non li riscrive. Niente doppioni.",
    ],
    en: [
      "FitMesh Sync is now in TestFlight beta on iPhone: Google or Apple login, Apple Health/HealthKit reading, cloud sync, Colmi ring via Bluetooth. App Store launch imminent.",
      "One account works across Android and iPhone: the dashboard is identical on both phones, data comes from the same EU cloud.",
      "Flagship feature: the Apple Health write bridge (opt-in). Data from your Android smartwatch or smart ring arrives via FitMesh cloud and gets written into Apple Health, with no duplicates.",
      "Users with two phones (e.g. Android + iPhone) see ring sleep and watch steps directly inside the Apple Health/Fitness app.",
      "EU cloud, GDPR, zero third-party data sales. The bridge is opt-in: if Apple Health already has that data, FitMesh won't rewrite it. No duplicates.",
    ],
    es: [
      "FitMesh Sync ya está en beta TestFlight en iPhone: inicio de sesión con Google o Apple, lectura de Apple Health/HealthKit, sincronización en la nube, anillo Colmi vía Bluetooth. Lanzamiento en App Store inminente.",
      "Una sola cuenta funciona en Android e iPhone a la vez: el panel es idéntico en ambos teléfonos y los datos provienen de la misma nube EU.",
      "Función estrella: el puente de escritura a Apple Salud (opt-in). Los datos de tu smartwatch Android o anillo inteligente llegan a través de la nube de FitMesh y se escriben en Apple Salud, sin duplicados.",
      "Si tienes dos teléfonos (por ejemplo, Android + iPhone), verás el sueño del anillo y los pasos del reloj directamente dentro de la app Apple Salud/Fitness.",
      "Datos en nube EU, GDPR, cero venta a terceros. El puente es opt-in: si Apple Salud ya tiene esos datos, FitMesh no los vuelve a escribir. Sin duplicados.",
    ],
    de: [
      "FitMesh Sync ist jetzt in der TestFlight-Beta auf dem iPhone verfügbar: Anmeldung mit Google oder Apple, Lesen von Apple Health/HealthKit, Cloud-Synchronisierung, Colmi-Ring per Bluetooth. App-Store-Launch steht kurz bevor.",
      "Ein einziges Konto funktioniert auf Android und iPhone gleichzeitig: Das Dashboard ist auf beiden Geräten identisch, die Daten stammen aus derselben EU-Cloud.",
      "Highlight-Feature: die Schreibbrücke zu Apple Health (opt-in). Daten deines Android-Smartwatchs oder Smart-Rings kommen über die FitMesh-Cloud und werden ohne Duplikate in Apple Health geschrieben.",
      "Wer zwei Smartphones nutzt (z. B. Android + iPhone), sieht Schlaf des Rings und Schritte der Uhr direkt in der Apple Health/Fitness-App.",
      "EU-Cloud, DSGVO, keine Datenweitergabe an Dritte. Die Brücke ist opt-in: Hat Apple Health diese Daten bereits, überschreibt FitMesh sie nicht. Keine Duplikate.",
    ],
    pt: [
      "FitMesh Sync está agora em beta no TestFlight para iPhone: login com Google ou Apple, leitura do Apple Health/HealthKit, sincronização na nuvem, anel Colmi via Bluetooth. Lançamento na App Store iminente.",
      "Uma única conta funciona em Android e iPhone ao mesmo tempo: o painel é idêntico nos dois celulares e os dados vêm da mesma nuvem EU.",
      "Funcionalidade principal: a ponte de escrita para o Apple Health (opt-in). Os dados do seu smartwatch Android ou anel inteligente chegam via nuvem FitMesh e são gravados no Apple Health, sem duplicatas.",
      "Quem tem dois celulares (ex.: Android + iPhone) vê o sono do anel e os passos do smartwatch diretamente no app Apple Health/Fitness.",
      "Nuvem EU, LGPD/GDPR, zero venda de dados a terceiros. A ponte é opt-in: se o Apple Health já tiver esses dados, FitMesh não os reescreve. Sem duplicatas.",
    ],
    fr: [
      "FitMesh Sync est maintenant en bêta TestFlight sur iPhone : connexion Google ou Apple, lecture Apple Health/HealthKit, synchronisation cloud, bague Colmi connectée via Bluetooth. Lancement sur l'App Store imminent.",
      "Un seul compte fonctionne sur Android et iPhone en même temps : le tableau de bord est identique sur les deux téléphones, les données proviennent du même cloud EU.",
      "Fonctionnalité phare : le pont d'écriture vers Apple Health (opt-in). Les données de votre montre connectée Android ou bague connectée arrivent via le cloud FitMesh et sont écrites dans Apple Health, sans doublons.",
      "Les utilisateurs avec deux téléphones (ex. Android + iPhone) voient le sommeil de la bague et les pas de la montre directement dans l'app Apple Health/Fitness.",
      "Cloud EU, RGPD, zéro vente de données à des tiers. Le pont est opt-in : si Apple Health possède déjà ces données, FitMesh ne les réécrit pas. Aucun doublon.",
    ],
  },
  primaryKeyword: {
    it: "fitmesh sync iphone",
    en: "fitmesh sync iphone",
    es: "fitmesh sync iphone",
  },
  secondaryKeywords: {
    it: [
      "fitmesh ios beta",
      "app salute iphone smartwatch android",
      "sincronizzare smartwatch android apple salute",
      "ponte apple salute wearable android",
      "dashboard salute iphone",
    ],
    en: [
      "fitmesh ios beta",
      "apple health android smartwatch sync",
      "write android data to apple health",
      "apple health bridge wearable",
      "health dashboard iphone",
    ],
  },
  metaDescription: {
    it: "FitMesh Sync arriva su iPhone: beta TestFlight attiva, App Store imminente. Un account, Android + iPhone insieme. Feature esclusiva: ponte di scrittura Apple Salute per i dati del tuo wearable Android.",
    en: "FitMesh Sync arrives on iPhone: TestFlight beta active, App Store launch imminent. One account, Android + iPhone together. Flagship feature: Apple Health write bridge for your Android wearable data.",
    es: "FitMesh Sync llega a iPhone: beta TestFlight activa, lanzamiento en App Store inminente. Una cuenta, Android + iPhone juntos. Función exclusiva: puente de escritura a Apple Salud para los datos de tu wearable Android.",
    de: "FitMesh Sync ist jetzt auf dem iPhone: TestFlight-Beta aktiv, App-Store-Launch steht bevor. Ein Konto für Android und iPhone. Exklusives Feature: Schreibbrücke zu Apple Health für deine Android-Wearable-Daten.",
    pt: "FitMesh Sync chega ao iPhone: beta TestFlight ativa, lançamento na App Store iminente. Uma conta, Android + iPhone juntos. Funcionalidade exclusiva: ponte de escrita para o Apple Health com dados do seu wearable Android.",
    fr: "FitMesh Sync arrive sur iPhone : bêta TestFlight active, lancement App Store imminent. Un compte, Android + iPhone ensemble. Fonctionnalité exclusive : pont d'écriture vers Apple Health pour vos données wearable Android.",
  },
  hero: {
    kicker: {
      it: "Annuncio",
      en: "Announcement",
      es: "Anuncio",
      de: "Ankündigung",
      pt: "Anúncio",
      fr: "Annonce",
    },
    title: {
      it: "FitMesh Sync arriva su iPhone",
      en: "FitMesh Sync arrives on iPhone",
      es: "FitMesh Sync llega a iPhone",
      de: "FitMesh Sync ist jetzt auf dem iPhone",
      pt: "FitMesh Sync chega ao iPhone",
      fr: "FitMesh Sync arrive sur iPhone",
    },
    subtitle: {
      it: "Dopo mesi di sviluppo, l'app iOS è in beta TestFlight e in submission su App Store. Un account, Android e iPhone insieme. E una feature nuova: i dati del tuo wearable Android scritti direttamente in Apple Salute.",
      en: "After months of development, the iOS app is in TestFlight beta and in App Store submission. One account, Android and iPhone together. And a new feature: your Android wearable data written directly into Apple Health.",
      es: "Después de meses de desarrollo, la app para iOS está en beta TestFlight y en proceso de revisión en App Store. Una cuenta, Android e iPhone juntos. Y una función nueva: los datos de tu wearable Android escritos directamente en Apple Salud.",
      de: "Nach monatelanger Entwicklung ist die iOS-App in der TestFlight-Beta und in der App-Store-Einreichung. Ein Konto, Android und iPhone gemeinsam. Und ein neues Feature: deine Android-Wearable-Daten direkt in Apple Health geschrieben.",
      pt: "Após meses de desenvolvimento, o app iOS está na beta do TestFlight e em análise na App Store. Uma conta, Android e iPhone juntos. E uma nova funcionalidade: seus dados de wearable Android gravados diretamente no Apple Health.",
      fr: "Après des mois de développement, l'app iOS est en bêta TestFlight et en cours de soumission sur l'App Store. Un compte, Android et iPhone ensemble. Et une nouvelle fonctionnalité : vos données wearable Android écrites directement dans Apple Health.",
    },
  },
  body: [
    {
      type: "paragraph",
      text: {
        it: "Oggi, 12 giugno 2026, FitMesh Sync funziona su iPhone. L'app è in beta TestFlight, in submission su App Store, e già testata sul campo con login Google e Apple, lettura completa di Apple Health, sync cloud e connessione BLE all'anello Colmi. Non è una demo: è l'app reale, con tutte le funzionalità che già conosci dalla versione Android.",
        en: "Today, June 12 2026, FitMesh Sync works on iPhone. The app is in TestFlight beta, in App Store submission, and already field-tested with Google and Apple login, full Apple Health reading, cloud sync and BLE connection to the Colmi ring. This isn't a demo: it's the real app, with all the features you already know from the Android version.",
        es: "Hoy, 12 de junio de 2026, FitMesh Sync funciona en iPhone. La app está en beta TestFlight, en proceso de revisión en App Store, y ya probada en campo con inicio de sesión Google y Apple, lectura completa de Apple Health, sincronización en la nube y conexión BLE al anillo Colmi. No es una demo: es la app real, con todas las funciones que ya conoces de la versión Android.",
        de: "Heute, am 12. Juni 2026, funktioniert FitMesh Sync auf dem iPhone. Die App ist in der TestFlight-Beta, in der App-Store-Einreichung, und bereits im Praxistest mit Google- und Apple-Anmeldung, vollständiger Apple-Health-Lese-Integration, Cloud-Synchronisierung und BLE-Verbindung zum Colmi-Ring. Das ist keine Demo: Es ist die echte App, mit allen Funktionen, die du bereits aus der Android-Version kennst.",
        pt: "Hoje, 12 de junho de 2026, FitMesh Sync funciona no iPhone. O app está na beta do TestFlight, em análise na App Store, e já testado em campo com login Google e Apple, leitura completa do Apple Health, sincronização na nuvem e conexão BLE ao anel Colmi. Não é uma demonstração: é o app real, com todas as funcionalidades que você já conhece da versão Android.",
        fr: "Aujourd'hui, 12 juin 2026, FitMesh Sync fonctionne sur iPhone. L'app est en bêta TestFlight, en cours de soumission sur l'App Store, et déjà testée sur le terrain avec connexion Google et Apple, lecture complète d'Apple Health, synchronisation cloud et connexion BLE à la bague Colmi. Ce n'est pas une démo : c'est la vraie app, avec toutes les fonctionnalités que vous connaissez déjà depuis la version Android.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Cosa funziona oggi in beta",
        en: "What works today in beta",
        es: "Qué funciona hoy en la beta",
        de: "Was in der Beta heute schon funktioniert",
        pt: "O que funciona hoje na beta",
        fr: "Ce qui fonctionne aujourd'hui en bêta",
      },
    },
    {
      type: "list",
      items: {
        it: [
          "**Login Google e Sign in with Apple**: stesso account che usi su Android, zero doppioni.",
          "**Lettura Apple Health / HealthKit**: passi, frequenza cardiaca, sonno con fasi, SpO₂, calorie, distanza. Tutto quello che il tuo iPhone o Apple Watch scrive in Apple Salute è visibile in FitMesh.",
          "**Sync cloud EU**: i dati vengono sincronizzati sullo stesso server che serve l'app Android (datacenter EU, GDPR).",
          "**Anello Colmi via Bluetooth**: se hai un anello smart Colmi R02/R03, l'app iOS lo legge via BLE diretto come fa quella Android.",
          "**Dashboard unificata**: la stessa interfaccia che conosci su Android, con trend giornalieri, settimana in review, confronto multi-sorgente.",
          "**Ponte di scrittura Apple Salute** (opt-in): i dati degli altri device collegati al tuo account FitMesh vengono scritti in Apple Salute. Dettaglio completo nella sezione dedicata.",
        ],
        en: [
          "**Google login and Sign in with Apple**: same account you use on Android, zero duplicates.",
          "**Apple Health / HealthKit reading**: steps, heart rate, sleep with stages, SpO₂, calories, distance. Everything your iPhone or Apple Watch writes to Apple Health is visible in FitMesh.",
          "**EU cloud sync**: data is synced to the same server serving the Android app (EU datacenters, GDPR).",
          "**Colmi ring via Bluetooth**: if you have a Colmi R02/R03 smart ring, the iOS app reads it via direct BLE like the Android version does.",
          "**Unified dashboard**: the same interface you know from Android, with daily trends, week-in-review, multi-source comparison.",
          "**Apple Health write bridge** (opt-in): data from other devices connected to your FitMesh account gets written into Apple Health. Full details in the dedicated section.",
        ],
        es: [
          "**Inicio de sesión con Google e Iniciar sesión con Apple**: la misma cuenta que usas en Android, sin duplicados.",
          "**Lectura de Apple Health / HealthKit**: pasos, frecuencia cardíaca, sueño con fases, SpO₂, calorías, distancia. Todo lo que tu iPhone o Apple Watch escribe en Apple Salud es visible en FitMesh.",
          "**Sincronización en nube EU**: los datos se sincronizan en el mismo servidor que usa la app Android (centros de datos EU, GDPR).",
          "**Anillo Colmi vía Bluetooth**: si tienes un anillo inteligente Colmi R02/R03, la app para iOS lo lee mediante BLE directo, igual que la versión Android.",
          "**Panel unificado**: la misma interfaz que conoces en Android, con tendencias diarias, resumen semanal y comparación entre varias fuentes.",
          "**Puente de escritura a Apple Salud** (opt-in): los datos de los demás dispositivos conectados a tu cuenta de FitMesh se escriben en Apple Salud. Todos los detalles en la sección dedicada.",
        ],
        de: [
          "**Google-Anmeldung und Sign in with Apple**: dasselbe Konto, das du auf Android nutzt, ohne Duplikate.",
          "**Apple Health / HealthKit lesen**: Schritte, Herzfrequenz, Schlaf mit Schlafphasen, SpO₂, Kalorien, Distanz. Alles, was dein iPhone oder Apple Watch in Apple Health schreibt, ist in FitMesh sichtbar.",
          "**EU-Cloud-Synchronisierung**: Daten werden mit demselben Server synchronisiert, der die Android-App bedient (EU-Rechenzentren, DSGVO).",
          "**Colmi-Ring per Bluetooth**: Hast du einen Colmi R02/R03 Smart-Ring, liest die iOS-App ihn per direktem BLE, genau wie die Android-Version.",
          "**Einheitliches Dashboard**: dieselbe Benutzeroberfläche, die du von Android kennst, mit täglichen Trends, Wochenrückblick und Mehrquellen-Vergleich.",
          "**Schreibbrücke zu Apple Health** (opt-in): Daten anderer Geräte, die mit deinem FitMesh-Konto verbunden sind, werden in Apple Health geschrieben. Vollständige Details im entsprechenden Abschnitt.",
        ],
        pt: [
          "**Login com Google e Sign in with Apple**: a mesma conta que você usa no Android, sem duplicatas.",
          "**Leitura do Apple Health / HealthKit**: passos, frequência cardíaca, sono com fases, SpO₂, calorias, distância. Tudo o que seu iPhone ou Apple Watch grava no Apple Health fica visível no FitMesh.",
          "**Sincronização na nuvem EU**: os dados são sincronizados no mesmo servidor que serve o app Android (datacenters EU, LGPD/GDPR).",
          "**Anel Colmi via Bluetooth**: se você tem um anel inteligente Colmi R02/R03, o app iOS o lê via BLE direto, assim como a versão Android.",
          "**Painel unificado**: a mesma interface que você conhece no Android, com tendências diárias, revisão semanal e comparação entre múltiplas fontes.",
          "**Ponte de escrita para o Apple Health** (opt-in): os dados de outros dispositivos conectados à sua conta FitMesh são gravados no Apple Health. Detalhes completos na seção dedicada.",
        ],
        fr: [
          "**Connexion Google et Sign in with Apple** : le même compte que vous utilisez sur Android, sans doublons.",
          "**Lecture Apple Health / HealthKit** : pas, fréquence cardiaque, sommeil avec phases, SpO₂, calories, distance. Tout ce que votre iPhone ou Apple Watch écrit dans Apple Health est visible dans FitMesh.",
          "**Synchronisation cloud EU** : les données sont synchronisées sur le même serveur qui sert l'app Android (datacenters EU, RGPD).",
          "**Bague Colmi connectée via Bluetooth** : si vous avez une bague connectée Colmi R02/R03, l'app iOS la lit via BLE direct, comme la version Android.",
          "**Tableau de bord unifié** : la même interface que vous connaissez sur Android, avec tendances quotidiennes, bilan de la semaine et comparaison multi-sources.",
          "**Pont d'écriture vers Apple Health** (opt-in) : les données des autres appareils connectés à votre compte FitMesh sont écrites dans Apple Health. Détails complets dans la section dédiée.",
        ],
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Un account, Android e iPhone insieme",
        en: "One account, Android and iPhone together",
        es: "Una cuenta, Android e iPhone juntos",
        de: "Ein Konto, Android und iPhone gemeinsam",
        pt: "Uma conta, Android e iPhone juntos",
        fr: "Un compte, Android et iPhone ensemble",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "La cosa che più mi piaceva risolvere era questa: hai due telefoni, una dashboard. Accedi con lo stesso account su Android e su iPhone: i dati di tutti i device collegati (Galaxy Watch, anello Colmi, Apple Watch, qualsiasi wearable che scrivi su Health Connect o Apple Health) confluiscono in un'unica dashboard, accessibile da entrambi i telefoni e da qualsiasi browser web.",
        en: "The thing I most wanted to solve was this: you have two phones, one dashboard. Sign in with the same account on Android and iPhone: data from all connected devices (Galaxy Watch, Colmi ring, Apple Watch, any wearable writing to Health Connect or Apple Health) feeds into one unified dashboard, accessible from both phones and any web browser.",
        es: "Lo que más quería resolver era esto: tienes dos teléfonos, un solo panel. Inicia sesión con la misma cuenta en Android e iPhone: los datos de todos los dispositivos conectados (Galaxy Watch, anillo Colmi, Apple Watch, cualquier wearable que escriba en Health Connect o Apple Health) se reúnen en un único panel, accesible desde ambos teléfonos y desde cualquier navegador web.",
        de: "Das Problem, das ich am dringendsten lösen wollte, war dieses: Du hast zwei Smartphones, aber ein einziges Dashboard. Melde dich mit demselben Konto auf Android und iPhone an: Die Daten aller verbundenen Geräte (Galaxy Watch, Colmi-Ring, Apple Watch, jedes Wearable, das in Health Connect oder Apple Health schreibt) fließen in ein einheitliches Dashboard ein, das von beiden Smartphones und jedem Webbrowser aus erreichbar ist.",
        pt: "O problema que eu mais queria resolver era este: você tem dois celulares, mas um único painel. Entre com a mesma conta no Android e no iPhone: os dados de todos os dispositivos conectados (Galaxy Watch, anel Colmi, Apple Watch, qualquer wearable que grave no Health Connect ou no Apple Health) se reúnem em um único painel, acessível nos dois celulares e em qualquer navegador web.",
        fr: "Le problème que je voulais le plus résoudre était celui-ci : vous avez deux téléphones, mais un seul tableau de bord. Connectez-vous avec le même compte sur Android et iPhone : les données de tous les appareils connectés (Galaxy Watch, bague Colmi, Apple Watch, tout wearable qui écrit dans Health Connect ou Apple Health) convergent dans un tableau de bord unifié, accessible depuis les deux téléphones et depuis n'importe quel navigateur web.",
      },
    },
    {
      type: "callout",
      variant: "info",
      title: {
        it: "Come funziona il cross-device",
        en: "How cross-device works",
        es: "Cómo funciona el uso entre dispositivos",
        de: "Wie das Geräteübergreifende funktioniert",
        pt: "Como funciona o uso entre dispositivos",
        fr: "Comment fonctionne le multi-appareils",
      },
      body: {
        it: "Ogni device scrive i propri dati sul cloud FitMesh (EU). La dashboard li legge tutti, mostra i dati da tutte le sorgenti senza sommare due volte la stessa attività, e ti mostra un unico flusso coerente. Non importa da quale telefono apri l'app: vedi sempre lo stesso dataset.",
        en: "Each device writes its data to the FitMesh EU cloud. The dashboard reads all of them, shows data from all sources without double-counting the same activity, and shows a single coherent stream. It doesn't matter which phone you open the app on: you always see the same dataset.",
        es: "Cada dispositivo escribe sus datos en la nube EU de FitMesh. El panel los lee todos, muestra los datos de todas las fuentes sin contar dos veces la misma actividad, y te presenta un único flujo coherente. No importa desde qué teléfono abras la app: siempre ves el mismo conjunto de datos.",
        de: "Jedes Gerät schreibt seine Daten in die FitMesh-EU-Cloud. Das Dashboard liest alle Daten, zeigt sie aus allen Quellen an, ohne dieselbe Aktivität doppelt zu zählen, und präsentiert einen einzigen kohärenten Datenstrom. Egal von welchem Smartphone du die App öffnest: Du siehst immer denselben Datensatz.",
        pt: "Cada dispositivo grava seus dados na nuvem EU do FitMesh. O painel lê todos eles, exibe os dados de todas as fontes sem contar a mesma atividade duas vezes e mostra um único fluxo coerente. Não importa de qual celular você abre o app: você sempre vê o mesmo conjunto de dados.",
        fr: "Chaque appareil écrit ses données dans le cloud EU FitMesh. Le tableau de bord les lit tous, affiche les données de toutes les sources sans comptabiliser deux fois la même activité, et vous présente un flux unique et cohérent. Peu importe depuis quel téléphone vous ouvrez l'app : vous voyez toujours le même jeu de données.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Il ponte di scrittura Apple Salute: i dati del tuo wearable Android dentro Apple Health",
        en: "The Apple Health write bridge: your Android wearable data inside Apple Health",
        es: "El puente de escritura a Apple Salud: los datos de tu wearable Android dentro de Apple Health",
        de: "Die Schreibbrücke zu Apple Health: deine Android-Wearable-Daten in Apple Health",
        pt: "A ponte de escrita para o Apple Health: seus dados de wearable Android dentro do Apple Health",
        fr: "Le pont d'écriture vers Apple Health : vos données wearable Android dans Apple Health",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Questa è la feature che ho trovato più utile in test. Se hai un Galaxy Watch o un anello smart accoppiato con il telefono Android, e apri l'app Salute sull'iPhone, quei dati non ci sono. Il ponte di scrittura Apple Salute risolve questo: i dati raccolti dagli altri device del tuo account FitMesh (smartwatch Android, anello Colmi, qualsiasi sorgente già collegata) arrivano via cloud e vengono scritti in Apple Salute, opt-in.",
        en: "This is the feature I found most useful in testing. If you have a Galaxy Watch or smart ring paired with your Android phone, and open the Health app on iPhone, those data aren't there. The Apple Health write bridge solves this: data collected from other devices on your FitMesh account (Android smartwatch, Colmi ring, any already-connected source) arrives via cloud and gets written into Apple Health, opt-in.",
        es: "Esta es la función que encontré más útil durante las pruebas. Si tienes un Galaxy Watch o un anillo inteligente vinculado a tu teléfono Android y abres la app Salud en el iPhone, esos datos no aparecen. El puente de escritura a Apple Salud resuelve esto: los datos recogidos por los demás dispositivos de tu cuenta FitMesh (smartwatch Android, anillo Colmi, cualquier fuente ya conectada) llegan a través de la nube y se escriben en Apple Salud, de forma opt-in.",
        de: "Das ist die Funktion, die ich im Test am nützlichsten fand. Hast du einen Galaxy Watch oder Smart-Ring, der mit deinem Android-Smartphone gekoppelt ist, und öffnest dann die Health-App auf dem iPhone, fehlen diese Daten. Die Schreibbrücke zu Apple Health löst das: Daten, die von anderen Geräten deines FitMesh-Kontos gesammelt wurden (Android-Smartwatch, Colmi-Ring, jede bereits verbundene Quelle), kommen über die Cloud und werden opt-in in Apple Health geschrieben.",
        pt: "Esta é a funcionalidade que achei mais útil nos testes. Se você tem um Galaxy Watch ou um anel inteligente pareado com o celular Android e abre o app Saúde no iPhone, esses dados simplesmente não aparecem. A ponte de escrita para o Apple Health resolve isso: os dados coletados pelos outros dispositivos da sua conta FitMesh (smartwatch Android, anel Colmi, qualquer fonte já conectada) chegam via nuvem e são gravados no Apple Health, de forma opt-in.",
        fr: "C'est la fonctionnalité que j'ai trouvée la plus utile lors des tests. Si vous avez un Galaxy Watch ou une bague connectée associée à votre téléphone Android, et que vous ouvrez l'app Santé sur iPhone, ces données n'y sont pas. Le pont d'écriture vers Apple Health résout ce problème : les données collectées par les autres appareils de votre compte FitMesh (montre connectée Android, bague Colmi, toute source déjà connectée) arrivent via le cloud et sont écrites dans Apple Health, en mode opt-in.",
      },
    },
    {
      type: "list",
      items: {
        it: [
          "**Sonno con fasi complete**: profondo, leggero, REM. Non solo la durata totale, ma le fasi dettagliate del tuo anello o watch Android, visibili in Apple Salute come se fossero stati registrati dall'iPhone.",
          "**Passi e attività**: i passi del Galaxy Watch o del wearable Android finiscono nei tuoi totali Apple Fitness senza che tu debba fare nulla.",
          "**Zero duplicati**: se Apple Salute ha già qualcosa per quell'orario (da Apple Watch o qualsiasi altra app), FitMesh non lo tocca.",
          "**Completamente opt-in**: si attiva dalle impostazioni iOS di FitMesh, disattivabile in qualsiasi momento.",
        ],
        en: [
          "**Sleep with full stages**: deep, light, REM. Not just total duration, but the detailed stages from your Android ring or watch, visible in Apple Health as if recorded by iPhone.",
          "**Steps and activity**: steps from Galaxy Watch or Android wearable land in your Apple Fitness totals without you having to do anything.",
          "**Zero duplicates**: if Apple Health already has something for that time slot (from Apple Watch or any other app), FitMesh doesn't touch it.",
          "**Fully opt-in**: activated from FitMesh iOS settings, can be turned off at any time.",
        ],
        es: [
          "**Sueño con fases completas**: profundo, ligero, REM. No solo la duración total, sino las fases detalladas de tu anillo o reloj Android, visibles en Apple Salud como si hubieran sido registradas por el iPhone.",
          "**Pasos y actividad**: los pasos del Galaxy Watch o del wearable Android se suman a tus totales de Apple Fitness sin que tengas que hacer nada.",
          "**Cero duplicados**: si Apple Salud ya tiene datos para ese intervalo de tiempo (de Apple Watch o de cualquier otra app), FitMesh no los toca.",
          "**Completamente opt-in**: se activa desde los ajustes de FitMesh en iOS y se puede desactivar en cualquier momento.",
        ],
        de: [
          "**Schlaf mit vollständigen Schlafphasen**: Tiefschlaf, Leichtschlaf, REM. Nicht nur die Gesamtdauer, sondern die detaillierten Schlafphasen deines Android-Rings oder deiner Android-Uhr, in Apple Health sichtbar, als wären sie vom iPhone aufgezeichnet worden.",
          "**Schritte und Aktivität**: Schritte von Galaxy Watch oder Android-Wearable landen in deinen Apple-Fitness-Gesamtwerten, ohne dass du etwas tun musst.",
          "**Keine Duplikate**: Hat Apple Health für diesen Zeitraum bereits Daten (von Apple Watch oder einer anderen App), lässt FitMesh sie unberührt.",
          "**Vollständig opt-in**: Wird in den FitMesh-iOS-Einstellungen aktiviert und kann jederzeit deaktiviert werden.",
        ],
        pt: [
          "**Sono com fases completas**: profundo, leve, REM. Não apenas a duração total, mas as fases detalhadas do seu anel ou smartwatch Android, visíveis no Apple Health como se tivessem sido registradas pelo iPhone.",
          "**Passos e atividade**: os passos do Galaxy Watch ou do wearable Android aparecem nos seus totais do Apple Fitness sem que você precise fazer nada.",
          "**Zero duplicatas**: se o Apple Health já tiver dados para aquele intervalo de tempo (do Apple Watch ou de qualquer outro app), FitMesh não os altera.",
          "**Totalmente opt-in**: ativado nas configurações iOS do FitMesh, pode ser desativado a qualquer momento.",
        ],
        fr: [
          "**Sommeil avec phases complètes** : profond, léger, REM. Pas seulement la durée totale, mais les phases détaillées de votre bague ou montre Android, visibles dans Apple Health comme si elles avaient été enregistrées par l'iPhone.",
          "**Pas et activité** : les pas de Galaxy Watch ou du wearable Android s'ajoutent à vos totaux Apple Fitness sans que vous ayez à faire quoi que ce soit.",
          "**Zéro doublon** : si Apple Health possède déjà des données pour ce créneau horaire (depuis Apple Watch ou toute autre app), FitMesh n'y touche pas.",
          "**Entièrement opt-in** : activé depuis les paramètres iOS de FitMesh, désactivable à tout moment.",
        ],
      },
    },
    {
      type: "callout",
      variant: "tip",
      title: {
        it: "Caso d'uso tipico: Galaxy Watch + iPhone",
        en: "Typical use case: Galaxy Watch + iPhone",
        es: "Caso de uso típico: Galaxy Watch + iPhone",
        de: "Typisches Anwendungsbeispiel: Galaxy Watch + iPhone",
        pt: "Caso de uso típico: Galaxy Watch + iPhone",
        fr: "Cas d'usage typique : Galaxy Watch + iPhone",
      },
      body: {
        it: "Usi un Galaxy Watch accoppiato col telefono Android, ma il telefono principale è l'iPhone. Prima: i dati del Watch erano visibili solo in Samsung Health su Android. Ora: FitMesh li legge su Android, li sincronizza sul cloud EU, e l'app iOS li scrive in Apple Salute, compresi gli stage del sonno. Il tuo iPhone Fitness vede tutto.",
        en: "You use a Galaxy Watch paired to Android, but your main phone is iPhone. Before: Watch data was only visible in Samsung Health on Android. Now: FitMesh reads them on Android, syncs to EU cloud, and the iOS app writes them into Apple Health, including sleep stages. Your iPhone Fitness sees everything.",
        es: "Usas un Galaxy Watch vinculado al teléfono Android, pero tu teléfono principal es el iPhone. Antes: los datos del Watch solo eran visibles en Samsung Health en Android. Ahora: FitMesh los lee en Android, los sincroniza en la nube EU, y la app para iOS los escribe en Apple Salud, incluidas las fases del sueño. Tu iPhone y Fitness lo ven todo.",
        de: "Du nutzt eine Galaxy Watch, die mit dem Android-Smartphone gekoppelt ist, aber dein Hauptgerät ist das iPhone. Vorher: Watch-Daten waren nur in Samsung Health auf Android sichtbar. Jetzt: FitMesh liest sie auf Android, synchronisiert sie in die EU-Cloud, und die iOS-App schreibt sie in Apple Health, einschließlich der Schlafphasen. Dein iPhone und Fitness sehen alles.",
        pt: "Você usa um Galaxy Watch pareado com o celular Android, mas o celular principal é o iPhone. Antes: os dados do Watch ficavam visíveis apenas no Samsung Health no Android. Agora: FitMesh os lê no Android, sincroniza na nuvem EU, e o app iOS os grava no Apple Health, incluindo as fases do sono. Seu iPhone e o Fitness veem tudo.",
        fr: "Vous utilisez une Galaxy Watch associée à Android, mais votre téléphone principal est l'iPhone. Avant : les données de la Watch n'étaient visibles que dans Samsung Health sur Android. Maintenant : FitMesh les lit sur Android, les synchronise vers le cloud EU, et l'app iOS les écrit dans Apple Health, y compris les phases du sommeil. Votre iPhone et Fitness voient tout.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Privacy e sicurezza",
        en: "Privacy and security",
        es: "Privacidad y seguridad",
        de: "Datenschutz und Sicherheit",
        pt: "Privacidade e segurança",
        fr: "Confidentialité et sécurité",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Tutti i dati transitano e vengono archiviati su cloud in datacenter EU, conformi GDPR. FitMesh non vende dati a terzi e non li usa per addestrare modelli. Il ponte di scrittura Apple Salute è opt-in: se non lo attivi, l'app iOS legge da Apple Health ma non scrive nulla. Puoi revocare i permessi HealthKit dall'app Impostazioni iPhone in qualsiasi momento.",
        en: "All data transits and is stored in EU datacenter cloud, GDPR compliant. FitMesh doesn't sell data to third parties and doesn't use it to train models. The Apple Health write bridge is opt-in: if you don't activate it, the iOS app reads from Apple Health but writes nothing. You can revoke HealthKit permissions from iPhone Settings at any time.",
        es: "Todos los datos se transmiten y almacenan en centros de datos EU conformes con el GDPR. FitMesh no vende datos a terceros ni los utiliza para entrenar modelos. El puente de escritura a Apple Salud es opt-in: si no lo activas, la app para iOS lee de Apple Health pero no escribe nada. Puedes revocar los permisos de HealthKit desde los Ajustes del iPhone en cualquier momento.",
        de: "Alle Daten werden über EU-Rechenzentren übertragen und gespeichert, die DSGVO-konform sind. FitMesh verkauft keine Daten an Dritte und verwendet sie nicht zum Training von Modellen. Die Schreibbrücke zu Apple Health ist opt-in: Aktivierst du sie nicht, liest die iOS-App nur aus Apple Health, schreibt aber nichts. Du kannst die HealthKit-Berechtigungen jederzeit in den iPhone-Einstellungen widerrufen.",
        pt: "Todos os dados transitam e são armazenados em datacenters EU em conformidade com a LGPD/GDPR. FitMesh não vende dados a terceiros e não os usa para treinar modelos. A ponte de escrita para o Apple Health é opt-in: se você não ativá-la, o app iOS lê o Apple Health mas não grava nada. Você pode revogar as permissões do HealthKit nas Configurações do iPhone a qualquer momento.",
        fr: "Toutes les données transitent et sont stockées dans des datacenters EU conformes au RGPD. FitMesh ne vend pas de données à des tiers et ne les utilise pas pour entraîner des modèles. Le pont d'écriture vers Apple Health est opt-in : si vous ne l'activez pas, l'app iOS lit depuis Apple Health mais n'écrit rien. Vous pouvez révoquer les autorisations HealthKit depuis les Réglages de l'iPhone à tout moment.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Come entrare in beta",
        en: "How to join the beta",
        es: "Cómo unirte a la beta",
        de: "So trittst du der Beta bei",
        pt: "Como entrar na beta",
        fr: "Comment rejoindre la bêta",
      },
    },
    {
      type: "list",
      ordered: true,
      items: {
        it: [
          "Iscriviti alla beta dalla pagina /beta di questo sito: ti mandiamo l'invito TestFlight.",
          "Installa l'app tramite il link TestFlight ricevuto per email.",
          "Accedi con lo stesso account Google o Apple che usi (o che useresti) su Android.",
          "Attiva il ponte Apple Salute dalle Impostazioni se vuoi scrivere i dati dei device Android.",
        ],
        en: [
          "Sign up for the beta from the /beta page on this site: we'll send you a TestFlight invite.",
          "Install the app via the TestFlight link received by email.",
          "Sign in with the same Google or Apple account you use (or would use) on Android.",
          "Enable the Apple Health bridge from Settings if you want to write data from Android devices.",
        ],
        es: [
          "Regístrate en la beta desde la página /beta de este sitio: te enviaremos la invitación de TestFlight.",
          "Instala la app mediante el enlace de TestFlight que recibirás por correo electrónico.",
          "Inicia sesión con la misma cuenta de Google o Apple que usas (o que usarías) en Android.",
          "Activa el puente de Apple Salud desde los Ajustes si quieres escribir los datos de los dispositivos Android.",
        ],
        de: [
          "Melde dich für die Beta über die Seite /beta auf dieser Website an: Wir schicken dir eine TestFlight-Einladung.",
          "Installiere die App über den per E-Mail erhaltenen TestFlight-Link.",
          "Melde dich mit demselben Google- oder Apple-Konto an, das du auf Android nutzt (oder nutzen würdest).",
          "Aktiviere die Apple-Health-Brücke in den Einstellungen, wenn du Daten von Android-Geräten schreiben möchtest.",
        ],
        pt: [
          "Cadastre-se na beta pela página /beta deste site: enviaremos o convite do TestFlight para você.",
          "Instale o app pelo link do TestFlight recebido por e-mail.",
          "Entre com a mesma conta Google ou Apple que você usa (ou usaria) no Android.",
          "Ative a ponte do Apple Health nas Configurações se quiser gravar os dados dos dispositivos Android.",
        ],
        fr: [
          "Inscrivez-vous à la bêta depuis la page /beta de ce site : nous vous enverrons une invitation TestFlight.",
          "Installez l'app via le lien TestFlight reçu par e-mail.",
          "Connectez-vous avec le même compte Google ou Apple que vous utilisez (ou utiliseriez) sur Android.",
          "Activez le pont Apple Health depuis les Paramètres si vous souhaitez écrire les données de vos appareils Android.",
        ],
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "In sintesi",
        en: "In summary",
        es: "En resumen",
        de: "Zusammenfassung",
        pt: "Em resumo",
        fr: "En résumé",
      },
    },
    {
      type: "list",
      items: {
        it: [
          "FitMesh Sync è in beta TestFlight su iPhone, con uscita App Store imminente.",
          "Un account, due telefoni: la stessa dashboard su Android e iPhone, dati dallo stesso cloud EU.",
          "Il ponte Apple Salute (opt-in) porta i dati del tuo wearable Android dentro l'app Salute di iPhone: sonno con fasi, passi, attività, senza doppioni.",
          "Privacy EU/GDPR: nessuna vendita di dati, bridge opt-in, revocabile in qualsiasi momento.",
        ],
        en: [
          "FitMesh Sync is in TestFlight beta on iPhone, with App Store launch imminent.",
          "One account, two phones: the same dashboard on Android and iPhone, data from the same EU cloud.",
          "The Apple Health bridge (opt-in) brings your Android wearable data into the iPhone Health app: sleep with stages, steps, activity, no duplicates.",
          "EU/GDPR privacy: no data sales, opt-in bridge, revocable at any time.",
        ],
        es: [
          "FitMesh Sync está en beta TestFlight en iPhone, con lanzamiento en App Store inminente.",
          "Una cuenta, dos teléfonos: el mismo panel en Android e iPhone, datos desde la misma nube EU.",
          "El puente de Apple Salud (opt-in) lleva los datos de tu wearable Android a la app Salud del iPhone: sueño con fases, pasos, actividad, sin duplicados.",
          "Privacidad EU/GDPR: sin venta de datos, puente opt-in, revocable en cualquier momento.",
        ],
        de: [
          "FitMesh Sync ist in der TestFlight-Beta auf dem iPhone, mit dem App-Store-Launch kurz bevor.",
          "Ein Konto, zwei Smartphones: dasselbe Dashboard auf Android und iPhone, Daten aus derselben EU-Cloud.",
          "Die Apple-Health-Brücke (opt-in) bringt deine Android-Wearable-Daten in die Health-App des iPhones: Schlaf mit Schlafphasen, Schritte, Aktivität, ohne Duplikate.",
          "EU/DSGVO-Datenschutz: keine Datenweitergabe, opt-in-Brücke, jederzeit widerrufbar.",
        ],
        pt: [
          "FitMesh Sync está na beta do TestFlight para iPhone, com lançamento na App Store iminente.",
          "Uma conta, dois celulares: o mesmo painel no Android e no iPhone, dados da mesma nuvem EU.",
          "A ponte do Apple Health (opt-in) leva seus dados de wearable Android para o app Saúde do iPhone: sono com fases, passos, atividade, sem duplicatas.",
          "Privacidade EU/LGPD-GDPR: sem venda de dados, ponte opt-in, revogável a qualquer momento.",
        ],
        fr: [
          "FitMesh Sync est en bêta TestFlight sur iPhone, avec un lancement sur l'App Store imminent.",
          "Un compte, deux téléphones : le même tableau de bord sur Android et iPhone, données provenant du même cloud EU.",
          "Le pont Apple Health (opt-in) apporte vos données wearable Android dans l'app Santé de l'iPhone : sommeil avec phases, pas, activité, sans doublons.",
          "Confidentialité EU/RGPD : aucune vente de données, pont opt-in, révocable à tout moment.",
        ],
      },
    },
    {
      type: "cta",
      title: {
        it: "Entra in beta iOS (posti limitati)",
        en: "Join the iOS beta (limited spots)",
        es: "Únete a la beta de iOS (plazas limitadas)",
        de: "Jetzt der iOS-Beta beitreten (begrenzte Plätze)",
        pt: "Entre na beta iOS (vagas limitadas)",
        fr: "Rejoignez la bêta iOS (places limitées)",
      },
      body: {
        it: "La beta TestFlight è aperta. Iscriviti dalla pagina beta e ricevi il link di installazione entro 24 ore. L'uscita su App Store è imminente.",
        en: "The TestFlight beta is open. Sign up from the beta page and receive your installation link within 24 hours. App Store launch is imminent.",
        es: "La beta TestFlight está abierta. Regístrate desde la página beta y recibe tu enlace de instalación en menos de 24 horas. El lanzamiento en App Store es inminente.",
        de: "Die TestFlight-Beta ist geöffnet. Melde dich über die Beta-Seite an und erhalte deinen Installations-Link innerhalb von 24 Stunden. Der App-Store-Launch ist unmittelbar bevorstehend.",
        pt: "A beta do TestFlight está aberta. Cadastre-se na página beta e receba seu link de instalação em até 24 horas. O lançamento na App Store é iminente.",
        fr: "La bêta TestFlight est ouverte. Inscrivez-vous depuis la page bêta et recevez votre lien d'installation en moins de 24 heures. Le lancement sur l'App Store est imminent.",
      },
      ctaLabel: {
        it: "Iscriviti alla beta iOS →",
        en: "Join the iOS beta →",
        es: "Únete a la beta de iOS →",
        de: "Zur iOS-Beta anmelden →",
        pt: "Entrar na beta iOS →",
        fr: "Rejoindre la bêta iOS →",
      },
      ctaHref: {
        it: "/it/beta",
        en: "/en/beta",
      },
    },
  ],
  faq: [
    {
      q: {
        it: "FitMesh iOS è già sull'App Store?",
        en: "Is FitMesh iOS already on the App Store?",
        es: "¿FitMesh para iOS ya está en el App Store?",
        de: "Ist FitMesh iOS bereits im App Store?",
        pt: "FitMesh iOS já está na App Store?",
        fr: "FitMesh iOS est-il déjà sur l'App Store ?",
      },
      a: {
        it: "Non ancora. L'app è in beta TestFlight e in submission su App Store. L'uscita è imminente. Nel frattempo puoi iscriverti alla beta dalla pagina /beta e ricevere l'accesso TestFlight.",
        en: "Not yet. The app is in TestFlight beta and in App Store submission. Launch is imminent. In the meantime you can sign up for the beta from the /beta page and receive TestFlight access.",
        es: "Todavía no. La app está en beta TestFlight y en proceso de revisión en App Store. El lanzamiento es inminente. Mientras tanto, puedes registrarte en la beta desde la página /beta y recibir acceso a TestFlight.",
        de: "Noch nicht. Die App ist in der TestFlight-Beta und in der App-Store-Einreichung. Der Launch steht kurz bevor. In der Zwischenzeit kannst du dich über die Seite /beta für die Beta anmelden und TestFlight-Zugang erhalten.",
        pt: "Ainda não. O app está na beta do TestFlight e em análise na App Store. O lançamento é iminente. Enquanto isso, você pode se cadastrar na beta pela página /beta e receber acesso ao TestFlight.",
        fr: "Pas encore. L'app est en bêta TestFlight et en cours de soumission sur l'App Store. Le lancement est imminent. En attendant, vous pouvez vous inscrire à la bêta depuis la page /beta et recevoir un accès TestFlight.",
      },
    },
    {
      q: {
        it: "Devo creare un nuovo account per iOS?",
        en: "Do I need to create a new account for iOS?",
        es: "¿Necesito crear una cuenta nueva para iOS?",
        de: "Muss ich für iOS ein neues Konto erstellen?",
        pt: "Preciso criar uma nova conta para o iOS?",
        fr: "Dois-je créer un nouveau compte pour iOS ?",
      },
      a: {
        it: "No. Usa lo stesso account Google o Apple che hai su Android (o che crei per la prima volta). Un account FitMesh funziona su tutti i device: Android, iPhone e dashboard web.",
        en: "No. Use the same Google or Apple account you have on Android (or that you're creating for the first time). One FitMesh account works on all devices: Android, iPhone and web dashboard.",
        es: "No. Usa la misma cuenta de Google o Apple que tienes en Android (o que estás creando por primera vez). Una cuenta de FitMesh funciona en todos los dispositivos: Android, iPhone y panel web.",
        de: "Nein. Verwende dasselbe Google- oder Apple-Konto, das du auf Android hast (oder das du zum ersten Mal erstellst). Ein FitMesh-Konto funktioniert auf allen Geräten: Android, iPhone und Web-Dashboard.",
        pt: "Não. Use a mesma conta Google ou Apple que você tem no Android (ou que está criando pela primeira vez). Uma conta FitMesh funciona em todos os dispositivos: Android, iPhone e painel web.",
        fr: "Non. Utilisez le même compte Google ou Apple que vous avez sur Android (ou que vous créez pour la première fois). Un compte FitMesh fonctionne sur tous les appareils : Android, iPhone et tableau de bord web.",
      },
    },
    {
      q: {
        it: "Il ponte Apple Salute funziona in entrambe le direzioni?",
        en: "Does the Apple Health bridge work in both directions?",
        es: "¿El puente de Apple Salud funciona en ambas direcciones?",
        de: "Funktioniert die Apple-Health-Brücke in beide Richtungen?",
        pt: "A ponte do Apple Health funciona nas duas direções?",
        fr: "Le pont Apple Health fonctionne-t-il dans les deux sens ?",
      },
      a: {
        it: "Il ponte di scrittura porta dati dai device Android verso Apple Salute. La lettura da Apple Salute (per vedere i dati di Apple Watch o dei wearable iOS) funziona sempre, indipendentemente dal bridge. In sintesi: FitMesh legge da Apple Health (sempre), e può scrivere su Apple Health (opt-in) i dati raccolti dagli altri device del tuo account.",
        en: "The write bridge brings data from Android devices to Apple Health. Reading from Apple Health (to see Apple Watch or iOS wearable data) always works, regardless of the bridge. In short: FitMesh reads from Apple Health (always), and can write to Apple Health (opt-in) data collected from other devices on your account.",
        es: "El puente de escritura lleva datos desde los dispositivos Android hacia Apple Salud. La lectura de Apple Salud (para ver los datos de Apple Watch o de wearables iOS) siempre funciona, independientemente del puente. En resumen: FitMesh lee de Apple Health (siempre) y puede escribir en Apple Health (opt-in) los datos recogidos por los demás dispositivos de tu cuenta.",
        de: "Die Schreibbrücke überträgt Daten von Android-Geräten zu Apple Health. Das Lesen aus Apple Health (um Apple Watch- oder iOS-Wearable-Daten zu sehen) funktioniert immer, unabhängig von der Brücke. Kurz gesagt: FitMesh liest immer aus Apple Health und kann (opt-in) Daten, die von anderen Geräten deines Kontos gesammelt wurden, in Apple Health schreiben.",
        pt: "A ponte de escrita leva dados dos dispositivos Android para o Apple Health. A leitura do Apple Health (para ver os dados do Apple Watch ou de wearables iOS) funciona sempre, independentemente da ponte. Em resumo: FitMesh lê do Apple Health (sempre) e pode gravar no Apple Health (opt-in) os dados coletados pelos outros dispositivos da sua conta.",
        fr: "Le pont d'écriture apporte les données des appareils Android vers Apple Health. La lecture depuis Apple Health (pour voir les données d'Apple Watch ou des wearables iOS) fonctionne toujours, indépendamment du pont. En résumé : FitMesh lit depuis Apple Health (toujours) et peut écrire dans Apple Health (opt-in) les données collectées par les autres appareils de votre compte.",
      },
    },
    {
      q: {
        it: "Se ho sia Apple Watch che Galaxy Watch, ci sono duplicati?",
        en: "If I have both Apple Watch and Galaxy Watch, will there be duplicates?",
        es: "Si tengo tanto Apple Watch como Galaxy Watch, ¿habrá duplicados?",
        de: "Wenn ich sowohl Apple Watch als auch Galaxy Watch habe, gibt es Duplikate?",
        pt: "Se eu tiver Apple Watch e Galaxy Watch, haverá duplicatas?",
        fr: "Si j'ai à la fois Apple Watch et Galaxy Watch, y aura-t-il des doublons ?",
      },
      a: {
        it: "No. FitMesh controlla prima se Apple Salute ha già qualcosa per quella fascia oraria. Se Apple Watch ha già registrato sonno dalle 23:00 alle 07:00, il bridge non scrive nulla per quelle ore. Si scrive solo dove non c'è già copertura.",
        en: "No. FitMesh checks first whether Apple Health already has something for that time slot. If Apple Watch has already recorded sleep from 11pm to 7am, the bridge writes nothing for those hours. It only writes where there's no existing coverage.",
        es: "No. FitMesh comprueba primero si Apple Salud ya tiene datos para ese intervalo de tiempo. Si Apple Watch ya registró el sueño de las 23:00 a las 07:00, el puente no escribe nada para esas horas. Solo escribe donde no hay cobertura existente.",
        de: "Nein. FitMesh prüft zuerst, ob Apple Health für diesen Zeitraum bereits Daten hat. Hat Apple Watch bereits Schlaf von 23:00 bis 07:00 Uhr aufgezeichnet, schreibt die Brücke für diese Stunden nichts. Es wird nur geschrieben, wo noch keine Daten vorhanden sind.",
        pt: "Não. FitMesh verifica primeiro se o Apple Health já tem dados para aquele intervalo de tempo. Se o Apple Watch já registrou o sono das 23h às 07h, a ponte não grava nada para essas horas. Só grava onde ainda não há cobertura.",
        fr: "Non. FitMesh vérifie d'abord si Apple Health possède déjà des données pour ce créneau horaire. Si Apple Watch a déjà enregistré le sommeil de 23h à 7h, le pont n'écrit rien pour ces heures. Il n'écrit que là où il n'y a pas encore de données.",
      },
    },
    {
      q: {
        it: "Quali device Android funzionano con il ponte Apple Salute?",
        en: "Which Android devices work with the Apple Health bridge?",
        es: "¿Qué dispositivos Android funcionan con el puente de Apple Salud?",
        de: "Welche Android-Geräte funktionieren mit der Apple-Health-Brücke?",
        pt: "Quais dispositivos Android funcionam com a ponte do Apple Health?",
        fr: "Quels appareils Android fonctionnent avec le pont Apple Health ?",
      },
      a: {
        it: "Tutti i device già supportati da FitMesh su Android: Galaxy Watch (via Samsung Health e Health Connect), anelli Colmi R02/R03 via BLE, e qualsiasi wearable che scrive su Health Connect. I dati di questi device vengono sincronizzati sul cloud FitMesh e possono essere scritti su Apple Health dall'app iOS.",
        en: "All devices already supported by FitMesh on Android: Galaxy Watch (via Samsung Health and Health Connect), Colmi R02/R03 rings via BLE, and any wearable writing to Health Connect. Data from these devices is synced to the FitMesh cloud and can be written to Apple Health by the iOS app.",
        es: "Todos los dispositivos ya compatibles con FitMesh en Android: Galaxy Watch (a través de Samsung Health y Health Connect), anillos Colmi R02/R03 vía BLE, y cualquier wearable que escriba en Health Connect. Los datos de estos dispositivos se sincronizan en la nube de FitMesh y pueden ser escritos en Apple Health por la app para iOS.",
        de: "Alle Geräte, die von FitMesh auf Android bereits unterstützt werden: Galaxy Watch (über Samsung Health und Health Connect), Colmi R02/R03 Ringe per BLE und jedes Wearable, das in Health Connect schreibt. Daten dieser Geräte werden mit der FitMesh-Cloud synchronisiert und können von der iOS-App in Apple Health geschrieben werden.",
        pt: "Todos os dispositivos já compatíveis com FitMesh no Android: Galaxy Watch (via Samsung Health e Health Connect), anéis Colmi R02/R03 via BLE e qualquer wearable que grave no Health Connect. Os dados desses dispositivos são sincronizados na nuvem FitMesh e podem ser gravados no Apple Health pelo app iOS.",
        fr: "Tous les appareils déjà pris en charge par FitMesh sur Android : Galaxy Watch (via Samsung Health et Health Connect), bagues Colmi R02/R03 via BLE, et tout wearable qui écrit dans Health Connect. Les données de ces appareils sont synchronisées vers le cloud FitMesh et peuvent être écrites dans Apple Health par l'app iOS.",
      },
    },
  ],
  related: [
    "how-to-export-apple-health-data",
    "colmi-ring-fitmesh",
    "come-funziona-health-connect",
  ],
  brandsMentioned: ["Apple", "Google", "Samsung"],
  ldType: "BlogPosting",
};
