import type { BlogPost } from "../types";

export const post: BlogPost = {
  slug: "fitmesh-sync-disponibile-google-play",
  category: "news",
  publishedAt: "2026-06-14",
  updatedAt: "2026-09-24",
  ldType: "BlogPosting",
  readMinutes: 3,
  primaryKeyword: {
    it: "FitMesh Sync su Google Play",
    en: "FitMesh Sync on Google Play",
    es: "FitMesh Sync en Google Play",
    de: "FitMesh Sync auf Google Play",
    pt: "FitMesh Sync no Google Play",
    fr: "FitMesh Sync sur Google Play",
    pl: "FitMesh Sync w Google Play",
    tr: "FitMesh Sync Google Play'de",
    nl: "FitMesh Sync in Google Play",
    ja: "FitMesh Sync、Google Playで公開",
    ko: "FitMesh Sync, Google Play 출시",
  },
  secondaryKeywords: {
    it: [
      "app per unire i dati dello smartwatch",
      "dashboard salute Android",
      "scaricare FitMesh Sync",
      "app dati wearable in italiano",
      "Pro a vita gratis founder",
    ],
    en: [
      "app to unify smartwatch data",
      "Android health dashboard",
      "download FitMesh Sync",
      "wearable data app",
      "lifetime Pro founder",
    ],
    pt: [
      "app para unir dados do smartwatch",
      "painel de saúde Android",
      "baixar FitMesh Sync",
      "app de dados wearable",
      "Pro vitalício grátis founder",
    ],
    fr: [
      "app pour unifier les données du smartwatch",
      "tableau de bord santé Android",
      "télécharger FitMesh Sync",
      "app de données wearable",
      "Pro à vie gratuit founder",
    ],
    pl: [
      "aplikacja do łączenia danych ze smartwatcha",
      "panel zdrowia Android",
      "pobierz FitMesh Sync",
      "aplikacja danych wearable",
      "dożywotnie Pro za darmo dla założycieli",
    ],
    tr: [
      "akıllı saat verilerini birleştiren uygulama",
      "Android sağlık paneli",
      "FitMesh Sync indir",
      "giyilebilir cihaz veri uygulaması",
      "kuruculara ömür boyu ücretsiz Pro",
    ],
    nl: [
      "app om smartwatchgegevens samen te voegen",
      "Android gezondheidsdashboard",
      "FitMesh Sync downloaden",
      "wearable data-app",
      "levenslang Pro gratis voor founders",
    ],
    ja: [
      "スマートウォッチデータを統合するアプリ",
      "Android健康ダッシュボード",
      "FitMesh Syncをダウンロード",
      "ウェアラブルデータアプリ",
      "創業者向け永久版Pro無料",
    ],
    ko: [
      "스마트워치 데이터를 통합하는 앱",
      "Android 건강 대시보드",
      "FitMesh Sync 다운로드",
      "웨어러블 데이터 앱",
      "파운더 평생 무료 Pro",
    ],
    de: [
      "App zum Zusammenführen von Smartwatch-Daten",
      "Android Gesundheits-Dashboard",
      "FitMesh Sync herunterladen",
      "Wearable-Daten-App auf Deutsch",
      "lebenslang Pro als Founder gratis",
    ],
    es: [
      "app para unificar datos del smartwatch",
      "panel de salud android",
      "descargar fitmesh sync",
      "app de datos wearable en español",
      "pro de por vida gratis founder",
    ],
  },
  metaDescription: {
    it: "FitMesh Sync è disponibile su Google Play: unisci i dati di smartwatch e anello in un'unica dashboard. L'app iOS è già disponibile, incluse tutte le storefront dell'Unione Europea.",
    en: "FitMesh Sync is now on Google Play: bring your smartwatch and ring data into one dashboard. The iOS app is already available, including all European Union storefronts.",
    es: "FitMesh Sync ya está disponible en Google Play: une los datos de tu smartwatch y tu anillo en un único panel. La app iOS ya está disponible, incluidas todas las tiendas de la Unión Europea.",
    de: "FitMesh Sync ist jetzt auf Google Play: Führe Smartwatch- und Ring-Daten in einer Dashboard zusammen. Die iOS-App ist bereits verfügbar, einschließlich aller Storefronts der Europäischen Union.",
    pt: "FitMesh Sync está disponível no Google Play: reúna os dados do seu smartwatch e anel em um único painel. O app iOS já está disponível, incluindo todas as lojas da União Europeia.",
    fr: "FitMesh Sync est maintenant sur Google Play: regroupez les données de votre montre connectée et de votre bague en un seul tableau de bord. L'app iOS est déjà disponible, y compris dans toutes les boutiques de l'Union européenne.",
    pl: "FitMesh Sync jest teraz w Google Play: połącz dane ze swojego smartwatcha i pierścionka w jednym panelu. Aplikacja iOS jest już dostępna, we wszystkich sklepach Unii Europejskiej.",
    tr: "FitMesh Sync artık Google Play'de: akıllı saat ve yüzük verilerinizi tek bir panelde birleştirin. iOS uygulaması Avrupa Birliği'ndeki tüm mağazalar dahil olmak üzere zaten kullanılabilir.",
    nl: "FitMesh Sync is nu beschikbaar in Google Play: breng de gegevens van je sporthorloge en slimme ring samen in één dashboard. De iOS-app is al beschikbaar, inclusief alle winkels van de Europese Unie.",
    ja: "FitMesh SyncがGoogle Playで公開されました。スマートウォッチとリングのデータを1つのダッシュボードにまとめます。iOS版はすでにEU域内を含め提供中です。",
    ko: "FitMesh Sync가 이제 Google Play에 출시되었습니다. 스마트워치와 링 데이터를 하나의 대시보드에 통합합니다. iOS 앱은 이미 EU 지역을 포함하여 출시되었습니다.",
  },
  tldr: {
    it: [
      "FitMesh Sync è ora scaricabile su Google Play, per tutti i telefoni Android.",
      "Unisci smartwatch, anello e altri dispositivi in un'unica dashboard, senza saltare tra app.",
      "Informazioni su gestione, conservazione e cancellazione dei dati consultabili nell'informativa sulla privacy.",
      "I primi 1000 a registrarsi (entro il 31 luglio 2026) hanno ricevuto il Pro a vita gratis. L'app è già disponibile anche su iPhone, incluse tutte le storefront dell'Unione Europea.",
    ],
    en: [
      "FitMesh Sync is now available on Google Play, for every Android phone.",
      "Bring your watch, ring and other devices into one dashboard, without jumping between apps.",
      "Information on data handling, retention, and deletion is available in our privacy policy.",
      "The first 1,000 to sign up (by July 31, 2026) got lifetime Pro free. The iPhone app is already available too, including all European Union storefronts.",
    ],
    es: [
      "FitMesh Sync ya está disponible en Google Play, para todos los teléfonos Android.",
      "Une tu smartwatch, tu anillo y otros dispositivos en un único panel, sin saltar entre apps.",
      "Información sobre tratamiento, conservación y eliminación de datos disponible en la política de privacidad.",
      "Los primeros 1000 en registrarse (hasta el 31 de julio de 2026) recibieron el Pro de por vida gratis. La app para iPhone también está disponible ya, incluidas todas las tiendas de la Unión Europea.",
    ],
    de: [
      "FitMesh Sync ist jetzt auf Google Play verfügbar, für alle Android-Smartphones.",
      "Führe Smartwatch, Ring und andere Geräte in einer Dashboard zusammen, ohne zwischen Apps zu wechseln.",
      "Informationen zu Datenverarbeitung, Speicherung und Löschung findest du in der Datenschutzerklärung.",
      "Die ersten 1000, die sich registriert haben (bis 31. Juli 2026), haben lebenslang Pro kostenlos erhalten. Die iPhone-App ist ebenfalls schon verfügbar, einschließlich aller Storefronts der Europäischen Union.",
    ],
    pt: [
      "FitMesh Sync já está disponível no Google Play, para todos os celulares Android.",
      "Reúna seu smartwatch, anel e outros dispositivos em um único painel, sem precisar alternar entre apps.",
      "Informações sobre tratamento, retenção e exclusão de dados disponíveis na política de privacidade.",
      "Os primeiros 1000 a se cadastrar (até 31 de julho de 2026) receberam o Pro vitalício grátis. O app para iPhone também já está disponível, incluindo todas as lojas da União Europeia.",
    ],
    fr: [
      "FitMesh Sync est maintenant disponible sur Google Play, pour tous les téléphones Android.",
      "Regroupez votre montre connectée, votre bague et vos autres appareils dans un seul tableau de bord, sans jongler entre les applications.",
      "Informations sur le traitement, la conservation et la suppression des données disponibles dans la politique de confidentialité.",
      "Les 1000 premiers inscrits (jusqu'au 31 juillet 2026) ont reçu le Pro à vie gratuit. L'app iPhone est elle aussi déjà disponible, y compris dans toutes les boutiques de l'Union européenne.",
    ],
    pl: [
      "FitMesh Sync jest dostępny w Google Play. Pobierz, podłącz swoje urządzenie, zaloguj się i zacznij synchronizować - bez konfiguracji poza telefonem.",
      "Health Connect to most między Twoim wearablem a wszystkimi innymi aplikacjami Android. FitMesh Sync odczytuje z niego dane zdrowotne.",
      "Informacje o przetwarzaniu, przechowywaniu i usuwaniu danych dostępne są w polityce prywatności.",
      "Pierwszych 1000 osób, które się zarejestrowały (do 31 lipca 2026), otrzymało dożywotnie Pro za darmo. Aplikacja na iPhone'a jest już dostępna, we wszystkich sklepach Unii Europejskiej.",
    ],
    tr: [
      "FitMesh Sync Google Play'de mevcut. İndirin, cihazınızı bağlayın, giriş yapın ve senkronizasyona başlayın - telefon dışında herhangi bir kurulum gerekmez.",
      "Health Connect, giyilebilir cihazınız ile diğer tüm Android uygulamaları arasındaki köprüdür. FitMesh Sync buradan sağlık verilerini okur.",
      "Veri işleme, saklama ve silme işlemleri hakkında ayrıntılı bilgi gizlilik politikasında mevcuttur.",
      "İlk 1000 kayıt olan (31 Temmuz 2026'ya kadar) ömür boyu ücretsiz Pro aldı. iPhone uygulaması da Avrupa Birliği'ndeki tüm mağazalar dahil olmak üzere zaten kullanılabilir.",
    ],
    nl: [
      "FitMesh Sync is nu beschikbaar in Google Play. Download het, koppel je apparaat, log in en begin te synchroniseren - geen installatie buiten je telefoon nodig.",
      "Health Connect is de brug tussen je wearable en alle andere Android-apps. FitMesh Sync leest gezondheidsgegevens daaruit.",
      "Informatie over gegevensverwerking, opslag en verwijdering is te vinden in het privacybeleid.",
      "De eerste 1000 die zich hebben geregistreerd (tot 31 juli 2026) hebben levenslang Pro gratis gekregen. De iPhone-app is ook al beschikbaar, inclusief alle winkels van de Europese Unie.",
    ],
    ja: [
      "FitMesh SyncはGoogle Playで入手できます。ダウンロードして、デバイスを接続し、ログインして同期を開始しましょう。スマートフォン以外の設定は不要です。",
      "Health ConnectはウェアラブルとすべてのAndroidアプリをつなぐ橋渡し役です。FitMesh Syncはそこから健康データを読み取ります。",
      "データの取り扱い、保持、削除に関する詳細はプライバシーポリシーでご確認いただけます。",
      "先着1000名（2026年7月31日まで）は永久版Proを無料で取得しました。iPhone版もすでにEU域内を含め提供中です。",
    ],
    ko: [
      "FitMesh Sync가 Google Play에 출시되었습니다. 다운로드하고, 기기를 연결하고, 로그인한 뒤 동기화를 시작하세요. 스마트폰 외에 별도 설정이 필요 없습니다.",
      "Health Connect는 웨어러블과 모든 Android 앱을 연결하는 다리 역할을 합니다. FitMesh Sync는 그곳에서 건강 데이터를 읽습니다.",
      "데이터 처리, 보관 및 삭제에 관한 정보는 개인정보 처리방침에서 확인할 수 있습니다.",
      "선착순 1000명(2026년 7월 31일까지)은 평생 무료 Pro를 받았습니다. iPhone 앱도 이미 EU 지역을 포함하여 출시되었습니다.",
    ],
  },
  hero: {
    kicker: {
      it: "Novità",
      en: "What's New",
      es: "Novedades",
      de: "Neuigkeiten",
      pt: "Novidades",
      fr: "Nouveauté",
      pl: "Nowości",
      tr: "Yenilikler",
      nl: "Nieuws",
      ja: "新着情報",
      ko: "새 소식",
    },
    title: {
      it: "FitMesh Sync è disponibile su Google Play",
      en: "FitMesh Sync is now on Google Play",
      es: "FitMesh Sync ya está disponible en Google Play",
      de: "FitMesh Sync ist jetzt auf Google Play verfügbar",
      pt: "FitMesh Sync já está disponível no Google Play",
      fr: "FitMesh Sync est maintenant disponible sur Google Play",
      pl: "FitMesh Sync jest teraz dostępny w Google Play",
      tr: "FitMesh Sync artık Google Play'de",
      nl: "FitMesh Sync is nu beschikbaar in Google Play",
      ja: "FitMesh Sync、Google Playで公開開始",
      ko: "FitMesh Sync, 이제 Google Play에서 출시",
    },
    subtitle: {
      it: "Da oggi puoi scaricare l'app e vedere i dati di tutti i tuoi dispositivi in una sola dashboard. L'app è già disponibile anche su iPhone, incluse tutte le storefront dell'Unione Europea.",
      en: "Starting today you can download the app and see all your devices' data in one dashboard. The iPhone app is already available too, including all European Union storefronts.",
      es: "Desde hoy puedes descargar la app y ver los datos de todos tus dispositivos en un único panel. La app para iPhone también está disponible ya, incluidas todas las tiendas de la Unión Europea.",
      de: "Ab heute kannst du die App herunterladen und die Daten all deiner Geräte in einer Dashboard sehen. Die iPhone-App ist ebenfalls schon verfügbar, einschließlich aller Storefronts der Europäischen Union.",
      pt: "A partir de hoje você pode baixar o app e ver os dados de todos os seus dispositivos em um único painel. O app para iPhone também já está disponível, incluindo todas as lojas da União Europeia.",
      fr: "Dès aujourd'hui, vous pouvez télécharger l'application et consulter les données de tous vos appareils dans un seul tableau de bord. L'app iPhone est elle aussi déjà disponible, y compris dans toutes les boutiques de l'Union européenne.",
      pl: "Od dziś możesz pobrać aplikację i przeglądać dane wszystkich swoich urządzeń w jednym panelu. Aplikacja na iPhone'a jest już dostępna, we wszystkich sklepach Unii Europejskiej.",
      tr: "Bugünden itibaren uygulamayı indirebilir ve tüm cihazlarınızın verilerini tek bir panelde görebilirsiniz. iPhone uygulaması da Avrupa Birliği'ndeki tüm mağazalar dahil olmak üzere zaten kullanılabilir.",
      nl: "Vanaf vandaag kun je de app downloaden en de gegevens van al je apparaten in één dashboard bekijken. De iPhone-app is ook al beschikbaar, inclusief alle winkels van de Europese Unie.",
      ja: "本日より、アプリをダウンロードしてすべてのデバイスのデータを1つのダッシュボードで確認できます。iPhone版もすでにEU域内を含め提供中です。",
      ko: "오늘부터 앱을 다운로드하고 모든 기기의 데이터를 하나의 대시보드에서 확인할 수 있습니다. iPhone 앱도 이미 EU 지역을 포함하여 출시되었습니다.",
    },
  },
  body: [
    {
      type: "paragraph",
      text: {
        it: "Ci siamo: FitMesh Sync è ufficialmente disponibile su Google Play. Puoi scaricarla su qualsiasi telefono Android e iniziare subito a vedere i dati del tuo smartwatch, del tuo anello e degli altri dispositivi in un unico posto.",
        en: "It is here: FitMesh Sync is officially available on Google Play. You can download it on any Android phone and start seeing your smartwatch, ring and other devices' data all in one place.",
        es: "Ya está aquí: FitMesh Sync está disponible oficialmente en Google Play. Puedes descargarla en cualquier teléfono Android y empezar a ver los datos de tu smartwatch, tu anillo y el resto de tus dispositivos en un único lugar.",
        de: "Es ist so weit: FitMesh Sync ist offiziell auf Google Play verfügbar. Du kannst sie auf jedem Android-Smartphone herunterladen und sofort die Daten deines Smartwatchs, deines Rings und anderer Geräte an einem einzigen Ort sehen.",
        pt: "Chegou: FitMesh Sync está disponível oficialmente no Google Play. Você pode baixá-lo em qualquer celular Android e começar a ver agora mesmo os dados do seu smartwatch, do seu anel e de outros dispositivos, tudo em um único lugar.",
        fr: "C'est ici: FitMesh Sync est officiellement disponible sur Google Play. Vous pouvez le télécharger sur n'importe quel téléphone Android et commencer à consulter les données de votre montre connectée, de votre bague et de vos autres appareils au même endroit.",
        pl: "Stało się: FitMesh Sync jest oficjalnie dostępny w Google Play. Możesz go pobrać na dowolny telefon z Androidem i zacząć widzieć dane swojego smartwatcha, pierścionka i innych urządzeń w jednym miejscu.",
        tr: "Geldi: FitMesh Sync resmi olarak Google Play'de mevcut. Herhangi bir Android telefona indirebilir ve akıllı saatinizin, yüzüğünüzün ve diğer cihazlarınızın verilerini tek bir yerde görmeye hemen başlayabilirsiniz.",
        nl: "Het is zover: FitMesh Sync is officieel beschikbaar in Google Play. Je kunt het op elke Android-telefoon downloaden en meteen de gegevens van je sporthorloge, slimme ring en andere apparaten op één plek bekijken.",
        ja: "ついに公開：FitMesh SyncがGoogle Playで正式リリースされました。すべてのAndroidスマートフォンにダウンロードして、スマートウォッチ、スマートリング、その他のデバイスのデータを1か所でまとめて確認できます。",
        ko: "드디어 출시: FitMesh Sync가 Google Play에 공식 출시되었습니다. 모든 Android 스마트폰에서 다운로드하여 스마트워치, 스마트 링, 그 외 기기의 데이터를 한 곳에서 바로 확인할 수 있습니다.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Cosa fa FitMesh Sync",
        en: "What FitMesh Sync does",
        es: "Qué hace FitMesh Sync",
        de: "Was FitMesh Sync kann",
        pt: "O que o FitMesh Sync faz",
        fr: "Ce que fait FitMesh Sync",
        pl: "Co robi FitMesh Sync",
        tr: "FitMesh Sync ne yapar",
        nl: "Wat FitMesh Sync doet",
        ja: "FitMesh Syncでできること",
        ko: "FitMesh Sync의 기능",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Ogni marca tiene i tuoi dati dentro la propria app. Se hai un Galaxy Watch, un anello smart e magari una band di un altro produttore, finisci per saltare da un'app all'altra. FitMesh Sync li raccoglie tutti in una dashboard unica e chiara: passi, sonno, battito, recupero e andamento nel tempo, in italiano e pensata per la lettura di tutti i giorni.",
        en: "Every brand keeps your data inside its own app. If you have a Galaxy Watch, a smart ring and maybe a band from another maker, you end up jumping from one app to another. FitMesh Sync brings them all into one clear dashboard: steps, sleep, heart rate, recovery and trends over time, designed for everyday reading.",
        es: "Cada marca guarda tus datos dentro de su propia app. Si tienes un Galaxy Watch, un anillo inteligente y quizás una pulsera de otro fabricante, acabas saltando de una app a otra. FitMesh Sync los reúne todos en un panel claro y único: pasos, sueño, frecuencia cardíaca, recuperación y tendencias a lo largo del tiempo, pensado para consultarlo cada día.",
        de: "Jede Marke hält deine Daten in ihrer eigenen App. Wenn du eine Galaxy Watch, einen Smart-Ring und vielleicht ein Band eines anderen Herstellers hast, springst du ständig zwischen Apps hin und her. FitMesh Sync bringt sie alle in eine übersichtliche Dashboard: Schritte, Schlaf, Herzfrequenz, Erholung und Trends über die Zeit, gestaltet für den täglichen Gebrauch.",
        pt: "Cada marca mantém seus dados dentro do próprio app. Se você tem um Galaxy Watch, um anel inteligente e talvez uma pulseira de outro fabricante, acaba pulando de app em app. FitMesh Sync reúne tudo em um único painel claro: passos, sono, frequência cardíaca, recuperação e tendências ao longo do tempo, pensado para a leitura do dia a dia.",
        fr: "Chaque marque conserve vos données dans sa propre application. Si vous avez une Galaxy Watch, une bague connectée et peut-être un bracelet d'un autre fabricant, vous finissez par jongler entre les applications. FitMesh Sync les rassemble toutes dans un tableau de bord clair et unique: pas, sommeil, fréquence cardiaque, récupération et tendances dans le temps, conçu pour une consultation quotidienne.",
        pl: "Każda marka trzyma Twoje dane we własnej aplikacji. Jeśli masz Galaxy Watch, inteligentny pierścionek i może opaskę innego producenta, skaczysz z jednej aplikacji do drugiej. FitMesh Sync zbiera je wszystkie w jeden przejrzysty panel: kroki, sen, tętno, regeneracja i trendy w czasie, zaprojektowany do codziennego przeglądania.",
        tr: "Her marka verilerinizi kendi uygulamasında tutar. Bir Galaxy Watch, akıllı yüzük ve belki başka bir üreticinin bandı varsa, sürekli uygulamalar arasında geçiş yaparsınız. FitMesh Sync hepsini tek, net bir panelde toplar: adımlar, uyku, kalp atış hızı, toparlanma ve zaman içindeki eğilimler - günlük okuma için tasarlanmış.",
        nl: "Elk merk bewaart je gegevens in zijn eigen app. Als je een Galaxy Watch, een slimme ring en misschien een band van een andere fabrikant hebt, spring je voortdurend van app naar app. FitMesh Sync bundelt ze allemaal in één overzichtelijk dashboard: stappen, slaap, hartslag, herstel en trends in de tijd, ontworpen voor dagelijks gebruik.",
        ja: "どのブランドもデータを自社アプリの中に閉じ込めています。Galaxy Watch、スマートリング、さらに別のメーカーのバンドを持っていると、アプリを行ったり来たりする羽目になります。FitMesh Syncはそれらをすべて1つの明快なダッシュボードにまとめます。歩数、睡眠、心拍数、回復、時系列トレンドを毎日の確認に最適な形で表示します。",
        ko: "모든 브랜드는 자사 앱 안에 데이터를 가둬둡니다. Galaxy Watch, 스마트 링, 다른 제조사의 밴드까지 갖고 있다면 앱을 계속 오가게 됩니다. FitMesh Sync는 이 모든 것을 하나의 명확한 대시보드로 통합합니다. 걸음 수, 수면, 심박수, 회복, 시간별 트렌드를 매일 쉽게 확인할 수 있도록 설계되었습니다.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Più dispositivi, una vista sola",
        en: "More devices, one single view",
        es: "Varios dispositivos, una sola vista",
        de: "Mehrere Geräte, eine einzige Ansicht",
        pt: "Vários dispositivos, uma única visualização",
        fr: "Plusieurs appareils, une seule vue",
        pl: "Więcej urządzeń, jeden widok",
        tr: "Birden fazla cihaz, tek bir görünüm",
        nl: "Meerdere apparaten, één overzicht",
        ja: "複数デバイス、1つのビュー",
        ko: "여러 기기, 하나의 화면",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Se indossi più dispositivi, FitMesh Sync ti aiuta a gestire le sorgenti applicando regole di priorità per limitare i conteggi doppi dei passi. Quando un dispositivo è in carica, un altro wearable può coprire quella fascia oraria. Abbiamo spiegato criteri, priorità e limiti nella guida [più smartwatch insieme senza dati doppi](/it/blog/piu-smartwatch-insieme-dati-doppi).",
        en: "If you wear multiple devices, FitMesh Sync helps manage sources by applying priority rules to limit duplicate step counts. When one device is charging, another wearable can help cover that time window. We explained the criteria, priorities, and limits in the guide [multiple smartwatches together without double data](/en/blog/piu-smartwatch-insieme-dati-doppi).",
        es: "Si usas varios dispositivos, FitMesh Sync te ayuda a gestionar las fuentes aplicando reglas de prioridad para limitar los pasos duplicados. Cuando un dispositivo se está cargando, otro wearable puede cubrir esa franja horaria. Explicamos criterios, prioridades y límites en la guía [varios smartwatches juntos sin datos duplicados](/es/blog/piu-smartwatch-insieme-dati-doppi).",
        de: "Wenn du mehrere Geräte nutzt, hilft dir FitMesh Sync bei der Verwaltung der Quellen durch Prioritätsregeln, um doppelt gezählte Schritte zu begrenzen. Wenn ein Gerät lädt, kann ein anderes Wearable dieses Zeitfenster abdecken. Kriterien, Prioritäten und Grenzen erklären wir in der Anleitung [mehrere Smartwatches zusammen ohne doppelte Daten](/de/blog/piu-smartwatch-insieme-dati-doppi).",
        pt: "Se você usa vários dispositivos, o FitMesh Sync ajuda a gerenciar as fontes aplicando regras de prioridade para limitar contagens duplicadas de passos. Quando um dispositivo está carregando, outro wearable pode cobrir aquele período. Explicamos critérios, prioridades e limites no guia [vários smartwatches juntos sem dados duplicados](/pt/blog/piu-smartwatch-insieme-dati-doppi).",
        fr: "Si vous portez plusieurs appareils, FitMesh Sync vous aide à gérer les sources en appliquant des règles de priorité pour limiter les doublons de pas. Quand un appareil est en charge, un autre wearable peut couvrir ce créneau. Nous expliquons les critères, priorités et limites dans le guide [plusieurs montres connectées ensemble sans données en double](/fr/blog/piu-smartwatch-insieme-dati-doppi).",
        pl: "Jeśli nosisz kilka urządzeń, FitMesh Sync pomaga zarządzać źródłami, stosując reguły priorytetów, aby ograniczać podwójne liczenie kroków. Gdy jedno urządzenie się ładuje, inne urządzenie ubieralne może pokryć ten przedział czasu. Kryteria, priorytety i ograniczenia wyjaśniamy w przewodniku [kilka smartwatchy jednocześnie bez duplikatów danych](/pl/blog/piu-smartwatch-insieme-dati-doppi).",
        tr: "Birden fazla cihaz kullanıyorsanız, FitMesh Sync adım çift sayımlarını sınırlamak için kaynak öncelik kuralları uygulayarak cihazları yönetmenize yardımcı olur. Bir cihaz şarj olurken, başka bir giyilebilir cihaz o zaman aralığını karşılayabilir. Ölçütleri, öncelikleri ve sınırları [birden fazla akıllı saat - veriler çift sayılmaz](/tr/blog/piu-smartwatch-insieme-dati-doppi) rehberinde anlattık.",
        nl: "Als je meerdere apparaten draagt, helpt FitMesh Sync je bronnen te beheren door prioriteitsregels toe te passen om dubbele stappentellingen te beperken. Wanneer een apparaat oplaadt, kan een andere wearable dat tijdvak helpen overbruggen. We leggen de criteria, prioriteiten en beperkingen uit in de gids [meerdere smartwatches samen zonder dubbele data](/nl/blog/piu-smartwatch-insieme-dati-doppi).",
        ja: "複数のデバイスを使用する場合、FitMesh Syncは優先順位ルールを適用して歩数の重複カウントを抑制し、ソースの管理を支援します。1台のデバイスを充電している間、別のウェアラブルがその時間帯を補うことができます。基準、優先順位、および制限事項については、ガイド[複数スマートウォッチを同時使用してもデータが重複しない方法](/ja/blog/piu-smartwatch-insieme-dati-doppi)で詳しく解説しています。",
        ko: "여러 기기를 사용하는 경우, FitMesh Sync는 걸음 수 중복 집계를 줄이기 위해 소스 우선순위 규칙을 적용하여 기기 관리를 돕습니다. 기기 하나를 충전하는 동안 다른 웨어러블이 해당 시간대를 보완할 수 있습니다. 기준, 우선순위 및 제한 사항은 가이드 [여러 스마트워치를 함께 사용해도 데이터 중복 없음](/ko/blog/piu-smartwatch-insieme-dati-doppi)에서 자세히 설명합니다.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Gestione dei tuoi dati e privacy",
        en: "Your data and privacy",
        es: "Gestión de tus datos y privacidad",
        de: "Deine Daten und Datenschutz",
        pt: "Gestão dos seus dados e privacidade",
        fr: "Gestion de vos données et confidentialité",
        pl: "Zarządzanie Twoimi danymi i prywatność",
        tr: "Veri yönetimi ve gizlilik",
        nl: "Gegevensbeheer en privacy",
        ja: "データの管理とプライバシー",
        ko: "데이터 관리와 개인정보 보호",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "I dati relativi alla salute richiedono trasparenza e cura. Per conoscere in dettaglio le modalità di raccolta, conservazione, sicurezza e come richiedere la cancellazione tramite il tuo account, consulta l'informativa sulla [privacy](/it/privacy).",
        en: "Health-related data requires transparency and care. To learn in detail how data is collected, stored, secured, and how to request deletion through your account, please read our [privacy policy](/en/privacy).",
        es: "Los datos de salud requieren transparencia y cuidado. Para conocer en detalle cómo se recopilan, almacenan y protegen, y cómo solicitar su eliminación a través de tu cuenta, consulta la política de [privacidad](/es/privacy).",
        de: "Gesundheitsbezogene Daten erfordern Transparenz und Sorgfalt. Details zur Erhebung, Speicherung, Sicherheit und zur Beantragung der Löschung über dein Konto findest du in der [Datenschutzerklärung](/de/privacy).",
        pt: "Dados relativos à saúde exigem transparência e cuidado. Para conhecer detalhadamente como os dados são coletados, armazenados e protegidos, e como solicitar a exclusão pela sua conta, consulte a política de [privacidade](/pt/privacy).",
        fr: "Les données de santé exigent transparence et rigueur. Pour savoir en détail comment les données sont collectées, conservées, sécurisées et comment en demander la suppression via votre compte, consultez la politique de [confidentialité](/fr/privacy).",
        pl: "Dane dotyczące zdrowia wymagają przejrzystości i szczególnej dbałości. Szczegółowe informacje o sposobie zbierania, przechowywania, zabezpieczania oraz usuwania danych przez Twoje konto znajdziesz w polityce [prywatności](/pl/privacy).",
        tr: "Sağlıkla ilgili veriler şeffaflık ve özen gerektirir. Verilerin nasıl toplandığı, saklandığı, korunduğu ve hesabınız üzerinden silinmesini nasıl talep edebileceğiniz hakkında ayrıntılı bilgi için [gizlilik](/tr/privacy) sayfamızı inceleyin.",
        nl: "Gezondheidsgegevens vereisen transparantie en zorgvuldigheid. Lees ons [privacybeleid](/nl/privacy) voor meer informatie over hoe gegevens worden verzameld, opgeslagen, beveiligd en hoe je verwijdering via je account kunt aanvragen.",
        ja: "健康に関するデータには透明性と慎重な管理が求められます。データの収集、保存、保護の方法や、アカウントを通じた削除リクエストの詳細については、[プライバシーポリシー](/ja/privacy)をご覧ください。",
        ko: "건강 관련 데이터는 투명성과 신중한 관리가 필수적입니다. 데이터의 수집, 저장, 보안 및 계정을 통한 삭제 요청 방법에 대한 자세한 내용은 [개인정보 처리방침](/ko/privacy)에서 확인하실 수 있습니다.",
      },
    },
    {
      type: "callout",
      variant: "tip",
      title: {
        it: "Promozione iniziale di lancio: Pro a vita per i primi 1000 iscritti (conclusa il 31 luglio 2026)",
        en: "Initial launch promotion: lifetime Pro for the first 1,000 sign-ups (ended July 31, 2026)",
        es: "Promoción inicial de lanzamiento: Pro de por vida para los primeros 1000 registrados (finalizada el 31 de julio de 2026)",
        de: "Ursprüngliche Einführungsaktion: lebenslang Pro für die ersten 1000 Anmeldungen (beendet am 31. Juli 2026)",
        pt: "Promoção inicial de lançamento: Pro vitalício para os primeiros 1000 inscritos (encerrada em 31 de julho de 2026)",
        fr: "Promotion initiale de lancement: Pro à vie pour les 1000 premiers inscrits (terminée le 31 juillet 2026)",
        pl: "Początkowa promocja premierowa: dożywotnie Pro dla pierwszych 1000 zarejestrowanych (zakończona 31 lipca 2026)",
        tr: "İlk lansman promosyonu: ilk 1000 kayıt için ömür boyu Pro (31 Temmuz 2026'da sona erdi)",
        nl: "Oorspronkelijke lanceringsactie: levenslang Pro voor de eerste 1000 registraties (afgelopen op 31 juli 2026)",
        ja: "初期ローンチプロモーション：先着1000名への永久版Pro（2026年7月31日に終了）",
        ko: "초기 출시 프로모션: 선착순 1000명 대상 평생 Pro (2026년 7월 31일 종료)",
      },
      body: {
        it: "Durante la prima finestra di lancio dell'app, i primi 1000 account registrati entro il 31 luglio 2026 hanno ottenuto il Pro a vita gratuito. La promozione è ora conclusa; le condizioni storiche dell'iniziativa restano documentate nella pagina [Founder](/it/beta).",
        en: "During the initial app launch window, the first 1,000 accounts registered by July 31, 2026 received free lifetime Pro. That promotion is now closed; the historical terms of the initiative remain documented on the [Founder](/en/beta) page.",
        es: "Durante la primera ventana de lanzamiento de la app, las primeras 1000 cuentas registradas hasta el 31 de julio de 2026 obtuvieron Pro de por vida gratuito. La promoción ya ha concluido; los términos históricos de la iniciativa siguen documentados en la página [Founder](/es/beta).",
        de: "Während des ersten Startzeitraums der App erhielten die ersten 1000 bis zum 31. Juli 2026 registrierten Konten kostenloses Pro auf Lebenszeit. Die Aktion ist mittlerweile beendet; die historischen Bedingungen der Initiative sind auf der [Founder](/de/beta)-Seite dokumentiert.",
        pt: "Durante o período inicial de lançamento do aplicativo, as primeiras 1000 contas cadastradas até 31 de julho de 2026 obtiveram o Pro vitalício gratuito. A promoção já está encerrada; as condições históricas da iniciativa continuam documentadas na página [Founder](/pt/beta).",
        fr: "Durant la phase initiale de lancement de l'application, les 1000 premiers comptes enregistrés avant le 31 juillet 2026 ont bénéficié du Pro à vie gratuit. Cette offre est désormais terminée; les conditions historiques de l'initiative restent consultables sur la page [Founder](/fr/beta).",
        pl: "W początkowym okresie premiery aplikacji pierwszych 1000 kont zarejestrowanych do 31 lipca 2026 r. otrzymało bezpłatny dożywotni pakiet Pro. Promocja dobiegła końca; historyczne warunki inicjatywy pozostają udokumentowane na stronie [Founder](/pl/beta)." ,
        tr: "Uygulamanın ilk lansman döneminde, 31 Temmuz 2026 tarihine kadar kaydolan ilk 1000 hesap ücretsiz ömür boyu Pro kazandı. Kampanya sona ermiştir; girişimin geçmiş koşulları [Founder](/tr/beta) sayfasında arşivlenmiştir.",
        nl: "Tijdens de eerste lanceringsperiode ontvingen de eerste 1000 accounts die zich vóór 31 juli 2026 registreerden gratis levenslang Pro. De actie is inmiddels gesloten; de historische voorwaarden blijven gedocumenteerd op de [Founder](/nl/beta)-pagina.",
        ja: "アプリの初期ローンチ期間中、2026年7月31日までに登録された先着1000アカウントには無料の永久版Proが付与されました。このプロモーションは現在終了しています。当時の条件は[Founder](/ja/beta)ページに記録されています。",
        ko: "앱 초기 출시 기간 동안 2026년 7월 31일까지 등록된 선착순 1000개 계정은 무료 평생 Pro를 받았습니다. 해당 프로모션은 현재 종료되었으며, 당시의 조건은 [Founder](/ko/beta) 페이지에 기록되어 있습니다.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "L'app è già live anche su iPhone",
        en: "The iPhone app is already live too",
        es: "La app para iPhone también ya está disponible",
        de: "Die iPhone-App ist ebenfalls schon live",
        pt: "O app para iPhone também já está disponível",
        fr: "L'app iPhone est elle aussi déjà disponible",
        pl: "Aplikacja na iPhone'a jest już dostępna",
        tr: "iPhone uygulaması da zaten yayında",
        nl: "De iPhone-app is ook al live",
        ja: "iPhone版もすでに提供中",
        ko: "iPhone 앱도 이미 출시",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "FitMesh Sync è arrivato anche su iPhone: l'app iOS è già disponibile, incluse tutte le storefront dell'Unione Europea. Scopri tutti i dettagli qui: [FitMesh Sync arriva su iPhone](/it/blog/fitmesh-arriva-su-iphone).",
        en: "FitMesh Sync has also arrived on iPhone: the iOS app is already available, including all European Union storefronts. Read all the details here: [FitMesh Sync is coming to iPhone](/en/blog/fitmesh-arriva-su-iphone).",
        es: "FitMesh Sync también ha llegado a iPhone: la app iOS ya está disponible, incluidas todas las tiendas de la Unión Europea. Descubre todos los detalles aquí: [FitMesh Sync llega a iPhone](/es/blog/fitmesh-arriva-su-iphone).",
        de: "FitMesh Sync ist jetzt auch für das iPhone da: Die iOS-App ist bereits verfügbar, einschließlich aller Storefronts der Europäischen Union. Alle Details findest du hier: [FitMesh Sync kommt auf das iPhone](/de/blog/fitmesh-arriva-su-iphone).",
        pt: "O FitMesh Sync também chegou ao iPhone: o app iOS já está disponível, incluindo todas as lojas da União Europeia. Veja todos os detalhes aqui: [FitMesh Sync chega ao iPhone](/pt/blog/fitmesh-arriva-su-iphone).",
        fr: "FitMesh Sync est aussi arrivé sur iPhone: l'app iOS est déjà disponible, y compris dans toutes les boutiques de l'Union européenne. Découvrez tous les détails ici: [FitMesh Sync arrive sur iPhone](/fr/blog/fitmesh-arriva-su-iphone).",
        pl: "FitMesh Sync trafił też na iPhone'a: aplikacja iOS jest już dostępna, we wszystkich sklepach Unii Europejskiej. Wszystkie szczegóły znajdziesz tutaj: [FitMesh Sync trafia na iPhone'a](/pl/blog/fitmesh-arriva-su-iphone).",
        tr: "FitMesh Sync artık iPhone'da da var: iOS uygulaması Avrupa Birliği'ndeki tüm mağazalar dahil olmak üzere zaten kullanılabilir. Tüm ayrıntıları burada bulabilirsiniz: [FitMesh Sync iPhone'a geliyor](/tr/blog/fitmesh-arriva-su-iphone).",
        nl: "FitMesh Sync is ook op iPhone gearriveerd: de iOS-app is al beschikbaar, inclusief alle winkels van de Europese Unie. Lees hier alle details: [FitMesh Sync komt naar iPhone](/nl/blog/fitmesh-arriva-su-iphone).",
        ja: "FitMesh SyncはiPhoneにも対応しました。iOS版はすでにEU域内を含め提供中で、詳細はこちらをご覧ください：[FitMesh Sync、iPhoneに対応予定](/ja/blog/fitmesh-arriva-su-iphone)。",
        ko: "FitMesh Sync가 iPhone에도 출시되었습니다. iOS 앱은 이미 EU 지역을 포함하여 출시되었습니다. 자세한 내용은 여기에서 확인하세요: [FitMesh Sync, iPhone 출시 예정](/ko/blog/fitmesh-arriva-su-iphone).",
      },
    },
    {
      type: "fitmesh-editorial-cta",
      contentCluster: "general",
      placement: "article_end",
      title: {
        it: "Scarica FitMesh Sync per Android e iPhone",
        en: "Download FitMesh Sync for Android and iPhone",
        es: "Descarga FitMesh Sync para Android y iPhone",
        de: "FitMesh Sync für Android und iPhone herunterladen",
        pt: "Baixe o FitMesh Sync para Android e iPhone",
        fr: "Téléchargez FitMesh Sync pour Android et iPhone",
        pl: "Pobierz FitMesh Sync na Androida i iPhone'a",
        tr: "Android ve iPhone için FitMesh Sync'i indirin",
        nl: "Download FitMesh Sync voor Android en iPhone",
        ja: "AndroidとiPhoneでFitMesh Syncをダウンロード",
        ko: "Android 및 iPhone용 FitMesh Sync 다운로드",
        sv: "Ladda ner FitMesh Sync för Android och iPhone",
        da: "Download FitMesh Sync til Android og iPhone",
        no: "Last ned FitMesh Sync for Android og iPhone",
        fi: "Lataa FitMesh Sync Androidille ja iPhonelle",
      },
      body: {
        it: "L'app è disponibile su Google Play e su App Store. Collega smartwatch e anello, crea il tuo account e vedi i dati dei tuoi dispositivi uniti in un unico posto.",
        en: "The app is available on Google Play and the App Store. Connect your watch and ring, create your account, and see your devices' data unified in one place.",
        es: "La app está disponible en Google Play y en App Store. Conecta tu smartwatch y tu anillo, crea tu cuenta y ve los datos de tus dispositivos reunidos en un único lugar.",
        de: "Die App ist auf Google Play und im App Store verfügbar. Verbinde Smartwatch und Ring, erstelle dein Konto und sieh die Daten deiner Geräte an einem einzigen Ort vereint.",
        pt: "O app está disponível no Google Play e na App Store. Conecte seu smartwatch e seu anel, crie sua conta e veja os dados dos seus dispositivos reunidos em um único lugar.",
        fr: "L'application est disponible sur Google Play et sur l'App Store. Connectez votre montre et votre bague, créez votre compte et consultez les données de vos appareils réunies en un seul endroit.",
        pl: "Aplikacja jest dostępna w Google Play i App Store. Podłącz smartwatch i pierścień, utwórz konto i zobacz dane ze swoich urządzeń w jednym miejscu.",
        tr: "Uygulama Google Play ve App Store'da mevcuttur. Akıllı saatinizi ve yüzüğünüzü bağlayın, hesabınızı oluşturun ve cihazlarınızın verilerini tek bir yerde görün.",
        nl: "De app is beschikbaar in Google Play en de App Store. Koppel je smartwatch en slimme ring, maak je account aan en bekijk de gegevens van je apparaten op één plek.",
        ja: "アプリはGoogle PlayおよびApp Storeで入手できます。スマートウォッチとリングを接続し、アカウントを作成して、デバイスのデータを1か所でまとめて確認しましょう。",
        ko: "앱은 Google Play와 App Store에서 다운로드할 수 있습니다. 스마트워치와 링을 연결하고, 계정을 만들어 기기들의 데이터를 한곳에서 확인하세요.",
        sv: "Appen finns tillgänglig på Google Play och App Store. Anslut din smartklocka och ring, skapa ditt konto och se dina enheters data samlade på ett ställe.",
        da: "Appen er tilgængelig på Google Play og App Store. Tilslut dit smartwatch og din ring, opret din konto og se dine enheders data samlet ét sted.",
        no: "Appen er tilgjengelig på Google Play og App Store. Koble til smartklokken og ringen din, opprett kontoen din og se enhetsdataene dine samlet på ett sted.",
        fi: "Sovellus on saatavilla Google Playssa ja App Storessa. Yhdistä älykellosi ja sormuksesi, luo tili ja näe laitteidesi tiedot yhdessä paikassa.",
      },
      benefits: {
        it: [
          "Disponibile su Google Play e App Store",
          "Unisci più smartwatch e smart ring compatibili",
        ],
        en: [
          "Available on Google Play and the App Store",
          "Combine multiple compatible smartwatches and rings",
        ],
        es: [
          "Disponible en Google Play y App Store",
          "Combina varios smartwatches y anillos inteligentes compatibles",
        ],
        de: [
          "Auf Google Play und im App Store verfügbar",
          "Kombiniere mehrere kompatible Smartwatches und Ringe",
        ],
        pt: [
          "Disponível no Google Play e na App Store",
          "Combine vários smartwatches e anéis inteligentes compatíveis",
        ],
        fr: [
          "Disponible sur Google Play et l'App Store",
          "Combinez plusieurs montres et bagues connectées compatibles",
        ],
        pl: [
          "Dostępne w Google Play i App Store",
          "Połącz wiele kompatybilnych smartwatchy i pierścieni",
        ],
        tr: [
          "Google Play ve App Store'da mevcut",
          "Birden fazla uyumlu akıllı saat ve yüzüğü birleştirin",
        ],
        nl: [
          "Beschikbaar in Google Play en de App Store",
          "Combineer meerdere compatibele smartwatches en ringen",
        ],
        ja: [
          "Google PlayとApp Storeの両方で利用可能",
          "対応するスマートウォッチとスマートリングを統合",
        ],
        ko: [
          "Google Play 및 App Store에서 모두 이용 가능",
          "호환되는 여러 스마트워치와 스마트 링 통합",
        ],
        sv: [
          "Tillgänglig på Google Play och App Store",
          "Kombinera flera kompatibla smartklockor och ringar",
        ],
        da: [
          "Tilgængelig på Google Play og App Store",
          "Kombiner flere kompatible smartwatches og ringe",
        ],
        no: [
          "Tilgjengelig på Google Play og App Store",
          "Kombiner flere kompatible smartklokker og ringer",
        ],
        fi: [
          "Saatavilla Google Playssa ja App Storessa",
          "Yhdistä useita yhteensopivia älykelloja ja -sormuksia",
        ],
      },
      secondaryLabel: {
        it: "Vedi tutte le integrazioni",
        en: "See all integrations",
        es: "Ver todas las integraciones",
        de: "Alle Integrationen ansehen",
        pt: "Ver todas as integrações",
        fr: "Voir toutes les intégrations",
        pl: "Zobacz wszystkie integracje",
        tr: "Tüm entegrasyonları görün",
        nl: "Bekijk alle integraties",
        ja: "すべての連携を見る",
        ko: "모든 연동 보기",
        sv: "Se alla integrationer",
        da: "Se alle integrationer",
        no: "Se alle integrasjoner",
        fi: "Katso kaikki integraatiot",
      },
      secondaryHref: {
        it: "/it/integrations",
        en: "/en/integrations",
      },
    },
  ],
  faq: [
    {
      q: {
        it: "Quanto costa FitMesh Sync?",
        en: "How much does FitMesh Sync cost?",
        es: "¿Cuánto cuesta FitMesh Sync?",
        de: "Was kostet FitMesh Sync?",
        pt: "Quanto custa o FitMesh Sync?",
        fr: "Combien coûte FitMesh Sync?",
        pl: "Ile kosztuje FitMesh Sync?",
        tr: "FitMesh Sync ne kadar?",
        nl: "Wat kost FitMesh Sync?",
        ja: "FitMesh Syncはいくらですか？",
        ko: "FitMesh Sync는 얼마인가요?",
      },
      a: {
        it: "Puoi provare le funzionalità Pro gratuitamente per 14 giorni. Successivamente puoi scegliere tra un abbonamento ogni 6 mesi oppure l'acquisto una tantum a vita. (I primi 1000 iscritti nella fase iniziale di lancio, fino al 31 luglio 2026, hanno ricevuto il Pro a vita come promozione storica).",
        en: "You can try Pro features free for 14 days. Afterwards you can choose between a 6-month subscription or a one-time lifetime unlock. (The first 1,000 sign-ups during the initial launch phase, up to July 31, 2026, received lifetime Pro as a historical promotion).",
        es: "Puedes probar las funciones Pro gratis durante 14 días. Después puedes elegir entre una suscripción cada 6 meses o una compra única de por vida. (Los primeros 1000 registrados en la fase inicial de lanzamiento, hasta el 31 de julio de 2026, recibieron Pro de por vida como promoción histórica).",
        de: "Du kannst alle Pro-Funktionen 14 Tage lang kostenlos testen. Danach kannst du zwischen einem 6-Monats-Abonnement oder einem einmaligen lebenslangen Kauf wählen. (Die ersten 1000 Anmeldungen in der anfänglichen Startphase bis zum 31. Juli 2026 erhielten Pro auf Lebenszeit im Rahmen einer historischen Aktion).",
        pt: "Você pode testar os recursos Pro gratuitamente por 14 dias. Em seguida, pode escolher entre uma assinatura semestral ou a compra única vitalícia. (Os primeiros 1000 cadastrados na fase inicial de lançamento, até 31 de julho de 2026, receberam Pro vitalício como promoção histórica).",
        fr: "Vous pouvez tester les fonctionnalités Pro gratuitement pendant 14 jours. Ensuite, vous pouvez choisir entre un abonnement semestriel ou un achat unique à vie. (Les 1000 premiers inscrits lors du lancement initial, jusqu'au 31 juillet 2026, ont bénéficié du Pro à vie dans le cadre d'une offre historique).",
        pl: "Możesz wypróbować funkcje Pro bezpłatnie przez 14 dni. Następnie możesz wybrać subskrypcję co 6 miesięcy lub jednorazowy zakup na całe życie. (Pierwszych 1000 zarejestrowanych w początkowej fazie premiery, do 31 lipca 2026 r., otrzymało dożywotnie Pro w ramach historycznej promocji).",
        tr: "Pro özelliklerini 14 gün boyunca ücretsiz deneyebilirsiniz. Sonrasında 6 aylık abonelik veya tek seferlik ömür boyu kilit açma arasında seçim yapabilirsiniz. (31 Temmuz 2026'ya kadar ilk lansman aşamasında kaydolan ilk 1000 kullanıcı, geçmiş promosyon kapsamında ömür boyu Pro aldı).",
        nl: "Je kunt de Pro-functies 14 dagen gratis uitproberen. Daarna kun je kiezen tussen een abonnement per 6 maanden of een eenmalige levenslange aankoop. (De eerste 1000 aanmeldingen tijdens de eerste lanceringsfase, tot 31 juli 2026, ontvingen levenslang Pro via een historische actie).",
        ja: "Pro機能は14日間無料でお試しいただけます。その後は6か月ごとのサブスクリプションまたは買い切りの永久ライセンスから選択できます。（2026年7月31日までの初期ローンチ期間中に登録した先着1000名には、当時のプロモーションとして永久版Proが付与されました）。",
        ko: "Pro 기능은 14일 동안 무료로 체험해 볼 수 있습니다. 이후에는 6개월 구독 또는 일회성 평생 구매 중에서 선택할 수 있습니다. (2026년 7월 31일까지 초기 출시 단계에서 등록한 선착순 1000명은 당시 프로모션으로 평생 Pro를 받았습니다).",
      },
    },
    {
      q: {
        it: "Quali dispositivi sono compatibili?",
        en: "Which devices are compatible?",
        es: "¿Qué dispositivos son compatibles?",
        de: "Welche Geräte sind kompatibel?",
        pt: "Quais dispositivos são compatíveis?",
        fr: "Quels appareils sont compatibles?",
        pl: "Które urządzenia są kompatybilne?",
        tr: "Hangi cihazlar uyumludur?",
        nl: "Welke apparaten zijn compatibel?",
        ja: "対応デバイスはどれですか？",
        ko: "어떤 기기가 호환되나요?",
      },
      a: {
        it: "Tutti i dispositivi che funzionano con Health Connect su Android: Galaxy Watch, Google Pixel Watch, Fitbit, Garmin, Polar, Mi Band, anelli smart e molti altri. Per Samsung Galaxy Watch c'è anche un collegamento diretto con Samsung Health.",
        en: "Any device that works with Health Connect on Android: Galaxy Watch, Google Pixel Watch, Fitbit, Garmin, Polar, Mi Band, smart rings and many more. For Samsung Galaxy Watch there is also a direct link with Samsung Health.",
        es: "Cualquier dispositivo que funcione con Health Connect en Android: Galaxy Watch, Google Pixel Watch, Fitbit, Garmin, Polar, Mi Band, anillos inteligentes y muchos más. Para Samsung Galaxy Watch también hay una conexión directa con Samsung Health.",
        de: "Alle Geräte, die mit Health Connect auf Android funktionieren: Galaxy Watch, Google Pixel Watch, Fitbit, Garmin, Polar, Mi Band, Smart-Ringe und viele mehr. Für Samsung Galaxy Watch gibt es außerdem eine direkte Verbindung mit Samsung Health.",
        pt: "Todos os dispositivos que funcionam com Health Connect no Android: Galaxy Watch, Google Pixel Watch, Fitbit, Garmin, Polar, Mi Band, anéis inteligentes e muitos outros. Para Samsung Galaxy Watch há também uma conexão direta com Samsung Health.",
        fr: "Tous les appareils qui fonctionnent avec Health Connect sur Android: Galaxy Watch, Google Pixel Watch, Fitbit, Garmin, Polar, Mi Band, bagues connectées et bien d'autres. Pour la Samsung Galaxy Watch, il existe également une connexion directe avec Samsung Health.",
        pl: "Każde urządzenie, które działa z Health Connect na Androidzie: Galaxy Watch, Google Pixel Watch, Fitbit, Garmin, Polar, Mi Band, inteligentne pierścionki i wiele innych. Dla Samsung Galaxy Watch istnieje również bezpośrednie połączenie z Samsung Health.",
        tr: "Android'de Health Connect ile çalışan her cihaz: Galaxy Watch, Google Pixel Watch, Fitbit, Garmin, Polar, Mi Band, akıllı yüzükler ve daha fazlası. Samsung Galaxy Watch için Samsung Health ile doğrudan bir bağlantı da mevcuttur.",
        nl: "Elk apparaat dat werkt met Health Connect op Android: Galaxy Watch, Google Pixel Watch, Fitbit, Garmin, Polar, Mi Band, slimme ringen en nog veel meer. Voor Samsung Galaxy Watch is er ook een directe koppeling met Samsung Health.",
        ja: "AndroidのHealth Connectと連携するすべてのデバイス：Galaxy Watch、Google Pixel Watch、Fitbit、Garmin、Polar、Mi Band、スマートリングなど多数。Samsung Galaxy WatchはSamsung Healthとの直接連携にも対応しています。",
        ko: "Android에서 Health Connect와 연동되는 모든 기기: Galaxy Watch, Google Pixel Watch, Fitbit, Garmin, Polar, Mi Band, 스마트 링 등 다양합니다. Samsung Galaxy Watch는 Samsung Health와의 직접 연동도 지원합니다.",
      },
    },
    {
      q: {
        it: "È disponibile anche su iPhone?",
        en: "Is it available on iPhone too?",
        es: "¿También está disponible en iPhone?",
        de: "Ist es auch für iPhone verfügbar?",
        pt: "Também está disponível para iPhone?",
        fr: "Est-ce aussi disponible sur iPhone ?",
        pl: "Czy jest też dostępne na iPhone'a?",
        tr: "iPhone'da da mevcut mu?",
        nl: "Is het ook beschikbaar voor iPhone?",
        ja: "iPhoneでも利用できますか？",
        ko: "iPhone에서도 이용할 수 있나요?",
      },
      a: {
        it: "Sì: l'app iOS è disponibile sull'App Store, incluse tutte le storefront dell'Unione Europea. I primi 1000 Founder (entro il 31 luglio 2026) hanno ricevuto il Pro a vita gratis anche su iPhone.",
        en: "Yes: the iOS app is available on the App Store, including all European Union storefronts. The first 1,000 Founders (by July 31, 2026) got lifetime Pro free on iPhone too.",
        es: "Sí: la app iOS está disponible en App Store, incluidas todas las tiendas de la Unión Europea. Los primeros 1000 Founders (hasta el 31 de julio de 2026) recibieron el Pro de por vida gratis también en iPhone.",
        de: "Ja: Die iOS-App ist im App Store verfügbar, einschließlich aller Storefronts der Europäischen Union. Die ersten 1000 Founder (bis 31. Juli 2026) haben lebenslang Pro kostenlos erhalten, auch auf dem iPhone.",
        pt: "Sim: o app iOS está disponível na App Store, incluindo todas as lojas da União Europeia. Os primeiros 1000 Founders (até 31 de julho de 2026) receberam o Pro vitalício grátis também no iPhone.",
        fr: "Oui: l'app iOS est disponible sur l'App Store, y compris dans toutes les boutiques de l'Union européenne. Les 1000 premiers Founders (jusqu'au 31 juillet 2026) ont reçu le Pro à vie gratuit, aussi sur iPhone.",
        pl: "Tak: aplikacja iOS jest dostępna w App Store, we wszystkich sklepach Unii Europejskiej. Pierwsze 1000 osób Founder (do 31 lipca 2026) otrzymało dożywotnie Pro za darmo, także na iPhone'a.",
        tr: "Evet: iOS uygulaması App Store'da Avrupa Birliği'ndeki tüm mağazalar dahil olmak üzere kullanılabilir. İlk 1000 Founder (31 Temmuz 2026'ya kadar), iPhone'da da ömür boyu ücretsiz Pro aldı.",
        nl: "Ja: de iOS-app is beschikbaar in de App Store, inclusief alle winkels van de Europese Unie. De eerste 1000 Founders (tot 31 juli 2026) hebben ook op iPhone levenslang Pro gratis gekregen.",
        ja: "はい。iOS版はすでにEU域内を含めApp Storeで提供中で、先着1000名のFounder（2026年7月31日まで）はiPhoneでも永久版Proを無料で取得できました。",
        ko: "예. iOS 앱은 이미 EU 지역을 포함하여 App Store에서 출시되었습니다. 선착순 1000명의 Founder(2026년 7월 31일까지)는 iPhone에서도 평생 무료 Pro를 받았습니다.",
      },
    },
    {
      q: {
        it: "Dove vengono conservati i miei dati?",
        en: "Where is my data stored?",
        es: "¿Dónde se guardan mis datos?",
        de: "Wo werden meine Daten gespeichert?",
        pt: "Onde os meus dados são armazenados?",
        fr: "Où sont stockées mes données?",
        pl: "Gdzie są przechowywane moje dane?",
        tr: "Verilerim nerede saklanıyor?",
        nl: "Waar worden mijn gegevens opgeslagen?",
        ja: "データはどこに保存されますか？",
        ko: "내 데이터는 어디에 저장되나요?",
      },
      a: {
        it: "I dettagli su archiviazione, sicurezza e gestione dell'account sono consultabili nella nostra informativa sulla [privacy](/it/privacy), dove è descritta anche la procedura per richiedere la cancellazione dei tuoi dati.",
        en: "Details on storage, security, and account management can be found in our [privacy policy](/en/privacy), which also describes the process for requesting data deletion.",
        es: "Los detalles sobre almacenamiento, seguridad y gestión de la cuenta se encuentran en nuestra política de [privacidad](/es/privacy), donde también se describe cómo solicitar la eliminación de tus datos.",
        de: "Details zu Speicherung, Sicherheit und Kontoverwaltung findest du in unserer [Datenschutzerklärung](/de/privacy), in der auch die Vorgehensweise zur Löschung deiner Daten beschrieben ist.",
        pt: "Os detalhes sobre armazenamento, segurança e gerenciamento de conta podem ser consultados na nossa política de [privacidade](/pt/privacy), onde também se descreve o procedimento para exclusão dos dados.",
        fr: "Les détails concernant le stockage, la sécurité et la gestion du compte sont précisés dans notre politique de [confidentialité](/fr/privacy), qui décrit également la procédure de suppression de vos données.",
        pl: "Szczegóły dotyczące przechowywania, bezpieczeństwa i zarządzania kontem znajdują się w naszej polityce [prywatności](/pl/privacy), w której opisano również procedurę usuwania danych.",
        tr: "Veri depolama, güvenlik ve hesap yönetimine ilişkin ayrıntılara, verilerinizin silinmesini talep etme sürecinin de açıklandığı [gizlilik](/tr/privacy) politikamızdan ulaşabilirsiniz.",
        nl: "Details over opslag, beveiliging en accountbeheer vind je in ons [privacybeleid](/nl/privacy), waarin ook de procedure voor het verwijderen van gegevens wordt uitgelegd.",
        ja: "保管、セキュリティ、アカウント管理の詳細については[プライバシーポリシー](/ja/privacy)をご覧ください。データの削除リクエスト手順についても記載されています。",
        ko: "데이터 저장, 보안 및 계정 관리에 관한 자세한 내용은 [개인정보 처리방침](/ko/privacy)에서 확인하실 수 있으며, 데이터 삭제 요청 절차도 함께 안내되어 있습니다.",
      },
    },
  ],
  related: [
    "piu-smartwatch-insieme-dati-doppi",
    "novita-fonte-del-dato",
    "fitmesh-arriva-su-iphone",
    "sync-them-all",
  ],
};
