import type { BlogPost } from "../types";

export const post: BlogPost = {
  slug: "fitmesh-sync-disponibile-google-play",
  category: "news",
  publishedAt: "2026-06-14",
  updatedAt: "2026-06-14",
  ldType: "BlogPosting",
  readMinutes: 3,
  primaryKeyword: {
    it: "FitMesh Sync su Google Play",
    en: "FitMesh Sync on Google Play",
    es: "FitMesh Sync en Google Play",
    de: "FitMesh Sync auf Google Play",
    pt: "FitMesh Sync no Google Play",
    fr: "FitMesh Sync sur Google Play",
    pl: "FitMesh Sync w Google Play",
    tr: "FitMesh Sync Google Play'de",
  },
  secondaryKeywords: {
    it: [
      "app per unire i dati dello smartwatch",
      "dashboard salute Android",
      "scaricare FitMesh Sync",
      "app dati wearable in italiano",
      "un anno di Pro gratis founder",
    ],
    en: [
      "app to unify smartwatch data",
      "Android health dashboard",
      "download FitMesh Sync",
      "wearable data app",
      "free year of Pro founder",
    ],
    pt: [
      "app para unir dados do smartwatch",
      "painel de saúde Android",
      "baixar FitMesh Sync",
      "app de dados wearable",
      "um ano de Pro grátis founder",
    ],
    fr: [
      "app pour unifier les données du smartwatch",
      "tableau de bord santé Android",
      "télécharger FitMesh Sync",
      "app de données wearable",
      "un an de Pro gratuit founder",
    ],
    pl: [
      "aplikacja do łączenia danych ze smartwatcha",
      "panel zdrowia Android",
      "pobierz FitMesh Sync",
      "aplikacja danych wearable",
      "rok Pro za darmo dla założycieli",
    ],
    tr: [
      "akıllı saat verilerini birleştiren uygulama",
      "Android sağlık paneli",
      "FitMesh Sync indir",
      "giyilebilir cihaz veri uygulaması",
      "kuruculara ücretsiz bir yıl Pro",
    ],
  },
  metaDescription: {
    it: "FitMesh Sync è disponibile su Google Play: unisci i dati di smartwatch e anello in un'unica dashboard, con i tuoi dati su server in Europa. La versione iPhone arriva tra pochi giorni.",
    en: "FitMesh Sync is now on Google Play: bring your smartwatch and ring data into one dashboard, with your data on servers in Europe. The iPhone version arrives in a few days.",
    es: "FitMesh Sync ya está disponible en Google Play: une los datos de tu smartwatch y tu anillo en un único panel, con tus datos en servidores en Europa. La versión para iPhone llega en pocos días.",
    de: "FitMesh Sync ist jetzt auf Google Play: Führe Smartwatch- und Ring-Daten in einer Dashboard zusammen, mit deinen Daten auf Servern in Europa. Die iPhone-Version kommt in wenigen Tagen.",
    pt: "FitMesh Sync está disponível no Google Play: reúna os dados do seu smartwatch e anel em um único painel, com seus dados em servidores na Europa. A versão para iPhone chega em poucos dias.",
    fr: "FitMesh Sync est maintenant sur Google Play: regroupez les données de votre montre connectée et de votre bague en un seul tableau de bord, avec vos données sur des serveurs en Europe. La version iPhone arrive dans quelques jours.",
    pl: "FitMesh Sync jest teraz w Google Play: połącz dane ze swojego smartwatcha i pierścionka w jednym panelu, z danymi na serwerach w Europie. Wersja na iPhone'a pojawi się za kilka dni.",
    tr: "FitMesh Sync artık Google Play'de: akıllı saat ve yüzük verilerinizi tek bir panelde birleştirin, verileriniz Avrupa'daki sunucularda saklanır. iPhone sürümü birkaç gün içinde geliyor.",
  },
  tldr: {
    it: [
      "FitMesh Sync è ora scaricabile su Google Play, per tutti i telefoni Android.",
      "Unisci smartwatch, anello e altri dispositivi in un'unica dashboard, senza saltare tra app.",
      "I tuoi dati restano su server in Europa, senza pubblicità e senza rivendita a terzi.",
      "I primi a registrarsi ricevono un anno di Pro gratis. La versione iPhone arriva tra pochi giorni.",
    ],
    en: [
      "FitMesh Sync is now available on Google Play, for every Android phone.",
      "Bring your watch, ring and other devices into one dashboard, without jumping between apps.",
      "Your data stays on servers in Europe, with no ads and no reselling to third parties.",
      "The first to sign up get a free year of Pro. The iPhone version arrives in a few days.",
    ],
    es: [
      "FitMesh Sync ya está disponible en Google Play, para todos los teléfonos Android.",
      "Une tu smartwatch, tu anillo y otros dispositivos en un único panel, sin saltar entre apps.",
      "Tus datos permanecen en servidores en Europa, sin publicidad y sin cederlos a terceros.",
      "Los primeros en registrarse reciben un año de Pro gratis. La versión para iPhone llega en pocos días.",
    ],
    de: [
      "FitMesh Sync ist jetzt auf Google Play verfügbar, für alle Android-Smartphones.",
      "Führe Smartwatch, Ring und andere Geräte in einer Dashboard zusammen, ohne zwischen Apps zu wechseln.",
      "Deine Daten bleiben auf Servern in Europa, ohne Werbung und ohne Weitergabe an Dritte.",
      "Die Ersten, die sich registrieren, erhalten ein Jahr Pro kostenlos. Die iPhone-Version kommt in wenigen Tagen.",
    ],
    pt: [
      "FitMesh Sync já está disponível no Google Play, para todos os celulares Android.",
      "Reúna seu smartwatch, anel e outros dispositivos em um único painel, sem precisar alternar entre apps.",
      "Seus dados ficam em servidores na Europa, sem anúncios e sem revenda a terceiros.",
      "Os primeiros a se cadastrar recebem um ano de Pro grátis. A versão para iPhone chega em poucos dias.",
    ],
    fr: [
      "FitMesh Sync est maintenant disponible sur Google Play, pour tous les téléphones Android.",
      "Regroupez votre montre connectée, votre bague et vos autres appareils dans un seul tableau de bord, sans jongler entre les applications.",
      "Vos données restent sur des serveurs en Europe, sans publicité et sans revente à des tiers.",
      "Les premiers inscrits reçoivent un an de Pro gratuit. La version iPhone arrive dans quelques jours.",
    ],
    pl: [
      "FitMesh Sync jest dostępny w Google Play. Pobierz, podłącz swoje urządzenie, zaloguj się i zacznij synchronizować - bez konfiguracji poza telefonem.",
      "Health Connect to most między Twoim wearablem a wszystkimi innymi aplikacjami Android. FitMesh Sync odczytuje z niego dane zdrowotne i synchronizuje je z chmurą EU.",
      "Dane są przechowywane wyłącznie w Europie. Żadnych reklam, żadnych danych przekazywanych podmiotom trzecim, żadnych niejasnych warunków usługi.",
      "Przez pierwsze 60 dni jest bezpłatny dla każdego, kto pobierze z Google Play. Po tym czasie obowiązuje subskrypcja założyciela.",
    ],
    tr: [
      "FitMesh Sync Google Play'de mevcut. İndirin, cihazınızı bağlayın, giriş yapın ve senkronizasyona başlayın - telefon dışında herhangi bir kurulum gerekmez.",
      "Health Connect, giyilebilir cihazınız ile diğer tüm Android uygulamaları arasındaki köprüdür. FitMesh Sync buradan sağlık verilerini okur ve AB bulutuna senkronize eder.",
      "Veriler yalnızca Avrupa'da depolanır. Reklam yok, üçüncü taraflara veri yok, şifreli hizmet koşulları yok.",
      "Google Play'den indirenler için ilk 60 gün ücretsizdir. Daha sonra kurucu aboneliği uygulanır.",
    ],
  },
  hero: {
    kicker: {
      it: "Novità",
      en: "What's New",
      es: "Novedades",
      de: "Neuigkeiten",
      pt: "Novidades",
      fr: "Nouveauté",
      pl: "Nowości",
      tr: "Yenilikler",
    },
    title: {
      it: "FitMesh Sync è disponibile su Google Play",
      en: "FitMesh Sync is now on Google Play",
      es: "FitMesh Sync ya está disponible en Google Play",
      de: "FitMesh Sync ist jetzt auf Google Play verfügbar",
      pt: "FitMesh Sync já está disponível no Google Play",
      fr: "FitMesh Sync est maintenant disponible sur Google Play",
      pl: "FitMesh Sync jest teraz dostępny w Google Play",
      tr: "FitMesh Sync artık Google Play'de",
    },
    subtitle: {
      it: "Da oggi puoi scaricare l'app e vedere i dati di tutti i tuoi dispositivi in una sola dashboard. La versione per iPhone arriva tra pochi giorni.",
      en: "Starting today you can download the app and see all your devices' data in one dashboard. The iPhone version arrives in a few days.",
      es: "Desde hoy puedes descargar la app y ver los datos de todos tus dispositivos en un único panel. La versión para iPhone llega en pocos días.",
      de: "Ab heute kannst du die App herunterladen und die Daten all deiner Geräte in einer Dashboard sehen. Die iPhone-Version kommt in wenigen Tagen.",
      pt: "A partir de hoje você pode baixar o app e ver os dados de todos os seus dispositivos em um único painel. A versão para iPhone chega em poucos dias.",
      fr: "Dès aujourd'hui, vous pouvez télécharger l'application et consulter les données de tous vos appareils dans un seul tableau de bord. La version iPhone arrive dans quelques jours.",
      pl: "Od dziś możesz pobrać aplikację i przeglądać dane wszystkich swoich urządzeń w jednym panelu. Wersja na iPhone'a pojawi się za kilka dni.",
      tr: "Bugünden itibaren uygulamayı indirebilir ve tüm cihazlarınızın verilerini tek bir panelde görebilirsiniz. iPhone sürümü birkaç gün içinde geliyor.",
    },
  },
  body: [
    {
      type: "paragraph",
      text: {
        it: "Ci siamo: FitMesh Sync è ufficialmente disponibile su Google Play. Puoi scaricarla su qualsiasi telefono Android e iniziare subito a vedere i dati del tuo smartwatch, del tuo anello e degli altri dispositivi in un unico posto.",
        en: "It is here: FitMesh Sync is officially available on Google Play. You can download it on any Android phone and start seeing your smartwatch, ring and other devices' data all in one place.",
        es: "Ya está aquí: FitMesh Sync está disponible oficialmente en Google Play. Puedes descargarla en cualquier teléfono Android y empezar a ver los datos de tu smartwatch, tu anillo y el resto de tus dispositivos en un único lugar.",
        de: "Es ist so weit: FitMesh Sync ist offiziell auf Google Play verfügbar. Du kannst sie auf jedem Android-Smartphone herunterladen und sofort die Daten deines Smartwatchs, deines Rings und anderer Geräte an einem einzigen Ort sehen.",
        pt: "Chegou: FitMesh Sync está disponível oficialmente no Google Play. Você pode baixá-lo em qualquer celular Android e começar a ver agora mesmo os dados do seu smartwatch, do seu anel e de outros dispositivos, tudo em um único lugar.",
        fr: "C'est ici: FitMesh Sync est officiellement disponible sur Google Play. Vous pouvez le télécharger sur n'importe quel téléphone Android et commencer à consulter les données de votre montre connectée, de votre bague et de vos autres appareils au même endroit.",
        pl: "Stało się: FitMesh Sync jest oficjalnie dostępny w Google Play. Możesz go pobrać na dowolny telefon z Androidem i zacząć widzieć dane swojego smartwatcha, pierścionka i innych urządzeń w jednym miejscu.",
        tr: "Geldi: FitMesh Sync resmi olarak Google Play'de mevcut. Herhangi bir Android telefona indirebilir ve akıllı saatinizin, yüzüğünüzün ve diğer cihazlarınızın verilerini tek bir yerde görmeye hemen başlayabilirsiniz.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Cosa fa FitMesh Sync",
        en: "What FitMesh Sync does",
        es: "Qué hace FitMesh Sync",
        de: "Was FitMesh Sync kann",
        pt: "O que o FitMesh Sync faz",
        fr: "Ce que fait FitMesh Sync",
        pl: "Co robi FitMesh Sync",
        tr: "FitMesh Sync ne yapar",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Ogni marca tiene i tuoi dati dentro la propria app. Se hai un Galaxy Watch, un anello smart e magari una band di un altro produttore, finisci per saltare da un'app all'altra. FitMesh Sync li raccoglie tutti in una dashboard unica e chiara: passi, sonno, battito, recupero e andamento nel tempo, in italiano e pensata per la lettura di tutti i giorni.",
        en: "Every brand keeps your data inside its own app. If you have a Galaxy Watch, a smart ring and maybe a band from another maker, you end up jumping from one app to another. FitMesh Sync brings them all into one clear dashboard: steps, sleep, heart rate, recovery and trends over time, designed for everyday reading.",
        es: "Cada marca guarda tus datos dentro de su propia app. Si tienes un Galaxy Watch, un anillo inteligente y quizás una pulsera de otro fabricante, acabas saltando de una app a otra. FitMesh Sync los reúne todos en un panel claro y único: pasos, sueño, frecuencia cardíaca, recuperación y tendencias a lo largo del tiempo, pensado para consultarlo cada día.",
        de: "Jede Marke hält deine Daten in ihrer eigenen App. Wenn du eine Galaxy Watch, einen Smart-Ring und vielleicht ein Band eines anderen Herstellers hast, springst du ständig zwischen Apps hin und her. FitMesh Sync bringt sie alle in eine übersichtliche Dashboard: Schritte, Schlaf, Herzfrequenz, Erholung und Trends über die Zeit, gestaltet für den täglichen Gebrauch.",
        pt: "Cada marca mantém seus dados dentro do próprio app. Se você tem um Galaxy Watch, um anel inteligente e talvez uma pulseira de outro fabricante, acaba pulando de app em app. FitMesh Sync reúne tudo em um único painel claro: passos, sono, frequência cardíaca, recuperação e tendências ao longo do tempo, pensado para a leitura do dia a dia.",
        fr: "Chaque marque conserve vos données dans sa propre application. Si vous avez une Galaxy Watch, une bague connectée et peut-être un bracelet d'un autre fabricant, vous finissez par jongler entre les applications. FitMesh Sync les rassemble toutes dans un tableau de bord clair et unique: pas, sommeil, fréquence cardiaque, récupération et tendances dans le temps, conçu pour une consultation quotidienne.",
        pl: "Każda marka trzyma Twoje dane we własnej aplikacji. Jeśli masz Galaxy Watch, inteligentny pierścionek i może opaskę innego producenta, skaczysz z jednej aplikacji do drugiej. FitMesh Sync zbiera je wszystkie w jeden przejrzysty panel: kroki, sen, tętno, regeneracja i trendy w czasie, zaprojektowany do codziennego przeglądania.",
        tr: "Her marka verilerinizi kendi uygulamasında tutar. Bir Galaxy Watch, akıllı yüzük ve belki başka bir üreticinin bandı varsa, sürekli uygulamalar arasında geçiş yaparsınız. FitMesh Sync hepsini tek, net bir panelde toplar: adımlar, uyku, kalp atış hızı, toparlanma ve zaman içindeki eğilimler - günlük okuma için tasarlanmış.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Più dispositivi, una vista sola",
        en: "More devices, one single view",
        es: "Varios dispositivos, una sola vista",
        de: "Mehrere Geräte, eine einzige Ansicht",
        pt: "Vários dispositivos, uma única visualização",
        fr: "Plusieurs appareils, une seule vue",
        pl: "Więcej urządzeń, jeden widok",
        tr: "Birden fazla cihaz, tek bir görünüm",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Se indossi più dispositivi insieme, FitMesh Sync li unisce senza contare due volte gli stessi passi e ti mostra sempre il dato più completo. Quando un dispositivo è in carica, un altro copre quel periodo senza lasciare buchi. Abbiamo spiegato tutto, con esempi per ogni combinazione, nella guida [più smartwatch insieme senza dati doppi](/it/blog/piu-smartwatch-insieme-dati-doppi).",
        en: "If you wear several devices together, FitMesh Sync merges them without counting the same steps twice and always shows you the most complete value. When one device is charging, another covers that window with no gaps. We explained it all, with examples for each combination, in the guide [multiple smartwatches together without double data](/en/blog/piu-smartwatch-insieme-dati-doppi).",
        es: "Si llevas varios dispositivos a la vez, FitMesh Sync los combina sin contar los mismos pasos dos veces y siempre te muestra el dato más completo. Cuando un dispositivo está cargando, otro cubre ese intervalo sin dejar huecos. Lo explicamos todo, con ejemplos para cada combinación, en la guía [varios smartwatches juntos sin datos duplicados](/es/blog/piu-smartwatch-insieme-dati-doppi).",
        de: "Wenn du mehrere Geräte gleichzeitig trägst, führt FitMesh Sync sie zusammen, ohne dieselben Schritte doppelt zu zählen, und zeigt dir immer den vollständigsten Wert. Wenn ein Gerät aufgeladen wird, deckt ein anderes diesen Zeitraum ohne Lücken ab. Alles erklärt, mit Beispielen für jede Kombination, in der Anleitung [mehrere Smartwatches zusammen ohne doppelte Daten](/de/blog/piu-smartwatch-insieme-dati-doppi).",
        pt: "Se você usa vários dispositivos ao mesmo tempo, FitMesh Sync os une sem contar os mesmos passos duas vezes e sempre mostra o dado mais completo. Quando um dispositivo está carregando, outro cobre esse período sem deixar lacunas. Explicamos tudo, com exemplos para cada combinação, no guia [vários smartwatches juntos sem dados duplicados](/pt/blog/piu-smartwatch-insieme-dati-doppi).",
        fr: "Si vous portez plusieurs appareils en même temps, FitMesh Sync les fusionne sans compter les mêmes pas deux fois et vous affiche toujours la valeur la plus complète. Quand un appareil est en charge, un autre couvre cette période sans laisser de trous. Nous avons tout expliqué, avec des exemples pour chaque combinaison, dans le guide [plusieurs montres connectées ensemble sans données en double](/fr/blog/piu-smartwatch-insieme-dati-doppi).",
        pl: "Jeśli nosisz kilka urządzeń jednocześnie, FitMesh Sync łączy je bez podwójnego liczenia tych samych kroków i zawsze pokazuje Ci najbardziej kompletną wartość. Gdy jedno urządzenie się ładuje, drugie pokrywa ten okres bez żadnych luk. Wyjaśniliśmy wszystko, z przykładami dla każdej kombinacji, w przewodniku [kilka smartwatchy jednocześnie bez duplikatów danych](/pl/blog/piu-smartwatch-insieme-dati-doppi).",
        tr: "Birden fazla cihaz takıyorsanız, FitMesh Sync aynı adımları iki kez saymadan hepsini birleştirir ve size her zaman en eksiksiz değeri gösterir. Bir cihaz şarj olurken diğeri o aralığı boşluksuz kapatır. Her kombinasyon için örneklerle tümünü [birden fazla akıllı saat - veriler çift sayılmaz](/tr/blog/piu-smartwatch-insieme-dati-doppi) rehberinde anlattık.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "I tuoi dati restano tuoi",
        en: "Your data stays yours",
        es: "Tus datos son solo tuyos",
        de: "Deine Daten bleiben deine",
        pt: "Seus dados continuam sendo seus",
        fr: "Vos données restent les vôtres",
        pl: "Twoje dane pozostają Twoje",
        tr: "Verileriniz size ait kalır",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "I dati di salute sono tra le cose più personali che hai. Per questo restano su server in Europa, accessibili solo a te tramite il tuo account, senza pubblicità e senza essere rivenduti a terzi. Trovi tutti i dettagli nella pagina [privacy](/it/privacy).",
        en: "Health data is among the most personal you have. That is why it stays on servers in Europe, accessible only to you through your account, with no ads and never resold to third parties. You can find all the details on the [privacy](/en/privacy) page.",
        es: "Los datos de salud son de las cosas más personales que tienes. Por eso permanecen en servidores en Europa, accesibles solo a través de tu cuenta, sin publicidad y sin cederlos a terceros. Encuentra todos los detalles en la página de [privacidad](/es/privacy).",
        de: "Gesundheitsdaten gehören zu den persönlichsten Dingen, die du hast. Deshalb bleiben sie auf Servern in Europa, nur für dich über dein Konto zugänglich, ohne Werbung und ohne Weitergabe an Dritte. Alle Details findest du auf der [Datenschutz](/de/privacy)-Seite.",
        pt: "Os dados de saúde estão entre as coisas mais pessoais que você tem. Por isso ficam em servidores na Europa, acessíveis apenas por você através da sua conta, sem anúncios e sem serem revendidos a terceiros. Todos os detalhes estão na página de [privacidade](/pt/privacy).",
        fr: "Les données de santé comptent parmi les informations les plus personnelles que vous possédez. C'est pourquoi elles restent sur des serveurs en Europe, accessibles uniquement à vous via votre compte, sans publicité et sans revente à des tiers. Retrouvez tous les détails sur la page [confidentialité](/fr/privacy).",
        pl: "Dane zdrowotne należą do najbardziej osobistych, jakie posiadasz. Dlatego pozostają na serwerach w Europie, dostępne tylko dla Ciebie przez Twoje konto, bez reklam i nigdy nie odsprzedawane osobom trzecim. Wszystkie szczegóły znajdziesz na stronie [prywatności](/pl/privacy).",
        tr: "Sağlık verileri en kişisel bilgilerinizden biridir. Bu nedenle Avrupa'daki sunucularda saklanır, yalnızca hesabınız aracılığıyla size erişilebilir, reklam yoktur ve üçüncü taraflara asla satılmaz. Tüm ayrıntıları [gizlilik](/tr/privacy) sayfasında bulabilirsiniz.",
      },
    },
    {
      type: "callout",
      variant: "tip",
      title: {
        it: "Un anno di Pro gratis ai primi che si iscrivono",
        en: "A free year of Pro for the first to sign up",
        es: "Un año de Pro gratis para los primeros en registrarse",
        de: "Ein Jahr Pro kostenlos für die Ersten, die sich registrieren",
        pt: "Um ano de Pro grátis para os primeiros a se cadastrar",
        fr: "Un an de Pro gratuit pour les premiers inscrits",
        pl: "Rok Pro za darmo dla pierwszych, którzy się zarejestrują",
        tr: "İlk kayıt olanlara ücretsiz bir yıl Pro",
      },
      body: {
        it: "Scarica l'app e crea l'account adesso: i primi 1000 ricevono un anno di Pro completo, che si attiva da solo. Niente carta, niente abbonamento. Dettagli nella pagina [Founder](/it/beta).",
        en: "Download the app and create your account now: the first 1000 get a full year of Pro that activates by itself. No card, no subscription. Details on the [Founder](/en/beta) page.",
        es: "Descarga la app y crea tu cuenta ahora: los primeros 1000 reciben un año completo de Pro que se activa solo. Sin tarjeta, sin suscripción. Detalles en la página [Founder](/es/beta).",
        de: "Lade die App herunter und erstelle jetzt dein Konto: Die ersten 1000 erhalten ein vollständiges Jahr Pro, das sich automatisch aktiviert. Keine Karte, kein Abonnement. Details auf der [Founder](/de/beta)-Seite.",
        pt: "Baixe o app e crie sua conta agora: os primeiros 1000 recebem um ano completo de Pro que se ativa automaticamente. Sem cartão, sem assinatura. Detalhes na página [Founder](/pt/beta).",
        fr: "Téléchargez l'application et créez votre compte maintenant: les 1000 premiers reçoivent un an complet de Pro qui s'active automatiquement. Pas de carte, pas d'abonnement. Détails sur la page [Founder](/fr/beta).",
        pl: "Pobierz aplikację i utwórz konto teraz: pierwsze 1000 osób otrzymuje pełny rok Pro, który aktywuje się automatycznie. Bez karty, bez subskrypcji. Szczegóły na stronie [Founder](/pl/beta).",
        tr: "Uygulamayı indirin ve hesabınızı şimdi oluşturun: ilk 1000 kişi kendiliğinden etkinleşen tam bir yıllık Pro alır. Kart yok, abonelik yok. Ayrıntılar [Founder](/tr/beta) sayfasında.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "La versione iPhone arriva tra pochi giorni",
        en: "The iPhone version arrives in a few days",
        es: "La versión para iPhone llega en pocos días",
        de: "Die iPhone-Version kommt in wenigen Tagen",
        pt: "A versão para iPhone chega em poucos dias",
        fr: "La version iPhone arrive dans quelques jours",
        pl: "Wersja na iPhone'a pojawi się za kilka dni",
        tr: "iPhone sürümü birkaç gün içinde geliyor",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Stiamo finendo gli ultimi passaggi per portare FitMesh Sync anche su iPhone: la versione iOS è in arrivo a giorni. Se vuoi essere avvisato appena esce, ne parliamo qui: [FitMesh Sync arriva su iPhone](/it/blog/fitmesh-arriva-su-iphone).",
        en: "We are finishing the last steps to bring FitMesh Sync to iPhone too: the iOS version is coming within days. If you want to be notified as soon as it is out, we talk about it here: [FitMesh Sync is coming to iPhone](/en/blog/fitmesh-arriva-su-iphone).",
        es: "Estamos terminando los últimos pasos para llevar FitMesh Sync también a iPhone: la versión iOS llega en pocos días. Si quieres recibir una notificación en cuanto esté disponible, hablamos de ello aquí: [FitMesh Sync llega a iPhone](/es/blog/fitmesh-arriva-su-iphone).",
        de: "Wir sind dabei, die letzten Schritte abzuschließen, um FitMesh Sync auch auf das iPhone zu bringen: Die iOS-Version ist in wenigen Tagen verfügbar. Wenn du benachrichtigt werden möchtest, sobald sie erscheint, findest du alles hier: [FitMesh Sync kommt auf das iPhone](/de/blog/fitmesh-arriva-su-iphone).",
        pt: "Estamos finalizando os últimos passos para levar FitMesh Sync também ao iPhone: a versão iOS chega em poucos dias. Se você quiser ser avisado assim que sair, falamos sobre isso aqui: [FitMesh Sync chega ao iPhone](/pt/blog/fitmesh-arriva-su-iphone).",
        fr: "Nous finalisons les dernières étapes pour apporter FitMesh Sync sur iPhone également: la version iOS arrive dans quelques jours. Si vous souhaitez être notifié dès sa sortie, nous en parlons ici: [FitMesh Sync arrive sur iPhone](/fr/blog/fitmesh-arriva-su-iphone).",
        pl: "Kończymy ostatnie kroki, żeby przynieść FitMesh Sync również na iPhone'a: wersja iOS pojawi się za kilka dni. Jeśli chcesz zostać powiadomiony, gdy tylko się ukaże, piszemy o tym tutaj: [FitMesh Sync trafia na iPhone'a](/pl/blog/fitmesh-arriva-su-iphone).",
        tr: "FitMesh Sync'i iPhone'a da getirmek için son adımları tamamlıyoruz: iOS sürümü birkaç gün içinde geliyor. Çıkar çıkmaz haberdar olmak istiyorsanız bunu burada anlattık: [FitMesh Sync iPhone'a geliyor](/tr/blog/fitmesh-arriva-su-iphone).",
      },
    },
    {
      type: "cta",
      title: {
        it: "Scaricala ora su Google Play",
        en: "Download it now on Google Play",
        es: "Descárgala ahora en Google Play",
        de: "Jetzt auf Google Play herunterladen",
        pt: "Baixe agora no Google Play",
        fr: "Téléchargez maintenant sur Google Play",
        pl: "Pobierz teraz w Google Play",
        tr: "Şimdi Google Play'den indirin",
      },
      body: {
        it: "Collega lo smartwatch e l'anello, crea l'account e vedi la tua giornata unita in un solo posto. Bastano pochi minuti.",
        en: "Connect your watch and ring, create your account and see your day brought together in one place. It takes just a few minutes.",
        es: "Conecta tu smartwatch y tu anillo, crea tu cuenta y ve todo tu día reunido en un solo lugar. Solo necesitas unos minutos.",
        de: "Verbinde deine Smartwatch und deinen Ring, erstelle dein Konto und sieh deinen Tag vereint an einem einzigen Ort. Es dauert nur wenige Minuten.",
        pt: "Conecte seu smartwatch e seu anel, crie sua conta e veja seu dia reunido em um único lugar. Leva apenas alguns minutos.",
        fr: "Connectez votre montre connectée et votre bague, créez votre compte et consultez votre journée réunie en un seul endroit. Cela ne prend que quelques minutes.",
        pl: "Podłącz swój smartwatch i pierścionek, utwórz konto i zobacz swój dzień zebrany w jednym miejscu. Zajmuje to tylko kilka minut.",
        tr: "Akıllı saatinizi ve yüzüğünüzü bağlayın, hesabınızı oluşturun ve gününüzü tek bir yerde bir araya getirilmiş halde görün. Sadece birkaç dakika sürer.",
      },
      ctaLabel: {
        it: "Scarica su Google Play",
        en: "Get it on Google Play",
        es: "Descargar en Google Play",
        de: "Auf Google Play laden",
        pt: "Baixar no Google Play",
        fr: "Télécharger sur Google Play",
        pl: "Pobierz w Google Play",
        tr: "Google Play'den indir",
      },
      ctaHref: {
        it: "https://play.google.com/store/apps/details?id=com.fitmeshsync.app",
        en: "https://play.google.com/store/apps/details?id=com.fitmeshsync.app",
        pl: "https://play.google.com/store/apps/details?id=com.fitmeshsync.app",
        tr: "https://play.google.com/store/apps/details?id=com.fitmeshsync.app",
      },
    },
  ],
  faq: [
    {
      q: {
        it: "Quanto costa FitMesh Sync?",
        en: "How much does FitMesh Sync cost?",
        es: "¿Cuánto cuesta FitMesh Sync?",
        de: "Was kostet FitMesh Sync?",
        pt: "Quanto custa o FitMesh Sync?",
        fr: "Combien coûte FitMesh Sync?",
        pl: "Ile kosztuje FitMesh Sync?",
        tr: "FitMesh Sync ne kadar?",
      },
      a: {
        it: "C'è un piano gratuito che copre l'uso quotidiano. Le funzioni Pro, come lo storico illimitato, sono disponibili con un acquisto unico o un piano leggero. In più, i primi 1000 che si iscrivono ricevono un anno di Pro gratis.",
        en: "There is a free plan that covers everyday use. Pro features, like unlimited history, are available with a one-time purchase or a light plan. On top of that, the first 1000 to sign up get a free year of Pro.",
        es: "Hay un plan gratuito que cubre el uso diario. Las funciones Pro, como el historial ilimitado, están disponibles con un pago único o un plan ligero. Además, los primeros 1000 en registrarse reciben un año de Pro gratis.",
        de: "Es gibt einen kostenlosen Plan, der den täglichen Gebrauch abdeckt. Pro-Funktionen wie der unbegrenzte Verlauf sind mit einem Einmalkauf oder einem leichten Plan verfügbar. Außerdem erhalten die ersten 1000 Registrierungen ein Jahr Pro kostenlos.",
        pt: "Há um plano gratuito que cobre o uso diário. Os recursos Pro, como o histórico ilimitado, estão disponíveis com uma compra única ou um plano leve. Além disso, os primeiros 1000 a se cadastrar recebem um ano de Pro grátis.",
        fr: "Il existe un plan gratuit qui couvre l'usage quotidien. Les fonctionnalités Pro, comme l'historique illimité, sont disponibles avec un achat unique ou un plan léger. De plus, les 1000 premiers inscrits reçoivent un an de Pro gratuit.",
        pl: "Jest bezpłatny plan, który pokrywa codzienne użytkowanie. Funkcje Pro, takie jak nieograniczona historia, są dostępne za jednorazowy zakup lub lekki plan. Dodatkowo, pierwsze 1000 osób, które się zarejestrują, otrzymuje rok Pro za darmo.",
        tr: "Günlük kullanımı karşılayan ücretsiz bir plan var. Sınırsız geçmiş gibi Pro özellikler, tek seferlik satın alma veya hafif bir planla kullanılabilir. Bunun yanı sıra, ilk 1000 kayıt olan kişi ücretsiz bir yıllık Pro alır.",
      },
    },
    {
      q: {
        it: "Quali dispositivi sono compatibili?",
        en: "Which devices are compatible?",
        es: "¿Qué dispositivos son compatibles?",
        de: "Welche Geräte sind kompatibel?",
        pt: "Quais dispositivos são compatíveis?",
        fr: "Quels appareils sont compatibles?",
        pl: "Które urządzenia są kompatybilne?",
        tr: "Hangi cihazlar uyumludur?",
      },
      a: {
        it: "Tutti i dispositivi che funzionano con Health Connect su Android: Galaxy Watch, Google Pixel Watch, Fitbit, Garmin, Polar, Mi Band, anelli smart e molti altri. Per Samsung Galaxy Watch c'è anche un collegamento diretto con Samsung Health.",
        en: "Any device that works with Health Connect on Android: Galaxy Watch, Google Pixel Watch, Fitbit, Garmin, Polar, Mi Band, smart rings and many more. For Samsung Galaxy Watch there is also a direct link with Samsung Health.",
        es: "Cualquier dispositivo que funcione con Health Connect en Android: Galaxy Watch, Google Pixel Watch, Fitbit, Garmin, Polar, Mi Band, anillos inteligentes y muchos más. Para Samsung Galaxy Watch también hay una conexión directa con Samsung Health.",
        de: "Alle Geräte, die mit Health Connect auf Android funktionieren: Galaxy Watch, Google Pixel Watch, Fitbit, Garmin, Polar, Mi Band, Smart-Ringe und viele mehr. Für Samsung Galaxy Watch gibt es außerdem eine direkte Verbindung mit Samsung Health.",
        pt: "Todos os dispositivos que funcionam com Health Connect no Android: Galaxy Watch, Google Pixel Watch, Fitbit, Garmin, Polar, Mi Band, anéis inteligentes e muitos outros. Para Samsung Galaxy Watch há também uma conexão direta com Samsung Health.",
        fr: "Tous les appareils qui fonctionnent avec Health Connect sur Android: Galaxy Watch, Google Pixel Watch, Fitbit, Garmin, Polar, Mi Band, bagues connectées et bien d'autres. Pour la Samsung Galaxy Watch, il existe également une connexion directe avec Samsung Health.",
        pl: "Każde urządzenie, które działa z Health Connect na Androidzie: Galaxy Watch, Google Pixel Watch, Fitbit, Garmin, Polar, Mi Band, inteligentne pierścionki i wiele innych. Dla Samsung Galaxy Watch istnieje również bezpośrednie połączenie z Samsung Health.",
        tr: "Android'de Health Connect ile çalışan her cihaz: Galaxy Watch, Google Pixel Watch, Fitbit, Garmin, Polar, Mi Band, akıllı yüzükler ve daha fazlası. Samsung Galaxy Watch için Samsung Health ile doğrudan bir bağlantı da mevcuttur.",
      },
    },
    {
      q: {
        it: "Quando arriva su iPhone?",
        en: "When is it coming to iPhone?",
        es: "¿Cuándo llega a iPhone?",
        de: "Wann kommt es auf das iPhone?",
        pt: "Quando chega ao iPhone?",
        fr: "Quand arrive-t-il sur iPhone?",
        pl: "Kiedy pojawi się na iPhonie?",
        tr: "iPhone'a ne zaman geliyor?",
      },
      a: {
        it: "La versione iOS è in arrivo a giorni. Chi si iscrive ora come Founder ha accesso prioritario alla prima versione per iPhone.",
        en: "The iOS version is coming within days. Those who sign up now as Founders get priority access to the first iPhone version.",
        es: "La versión iOS llega en pocos días. Quienes se registren ahora como Founders tendrán acceso prioritario a la primera versión para iPhone.",
        de: "Die iOS-Version ist in wenigen Tagen verfügbar. Wer sich jetzt als Founder registriert, erhält bevorzugten Zugang zur ersten iPhone-Version.",
        pt: "A versão iOS chega em poucos dias. Quem se cadastrar agora como Founder terá acesso prioritário à primeira versão para iPhone.",
        fr: "La version iOS arrive dans quelques jours. Ceux qui s'inscrivent maintenant en tant que Founders bénéficient d'un accès prioritaire à la première version iPhone.",
        pl: "Wersja iOS pojawi się za kilka dni. Ci, którzy zarejestrują się teraz jako Founders, otrzymują priorytetowy dostęp do pierwszej wersji na iPhone'a.",
        tr: "iOS sürümü birkaç gün içinde geliyor. Şimdi Founder olarak kayıt olanlar, ilk iPhone sürümüne öncelikli erişim alır.",
      },
    },
    {
      q: {
        it: "Dove vengono conservati i miei dati?",
        en: "Where is my data stored?",
        es: "¿Dónde se guardan mis datos?",
        de: "Wo werden meine Daten gespeichert?",
        pt: "Onde os meus dados são armazenados?",
        fr: "Où sont stockées mes données?",
        pl: "Gdzie są przechowywane moje dane?",
        tr: "Verilerim nerede saklanıyor?",
      },
      a: {
        it: "Su server in Europa, accessibili solo a te tramite il tuo account. Non vengono mai venduti né condivisi con terzi e puoi cancellarli quando vuoi.",
        en: "On servers in Europe, accessible only to you through your account. They are never sold or shared with third parties and you can delete them whenever you want.",
        es: "En servidores en Europa, accesibles solo a través de tu cuenta. Nunca se venden ni se comparten con terceros, y puedes eliminarlos cuando quieras.",
        de: "Auf Servern in Europa, nur über dein Konto für dich zugänglich. Sie werden niemals verkauft oder an Dritte weitergegeben, und du kannst sie jederzeit löschen.",
        pt: "Em servidores na Europa, acessíveis apenas por você através da sua conta. Nunca são vendidos nem compartilhados com terceiros, e você pode excluí-los quando quiser.",
        fr: "Sur des serveurs en Europe, accessibles uniquement à vous via votre compte. Ils ne sont jamais vendus ni partagés avec des tiers, et vous pouvez les supprimer à tout moment.",
        pl: "Na serwerach w Europie, dostępne tylko dla Ciebie przez Twoje konto. Nigdy nie są sprzedawane ani udostępniane osobom trzecim i możesz je usunąć w dowolnym momencie.",
        tr: "Avrupa'daki sunucularda, yalnızca hesabınız aracılığıyla size erişilebilir. Asla satılmaz veya üçüncü taraflarla paylaşılmaz ve istediğiniz zaman silebilirsiniz.",
      },
    },
  ],
  related: [
    "piu-smartwatch-insieme-dati-doppi",
    "novita-fonte-del-dato",
    "fitmesh-arriva-su-iphone",
    "sync-them-all",
  ],
};
