import type { BlogPost } from "../types";

export const post: BlogPost = {
  slug: "garmin-body-battery-health-connect",
  category: "guides",
  publishedAt: "2026-06-20",
  updatedAt: "2026-06-20",
  readMinutes: 6,
  tldr: {
    it: [
      "Body Battery non arriva in Health Connect perché Garmin lo tratta come dato proprietario e non lo esporta.",
      "Tutti gli altri dati Garmin (passi, frequenza cardiaca, sonno, calorie) passano regolarmente via Health Connect se abiliti l'integrazione nelle impostazioni di Garmin Connect.",
      "Per leggere Body Battery in FitMesh serve FitMesh Pro con connessione OAuth diretta a Garmin Connect.",
      "Body Battery non è uno standard Health Connect: è un indicatore calcolato da Garmin internamente con un algoritmo proprietario.",
      "La soluzione pratica: abilita l'integrazione Garmin-Health Connect per avere tutti gli altri dati, poi valuta FitMesh Pro per Body Battery.",
    ],
    en: [
      "Body Battery doesn't reach Health Connect because Garmin treats it as proprietary data and doesn't export it.",
      "All other Garmin data (steps, heart rate, sleep, calories) flows regularly via Health Connect if you enable the integration in Garmin Connect settings.",
      "To read Body Battery in FitMesh you need FitMesh Pro with a direct OAuth connection to Garmin Connect.",
      "Body Battery is not a Health Connect standard: it's an indicator calculated internally by Garmin using a proprietary algorithm.",
      "The practical solution: enable the Garmin-Health Connect integration for all other data, then consider FitMesh Pro for Body Battery.",
    ],
    es: [
      "Body Battery no llega a Health Connect porque Garmin lo trata como dato propietario y no lo exporta.",
      "Todos los demás datos de Garmin (pasos, frecuencia cardíaca, sueño, calorías) fluyen normalmente vía Health Connect si activas la integración en los ajustes de Garmin Connect.",
      "Para leer Body Battery en FitMesh necesitas FitMesh Pro con conexión OAuth directa a Garmin Connect.",
      "Body Battery no es un estándar de Health Connect: es un indicador calculado internamente por Garmin con un algoritmo propietario.",
      "La solución práctica: activa la integración Garmin-Health Connect para el resto de datos y luego valora FitMesh Pro para Body Battery.",
    ],
    de: [
      "Body Battery gelangt nicht in Health Connect, weil Garmin es als proprietäre Daten behandelt und nicht exportiert.",
      "Alle anderen Garmin-Daten (Schritte, Herzfrequenz, Schlaf, Kalorien) fließen regelmäßig über Health Connect, wenn du die Integration in den Garmin Connect-Einstellungen aktivierst.",
      "Um Body Battery in FitMesh zu lesen, benötigst du FitMesh Pro mit einer direkten OAuth-Verbindung zu Garmin Connect.",
      "Body Battery ist kein Health Connect-Standard: Es ist ein von Garmin intern berechneter Indikator mit einem proprietären Algorithmus.",
      "Die praktische Lösung: Aktiviere die Garmin-Health Connect-Integration für alle anderen Daten und erwäge dann FitMesh Pro für Body Battery.",
    ],
    pt: [
      "Body Battery não chega ao Health Connect porque a Garmin o trata como dado proprietário e não o exporta.",
      "Todos os outros dados da Garmin (passos, frequência cardíaca, sono, calorias) fluem normalmente pelo Health Connect se você ativar a integração nas configurações do Garmin Connect.",
      "Para ler o Body Battery no FitMesh você precisa do FitMesh Pro com conexão OAuth direta ao Garmin Connect.",
      "Body Battery não é um padrão do Health Connect: é um indicador calculado internamente pela Garmin com um algoritmo proprietário.",
      "A solução prática: ative a integração Garmin-Health Connect para os outros dados e avalie o FitMesh Pro para o Body Battery.",
    ],
    fr: [
      "Body Battery n'atteint pas Health Connect parce que Garmin le traite comme une donnée propriétaire et ne l'exporte pas.",
      "Toutes les autres données Garmin (pas, fréquence cardiaque, sommeil, calories) transitent normalement par Health Connect si vous activez l'intégration dans les paramètres de Garmin Connect.",
      "Pour lire Body Battery dans FitMesh, vous avez besoin de FitMesh Pro avec une connexion OAuth directe à Garmin Connect.",
      "Body Battery n'est pas un standard Health Connect : c'est un indicateur calculé en interne par Garmin avec un algorithme propriétaire.",
      "La solution pratique : activez l'intégration Garmin-Health Connect pour toutes les autres données, puis envisagez FitMesh Pro pour Body Battery.",
    ],
    pl: [
      "Body Battery nie trafia do Health Connect, ponieważ Garmin traktuje go jako dane zastrzeżone i nie eksportuje ich.",
      "Wszystkie inne dane Garmin (kroki, tętno, sen, kalorie) przepływają regularnie przez Health Connect, jeśli włączysz integrację w ustawieniach Garmin Connect.",
      "Aby odczytać Body Battery w FitMesh, potrzebujesz FitMesh Pro z bezpośrednim połączeniem OAuth z Garmin Connect.",
      "Body Battery nie jest standardem Health Connect: to wskaźnik obliczany wewnętrznie przez Garmin za pomocą zastrzeżonego algorytmu.",
      "Praktyczne rozwiązanie: włącz integrację Garmin-Health Connect dla pozostałych danych, a następnie rozważ FitMesh Pro dla Body Battery.",
    ],
    tr: [
      "Body Battery, Garmin tarafından tescilli veri olarak ele alındığı ve dışa aktarılmadığı için Health Connect'e ulaşmaz.",
      "Diğer tüm Garmin verileri (adımlar, kalp atış hızı, uyku, kalori), Garmin Connect ayarlarından entegrasyonu etkinleştirirseniz Health Connect üzerinden düzenli olarak akar.",
      "FitMesh'te Body Battery'yi okumak için Garmin Connect'e doğrudan OAuth bağlantısıyla FitMesh Pro gerekir.",
      "Body Battery bir Health Connect standardı değildir: Garmin tarafından tescilli bir algoritmayla dahili olarak hesaplanan bir göstergedir.",
      "Pratik çözüm: diğer veriler için Garmin-Health Connect entegrasyonunu etkinleştirin, ardından Body Battery için FitMesh Pro'yu değerlendirin.",
    ],
    nl: [
      "Body Battery bereikt Health Connect niet omdat Garmin het als eigendomsgegevens beschouwt en het niet exporteert.",
      "Alle andere Garmin-gegevens (stappen, hartslag, slaap, calorieën) stromen regelmatig via Health Connect als u de integratie inschakelt in de Garmin Connect-instellingen.",
      "Om Body Battery in FitMesh te lezen heeft u FitMesh Pro nodig met een directe OAuth-verbinding naar Garmin Connect.",
      "Body Battery is geen Health Connect-standaard: het is een indicator die intern door Garmin wordt berekend met een eigen algoritme.",
      "De praktische oplossing: schakel de Garmin-Health Connect-integratie in voor alle andere gegevens en overweeg dan FitMesh Pro voor Body Battery.",
    ],
    ja: [
      "Body BatteryはGarminが独自データとして扱いエクスポートしないため、Health Connectには届きません。",
      "他のすべてのGarminデータ（歩数、心拍数、睡眠、カロリー）は、Garmin Connectの設定で連携を有効にすればHealth Connect経由で正常に流れます。",
      "FitMeshでBody Batteryを読み取るには、Garmin ConnectへのダイレクトOAuth接続を持つFitMesh Proが必要です。",
      "Body BatteryはHealth Connectの標準ではありません。Garminが独自アルゴリズムで内部計算する指標です。",
      "実践的な解決策：他のデータのためにGarmin-Health Connect連携を有効にし、Body BatteryにはFitMesh Proを検討してください。",
    ],
    ko: [
      "Body Battery는 Garmin이 독점 데이터로 취급하여 내보내지 않기 때문에 Health Connect에 도달하지 않습니다.",
      "다른 모든 Garmin 데이터(걸음 수, 심박수, 수면, 칼로리)는 Garmin Connect 설정에서 연동을 활성화하면 Health Connect를 통해 정상적으로 흐릅니다.",
      "FitMesh에서 Body Battery를 읽으려면 Garmin Connect에 직접 OAuth 연결이 있는 FitMesh Pro가 필요합니다.",
      "Body Battery는 Health Connect 표준이 아닙니다. Garmin이 독점 알고리즘으로 내부 계산하는 지표입니다.",
      "실용적인 해결책: 다른 데이터를 위해 Garmin-Health Connect 연동을 활성화하고, Body Battery를 위해 FitMesh Pro를 고려하세요.",
    ],
  },
  primaryKeyword: {
    it: "garmin body battery health connect",
    en: "garmin body battery health connect",
    es: "garmin body battery health connect",
    de: "garmin body battery health connect",
    pt: "garmin body battery health connect",
    fr: "garmin body battery health connect",
    pl: "garmin body battery health connect",
    tr: "garmin body battery health connect",
    nl: "garmin body battery health connect",
    ja: "garmin body battery health connect",
    ko: "garmin body battery health connect",
  },
  secondaryKeywords: {
    it: [
      "garmin connect health connect android",
      "body battery non disponibile",
      "garmin dati mancanti health connect",
      "garmin recupero energia app",
    ],
    en: [
      "garmin connect health connect android",
      "body battery not available",
      "garmin data missing health connect",
      "garmin recovery score third party app",
    ],
    es: [
      "garmin connect health connect android",
      "body battery no disponible",
      "datos garmin no aparecen health connect",
      "garmin energia recuperacion app",
    ],
    de: [
      "garmin connect health connect android",
      "body battery nicht verfügbar",
      "garmin daten fehlen health connect",
      "garmin erholung drittanbieter app",
    ],
    pt: [
      "garmin connect health connect android",
      "body battery indisponível",
      "dados garmin ausentes health connect",
      "garmin recuperação app terceiros",
    ],
    fr: [
      "garmin connect health connect android",
      "body battery indisponible",
      "données garmin manquantes health connect",
      "garmin récupération application tierce",
    ],
    pl: [
      "garmin connect health connect android",
      "body battery niedostępny",
      "dane garmin brakujące health connect",
      "garmin regeneracja aplikacja",
    ],
    tr: [
      "garmin connect health connect android",
      "body battery mevcut değil",
      "garmin veriler eksik health connect",
      "garmin toparlanma üçüncü taraf uygulama",
    ],
    nl: [
      "garmin connect health connect android",
      "body battery niet beschikbaar",
      "garmin gegevens ontbreken health connect",
      "garmin herstel derde partij app",
    ],
    ja: [
      "garmin connect health connect android",
      "body battery 表示されない",
      "garmin データ health connect 欠落",
      "garmin 回復スコア サードパーティ",
    ],
    ko: [
      "garmin connect health connect android",
      "body battery 표시 안됨",
      "garmin 데이터 health connect 누락",
      "garmin 회복 점수 서드파티 앱",
    ],
  },
  metaDescription: {
    it: "Body Battery di Garmin non appare in Health Connect perché è un dato proprietario. Ecco perché succede, cosa puoi fare oggi per avere tutti gli altri dati Garmin, e come leggere Body Battery con FitMesh Pro.",
    en: "Garmin Body Battery doesn't show in Health Connect because it's proprietary data. Here's why it happens, what you can do today to get all other Garmin data, and how to read Body Battery with FitMesh Pro.",
    es: "El Body Battery de Garmin no aparece en Health Connect porque es un dato propietario. Esto explica por qué ocurre, qué puedes hacer hoy para obtener todos los demás datos de Garmin y cómo leer Body Battery con FitMesh Pro.",
    de: "Garmins Body Battery erscheint nicht in Health Connect, weil es proprietäre Daten sind. Hier erfährst du, warum das passiert, was du heute tun kannst, um alle anderen Garmin-Daten zu erhalten, und wie du Body Battery mit FitMesh Pro lesen kannst.",
    pt: "O Body Battery da Garmin não aparece no Health Connect porque é um dado proprietário. Veja por que isso acontece, o que você pode fazer hoje para obter todos os outros dados da Garmin e como ler o Body Battery com o FitMesh Pro.",
    fr: "Le Body Battery de Garmin n'apparait pas dans Health Connect car c'est une donnée propriétaire. Voici pourquoi cela se produit, ce que vous pouvez faire aujourd'hui pour obtenir toutes les autres données Garmin, et comment lire Body Battery avec FitMesh Pro.",
    pl: "Body Battery Garmin nie pojawia się w Health Connect, ponieważ są to dane zastrzeżone. Oto dlaczego tak się dzieje, co możesz zrobić już dziś, aby uzyskać wszystkie inne dane Garmin i jak odczytać Body Battery za pomocą FitMesh Pro.",
    tr: "Garmin Body Battery, Health Connect'te görünmez çünkü bu tescilli bir veridir. Bunun neden olduğunu, diğer tüm Garmin verilerini bugün nasıl alabileceğinizi ve FitMesh Pro ile Body Battery'yi nasıl okuyabileceğinizi açıklıyoruz.",
    nl: "Garmin Body Battery verschijnt niet in Health Connect omdat het eigendomsgegevens zijn. Hier leest u waarom dit gebeurt, wat u vandaag kunt doen voor alle andere Garmin-gegevens en hoe u Body Battery kunt lezen met FitMesh Pro.",
    ja: "Garmin Body BatteryはHealth Connectに表示されません。独自データだからです。なぜ起きるのか、他のGarminデータを取得するために今日できること、そしてFitMesh ProでBody Batteryを読む方法を解説します。",
    ko: "Garmin Body Battery가 Health Connect에 표시되지 않는 이유는 독점 데이터이기 때문입니다. 왜 그런지, 다른 모든 Garmin 데이터를 오늘 얻는 방법, FitMesh Pro로 Body Battery를 읽는 방법을 설명합니다.",
  },
  hero: {
    kicker: {
      it: "Guida",
      en: "Guide",
      es: "Guía",
      de: "Anleitung",
      pt: "Guia",
      fr: "Guide",
      pl: "Poradnik",
      tr: "Kılavuz",
      nl: "Gids",
      ja: "ガイド",
      ko: "가이드",
    },
    title: {
      it: "Garmin Body Battery non appare in Health Connect: perché e cosa fare",
      en: "Garmin Body Battery not showing in Health Connect: why and what to do",
      es: "El Body Battery de Garmin no aparece en Health Connect: por qué y qué hacer",
      de: "Garmin Body Battery erscheint nicht in Health Connect: Warum und was zu tun ist",
      pt: "Body Battery da Garmin não aparece no Health Connect: por que e o que fazer",
      fr: "Le Body Battery Garmin n'apparait pas dans Health Connect : pourquoi et que faire",
      pl: "Body Battery Garmin nie pojawia się w Health Connect: dlaczego i co zrobić",
      tr: "Garmin Body Battery Health Connect'te görünmüyor: neden ve ne yapmalı",
      nl: "Garmin Body Battery verschijnt niet in Health Connect: waarom en wat te doen",
      ja: "Garmin Body BatteryがHealth Connectに表示されない：理由と対処法",
      ko: "Garmin Body Battery가 Health Connect에 표시되지 않는 이유와 해결책",
    },
    subtitle: {
      it: "Body Battery non è un dato che Garmin condivide con Health Connect. Non è un bug: è una scelta deliberata. Ecco cosa puoi fare oggi.",
      en: "Body Battery is not data that Garmin shares with Health Connect. It's not a bug: it's a deliberate choice. Here's what you can do today.",
      es: "Body Battery no es un dato que Garmin comparte con Health Connect. No es un error: es una decisión deliberada. Esto es lo que puedes hacer hoy.",
      de: "Body Battery ist kein Datum, das Garmin mit Health Connect teilt. Es ist kein Fehler: Es ist eine bewusste Entscheidung. Hier erfährst du, was du heute tun kannst.",
      pt: "Body Battery não é um dado que a Garmin compartilha com o Health Connect. Não é um bug: é uma escolha deliberada. Veja o que você pode fazer hoje.",
      fr: "Body Battery n'est pas une donnée que Garmin partage avec Health Connect. Ce n'est pas un bug : c'est un choix délibéré. Voici ce que vous pouvez faire aujourd'hui.",
      pl: "Body Battery nie jest danymi, które Garmin udostępnia w Health Connect. To nie błąd: to świadoma decyzja. Oto co możesz zrobić już dziś.",
      tr: "Body Battery, Garmin'in Health Connect ile paylaşmadigi bir veridir. Bu bir hata değil: kasıtlı bir tercihtir. Bugün yapabilecekleriniz.",
      nl: "Body Battery is geen gegevens die Garmin deelt met Health Connect. Het is geen bug: het is een bewuste keuze. Dit kunt u vandaag doen.",
      ja: "Body BatteryはGarminがHealth Connectと共有しないデータです。バグではなく意図的な選択です。今日できることを説明します。",
      ko: "Body Battery는 Garmin이 Health Connect와 공유하지 않는 데이터입니다. 버그가 아니라 의도적인 선택입니다. 오늘 할 수 있는 것을 알아봅니다.",
    },
  },
  body: [
    {
      type: "paragraph",
      text: {
        it: "Se hai un orologio Garmin e cerchi di vedere il Body Battery in Health Connect o in un'altra app Android, trovi sempre zero. Passi, frequenza cardiaca, sonno, calorie: arrivano tutti. Body Battery: niente. Non è un problema di configurazione. Garmin non lo esporta deliberatamente, e capiamo perché.",
        en: "If you have a Garmin watch and try to see Body Battery in Health Connect or any other Android app, you always find zero. Steps, heart rate, sleep, calories: they all arrive. Body Battery: nothing. It's not a configuration problem. Garmin deliberately doesn't export it, and there's a reason for that.",
        es: "Si tienes un reloj Garmin e intentas ver el Body Battery en Health Connect o en otra app Android, siempre encuentras cero. Los pasos, la frecuencia cardíaca, el sueño y las calorías llegan todos. Body Battery: nada. No es un problema de configuración. Garmin deliberadamente no lo exporta, y hay una razón para ello.",
        de: "Wenn du eine Garmin-Uhr hast und versuchst, Body Battery in Health Connect oder einer anderen Android-App zu sehen, findest du immer null. Schritte, Herzfrequenz, Schlaf, Kalorien: alles kommt an. Body Battery: nichts. Es ist kein Konfigurationsproblem. Garmin exportiert es absichtlich nicht, und dafür gibt es einen Grund.",
        pt: "Se você tem um relógio Garmin e tenta ver o Body Battery no Health Connect ou em outro app Android, sempre encontra zero. Passos, frequência cardíaca, sono, calorias: tudo chega. Body Battery: nada. Não é um problema de configuração. A Garmin deliberadamente não o exporta, e há um motivo para isso.",
        fr: "Si vous avez une montre Garmin et que vous essayez de voir le Body Battery dans Health Connect ou dans une autre application Android, vous ne trouvez toujours rien. Les pas, la fréquence cardiaque, le sommeil, les calories : tout arrive. Body Battery : rien. Ce n'est pas un problème de configuration. Garmin ne l'exporte délibérément pas, et il y a une raison à cela.",
        pl: "Jeśli masz zegarek Garmin i próbujesz zobaczyć Body Battery w Health Connect lub innej aplikacji Android, zawsze znajdujesz zero. Kroki, tętno, sen, kalorie: wszystko dochodzi. Body Battery: nic. To nie problem konfiguracyjny. Garmin celowo go nie eksportuje i jest ku temu powód.",
        tr: "Bir Garmin saatiniz varsa ve Health Connect'te veya başka bir Android uygulamasında Body Battery'yi görmeye çalışıyorsanız her zaman sıfır bulursunuz. Adımlar, kalp atış hızı, uyku, kalori: hepsi geliyor. Body Battery: hiçbir şey. Bu bir yapılandırma sorunu değildir. Garmin bunu kasıtlı olarak dışa aktarmaz ve bunun bir nedeni var.",
        nl: "Als u een Garmin-horloge heeft en Body Battery wilt zien in Health Connect of een andere Android-app, vindt u altijd nul. Stappen, hartslag, slaap, calorieën: ze komen allemaal aan. Body Battery: niets. Het is geen configuratieprobleem. Garmin exporteert het bewust niet, en daar is een reden voor.",
        ja: "Garminのウォッチをお持ちで、Health Connectや他のAndroidアプリでBody Batteryを確認しようとすると、常にゼロが表示されます。歩数、心拍数、睡眠、カロリーは全部届きます。Body Battery：何もありません。設定の問題ではありません。Garminは意図的にエクスポートしていないのです。理由があります。",
        ko: "Garmin 시계가 있고 Health Connect나 다른 Android 앱에서 Body Battery를 보려고 하면 항상 0을 찾게 됩니다. 걸음 수, 심박수, 수면, 칼로리는 모두 도달합니다. Body Battery: 아무것도 없습니다. 설정 문제가 아닙니다. Garmin이 의도적으로 내보내지 않으며, 그 이유가 있습니다.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Perché Body Battery non arriva in Health Connect",
        en: "Why Body Battery doesn't reach Health Connect",
        es: "Por qué Body Battery no llega a Health Connect",
        de: "Warum Body Battery Health Connect nicht erreicht",
        pt: "Por que o Body Battery não chega ao Health Connect",
        fr: "Pourquoi Body Battery n'atteint pas Health Connect",
        pl: "Dlaczego Body Battery nie dociera do Health Connect",
        tr: "Body Battery neden Health Connect'e ulaşmaz",
        nl: "Waarom Body Battery Health Connect niet bereikt",
        ja: "Body BatteryがHealth Connectに届かない理由",
        ko: "Body Battery가 Health Connect에 도달하지 않는 이유",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Body Battery è un punteggio di recupero che Garmin calcola internamente combinando HRV, stress, qualità del sonno e attività. Non è una metrica raw come i passi o la frequenza cardiaca: è un dato elaborato con un algoritmo che Garmin non ha documentato pubblicamente. Di conseguenza, non esiste un tipo di dato 'Body Battery' nel catalogo ufficiale di Health Connect. Health Connect può ospitare solo i tipi di dato che Google ha standardizzato: passi, calorie, frequenza cardiaca, sonno, SpO2 e altri. Un punteggio calcolato internamente da un produttore non rientra in nessuna di queste categorie.",
        en: "Body Battery is a recovery score that Garmin calculates internally by combining HRV, stress, sleep quality, and activity. It's not a raw metric like steps or heart rate: it's processed data using an algorithm that Garmin hasn't publicly documented. As a result, there's no 'Body Battery' data type in the official Health Connect catalog. Health Connect can only host data types that Google has standardized: steps, calories, heart rate, sleep, SpO2 and others. A score calculated internally by a manufacturer doesn't fit into any of those categories.",
        es: "Body Battery es una puntuación de recuperación que Garmin calcula internamente combinando VFC, estrés, calidad del sueño y actividad. No es una métrica en bruto como los pasos o la frecuencia cardíaca: son datos procesados con un algoritmo que Garmin no ha documentado públicamente. Por eso no existe ningún tipo de dato 'Body Battery' en el catálogo oficial de Health Connect. Health Connect solo puede alojar los tipos de datos que Google ha estandarizado: pasos, calorías, frecuencia cardíaca, sueño, SpO2 y otros. Una puntuación calculada internamente por un fabricante no encaja en ninguna de esas categorías.",
        de: "Body Battery ist ein Erholungswert, den Garmin intern berechnet, indem HRV, Stress, Schlafqualität und Aktivität kombiniert werden. Es ist keine Rohmetrik wie Schritte oder Herzfrequenz: Es sind verarbeitete Daten mit einem Algorithmus, den Garmin nicht öffentlich dokumentiert hat. Daher gibt es keinen Datentyp 'Body Battery' im offiziellen Health Connect-Katalog. Health Connect kann nur Datentypen hosten, die Google standardisiert hat: Schritte, Kalorien, Herzfrequenz, Schlaf, SpO2 und andere. Ein intern von einem Hersteller berechneter Wert passt in keine dieser Kategorien.",
        pt: "Body Battery é uma pontuação de recuperação que a Garmin calcula internamente combinando VFC, estresse, qualidade do sono e atividade. Não é uma métrica bruta como passos ou frequência cardíaca: são dados processados com um algoritmo que a Garmin não documentou publicamente. Por isso, não existe um tipo de dado 'Body Battery' no catálogo oficial do Health Connect. O Health Connect só pode hospedar tipos de dados que o Google padronizou: passos, calorias, frequência cardíaca, sono, SpO2 e outros. Uma pontuação calculada internamente por um fabricante não se encaixa em nenhuma dessas categorias.",
        fr: "Body Battery est un score de récupération que Garmin calcule en interne en combinant VFC, stress, qualité du sommeil et activité. Ce n'est pas une métrique brute comme les pas ou la fréquence cardiaque : ce sont des données traitées avec un algorithme que Garmin n'a pas documenté publiquement. Il n'existe donc pas de type de données 'Body Battery' dans le catalogue officiel de Health Connect. Health Connect ne peut héberger que les types de données que Google a standardisés : pas, calories, fréquence cardiaque, sommeil, SpO2 et autres. Un score calculé en interne par un fabricant ne correspond à aucune de ces catégories.",
        pl: "Body Battery to wynik regeneracji, który Garmin oblicza wewnętrznie, łącząc HRV, stres, jakość snu i aktywność. Nie jest to surowa metryka jak kroki czy tętno: to dane przetworzone algorytmem, którego Garmin nie udokumentował publicznie. W rezultacie w oficjalnym katalogu Health Connect nie ma typu danych 'Body Battery'. Health Connect może hostować tylko typy danych, które Google standaryzowało: kroki, kalorie, tętno, sen, SpO2 i inne. Wynik obliczony wewnętrznie przez producenta nie pasuje do żadnej z tych kategorii.",
        tr: "Body Battery, Garmin'in HRV, stres, uyku kalitesi ve aktiviteyi birleştirerek dahili olarak hesapladığı bir toparlanma puanıdır. Adımlar veya kalp atış hızı gibi ham bir metrik değildir: Garmin'in kamuya açıklamadığı bir algoritmayla işlenmiş veridir. Sonuç olarak, resmi Health Connect kataloğunda 'Body Battery' veri türü yoktur. Health Connect yalnızca Google'ın standartlaştırdığı veri türlerini barındırabilir: adımlar, kalori, kalp atış hızı, uyku, SpO2 ve diğerleri. Bir üretici tarafından dahili olarak hesaplanan bir puan bu kategorilerin hiçbirine uymaz.",
        nl: "Body Battery is een herstelscore die Garmin intern berekent door HRV, stress, slaapkwaliteit en activiteit te combineren. Het is geen ruwe metriek zoals stappen of hartslag: het zijn verwerkte gegevens met een algoritme dat Garmin niet openbaar heeft gedocumenteerd. Als gevolg hiervan is er geen gegevenstype 'Body Battery' in de officiële Health Connect-catalogus. Health Connect kan alleen gegevenstypen hosten die Google heeft gestandaardiseerd: stappen, calorieën, hartslag, slaap, SpO2 en andere. Een score die intern door een fabrikant wordt berekend, past in geen van die categorieën.",
        ja: "Body BatteryはGarminがHRV、ストレス、睡眠の質、活動量を組み合わせて内部的に計算するリカバリースコアです。歩数や心拍数のような生の指標ではありません。Garminが公開していないアルゴリズムを使った処理済みデータです。そのため、公式のHealth Connectカタログには「Body Battery」データタイプが存在しません。Health ConnectはGoogleが標準化したデータタイプ（歩数、カロリー、心拍数、睡眠、SpO2など）しかホストできません。メーカーが内部的に計算したスコアはそのどれにも当てはまりません。",
        ko: "Body Battery는 Garmin이 HRV, 스트레스, 수면 품질, 활동량을 결합하여 내부적으로 계산하는 회복 점수입니다. 걸음 수나 심박수처럼 원시 지표가 아닙니다. Garmin이 공개하지 않은 알고리즘을 사용한 처리된 데이터입니다. 결과적으로 공식 Health Connect 카탈로그에는 'Body Battery' 데이터 유형이 없습니다. Health Connect는 Google이 표준화한 데이터 유형(걸음 수, 칼로리, 심박수, 수면, SpO2 등)만 호스팅할 수 있습니다. 제조업체가 내부적으로 계산한 점수는 그 어느 카테고리에도 맞지 않습니다.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Cosa funziona: i dati Garmin che arrivano in Health Connect",
        en: "What works: the Garmin data that does reach Health Connect",
        es: "Qué funciona: los datos de Garmin que sí llegan a Health Connect",
        de: "Was funktioniert: die Garmin-Daten, die Health Connect erreichen",
        pt: "O que funciona: os dados Garmin que chegam ao Health Connect",
        fr: "Ce qui fonctionne : les données Garmin qui atteignent bien Health Connect",
        pl: "Co dziala: dane Garmin, które docierają do Health Connect",
        tr: "Neler calisiyor: Health Connect'e ulasan Garmin verileri",
        nl: "Wat werkt: de Garmin-gegevens die Health Connect wel bereiken",
        ja: "機能するもの：Health Connectに届くGarminデータ",
        ko: "작동하는 것: Health Connect에 도달하는 Garmin 데이터",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Prima di concentrarsi su ciò che manca, vale la pena sapere cosa funziona bene. Garmin Connect esporta regolarmente in Health Connect passi giornalieri, distanza, calorie attive e totali, frequenza cardiaca (media, a riposo, intraday se il dispositivo la supporta), dati del sonno (durata totale e fasi se la watch le rileva), SpO2 e dati dei workout. Tutto questo arriva in Health Connect, e da lì in qualsiasi app che abbia i permessi di lettura, inclusa FitMesh Sync.",
        en: "Before focusing on what's missing, it's worth knowing what works well. Garmin Connect regularly exports to Health Connect: daily steps, distance, active and total calories, heart rate (average, resting, intraday if the device supports it), sleep data (total duration and stages if the watch detects them), SpO2 and workout data. All of this reaches Health Connect, and from there to any app with read permissions, including FitMesh Sync.",
        es: "Antes de centrarse en lo que falta, vale la pena saber qué funciona bien. Garmin Connect exporta regularmente a Health Connect: pasos diarios, distancia, calorías activas y totales, frecuencia cardíaca (media, en reposo, intradía si el dispositivo lo admite), datos de sueño (duración total y fases si el reloj las detecta), SpO2 y datos de entrenamiento. Todo esto llega a Health Connect y desde allí a cualquier aplicación con permisos de lectura, incluida FitMesh Sync.",
        de: "Bevor wir uns auf das Fehlende konzentrieren, lohnt es sich zu wissen, was gut funktioniert. Garmin Connect exportiert regelmäßig zu Health Connect: tägliche Schritte, Distanz, aktive und gesamte Kalorien, Herzfrequenz (Durchschnitt, Ruhepuls, Intraday wenn das Gerät es unterstützt), Schlafdaten (Gesamtdauer und Phasen wenn die Uhr sie erkennt), SpO2 und Trainingsdaten. All das gelangt in Health Connect, und von dort in jede App mit Leseberechtigungen, einschließlich FitMesh Sync.",
        pt: "Antes de focar no que está faltando, vale saber o que funciona bem. O Garmin Connect exporta regularmente para o Health Connect: passos diários, distância, calorias ativas e totais, frequência cardíaca (média, em repouso, intradiária se o dispositivo suportar), dados de sono (duração total e fases se o relógio as detectar), SpO2 e dados de treino. Tudo isso chega ao Health Connect e, de lá, a qualquer app com permissões de leitura, incluindo o FitMesh Sync.",
        fr: "Avant de se concentrer sur ce qui manque, il vaut la peine de savoir ce qui fonctionne bien. Garmin Connect exporte régulièrement vers Health Connect : pas quotidiens, distance, calories actives et totales, fréquence cardiaque (moyenne, au repos, intraday si l'appareil le prend en charge), données de sommeil (durée totale et phases si la montre les détecte), SpO2 et données d'entrainement. Tout cela parvient à Health Connect, et de là à toute application disposant d'autorisations de lecture, y compris FitMesh Sync.",
        pl: "Zanim skupimy się na tym, czego brakuje, warto wiedzieć, co działa dobrze. Garmin Connect regularnie eksportuje do Health Connect: codzienne kroki, dystans, aktywne i całkowite kalorie, tętno (średnie, spoczynkowe, intraday jeśli urządzenie to obsługuje), dane snu (całkowity czas trwania i fazy jeśli zegarek je wykrywa), SpO2 i dane treningowe. Wszystko to trafia do Health Connect, a stamtąd do każdej aplikacji z uprawnieniami do odczytu, w tym FitMesh Sync.",
        tr: "Eksik olanlara odaklanmadan önce, neyin iyi çalıştığını bilmek faydalıdır. Garmin Connect, Health Connect'e düzenli olarak dışa aktarır: günlük adımlar, mesafe, aktif ve toplam kalori, kalp atış hızı (cihaz destekliyorsa ortalama, istirahat, intraday), uyku verileri (saat destekliyorsa toplam süre ve aşamalar), SpO2 ve antrenman verileri. Bunların tamamı Health Connect'e ulaşır ve oradan FitMesh Sync dahil okuma iznine sahip herhangi bir uygulamaya aktarılır.",
        nl: "Voordat we ons richten op wat ontbreekt, is het de moeite waard te weten wat goed werkt. Garmin Connect exporteert regelmatig naar Health Connect: dagelijkse stappen, afstand, actieve en totale calorieën, hartslag (gemiddeld, rustend, intraday als het apparaat dit ondersteunt), slaapgegevens (totale duur en fasen als het horloge ze detecteert), SpO2 en trainingsgegevens. Dit alles bereikt Health Connect, en van daaruit elke app met leesrechten, inclusief FitMesh Sync.",
        ja: "不足しているものに集中する前に、何がうまく機能するかを知る価値があります。Garmin Connectは定期的にHealth Connectにエクスポートします：日々の歩数、距離、アクティブカロリーと総カロリー、心拍数（平均、安静時、デバイスがサポートしていれば日中）、睡眠データ（ウォッチが検出すれば総時間とフェーズ）、SpO2、ワークアウトデータ。これらすべてがHealth Connectに届き、そこからFitMesh Syncを含む読み取り権限を持つ任意のアプリへと流れます。",
        ko: "없는 것에 집중하기 전에, 잘 작동하는 것이 무엇인지 알 가치가 있습니다. Garmin Connect는 정기적으로 Health Connect에 내보냅니다: 일일 걸음 수, 거리, 활성 칼로리 및 총 칼로리, 심박수(평균, 안정 시, 기기가 지원하면 일중), 수면 데이터(시계가 감지하면 총 지속 시간과 단계), SpO2 및 운동 데이터. 이 모든 것이 Health Connect에 도달하고, 거기서 FitMesh Sync를 포함한 읽기 권한이 있는 모든 앱으로 전달됩니다.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Come attivare l'integrazione Garmin-Health Connect",
        en: "How to enable the Garmin-Health Connect integration",
        es: "Cómo activar la integración Garmin-Health Connect",
        de: "So aktivierst du die Garmin-Health Connect-Integration",
        pt: "Como ativar a integração Garmin-Health Connect",
        fr: "Comment activer l'intégration Garmin-Health Connect",
        pl: "Jak włączyć integrację Garmin-Health Connect",
        tr: "Garmin-Health Connect entegrasyonunu nasil etkinleştirirsiniz",
        nl: "Hoe u de Garmin-Health Connect-integratie inschakelt",
        ja: "Garmin-Health Connect連携を有効にする方法",
        ko: "Garmin-Health Connect 연동을 활성화하는 방법",
      },
    },
    {
      type: "list",
      ordered: true,
      items: {
        it: [
          "Apri **Garmin Connect** sul tuo telefono.",
          "Tocca il menu in alto a sinistra, poi vai su **Impostazioni** (icona ingranaggio in alto a destra).",
          "Cerca la sezione **Connessioni salute** o **Integrazioni** (il nome varia leggermente tra le versioni). Seleziona **Health Connect**.",
          "Se la voce non compare, aggiorna Garmin Connect all'ultima versione disponibile nel Play Store.",
          "Abilita l'interruttore e concedi i permessi richiesti. Garmin inizierà a scrivere i tuoi dati in Health Connect ad ogni sync.",
          "Per forzare un primo invio, apri Garmin Connect, vai sul profilo e tocca **Sincronizza**. I dati appariranno in Health Connect entro pochi minuti.",
        ],
        en: [
          "Open **Garmin Connect** on your phone.",
          "Tap the top-left menu, then go to **Settings** (gear icon, top right).",
          "Look for the **Health connections** or **Integrations** section (the name varies slightly between versions). Select **Health Connect**.",
          "If the entry doesn't appear, update Garmin Connect to the latest version available on the Play Store.",
          "Enable the toggle and grant the requested permissions. Garmin will start writing your data to Health Connect with each sync.",
          "To force a first upload, open Garmin Connect, go to your profile and tap **Sync**. Data will appear in Health Connect within a few minutes.",
        ],
        es: [
          "Abre **Garmin Connect** en tu teléfono.",
          "Toca el menú en la parte superior izquierda y ve a **Ajustes** (icono de engranaje, en la parte superior derecha).",
          "Busca la sección **Conexiones de salud** o **Integraciones** (el nombre varía ligeramente entre versiones). Selecciona **Health Connect**.",
          "Si la opción no aparece, actualiza Garmin Connect a la última versión disponible en Play Store.",
          "Activa el interruptor y concede los permisos solicitados. Garmin empezará a escribir tus datos en Health Connect con cada sincronización.",
          "Para forzar un primer envío, abre Garmin Connect, ve a tu perfil y toca **Sincronizar**. Los datos aparecerán en Health Connect en pocos minutos.",
        ],
        de: [
          "Öffne **Garmin Connect** auf deinem Telefon.",
          "Tippe auf das Menü oben links und gehe zu **Einstellungen** (Zahnrad-Symbol, oben rechts).",
          "Suche nach dem Abschnitt **Gesundheitsverbindungen** oder **Integrationen** (der Name variiert je nach Version). Wähle **Health Connect**.",
          "Falls der Eintrag nicht erscheint, aktualisiere Garmin Connect auf die neueste Version im Play Store.",
          "Aktiviere den Schalter und erteile die angeforderten Berechtigungen. Garmin beginnt bei jeder Synchronisierung, deine Daten in Health Connect zu schreiben.",
          "Um einen ersten Upload zu erzwingen, öffne Garmin Connect, gehe zu deinem Profil und tippe auf **Synchronisieren**. Die Daten erscheinen innerhalb weniger Minuten in Health Connect.",
        ],
        pt: [
          "Abra o **Garmin Connect** no seu telefone.",
          "Toque no menu no canto superior esquerdo e vá em **Configurações** (ícone de engrenagem, canto superior direito).",
          "Procure a seção **Conexões de saúde** ou **Integrações** (o nome varia um pouco entre as versões). Selecione **Health Connect**.",
          "Se a opção não aparecer, atualize o Garmin Connect para a versão mais recente disponível na Play Store.",
          "Ative o botão e conceda as permissões solicitadas. O Garmin começará a escrever seus dados no Health Connect a cada sincronização.",
          "Para forçar um primeiro envio, abra o Garmin Connect, vá ao seu perfil e toque em **Sincronizar**. Os dados aparecerão no Health Connect em poucos minutos.",
        ],
        fr: [
          "Ouvrez **Garmin Connect** sur votre téléphone.",
          "Appuyez sur le menu en haut à gauche, puis allez dans **Paramètres** (icône d'engrenage, en haut à droite).",
          "Cherchez la section **Connexions santé** ou **Intégrations** (le nom varie légèrement selon les versions). Sélectionnez **Health Connect**.",
          "Si l'entrée n'apparait pas, mettez à jour Garmin Connect vers la dernière version disponible sur le Play Store.",
          "Activez le bouton et accordez les autorisations demandées. Garmin commencera à écrire vos données dans Health Connect à chaque synchronisation.",
          "Pour forcer un premier envoi, ouvrez Garmin Connect, allez dans votre profil et appuyez sur **Synchroniser**. Les données apparaitront dans Health Connect en quelques minutes.",
        ],
        pl: [
          "Otwórz **Garmin Connect** na swoim telefonie.",
          "Dotknij menu w lewym górnym rogu, następnie przejdź do **Ustawień** (ikona koła zębatego, w prawym górnym rogu).",
          "Poszukaj sekcji **Połączenia zdrowotne** lub **Integracje** (nazwa może się nieco różnić między wersjami). Wybierz **Health Connect**.",
          "Jeśli pozycja nie pojawia się, zaktualizuj Garmin Connect do najnowszej wersji dostępnej w Play Store.",
          "Włącz przełącznik i przyznaj wymagane uprawnienia. Garmin zacznie zapisywać Twoje dane w Health Connect przy każdej synchronizacji.",
          "Aby wymusić pierwsze przesłanie danych, otwórz Garmin Connect, przejdź do profilu i dotknij **Synchronizuj**. Dane pojawią się w Health Connect w ciągu kilku minut.",
        ],
        tr: [
          "Telefonunuzda **Garmin Connect**'i açın.",
          "Sol üstteki menüye dokunun, ardından **Ayarlar**'a gidin (sağ üstteki dişli simgesi).",
          "**Saglik baglantilari** veya **Entegrasyonlar** bölümünü arayın (ad sürümler arasında biraz değişebilir). **Health Connect**'i seçin.",
          "Giriş görünmüyorsa Garmin Connect'i Play Store'daki en son sürüme güncelleyin.",
          "Geçiş düğmesini etkinleştirin ve istenen izinleri verin. Garmin, her senkronizasyonda verilerinizi Health Connect'e yazmaya başlayacaktır.",
          "İlk yüklemeyi zorlamak için Garmin Connect'i açın, profilinize gidin ve **Senkronize Et**'e dokunun. Veriler birkaç dakika içinde Health Connect'te görünecektir.",
        ],
        nl: [
          "Open **Garmin Connect** op uw telefoon.",
          "Tik op het menu linksboven en ga naar **Instellingen** (tandwielpictogram, rechtsboven).",
          "Zoek naar de sectie **Gezondheidsverbindingen** of **Integraties** (de naam varieert iets per versie). Selecteer **Health Connect**.",
          "Als de vermelding niet verschijnt, werk Garmin Connect bij naar de nieuwste versie in de Play Store.",
          "Schakel de schakelaar in en verleen de gevraagde toestemmingen. Garmin begint bij elke synchronisatie uw gegevens naar Health Connect te schrijven.",
          "Om een eerste upload te forceren, open Garmin Connect, ga naar uw profiel en tik op **Synchroniseren**. De gegevens verschijnen binnen enkele minuten in Health Connect.",
        ],
        ja: [
          "スマートフォンで**Garmin Connect**を開きます。",
          "左上のメニューをタップし、**設定**（右上の歯車アイコン）に進みます。",
          "**ヘルスコネクション**または**連携**セクションを探します（バージョンによって名前が若干異なります）。**Health Connect**を選択します。",
          "項目が表示されない場合は、Play StoreでGarmin Connectを最新バージョンに更新してください。",
          "トグルを有効にして、要求された権限を付与します。Garminは同期のたびにデータをHealth Connectに書き込み始めます。",
          "最初のアップロードを強制するには、Garmin Connectを開き、プロフィールに移動して**同期**をタップします。数分以内にデータがHealth Connectに表示されます。",
        ],
        ko: [
          "스마트폰에서 **Garmin Connect**를 엽니다.",
          "왼쪽 상단 메뉴를 탭하고 **설정**(오른쪽 상단 기어 아이콘)으로 이동합니다.",
          "**건강 연결** 또는 **연동** 섹션을 찾습니다(버전마다 이름이 약간 다를 수 있습니다). **Health Connect**를 선택합니다.",
          "항목이 나타나지 않으면 Play Store에서 Garmin Connect를 최신 버전으로 업데이트하세요.",
          "토글을 활성화하고 요청된 권한을 부여합니다. Garmin은 매 동기화 시 Health Connect에 데이터를 쓰기 시작합니다.",
          "첫 번째 업로드를 강제하려면 Garmin Connect를 열고 프로필로 이동하여 **동기화**를 탭합니다. 몇 분 내에 Health Connect에 데이터가 나타납니다.",
        ],
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Come leggere Body Battery in FitMesh",
        en: "How to read Body Battery in FitMesh",
        es: "Cómo leer Body Battery en FitMesh",
        de: "So liest du Body Battery in FitMesh",
        pt: "Como ler o Body Battery no FitMesh",
        fr: "Comment lire Body Battery dans FitMesh",
        pl: "Jak odczytać Body Battery w FitMesh",
        tr: "FitMesh'te Body Battery nasil okunur",
        nl: "Hoe u Body Battery kunt lezen in FitMesh",
        ja: "FitMeshでBody Batteryを読む方法",
        ko: "FitMesh에서 Body Battery를 읽는 방법",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Poiché Body Battery non transita per Health Connect, l'unico modo per leggerlo in una terza app è connettersi direttamente all'API di Garmin Connect tramite OAuth. FitMesh Pro offre questa connessione: una volta autorizzata, FitMesh recupera Body Battery, stress, VO2 max e altri dati avanzati direttamente da Garmin, senza passare per Health Connect. La connessione OAuth usa le credenziali ufficiali Garmin: non viene mai chiesta la password a FitMesh.",
        en: "Since Body Battery doesn't go through Health Connect, the only way to read it in a third-party app is to connect directly to the Garmin Connect API via OAuth. FitMesh Pro offers this connection: once authorized, FitMesh retrieves Body Battery, stress, VO2 max and other advanced data directly from Garmin, without going through Health Connect. The OAuth connection uses official Garmin credentials: your password is never shared with FitMesh.",
        es: "Como Body Battery no pasa por Health Connect, la única forma de leerlo en una app de terceros es conectarse directamente a la API de Garmin Connect mediante OAuth. FitMesh Pro ofrece esta conexión: una vez autorizada, FitMesh recupera Body Battery, estrés, VO2 max y otros datos avanzados directamente de Garmin, sin pasar por Health Connect. La conexión OAuth usa las credenciales oficiales de Garmin: tu contraseña nunca se comparte con FitMesh.",
        de: "Da Body Battery nicht über Health Connect läuft, ist die einzige Möglichkeit, es in einer Drittanbieter-App zu lesen, die direkte Verbindung zur Garmin Connect-API über OAuth. FitMesh Pro bietet diese Verbindung: Nach der Autorisierung ruft FitMesh Body Battery, Stress, VO2 max und andere erweiterte Daten direkt von Garmin ab, ohne über Health Connect zu gehen. Die OAuth-Verbindung verwendet offizielle Garmin-Anmeldedaten: Dein Passwort wird niemals mit FitMesh geteilt.",
        pt: "Como o Body Battery não passa pelo Health Connect, a única forma de lê-lo em um app de terceiros é conectar-se diretamente à API do Garmin Connect via OAuth. O FitMesh Pro oferece essa conexão: uma vez autorizado, o FitMesh recupera Body Battery, estresse, VO2 max e outros dados avançados diretamente da Garmin, sem passar pelo Health Connect. A conexão OAuth usa as credenciais oficiais da Garmin: sua senha nunca é compartilhada com o FitMesh.",
        fr: "Comme Body Battery ne transite pas par Health Connect, la seule façon de le lire dans une application tierce est de se connecter directement à l'API Garmin Connect via OAuth. FitMesh Pro offre cette connexion : une fois autorisée, FitMesh récupère Body Battery, le stress, le VO2 max et d'autres données avancées directement depuis Garmin, sans passer par Health Connect. La connexion OAuth utilise les identifiants officiels Garmin : votre mot de passe n'est jamais partagé avec FitMesh.",
        pl: "Ponieważ Body Battery nie przechodzi przez Health Connect, jedynym sposobem na odczytanie go w aplikacji innego producenta jest bezpośrednie połączenie z API Garmin Connect przez OAuth. FitMesh Pro oferuje to połączenie: po autoryzacji FitMesh pobiera Body Battery, stres, VO2 max i inne zaawansowane dane bezpośrednio z Garmin, bez przechodzenia przez Health Connect. Połączenie OAuth używa oficjalnych danych uwierzytelniających Garmin: Twoje hasło nigdy nie jest udostępniane FitMesh.",
        tr: "Body Battery Health Connect üzerinden geçmediğinden, bunu bir üçüncü taraf uygulamasında okumanın tek yolu OAuth aracılığıyla Garmin Connect API'sine doğrudan bağlanmaktır. FitMesh Pro bu bağlantıyı sunar: Yetkilendirildikten sonra FitMesh, Body Battery, stres, VO2 max ve diğer gelişmiş verileri Health Connect üzerinden geçmeden doğrudan Garmin'den alır. OAuth bağlantısı resmi Garmin kimlik bilgilerini kullanır: Şifreniz hiçbir zaman FitMesh ile paylaşılmaz.",
        nl: "Omdat Body Battery niet via Health Connect gaat, is de enige manier om het in een app van derden te lezen een directe verbinding met de Garmin Connect-API via OAuth. FitMesh Pro biedt deze verbinding: eenmaal geautoriseerd haalt FitMesh Body Battery, stress, VO2 max en andere geavanceerde gegevens rechtstreeks op van Garmin, zonder via Health Connect te gaan. De OAuth-verbinding gebruikt officiële Garmin-inloggegevens: uw wachtwoord wordt nooit gedeeld met FitMesh.",
        ja: "Body BatteryはHealth Connectを経由しないため、サードパーティアプリで読み取る唯一の方法はOAuth経由でGarmin Connect APIに直接接続することです。FitMesh Proはこの接続を提供します。認証されると、FitMeshはHealth Connectを経由せずにGarminから直接Body Battery、ストレス、VO2 maxなどの高度なデータを取得します。OAuth接続は公式Garminの認証情報を使用します。パスワードはFitMeshと共有されません。",
        ko: "Body Battery는 Health Connect를 통과하지 않기 때문에, 서드파티 앱에서 읽는 유일한 방법은 OAuth를 통해 Garmin Connect API에 직접 연결하는 것입니다. FitMesh Pro는 이 연결을 제공합니다. 승인되면 FitMesh는 Health Connect를 거치지 않고 Garmin에서 직접 Body Battery, 스트레스, VO2 max 및 기타 고급 데이터를 가져옵니다. OAuth 연결은 공식 Garmin 자격 증명을 사용합니다. 비밀번호는 FitMesh와 공유되지 않습니다.",
      },
    },
    {
      type: "callout",
      variant: "tip",
      title: {
        it: "In sintesi",
        en: "In summary",
        es: "En resumen",
        de: "Zusammenfassung",
        pt: "Em resumo",
        fr: "En résumé",
        pl: "Podsumowanie",
        tr: "Ozet",
        nl: "Samenvatting",
        ja: "まとめ",
        ko: "요약",
      },
      body: {
        it: "Se vuoi tutti i dati Garmin su Health Connect (passi, sonno, frequenza cardiaca, calorie, workout): abilita l'integrazione in Garmin Connect come spiegato sopra. Se vuoi anche Body Battery, stress e VO2 max in FitMesh: attiva FitMesh Pro e connetti l'account Garmin. I due percorsi si complementano, non si escludono.",
        en: "If you want all Garmin data in Health Connect (steps, sleep, heart rate, calories, workouts): enable the integration in Garmin Connect as explained above. If you also want Body Battery, stress and VO2 max in FitMesh: activate FitMesh Pro and connect your Garmin account. The two paths complement each other, they're not mutually exclusive.",
        es: "Si quieres todos los datos de Garmin en Health Connect (pasos, sueño, frecuencia cardíaca, calorías, entrenamientos): activa la integración en Garmin Connect como se explicó arriba. Si también quieres Body Battery, estrés y VO2 max en FitMesh: activa FitMesh Pro y conecta la cuenta de Garmin. Los dos caminos se complementan, no se excluyen.",
        de: "Wenn du alle Garmin-Daten in Health Connect möchtest (Schritte, Schlaf, Herzfrequenz, Kalorien, Workouts): Aktiviere die Integration in Garmin Connect wie oben erklärt. Wenn du auch Body Battery, Stress und VO2 max in FitMesh möchtest: Aktiviere FitMesh Pro und verbinde dein Garmin-Konto. Die beiden Wege ergänzen sich, sie schließen sich nicht aus.",
        pt: "Se você quer todos os dados da Garmin no Health Connect (passos, sono, frequência cardíaca, calorias, treinos): ative a integração no Garmin Connect conforme explicado acima. Se também quer Body Battery, estresse e VO2 max no FitMesh: ative o FitMesh Pro e conecte a conta da Garmin. Os dois caminhos se complementam, não se excluem.",
        fr: "Si vous voulez toutes les données Garmin dans Health Connect (pas, sommeil, fréquence cardiaque, calories, entrainements) : activez l'intégration dans Garmin Connect comme expliqué ci-dessus. Si vous voulez également Body Battery, stress et VO2 max dans FitMesh : activez FitMesh Pro et connectez votre compte Garmin. Les deux chemins se complètent, ils ne s'excluent pas.",
        pl: "Jeśli chcesz wszystkich danych Garmin w Health Connect (kroki, sen, tętno, kalorie, treningi): włącz integrację w Garmin Connect jak wyjaśniono powyżej. Jeśli chcesz też Body Battery, stresu i VO2 max w FitMesh: aktywuj FitMesh Pro i połącz konto Garmin. Oba rozwiązania uzupełniają się, nie wykluczają.",
        tr: "Garmin verilerinin tamamını Health Connect'te istiyorsanız (adımlar, uyku, kalp atış hızı, kalori, antrenmanlar): yukarıda açıklandığı gibi Garmin Connect'te entegrasyonu etkinleştirin. FitMesh'te Body Battery, stres ve VO2 max de istiyorsanız: FitMesh Pro'yu etkinleştirin ve Garmin hesabını bağlayın. Bu iki yol birbirini tamamlar, birbirini dışlamaz.",
        nl: "Als u alle Garmin-gegevens in Health Connect wilt (stappen, slaap, hartslag, calorieën, trainingen): schakel de integratie in Garmin Connect in zoals hierboven uitgelegd. Als u ook Body Battery, stress en VO2 max in FitMesh wilt: activeer FitMesh Pro en verbind uw Garmin-account. De twee paden vullen elkaar aan, ze sluiten elkaar niet uit.",
        ja: "Health ConnectですべてのGarminデータ（歩数、睡眠、心拍数、カロリー、ワークアウト）が欲しい場合：上記の説明に従ってGarmin Connectで連携を有効にしてください。FitMeshでBody Battery、ストレス、VO2 maxも欲しい場合：FitMesh Proを有効にしてGarminアカウントを接続してください。2つの方法は補完関係にあり、相互に排他的ではありません。",
        ko: "Health Connect에서 모든 Garmin 데이터(걸음 수, 수면, 심박수, 칼로리, 운동)를 원한다면: 위에 설명한 대로 Garmin Connect에서 연동을 활성화하세요. FitMesh에서 Body Battery, 스트레스, VO2 max도 원한다면: FitMesh Pro를 활성화하고 Garmin 계정을 연결하세요. 두 가지 방법은 상호 보완적이며 상호 배타적이지 않습니다.",
      },
    },
  ],
  faq: [
    {
      q: {
        it: "Body Battery arriverà mai in Health Connect?",
        en: "Will Body Battery ever come to Health Connect?",
        es: "¿Body Battery llegará alguna vez a Health Connect?",
        de: "Wird Body Battery jemals in Health Connect kommen?",
        pt: "O Body Battery chegará algum dia ao Health Connect?",
        fr: "Body Battery arrivera-t-il un jour dans Health Connect ?",
        pl: "Czy Body Battery kiedykolwiek trafi do Health Connect?",
        tr: "Body Battery hiç Health Connect'e gelecek mi?",
        nl: "Zal Body Battery ooit naar Health Connect komen?",
        ja: "Body BatteryはいつかHealth Connectに来るでしょうか？",
        ko: "Body Battery가 언젠가 Health Connect에 올까요?",
      },
      a: {
        it: "Non esiste un annuncio pubblico in tal senso. Body Battery è una metrica calcolata internamente con un algoritmo non documentato: per esportarla in Health Connect, Garmin dovrebbe o pubblicare il metodo di calcolo o lavorare con Google per aggiungere un nuovo tipo di dato standard. Nessuno dei due è avvenuto finora.",
        en: "There's no public announcement in that direction. Body Battery is a metric calculated internally with an undocumented algorithm: to export it to Health Connect, Garmin would need to either publish the calculation method or work with Google to add a new standard data type. Neither has happened so far.",
        es: "No hay ningún anuncio público en ese sentido. Body Battery es una métrica calculada internamente con un algoritmo no documentado: para exportarla a Health Connect, Garmin tendría que publicar el método de cálculo o trabajar con Google para añadir un nuevo tipo de dato estándar. Ninguna de las dos cosas ha ocurrido hasta ahora.",
        de: "Es gibt keine öffentliche Ankündigung in diese Richtung. Body Battery ist eine intern mit einem nicht dokumentierten Algorithmus berechnete Metrik: Um sie in Health Connect zu exportieren, müsste Garmin entweder die Berechnungsmethode veröffentlichen oder mit Google zusammenarbeiten, um einen neuen Standard-Datentyp hinzuzufügen. Beides ist bisher nicht geschehen.",
        pt: "Não há nenhum anúncio público nesse sentido. Body Battery é uma métrica calculada internamente com um algoritmo não documentado: para exportá-la ao Health Connect, a Garmin precisaria publicar o método de cálculo ou trabalhar com o Google para adicionar um novo tipo de dado padrão. Nenhum dos dois ocorreu até agora.",
        fr: "Il n'y a aucune annonce publique dans ce sens. Body Battery est une métrique calculée en interne avec un algorithme non documenté : pour l'exporter dans Health Connect, Garmin devrait soit publier la méthode de calcul, soit travailler avec Google pour ajouter un nouveau type de données standard. Aucune des deux choses ne s'est produite jusqu'à présent.",
        pl: "Nie ma żadnego publicznego ogłoszenia w tym kierunku. Body Battery to metryka obliczana wewnętrznie za pomocą nieudokumentowanego algorytmu: aby wyeksportować ją do Health Connect, Garmin musiałby albo opublikować metodę obliczania, albo współpracować z Google, aby dodać nowy standardowy typ danych. Żadne z nich nie miało dotąd miejsca.",
        tr: "Bu yönde kamuya açık bir duyuru yok. Body Battery, belgelenmemiş bir algoritmayla dahili olarak hesaplanan bir metriktir: Health Connect'e dışa aktarmak için Garmin'in ya hesaplama yöntemini yayımlaması ya da yeni bir standart veri türü eklemek için Google ile çalışması gerekir. Şimdiye kadar bunların hiçbiri gerçekleşmedi.",
        nl: "Er is geen publieke aankondiging in die richting. Body Battery is een metriek die intern wordt berekend met een ongedocumenteerd algoritme: om het naar Health Connect te exporteren, zou Garmin ofwel de berekeningsmethode moeten publiceren ofwel met Google moeten samenwerken om een nieuw standaard gegevenstype toe te voegen. Geen van beide is tot nu toe gebeurd.",
        ja: "その方向での公式発表はありません。Body Batteryは文書化されていないアルゴリズムで内部計算される指標です。Health Connectにエクスポートするには、Garminが計算方法を公開するか、Googleと協力して新しい標準データタイプを追加する必要があります。現時点ではどちらも起きていません。",
        ko: "그 방향으로의 공개 발표는 없습니다. Body Battery는 문서화되지 않은 알고리즘으로 내부적으로 계산되는 지표입니다. Health Connect에 내보내려면 Garmin이 계산 방법을 공개하거나 Google과 협력하여 새로운 표준 데이터 유형을 추가해야 합니다. 지금까지 둘 다 일어나지 않았습니다.",
      },
    },
    {
      q: {
        it: "Se connetto Garmin a FitMesh Pro, i dati Health Connect si duplicano?",
        en: "If I connect Garmin to FitMesh Pro, does Health Connect data get duplicated?",
        es: "Si conecto Garmin a FitMesh Pro, ¿se duplican los datos de Health Connect?",
        de: "Wenn ich Garmin mit FitMesh Pro verbinde, werden die Health Connect-Daten dupliziert?",
        pt: "Se eu conectar a Garmin ao FitMesh Pro, os dados do Health Connect serão duplicados?",
        fr: "Si je connecte Garmin à FitMesh Pro, les données Health Connect seront-elles dupliquées ?",
        pl: "Jeśli podłączę Garmin do FitMesh Pro, czy dane Health Connect się zduplikują?",
        tr: "Garmin'i FitMesh Pro'ya bağlarsam Health Connect verileri kopyalanır mi?",
        nl: "Als ik Garmin verbind met FitMesh Pro, worden Health Connect-gegevens dan gedupliceerd?",
        ja: "GarminをFitMesh Proに接続すると、Health Connectのデータが重複しますか？",
        ko: "Garmin을 FitMesh Pro에 연결하면 Health Connect 데이터가 중복될까요?",
      },
      a: {
        it: "No. FitMesh gestisce la deduplica automaticamente: quando riceve gli stessi dati sia da Health Connect sia dall'API Garmin, mantiene solo il valore più recente per ogni metrica. Non vedrai passi o frequenza cardiaca contati due volte.",
        en: "No. FitMesh handles deduplication automatically: when it receives the same data from both Health Connect and the Garmin API, it keeps only the most recent value for each metric. You won't see steps or heart rate counted twice.",
        es: "No. FitMesh gestiona la deduplicación automáticamente: cuando recibe los mismos datos tanto de Health Connect como de la API de Garmin, conserva solo el valor más reciente para cada métrica. No verás los pasos ni la frecuencia cardíaca contados dos veces.",
        de: "Nein. FitMesh handhabt die Deduplizierung automatisch: Wenn es dieselben Daten sowohl von Health Connect als auch von der Garmin-API erhält, behält es nur den neuesten Wert für jede Metrik. Schritte oder Herzfrequenz werden nicht doppelt gezählt.",
        pt: "Não. O FitMesh gerencia a deduplicação automaticamente: quando recebe os mesmos dados tanto do Health Connect quanto da API da Garmin, mantém apenas o valor mais recente para cada métrica. Você não verá passos ou frequência cardíaca contados duas vezes.",
        fr: "Non. FitMesh gère automatiquement la déduplication : quand il reçoit les mêmes données de Health Connect et de l'API Garmin, il ne conserve que la valeur la plus récente pour chaque métrique. Vous ne verrez pas les pas ou la fréquence cardiaque comptés deux fois.",
        pl: "Nie. FitMesh automatycznie obsługuje deduplikację: gdy otrzymuje te same dane zarówno z Health Connect, jak i z API Garmin, zachowuje tylko najnowszą wartość dla każdej metryki. Nie zobaczysz kroków ani tętna liczonych podwójnie.",
        tr: "Hayir. FitMesh tekilleştirmeyi otomatik olarak yönetir: hem Health Connect'ten hem de Garmin API'sinden aynı verileri aldığında her metrik için yalnızca en son değeri saklar. Adımları veya kalp atış hızını iki kez sayılmış görmezsiniz.",
        nl: "Nee. FitMesh verwerkt deduplicatie automatisch: wanneer het dezelfde gegevens ontvangt van zowel Health Connect als de Garmin-API, behoudt het alleen de meest recente waarde voor elke metriek. U zult stappen of hartslag niet dubbel geteld zien.",
        ja: "いいえ。FitMeshは重複排除を自動的に処理します。Health ConnectとGarmin APIの両方から同じデータを受け取ると、各指標の最新値のみを保持します。歩数や心拍数が2回カウントされることはありません。",
        ko: "아니요. FitMesh는 자동으로 중복 제거를 처리합니다. Health Connect와 Garmin API 모두에서 동일한 데이터를 받으면 각 지표에 대해 가장 최근 값만 유지합니다. 걸음 수나 심박수가 두 번 계산되는 것을 보지 않을 것입니다.",
      },
    },
    {
      q: {
        it: "Gli altri punteggi Garmin (stress, VO2 max) hanno lo stesso problema di Body Battery?",
        en: "Do other Garmin scores (stress, VO2 max) have the same problem as Body Battery?",
        es: "¿Los demás indicadores de Garmin (estrés, VO2 max) tienen el mismo problema que Body Battery?",
        de: "Haben andere Garmin-Scores (Stress, VO2 max) das gleiche Problem wie Body Battery?",
        pt: "Os outros indicadores Garmin (estresse, VO2 max) têm o mesmo problema que o Body Battery?",
        fr: "Les autres scores Garmin (stress, VO2 max) ont-ils le même problème que Body Battery ?",
        pl: "Czy inne wskaźniki Garmin (stres, VO2 max) mają ten sam problem co Body Battery?",
        tr: "Diger Garmin puanlari (stres, VO2 max) Body Battery ile ayni soruna sahip mi?",
        nl: "Hebben andere Garmin-scores (stress, VO2 max) hetzelfde probleem als Body Battery?",
        ja: "他のGarminスコア（ストレス、VO2 max）もBody Batteryと同じ問題がありますか？",
        ko: "다른 Garmin 점수(스트레스, VO2 max)도 Body Battery와 같은 문제가 있나요?",
      },
      a: {
        it: "Sì, stessa situazione. Stress score e VO2 max di Garmin sono anch'essi metriche calcolate internamente che non vengono esportate in Health Connect. Entrambe sono disponibili tramite FitMesh Pro con connessione OAuth Garmin.",
        en: "Yes, same situation. Garmin's stress score and VO2 max are also internally calculated metrics that are not exported to Health Connect. Both are available through FitMesh Pro with a Garmin OAuth connection.",
        es: "Sí, misma situación. La puntuación de estrés y el VO2 max de Garmin también son métricas calculadas internamente que no se exportan a Health Connect. Ambas están disponibles a través de FitMesh Pro con conexión OAuth de Garmin.",
        de: "Ja, gleiche Situation. Garmins Stress-Score und VO2 max sind ebenfalls intern berechnete Metriken, die nicht in Health Connect exportiert werden. Beide sind über FitMesh Pro mit einer Garmin-OAuth-Verbindung verfügbar.",
        pt: "Sim, mesma situação. A pontuação de estresse e o VO2 max da Garmin também são métricas calculadas internamente que não são exportadas para o Health Connect. Ambas estão disponíveis no FitMesh Pro com conexão OAuth da Garmin.",
        fr: "Oui, même situation. Le score de stress et le VO2 max de Garmin sont aussi des métriques calculées en interne qui ne sont pas exportées vers Health Connect. Les deux sont disponibles via FitMesh Pro avec une connexion OAuth Garmin.",
        pl: "Tak, ta sama sytuacja. Wynik stresu i VO2 max Garmin to również metryki obliczane wewnętrznie, które nie są eksportowane do Health Connect. Oba są dostępne przez FitMesh Pro z połączeniem OAuth Garmin.",
        tr: "Evet, aynı durum. Garmin'in stres puanı ve VO2 max da Health Connect'e dışa aktarılmayan dahili olarak hesaplanan metriklerdir. Her ikisi de Garmin OAuth bağlantısıyla FitMesh Pro aracılığıyla kullanılabilir.",
        nl: "Ja, zelfde situatie. Garmins stressscore en VO2 max zijn ook intern berekende metrieken die niet naar Health Connect worden geëxporteerd. Beide zijn beschikbaar via FitMesh Pro met een Garmin OAuth-verbinding.",
        ja: "はい、同じ状況です。GarminのストレススコアとVO2 maxも内部計算される指標であり、Health Connectにはエクスポートされません。どちらもGarmin OAuthを接続したFitMesh Pro経由で利用できます。",
        ko: "네, 같은 상황입니다. Garmin의 스트레스 점수와 VO2 max도 Health Connect에 내보내지 않는 내부 계산 지표입니다. 둘 다 Garmin OAuth 연결로 FitMesh Pro를 통해 사용할 수 있습니다.",
      },
    },
    {
      q: {
        it: "Devo disinstallare Garmin Connect per usare FitMesh?",
        en: "Do I need to uninstall Garmin Connect to use FitMesh?",
        es: "¿Tengo que desinstalar Garmin Connect para usar FitMesh?",
        de: "Muss ich Garmin Connect deinstallieren, um FitMesh zu verwenden?",
        pt: "Preciso desinstalar o Garmin Connect para usar o FitMesh?",
        fr: "Dois-je désinstaller Garmin Connect pour utiliser FitMesh ?",
        pl: "Czy muszę odinstalować Garmin Connect, żeby używać FitMesh?",
        tr: "FitMesh kullanmak icin Garmin Connect'i kaldirmam gerekiyor mu?",
        nl: "Moet ik Garmin Connect verwijderen om FitMesh te gebruiken?",
        ja: "FitMeshを使うためにGarmin Connectをアンインストールする必要がありますか？",
        ko: "FitMesh를 사용하려면 Garmin Connect를 제거해야 하나요?",
      },
      a: {
        it: "No, assolutamente. Garmin Connect deve restare installato: è l'app che sincronizza i dati dall'orologio al telefono e li scrive in Health Connect. FitMesh legge da Health Connect, e opzionalmente da Garmin Connect via OAuth per i dati avanzati. I due convivono senza problemi.",
        en: "No, absolutely not. Garmin Connect must stay installed: it's the app that syncs data from your watch to your phone and writes it to Health Connect. FitMesh reads from Health Connect, and optionally from Garmin Connect via OAuth for advanced data. The two coexist without issues.",
        es: "No, en absoluto. Garmin Connect debe permanecer instalado: es la app que sincroniza los datos del reloj al teléfono y los escribe en Health Connect. FitMesh lee de Health Connect y, opcionalmente, de Garmin Connect vía OAuth para los datos avanzados. Ambas conviven sin problemas.",
        de: "Nein, auf keinen Fall. Garmin Connect muss installiert bleiben: Es ist die App, die Daten von der Uhr auf das Telefon synchronisiert und in Health Connect schreibt. FitMesh liest von Health Connect und optional von Garmin Connect über OAuth für erweiterte Daten. Beide koexistieren problemlos.",
        pt: "Não, de jeito nenhum. O Garmin Connect deve continuar instalado: é o app que sincroniza os dados do relógio para o telefone e os escreve no Health Connect. O FitMesh lê do Health Connect e, opcionalmente, do Garmin Connect via OAuth para os dados avançados. Os dois coexistem sem problemas.",
        fr: "Non, absolument pas. Garmin Connect doit rester installé : c'est l'application qui synchronise les données de la montre vers le téléphone et les écrit dans Health Connect. FitMesh lit depuis Health Connect, et optionnellement depuis Garmin Connect via OAuth pour les données avancées. Les deux coexistent sans problème.",
        pl: "Nie, absolutnie nie. Garmin Connect musi pozostać zainstalowany: to aplikacja, która synchronizuje dane z zegarka do telefonu i zapisuje je w Health Connect. FitMesh czyta z Health Connect i opcjonalnie z Garmin Connect przez OAuth dla zaawansowanych danych. Oba działają razem bez problemów.",
        tr: "Hayir, kesinlikle hayir. Garmin Connect yüklü kalmalıdır: saatteki verileri telefonunuza senkronize eden ve Health Connect'e yazan uygulamadır. FitMesh Health Connect'ten ve isteğe bağlı olarak gelişmiş veriler için OAuth aracılığıyla Garmin Connect'ten okur. İkisi sorunsuz birlikte çalışır.",
        nl: "Nee, absoluut niet. Garmin Connect moet geïnstalleerd blijven: het is de app die gegevens van uw horloge naar uw telefoon synchroniseert en naar Health Connect schrijft. FitMesh leest van Health Connect, en optioneel van Garmin Connect via OAuth voor geavanceerde gegevens. De twee bestaan probleemloos naast elkaar.",
        ja: "いいえ、絶対にそうではありません。Garmin Connectはインストールしたままにしておく必要があります。ウォッチからスマートフォンにデータを同期し、Health Connectに書き込むアプリです。FitMeshはHealth Connectから読み取り、高度なデータについてはOAuth経由でGarmin Connectからオプションで読み取ります。2つは問題なく共存します。",
        ko: "아니요, 절대로 그렇지 않습니다. Garmin Connect는 계속 설치되어 있어야 합니다. 시계에서 스마트폰으로 데이터를 동기화하고 Health Connect에 쓰는 앱입니다. FitMesh는 Health Connect에서 읽고, 고급 데이터를 위해 선택적으로 OAuth를 통해 Garmin Connect에서 읽습니다. 두 앱은 문제없이 공존합니다.",
      },
    },
    {
      q: {
        it: "Perché i miei dati Garmin arrivano in ritardo in Health Connect?",
        en: "Why does my Garmin data arrive late in Health Connect?",
        es: "¿Por qué mis datos de Garmin llegan con retraso a Health Connect?",
        de: "Warum kommen meine Garmin-Daten verspätet in Health Connect an?",
        pt: "Por que meus dados da Garmin chegam com atraso no Health Connect?",
        fr: "Pourquoi mes données Garmin arrivent-elles en retard dans Health Connect ?",
        pl: "Dlaczego moje dane Garmin docierają do Health Connect z opóźnieniem?",
        tr: "Garmin verilerim neden Health Connect'e gec geliyor?",
        nl: "Waarom komen mijn Garmin-gegevens laat aan in Health Connect?",
        ja: "GarminデータがHealth Connectに遅れて届くのはなぜですか？",
        ko: "Garmin 데이터가 Health Connect에 늦게 도착하는 이유는 무엇인가요?",
      },
      a: {
        it: "Garmin Connect scrive in Health Connect solo quando si sincronizza attivamente con l'orologio. Se tieni l'orologio lontano dal telefono per ore, i dati arriveranno in blocco quando riapri Garmin Connect in range Bluetooth. Per avere dati più freschi, forza manualmente la sincronizzazione di Garmin Connect oppure tieni il telefono e l'orologio vicini.",
        en: "Garmin Connect writes to Health Connect only when it actively syncs with the watch. If you keep the watch away from your phone for hours, data will arrive in bulk when you reopen Garmin Connect within Bluetooth range. For fresher data, manually force a Garmin Connect sync or keep your phone and watch nearby.",
        es: "Garmin Connect escribe en Health Connect solo cuando se sincroniza activamente con el reloj. Si mantienes el reloj lejos del teléfono durante horas, los datos llegarán en bloque cuando vuelvas a abrir Garmin Connect en rango Bluetooth. Para datos más recientes, fuerza manualmente la sincronización de Garmin Connect o mantén el teléfono y el reloj cerca.",
        de: "Garmin Connect schreibt nur dann in Health Connect, wenn es sich aktiv mit der Uhr synchronisiert. Wenn du die Uhr stundenlang vom Telefon fernhältst, werden die Daten in einem Block ankommen, wenn du Garmin Connect im Bluetooth-Bereich wieder öffnest. Für aktuellere Daten erzwinge manuell eine Garmin Connect-Synchronisierung oder halte Telefon und Uhr in der Nähe.",
        pt: "O Garmin Connect grava no Health Connect apenas quando sincroniza ativamente com o relógio. Se você mantiver o relógio longe do telefone por horas, os dados chegarão em bloco quando você reabrir o Garmin Connect dentro do alcance Bluetooth. Para dados mais recentes, force manualmente uma sincronização do Garmin Connect ou mantenha o telefone e o relógio próximos.",
        fr: "Garmin Connect n'écrit dans Health Connect que lorsqu'il se synchronise activement avec la montre. Si vous gardez la montre loin du téléphone pendant des heures, les données arriveront en bloc lorsque vous rouvrirez Garmin Connect à portée Bluetooth. Pour des données plus fraîches, forcez manuellement une synchronisation de Garmin Connect ou gardez votre téléphone et votre montre à proximité.",
        pl: "Garmin Connect zapisuje do Health Connect tylko wtedy, gdy aktywnie synchronizuje się z zegarkiem. Jeśli trzymasz zegarek z dala od telefonu przez godziny, dane dotrą zbiorczo, gdy ponownie otworzysz Garmin Connect w zasięgu Bluetooth. Aby uzyskać świeższe dane, wymuś ręcznie synchronizację Garmin Connect lub trzymaj telefon i zegarek blisko siebie.",
        tr: "Garmin Connect, yalnızca saatinizle aktif olarak senkronize edildiğinde Health Connect'e yazar. Saati telefonunuzdan saatlerce uzak tutarsanız Garmin Connect'i Bluetooth menzilinde yeniden açtığınızda veriler toplu olarak gelir. Daha güncel veriler için Garmin Connect senkronizasyonunu manuel olarak zorunlu kılın veya telefon ve saatinizi yakın tutun.",
        nl: "Garmin Connect schrijft alleen naar Health Connect wanneer het actief synchroniseert met het horloge. Als u het horloge uren van uw telefoon verwijderd houdt, komen de gegevens in bulk aan wanneer u Garmin Connect opnieuw opent binnen Bluetooth-bereik. Voor versere gegevens, forceer handmatig een Garmin Connect-synchronisatie of houd uw telefoon en horloge in de buurt.",
        ja: "Garmin Connectは時計と積極的に同期するときのみHealth Connectに書き込みます。時計をスマートフォンから何時間も離しておくと、Bluetooth圏内でGarmin Connectを再度開いたときにデータがまとめて届きます。より新鮮なデータを得るには、手動でGarmin Connectの同期を強制するか、スマートフォンと時計を近くに置いてください。",
        ko: "Garmin Connect는 시계와 적극적으로 동기화할 때만 Health Connect에 씁니다. 시계를 스마트폰에서 수 시간 동안 멀리 두면, Bluetooth 범위 내에서 Garmin Connect를 다시 열 때 데이터가 일괄적으로 도달합니다. 더 신선한 데이터를 위해 Garmin Connect 동기화를 수동으로 강제하거나 스마트폰과 시계를 가까이 두세요.",
      },
    },
  ],
  brandsMentioned: ["Garmin"],
};
