import type { BlogPost } from "../types";

export const post: BlogPost = {
  slug: "health-connect-vs-samsung-health",
  category: "comparisons",
  publishedAt: "2026-05-21",
  updatedAt: "2026-05-21",
  readMinutes: 8,
  tldr: {
    it: [
      "Samsung Health e Health Connect non sono concorrenti: lavorano insieme.",
      "Samsung Health raccoglie i dati dal Galaxy Watch via Bluetooth: disabilitarla rompe il sync del Watch.",
      "Health Connect è il layer di permessi Android tra app salute: disabilitarla impedisce alle app terze di leggere i dati, ma Samsung Health continua a funzionare.",
      "Il flusso reale è: Watch → Samsung Health → Health Connect → app terze.",
      "Per bloccare il cloud Samsung senza rompere nulla: Samsung Health → Impostazioni → Privacy → disabilita la sincronizzazione con Samsung Cloud. I dati restano locali e continuano a fluire verso Health Connect.",
    ],
    en: [
      "Samsung Health and Health Connect are not competitors: they work together.",
      "Samsung Health collects data from the Galaxy Watch via Bluetooth: disabling it breaks Watch sync.",
      "Health Connect is the Android permissions layer between health apps: disabling it stops third-party apps from reading data, but Samsung Health keeps working.",
      "The real flow is: Watch → Samsung Health → Health Connect → third-party apps.",
      "To block the Samsung cloud without breaking anything: Samsung Health → Settings → Privacy → disable sync with Samsung Cloud. Data stays local and keeps flowing to Health Connect.",
    ],
    es: [
      "Samsung Health y Health Connect no son competidores: trabajan juntos.",
      "Samsung Health recopila los datos del Galaxy Watch por Bluetooth: desactivarla rompe la sincronización del Watch.",
      "Health Connect es la capa de permisos de Android entre apps de salud: desactivarla impide que apps de terceros lean tus datos, pero Samsung Health sigue funcionando.",
      "El flujo real es: Watch → Samsung Health → Health Connect → apps de terceros.",
      "Para bloquear la nube de Samsung sin romper nada: Samsung Health → Ajustes → Privacidad → desactiva la sincronización con Samsung Cloud. Los datos quedan locales y siguen fluyendo hacia Health Connect.",
    ],
    de: [
      "Samsung Health und Health Connect sind keine Konkurrenten: Sie arbeiten zusammen.",
      "Samsung Health empfängt Daten vom Galaxy Watch per Bluetooth: Deaktivieren bricht die Watch-Synchronisierung.",
      "Health Connect ist die Android-Berechtigungsschicht zwischen Gesundheits-Apps: Deaktivieren verhindert, dass Drittanbieter-Apps deine Gesundheitsdaten lesen, aber Samsung Health funktioniert weiterhin.",
      "Der tatsächliche Datenfluss ist: Watch → Samsung Health → Health Connect → Drittanbieter-Apps.",
      "Um die Samsung-Cloud zu blockieren, ohne etwas zu beschädigen: Samsung Health → Einstellungen → Datenschutz → Synchronisierung mit Samsung Cloud deaktivieren. Die Daten bleiben lokal und fließen weiterhin zu Health Connect.",
    ],
    pt: [
      "Samsung Health e Health Connect não são concorrentes: eles trabalham juntos.",
      "O Samsung Health coleta dados do Galaxy Watch via Bluetooth: desativá-lo quebra a sincronização do Watch.",
      "O Health Connect é a camada de permissões do Android entre apps de saúde: desativá-lo impede que apps de terceiros leiam seus dados, mas o Samsung Health continua funcionando.",
      "O fluxo real é: Watch → Samsung Health → Health Connect → apps de terceiros.",
      "Para bloquear a nuvem da Samsung sem quebrar nada: Samsung Health → Configurações → Privacidade → desative a sincronização com o Samsung Cloud. Os dados ficam locais e continuam fluindo para o Health Connect.",
    ],
    fr: [
      "Samsung Health et Health Connect ne sont pas des concurrents : ils fonctionnent ensemble.",
      "Samsung Health collecte les données de la Galaxy Watch via Bluetooth : le désactiver interrompt la synchronisation de la montre.",
      "Health Connect est la couche de permissions Android entre les applications de santé : le désactiver empêche les applications tierces de lire vos données, mais Samsung Health continue de fonctionner.",
      "Le flux réel est : Watch → Samsung Health → Health Connect → applications tierces.",
      "Pour bloquer le cloud Samsung sans rien casser : Samsung Health → Paramètres → Confidentialité → désactiver la synchronisation avec Samsung Cloud. Les données restent locales et continuent de transiter vers Health Connect.",
    ],
    pl: [
      "Samsung Health i Health Connect nie są konkurentami: współpracują ze sobą.",
      "Samsung Health zbiera dane z Galaxy Watch przez Bluetooth: wyłączenie jej zrywa synchronizację zegarka.",
      "Health Connect to warstwa uprawnień Androida między aplikacjami zdrowotnymi: wyłączenie jej uniemożliwia aplikacjom trzecim odczyt danych, ale Samsung Health nadal działa.",
      "Rzeczywisty przepływ to: Watch → Samsung Health → Health Connect → aplikacje trzecie.",
      "Aby zablokować chmurę Samsung bez zrywania czegokolwiek: Samsung Health → Ustawienia → Prywatność → wyłącz synchronizację z Samsung Cloud. Dane pozostają lokalnie i nadal przepływają do Health Connect.",
    ],
    tr: [
      "Samsung Health ve Health Connect rakip değil: birlikte çalışıyorlar.",
      "Samsung Health, Galaxy Watch'tan Bluetooth üzerinden veri topluyor: devre dışı bırakmak Watch senkronizasyonunu kesiyor.",
      "Health Connect, sağlık uygulamaları arasındaki Android izin katmanıdır: devre dışı bırakmak üçüncü taraf uygulamaların veri okumasını engelliyor, ancak Samsung Health çalışmaya devam ediyor.",
      "Gerçek veri akışı şöyle: Watch → Samsung Health → Health Connect → üçüncü taraf uygulamalar.",
      "Hiçbir şeyi bozmadan Samsung bulutunu engellemek için: Samsung Health → Ayarlar → Gizlilik → Samsung Cloud ile senkronizasyonu devre dışı bırak. Veriler yerel kalır ve Health Connect'e akmaya devam eder.",
    ],
    nl: [
      "Samsung Health en Health Connect zijn geen concurrenten: ze werken samen.",
      "Samsung Health verzamelt gegevens van de Galaxy Watch via Bluetooth: uitschakelen verbreekt de Watch-synchronisatie.",
      "Health Connect is de Android-machtigingenlaag tussen gezondheidsapps: uitschakelen voorkomt dat apps van derden je gegevens lezen, maar Samsung Health blijft werken.",
      "De werkelijke gegevensstroom is: Watch → Samsung Health → Health Connect → apps van derden.",
      "Om de Samsung-cloud te blokkeren zonder iets te breken: Samsung Health → Instellingen → Privacy → synchronisatie met Samsung Cloud uitschakelen. Gegevens blijven lokaal en blijven naar Health Connect stromen.",
    ],
    ja: [
      "Samsung HealthとHealth Connectは競合していません：連携して動作します。",
      "Samsung HealthはBluetooth経由でGalaxy Watchからデータを収集します：無効にするとWatchの同期が壊れます。",
      "Health Connectはヘルスアプリ間のAndroid権限レイヤーです：無効にするとサードパーティアプリがデータを読めなくなりますが、Samsung Healthは引き続き動作します。",
      "実際のデータフローは：Watch → Samsung Health → Health Connect → サードパーティアプリです。",
      "何も壊さずにSamsungクラウドをブロックするには：Samsung Health → 設定 → プライバシー → Samsung Cloudとの同期を無効にします。データはローカルに保持され、Health Connectへ流れ続けます。",
    ],
    ko: [
      "Samsung Health와 Health Connect는 경쟁자가 아닙니다: 함께 작동합니다.",
      "Samsung Health는 Bluetooth를 통해 Galaxy Watch에서 데이터를 수집합니다: 비활성화하면 Watch 동기화가 끊깁니다.",
      "Health Connect는 건강 앱 간의 Android 권한 레이어입니다: 비활성화하면 타사 앱이 데이터를 읽지 못하지만 Samsung Health는 계속 작동합니다.",
      "실제 데이터 흐름은: Watch → Samsung Health → Health Connect → 타사 앱입니다.",
      "아무것도 망가뜨리지 않고 Samsung 클라우드를 차단하려면: Samsung Health → 설정 → 개인정보 보호 → Samsung Cloud와의 동기화 비활성화. 데이터는 로컬에 유지되고 Health Connect로 계속 흐릅니다.",
    ],
  },
  primaryKeyword: {
    it: "health connect vs samsung health",
    en: "health connect vs samsung health",
    es: "health connect vs samsung health",
    de: "health connect vs samsung health",
    pt: "health connect vs samsung health",
    fr: "health connect vs samsung health",
    pl: "health connect vs samsung health",
    tr: "health connect vs samsung health",
    nl: "health connect vs samsung health",
    ja: "health connect vs samsung health",
    ko: "health connect vs samsung health",
  },
  secondaryKeywords: {
    it: [
      "samsung health o health connect",
      "health connect funziona con galaxy watch",
      "samsung health 2026",
      "samsung health esportare dati",
    ],
    en: [
      "samsung health or health connect",
      "health connect works with galaxy watch",
      "samsung health 2026",
      "samsung health export data",
    ],
    pt: [
      "samsung health ou health connect",
      "health connect funciona com galaxy watch",
      "samsung health 2026",
      "samsung health exportar dados",
    ],
    fr: [
      "samsung health ou health connect",
      "health connect fonctionne avec galaxy watch",
      "samsung health 2026",
      "samsung health exporter les données",
    ],
    pl: [
      "samsung health czy health connect",
      "health connect działa z galaxy watch",
      "samsung health 2026",
      "samsung health eksport danych",
    ],
    tr: [
      "samsung health mı health connect mi",
      "health connect galaxy watch ile çalışır mı",
      "samsung health 2026",
      "samsung health veri dışa aktarma",
    ],
    nl: [
      "samsung health of health connect",
      "health connect werkt met galaxy watch",
      "samsung health 2026",
      "samsung health gegevens exporteren",
    ],
    ja: [
      "samsung healthかhealth connectか",
      "health connectはgalaxy watchで動作する",
      "samsung health 2026",
      "samsung healthデータエクスポート",
    ],
    ko: [
      "samsung health 아니면 health connect",
      "health connect galaxy watch와 호환",
      "samsung health 2026",
      "samsung health 데이터 내보내기",
    ],
  },
  metaDescription: {
    it: "Health Connect vs Samsung Health spiegati semplicemente: a cosa servono, perché lavorano insieme, e quando usare cosa nel 2026. Galaxy Watch incluso.",
    en: "Health Connect vs Samsung Health explained simply: what they do, why they work together, and when to use which in 2026. Galaxy Watch included.",
    es: "Health Connect vs Samsung Health explicados de forma sencilla: para qué sirven, por qué trabajan juntos y cuándo usar cada uno en 2026. Galaxy Watch incluido.",
    de: "Health Connect vs Samsung Health einfach erklärt: Was sie tun, warum sie zusammenarbeiten und wann man welches 2026 verwendet. Galaxy Watch inklusive.",
    pt: "Health Connect vs Samsung Health explicados de forma simples: para que servem, por que trabalham juntos e quando usar cada um em 2026. Galaxy Watch incluído.",
    fr: "Health Connect vs Samsung Health expliqués simplement : à quoi ils servent, pourquoi ils fonctionnent ensemble et lequel utiliser en 2026. Galaxy Watch inclus.",
    pl: "Health Connect kontra Samsung Health – proste wyjaśnienie: do czego służą, dlaczego współpracują i kiedy używać którego w 2026 roku. Galaxy Watch uwzględniony.",
    tr: "Health Connect ile Samsung Health basitçe anlatıldı: ne işe yararlar, neden birlikte çalışırlar ve 2026'da hangisini ne zaman kullanmalısınız. Galaxy Watch dahil.",
    nl: "Health Connect vs Samsung Health eenvoudig uitgelegd: wat ze doen, waarom ze samenwerken en wanneer je welke gebruikt in 2026. Galaxy Watch inbegrepen.",
    ja: "Health ConnectとSamsung Healthをわかりやすく解説：それぞれの役割、連携の理由、2026年にどちらをいつ使うべきか。Galaxy Watch対応。",
    ko: "Health Connect vs Samsung Health 간단 설명: 각각의 역할, 함께 작동하는 이유, 2026년에 언제 어떤 것을 사용할지. Galaxy Watch 포함.",
  },
  hero: {
    kicker: { it: "Confronto", en: "Comparison", es: "Comparativa", de: "Vergleich", pt: "Comparação", fr: "Comparatif", pl: "Porównanie", tr: "Karşılaştırma", nl: "Vergelijking", ja: "比較", ko: "비교" },
    title: {
      it: "Health Connect vs Samsung Health: differenze 2026",
      en: "Health Connect vs Samsung Health: differences and when to use which in 2026",
      es: "Health Connect vs Samsung Health: diferencias y cuándo usar cada uno en 2026",
      de: "Health Connect vs Samsung Health: Unterschiede und wann man was 2026 verwendet",
      pt: "Health Connect vs Samsung Health: diferenças e quando usar cada um em 2026",
      fr: "Health Connect vs Samsung Health: différences et lequel utiliser en 2026",
      pl: "Health Connect vs Samsung Health: różnice i kiedy używać którego w 2026 roku",
      tr: "Health Connect ile Samsung Health: farklar ve 2026'da hangisini ne zaman kullanmalı",
      nl: "Health Connect vs Samsung Health: verschillen en wanneer je welke gebruikt in 2026",
      ja: "Health Connect vs Samsung Health：2026年の違いとどちらをいつ使うか",
      ko: "Health Connect vs Samsung Health: 차이점과 2026년 사용 시점",
    },
    subtitle: {
      it: "Non sono concorrenti. Lavorano insieme. Ma è importante capire chi fa cosa per non disabilitare quello sbagliato.",
      en: "Not competitors. They work together. But it matters to understand who does what so you don't disable the wrong one.",
      es: "No son competidores. Trabajan juntos. Pero es importante entender qué hace cada uno para no desactivar el que no debes.",
      de: "Keine Konkurrenten. Sie arbeiten zusammen. Aber es ist wichtig zu verstehen, wer was tut, damit du nicht das Falsche deaktivierst.",
      pt: "Não são concorrentes. Eles trabalham juntos. Mas é importante entender quem faz o quê para não desativar o errado.",
      fr: "Pas des concurrents. Ils fonctionnent ensemble. Mais il est important de comprendre qui fait quoi pour ne pas désactiver le mauvais.",
      pl: "Nie są konkurentami. Współpracują ze sobą. Ale ważne jest, żeby wiedzieć, kto co robi, żeby nie wyłączyć tej niewłaściwej.",
      tr: "Rakip değiller. Birlikte çalışıyorlar. Ama yanlış olanı devre dışı bırakmamak için kimin ne yaptığını anlamak önemli.",
      nl: "Geen concurrenten. Ze werken samen. Maar het is belangrijk te begrijpen wie wat doet, zodat je niet de verkeerde uitschakelt.",
      ja: "競合ではありません。連携して動作します。ただし、誤ったものを無効にしないために、どちらが何をするかを理解することが重要です。",
      ko: "경쟁자가 아닙니다. 함께 작동합니다. 하지만 잘못된 것을 비활성화하지 않으려면 누가 무엇을 하는지 이해하는 것이 중요합니다.",
    },
  },
  body: [
    {
      type: "paragraph",
      text: {
        it: "Samsung Health e Health Connect non sono concorrenti: lavorano insieme, e disabilitare quella sbagliata interrompe il sync del Galaxy Watch o impedisce alle app terze di leggere i tuoi dati. Samsung Health raccoglie i dati dal Watch; Health Connect è il quadro elettrico dei permessi che decide cosa esce verso le altre app. Capire questa distinzione risolve il 90% delle domande su Galaxy Watch e app fitness.",
        en: "Samsung Health and Health Connect are not competitors: they work together, and disabling the wrong one either breaks Galaxy Watch sync or stops third-party apps from reading your data. Samsung Health collects data from the Watch; Health Connect is the permissions panel that decides what flows out to other apps. Understanding this distinction resolves 90% of questions about Galaxy Watch and fitness apps.",
        es: "Samsung Health y Health Connect no son competidores: trabajan juntos, y desactivar el incorrecto puede romper la sincronización del Galaxy Watch o impedir que las apps de terceros lean tus datos. Samsung Health recopila los datos del Watch; Health Connect es el panel de permisos que decide qué sale hacia las demás apps. Entender esta distinción resuelve el 90% de las dudas sobre Galaxy Watch y apps de fitness.",
        de: "Samsung Health und Health Connect sind keine Konkurrenten: Sie arbeiten zusammen, und das Deaktivieren des falschen unterbricht entweder die Galaxy Watch-Synchronisierung oder verhindert, dass Drittanbieter-Apps deine Daten lesen. Samsung Health empfängt Daten vom Watch; Health Connect ist das Berechtigungs-Panel, das entscheidet, was an andere Apps weitergegeben wird. Wer diesen Unterschied versteht, löst 90 % der Fragen zu Galaxy Watch und Fitness-Apps.",
        pt: "Samsung Health e Health Connect não são concorrentes: eles trabalham juntos, e desativar o errado pode quebrar a sincronização do Galaxy Watch ou impedir que apps de terceiros leiam seus dados. O Samsung Health coleta dados do Watch; o Health Connect é o painel de permissões que decide o que sai para outros apps. Entender essa distinção resolve 90% das dúvidas sobre Galaxy Watch e apps de saúde.",
        fr: "Samsung Health et Health Connect ne sont pas des concurrents : ils fonctionnent ensemble, et désactiver le mauvais interrompt soit la synchronisation du Galaxy Watch, soit l'accès des applications tierces à vos données. Samsung Health collecte les données de la montre; Health Connect est le panneau de permissions qui décide ce qui est transmis aux autres applications. Comprendre cette distinction résout 90 % des questions sur Galaxy Watch et les applications fitness.",
        pl: "Samsung Health i Health Connect nie są konkurentami: współpracują ze sobą, a wyłączenie niewłaściwej albo zrywa synchronizację Galaxy Watch, albo uniemożliwia aplikacjom trzecim odczyt Twoich danych. Samsung Health zbiera dane z zegarka; Health Connect to panel uprawnień decydujący o tym, co trafia do innych aplikacji. Zrozumienie tej różnicy rozwiązuje 90% pytań o Galaxy Watch i aplikacje fitness.",
        tr: "Samsung Health ve Health Connect rakip değil: birlikte çalışıyorlar ve yanlış olanı devre dışı bırakmak ya Galaxy Watch senkronizasyonunu kesiyor ya da üçüncü taraf uygulamaların verilerinizi okumasını engelliyor. Samsung Health Watch'tan veri topluyor; Health Connect ise diğer uygulamalara neyin aktarılacağına karar veren izin panelidir. Bu farkı anlamak, Galaxy Watch ve fitness uygulamalarıyla ilgili soruların %90'ını çözüyor.",
        nl: "Samsung Health en Health Connect zijn geen concurrenten: ze werken samen, en het uitschakelen van de verkeerde verbreekt ofwel de Galaxy Watch-synchronisatie ofwel het lezen van je gegevens door apps van derden. Samsung Health verzamelt gegevens van de Watch; Health Connect is het machtigingenpaneel dat bepaalt wat naar andere apps gaat. Dit onderscheid begrijpen lost 90% van de vragen over Galaxy Watch en fitnessapps op.",
        ja: "Samsung HealthとHealth Connectは競合していません：連携して動作し、誤った方を無効にするとGalaxy Watchの同期が壊れるか、サードパーティアプリによるデータ読み取りが停止します。Samsung HealthはWatchからデータを収集し、Health Connectは他のアプリへの出力を決める権限パネルです。この違いを理解することで、Galaxy Watchとフィットネスアプリに関する質問の90%が解決します。",
        ko: "Samsung Health와 Health Connect는 경쟁자가 아닙니다: 함께 작동하며, 잘못된 것을 비활성화하면 Galaxy Watch 동기화가 끊기거나 타사 앱이 데이터를 읽지 못하게 됩니다. Samsung Health는 Watch에서 데이터를 수집하고, Health Connect는 다른 앱으로 무엇이 나가는지 결정하는 권한 패널입니다. 이 차이를 이해하면 Galaxy Watch와 피트니스 앱에 관한 질문의 90%가 해결됩니다.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Samsung Health: l'app del produttore",
        en: "Samsung Health: the manufacturer's app",
        es: "Samsung Health: la app del fabricante",
        de: "Samsung Health: die App des Herstellers",
        pt: "Samsung Health: o app do fabricante",
        fr: "Samsung Health: l'application du fabricant",
        pl: "Samsung Health: aplikacja producenta",
        tr: "Samsung Health: üreticinin uygulaması",
        nl: "Samsung Health: de app van de fabrikant",
        ja: "Samsung Health：メーカーのアプリ",
        ko: "Samsung Health: 제조사의 앱",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Samsung Health è l'app companion ufficiale per Galaxy Watch (e accessoriamente per altri device Samsung). Il suo lavoro è:",
        en: "Samsung Health is the official companion app for Galaxy Watch (and accessorily for other Samsung devices). Its job:",
        es: "Samsung Health es la app compañera oficial para Galaxy Watch (y también para otros dispositivos Samsung). Sus funciones son:",
        de: "Samsung Health ist die offizielle Begleit-App für Galaxy Watch (und auch für andere Samsung-Geräte). Ihre Aufgaben:",
        pt: "O Samsung Health é o app companion oficial para o Galaxy Watch (e também para outros dispositivos Samsung). Suas funções:",
        fr: "Samsung Health est l'application compagnon officielle pour Galaxy Watch (et accessoirement pour d'autres appareils Samsung). Son rôle :",
        pl: "Samsung Health to oficjalna aplikacja towarzysząca dla Galaxy Watch (i pomocniczo dla innych urządzeń Samsung). Jej zadania:",
        tr: "Samsung Health, Galaxy Watch için resmi companion uygulamasıdır (ve isteğe bağlı olarak diğer Samsung cihazları için). Görevi:",
        nl: "Samsung Health is de officiële companion-app voor Galaxy Watch (en bijkomend voor andere Samsung-apparaten). Zijn taak:",
        ja: "Samsung HealthはGalaxy Watch（および他のSamsungデバイス）の公式コンパニオンアプリです。その役割：",
        ko: "Samsung Health는 Galaxy Watch(및 기타 Samsung 기기)의 공식 컴패니언 앱입니다. 역할：",
      },
    },
    {
      type: "list",
      items: {
        it: [
          "Ricevere i dati dal Watch via Bluetooth.",
          "Visualizzarli in dashboard, grafici, achievement, programmi guidati.",
          "Sincronizzarli col cloud Samsung Health (se hai un Samsung Account e l'opzione è attiva).",
          "Da metà 2024, scrivere automaticamente su Health Connect i tipi di dato richiesti.",
        ],
        en: [
          "Receive data from the Watch via Bluetooth.",
          "Display it in dashboards, charts, achievements, guided programs.",
          "Sync it with the Samsung Health cloud (if you have a Samsung Account and the option is on).",
          "Since mid-2024, automatically write to Health Connect for the requested data types.",
        ],
        es: [
          "Recibir los datos del Watch por Bluetooth.",
          "Mostrarlos en paneles, gráficos, logros y programas guiados.",
          "Sincronizarlos con la nube de Samsung Health (si tienes una Samsung Account y la opción está activada).",
          "Desde mediados de 2024, escribir automáticamente en Health Connect los tipos de dato permitidos.",
        ],
        de: [
          "Daten vom Watch per Bluetooth empfangen.",
          "Sie in Dashboards, Diagrammen, Achievements und geführten Programmen anzeigen.",
          "Sie mit der Samsung Health-Cloud synchronisieren (wenn du ein Samsung-Konto hast und die Option aktiviert ist).",
          "Seit Mitte 2024: automatisch die angeforderten Datentypen in Health Connect schreiben.",
        ],
        pt: [
          "Receber dados do Watch via Bluetooth.",
          "Exibi-los em painéis, gráficos, conquistas e programas guiados.",
          "Sincronizá-los com a nuvem do Samsung Health (se você tiver uma Samsung Account e a opção estiver ativa).",
          "Desde meados de 2024, escrever automaticamente no Health Connect os tipos de dados solicitados.",
        ],
        fr: [
          "Recevoir les données de la montre via Bluetooth.",
          "Les afficher dans des tableaux de bord, graphiques, succès et programmes guidés.",
          "Les synchroniser avec le cloud Samsung Health (si vous avez un compte Samsung et l'option activée).",
          "Depuis mi-2024, écrire automatiquement dans Health Connect les types de données demandés.",
        ],
        pl: [
          "Odbierać dane z zegarka przez Bluetooth.",
          "Wyświetlać je w panelach, wykresach, osiągnięciach i programach treningowych.",
          "Synchronizować je z chmurą Samsung Health (jeśli masz konto Samsung i opcja jest włączona).",
          "Od połowy 2024 roku automatycznie zapisywać żądane typy danych do Health Connect.",
        ],
        tr: [
          "Watch'tan Bluetooth üzerinden veri almak.",
          "Verileri panolarda, grafiklerde, başarımlarda ve rehberli programlarda görüntülemek.",
          "Verileri Samsung Health bulutuna senkronize etmek (Samsung hesabınız varsa ve seçenek açıksa).",
          "2024 ortasından itibaren, istenen veri türlerini otomatik olarak Health Connect'e yazmak.",
        ],
        nl: [
          "Gegevens ontvangen van de Watch via Bluetooth.",
          "Deze weergeven in dashboards, grafieken, prestaties en begeleide programma's.",
          "Synchroniseren met de Samsung Health-cloud (als je een Samsung-account hebt en de optie ingeschakeld is).",
          "Sinds medio 2024: automatisch de gevraagde gegevenstypen naar Health Connect schrijven.",
        ],
        ja: [
          "Bluetooth経由でWatchからデータを受信する。",
          "ダッシュボード、グラフ、実績、ガイドプログラムに表示する。",
          "Samsung Healthクラウドと同期する（Samsung Accountがあり、オプションがオンの場合）。",
          "2024年半ばから、要求されたデータタイプをHealth Connectに自動的に書き込む。",
        ],
        ko: [
          "Bluetooth를 통해 Watch에서 데이터를 수신한다.",
          "대시보드, 차트, 성취, 가이드 프로그램에 표시한다.",
          "Samsung Health 클라우드와 동기화한다 (Samsung 계정이 있고 옵션이 켜져 있는 경우).",
          "2024년 중반부터 요청된 데이터 유형을 Health Connect에 자동으로 기록한다.",
        ],
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Samsung Health è proprietaria, focalizzata su esperienza utente Samsung, e include feature consumer come food tracking, programmi fitness guidati, dashboard sociale (sfide tra amici). Il suo modello di dati è del tutto sue (formato interno, non documentato pubblicamente).",
        en: "Samsung Health is proprietary, focused on the Samsung user experience, and includes consumer features like food tracking, guided fitness programs, social dashboard (challenges with friends). Its data model is fully its own (internal format, not publicly documented).",
        es: "Samsung Health es propietaria, orientada a la experiencia de usuario Samsung, e incluye funciones de consumo como seguimiento de alimentación, programas de fitness guiados y panel social (retos entre amigos). Su modelo de datos es completamente propio (formato interno, no documentado públicamente).",
        de: "Samsung Health ist proprietär, auf das Samsung-Nutzererlebnis ausgerichtet und enthält Verbraucher-Features wie Ernährungstracking, geführte Fitness-Programme und ein soziales Dashboard (Challenges mit Freunden). Das Datenmodell ist vollständig proprietär (internes Format, nicht öffentlich dokumentiert).",
        pt: "O Samsung Health é proprietário, focado na experiência do usuário Samsung, e inclui funcionalidades voltadas ao consumidor, como rastreamento de alimentação, programas de fitness guiados e painel social (desafios com amigos). Seu modelo de dados é totalmente próprio (formato interno, não documentado publicamente).",
        fr: "Samsung Health est propriétaire, centré sur l'expérience utilisateur Samsung, et inclut des fonctionnalités grand public telles que le suivi alimentaire, les programmes fitness guidés et un tableau de bord social (défis entre amis). Son modèle de données est entièrement propriétaire (format interne, non documenté publiquement).",
        pl: "Samsung Health jest zastrzeżoną aplikacją, skupioną na doświadczeniu użytkownika Samsung, i zawiera funkcje konsumenckie, takie jak śledzenie żywności, prowadzone programy fitness i społeczny panel (wyzwania ze znajomymi). Jej model danych jest w pełni własny (format wewnętrzny, nie publicznie udokumentowany).",
        tr: "Samsung Health özel mülkiyetli bir uygulamadır, Samsung kullanıcı deneyimine odaklanmış ve yiyecek takibi, rehberli fitness programları, sosyal pano (arkadaşlarla yarışmalar) gibi tüketici özellikleri içeriyor. Veri modeli tamamen kendine aittir (dahili format, kamuya açıklanmamış).",
        nl: "Samsung Health is eigendomssoftware, gericht op de Samsung-gebruikerservaring, en bevat consumentenfuncties zoals voedingstracking, begeleide fitnessprogramma's en een sociaal dashboard (uitdagingen met vrienden). Het gegevensmodel is volledig van henzelf (intern formaat, niet openbaar gedocumenteerd).",
        ja: "Samsung Healthは独自仕様で、Samsungユーザー体験に特化しており、食事追跡、ガイド付きフィットネスプログラム、ソーシャルダッシュボード（友人とのチャレンジ）などの消費者向け機能を含みます。データモデルは完全に独自のものです（内部形式、公開未ドキュメント）。",
        ko: "Samsung Health는 독점 소프트웨어로 Samsung 사용자 경험에 집중하며, 식품 추적, 가이드 피트니스 프로그램, 소셜 대시보드(친구와의 챌린지) 같은 소비자 기능을 포함합니다. 데이터 모델은 완전히 독자적입니다(내부 형식, 공개 미문서화).",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Health Connect: il livello di scambio Android",
        en: "Health Connect: the Android exchange layer",
        es: "Health Connect: la capa de intercambio de Android",
        de: "Health Connect: die Android-Austauschschicht",
        pt: "Health Connect: a camada de troca do Android",
        fr: "Health Connect: la couche d'échange Android",
        pl: "Health Connect: warstwa wymiany Androida",
        tr: "Health Connect: Android değişim katmanı",
        nl: "Health Connect: de Android-uitwisselingslaag",
        ja: "Health Connect：Androidの交換レイヤー",
        ko: "Health Connect: Android 교환 레이어",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Health Connect è una API e un'app distribuita da Google, pensata come livello neutrale dove tutte le app salute Android scrivono e leggono. Non ha una dashboard utente ricca: è quasi solo un pannello di controllo che ti mostra:",
        en: "Health Connect is an API and an app distributed by Google, designed as a neutral layer where all Android health apps write and read. It doesn't have a rich user dashboard: it's almost just a control panel showing you:",
        es: "Health Connect es una API y una app distribuida por Google, diseñada como capa neutral donde todas las apps de salud de Android leen y escriben datos. No tiene un panel de usuario completo: es casi exclusivamente un panel de control que te muestra:",
        de: "Health Connect ist eine API und eine von Google verteilte App, die als neutrale Schicht konzipiert ist, in die alle Android-Gesundheits-Apps schreiben und lesen. Es bietet kein umfangreiches Nutzer-Dashboard: Es ist fast nur ein Kontrollpanel, das dir zeigt:",
        pt: "O Health Connect é uma API e um app distribuído pelo Google, projetado como uma camada neutra onde todos os apps de saúde do Android escrevem e leem dados. Ele não tem um painel de usuário completo: é quase apenas um painel de controle que mostra:",
        fr: "Health Connect est une API et une application distribuée par Google, conçue comme une couche neutre où toutes les applications de santé Android écrivent et lisent des données. Elle ne dispose pas d'un tableau de bord utilisateur riche : c'est presque uniquement un panneau de contrôle qui vous affiche :",
        pl: "Health Connect to API i aplikacja dystrybuowana przez Google, zaprojektowana jako neutralna warstwa, w której wszystkie androidowe aplikacje zdrowotne piszą i czytają dane. Nie ma bogatego panelu użytkownika: to niemal tylko panel sterowania, który pokazuje Ci:",
        tr: "Health Connect, Google tarafından dağıtılan bir API ve uygulamadır; tüm Android sağlık uygulamalarının yazdığı ve okuduğu nötr bir katman olarak tasarlanmıştır. Zengin bir kullanıcı panosu yok: neredeyse sadece size şunları gösteren bir kontrol paneli:",
        nl: "Health Connect is een API en een app die door Google wordt verspreid, ontworpen als neutrale laag waar alle Android-gezondheidsapps schrijven en lezen. Het heeft geen uitgebreid gebruikersdashboard: het is vrijwel alleen een configuratiepaneel dat je het volgende toont:",
        ja: "Health ConnectはGoogleが配布するAPIとアプリで、すべてのAndroidヘルスアプリが書き込みと読み取りを行う中立的なレイヤーとして設計されています。充実したユーザーダッシュボードはなく、ほぼ次を表示するコントロールパネルのみです：",
        ko: "Health Connect는 Google이 배포하는 API와 앱으로, 모든 Android 건강 앱이 쓰고 읽는 중립적인 레이어로 설계되었습니다. 풍부한 사용자 대시보드는 없으며, 거의 다음을 보여주는 제어판입니다：",
      },
    },
    {
      type: "list",
      items: {
        it: [
          "Quali app hanno il permesso di leggere ogni tipo di dato (passi, BPM, sonno, etc.).",
          "Quali app hanno il permesso di scrivere.",
          "Cronologia di chi ha letto cosa quando.",
          "Pulsante per revocare permessi singolarmente.",
        ],
        en: [
          "Which apps have permission to read each data type (steps, HR, sleep, etc.).",
          "Which apps have permission to write.",
          "History of who read what when.",
          "Button to revoke permissions individually.",
        ],
        es: [
          "Qué apps tienen permiso para leer cada tipo de dato (pasos, frecuencia cardíaca, sueño, etc.).",
          "Qué apps tienen permiso para escribir.",
          "Historial de quién ha leído qué y cuándo.",
          "Botón para revocar permisos individualmente.",
        ],
        de: [
          "Welche Apps die Berechtigung haben, jeden Datentyp zu lesen (Schritte, Herzfrequenz, Schlaf usw.).",
          "Welche Apps die Berechtigung haben, zu schreiben.",
          "Verlauf, wer wann was gelesen hat.",
          "Schaltfläche zum einzelnen Widerrufen von Berechtigungen.",
        ],
        pt: [
          "Quais apps têm permissão para ler cada tipo de dado (passos, frequência cardíaca, sono, etc.).",
          "Quais apps têm permissão para escrever.",
          "Histórico de quem leu o quê e quando.",
          "Botão para revogar permissões individualmente.",
        ],
        fr: [
          "Quelles applications ont la permission de lire chaque type de données (pas, fréquence cardiaque, sommeil, etc.).",
          "Quelles applications ont la permission d'écrire.",
          "Historique de qui a lu quoi et quand.",
          "Bouton pour révoquer les permissions individuellement.",
        ],
        pl: [
          "Które aplikacje mają uprawnienia do odczytu każdego typu danych (kroki, tętno, sen itp.).",
          "Które aplikacje mają uprawnienia do zapisu.",
          "Historia kto co i kiedy odczytał.",
          "Przycisk do indywidualnego cofania uprawnień.",
        ],
        tr: [
          "Hangi uygulamaların her veri türünü okuma izni var (adım, nabız, uyku vb.).",
          "Hangi uygulamaların yazma izni var.",
          "Kimin ne zaman ne okuduğunun geçmişi.",
          "İzinleri tek tek iptal etmek için düğme.",
        ],
        nl: [
          "Welke apps toestemming hebben om elk gegevenstype te lezen (stappen, hartslag, slaap, etc.).",
          "Welke apps toestemming hebben om te schrijven.",
          "Geschiedenis van wie wat wanneer heeft gelezen.",
          "Knop om machtigingen afzonderlijk in te trekken.",
        ],
        ja: [
          "どのアプリが各データタイプ（歩数、心拍数、睡眠など）を読む権限を持っているか。",
          "どのアプリが書き込む権限を持っているか。",
          "誰がいつ何を読んだかの履歴。",
          "権限を個別に取り消すボタン。",
        ],
        ko: [
          "어떤 앱이 각 데이터 유형(걸음 수, 심박수, 수면 등)을 읽을 권한이 있는지.",
          "어떤 앱이 쓰기 권한이 있는지.",
          "누가 언제 무엇을 읽었는지의 기록.",
          "권한을 개별적으로 취소하는 버튼.",
        ],
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Il modello dati Health Connect è documentato pubblicamente (developer.android.com/health-connect), strutturato, e ogni tipo è una classe esplicita. È la versione 2.0 di Google Fit, completamente on-device.",
        en: "The Health Connect data model is publicly documented (developer.android.com/health-connect), structured, and each type is an explicit class. It's Google Fit 2.0, fully on-device.",
        es: "El modelo de datos de Health Connect está documentado públicamente (developer.android.com/health-connect), es estructurado y cada tipo es una clase explícita. Es Google Fit 2.0, completamente en el dispositivo.",
        de: "Das Health Connect-Datenmodell ist öffentlich dokumentiert (developer.android.com/health-connect), strukturiert, und jeder Typ ist eine explizite Klasse. Es ist Google Fit 2.0, vollständig auf dem Gerät.",
        pt: "O modelo de dados do Health Connect é documentado publicamente (developer.android.com/health-connect), estruturado, e cada tipo é uma classe explícita. É o Google Fit 2.0, totalmente no dispositivo.",
        fr: "Le modèle de données Health Connect est documenté publiquement (developer.android.com/health-connect), structuré, et chaque type est une classe explicite. C'est Google Fit 2.0, entièrement sur l'appareil.",
        pl: "Model danych Health Connect jest publicznie udokumentowany (developer.android.com/health-connect), ustrukturyzowany, a każdy typ to jawna klasa. To Google Fit 2.0, w całości na urządzeniu.",
        tr: "Health Connect veri modeli kamuya açık belgelenmiş (developer.android.com/health-connect), yapılandırılmış ve her tür açık bir sınıftır. Tamamen cihaz üzerinde çalışan Google Fit 2.0'dır.",
        nl: "Het Health Connect-gegevensmodel is openbaar gedocumenteerd (developer.android.com/health-connect), gestructureerd en elk type is een expliciete klasse. Het is Google Fit 2.0, volledig op het apparaat.",
        ja: "Health Connectデータモデルは公開ドキュメント化されており（developer.android.com/health-connect）、構造化されていて、各タイプは明示的なクラスです。完全にデバイス上で動作するGoogle Fit 2.0です。",
        ko: "Health Connect 데이터 모델은 공개 문서화되어 있으며(developer.android.com/health-connect), 구조화되어 있고 각 유형은 명시적 클래스입니다. 완전히 기기에서 실행되는 Google Fit 2.0입니다.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Come lavorano insieme",
        en: "How they work together",
        es: "Cómo trabajan juntos",
        de: "Wie sie zusammenarbeiten",
        pt: "Como eles trabalham juntos",
        fr: "Comment ils fonctionnent ensemble",
        pl: "Jak współpracują ze sobą",
        tr: "Birlikte nasıl çalışırlar",
        nl: "Hoe ze samenwerken",
        ja: "どのように連携するか",
        ko: "함께 작동하는 방식",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Sul tuo Galaxy Watch, il flusso reale dei dati è:",
        en: "On your Galaxy Watch, the actual data flow is:",
        es: "En tu Galaxy Watch, el flujo real de datos es:",
        de: "Auf deiner Galaxy Watch ist der tatsächliche Datenfluss:",
        pt: "No seu Galaxy Watch, o fluxo real de dados é:",
        fr: "Sur votre Galaxy Watch, le flux de données réel est :",
        pl: "Na Twoim Galaxy Watch rzeczywisty przepływ danych to:",
        tr: "Galaxy Watch'ınızda gerçek veri akışı şöyle:",
        nl: "Op je Galaxy Watch is de werkelijke gegevensstroom:",
        ja: "Galaxy Watchでの実際のデータフローは：",
        ko: "Galaxy Watch에서 실제 데이터 흐름은：",
      },
    },
    {
      type: "list",
      ordered: true,
      items: {
        it: [
          "Sensori del Watch → BLE → Samsung Health (app principale).",
          "Samsung Health archivia internamente + (se attivato) scrive su Health Connect i tipi di dato consentiti.",
          "Health Connect tiene una copia neutrale dei dati ed espone l'API a chiunque abbia il permesso.",
          "App terze (FitMesh Sync, Strava, MyFitnessPal, app di sleep coaching, etc.) leggono via Health Connect.",
        ],
        en: [
          "Watch sensors → BLE → Samsung Health (main app).",
          "Samsung Health stores internally + (if enabled) writes to Health Connect the allowed data types.",
          "Health Connect keeps a neutral copy of data and exposes the API to anyone with permission.",
          "Third-party apps (FitMesh Sync, Strava, MyFitnessPal, sleep coaching apps, etc.) read via Health Connect.",
        ],
        es: [
          "Sensores del Watch → BLE → Samsung Health (app principal).",
          "Samsung Health guarda internamente y (si está activado) escribe en Health Connect los tipos de dato permitidos.",
          "Health Connect mantiene una copia neutral de los datos y expone su acceso a cualquier app con permiso.",
          "Apps de terceros (FitMesh Sync, Strava, MyFitnessPal, apps de seguimiento del sueño, etc.) leen a través de Health Connect.",
        ],
        de: [
          "Watch-Sensoren → BLE → Samsung Health (Haupt-App).",
          "Samsung Health speichert intern + schreibt (wenn aktiviert) die erlaubten Datentypen in Health Connect.",
          "Health Connect bewahrt eine neutrale Kopie der Daten und stellt die Schnittstelle für jeden mit Berechtigung bereit.",
          "Drittanbieter-Apps (FitMesh Sync, Strava, MyFitnessPal, Schlaf-Coaching-Apps usw.) lesen über Health Connect.",
        ],
        pt: [
          "Sensores do Watch → BLE → Samsung Health (app principal).",
          "O Samsung Health armazena internamente e (se ativado) escreve no Health Connect os tipos de dados permitidos.",
          "O Health Connect mantém uma cópia neutra dos dados e expõe o acesso a qualquer app com permissão.",
          "Apps de terceiros (FitMesh Sync, Strava, MyFitnessPal, apps de acompanhamento do sono, etc.) leem via Health Connect.",
        ],
        fr: [
          "Capteurs de la montre → BLE → Samsung Health (application principale).",
          "Samsung Health stocke en interne et (si activé) écrit dans Health Connect les types de données autorisés.",
          "Health Connect conserve une copie neutre des données et expose l'accès à quiconque dispose d'une permission.",
          "Les applications tierces (FitMesh Sync, Strava, MyFitnessPal, applications de coaching du sommeil, etc.) lisent via Health Connect.",
        ],
        pl: [
          "Czujniki zegarka → BLE → Samsung Health (główna aplikacja).",
          "Samsung Health przechowuje dane wewnętrznie + (jeśli włączono) zapisuje dozwolone typy danych do Health Connect.",
          "Health Connect przechowuje neutralną kopię danych i udostępnia API każdemu z uprawnieniami.",
          "Aplikacje trzecie (FitMesh Sync, Strava, MyFitnessPal, aplikacje do coachingu snu itp.) odczytują przez Health Connect.",
        ],
        tr: [
          "Watch sensörleri → BLE → Samsung Health (ana uygulama).",
          "Samsung Health dahili olarak saklar + (etkinleştirilmişse) izin verilen veri türlerini Health Connect'e yazar.",
          "Health Connect verilerin nötr bir kopyasını tutar ve izni olana API'yi açar.",
          "Üçüncü taraf uygulamalar (FitMesh Sync, Strava, MyFitnessPal, uyku koçluğu uygulamaları vb.) Health Connect üzerinden okur.",
        ],
        nl: [
          "Watch-sensoren → BLE → Samsung Health (hoofdapp).",
          "Samsung Health slaat intern op + schrijft (indien ingeschakeld) de toegestane gegevenstypen naar Health Connect.",
          "Health Connect bewaart een neutrale kopie van de gegevens en stelt de API beschikbaar aan iedereen met toestemming.",
          "Apps van derden (FitMesh Sync, Strava, MyFitnessPal, slaapcoaching-apps, etc.) lezen via Health Connect.",
        ],
        ja: [
          "Watchセンサー → BLE → Samsung Health（メインアプリ）。",
          "Samsung Healthは内部に保存し、（有効な場合）許可されたデータタイプをHealth Connectに書き込む。",
          "Health Connectはデータの中立的なコピーを保持し、権限を持つ人にAPIを公開する。",
          "サードパーティアプリ（FitMesh Sync、Strava、MyFitnessPal、睡眠コーチングアプリなど）はHealth Connect経由で読み取る。",
        ],
        ko: [
          "Watch 센서 → BLE → Samsung Health(메인 앱).",
          "Samsung Health는 내부에 저장하고 + (활성화된 경우) 허용된 데이터 유형을 Health Connect에 기록한다.",
          "Health Connect는 데이터의 중립적인 복사본을 유지하고 권한이 있는 사람에게 API를 공개한다.",
          "타사 앱(FitMesh Sync, Strava, MyFitnessPal, 수면 코칭 앱 등)은 Health Connect를 통해 읽는다.",
        ],
      },
    },
    {
      type: "callout",
      variant: "tip",
      title: {
        it: "Punto chiave",
        en: "Key point",
        es: "Punto clave",
        de: "Wichtiger Hinweis",
        pt: "Ponto-chave",
        fr: "Point clé",
        pl: "Kluczowa kwestia",
        tr: "Temel nokta",
        nl: "Kernpunt",
        ja: "重要ポイント",
        ko: "핵심 포인트",
      },
      body: {
        it: "Samsung Health è chi raccoglie i dati e li gestisce. Health Connect è il quadro elettrico dei permessi che decide cosa esce verso le altre app. Disattivare Samsung Health = il Watch non si sincronizza più. Disattivare Health Connect = le app terze non vedono più i dati, ma Samsung Health continua a funzionare.",
        en: "Samsung Health is who collects data and manages it. Health Connect is the electrical panel deciding what goes out to other apps. Disable Samsung Health = the Watch no longer syncs. Disable Health Connect = third-party apps no longer see data, but Samsung Health keeps working.",
        es: "Samsung Health es quien recopila los datos y los gestiona. Health Connect es el panel de permisos que decide qué sale hacia las demás apps. Desactivar Samsung Health = el Watch deja de sincronizarse. Desactivar Health Connect = las apps de terceros dejan de ver los datos, pero Samsung Health sigue funcionando.",
        de: "Samsung Health ist diejenige, die Daten sammelt und verwaltet. Health Connect ist die Berechtigungszentrale, die entscheidet, was an andere Apps weitergegeben wird. Samsung Health deaktivieren = die Watch synchronisiert nicht mehr. Health Connect deaktivieren = Drittanbieter-Apps sehen keine Daten mehr, aber Samsung Health funktioniert weiterhin.",
        pt: "O Samsung Health é quem coleta e gerencia os dados. O Health Connect é o painel de controle de permissões que decide o que sai para outros apps. Desativar o Samsung Health = o Watch para de sincronizar. Desativar o Health Connect = apps de terceiros não veem mais os dados, mas o Samsung Health continua funcionando.",
        fr: "Samsung Health est celui qui collecte et gère les données. Health Connect est le panneau de permissions qui décide ce qui est transmis aux autres applications. Désactiver Samsung Health = la montre ne se synchronise plus. Désactiver Health Connect = les applications tierces ne voient plus les données, mais Samsung Health continue de fonctionner.",
        pl: "Samsung Health to ten, który zbiera dane i nimi zarządza. Health Connect to panel uprawnień decydujący o tym, co trafia do innych aplikacji. Wyłącz Samsung Health = zegarek nie synchronizuje się. Wyłącz Health Connect = aplikacje trzecie nie widzą danych, ale Samsung Health nadal działa.",
        tr: "Samsung Health veri toplayan ve yöneten. Health Connect ise diğer uygulamalara neyin aktarılacağına karar veren izin paneli. Samsung Health'i devre dışı bırak = Watch artık senkronize olmaz. Health Connect'i devre dışı bırak = üçüncü taraf uygulamalar veri göremez, ama Samsung Health çalışmaya devam eder.",
        nl: "Samsung Health is degene die gegevens verzamelt en beheert. Health Connect is het machtigingenpaneel dat bepaalt wat naar andere apps gaat. Samsung Health uitschakelen = de Watch synchroniseert niet meer. Health Connect uitschakelen = apps van derden zien geen gegevens meer, maar Samsung Health blijft werken.",
        ja: "Samsung Healthはデータを収集・管理するものです。Health Connectは他のアプリへの出力を決める権限パネルです。Samsung Healthを無効にする = Watchが同期しなくなります。Health Connectを無効にする = サードパーティアプリはデータを見られなくなりますが、Samsung Healthは引き続き動作します。",
        ko: "Samsung Health는 데이터를 수집하고 관리하는 것입니다. Health Connect는 다른 앱으로 무엇이 나가는지 결정하는 권한 패널입니다. Samsung Health 비활성화 = Watch가 더 이상 동기화되지 않습니다. Health Connect 비활성화 = 타사 앱은 더 이상 데이터를 볼 수 없지만 Samsung Health는 계속 작동합니다.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Differenze pratiche, una per una",
        en: "Practical differences, one by one",
        es: "Diferencias prácticas, una por una",
        de: "Praktische Unterschiede, einer nach dem anderen",
        pt: "Diferenças práticas, uma por uma",
        fr: "Différences pratiques, une par une",
        pl: "Praktyczne różnice, jedna po drugiej",
        tr: "Pratik farklar, birer birer",
        nl: "Praktische verschillen, een voor een",
        ja: "実際の違い、一つずつ",
        ko: "실질적인 차이점, 하나씩",
      },
    },
    {
      type: "table",
      headers: {
        it: ["Aspetto", "Samsung Health", "Health Connect"],
        en: ["Aspect", "Samsung Health", "Health Connect"],
        es: ["Aspecto", "Samsung Health", "Health Connect"],
        de: ["Aspekt", "Samsung Health", "Health Connect"],
        pt: ["Aspecto", "Samsung Health", "Health Connect"],
        fr: ["Aspect", "Samsung Health", "Health Connect"],
        pl: ["Aspekt", "Samsung Health", "Health Connect"],
        tr: ["Konu", "Samsung Health", "Health Connect"],
        nl: ["Aspect", "Samsung Health", "Health Connect"],
        ja: ["項目", "Samsung Health", "Health Connect"],
        ko: ["항목", "Samsung Health", "Health Connect"],
      },
      rows: [
        {
          it: ["Funzione primaria", "App utente: visualizza, allenamenti, coaching", "Livello permessi tra app salute"],
          en: ["Primary function", "User app: visualize, workouts, coaching", "Permissions layer between health apps"],
          es: ["Función principal", "App de usuario: visualización, entrenamientos, coaching", "Capa de permisos entre apps de salud"],
          de: ["Hauptfunktion", "Nutzer-App: Anzeige, Trainings, Coaching", "Berechtigungsschicht zwischen Gesundheits-Apps"],
          pt: ["Função principal", "App do usuário: visualização, treinos, coaching", "Camada de permissões entre apps de saúde"],
          fr: ["Fonction principale", "Application utilisateur: visualisation, séances d'entraînement, coaching", "Couche de permissions entre applications de santé"],
          pl: ["Funkcja główna", "Aplikacja użytkownika: wizualizacja, treningi, coaching", "Warstwa uprawnień między aplikacjami zdrowotnymi"],
          tr: ["Birincil işlev", "Kullanıcı uygulaması: görselleştirme, antrenmanlar, koçluk", "Sağlık uygulamaları arasındaki izin katmanı"],
          nl: ["Primaire functie", "Gebruikersapp: visualiseren, trainingen, coaching", "Machtigingenlaag tussen gezondheidsapps"],
          ja: ["主な機能", "ユーザーアプリ：可視化、トレーニング、コーチング", "ヘルスアプリ間の権限レイヤー"],
          ko: ["주요 기능", "사용자 앱: 시각화, 운동, 코칭", "건강 앱 간의 권한 레이어"],
        },
        {
          it: ["Dashboard ricca", "Sì (passi, sonno, food, sfide, ECG, etc.)", "No (solo gestione permessi)"],
          en: ["Rich dashboard", "Yes (steps, sleep, food, challenges, ECG, etc.)", "No (permissions only)"],
          es: ["Panel completo", "Sí (pasos, sueño, alimentación, retos, ECG, etc.)", "No (solo gestión de permisos)"],
          de: ["Umfangreiches Dashboard", "Ja (Schritte, Schlaf, Ernährung, Challenges, EKG usw.)", "Nein (nur Berechtigungsverwaltung)"],
          pt: ["Painel completo", "Sim (passos, sono, alimentação, desafios, ECG, etc.)", "Não (somente gestão de permissões)"],
          fr: ["Tableau de bord complet", "Oui (pas, sommeil, alimentation, défis, ECG, etc.)", "Non (gestion des permissions uniquement)"],
          pl: ["Rozbudowany panel", "Tak (kroki, sen, jedzenie, wyzwania, EKG itp.)", "Nie (tylko zarządzanie uprawnieniami)"],
          tr: ["Zengin pano", "Evet (adım, uyku, yiyecek, yarışmalar, EKG vb.)", "Hayır (yalnızca izin yönetimi)"],
          nl: ["Uitgebreid dashboard", "Ja (stappen, slaap, voeding, uitdagingen, ECG, etc.)", "Nee (alleen machtigingsbeheer)"],
          ja: ["充実したダッシュボード", "あり（歩数、睡眠、食事、チャレンジ、ECGなど）", "なし（権限管理のみ）"],
          ko: ["풍부한 대시보드", "있음(걸음 수, 수면, 식품, 챌린지, ECG 등)", "없음(권한 관리만)"],
        },
        {
          it: ["Cloud sync", "Sì (Samsung Cloud, opt-in via Samsung Account)", "No (strettamente on-device)"],
          en: ["Cloud sync", "Yes (Samsung Cloud, opt-in via Samsung Account)", "No (strictly on-device)"],
          es: ["Sincronización en la nube", "Sí (Samsung Cloud, opcional con Samsung Account)", "No (estrictamente en el dispositivo)"],
          de: ["Cloud-Synchronisierung", "Ja (Samsung Cloud, opt-in über Samsung-Konto)", "Nein (strikt auf dem Gerät)"],
          pt: ["Sincronização na nuvem", "Sim (Samsung Cloud, opt-in via Samsung Account)", "Não (estritamente no dispositivo)"],
          fr: ["Synchronisation cloud", "Oui (Samsung Cloud, opt-in via compte Samsung)", "Non (strictement sur l'appareil)"],
          pl: ["Synchronizacja w chmurze", "Tak (Samsung Cloud, opt-in przez konto Samsung)", "Nie (ściśle na urządzeniu)"],
          tr: ["Bulut senkronizasyonu", "Evet (Samsung Cloud, Samsung hesabıyla isteğe bağlı)", "Hayır (yalnızca cihaz üzerinde)"],
          nl: ["Cloudsynchronisatie", "Ja (Samsung Cloud, opt-in via Samsung-account)", "Nee (strikt op het apparaat)"],
          ja: ["クラウド同期", "あり（Samsung Cloud、Samsung Accountでオプトイン）", "なし（完全にデバイス上）"],
          ko: ["클라우드 동기화", "있음(Samsung Cloud, Samsung 계정으로 선택 가입)", "없음(완전히 기기 내)"],
        },
        {
          it: ["Tipi di dato proprietari", "Sì (es. Body Composition, allenamenti guidati)", "No, solo schemi standard"],
          en: ["Proprietary data types", "Yes (e.g. Body Composition, guided workouts)", "No, only standard schemas"],
          es: ["Tipos de dato propietarios", "Sí (p. ej. composición corporal, entrenamientos guiados)", "No, solo esquemas estándar"],
          de: ["Proprietäre Datentypen", "Ja (z. B. Körperzusammensetzung, geführte Trainings)", "Nein, nur Standardschemata"],
          pt: ["Tipos de dados proprietários", "Sim (ex.: Composição Corporal, treinos guiados)", "Não, apenas esquemas padrão"],
          fr: ["Types de données propriétaires", "Oui (ex. Composition corporelle, séances guidées)", "Non, uniquement des schémas standard"],
          pl: ["Zastrzeżone typy danych", "Tak (np. Skład ciała, prowadzone treningi)", "Nie, tylko standardowe schematy"],
          tr: ["Tescilli veri türleri", "Evet (örn. Vücut Bileşimi, rehberli antrenmanlar)", "Hayır, yalnızca standart şemalar"],
          nl: ["Eigen gegevenstypen", "Ja (bijv. Lichaamssamenstelling, begeleide trainingen)", "Nee, alleen standaardschema's"],
          ja: ["独自データタイプ", "あり（例：体組成、ガイドトレーニング）", "なし、標準スキーマのみ"],
          ko: ["독점 데이터 유형", "있음(예: 체성분, 가이드 운동)", "없음, 표준 스키마만"],
        },
        {
          it: ["Esportazione manuale", "CSV via app, processo lungo", "Non c'è export utente (lo fanno le app terze)"],
          en: ["Manual export", "CSV via app, slow process", "No user export (third-party apps do it)"],
          es: ["Exportación manual", "CSV desde la app, proceso lento", "No hay exportación para el usuario (lo hacen las apps de terceros)"],
          de: ["Manueller Export", "CSV über die App, langsamer Prozess", "Kein Nutzer-Export (das erledigen Drittanbieter-Apps)"],
          pt: ["Exportação manual", "CSV via app, processo demorado", "Sem exportação para o usuário (feito por apps de terceiros)"],
          fr: ["Export manuel", "CSV via l'application, processus long", "Pas d'export utilisateur (c'est le rôle des applications tierces)"],
          pl: ["Ręczny eksport", "CSV przez aplikację, długi proces", "Brak eksportu użytkownika (robią to aplikacje trzecie)"],
          tr: ["Manuel dışa aktarma", "Uygulama üzerinden CSV, yavaş süreç", "Kullanıcı dışa aktarması yok (bunu üçüncü taraf uygulamalar yapar)"],
          nl: ["Handmatige export", "CSV via app, traag proces", "Geen gebruikersexport (apps van derden doen dit)"],
          ja: ["手動エクスポート", "アプリ経由のCSV、遅いプロセス", "ユーザーエクスポートなし（サードパーティアプリが行う）"],
          ko: ["수동 내보내기", "앱을 통한 CSV, 느린 과정", "사용자 내보내기 없음(타사 앱이 수행)"],
        },
        {
          it: ["Aggiornato da", "Samsung", "Google (con Play Store)"],
          en: ["Updated by", "Samsung", "Google (via Play Store)"],
          es: ["Actualizado por", "Samsung", "Google (a través de Play Store)"],
          de: ["Aktualisiert von", "Samsung", "Google (über den Play Store)"],
          pt: ["Atualizado por", "Samsung", "Google (via Play Store)"],
          fr: ["Mis à jour par", "Samsung", "Google (via Play Store)"],
          pl: ["Aktualizowany przez", "Samsung", "Google (przez Play Store)"],
          tr: ["Güncelleyen", "Samsung", "Google (Play Store üzerinden)"],
          nl: ["Bijgewerkt door", "Samsung", "Google (via Play Store)"],
          ja: ["更新者", "Samsung", "Google（Play Store経由）"],
          ko: ["업데이트 제공", "Samsung", "Google(Play Store 통해)"],
        },
      ],
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Quando usare cosa",
        en: "When to use which",
        es: "Cuándo usar cada uno",
        de: "Wann man was verwendet",
        pt: "Quando usar cada um",
        fr: "Lequel utiliser et quand",
        pl: "Kiedy używać którego",
        tr: "Hangisini ne zaman kullanmalı",
        nl: "Wanneer je welke gebruikt",
        ja: "どちらをいつ使うか",
        ko: "언제 어느 것을 사용할지",
      },
    },
    {
      type: "list",
      items: {
        it: [
          "**Vuoi vedere il tuo sonno con grafici dettagliati o seguire un programma di allenamento Samsung?** → Samsung Health.",
          "**Vuoi che un'app terza (es. MyFitnessPal, app dietologica, app coaching) legga i tuoi dati?** → Devi avere Health Connect e dare permessi.",
          "**Sei preoccupato che Samsung mandi i tuoi dati nel cloud?** → In Samsung Health → Impostazioni → Privacy disabilita 'Sincronizza con Samsung Cloud'. I dati restano locali e continuano a fluire verso Health Connect.",
          "**Vuoi capire chi sta leggendo i tuoi dati?** → Apri Health Connect → Accessibilità app: vedi la lista completa con timestamp.",
          "**Vuoi disinstallare una?** → Su Galaxy phone non puoi disinstallare Samsung Health (preinstallato), ma puoi disabilitarlo (perderai il sync Watch). Health Connect è preinstallato su Android 14+ e può essere disabilitato senza rompere Samsung Health.",
        ],
        en: [
          "**Want to see your sleep with detailed charts or follow a Samsung workout program?** → Samsung Health.",
          "**Want a third-party app (e.g. MyFitnessPal, dietitian app, coaching app) to read your data?** → You need Health Connect with granted permissions.",
          "**Worried Samsung sends your data to the cloud?** → In Samsung Health → Settings → Privacy disable 'Sync with Samsung Cloud'. Data stays local and keeps flowing to Health Connect.",
          "**Want to see who's reading your data?** → Open Health Connect → App accessibility: see the full list with timestamps.",
          "**Want to uninstall one?** → On Galaxy phones you can't uninstall Samsung Health (preinstalled) but you can disable it (you'll lose Watch sync). Health Connect is preinstalled on Android 14+ and can be disabled without breaking Samsung Health.",
        ],
        es: [
          "**¿Quieres ver tu sueño con gráficos detallados o seguir un programa de entrenamiento de Samsung?** → Samsung Health.",
          "**¿Quieres que una app de terceros (p. ej. MyFitnessPal, app de nutrición, app de coaching) lea tus datos?** → Necesitas Health Connect y darle los permisos correspondientes.",
          "**¿Te preocupa que Samsung envíe tus datos a la nube?** → En Samsung Health → Ajustes → Privacidad desactiva 'Sincronizar con Samsung Cloud'. Los datos quedan locales y siguen fluyendo hacia Health Connect.",
          "**¿Quieres saber quién está leyendo tus datos?** → Abre Health Connect → Acceso de apps: verás la lista completa con marcas de tiempo.",
          "**¿Quieres desinstalar una?** → En teléfonos Galaxy no puedes desinstalar Samsung Health (viene preinstalada), pero puedes desactivarla (perderás la sincronización con el Watch). Health Connect viene preinstalado en Android 14+ y puede desactivarse sin afectar a Samsung Health.",
        ],
        de: [
          "**Möchtest du deinen Schlaf mit detaillierten Diagrammen sehen oder einem Samsung-Trainingsprogramm folgen?** → Samsung Health.",
          "**Möchtest du, dass eine Drittanbieter-App (z. B. MyFitnessPal, Ernährungs-App, Coaching-App) deine Daten liest?** → Du benötigst Health Connect und musst Berechtigungen erteilen.",
          "**Machst du dir Sorgen, dass Samsung deine Daten in die Cloud sendet?** → In Samsung Health → Einstellungen → Datenschutz deaktiviere 'Mit Samsung Cloud synchronisieren'. Die Daten bleiben lokal und fließen weiterhin zu Health Connect.",
          "**Möchtest du wissen, wer deine Daten liest?** → Öffne Health Connect → App-Zugriff: Sieh die vollständige Liste mit Zeitstempeln.",
          "**Möchtest du eine deinstallieren?** → Auf Galaxy-Phones kannst du Samsung Health nicht deinstallieren (vorinstalliert), aber du kannst es deaktivieren (du verlierst die Watch-Synchronisierung). Health Connect ist auf Android 14+ vorinstalliert und kann deaktiviert werden, ohne Samsung Health zu beeinträchtigen.",
        ],
        pt: [
          "**Quer ver seu sono com gráficos detalhados ou seguir um programa de treino da Samsung?** → Samsung Health.",
          "**Quer que um app de terceiros (ex.: MyFitnessPal, app de nutrição, app de coaching) leia seus dados?** → Você precisa do Health Connect e deve conceder permissões.",
          "**Preocupado que a Samsung envie seus dados para a nuvem?** → Em Samsung Health → Configurações → Privacidade, desative 'Sincronizar com Samsung Cloud'. Os dados ficam locais e continuam fluindo para o Health Connect.",
          "**Quer saber quem está lendo seus dados?** → Abra o Health Connect → Acesso de apps: veja a lista completa com timestamps.",
          "**Quer desinstalar um?** → Em telefones Galaxy, você não pode desinstalar o Samsung Health (pré-instalado), mas pode desativá-lo (você perderá a sincronização com o Watch). O Health Connect vem pré-instalado no Android 14+ e pode ser desativado sem afetar o Samsung Health.",
        ],
        fr: [
          "**Vous souhaitez voir votre sommeil avec des graphiques détaillés ou suivre un programme d'entraînement Samsung ?** → Samsung Health.",
          "**Vous voulez qu'une application tierce (ex. MyFitnessPal, application nutritionnelle, application de coaching) lise vos données ?** → Vous avez besoin de Health Connect et devez accorder les permissions.",
          "**Vous craignez que Samsung envoie vos données dans le cloud ?** → Dans Samsung Health → Paramètres → Confidentialité, désactivez 'Synchroniser avec Samsung Cloud'. Les données restent locales et continuent de transiter vers Health Connect.",
          "**Vous voulez savoir qui lit vos données ?** → Ouvrez Health Connect → Accès des applications : voyez la liste complète avec les horodatages.",
          "**Vous voulez en désinstaller un ?** → Sur les téléphones Galaxy, vous ne pouvez pas désinstaller Samsung Health (préinstallé), mais vous pouvez le désactiver (vous perdrez la synchronisation Watch). Health Connect est préinstallé sur Android 14+ et peut être désactivé sans affecter Samsung Health.",
        ],
        pl: [
          "**Chcesz zobaczyć sen z szczegółowymi wykresami lub śledzić program treningowy Samsung?** → Samsung Health.",
          "**Chcesz, żeby aplikacja trzecia (np. MyFitnessPal, app dietetyczna, app coachingowa) odczytywała Twoje dane?** → Potrzebujesz Health Connect z przyznanymi uprawnieniami.",
          "**Martwisz się, że Samsung wysyła Twoje dane do chmury?** → W Samsung Health → Ustawienia → Prywatność wyłącz 'Synchronizuj z Samsung Cloud'. Dane pozostają lokalnie i nadal przepływają do Health Connect.",
          "**Chcesz zobaczyć, kto odczytuje Twoje dane?** → Otwórz Health Connect → Dostęp aplikacji: zobaczysz pełną listę z datami.",
          "**Chcesz odinstalować jedną?** → Na telefonach Galaxy nie możesz odinstalować Samsung Health (preinstalowana), ale możesz ją wyłączyć (stracisz synchronizację z zegarkiem). Health Connect jest preinstalowany na Android 14+ i można go wyłączyć bez szkody dla Samsung Health.",
        ],
        tr: [
          "**Uykunuzu ayrıntılı grafiklerle görmek veya Samsung antrenman programı takip etmek mi istiyorsunuz?** → Samsung Health.",
          "**Bir üçüncü taraf uygulamanın (örn. MyFitnessPal, diyet uygulaması, koçluk uygulaması) verilerinizi okumasını mı istiyorsunuz?** → Health Connect'e ihtiyacınız var ve izin vermeniz gerekiyor.",
          "**Samsung'un verilerinizi buluta gönderdiğinden endişe mi duyuyorsunuz?** → Samsung Health → Ayarlar → Gizlilik'te 'Samsung Cloud ile senkronize et'i devre dışı bırakın. Veriler yerel kalır ve Health Connect'e akmaya devam eder.",
          "**Verilerinizi kimin okuduğunu görmek mi istiyorsunuz?** → Health Connect → Uygulama erişimi: zaman damgalarıyla tam listeyi görün.",
          "**Birini kaldırmak mı istiyorsunuz?** → Galaxy telefonlarda Samsung Health'i kaldıramazsınız (önceden yüklenmiş), ancak devre dışı bırakabilirsiniz (Watch senkronizasyonunu kaybedersiniz). Health Connect Android 14+ üzerinde önceden yüklü ve Samsung Health'i etkilemeden devre dışı bırakılabilir.",
        ],
        nl: [
          "**Wil je je slaap zien met gedetailleerde grafieken of een Samsung trainingsprogramma volgen?** → Samsung Health.",
          "**Wil je dat een app van derden (bijv. MyFitnessPal, dieetapp, coachingapp) je gegevens leest?** → Je hebt Health Connect nodig met verleende machtigingen.",
          "**Bezorgd dat Samsung je gegevens naar de cloud stuurt?** → Schakel in Samsung Health → Instellingen → Privacy 'Synchroniseren met Samsung Cloud' uit. Gegevens blijven lokaal en blijven naar Health Connect stromen.",
          "**Wil je zien wie je gegevens leest?** → Open Health Connect → App-toegang: zie de volledige lijst met tijdstempels.",
          "**Wil je er een verwijderen?** → Op Galaxy-telefoons kun je Samsung Health niet verwijderen (vooraf geinstalleerd), maar je kunt het uitschakelen (je verliest de Watch-synchronisatie). Health Connect is vooraf geinstalleerd op Android 14+ en kan worden uitgeschakeld zonder Samsung Health te beinvloeden.",
        ],
        ja: [
          "**詳細なグラフで睡眠を確認したり、Samsungトレーニングプログラムを使いたいですか？** → Samsung Health。",
          "**サードパーティアプリ（例：MyFitnessPal、栄養士アプリ、コーチングアプリ）にデータを読み取ってほしいですか？** → Health Connectと権限の付与が必要です。",
          "**Samsungがデータをクラウドに送ることが心配ですか？** → Samsung Health → 設定 → プライバシーで「Samsung Cloudと同期」を無効にします。データはローカルに保持され、Health Connectへ流れ続けます。",
          "**誰がデータを読んでいるか確認したいですか？** → Health Connect → アプリのアクセス：タイムスタンプ付きの完全なリストを確認できます。",
          "**どちらかをアンインストールしたいですか？** → GalaxyスマートフォンではSamsung Healthはアンインストールできません（プリインストール）が、無効にできます（Watch同期が失われます）。Health ConnectはAndroid 14+にプリインストールされており、Samsung Healthに影響なく無効にできます。",
        ],
        ko: [
          "**상세 차트로 수면을 보거나 Samsung 운동 프로그램을 따르고 싶으신가요?** → Samsung Health。",
          "**타사 앱(예: MyFitnessPal, 영양사 앱, 코칭 앱)이 데이터를 읽기를 원하시나요?** → Health Connect와 권한 부여가 필요합니다.",
          "**Samsung이 데이터를 클라우드로 보내는 것이 걱정되시나요?** → Samsung Health → 설정 → 개인정보 보호에서 'Samsung Cloud와 동기화'를 비활성화하세요. 데이터는 로컬에 유지되고 Health Connect로 계속 흐릅니다.",
          "**누가 데이터를 읽는지 확인하고 싶으신가요?** → Health Connect → 앱 접근성: 타임스탬프와 함께 전체 목록을 확인하세요.",
          "**하나를 제거하고 싶으신가요?** → Galaxy 폰에서는 Samsung Health를 제거할 수 없습니다(사전 설치), 하지만 비활성화할 수 있습니다(Watch 동기화가 손실됩니다). Health Connect는 Android 14+에 사전 설치되어 있으며 Samsung Health에 영향 없이 비활성화할 수 있습니다.",
        ],
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "E se il telefono non è Samsung?",
        en: "What if the phone isn't Samsung?",
        es: "¿Y si el teléfono no es Samsung?",
        de: "Was, wenn das Telefon kein Samsung ist?",
        pt: "E se o telefone não for Samsung?",
        fr: "Et si le téléphone n'est pas Samsung ?",
        pl: "A co jeśli telefon nie jest Samsungiem?",
        tr: "Telefon Samsung değilse ne olur?",
        nl: "Wat als de telefoon geen Samsung is?",
        ja: "スマートフォンがSamsungでない場合は？",
        ko: "폰이 Samsung이 아니면 어떻게 되나요?",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Funziona comunque. Samsung Health è disponibile gratis sul Play Store anche su Pixel, OnePlus, Xiaomi. Il Galaxy Watch si accoppia via Galaxy Wearable (anch'esso multi-brand) e Samsung Health prende il sopravvento per leggere i dati. La sincronizzazione con Health Connect funziona uguale.",
        en: "Still works. Samsung Health is free on the Play Store also for Pixel, OnePlus, Xiaomi. The Galaxy Watch pairs via Galaxy Wearable (also multi-brand) and Samsung Health takes over to read data. Health Connect sync works the same way.",
        es: "Funciona igual. Samsung Health está disponible gratis en Play Store también para Pixel, OnePlus, Xiaomi. El Galaxy Watch se vincula a través de Galaxy Wearable (también compatible con múltiples marcas) y Samsung Health toma el control para leer los datos. La sincronización con Health Connect funciona exactamente igual.",
        de: "Funktioniert trotzdem. Samsung Health ist kostenlos im Play Store auch für Pixel, OnePlus und Xiaomi verfügbar. Die Galaxy Watch wird über Galaxy Wearable (ebenfalls multi-brand) gekoppelt, und Samsung Health übernimmt das Lesen der Daten. Die Synchronisierung mit Health Connect funktioniert genauso.",
        pt: "Funciona mesmo assim. O Samsung Health está disponível gratuitamente no Play Store também para Pixel, OnePlus e Xiaomi. O Galaxy Watch se emparelha via Galaxy Wearable (também multi-marca) e o Samsung Health assume a leitura dos dados. A sincronização com o Health Connect funciona da mesma forma.",
        fr: "Cela fonctionne quand même. Samsung Health est disponible gratuitement sur le Play Store pour Pixel, OnePlus et Xiaomi également. La Galaxy Watch se connecte via Galaxy Wearable (également multi-marque) et Samsung Health prend en charge la lecture des données. La synchronisation avec Health Connect fonctionne de la même manière.",
        pl: "Nadal działa. Samsung Health jest dostępny bezpłatnie w Play Store również na Pixel, OnePlus, Xiaomi. Galaxy Watch paruje się przez Galaxy Wearable (też multi-brand) i Samsung Health przejmuje odczyt danych. Synchronizacja z Health Connect działa tak samo.",
        tr: "Yine de çalışıyor. Samsung Health, Pixel, OnePlus, Xiaomi için de Play Store'da ücretsiz. Galaxy Watch, Galaxy Wearable (o da çok markalı) üzerinden eşleniyor ve Samsung Health veri okumayı devraliyor. Health Connect senkronizasyonu aynı şekilde çalışıyor.",
        nl: "Werkt nog steeds. Samsung Health is gratis in de Play Store ook voor Pixel, OnePlus, Xiaomi. De Galaxy Watch koppelt via Galaxy Wearable (ook multi-merk) en Samsung Health neemt het lezen van gegevens over. Health Connect-synchronisatie werkt op dezelfde manier.",
        ja: "それでも動作します。Samsung HealthはPixel、OnePlus、XiaomiでもPlay Storeで無料です。Galaxy WatchはGalaxy Wearable（こちらもマルチブランド）経由でペアリングし、Samsung Healthがデータ読み取りを引き継ぎます。Health Connectの同期は同じように機能します。",
        ko: "여전히 작동합니다. Samsung Health는 Pixel, OnePlus, Xiaomi에서도 Play Store에서 무료입니다. Galaxy Watch는 Galaxy Wearable(역시 멀티 브랜드)을 통해 페어링하고 Samsung Health가 데이터 읽기를 인계받습니다. Health Connect 동기화는 동일하게 작동합니다.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "In sintesi",
        en: "In summary",
        es: "En resumen",
        de: "Zusammenfassung",
        pt: "Em resumo",
        fr: "En résumé",
        pl: "Podsumowanie",
        tr: "Özet",
        nl: "Samenvatting",
        ja: "まとめ",
        ko: "요약",
      },
    },
    {
      type: "list",
      items: {
        it: [
          "Samsung Health raccoglie i dati dal Galaxy Watch via Bluetooth e li gestisce: disabilitarla rompe il sync del Watch.",
          "Health Connect è il layer di permessi Android tra app salute: disabilitarla impedisce alle app terze di leggere i dati, ma Samsung Health continua a funzionare.",
          "Il flusso dati reale è: Watch → Samsung Health → Health Connect → app terze (FitMesh Sync, MyFitnessPal, ecc.).",
          "Per bloccare il cloud Samsung senza rompere nulla: Samsung Health → Impostazioni → Privacy → disabilita 'Sincronizza con Samsung Cloud'. I dati restano locali e continuano a fluire verso Health Connect.",
          "Per vedere chi legge i tuoi dati: Health Connect → Accesso alle app → lista completa con timestamp.",
        ],
        en: [
          "Samsung Health collects data from the Galaxy Watch via Bluetooth and manages it: disabling it breaks Watch sync.",
          "Health Connect is the Android permissions layer between health apps: disabling it stops third-party apps from reading data, but Samsung Health keeps working.",
          "The real data flow is: Watch → Samsung Health → Health Connect → third-party apps (FitMesh Sync, MyFitnessPal, etc.).",
          "To block Samsung cloud without breaking anything: Samsung Health → Settings → Privacy → disable 'Sync with Samsung Cloud'. Data stays local and keeps flowing to Health Connect.",
          "To see who reads your data: Health Connect → App access → full list with timestamps.",
        ],
        es: [
          "Samsung Health recopila los datos del Galaxy Watch por Bluetooth y los gestiona: desactivarla rompe la sincronización del Watch.",
          "Health Connect es la capa de permisos de Android entre apps de salud: desactivarla impide que las apps de terceros lean los datos, pero Samsung Health sigue funcionando.",
          "El flujo de datos real es: Watch → Samsung Health → Health Connect → apps de terceros (FitMesh Sync, MyFitnessPal, etc.).",
          "Para bloquear la nube de Samsung sin romper nada: Samsung Health → Ajustes → Privacidad → desactiva 'Sincronizar con Samsung Cloud'. Los datos quedan locales y siguen fluyendo hacia Health Connect.",
          "Para ver quién lee tus datos: Health Connect → Acceso de apps → lista completa con marcas de tiempo.",
        ],
        de: [
          "Samsung Health empfängt Daten vom Galaxy Watch per Bluetooth und verwaltet sie: Deaktivieren bricht die Watch-Synchronisierung.",
          "Health Connect ist die Android-Berechtigungsschicht zwischen Gesundheits-Apps: Deaktivieren verhindert, dass Drittanbieter-Apps Daten lesen, aber Samsung Health funktioniert weiterhin.",
          "Der tatsächliche Datenfluss ist: Watch → Samsung Health → Health Connect → Drittanbieter-Apps (FitMesh Sync, MyFitnessPal usw.).",
          "Um die Samsung-Cloud zu blockieren, ohne etwas zu beschädigen: Samsung Health → Einstellungen → Datenschutz → 'Mit Samsung Cloud synchronisieren' deaktivieren. Die Daten bleiben lokal und fließen weiterhin zu Health Connect.",
          "Um zu sehen, wer deine Daten liest: Health Connect → App-Zugriff → vollständige Liste mit Zeitstempeln.",
        ],
        pt: [
          "O Samsung Health coleta dados do Galaxy Watch via Bluetooth e os gerencia: desativá-lo quebra a sincronização do Watch.",
          "O Health Connect é a camada de permissões do Android entre apps de saúde: desativá-lo impede que apps de terceiros leiam os dados, mas o Samsung Health continua funcionando.",
          "O fluxo de dados real é: Watch → Samsung Health → Health Connect → apps de terceiros (FitMesh Sync, MyFitnessPal, etc.).",
          "Para bloquear a nuvem da Samsung sem quebrar nada: Samsung Health → Configurações → Privacidade → desative 'Sincronizar com Samsung Cloud'. Os dados ficam locais e continuam fluindo para o Health Connect.",
          "Para ver quem lê seus dados: Health Connect → Acesso de apps → lista completa com timestamps.",
        ],
        fr: [
          "Samsung Health collecte les données du Galaxy Watch via Bluetooth et les gère : le désactiver interrompt la synchronisation de la montre.",
          "Health Connect est la couche de permissions Android entre les applications de santé : le désactiver empêche les applications tierces de lire les données, mais Samsung Health continue de fonctionner.",
          "Le flux de données réel est : Watch → Samsung Health → Health Connect → applications tierces (FitMesh Sync, MyFitnessPal, etc.).",
          "Pour bloquer le cloud Samsung sans rien casser : Samsung Health → Paramètres → Confidentialité → désactiver 'Synchroniser avec Samsung Cloud'. Les données restent locales et continuent de transiter vers Health Connect.",
          "Pour voir qui lit vos données : Health Connect → Accès des applications → liste complète avec horodatages.",
        ],
        pl: [
          "Samsung Health zbiera dane z Galaxy Watch przez Bluetooth i nimi zarządza: wyłączenie jej zrywa synchronizację zegarka.",
          "Health Connect to warstwa uprawnień Androida między aplikacjami zdrowotnymi: wyłączenie jej uniemożliwia aplikacjom trzecim odczyt danych, ale Samsung Health nadal działa.",
          "Rzeczywisty przepływ danych to: Watch → Samsung Health → Health Connect → aplikacje trzecie (FitMesh Sync, MyFitnessPal itp.).",
          "Aby zablokować chmurę Samsung bez zrywania czegokolwiek: Samsung Health → Ustawienia → Prywatność → wyłącz 'Synchronizuj z Samsung Cloud'. Dane pozostają lokalnie i nadal przepływają do Health Connect.",
          "Aby zobaczyć, kto odczytuje Twoje dane: Health Connect → Dostęp aplikacji → pełna lista z datami.",
        ],
        tr: [
          "Samsung Health, Galaxy Watch'tan Bluetooth üzerinden veri topluyor ve yönetiyor: devre dışı bırakmak Watch senkronizasyonunu kesiyor.",
          "Health Connect, sağlık uygulamaları arasındaki Android izin katmanıdır: devre dışı bırakmak üçüncü taraf uygulamaların veri okumasını engelliyor, ancak Samsung Health çalışmaya devam ediyor.",
          "Gerçek veri akışı: Watch → Samsung Health → Health Connect → üçüncü taraf uygulamalar (FitMesh Sync, MyFitnessPal vb.).",
          "Samsung bulutunu hiçbir şeyi bozmadan engellemek için: Samsung Health → Ayarlar → Gizlilik → 'Samsung Cloud ile senkronize et'i devre dışı bırak. Veriler yerel kalır ve Health Connect'e akmaya devam eder.",
          "Verilerinizi kimin okuduğunu görmek için: Health Connect → Uygulama erişimi → zaman damgalarıyla tam liste.",
        ],
        nl: [
          "Samsung Health verzamelt gegevens van de Galaxy Watch via Bluetooth en beheert deze: uitschakelen verbreekt de Watch-synchronisatie.",
          "Health Connect is de Android-machtigingenlaag tussen gezondheidsapps: uitschakelen voorkomt dat apps van derden gegevens lezen, maar Samsung Health blijft werken.",
          "De werkelijke gegevensstroom is: Watch → Samsung Health → Health Connect → apps van derden (FitMesh Sync, MyFitnessPal, etc.).",
          "Om de Samsung-cloud te blokkeren zonder iets te breken: Samsung Health → Instellingen → Privacy → 'Synchroniseren met Samsung Cloud' uitschakelen. Gegevens blijven lokaal en blijven naar Health Connect stromen.",
          "Om te zien wie je gegevens leest: Health Connect → App-toegang → volledige lijst met tijdstempels.",
        ],
        ja: [
          "Samsung HealthはBluetooth経由でGalaxy Watchからデータを収集・管理します：無効にするとWatchの同期が壊れます。",
          "Health Connectはヘルスアプリ間のAndroid権限レイヤーです：無効にするとサードパーティアプリがデータを読めなくなりますが、Samsung Healthは引き続き動作します。",
          "実際のデータフローは：Watch → Samsung Health → Health Connect → サードパーティアプリ（FitMesh Sync、MyFitnessPalなど）。",
          "何も壊さずにSamsungクラウドをブロックするには：Samsung Health → 設定 → プライバシー → 「Samsung Cloudと同期」を無効にします。データはローカルに保持され、Health Connectへ流れ続けます。",
          "誰がデータを読んでいるかを確認するには：Health Connect → アプリのアクセス → タイムスタンプ付きの完全なリスト。",
        ],
        ko: [
          "Samsung Health는 Bluetooth를 통해 Galaxy Watch에서 데이터를 수집하고 관리합니다: 비활성화하면 Watch 동기화가 끊깁니다.",
          "Health Connect는 건강 앱 간의 Android 권한 레이어입니다: 비활성화하면 타사 앱이 데이터를 읽지 못하지만 Samsung Health는 계속 작동합니다.",
          "실제 데이터 흐름은: Watch → Samsung Health → Health Connect → 타사 앱(FitMesh Sync, MyFitnessPal 등).",
          "아무것도 망가뜨리지 않고 Samsung 클라우드를 차단하려면: Samsung Health → 설정 → 개인정보 보호 → 'Samsung Cloud와 동기화' 비활성화. 데이터는 로컬에 유지되고 Health Connect로 계속 흐릅니다.",
          "누가 데이터를 읽는지 확인하려면: Health Connect → 앱 접근 → 타임스탬프가 있는 전체 목록.",
        ],
      },
    },
    {
      type: "cta",
      title: {
        it: "Vuoi una dashboard alternativa che legga da Health Connect?",
        en: "Want an alternative dashboard reading from Health Connect?",
        es: "¿Quieres un panel alternativo que lea desde Health Connect?",
        de: "Möchtest du ein alternatives Dashboard, das von Health Connect liest?",
        pt: "Quer um painel alternativo que leia do Health Connect?",
        fr: "Vous souhaitez un tableau de bord alternatif lisant depuis Health Connect ?",
        pl: "Chcesz alternatywny panel odczytujący z Health Connect?",
        tr: "Health Connect'ten okuyan alternatif bir panel ister misiniz?",
        nl: "Wil je een alternatief dashboard dat leest van Health Connect?",
        ja: "Health Connectからデータを読む代替ダッシュボードが欲しいですか？",
        ko: "Health Connect에서 읽는 대안 대시보드를 원하시나요?",
      },
      body: {
        it: "FitMesh Sync legge i dati Galaxy Watch via Health Connect e li mostra su una dashboard web pulita. Privacy-first, no ads, no tracker.",
        en: "FitMesh Sync reads Galaxy Watch data via Health Connect and shows it on a clean web dashboard. Privacy-first, no ads, no trackers.",
        es: "FitMesh Sync lee los datos del Galaxy Watch a través de Health Connect y los muestra en un panel web limpio. Privacidad ante todo, sin anuncios, sin rastreadores.",
        de: "FitMesh Sync liest Galaxy Watch-Daten über Health Connect und zeigt sie in einem übersichtlichen Web-Dashboard. Datenschutz an erster Stelle, keine Werbung, keine Tracker.",
        pt: "FitMesh Sync lê os dados do Galaxy Watch via Health Connect e os exibe em um painel web limpo. Privacidade em primeiro lugar, sem anúncios, sem rastreadores.",
        fr: "FitMesh Sync lit les données du Galaxy Watch via Health Connect et les affiche dans un tableau de bord web épuré. La confidentialité d'abord, sans publicités, sans traceurs.",
        pl: "FitMesh Sync odczytuje dane Galaxy Watch przez Health Connect i wyświetla je na przejrzystym panelu webowym. Prywatność na pierwszym miejscu, bez reklam, bez trackerów.",
        tr: "FitMesh Sync, Galaxy Watch verilerini Health Connect üzerinden okuyarak temiz bir web panosunda gösteriyor. Gizlilik önce, reklam yok, izleyici yok.",
        nl: "FitMesh Sync leest Galaxy Watch-gegevens via Health Connect en toont ze op een overzichtelijk webdashboard. Privacy voorop, geen advertenties, geen trackers.",
        ja: "FitMesh SyncはHealth Connect経由でGalaxy Watchのデータを読み取り、すっきりしたWebダッシュボードに表示します。プライバシー最優先、広告なし、トラッカーなし。",
        ko: "FitMesh Sync는 Health Connect를 통해 Galaxy Watch 데이터를 읽어 깔끔한 웹 대시보드에 표시합니다. 개인정보 보호 우선, 광고 없음, 트래커 없음.",
      },
      ctaLabel: {
        it: "Vedi Galaxy Watch su FitMesh →",
        en: "See Galaxy Watch on FitMesh →",
        es: "Ver Galaxy Watch en FitMesh →",
        de: "Galaxy Watch auf FitMesh ansehen →",
        pt: "Ver Galaxy Watch no FitMesh →",
        fr: "Voir Galaxy Watch sur FitMesh →",
        pl: "Zobacz Galaxy Watch na FitMesh →",
        tr: "FitMesh'te Galaxy Watch'ı gör →",
        nl: "Zie Galaxy Watch op FitMesh →",
        ja: "FitMeshでGalaxy Watchを見る →",
        ko: "FitMesh에서 Galaxy Watch 보기 →",
      },
      ctaHref: { it: "/it/sync/galaxy-watch", en: "/en/sync/galaxy-watch" },
    },
  ],
  faq: [
    {
      q: {
        it: "Posso usare Health Connect senza Samsung Health?",
        en: "Can I use Health Connect without Samsung Health?",
        es: "¿Puedo usar Health Connect sin Samsung Health?",
        de: "Kann ich Health Connect ohne Samsung Health verwenden?",
        pt: "Posso usar o Health Connect sem o Samsung Health?",
        fr: "Puis-je utiliser Health Connect sans Samsung Health ?",
        pl: "Czy mogę używać Health Connect bez Samsung Health?",
        tr: "Samsung Health olmadan Health Connect kullanabilir miyim?",
        nl: "Kan ik Health Connect gebruiken zonder Samsung Health?",
        ja: "Samsung HealthなしでHealth Connectを使えますか？",
        ko: "Samsung Health 없이 Health Connect를 사용할 수 있나요?",
      },
      a: {
        it: "Su un Galaxy Watch no: Samsung Health è il bridge ufficiale tra il Watch e il telefono. Senza Samsung Health il Watch non sincronizza. Su un altro wearable (Pixel Watch, Mi Band, Garmin, Polar, etc.) puoi usare la rispettiva app companion + Health Connect e ignorare completamente Samsung Health.",
        en: "On a Galaxy Watch no: Samsung Health is the official bridge between Watch and phone. Without it the Watch won't sync. On other wearables (Pixel Watch, Mi Band, Garmin, Polar, etc.) you can use the respective companion app + Health Connect and ignore Samsung Health entirely.",
        es: "En un Galaxy Watch no: Samsung Health es el puente oficial entre el Watch y el teléfono. Sin ella, el Watch no sincroniza. Con otros wearables (Pixel Watch, Mi Band, Garmin, Polar, etc.) puedes usar la app compañera correspondiente junto con Health Connect e ignorar Samsung Health por completo.",
        de: "Auf einer Galaxy Watch nein: Samsung Health ist die offizielle Verbindung zwischen Watch und Telefon. Ohne sie synchronisiert die Watch nicht. Bei anderen Wearables (Pixel Watch, Mi Band, Garmin, Polar usw.) kannst du die jeweilige Begleit-App zusammen mit Health Connect verwenden und Samsung Health vollständig ignorieren.",
        pt: "No Galaxy Watch, não: o Samsung Health é a ponte oficial entre o Watch e o telefone. Sem ele, o Watch não sincroniza. Em outros wearables (Pixel Watch, Mi Band, Garmin, Polar, etc.) você pode usar o respectivo app companion junto com o Health Connect e ignorar completamente o Samsung Health.",
        fr: "Sur une Galaxy Watch, non : Samsung Health est le pont officiel entre la montre et le téléphone. Sans lui, la montre ne se synchronise pas. Sur d'autres wearables (Pixel Watch, Mi Band, Garmin, Polar, etc.), vous pouvez utiliser l'application compagnon respective avec Health Connect et ignorer complètement Samsung Health.",
        pl: "Na Galaxy Watch nie: Samsung Health to oficjalny most między zegarkiem a telefonem. Bez niej zegarek nie synchronizuje się. Na innych urządzeniach wearable (Pixel Watch, Mi Band, Garmin, Polar itp.) możesz używać odpowiedniej aplikacji towarzyszącej + Health Connect i całkowicie ignorować Samsung Health.",
        tr: "Galaxy Watch'ta hayır: Samsung Health, Watch ile telefon arasındaki resmi köprüdür. Onsuz Watch senkronize olmaz. Diğer giyilebilir cihazlarda (Pixel Watch, Mi Band, Garmin, Polar vb.) ilgili companion uygulamasını + Health Connect'i kullanabilir ve Samsung Health'i tamamen görmezden gelebilirsiniz.",
        nl: "Op een Galaxy Watch niet: Samsung Health is de officiële brug tussen Watch en telefoon. Zonder het synchroniseert de Watch niet. Op andere wearables (Pixel Watch, Mi Band, Garmin, Polar, etc.) kun je de bijbehorende companion-app + Health Connect gebruiken en Samsung Health volledig negeren.",
        ja: "Galaxy Watchでは不可：Samsung HealthはWatchとスマートフォンの公式ブリッジです。それなしではWatchが同期しません。他のウェアラブル（Pixel Watch、Mi Band、Garmin、Polarなど）では、それぞれのコンパニオンアプリ + Health Connectを使用してSamsung Healthを完全に無視できます。",
        ko: "Galaxy Watch에서는 불가: Samsung Health는 Watch와 폰 사이의 공식 브리지입니다. 없으면 Watch가 동기화되지 않습니다. 다른 웨어러블(Pixel Watch, Mi Band, Garmin, Polar 등)에서는 해당 컴패니언 앱 + Health Connect를 사용하고 Samsung Health를 완전히 무시할 수 있습니다.",
      },
    },
    {
      q: {
        it: "I dati passano dal cloud Samsung anche se uso solo Health Connect?",
        en: "Do data pass through Samsung cloud even if I only use Health Connect?",
        es: "¿Los datos pasan por la nube de Samsung aunque use solo Health Connect?",
        de: "Fließen die Daten durch die Samsung-Cloud, auch wenn ich nur Health Connect verwende?",
        pt: "Os dados passam pela nuvem da Samsung mesmo se eu usar apenas o Health Connect?",
        fr: "Les données transitent-elles par le cloud Samsung même si j'utilise uniquement Health Connect ?",
        pl: "Czy dane przechodzą przez chmurę Samsung nawet jeśli używam tylko Health Connect?",
        tr: "Yalnızca Health Connect kullansam bile veriler Samsung bulutundan geçiyor mu?",
        nl: "Gaan gegevens via de Samsung-cloud, zelfs als ik alleen Health Connect gebruik?",
        ja: "Health Connectだけ使っていても、データはSamsungクラウドを経由しますか？",
        ko: "Health Connect만 사용해도 데이터가 Samsung 클라우드를 통과하나요?",
      },
      a: {
        it: "Dipende dalle tue impostazioni. Se in Samsung Health hai disabilitato la sincronizzazione con Samsung Account, i dati restano locali sul telefono e poi sono copiati su Health Connect (anch'esso locale). Se invece la sincronizzazione cloud è attiva, i dati sono prima nel cloud Samsung e poi copiati localmente, anche se Health Connect vede solo la copia locale.",
        en: "Depends on your settings. If you disabled sync with Samsung Account in Samsung Health, data stays local on the phone then is copied to Health Connect (also local). If cloud sync is enabled, data is first in the Samsung cloud then copied locally, even though Health Connect only sees the local copy.",
        es: "Depende de tus ajustes. Si en Samsung Health desactivaste la sincronización con Samsung Account, los datos quedan locales en el teléfono y luego se copian en Health Connect (también local). Si la sincronización en la nube está activada, los datos van primero a la nube de Samsung y después se copian localmente, aunque Health Connect solo ve la copia local.",
        de: "Das hängt von deinen Einstellungen ab. Wenn du in Samsung Health die Synchronisierung mit dem Samsung-Konto deaktiviert hast, bleiben die Daten lokal auf dem Telefon und werden dann in Health Connect (ebenfalls lokal) kopiert. Wenn die Cloud-Synchronisierung aktiviert ist, landen die Daten zuerst in der Samsung-Cloud und werden dann lokal kopiert, auch wenn Health Connect nur die lokale Kopie sieht.",
        pt: "Depende das suas configurações. Se você desativou a sincronização com a Samsung Account no Samsung Health, os dados ficam locais no telefone e depois são copiados para o Health Connect (também local). Se a sincronização na nuvem estiver ativa, os dados vão primeiro para a nuvem da Samsung e depois são copiados localmente, mesmo que o Health Connect veja apenas a cópia local.",
        fr: "Cela dépend de vos paramètres. Si vous avez désactivé la synchronisation avec le compte Samsung dans Samsung Health, les données restent locales sur le téléphone puis sont copiées dans Health Connect (également local). Si la synchronisation cloud est activée, les données se trouvent d'abord dans le cloud Samsung puis sont copiées localement, même si Health Connect ne voit que la copie locale.",
        pl: "Zależy od Twoich ustawień. Jeśli w Samsung Health wyłączyłeś synchronizację z kontem Samsung, dane pozostają lokalnie na telefonie i są następnie kopiowane do Health Connect (też lokalnego). Jeśli synchronizacja z chmurą jest włączona, dane trafiają najpierw do chmury Samsung, a potem są kopiowane lokalnie, choć Health Connect widzi tylko lokalną kopię.",
        tr: "Ayarlarınıza bağlı. Samsung Health'te Samsung Hesabı ile senkronizasyonu devre dışı bıraktıysanız, veriler telefonda yerel kalır ve ardından Health Connect'e kopyalanır (o da yerel). Bulut senkronizasyonu etkinse veriler önce Samsung bulutuna gider sonra yerel olarak kopyalanır; Health Connect yalnızca yerel kopyayı görür.",
        nl: "Hangt af van je instellingen. Als je in Samsung Health de synchronisatie met Samsung-account hebt uitgeschakeld, blijven gegevens lokaal op de telefoon en worden ze naar Health Connect gekopieerd (ook lokaal). Als cloudsynchronisatie is ingeschakeld, gaan gegevens eerst naar de Samsung-cloud en worden ze vervolgens lokaal gekopieerd, ook al ziet Health Connect alleen de lokale kopie.",
        ja: "設定によります。Samsung HealthでSamsung Accountとの同期を無効にした場合、データはスマートフォンにローカルに保持され、その後Health Connect（こちらもローカル）にコピーされます。クラウド同期が有効な場合、データはまずSamsungクラウドに送られてからローカルにコピーされますが、Health Connectはローカルコピーのみを参照します。",
        ko: "설정에 따라 다릅니다. Samsung Health에서 Samsung 계정과의 동기화를 비활성화한 경우, 데이터는 폰에 로컬로 유지되고 Health Connect(역시 로컬)에 복사됩니다. 클라우드 동기화가 활성화된 경우, 데이터는 먼저 Samsung 클라우드로 이동한 다음 로컬로 복사되지만 Health Connect는 로컬 복사본만 참조합니다.",
      },
    },
    {
      q: {
        it: "Quando Health Connect non riceve i dati Samsung Health?",
        en: "When does Health Connect not receive Samsung Health data?",
        es: "¿Cuándo Health Connect no recibe los datos de Samsung Health?",
        de: "Wann empfängt Health Connect keine Samsung Health-Daten?",
        pt: "Quando o Health Connect não recebe os dados do Samsung Health?",
        fr: "Quand Health Connect ne reçoit-il pas les données de Samsung Health ?",
        pl: "Kiedy Health Connect nie odbiera danych Samsung Health?",
        tr: "Health Connect Samsung Health verilerini ne zaman almıyor?",
        nl: "Wanneer ontvangt Health Connect geen Samsung Health-gegevens?",
        ja: "Health ConnectがSamsung Healthのデータを受信しないのはいつですか？",
        ko: "Health Connect가 Samsung Health 데이터를 받지 못하는 경우는 언제인가요?",
      },
      a: {
        it: "Tre casi tipici. Uno: Samsung Health → Impostazioni → Health Connect non è stato autorizzato (situazione default su molti device fino al 2024). Due: hai autorizzato solo alcuni tipi di dato. Tre: una versione vecchia di Samsung Health (< 6.20 ca.) non ha la sync HC. Aggiorna e ri-autorizza.",
        en: "Three typical cases. One: Samsung Health → Settings → Health Connect not authorized (default situation on many devices until 2024). Two: only some data types authorized. Three: an old Samsung Health version (< ~6.20) doesn't have HC sync. Update and re-authorize.",
        es: "Tres casos habituales. Primero: Samsung Health → Ajustes → Health Connect no fue autorizado (situación por defecto en muchos dispositivos hasta 2024). Segundo: solo autorizaste algunos tipos de dato. Tercero: una versión antigua de Samsung Health (anterior a la 6.20 aprox.) no tiene sincronización con Health Connect. Actualiza y vuelve a autorizar.",
        de: "Drei typische Fälle. Erstens: Samsung Health → Einstellungen → Health Connect wurde nicht autorisiert (Standard-Situation auf vielen Geräten bis 2024). Zweitens: Nur einige Datentypen wurden autorisiert. Drittens: Eine alte Samsung Health-Version (vor ca. 6.20) hat keine Health Connect-Synchronisierung. Aktualisiere die App und autorisiere erneut.",
        pt: "Três casos típicos. Primeiro: Samsung Health → Configurações → Health Connect não foi autorizado (situação padrão em muitos dispositivos até 2024). Segundo: apenas alguns tipos de dados foram autorizados. Terceiro: uma versão antiga do Samsung Health (anterior à 6.20 aprox.) não tem sincronização com o Health Connect. Atualize e reautorize.",
        fr: "Trois cas typiques. Premier cas : Samsung Health → Paramètres → Health Connect n'a pas été autorisé (situation par défaut sur de nombreux appareils jusqu'en 2024). Deuxième cas : seuls certains types de données ont été autorisés. Troisième cas : une ancienne version de Samsung Health (inférieure à environ 6.20) n'a pas la synchronisation Health Connect. Mettez à jour l'application et autorisez à nouveau.",
        pl: "Trzy typowe przypadki. Pierwszy: Samsung Health → Ustawienia → Health Connect nie został autoryzowany (domyślna sytuacja na wielu urządzeniach do 2024 roku). Drugi: autoryzowano tylko niektóre typy danych. Trzeci: stara wersja Samsung Health (poniżej ok. 6.20) nie ma synchronizacji HC. Zaktualizuj i ponownie autoryzuj.",
        tr: "Üç tipik durum. Birincisi: Samsung Health → Ayarlar → Health Connect yetkilendirilmemiş (2024'e kadar birçok cihazda varsayılan durum). İkincisi: yalnızca bazı veri türleri yetkilendirilmiş. Üçüncüsü: eski bir Samsung Health sürümü (yaklaşık 6.20'den düşük) HC senkronizasyonuna sahip değil. Güncelleyin ve yeniden yetkilendirin.",
        nl: "Drie typische gevallen. Een: Samsung Health → Instellingen → Health Connect niet geautoriseerd (standaardsituatie op veel apparaten tot 2024). Twee: alleen bepaalde gegevenstypen geautoriseerd. Drie: een oude Samsung Health-versie (< ~6.20) heeft geen HC-synchronisatie. Bijwerken en opnieuw autoriseren.",
        ja: "典型的な3つのケース。1つ目：Samsung Health → 設定 → Health Connectが認証されていない（2024年まで多くのデバイスでのデフォルト状態）。2つ目：一部のデータタイプのみ認証されている。3つ目：古いSamsung Healthバージョン（約6.20未満）にはHC同期がない。更新して再認証してください。",
        ko: "세 가지 일반적인 경우. 첫째: Samsung Health → 설정 → Health Connect가 승인되지 않음(2024년까지 많은 기기의 기본 상태). 둘째: 일부 데이터 유형만 승인됨. 셋째: 오래된 Samsung Health 버전(약 6.20 미만)에는 HC 동기화가 없음. 업데이트하고 재승인하세요.",
      },
    },
  ],
  related: [
    "guida-sync-wearable-2026",
    "backup-galaxy-watch-pc",
    "galaxy-watch-ultra2-watch9-health-connect",
  ],
  brandsMentioned: ["Samsung", "Google"],
  ldType: "BlogPosting",
};
