import type { BlogPost } from "../types";

export const post: BlogPost = {
  slug: "hrv-cose-significato-valori",
  category: "guides",
  publishedAt: "2026-05-22",
  updatedAt: "2026-05-22",
  readMinutes: 10,
  tldr: {
    it: [
      "La HRV misura la variazione negli intervalli tra battiti (millisecondi), non la frequenza media: una variabilità alta indica un sistema nervoso autonomo in equilibrio, non un problema cardiaco.",
      "Il valore assoluto conta poco: un atleta di 40 anni può avere 85 ms e un sedentario 35 ms, entrambi normali per chi sono. Il dato utile è il tuo trend personale su 2-4 settimane.",
      "La misura più affidabile è quella notturna, quando il movimento non disturba il sensore PPG.",
      "I valori di Garmin, Oura, Samsung e Polar non sono direttamente comparabili: usano algoritmi diversi. Scegli un dispositivo di riferimento e non mischiare i numeri.",
      "Per migliorare la HRV nel tempo: sonno regolare, attività aerobica moderata, riduzione dell'alcol. Non esistono hack rapidi: i cambiamenti richiedono settimane.",
    ],
    en: [
      "HRV measures variation in beat intervals (milliseconds), not average heart rate: high variability indicates a balanced autonomic nervous system, not a cardiac problem.",
      "The absolute value matters little: a 40-year-old athlete may have 85 ms and a sedentary person 35 ms, both normal for who they are. The useful data is your personal trend over 2-4 weeks.",
      "The most reliable measurement is overnight, when movement doesn't disturb the PPG sensor.",
      "Garmin, Oura, Samsung and Polar values are not directly comparable: they use different algorithms. Pick one reference device and don't mix numbers.",
      "To improve HRV over time: regular sleep, moderate aerobic activity, alcohol reduction. There are no quick hacks: changes take weeks.",
    ],
    es: [
      "La HRV mide la variación en los intervalos entre latidos (milisegundos), no la frecuencia media: una variabilidad alta indica un sistema nervioso autónomo equilibrado, no un problema cardíaco.",
      "El valor absoluto importa poco: un atleta de 40 años puede tener 85 ms y una persona sedentaria 35 ms, ambos normales para quienes son. El dato útil es tu tendencia personal durante 2-4 semanas.",
      "La medición más fiable es la nocturna, cuando el movimiento no interfiere con el sensor PPG.",
      "Los valores de Garmin, Oura, Samsung y Polar no son directamente comparables: usan algoritmos distintos. Elige un dispositivo de referencia y no mezcles los números.",
      "Para mejorar la HRV con el tiempo: sueño regular, actividad aeróbica moderada, reducción del alcohol. No existen atajos rápidos: los cambios requieren semanas.",
    ],
    de: [
      "Die HRV misst die Variation der Intervalle zwischen Herzschlägen (Millisekunden), nicht die durchschnittliche Herzfrequenz: Eine hohe Variabilität zeigt ein ausgeglichenes autonomes Nervensystem an, kein Herzproblem.",
      "Der absolute Wert spielt kaum eine Rolle: Ein 40-jähriger Athlet kann 85 ms haben, eine inaktive Person 35 ms, und beide sind normal für ihre jeweilige Situation. Das nützliche Datum ist dein persönlicher Trend über 2-4 Wochen.",
      "Die zuverlässigste Messung ist die nächtliche, wenn Bewegung den PPG-Sensor nicht stört.",
      "Die Werte von Garmin, Oura, Samsung und Polar sind nicht direkt vergleichbar: Sie verwenden unterschiedliche Algorithmen. Wähle ein Referenzgerät und vermische die Zahlen nicht.",
      "Um die HRV langfristig zu verbessern: regelmäßiger Schlaf, moderate aerobe Aktivität, Alkoholreduktion. Es gibt keine schnellen Abkürzungen: Veränderungen brauchen Wochen.",
    ],
    pt: [
      "A HRV mede a variação nos intervalos entre batimentos (milissegundos), não a frequência cardíaca média: uma alta variabilidade indica um sistema nervoso autônomo equilibrado, não um problema cardíaco.",
      "O valor absoluto importa pouco: um atleta de 40 anos pode ter 85 ms e uma pessoa sedentária 35 ms, ambos normais para quem são. O dado útil é a sua tendência pessoal ao longo de 2-4 semanas.",
      "A medição mais confiável é a noturna, quando o movimento não perturba o sensor PPG.",
      "Os valores de Garmin, Oura, Samsung e Polar não são diretamente comparáveis: usam algoritmos diferentes. Escolha um dispositivo de referência e não misture os números.",
      "Para melhorar a HRV ao longo do tempo: sono regular, atividade aeróbica moderada, redução do álcool. Não existem atalhos rápidos: as mudanças levam semanas.",
    ],
    fr: [
      "La HRV mesure la variation des intervalles entre les battements (millisecondes), pas la fréquence cardiaque moyenne: une variabilité élevée indique un système nerveux autonome équilibré, pas un problème cardiaque.",
      "La valeur absolue compte peu: un athlète de 40 ans peut avoir 85 ms et une personne sédentaire 35 ms, tous deux normaux pour ce qu'ils sont. La donnée utile est votre tendance personnelle sur 2-4 semaines.",
      "La mesure la plus fiable est celle de la nuit, quand les mouvements ne perturbent pas le capteur PPG.",
      "Les valeurs de Garmin, Oura, Samsung et Polar ne sont pas directement comparables: ils utilisent des algorithmes différents. Choisissez un appareil de référence et ne mélangez pas les chiffres.",
      "Pour améliorer la HRV dans le temps: sommeil régulier, activité aérobique modérée, réduction de l'alcool. Il n'existe pas de raccourcis rapides: les changements demandent des semaines.",
    ],
  },
  primaryKeyword: {
    it: "cos'è la HRV",
    en: "what is HRV",
    es: "qué es la HRV",
    de: "was ist HRV",
    pt: "o que é HRV",
    fr: "qu'est-ce que la HRV",
  },
  secondaryKeywords: {
    it: [
      "HRV valori normali",
      "variabilità frequenza cardiaca",
      "HRV significato sport",
      "HRV bassa cosa significa",
      "HRV smartwatch",
    ],
    en: [
      "HRV normal values",
      "heart rate variability",
      "HRV meaning sport",
      "low HRV what it means",
      "HRV smartwatch",
    ],
  },
  metaDescription: {
    it: "Cos'è la HRV (variabilità della frequenza cardiaca), come si misurano i valori normali per età, cosa significa quando è alta o bassa, e come leggerla sul tuo wearable nel 2026.",
    en: "What is HRV (heart rate variability), how normal values are measured by age, what it means when it's high or low, and how to read it on your wearable in 2026.",
    es: "Qué es la HRV (variabilidad de la frecuencia cardíaca), cómo se miden los valores normales por edad, qué significa cuando es alta o baja, y cómo leerla en tu wearable en 2026.",
    de: "Was ist HRV (Herzfrequenzvariabilität), wie werden Normalwerte nach Alter gemessen, was bedeutet es, wenn sie hoch oder niedrig ist, und wie liest du sie auf deinem Wearable im Jahr 2026.",
    pt: "O que é HRV (variabilidade da frequência cardíaca), como os valores normais são medidos por idade, o que significa quando é alta ou baixa, e como lê-la no seu wearable em 2026.",
    fr: "Qu'est-ce que la HRV (variabilité de la fréquence cardiaque), comment les valeurs normales sont mesurées par âge, ce que cela signifie quand elle est haute ou basse, et comment la lire sur votre appareil connecté en 2026.",
  },
  hero: {
    kicker: { it: "Guida", en: "Guide", es: "Guía", de: "Ratgeber", pt: "Guia", fr: "Guide" },
    title: {
      it: "Cos'è la HRV: significato e valori normali",
      en: "What is HRV: meaning, normal values and how to read it",
      es: "Qué es la HRV: significado, valores normales y cómo interpretarla",
      de: "Was ist HRV: Bedeutung, Normalwerte und wie man sie richtig liest",
      pt: "O que é HRV: significado, valores normais e como interpretá-la",
      fr: "Qu'est-ce que la HRV: signification, valeurs normales et comment l'interpréter",
    },
    subtitle: {
      it: "La variabilità della frequenza cardiaca (HRV) è una delle metriche più fraintese negli smartwatch. Non misura quanto batte il cuore, ma quanto irregolarmente: e quella irregolarità è in realtà un segnale di salute. Ecco cosa significa davvero, come si interpretano i valori, e perché il confronto con gli altri è quasi sempre inutile.",
      en: "Heart rate variability (HRV) is one of the most misunderstood metrics in smartwatches. It doesn't measure how fast the heart beats, but how irregularly: and that irregularity is actually a health signal. Here's what it really means, how to interpret values, and why comparing yourself to others is almost always useless.",
      es: "La variabilidad de la frecuencia cardíaca (HRV) es una de las métricas más malinterpretadas en los smartwatches. No mide la rapidez con la que late el corazón, sino la irregularidad de ese ritmo: y esa irregularidad es en realidad una señal de bienestar. Aquí te explicamos qué significa de verdad, cómo interpretar los valores y por qué compararte con otros es casi siempre inútil.",
      de: "Die Herzfrequenzvariabilität (HRV) ist eine der am häufigsten missverstandenen Metriken bei Smartwatches. Sie misst nicht, wie schnell das Herz schlägt, sondern wie unregelmäßig: und diese Unregelmäßigkeit ist tatsächlich ein Gesundheitssignal. Hier erfährst du, was sie wirklich bedeutet, wie du die Werte interpretierst und warum der Vergleich mit anderen fast immer sinnlos ist.",
      pt: "A variabilidade da frequência cardíaca (HRV) é uma das métricas mais mal compreendidas nos smartwatches. Ela não mede a rapidez com que o coração bate, mas a irregularidade desse ritmo: e essa irregularidade é, na verdade, um sinal de bem-estar. Veja o que ela realmente significa, como interpretar os valores e por que se comparar com outras pessoas é quase sempre inútil.",
      fr: "La variabilité de la fréquence cardiaque (HRV) est l'une des métriques les plus mal comprises dans les montres connectées. Elle ne mesure pas la vitesse à laquelle le coeur bat, mais l'irrégularité de ce rythme: et cette irrégularité est en réalité un signal de bien-être. Voici ce qu'elle signifie vraiment, comment interpréter les valeurs et pourquoi se comparer aux autres est presque toujours inutile.",
    },
  },
  body: [
    {
      type: "paragraph",
      text: {
        it: "La HRV (variabilità della frequenza cardiaca) non misura quanto batte il cuore, ma quanto irregolarmente: e quella irregolarità nei millisecondi tra un battito e l'altro è un segnale diretto dello stato del sistema nervoso autonomo. Il confronto del tuo valore con quello di altri è quasi sempre inutile: conta il tuo trend personale nel tempo, non il numero assoluto.",
        en: "HRV (heart rate variability) doesn't measure how fast the heart beats, but how irregularly: and that millisecond-level irregularity between beats is a direct signal of autonomic nervous system state. Comparing your value to others is almost always useless: what matters is your personal trend over time, not the absolute number.",
        es: "La HRV (variabilidad de la frecuencia cardíaca) no mide la rapidez con la que late el corazón, sino la irregularidad de ese ritmo: y esa irregularidad en los milisegundos entre un latido y el siguiente es una señal directa del estado del sistema nervioso autónomo. Comparar tu valor con el de otras personas es casi siempre inútil: lo que importa es tu tendencia personal en el tiempo, no el número absoluto.",
        de: "Die HRV (Herzfrequenzvariabilität) misst nicht, wie schnell das Herz schlägt, sondern wie unregelmäßig: und diese Unregelmäßigkeit auf Millisekundenebene zwischen den Schlägen ist ein direktes Signal des Zustands des autonomen Nervensystems. Den eigenen Wert mit anderen zu vergleichen ist fast immer sinnlos: Was zählt, ist dein persönlicher Trend im Laufe der Zeit, nicht die absolute Zahl.",
        pt: "A HRV (variabilidade da frequência cardíaca) não mede a rapidez com que o coração bate, mas a irregularidade desse ritmo: e essa irregularidade em milissegundos entre um batimento e outro é um sinal direto do estado do sistema nervoso autônomo. Comparar seu valor com o de outras pessoas é quase sempre inútil: o que importa é a sua tendência pessoal ao longo do tempo, não o número absoluto.",
        fr: "La HRV (variabilité de la fréquence cardiaque) ne mesure pas la vitesse à laquelle le coeur bat, mais l'irrégularité de ce rythme: et cette irrégularité en millisecondes entre les battements est un signal direct de l'état du système nerveux autonome. Comparer votre valeur à celle des autres est presque toujours inutile: ce qui compte, c'est votre tendance personnelle dans le temps, pas le chiffre absolu.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Cos'è la HRV: la definizione semplice",
        en: "What is HRV: the simple definition",
        es: "Qué es la HRV: la definición sencilla",
        de: "Was ist HRV: die einfache Definition",
        pt: "O que é HRV: a definição simples",
        fr: "Qu'est-ce que la HRV: la définition simple",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Il cuore non batte come un metronomo perfetto. Anche se la tua frequenza cardiaca è di 60 BPM, i singoli battiti non avvengono esattamente ogni secondo: uno arriva dopo 980 ms, il successivo dopo 1.020 ms, quello dopo ancora dopo 990 ms. Questa variazione negli intervalli tra un battito e l'altro si chiama variabilità della frequenza cardiaca (HRV, dall'inglese Heart Rate Variability).",
        en: "The heart doesn't beat like a perfect metronome. Even if your heart rate is 60 BPM, individual beats don't happen exactly every second: one arrives after 980 ms, the next after 1,020 ms, the one after that after 990 ms. This variation in intervals between beats is called heart rate variability (HRV).",
        es: "El corazón no late como un metrónomo perfecto. Aunque tu frecuencia cardíaca sea de 60 BPM, los latidos individuales no ocurren exactamente cada segundo: uno llega después de 980 ms, el siguiente después de 1.020 ms, el que viene después de 990 ms. Esta variación en los intervalos entre latidos se llama variabilidad de la frecuencia cardíaca (HRV, del inglés Heart Rate Variability).",
        de: "Das Herz schlägt nicht wie ein perfektes Metronom. Auch wenn deine Herzfrequenz 60 BPM beträgt, erfolgen die einzelnen Schläge nicht exakt jede Sekunde: einer kommt nach 980 ms, der nächste nach 1.020 ms, der darauffolgende nach 990 ms. Diese Variation in den Intervallen zwischen den Schlägen nennt sich Herzfrequenzvariabilität (HRV, vom englischen Heart Rate Variability).",
        pt: "O coração não bate como um metrônomo perfeito. Mesmo que sua frequência cardíaca seja de 60 BPM, os batimentos individuais não ocorrem exatamente a cada segundo: um chega após 980 ms, o próximo após 1.020 ms, o seguinte após 990 ms. Essa variação nos intervalos entre os batimentos é chamada de variabilidade da frequência cardíaca (HRV, do inglês Heart Rate Variability).",
        fr: "Le coeur ne bat pas comme un métronome parfait. Même si votre fréquence cardiaque est de 60 BPM, les battements individuels ne se produisent pas exactement chaque seconde: l'un arrive après 980 ms, le suivant après 1.020 ms, celui d'après après 990 ms. Cette variation dans les intervalles entre les battements s'appelle variabilité de la fréquence cardiaque (HRV, de l'anglais Heart Rate Variability).",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Più questa variazione è ampia (cioè più i battiti sono 'irregolari' nell'intervallo), più alta è la tua HRV. Questo sembra controintuitivo perché di solito l'irregolarità cardiaca è associata a problemi. Ma qui si tratta di variazioni fisiologiche nell'ordine dei millisecondi, non di aritmie patologiche. Una HRV alta è generalmente un segnale che il sistema nervoso autonomo funziona bene e il corpo è in buono stato di recupero.",
        en: "The wider this variation (meaning the more 'irregular' the beats are in interval), the higher your HRV. This seems counterintuitive because cardiac irregularity is usually associated with problems. But here we're talking about physiological variations in the order of milliseconds, not pathological arrhythmias. A high HRV is generally a signal that the autonomic nervous system is working well and the body is in a good state of recovery.",
        es: "Cuanto más amplia es esta variación (es decir, cuanto más 'irregulares' son los latidos en cuanto al intervalo), más alta es tu HRV. Esto puede parecer contraintuitivo, ya que la irregularidad cardíaca suele asociarse con problemas. Pero aquí se trata de variaciones fisiológicas en el orden de los milisegundos, no de arritmias patológicas. Una HRV alta es, en general, una señal de que el sistema nervioso autónomo funciona bien y el cuerpo se encuentra en buen estado de recuperación.",
        de: "Je breiter diese Variation ist (also je 'unregelmäßiger' die Schläge im Intervall sind), desto höher ist deine HRV. Das klingt kontraintuitiv, weil Herzunregelmäßigkeiten normalerweise mit Problemen assoziiert werden. Aber hier geht es um physiologische Variationen im Millisekundenbereich, nicht um pathologische Arrhythmien. Eine hohe HRV ist im Allgemeinen ein Signal dafür, dass das autonome Nervensystem gut funktioniert und der Körper in einem guten Erholungszustand ist.",
        pt: "Quanto mais ampla é essa variação (ou seja, quanto mais 'irregulares' são os batimentos no intervalo), maior é a sua HRV. Isso parece contraintuitivo porque a irregularidade cardíaca é geralmente associada a problemas. Mas aqui estamos falando de variações fisiológicas na ordem dos milissegundos, não de arritmias patológicas. Uma HRV alta é geralmente um sinal de que o sistema nervoso autônomo está funcionando bem e o corpo está em bom estado de recuperação.",
        fr: "Plus cette variation est large (c'est-à-dire plus les battements sont 'irréguliers' dans l'intervalle), plus votre HRV est élevée. Cela semble contre-intuitif car l'irrégularité cardiaque est habituellement associée à des problèmes. Mais ici, il s'agit de variations physiologiques de l'ordre des millisecondes, pas d'arythmies pathologiques. Une HRV élevée est généralement un signal que le système nerveux autonome fonctionne bien et que le corps est en bon état de récupération.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Perché la HRV riflette il sistema nervoso autonomo",
        en: "Why HRV reflects the autonomic nervous system",
        es: "Por qué la HRV refleja el sistema nervioso autónomo",
        de: "Warum die HRV das autonome Nervensystem widerspiegelt",
        pt: "Por que a HRV reflete o sistema nervoso autônomo",
        fr: "Pourquoi la HRV reflète le système nerveux autonome",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Il sistema nervoso autonomo ha due bracci: il simpatico (attivazione, stress, risposta 'fight or flight') e il parasimpatico (recupero, riposo, risposta 'rest and digest'). Il cuore è influenzato da entrambi costantemente, e quella variazione nei tempi dei battiti è il risultato di questa doppia influenza che si bilancia momento per momento.",
        en: "The autonomic nervous system has two branches: the sympathetic (activation, stress, 'fight or flight' response) and the parasympathetic (recovery, rest, 'rest and digest' response). The heart is influenced by both constantly, and that variation in beat timing is the result of this dual influence balancing moment by moment.",
        es: "El sistema nervioso autónomo tiene dos ramas: la simpática (activación, estrés, respuesta de 'lucha o huida') y la parasimpática (recuperación, descanso, respuesta de 'reposo y digestión'). El corazón está influenciado por ambas de forma constante, y esa variación en los tiempos de los latidos es el resultado de este doble influjo que se equilibra momento a momento.",
        de: "Das autonome Nervensystem hat zwei Äste: den Sympathikus (Aktivierung, Stress, 'Kampf-oder-Flucht'-Reaktion) und den Parasympathikus (Erholung, Ruhe, 'Ruhe-und-Verdauung'-Reaktion). Das Herz wird von beiden ständig beeinflusst, und diese Variation in den Schlagtakten ist das Ergebnis dieses dualen Einflusses, der sich Moment für Moment ausbalanciert.",
        pt: "O sistema nervoso autônomo tem dois ramos: o simpático (ativação, estresse, resposta de 'luta ou fuga') e o parassimpático (recuperação, repouso, resposta de 'descanso e digestão'). O coração é influenciado por ambos constantemente, e essa variação no tempo dos batimentos é o resultado dessa dupla influência se equilibrando a cada momento.",
        fr: "Le système nerveux autonome possède deux branches: le sympathique (activation, stress, réponse 'combat ou fuite') et le parasympathique (récupération, repos, réponse 'repos et digestion'). Le coeur est constamment influencé par les deux, et cette variation dans le rythme des battements est le résultat de cette double influence qui s'équilibre moment par moment.",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Quando sei sotto stress cronico, non hai dormito bene, hai fatto un allenamento intenso ieri sera, o stai iniziando a prendere un'influenza, il sistema simpatico prende il sopravvento: il cuore batte più regolarmente, la variabilità cala. Quando sei riposato, ben recuperato, e il sistema parasimpatico è dominante, la variabilità sale.",
        en: "When you're under chronic stress, haven't slept well, had an intense workout last night, or are starting to get the flu, the sympathetic system takes over: the heart beats more regularly, variability drops. When you're rested, well-recovered, and the parasympathetic system is dominant, variability rises.",
        es: "Cuando estás bajo estrés crónico, no has dormido bien, tuviste un entrenamiento intenso la noche anterior o empiezas a sentirte resfriado, el sistema simpático toma el control: el corazón late con más regularidad y la variabilidad disminuye. Cuando estás descansado, bien recuperado y el sistema parasimpático es dominante, la variabilidad sube.",
        de: "Wenn du unter chronischem Stress stehst, schlecht geschlafen hast, gestern Abend ein intensives Training hattest oder dabei bist, eine Grippe zu bekommen, übernimmt das sympathische System die Kontrolle: Das Herz schlägt regelmäßiger, die Variabilität sinkt. Wenn du ausgeruht, gut erholt bist und das parasympathische System dominiert, steigt die Variabilität.",
        pt: "Quando você está sob estresse crônico, não dormiu bem, teve um treino intenso na noite anterior ou está começando a pegar uma gripe, o sistema simpático assume o controle: o coração bate de forma mais regular, a variabilidade cai. Quando você está descansado, bem recuperado e o sistema parassimpático é dominante, a variabilidade sobe.",
        fr: "Quand vous êtes sous stress chronique, n'avez pas bien dormi, avez eu un entraînement intense la veille, ou commencez à attraper la grippe, le système sympathique prend le dessus: le coeur bat plus régulièrement, la variabilité diminue. Quand vous êtes reposé, bien récupéré et que le système parasympathique est dominant, la variabilité augmente.",
      },
    },
    {
      type: "callout",
      variant: "tip",
      title: {
        it: "La regola pratica",
        en: "The practical rule",
        es: "La regla práctica",
        de: "Die praktische Regel",
        pt: "A regra prática",
        fr: "La règle pratique",
      },
      body: {
        it: "HRV alta = corpo in stato di recupero, sistema parasimpatico attivo, buona riserva per lo stress (fisico e mentale). HRV bassa = corpo in stato di allerta o affaticamento, sistema simpatico attivo, meno riserva disponibile. Né alta né bassa è intrinsecamente 'migliore in assoluto': conta il trend personale nel tempo.",
        en: "High HRV = body in recovery state, parasympathetic system active, good reserve for stress (physical and mental). Low HRV = body in alert or fatigue state, sympathetic system active, less reserve available. Neither high nor low is intrinsically 'better in absolute': what matters is the personal trend over time.",
        es: "HRV alta = cuerpo en estado de recuperación, sistema parasimpático activo, buena reserva para el estrés (físico y mental). HRV baja = cuerpo en estado de alerta o fatiga, sistema simpático activo, menor reserva disponible. Ni alta ni baja es intrínsecamente 'mejor en términos absolutos': lo que importa es la tendencia personal en el tiempo.",
        de: "Hohe HRV = Körper im Erholungszustand, parasympathisches System aktiv, gute Reserve für Stress (physisch und mental). Niedrige HRV = Körper im Alarm- oder Erschöpfungszustand, sympathisches System aktiv, weniger Reserve verfügbar. Weder hoch noch niedrig ist intrinsisch 'besser in absoluten Begriffen': Was zählt, ist der persönliche Trend im Laufe der Zeit.",
        pt: "HRV alta = corpo em estado de recuperação, sistema parassimpático ativo, boa reserva para o estresse (físico e mental). HRV baixa = corpo em estado de alerta ou fadiga, sistema simpático ativo, menos reserva disponível. Nem alta nem baixa é intrinsecamente 'melhor em termos absolutos': o que importa é a tendência pessoal ao longo do tempo.",
        fr: "HRV élevée = corps en état de récupération, système parasympathique actif, bonne réserve pour le stress (physique et mental). HRV basse = corps en état d'alerte ou de fatigue, système sympathique actif, moins de réserve disponible. Ni élevée ni basse n'est intrinsèquement 'meilleure en absolu': ce qui compte, c'est la tendance personnelle dans le temps.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "HRV valori normali: cosa aspettarsi per età e fitness",
        en: "HRV normal values: what to expect by age and fitness",
        es: "Valores normales de HRV: qué esperar según edad y condición física",
        de: "HRV Normalwerte: was nach Alter und Fitness zu erwarten ist",
        pt: "Valores normais de HRV: o que esperar por idade e condicionamento físico",
        fr: "Valeurs normales de HRV: ce que vous pouvez attendre selon l'âge et la forme physique",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "La domanda più comune è: 'Il mio valore è normale?' La risposta onesta è che i range di riferimento per la HRV sono estremamente ampi e dipendono da molte variabili. Un adulto sedentario di 40 anni potrebbe avere un HRV medio di 35 ms; un atleta della stessa età potrebbe avere 80-90 ms. Entrambi sono 'normali' per chi sono.",
        en: "The most common question is: 'Is my value normal?' The honest answer is that HRV reference ranges are extremely wide and depend on many variables. A sedentary 40-year-old adult might have an average HRV of 35 ms; an athlete of the same age might have 80-90 ms. Both are 'normal' for who they are.",
        es: "La pregunta más habitual es: '¿Es normal mi valor?' La respuesta honesta es que los rangos de referencia de la HRV son muy amplios y dependen de muchas variables. Un adulto sedentario de 40 años puede tener una HRV media de 35 ms; un atleta de la misma edad puede tener 80-90 ms. Ambos son 'normales' para quienes son.",
        de: "Die häufigste Frage lautet: 'Ist mein Wert normal?' Die ehrliche Antwort ist, dass die Referenzbereiche für die HRV extrem breit sind und von vielen Variablen abhängen. Ein inaktiver 40-jähriger Erwachsener könnte einen durchschnittlichen HRV von 35 ms haben; ein Athlet desselben Alters könnte 80-90 ms haben. Beide sind 'normal' für das, was sie sind.",
        pt: "A pergunta mais comum é: 'O meu valor é normal?' A resposta honesta é que os intervalos de referência para a HRV são extremamente amplos e dependem de muitas variáveis. Um adulto sedentário de 40 anos pode ter uma HRV média de 35 ms; um atleta da mesma idade pode ter 80-90 ms. Ambos são 'normais' para quem são.",
        fr: "La question la plus fréquente est: 'Ma valeur est-elle normale?' La réponse honnête est que les plages de référence pour la HRV sont extrêmement larges et dépendent de nombreuses variables. Un adulte sédentaire de 40 ans peut avoir une HRV moyenne de 35 ms; un athlète du même âge peut avoir 80-90 ms. Les deux sont 'normaux' pour ce qu'ils sont.",
      },
    },
    {
      type: "table",
      caption: {
        it: "Range HRV orientativi per fascia d'età (RMSSD, misurazione notturna). Fonte: letteratura fisiologica generale. Non usare per diagnosi medica.",
        en: "Indicative HRV ranges by age group (RMSSD, overnight measurement). Source: general physiological literature. Do not use for medical diagnosis.",
        es: "Rangos orientativos de HRV por grupo de edad (RMSSD, medición nocturna). Fuente: literatura fisiológica general. No usar como referencia médica.",
        de: "Orientierungswerte für HRV-Bereiche nach Altersgruppe (RMSSD, nächtliche Messung). Quelle: allgemeine physiologische Literatur. Nicht für medizinische Zwecke verwenden.",
        pt: "Faixas indicativas de HRV por faixa etária (RMSSD, medição noturna). Fonte: literatura fisiológica geral. Não usar para fins de saúde.",
        fr: "Plages indicatives de HRV par groupe d'âge (RMSSD, mesure nocturne). Source: littérature physiologique générale. Ne pas utiliser à des fins médicales.",
      },
      headers: {
        it: ["Fascia d'età", "Range tipico (ms)", "Note"],
        en: ["Age group", "Typical range (ms)", "Notes"],
        es: ["Grupo de edad", "Rango típico (ms)", "Notas"],
        de: ["Altersgruppe", "Typischer Bereich (ms)", "Hinweise"],
        pt: ["Faixa etária", "Faixa típica (ms)", "Observações"],
        fr: ["Groupe d'âge", "Plage typique (ms)", "Notes"],
      },
      rows: [
        {
          it: ["20-29 anni", "55-105 ms", "Alta variabilità fisiologica tra individui"],
          en: ["20-29 years", "55-105 ms", "High physiological variability between individuals"],
          es: ["20-29 años", "55-105 ms", "Alta variabilidad fisiológica entre individuos"],
          de: ["20-29 Jahre", "55-105 ms", "Hohe physiologische Variabilität zwischen Personen"],
          pt: ["20-29 anos", "55-105 ms", "Alta variabilidade fisiológica entre indivíduos"],
          fr: ["20-29 ans", "55-105 ms", "Haute variabilité physiologique entre individus"],
        },
        {
          it: ["30-39 anni", "45-90 ms", "Calo naturale rispetto ai 20 anni"],
          en: ["30-39 years", "45-90 ms", "Natural decline compared to 20s"],
          es: ["30-39 años", "45-90 ms", "Descenso natural respecto a los 20 años"],
          de: ["30-39 Jahre", "45-90 ms", "Natürlicher Rückgang im Vergleich zu den 20ern"],
          pt: ["30-39 anos", "45-90 ms", "Declínio natural em comparação aos 20 anos"],
          fr: ["30-39 ans", "45-90 ms", "Déclin naturel par rapport aux 20 ans"],
        },
        {
          it: ["40-49 anni", "35-75 ms", "Fitness ha impatto maggiore sulla differenza"],
          en: ["40-49 years", "35-75 ms", "Fitness has greater impact on the difference"],
          es: ["40-49 años", "35-75 ms", "La condición física tiene mayor impacto en la diferencia"],
          de: ["40-49 Jahre", "35-75 ms", "Fitness hat größeren Einfluss auf den Unterschied"],
          pt: ["40-49 anos", "35-75 ms", "O condicionamento físico tem maior impacto na diferença"],
          fr: ["40-49 ans", "35-75 ms", "La forme physique a un impact plus grand sur la différence"],
        },
        {
          it: ["50-59 anni", "25-60 ms", "Variabilità tra sedentari e atleti si allarga"],
          en: ["50-59 years", "25-60 ms", "Variability between sedentary and athletes widens"],
          es: ["50-59 años", "25-60 ms", "La diferencia entre sedentarios y atletas se amplía"],
          de: ["50-59 Jahre", "25-60 ms", "Variabilität zwischen Inaktiven und Athleten vergrößert sich"],
          pt: ["50-59 anos", "25-60 ms", "A variabilidade entre sedentários e atletas aumenta"],
          fr: ["50-59 ans", "25-60 ms", "La variabilité entre sédentaires et athlètes s'élargit"],
        },
        {
          it: ["60+ anni", "20-50 ms", "Livelli assoluti più bassi, trend personale ancora valido"],
          en: ["60+ years", "20-50 ms", "Lower absolute levels, personal trend still valid"],
          es: ["60+ años", "20-50 ms", "Niveles absolutos más bajos, la tendencia personal sigue siendo válida"],
          de: ["60+ Jahre", "20-50 ms", "Niedrigere absolute Werte, persönlicher Trend bleibt gültig"],
          pt: ["60+ anos", "20-50 ms", "Níveis absolutos mais baixos, tendência pessoal ainda válida"],
          fr: ["60+ ans", "20-50 ms", "Niveaux absolus plus bas, tendance personnelle toujours valide"],
        },
      ],
    },
    {
      type: "callout",
      variant: "warning",
      title: {
        it: "Il confronto con gli altri è quasi inutile",
        en: "Comparing with others is almost useless",
        es: "Compararte con otros es casi inútil",
        de: "Der Vergleich mit anderen ist fast sinnlos",
        pt: "Comparar-se com os outros é quase inútil",
        fr: "Se comparer aux autres est presque inutile",
      },
      body: {
        it: "Un HRV di 42 ms è ottimo per una persona e mediocre per un'altra. Quello che conta è il **tuo** trend nel tempo: se la tua baseline è 50 ms e un mattino scende a 32, quel calo è significativo per te. Se la tua baseline è 30 ms e sei sempre intorno a quel valore, sei probabilmente in equilibrio. Le app come Garmin e Oura mostrano un 'intervallo normale personale' proprio per questo.",
        en: "An HRV of 42 ms is excellent for one person and mediocre for another. What matters is **your** trend over time: if your baseline is 50 ms and one morning it drops to 32, that drop is significant for you. If your baseline is 30 ms and you're always around that value, you're probably in balance. Apps like Garmin and Oura show a 'personal normal range' for exactly this reason.",
        es: "Una HRV de 42 ms puede ser excelente para una persona y mediocre para otra. Lo que importa es **tu** tendencia en el tiempo: si tu línea base es 50 ms y una mañana baja a 32, ese descenso es significativo para ti. Si tu línea base es 30 ms y siempre rondas ese valor, probablemente estás en equilibrio. Apps como Garmin y Oura muestran un 'rango normal personal' precisamente por eso.",
        de: "Eine HRV von 42 ms ist für eine Person ausgezeichnet und für eine andere mittelmäßig. Was zählt, ist **dein** Trend im Laufe der Zeit: Wenn deine Baseline 50 ms beträgt und sie eines Morgens auf 32 sinkt, ist dieser Rückgang für dich bedeutsam. Wenn deine Baseline 30 ms beträgt und du immer in der Nähe dieses Wertes bist, bist du wahrscheinlich im Gleichgewicht. Apps wie Garmin und Oura zeigen genau aus diesem Grund einen 'persönlichen Normalbereich'.",
        pt: "Uma HRV de 42 ms é excelente para uma pessoa e medíocre para outra. O que importa é a **sua** tendência ao longo do tempo: se a sua linha de base é 50 ms e uma manhã cai para 32, essa queda é significativa para você. Se a sua linha de base é 30 ms e você está sempre em torno desse valor, provavelmente está em equilíbrio. Apps como Garmin e Oura mostram um 'intervalo normal pessoal' exatamente por isso.",
        fr: "Une HRV de 42 ms est excellente pour une personne et médiocre pour une autre. Ce qui compte, c'est **votre** tendance dans le temps: si votre valeur de référence est 50 ms et qu'un matin elle chute à 32, cette baisse est significative pour vous. Si votre valeur de référence est 30 ms et que vous êtes toujours autour de cette valeur, vous êtes probablement en équilibre. Des applications comme Garmin et Oura affichent un 'intervalle normal personnel' exactement pour cette raison.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Come i wearable misurano la HRV",
        en: "How wearables measure HRV",
        es: "Cómo miden la HRV los wearables",
        de: "Wie Wearables die HRV messen",
        pt: "Como os wearables medem a HRV",
        fr: "Comment les appareils connectés mesurent la HRV",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "I wearable consumer (Galaxy Watch, Garmin, Oura, Polar) usano principalmente due metodi per misurare la HRV:",
        en: "Consumer wearables (Galaxy Watch, Garmin, Oura, Polar) primarily use two methods to measure HRV:",
        es: "Los wearables de consumo (Galaxy Watch, Garmin, Oura, Polar) utilizan principalmente dos métodos para medir la HRV:",
        de: "Consumer-Wearables (Galaxy Watch, Garmin, Oura, Polar) verwenden hauptsächlich zwei Methoden zur Messung der HRV:",
        pt: "Os wearables de consumo (Galaxy Watch, Garmin, Oura, Polar) usam principalmente dois métodos para medir a HRV:",
        fr: "Les appareils connectés grand public (Galaxy Watch, Garmin, Oura, Polar) utilisent principalement deux méthodes pour mesurer la HRV:",
      },
    },
    {
      type: "list",
      items: {
        it: [
          "**PPG (fotopletismografia)**: un LED verde (o rosso/infrarosso) illumina il polso e un sensore misura le variazioni di assorbimento della luce causate dal flusso sanguigno. È il metodo usato dalla stragrande maggioranza degli smartwatch. Meno preciso di un ECG, ma sufficiente per tracking delle tendenze.",
          "**ECG**: disponibile su alcuni watch premium (Galaxy Watch Ultra, Apple Watch Series con funzione ECG). Misura direttamente l'attività elettrica del cuore. Più accurata per sessioni brevi, ma la differenza pratica per il tracking quotidiano è spesso marginale.",
        ],
        en: [
          "**PPG (photoplethysmography)**: a green (or red/infrared) LED illuminates the wrist and a sensor measures light absorption variations caused by blood flow. This is the method used by the vast majority of smartwatches. Less precise than ECG, but sufficient for trend tracking.",
          "**ECG**: available on some premium watches (Galaxy Watch Ultra, Apple Watch Series with ECG function). Directly measures the heart's electrical activity. More accurate for short sessions, but the practical difference for daily tracking is often marginal.",
        ],
        es: [
          "**PPG (fotopletismografía)**: un LED verde (o rojo/infrarrojo) ilumina la muñeca y un sensor mide las variaciones de absorción de luz causadas por el flujo sanguíneo. Es el método utilizado por la gran mayoría de los smartwatches. Menos preciso que un ECG, pero suficiente para el seguimiento de tendencias.",
          "**ECG**: disponible en algunos relojes premium (Galaxy Watch Ultra, Apple Watch Series con función de ECG). Mide directamente la actividad eléctrica del corazón. Más preciso en sesiones cortas, aunque la diferencia práctica para el seguimiento diario suele ser marginal.",
        ],
        de: [
          "**PPG (Photoplethysmografie)**: Eine grüne (oder rote/Infrarot-) LED beleuchtet das Handgelenk und ein Sensor misst die durch den Blutfluss verursachten Lichtabsorptionsschwankungen. Dies ist die Methode, die von der überwältigenden Mehrheit der Smartwatches verwendet wird. Weniger präzise als ein EKG, aber ausreichend für das Trend-Tracking.",
          "**EKG**: Verfügbar auf einigen Premium-Smartwatches (Galaxy Watch Ultra, Apple Watch Series mit EKG-Funktion). Misst direkt die elektrische Aktivität des Herzens. Genauer für kurze Sitzungen, aber der praktische Unterschied für das tägliche Tracking ist oft marginal.",
        ],
        pt: [
          "**PPG (fotopletismografia)**: um LED verde (ou vermelho/infravermelho) ilumina o pulso e um sensor mede as variações de absorção de luz causadas pelo fluxo sanguíneo. É o método usado pela grande maioria dos smartwatches. Menos preciso que um ECG, mas suficiente para o acompanhamento de tendências.",
          "**ECG**: disponível em alguns relógios premium (Galaxy Watch Ultra, Apple Watch Series com função ECG). Mede diretamente a atividade elétrica do coração. Mais preciso para sessões curtas, mas a diferença prática para o monitoramento diário é frequentemente marginal.",
        ],
        fr: [
          "**PPG (photopléthysmographie)**: une LED verte (ou rouge/infrarouge) illumine le poignet et un capteur mesure les variations d'absorption de la lumière causées par le flux sanguin. C'est la méthode utilisée par la grande majorité des montres connectées. Moins précise qu'un ECG, mais suffisante pour le suivi des tendances.",
          "**ECG**: disponible sur certaines montres premium (Galaxy Watch Ultra, Apple Watch Series avec fonction ECG). Mesure directement l'activité électrique du coeur. Plus précis pour les sessions courtes, mais la différence pratique pour le suivi quotidien est souvent marginale.",
        ],
      },
    },
    {
      type: "paragraph",
      text: {
        it: "La misura più affidabile che un wearable può fare è durante il sonno, quando sei fermo e non ci sono movimenti che distorcono il segnale. Garmin chiama questa metrica 'HRV notturna' o 'RMSSD medio notturno'. Oura fa lo stesso. Galaxy Watch (via Samsung Health) registra la HRV durante il sonno ed espone i valori nell'app.",
        en: "The most reliable measurement a wearable can make is during sleep, when you're still and there are no movements distorting the signal. Garmin calls this metric 'overnight HRV' or 'nightly average RMSSD'. Oura does the same. Galaxy Watch (via Samsung Health) records HRV during sleep and exposes values in the app.",
        es: "La medición más fiable que puede hacer un wearable es durante el sueño, cuando estás quieto y no hay movimientos que distorsionen la señal. Garmin llama a esta métrica 'HRV nocturna' o 'RMSSD promedio nocturno'. Oura hace lo mismo. Galaxy Watch (a través de Samsung Health) registra la HRV durante el sueño y expone los valores en la app.",
        de: "Die zuverlässigste Messung, die ein Wearable machen kann, ist während des Schlafs, wenn du stillst und keine Bewegungen das Signal verzerren. Garmin nennt diese Metrik 'nächtliche HRV' oder 'nächtlicher RMSSD-Durchschnitt'. Oura macht dasselbe. Galaxy Watch (über Samsung Health) zeichnet die HRV während des Schlafs auf und zeigt die Werte in der App.",
        pt: "A medição mais confiável que um wearable pode fazer é durante o sono, quando você está quieto e não há movimentos distorcendo o sinal. Garmin chama essa métrica de 'HRV noturna' ou 'RMSSD médio noturno'. Oura faz o mesmo. Galaxy Watch (via Samsung Health) registra a HRV durante o sono e expõe os valores no app.",
        fr: "La mesure la plus fiable qu'un appareil connecté puisse effectuer est pendant le sommeil, quand vous êtes immobile et qu'il n'y a pas de mouvements qui déforment le signal. Garmin appelle cette métrique 'HRV nocturne' ou 'RMSSD moyen nocturne'. Oura fait de même. Galaxy Watch (via Samsung Health) enregistre la HRV pendant le sommeil et affiche les valeurs dans l'application.",
      },
    },
    {
      type: "callout",
      variant: "tip",
      title: {
        it: "Il numero assoluto della HRV è quasi irrilevante senza contesto personale",
        en: "The absolute HRV number is almost irrelevant without personal context",
        es: "El número absoluto de HRV es casi irrelevante sin contexto personal",
        de: "Der absolute HRV-Wert ist ohne persönlichen Kontext fast irrelevant",
        pt: "O número absoluto de HRV é quase irrelevante sem contexto pessoal",
        fr: "Le chiffre absolu de HRV est presque sans importance sans contexte personnel",
      },
      body: {
        it: "La maggior parte delle persone che cercano 'HRV valori normali' stanno facendo la domanda sbagliata. Non esiste un target universale: la differenza tra un atleta e un sedentario della stessa età può essere di 50 ms, e entrambi sono perfettamente normali per chi sono. La domanda giusta è: 'La mia HRV è significativamente diversa dalla mia baseline delle ultime 2-4 settimane?' Se la risposta è sì e il calo dura più di 3 giorni, quello è il segnale da ascoltare.",
        en: "Most people searching 'HRV normal values' are asking the wrong question. There is no universal target: the difference between an athlete and a sedentary person of the same age can be 50 ms, and both are perfectly normal for who they are. The right question is: 'Is my HRV significantly different from my baseline over the last 2-4 weeks?' If the answer is yes and the drop lasts more than 3 days, that's the signal worth paying attention to.",
        es: "La mayoría de las personas que buscan 'valores normales de HRV' están haciendo la pregunta equivocada. No existe un objetivo universal: la diferencia entre un atleta y una persona sedentaria de la misma edad puede ser de 50 ms, y ambos son perfectamente normales para quienes son. La pregunta correcta es: '¿Mi HRV es significativamente diferente de mi línea base de las últimas 2-4 semanas?' Si la respuesta es sí y el descenso dura más de 3 días, esa es la señal a la que debes prestar atención.",
        de: "Die meisten Menschen, die nach 'HRV Normalwerten' suchen, stellen die falsche Frage. Es gibt keinen universellen Zielwert: Der Unterschied zwischen einem Athleten und einer inaktiven Person desselben Alters kann 50 ms betragen, und beide sind vollkommen normal für das, was sie sind. Die richtige Frage lautet: 'Ist meine HRV signifikant anders als meine Baseline der letzten 2-4 Wochen?' Wenn die Antwort ja lautet und der Rückgang mehr als 3 Tage anhält, ist das das Signal, dem man Beachtung schenken sollte.",
        pt: "A maioria das pessoas que pesquisa 'valores normais de HRV' está fazendo a pergunta errada. Não existe um alvo universal: a diferença entre um atleta e uma pessoa sedentária da mesma idade pode ser de 50 ms, e ambos são perfeitamente normais para quem são. A pergunta certa é: 'A minha HRV é significativamente diferente da minha linha de base das últimas 2-4 semanas?' Se a resposta for sim e a queda durar mais de 3 dias, esse é o sinal ao qual prestar atenção.",
        fr: "La plupart des personnes qui recherchent 'valeurs normales HRV' posent la mauvaise question. Il n'existe pas de cible universelle: la différence entre un athlète et une personne sédentaire du même âge peut être de 50 ms, et les deux sont parfaitement normaux pour ce qu'ils sont. La bonne question est: 'Ma HRV est-elle significativement différente de ma valeur de référence des 2-4 dernières semaines?' Si la réponse est oui et que la baisse dure plus de 3 jours, c'est le signal auquel il faut prêter attention.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Cosa fare (e non fare) con la HRV nel training quotidiano",
        en: "What to do (and not do) with HRV in daily training",
        es: "Qué hacer (y qué no hacer) con la HRV en el entrenamiento diario",
        de: "Was man mit der HRV im täglichen Training tun (und lassen) sollte",
        pt: "O que fazer (e não fazer) com a HRV no treino diário",
        fr: "Ce qu'il faut faire (et ne pas faire) avec la HRV dans l'entraînement quotidien",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "L'uso più diffuso della HRV tra gli atleti amatori è come indicatore di recupero: se la HRV è significativamente sotto la baseline personale, potrebbe non essere il giorno migliore per un allenamento intenso. Questa è una semplificazione utile, ma con alcune condizioni importanti.",
        en: "The most widespread use of HRV among amateur athletes is as a recovery indicator: if HRV is significantly below personal baseline, it might not be the best day for an intense workout. This is a useful simplification, but with some important conditions.",
        es: "El uso más extendido de la HRV entre los atletas aficionados es como indicador de recuperación: si la HRV está significativamente por debajo de la línea base personal, puede que no sea el mejor día para un entrenamiento intenso. Es una simplificación útil, pero con algunas condiciones importantes.",
        de: "Die verbreitetste Verwendung der HRV unter Freizeitsportlern ist als Erholungsindikator: Wenn die HRV deutlich unter der persönlichen Baseline liegt, könnte es nicht der beste Tag für ein intensives Training sein. Das ist eine nützliche Vereinfachung, aber mit einigen wichtigen Bedingungen.",
        pt: "O uso mais difundido da HRV entre atletas amadores é como indicador de recuperação: se a HRV estiver significativamente abaixo da linha de base pessoal, pode não ser o melhor dia para um treino intenso. Esta é uma simplificação útil, mas com algumas condições importantes.",
        fr: "L'utilisation la plus répandue de la HRV chez les athlètes amateurs est comme indicateur de récupération: si la HRV est significativement en dessous de la valeur de référence personnelle, ce n'est peut-être pas le meilleur jour pour un entraînement intense. C'est une simplification utile, mais avec quelques conditions importantes.",
      },
    },
    {
      type: "list",
      items: {
        it: [
          "**Ha senso guardarlo come trend settimanale**, non come dato giornaliero assoluto. Una singola notte di HRV bassa può avere cento cause (cena pesante, alcol, posizione di sonno atipica, notte calda). Una settimana intera sotto la tua baseline è più informativa.",
          "**Non è un indicatore di malattia**: la HRV bassa non significa che stai per ammalarti o che hai un problema cardiaco. È un segnale di stato del sistema nervoso autonomo, non una diagnosi.",
          "**Il confronto tra diverse app non è diretto**: Garmin, Samsung, Oura e Polar usano algoritmi e intervalli di misura diversi. Un valore di 55 su Garmin non è direttamente comparabile con un 55 su Oura, anche se entrambi misurano 'HRV'.",
          "**Non sostituisce il buon senso**: se hai dormito 5 ore ma la tua HRV è alta quella mattina, probabilmente il sonno da recuperare pesa più del numero HRV.",
        ],
        en: [
          "**It makes sense to look at it as a weekly trend**, not as an absolute daily figure. A single night of low HRV can have a hundred causes (heavy dinner, alcohol, atypical sleep position, hot night). A full week below your baseline is more informative.",
          "**It's not a disease indicator**: low HRV doesn't mean you're about to get sick or have a heart problem. It's a signal of autonomic nervous system state, not a diagnosis.",
          "**Cross-app comparison isn't direct**: Garmin, Samsung, Oura and Polar use different algorithms and measurement intervals. A value of 55 on Garmin isn't directly comparable to a 55 on Oura, even if both measure 'HRV'.",
          "**It doesn't replace common sense**: if you slept 5 hours but your HRV is high that morning, the sleep debt you need to recover probably matters more than the HRV number.",
        ],
        es: [
          "**Tiene sentido observarla como tendencia semanal**, no como dato diario absoluto. Una sola noche de HRV baja puede tener cien causas (cena copiosa, alcohol, posición de sueño atípica, noche de calor). Una semana entera por debajo de tu línea base es mucho más informativa.",
          "**No es un indicador de enfermedad**: la HRV baja no significa que estés a punto de enfermar ni que tengas un problema cardíaco. Es una señal del estado del sistema nervioso autónomo, no un diagnóstico.",
          "**La comparación entre distintas apps no es directa**: Garmin, Samsung, Oura y Polar usan algoritmos e intervalos de medición diferentes. Un valor de 55 en Garmin no es directamente comparable con un 55 en Oura, aunque ambos midan la HRV.",
          "**No reemplaza el sentido común**: si dormiste 5 horas pero tu HRV es alta esa mañana, la deuda de sueño que tienes que recuperar probablemente pesa más que el número de HRV.",
        ],
        de: [
          "**Es macht Sinn, sie als wöchentlichen Trend zu betrachten**, nicht als absoluten Tageswert. Eine einzige Nacht mit niedriger HRV kann hundert Ursachen haben (schweres Abendessen, Alkohol, ungewöhnliche Schlafposition, warme Nacht). Eine ganze Woche unter deiner Baseline ist informativer.",
          "**Sie ist kein Krankheitsindikator**: Eine niedrige HRV bedeutet nicht, dass du krank werden wirst oder ein Herzproblem hast. Sie ist ein Signal des Zustands des autonomen Nervensystems, keine Diagnose.",
          "**Der App-übergreifende Vergleich ist nicht direkt**: Garmin, Samsung, Oura und Polar verwenden unterschiedliche Algorithmen und Messintervalle. Ein Wert von 55 bei Garmin ist nicht direkt vergleichbar mit einem 55 bei Oura, auch wenn beide 'HRV' messen.",
          "**Sie ersetzt nicht den gesunden Menschenverstand**: Wenn du 5 Stunden geschlafen hast, deine HRV aber an diesem Morgen hoch ist, wiegt der aufzuholende Schlaf wahrscheinlich mehr als die HRV-Zahl.",
        ],
        pt: [
          "**Faz sentido observá-la como tendência semanal**, não como dado diário absoluto. Uma única noite de HRV baixa pode ter cem causas (jantar pesado, álcool, posição de sono atípica, noite quente). Uma semana inteira abaixo da sua linha de base é mais informativa.",
          "**Não é um indicador de doença**: uma HRV baixa não significa que você vai ficar doente ou que tem um problema cardíaco. É um sinal do estado do sistema nervoso autônomo, não um diagnóstico.",
          "**A comparação entre apps diferentes não é direta**: Garmin, Samsung, Oura e Polar usam algoritmos e intervalos de medição diferentes. Um valor de 55 no Garmin não é diretamente comparável com um 55 no Oura, mesmo que ambos meçam 'HRV'.",
          "**Não substitui o bom senso**: se você dormiu 5 horas mas a sua HRV está alta naquela manhã, a dívida de sono que você precisa recuperar provavelmente pesa mais do que o número de HRV.",
        ],
        fr: [
          "**Il est logique de la regarder comme une tendance hebdomadaire**, pas comme une donnée journalière absolue. Une seule nuit de faible HRV peut avoir cent causes (dîner copieux, alcool, position de sommeil atypique, nuit chaude). Une semaine entière en dessous de votre valeur de référence est plus informative.",
          "**Ce n'est pas un indicateur de maladie**: une HRV basse ne signifie pas que vous êtes sur le point de tomber malade ou que vous avez un problème cardiaque. C'est un signal de l'état du système nerveux autonome, pas un diagnostic.",
          "**La comparaison entre différentes applications n'est pas directe**: Garmin, Samsung, Oura et Polar utilisent des algorithmes et des intervalles de mesure différents. Une valeur de 55 sur Garmin n'est pas directement comparable à un 55 sur Oura, même si les deux mesurent la 'HRV'.",
          "**Cela ne remplace pas le bon sens**: si vous avez dormi 5 heures mais que votre HRV est élevée ce matin-là, la dette de sommeil que vous devez récupérer pèse probablement plus que le chiffre HRV.",
        ],
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "HRV e salute generale: le domande frequenti",
        en: "HRV and general health: the frequently asked questions",
        es: "HRV y bienestar general: las preguntas más frecuentes",
        de: "HRV und allgemeines Wohlbefinden: die häufig gestellten Fragen",
        pt: "HRV e bem-estar geral: as perguntas frequentes",
        fr: "HRV et bien-être général: les questions fréquentes",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Al di là dello sport, la HRV è usata in contesti clinici come marcatore di stress cronico, benessere cardiovascolare, e risposta al trattamento in alcune patologie. Questo non significa che il numero sul tuo smartwatch abbia lo stesso peso clinico di una misurazione medica: la precisione è diversa, i protocolli di misura sono diversi, e un medico usa la HRV in contesti molto specifici e con strumenti calibrati.",
        en: "Beyond sports, HRV is used in clinical contexts as a marker of chronic stress, cardiovascular wellness, and treatment response in some conditions. This doesn't mean the number on your smartwatch carries the same clinical weight as a medical measurement: precision is different, measurement protocols are different, and a doctor uses HRV in very specific contexts with calibrated instruments.",
        es: "Más allá del deporte, la HRV se utiliza en contextos especializados como marcador de estrés crónico, bienestar cardiovascular y respuesta a ciertos tratamientos. Esto no significa que el número en tu smartwatch tenga el mismo peso que una medición médica: la precisión es diferente, los protocolos de medición son distintos, y los profesionales de la salud usan la HRV en contextos muy específicos con instrumentos calibrados.",
        de: "Über den Sport hinaus wird die HRV in Fachkontexten als Marker für chronischen Stress, kardiovaskuläres Wohlbefinden und die Reaktion auf bestimmte Maßnahmen verwendet. Das bedeutet nicht, dass die Zahl auf deiner Smartwatch dasselbe Gewicht hat wie eine professionelle Messung: Die Genauigkeit ist unterschiedlich, die Messprotokolle sind unterschiedlich, und Fachleute verwenden die HRV in sehr spezifischen Kontexten mit kalibrierten Instrumenten.",
        pt: "Além do esporte, a HRV é usada em contextos especializados como marcador de estresse crônico, bem-estar cardiovascular e resposta a certos tratamentos. Isso não significa que o número no seu smartwatch tenha o mesmo peso que uma medição profissional: a precisão é diferente, os protocolos de medição são diferentes, e profissionais de saúde usam a HRV em contextos muito específicos com instrumentos calibrados.",
        fr: "Au-delà du sport, la HRV est utilisée dans des contextes spécialisés comme marqueur de stress chronique, de bien-être cardiovasculaire et de réponse à certains traitements. Cela ne signifie pas que le chiffre sur votre montre connectée a le même poids qu'une mesure professionnelle: la précision est différente, les protocoles de mesure sont différents, et les professionnels de santé utilisent la HRV dans des contextes très spécifiques avec des instruments calibrés.",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Il valore del wearable è nel tracking longitudinale personale: vedere i propri pattern nel tempo, notare variazioni correlate a eventi della vita (stress lavorativo, cambi di routine, viaggio), e usare queste informazioni per prendere decisioni più informate sul proprio stile di vita. Non per autodiagnosticarsi.",
        en: "The value of the wearable is in personal longitudinal tracking: seeing your own patterns over time, noticing variations correlated to life events (work stress, routine changes, travel), and using this information to make more informed decisions about lifestyle. Not for self-diagnosis.",
        es: "El valor del wearable está en el seguimiento longitudinal personal: ver tus propios patrones a lo largo del tiempo, detectar variaciones relacionadas con eventos de la vida (estrés laboral, cambios de rutina, viajes) y usar esa información para tomar decisiones más conscientes sobre tu estilo de vida. No para sacar conclusiones médicas por tu cuenta.",
        de: "Der Wert des Wearables liegt im persönlichen Langzeit-Tracking: die eigenen Muster im Laufe der Zeit zu sehen, Variationen zu bemerken, die mit Lebensereignissen korrelieren (Arbeitsstress, Routineänderungen, Reisen), und diese Informationen zu nutzen, um fundiertere Entscheidungen über den Lebensstil zu treffen. Nicht zur Selbstdiagnose.",
        pt: "O valor do wearable está no acompanhamento longitudinal pessoal: ver os próprios padrões ao longo do tempo, notar variações correlacionadas a eventos da vida (estresse no trabalho, mudanças de rotina, viagens) e usar essas informações para tomar decisões mais informadas sobre o estilo de vida. Não para se autodiagnosticar.",
        fr: "La valeur de l'appareil connecté réside dans le suivi longitudinal personnel: voir ses propres schémas dans le temps, remarquer les variations corrélées aux événements de la vie (stress au travail, changements de routine, voyages), et utiliser ces informations pour prendre des décisions plus éclairées sur son mode de vie. Pas pour se diagnostiquer soi-même.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "In sintesi",
        en: "In summary",
        es: "En resumen",
        de: "Zusammenfassung",
        pt: "Em resumo",
        fr: "En résumé",
      },
    },
    {
      type: "list",
      items: {
        it: [
          "La HRV misura la variazione negli intervalli tra battiti (millisecondi), non la frequenza media: una variabilità alta indica sistema nervoso autonomo in equilibrio, non un problema cardiaco.",
          "Il valore assoluto conta poco: un atleta di 40 anni può avere 85 ms e un sedentario 35 ms, entrambi normali per chi sono. Il dato utile è il tuo trend personale su 2-4 settimane.",
          "La misura più affidabile è quella notturna (durante il sonno), quando il movimento non disturba il sensore PPG.",
          "I valori di Garmin, Oura, Samsung e Polar non sono direttamente comparabili: usano algoritmi diversi. Scegli un dispositivo come riferimento e non mischiare i numeri.",
          "Per migliorare la HRV nel tempo: sonno regolare, attività aerobica moderata, riduzione alcol. Non esistono hack rapidi: i cambiamenti visibili richiedono settimane.",
        ],
        en: [
          "HRV measures variation in beat intervals (milliseconds), not average heart rate: high variability indicates autonomic nervous system balance, not a cardiac problem.",
          "The absolute value matters little: a 40-year-old athlete may have 85 ms and a sedentary person 35 ms, both normal for who they are. The useful data is your personal trend over 2-4 weeks.",
          "The most reliable measurement is overnight (during sleep), when movement doesn't disturb the PPG sensor.",
          "Garmin, Oura, Samsung and Polar values are not directly comparable: they use different algorithms. Pick one device as your reference and don't mix numbers.",
          "To improve HRV over time: regular sleep, moderate aerobic activity, alcohol reduction. There are no quick hacks: visible changes take weeks.",
        ],
        es: [
          "La HRV mide la variación en los intervalos entre latidos (milisegundos), no la frecuencia media: una variabilidad alta indica equilibrio del sistema nervioso autónomo, no un problema cardíaco.",
          "El valor absoluto importa poco: un atleta de 40 años puede tener 85 ms y una persona sedentaria 35 ms, ambos normales para quienes son. El dato útil es tu tendencia personal durante 2-4 semanas.",
          "La medición más fiable es la nocturna (durante el sueño), cuando el movimiento no interfiere con el sensor PPG.",
          "Los valores de Garmin, Oura, Samsung y Polar no son directamente comparables: usan algoritmos distintos. Elige un dispositivo como referencia y no mezcles los números.",
          "Para mejorar la HRV con el tiempo: sueño regular, actividad aeróbica moderada, reducción del alcohol. No existen atajos rápidos: los cambios visibles requieren semanas.",
        ],
        de: [
          "Die HRV misst die Variation der Intervalle zwischen Herzschlägen (Millisekunden), nicht die durchschnittliche Herzfrequenz: Eine hohe Variabilität zeigt ein ausgeglichenes autonomes Nervensystem an, kein Herzproblem.",
          "Der absolute Wert spielt kaum eine Rolle: Ein 40-jähriger Athlet kann 85 ms haben, eine inaktive Person 35 ms, beide normal für ihre jeweilige Situation. Das nützliche Datum ist dein persönlicher Trend über 2-4 Wochen.",
          "Die zuverlässigste Messung ist die nächtliche (während des Schlafs), wenn Bewegung den PPG-Sensor nicht stört.",
          "Die Werte von Garmin, Oura, Samsung und Polar sind nicht direkt vergleichbar: Sie verwenden unterschiedliche Algorithmen. Wähle ein Gerät als Referenz und vermische die Zahlen nicht.",
          "Um die HRV langfristig zu verbessern: regelmäßiger Schlaf, moderate aerobe Aktivität, Alkoholreduktion. Es gibt keine schnellen Abkürzungen: sichtbare Veränderungen brauchen Wochen.",
        ],
        pt: [
          "A HRV mede a variação nos intervalos entre batimentos (milissegundos), não a frequência cardíaca média: uma alta variabilidade indica equilíbrio do sistema nervoso autônomo, não um problema cardíaco.",
          "O valor absoluto importa pouco: um atleta de 40 anos pode ter 85 ms e uma pessoa sedentária 35 ms, ambos normais para quem são. O dado útil é a sua tendência pessoal ao longo de 2-4 semanas.",
          "A medição mais confiável é a noturna (durante o sono), quando o movimento não perturba o sensor PPG.",
          "Os valores de Garmin, Oura, Samsung e Polar não são diretamente comparáveis: usam algoritmos diferentes. Escolha um dispositivo como referência e não misture os números.",
          "Para melhorar a HRV ao longo do tempo: sono regular, atividade aeróbica moderada, redução do álcool. Não existem atalhos rápidos: mudanças visíveis levam semanas.",
        ],
        fr: [
          "La HRV mesure la variation des intervalles entre les battements (millisecondes), pas la fréquence cardiaque moyenne: une variabilité élevée indique un système nerveux autonome équilibré, pas un problème cardiaque.",
          "La valeur absolue compte peu: un athlète de 40 ans peut avoir 85 ms et une personne sédentaire 35 ms, tous deux normaux pour ce qu'ils sont. La donnée utile est votre tendance personnelle sur 2-4 semaines.",
          "La mesure la plus fiable est celle de la nuit (pendant le sommeil), quand les mouvements ne perturbent pas le capteur PPG.",
          "Les valeurs de Garmin, Oura, Samsung et Polar ne sont pas directement comparables: ils utilisent des algorithmes différents. Choisissez un appareil comme référence et ne mélangez pas les chiffres.",
          "Pour améliorer la HRV dans le temps: sommeil régulier, activité aérobique modérée, réduction de l'alcool. Il n'existe pas de raccourcis rapides: les changements visibles prennent des semaines.",
        ],
      },
    },
    {
      type: "cta",
      title: {
        it: "Vuoi monitorare la tua HRV su una dashboard unificata?",
        en: "Want to monitor your HRV on a unified dashboard?",
        es: "¿Quieres monitorear tu HRV en un panel unificado?",
        de: "Möchtest du deine HRV auf einem einheitlichen Dashboard überwachen?",
        pt: "Quer monitorar sua HRV em um painel unificado?",
        fr: "Vous souhaitez surveiller votre HRV sur un tableau de bord unifié?",
      },
      body: {
        it: "Se hai un Garmin, un Oura Ring, o un Galaxy Watch e vuoi vedere la tua HRV storica su un'unica dashboard web, con trend nel tempo, confronto tra dispositivi e metriche correlate. FitMesh Sync è una delle opzioni che aggregano questi dati via API ufficiali.",
        en: "If you have a Garmin, an Oura Ring, or a Galaxy Watch and want to see your historical HRV on a single web dashboard, with trends over time, cross-device comparison and related metrics. FitMesh Sync is one of the options that aggregate this data via official APIs.",
        es: "Si tienes un Garmin, un Oura Ring o un Galaxy Watch y quieres ver tu HRV histórica en un único panel web, con tendencias en el tiempo, comparación entre dispositivos y métricas relacionadas. FitMesh Sync es una de las opciones que agregan estos datos a través de APIs oficiales.",
        de: "Wenn du ein Garmin, einen Oura Ring oder eine Galaxy Watch hast und deine HRV-Verlaufsdaten auf einem einzigen Web-Dashboard sehen möchtest, mit Trends im Laufe der Zeit, geräteübergreifendem Vergleich und verwandten Metriken. FitMesh Sync ist eine der Optionen, die diese Daten über offizielle APIs zusammenführt.",
        pt: "Se você tem um Garmin, um Oura Ring ou um Galaxy Watch e quer ver o histórico da sua HRV em um único painel web, com tendências ao longo do tempo, comparação entre dispositivos e métricas relacionadas. FitMesh Sync é uma das opções que agrega esses dados via APIs oficiais.",
        fr: "Si vous avez un Garmin, un Oura Ring ou une Galaxy Watch et souhaitez voir votre historique HRV sur un tableau de bord web unique, avec les tendances dans le temps, la comparaison entre appareils et les métriques associées. FitMesh Sync est l'une des options qui agrège ces données via des API officielles.",
      },
      ctaLabel: {
        it: "Vedi le integrazioni disponibili →",
        en: "See available integrations →",
        es: "Ver las integraciones disponibles →",
        de: "Verfügbare Integrationen ansehen →",
        pt: "Ver as integrações disponíveis →",
        fr: "Voir les intégrations disponibles →",
      },
      ctaHref: {
        it: "/it/integrations",
        en: "/en/integrations",
      },
    },
  ],
  faq: [
    {
      q: {
        it: "Cos'è la HRV in parole semplici?",
        en: "What is HRV in simple terms?",
        es: "¿Qué es la HRV en palabras sencillas?",
        de: "Was ist HRV in einfachen Worten?",
        pt: "O que é HRV em palavras simples?",
        fr: "Qu'est-ce que la HRV en termes simples?",
      },
      a: {
        it: "La HRV (variabilità della frequenza cardiaca) misura quanto variano i tempi tra un battito cardiaco e il successivo. Non è la frequenza cardiaca media: è la variazione di quella frequenza momento per momento. Una variabilità alta (battiti più 'irregolari' negli intervalli) indica in genere che il corpo è ben riposato e il sistema nervoso è in equilibrio. Una variabilità bassa segnala stress, affaticamento, o convalescenza.",
        en: "HRV (heart rate variability) measures how much the timing between heartbeats varies. It's not the average heart rate: it's the variation of that rate moment by moment. High variability (more 'irregular' intervals between beats) generally indicates the body is well-rested and the nervous system is balanced. Low variability signals stress, fatigue, or recovery from illness.",
        es: "La HRV (variabilidad de la frecuencia cardíaca) mide cuánto varían los tiempos entre un latido y el siguiente. No es la frecuencia cardíaca media: es la variación de esa frecuencia momento a momento. Una variabilidad alta (intervalos más 'irregulares' entre latidos) indica en general que el cuerpo está bien descansado y el sistema nervioso está equilibrado. Una variabilidad baja señala estrés, fatiga o recuperación.",
        de: "Die HRV (Herzfrequenzvariabilität) misst, wie stark die Zeitabstände zwischen den Herzschlägen variieren. Es ist nicht die durchschnittliche Herzfrequenz: Es ist die Variation dieser Frequenz von Moment zu Moment. Eine hohe Variabilität (mehr 'unregelmäßige' Intervalle zwischen Schlägen) zeigt in der Regel an, dass der Körper gut ausgeruht ist und das Nervensystem im Gleichgewicht ist. Eine niedrige Variabilität signalisiert Stress, Müdigkeit oder Erholung.",
        pt: "A HRV (variabilidade da frequência cardíaca) mede o quanto variam os tempos entre um batimento cardíaco e o próximo. Não é a frequência cardíaca média: é a variação dessa frequência momento a momento. Uma variabilidade alta (intervalos mais 'irregulares' entre batimentos) indica geralmente que o corpo está bem descansado e o sistema nervoso está equilibrado. Uma variabilidade baixa sinaliza estresse, fadiga ou recuperação.",
        fr: "La HRV (variabilité de la fréquence cardiaque) mesure dans quelle mesure les intervalles de temps entre les battements cardiaques varient. Ce n'est pas la fréquence cardiaque moyenne: c'est la variation de cette fréquence moment par moment. Une variabilité élevée (intervalles plus 'irréguliers' entre les battements) indique généralement que le corps est bien reposé et que le système nerveux est équilibré. Une faible variabilité signale le stress, la fatigue ou la convalescence.",
      },
    },
    {
      q: {
        it: "Quanto deve essere alta la mia HRV?",
        en: "How high should my HRV be?",
        es: "¿Cuánto debería ser mi HRV?",
        de: "Wie hoch sollte meine HRV sein?",
        pt: "Qual deve ser o valor da minha HRV?",
        fr: "Quelle doit être la valeur de ma HRV?",
      },
      a: {
        it: "Non esiste un target universale. La HRV varia enormemente per età, sesso, livello di fitness, genetica. Un range 'normale' per un adulto di 35 anni potrebbe essere tra 40 e 80 ms (RMSSD), ma un atleta potrebbe stare ben oltre 100 ms. La metrica utile non è il valore assoluto, ma il tuo trend personale: cerca di capire qual è la tua baseline su 2-4 settimane e osserva le deviazioni significative.",
        en: "There's no universal target. HRV varies enormously by age, sex, fitness level, genetics. A 'normal' range for a 35-year-old adult might be between 40 and 80 ms (RMSSD), but an athlete could be well above 100 ms. The useful metric isn't the absolute value, but your personal trend: try to understand your baseline over 2-4 weeks and observe significant deviations.",
        es: "No existe un objetivo universal. La HRV varía enormemente según la edad, el sexo, el nivel de condición física y la genética. Un rango 'normal' para un adulto de 35 años podría estar entre 40 y 80 ms (RMSSD), aunque un atleta puede estar por encima de los 100 ms. La métrica útil no es el valor absoluto, sino tu tendencia personal: trata de conocer tu línea base durante 2-4 semanas y observa las desviaciones significativas.",
        de: "Es gibt keinen universellen Zielwert. Die HRV variiert enorm je nach Alter, Geschlecht, Fitnesslevel und Genetik. Ein 'normaler' Bereich für einen 35-jährigen Erwachsenen könnte zwischen 40 und 80 ms (RMSSD) liegen, aber ein Athlet könnte weit über 100 ms liegen. Die nützliche Metrik ist nicht der absolute Wert, sondern dein persönlicher Trend: Versuche deine Baseline über 2-4 Wochen zu verstehen und beobachte signifikante Abweichungen.",
        pt: "Não existe um alvo universal. A HRV varia enormemente por idade, sexo, nível de condicionamento físico e genética. Uma faixa 'normal' para um adulto de 35 anos pode estar entre 40 e 80 ms (RMSSD), mas um atleta pode estar bem acima de 100 ms. A métrica útil não é o valor absoluto, mas a sua tendência pessoal: tente entender qual é a sua linha de base ao longo de 2-4 semanas e observe os desvios significativos.",
        fr: "Il n'existe pas de cible universelle. La HRV varie énormément selon l'âge, le sexe, le niveau de forme physique et la génétique. Une plage 'normale' pour un adulte de 35 ans pourrait se situer entre 40 et 80 ms (RMSSD), mais un athlète pourrait être bien au-delà de 100 ms. La métrique utile n'est pas la valeur absolue, mais votre tendance personnelle: essayez de comprendre votre valeur de référence sur 2-4 semaines et observez les écarts significatifs.",
      },
    },
    {
      q: {
        it: "HRV bassa: cosa significa?",
        en: "Low HRV: what does it mean?",
        es: "HRV baja: ¿qué significa?",
        de: "Niedrige HRV: Was bedeutet das?",
        pt: "HRV baixa: o que significa?",
        fr: "HRV basse: qu'est-ce que cela signifie?",
      },
      a: {
        it: "Una HRV sotto la tua baseline personale può segnalare varie cose: stress fisico (allenamento intenso, malattia in arrivo, convalescenza), stress mentale-emotivo, qualità del sonno scarsa, consumo di alcol la sera precedente, o semplicemente una notte con più movimenti del solito (che disturba la misura PPG). Un singolo valore basso non è preoccupante. Una settimana intera di valori significativamente sotto la tua normale merita attenzione e, se accompagnata da altri sintomi, potrebbe valere la pena menzionarla al medico.",
        en: "HRV below your personal baseline can signal various things: physical stress (intense workout, incoming illness, convalescence), mental-emotional stress, poor sleep quality, alcohol consumption the previous evening, or simply a night with more movement than usual (which disturbs the PPG measurement). A single low value isn't concerning. A full week of values significantly below your normal deserves attention and, if accompanied by other symptoms, might be worth mentioning to a doctor.",
        es: "Una HRV por debajo de tu línea base personal puede indicar varias cosas: estrés físico (entrenamiento intenso, inicio de una enfermedad, recuperación), estrés mental o emocional, calidad del sueño deficiente, consumo de alcohol la noche anterior o, simplemente, una noche con más movimiento de lo habitual (que interfiere con la medición PPG). Un valor bajo aislado no es motivo de preocupación. Una semana entera de valores significativamente por debajo de tu nivel habitual merece atención y, si va acompañada de otros síntomas, puede ser conveniente comentarlo con un profesional de la salud.",
        de: "Eine HRV unter deiner persönlichen Baseline kann verschiedene Dinge signalisieren: körperlichen Stress (intensives Training, aufkommende Erkrankung, Erholung), mentalen und emotionalen Stress, schlechte Schlafqualität, Alkoholkonsum am Vorabend oder einfach eine Nacht mit mehr Bewegung als üblich (was die PPG-Messung stört). Ein einzelner niedriger Wert ist nicht besorgniserregend. Eine ganze Woche mit Werten deutlich unter deinem normalen Niveau verdient Aufmerksamkeit und, wenn sie von anderen Beschwerden begleitet wird, könnte es sich lohnen, dies mit einem Arzt zu besprechen.",
        pt: "Uma HRV abaixo da sua linha de base pessoal pode sinalizar várias coisas: estresse físico (treino intenso, doença chegando, recuperação), estresse mental-emocional, qualidade do sono ruim, consumo de álcool na noite anterior ou simplesmente uma noite com mais movimentos do que o habitual (que perturba a medição PPG). Um único valor baixo não é preocupante. Uma semana inteira de valores significativamente abaixo do seu normal merece atenção e, se acompanhada de outros sintomas, pode valer a pena mencionar a um profissional de saúde.",
        fr: "Une HRV en dessous de votre valeur de référence personnelle peut signaler diverses choses: stress physique (entraînement intense, maladie imminente, convalescence), stress mental et émotionnel, mauvaise qualité du sommeil, consommation d'alcool la veille, ou simplement une nuit avec plus de mouvements que d'habitude (ce qui perturbe la mesure PPG). Une seule valeur basse n'est pas préoccupante. Une semaine entière de valeurs significativement en dessous de votre normale mérite attention et, si elle est accompagnée d'autres symptômes, il pourrait être utile d'en parler à un médecin.",
      },
    },
    {
      q: {
        it: "Galaxy Watch, Garmin e Oura misurano la stessa HRV?",
        en: "Do Galaxy Watch, Garmin and Oura measure the same HRV?",
        es: "¿Galaxy Watch, Garmin y Oura miden la misma HRV?",
        de: "Messen Galaxy Watch, Garmin und Oura dieselbe HRV?",
        pt: "Galaxy Watch, Garmin e Oura medem a mesma HRV?",
        fr: "Galaxy Watch, Garmin et Oura mesurent-ils la même HRV?",
      },
      a: {
        it: "Misurano la stessa metrica biologica (la variabilità degli intervalli RR) ma con hardware, algoritmi e protocolli di misura diversi. Il risultato numerico può differire anche significativamente tra un device e l'altro sulla stessa persona nella stessa notte. Non confrontare il numero assoluto tra device diversi. Scegli un device come riferimento principale e usa quello per il tuo trend personale.",
        en: "They measure the same biological metric (variability of RR intervals) but with different hardware, algorithms and measurement protocols. The numerical result can differ significantly between devices for the same person on the same night. Don't compare the absolute number between different devices. Choose one device as your primary reference and use that for your personal trend.",
        es: "Miden la misma métrica biológica (la variabilidad de los intervalos RR) pero con hardware, algoritmos y protocolos de medición distintos. El resultado numérico puede diferir de forma notable entre dispositivos para la misma persona en la misma noche. No compares el número absoluto entre dispositivos diferentes. Elige un dispositivo como referencia principal y úsalo para tu tendencia personal.",
        de: "Sie messen dieselbe biologische Metrik (die Variabilität der RR-Intervalle), aber mit unterschiedlicher Hardware, unterschiedlichen Algorithmen und Messprotokollen. Das numerische Ergebnis kann zwischen den Geräten bei derselben Person in derselben Nacht erheblich abweichen. Vergleiche die absolute Zahl nicht zwischen verschiedenen Geräten. Wähle ein Gerät als Hauptreferenz und verwende es für deinen persönlichen Trend.",
        pt: "Eles medem a mesma métrica biológica (a variabilidade dos intervalos RR), mas com hardware, algoritmos e protocolos de medição diferentes. O resultado numérico pode diferir significativamente entre os dispositivos para a mesma pessoa na mesma noite. Não compare o número absoluto entre dispositivos diferentes. Escolha um dispositivo como referência principal e use-o para a sua tendência pessoal.",
        fr: "Ils mesurent la même métrique biologique (la variabilité des intervalles RR) mais avec des matériels, algorithmes et protocoles de mesure différents. Le résultat numérique peut différer significativement entre les appareils pour la même personne la même nuit. Ne comparez pas le chiffre absolu entre différents appareils. Choisissez un appareil comme référence principale et utilisez-le pour votre tendance personnelle.",
      },
    },
    {
      q: {
        it: "Posso migliorare la mia HRV?",
        en: "Can I improve my HRV?",
        es: "¿Puedo mejorar mi HRV?",
        de: "Kann ich meine HRV verbessern?",
        pt: "Posso melhorar minha HRV?",
        fr: "Puis-je améliorer ma HRV?",
      },
      a: {
        it: "Sì, ma lentamente e indirettamente. Le variabili che influenzano positivamente la HRV nel lungo periodo includono: sonno regolare e sufficiente (7-8 ore per la maggior parte degli adulti), attività fisica aerobica moderata e costante, gestione dello stress (mindfulness, respirazione diaframmatica), riduzione dell'alcol, e in generale una routine di vita stabile. Non esistono 'hack' rapidi: i cambiamenti significativi nella HRV baseline si vedono tipicamente nel giro di settimane o mesi, non giorni.",
        en: "Yes, but slowly and indirectly. Variables that positively influence HRV in the long term include: regular and sufficient sleep (7-8 hours for most adults), moderate and consistent aerobic physical activity, stress management (mindfulness, diaphragmatic breathing), alcohol reduction, and generally a stable life routine. There are no quick 'hacks': significant changes in HRV baseline are typically seen over weeks or months, not days.",
        es: "Sí, pero de forma gradual e indirecta. Las variables que influyen positivamente en la HRV a largo plazo incluyen: sueño regular y suficiente (7-8 horas para la mayoría de los adultos), actividad física aeróbica moderada y constante, gestión del estrés (mindfulness, respiración diafragmática), reducción del alcohol y, en general, una rutina de vida estable. No existen 'atajos' rápidos: los cambios significativos en la línea base de HRV suelen verse en semanas o meses, no en días.",
        de: "Ja, aber langsam und indirekt. Zu den Variablen, die die HRV langfristig positiv beeinflussen, gehören: regelmäßiger und ausreichender Schlaf (7-8 Stunden für die meisten Erwachsenen), moderate und konstante aerobe körperliche Aktivität, Stressmanagement (Achtsamkeit, Zwerchfellatmung), Alkoholreduktion und generell eine stabile Lebensroutine. Es gibt keine schnellen 'Abkürzungen': Signifikante Veränderungen im HRV-Baseline sieht man typischerweise im Verlauf von Wochen oder Monaten, nicht Tagen.",
        pt: "Sim, mas de forma lenta e indireta. As variáveis que influenciam positivamente a HRV a longo prazo incluem: sono regular e suficiente (7-8 horas para a maioria dos adultos), atividade física aeróbica moderada e consistente, gestão do estresse (mindfulness, respiração diafragmática), redução do álcool e, em geral, uma rotina de vida estável. Não existem 'atalhos' rápidos: mudanças significativas na linha de base da HRV são tipicamente observadas ao longo de semanas ou meses, não dias.",
        fr: "Oui, mais lentement et indirectement. Les variables qui influencent positivement la HRV sur le long terme comprennent: un sommeil régulier et suffisant (7-8 heures pour la plupart des adultes), une activité physique aérobique modérée et régulière, la gestion du stress (pleine conscience, respiration diaphragmatique), la réduction de l'alcool et, en général, une routine de vie stable. Il n'existe pas de raccourcis rapides: les changements significatifs dans la valeur de référence HRV se voient généralement sur des semaines ou des mois, pas des jours.",
      },
    },
  ],
  related: [
    "guida-sync-wearable-2026",
    "scegliere-smartwatch-dati-2026",
    "health-connect-vs-samsung-health",
  ],
  brandsMentioned: ["Garmin", "Samsung", "Oura", "Polar", "Apple", "Google"],
  ldType: "BlogPosting",
};
