import type { BlogPost } from "../types";

export const post: BlogPost = {
  slug: "novita-anello-colmi-sonno",
  category: "news",
  publishedAt: "2026-06-12",
  updatedAt: "2026-06-12",
  ldType: "BlogPosting",
  readMinutes: 3,
  primaryKeyword: {
    it: "anello Colmi sonno",
    en: "Colmi ring sleep",
    es: "anillo Colmi sueño",
    de: "Colmi Ring Schlaf",
    pt: "anel Colmi sono",
    fr: "bague Colmi sommeil",
    pl: "pętla Colmi snu",
    tr: "anneli Colmi uyku",
    nl: "Colmi ring slaap",
    ja: "Colmiリング睡眠",
    ko: "Colmi 링 수면",
  },
  secondaryKeywords: {
    it: [
      "anello smart sonno fasi",
      "Colmi ring FitMesh",
      "monitoraggio sonno profondo REM",
      "trova anello Colmi",
      "badge Pro gratis FitMesh",
    ],
    en: [
      "smart ring sleep stages",
      "Colmi ring FitMesh",
      "deep sleep REM tracking",
      "find my Colmi ring",
      "free Pro badge FitMesh",
    ],
    pt: [
      "anel inteligente fases do sono",
      "Colmi ring FitMesh",
      "monitoramento sono profundo REM",
      "encontrar anel Colmi",
      "badge Pro grátis FitMesh",
    ],
    fr: [
      "bague connectée phases du sommeil",
      "Colmi ring FitMesh",
      "suivi sommeil profond REM",
      "localiser ma bague Colmi",
      "badge Pro gratuit FitMesh",
    ],
    pl: [
      "fazy seni smart anellu",
      "pierścień FitMesh",
      "monitorowanie głębokiego senu REM",
      "znajdź anell Colmi",
      "znak Premium bezpłatnie FitMesh",
    ],
    tr: [
      "ayı smart uyku aşamaları",
      "Colmi halka FitMesh",
      "uyku derinliklerini takip REM",
      "bul halka Colmi",
      "badge Pro Ücretsiz FitMesh",
    ],
    nl: [
      "slimme ring slaapfasen",
      "Colmi ring FitMesh",
      "diepe slaap REM tracking",
      "vind mijn Colmi ring",
      "gratis Pro badge FitMesh",
    ],
    ja: [
      "スマートリング睡眠ステージ",
      "ColmiリングFitMesh",
      "深い睡眠REM追跡",
      "Colmiリングを探す",
      "無料ProバッジFitMesh",
    ],
    ko: [
      "스마트 링 수면 단계",
      "Colmi 링 FitMesh",
      "깊은 수면 REM 추적",
      "내 Colmi 링 찾기",
      "무료 Pro 배지 FitMesh",
    ],
  },
  metaDescription: {
    it: "FitMesh Sync ora legge l'anello Colmi via Bluetooth: sonno con fasi, batteria sempre visibile, funzione Trova anello. E 7 giorni di dati sbloccano 6 mesi di Pro gratis.",
    en: "FitMesh Sync now reads the Colmi ring via Bluetooth: sleep with stages, battery always visible, Find ring feature. And 7 days of data unlock 6 months of Pro free.",
    es: "FitMesh Sync ya lee el anillo Colmi por Bluetooth: sueño con fases, batería siempre visible, función Encuentra tu anillo. Y 7 días de datos desbloquean 6 meses de Pro gratis.",
    de: "FitMesh Sync liest jetzt den Colmi Ring per Bluetooth: Schlaf mit Schlafphasen, Akkustand immer sichtbar, Ring-orten-Funktion. Und 7 Tage Daten schalten 6 Monate Pro kostenlos frei.",
    pt: "FitMesh Sync agora lê o anel Colmi via Bluetooth: sono com fases, bateria sempre visível, função Localizar anel. E 7 dias de dados desbloqueiam 6 meses de Pro grátis.",
    fr: "FitMesh Sync lit maintenant la bague Colmi via Bluetooth: sommeil avec phases, batterie toujours visible, fonction Localiser la bague. Et 7 jours de données débloquent 6 mois de Pro gratuit.",
    pl: "FitMesh Sync teraz czyść anell Colmi za pomocą Bluetooth: sen w fazach, zawsze widoczna bateria, funkcja Znajdź anell. A 7 dniowych danych otwierają 6 miesięcy bezpłatnej Pro.",
    tr: "FitMesh Sync şimdi Colmi cihazını oku: uyku aşamaları, şarj durumu her zaman görünür, ayarla Bluetooth özelliği. 7 gün veri kaydediyor ve Pro'u 6 ay ücretsiz yapar.",
    nl: "FitMesh Sync leest nu de Colmi ring via Bluetooth: slaap met fasen, batterij altijd zichtbaar, Ring zoeken functie. En 7 dagen data ontgrendelen 6 maanden Pro gratis.",
    ja: "FitMesh SyncがColmiリングをBluetoothで読み取れるようになりました。睡眠ステージ、バッテリー常時表示、リングを探す機能。7日間のデータで6か月のProが無料になります。",
    ko: "FitMesh Sync가 이제 Bluetooth로 Colmi 링을 읽습니다. 수면 단계, 배터리 항상 표시, 링 찾기 기능. 7일간의 데이터로 6개월 Pro가 무료 제공됩니다.",
  },
  tldr: {
    it: [
      "L'anello Colmi si connette direttamente a FitMesh Sync via Bluetooth, senza passare per app intermediarie.",
      "Il sonno viene registrato con le fasi complete: profondo, REM e leggero, visibili nella dashboard.",
      "La batteria dell'anello appare sempre in evidenza e la funzione 'Trova anello' lo fa lampeggiare per identificarlo.",
      "Traguardo lancio: 7 giorni di dati reali dall'anello sbloccano 6 mesi di abbonamento Pro gratis.",
    ],
    en: [
      "The Colmi ring connects directly to FitMesh Sync via Bluetooth, no intermediate apps needed.",
      "Sleep is recorded with full stages: deep, REM and light, visible in the dashboard.",
      "Ring battery is always shown prominently and the Find ring feature makes it blink for easy identification.",
      "Launch milestone: 7 days of real data from the ring unlock 6 months of Pro subscription free.",
    ],
    es: [
      "El anillo Colmi se conecta directamente a FitMesh Sync por Bluetooth, sin necesidad de apps intermediarias.",
      "El sueño se registra con las fases completas: profundo, REM y ligero, visibles en el panel.",
      "La batería del anillo siempre aparece destacada y la función 'Encuentra tu anillo' lo hace parpadear para localizarlo.",
      "Hito de lanzamiento: 7 días de datos reales desde el anillo desbloquean 6 meses de suscripción Pro gratis.",
    ],
    de: [
      "Der Colmi Ring verbindet sich direkt mit FitMesh Sync per Bluetooth, ohne Zwischen-Apps.",
      "Der Schlaf wird mit vollständigen Schlafphasen erfasst: Tiefschlaf, REM und Leichtschlaf, sichtbar in der Dashboard.",
      "Der Akkustand des Rings wird immer prominent angezeigt und die Ring-orten-Funktion lässt ihn zur einfachen Identifizierung blinken.",
      "Launch-Meilenstein: 7 Tage echte Daten vom Ring schalten 6 Monate Pro-Abonnement kostenlos frei.",
    ],
    pt: [
      "O anel Colmi se conecta diretamente ao FitMesh Sync via Bluetooth, sem precisar de apps intermediários.",
      "O sono é registrado com fases completas: profundo, REM e leve, visíveis no painel.",
      "A bateria do anel é sempre exibida com destaque e a função Localizar anel faz ele piscar para fácil identificação.",
      "Marco de lançamento: 7 dias de dados reais do anel desbloqueiam 6 meses de assinatura Pro grátis.",
    ],
    fr: [
      "La bague Colmi se connecte directement à FitMesh Sync via Bluetooth, sans passer par des applications intermédiaires.",
      "Le sommeil est enregistré avec les phases complètes: profond, REM et léger, visibles dans le tableau de bord.",
      "Le niveau de batterie de la bague est toujours affiché en évidence et la fonction Localiser la bague la fait clignoter pour une identification facile.",
      "Jalon de lancement: 7 jours de données réelles depuis la bague débloquent 6 mois d'abonnement Pro gratuit.",
    ],
    pl: [
      "Anell Colmi się połącza bezpośrednio z FitMesh Sync poprzez Bluetooth, bez przechodzenia przez intermedialne aplikacje.",
      "S:numel seno viene zarejestrowany ze wszystkimi fazami: głębokim, REM i lekkim, widocznych w panelu dashborду.",
      "Bateria pierścienia jest zawsze widoczna w aplikacji, a funkcja 'Znajdź pierścień' sprawia, że miga, aby łatwiej go zidentyfikować.",
      "Cel premiery: 7 dni rzeczywistych danych z pierścienia odblokowuje 6 miesięcy bezpłatnego Pro.",
    ],
    tr: [
      "Anel Colmi doğrudan FitMesh Sync'a Bluetooth üzerinden bağlanır, orta uygulamaları atlayarak.",
      "Uyku tam fasilere kadar kaydedilir: derin, REM ve hafif, panelde görünür hale getirilebilir.",
      "Günlük kullanımda aleykseen aleykseen, 'Aleykseen Bul' özelliği bu cihazı ışıklandırarak tespit edilmesini sağlar.",
      "Trageteddi açılış: 7 gün gerçek veri anelinden 6 ay Pro aboneliği ücretsiz çıkar.",
    ],
    nl: [
      "De Colmi ring verbindt rechtstreeks met FitMesh Sync via Bluetooth, zonder tussenliggende apps.",
      "Slaap wordt geregistreerd met volledige fasen: diep, REM en licht, zichtbaar in het dashboard.",
      "Het batterijniveau van de ring is altijd prominent zichtbaar en de Ring zoeken functie laat hem knipperen voor eenvoudige identificatie.",
      "Lanceringsmijlpaal: 7 dagen echte gegevens van de ring ontgrendelen 6 maanden Pro-abonnement gratis.",
    ],
    ja: [
      "ColmiリングはBluetoothでFitMesh Syncに直接接続します。中間アプリは不要です。",
      "睡眠はすべてのステージ（深い睡眠、REM、浅い睡眠）で記録され、ダッシュボードで確認できます。",
      "リングのバッテリー残量は常に目立つ位置に表示され、リングを探す機能で数秒間点滅させて見つけられます。",
      "ローンチ達成条件：リングから7日間の実データでProサブスクリプション6か月が無料になります。",
    ],
    ko: [
      "Colmi 링은 Bluetooth를 통해 FitMesh Sync에 직접 연결됩니다. 중간 앱이 필요 없습니다.",
      "수면은 깊은 수면, REM, 얕은 수면의 전체 단계로 기록되어 대시보드에서 확인할 수 있습니다.",
      "링의 배터리 잔량이 항상 눈에 띄게 표시되며, 링 찾기 기능으로 몇 초간 깜빡여 쉽게 찾을 수 있습니다.",
      "출시 마일스톤: 링에서 7일간의 실제 데이터를 기록하면 6개월 Pro 구독이 무료로 제공됩니다.",
    ],
  },
  hero: {
    kicker: {
      it: "Novità",
      en: "What's New",
      es: "Novedades",
      de: "Neuigkeiten",
      pt: "Novidades",
      fr: "Nouveautés",
      pl: "Nowości",
      tr: "Yeni Özellikler",
      nl: "Nieuw",
      ja: "新着情報",
      ko: "새 소식",
    },
    title: {
      it: "L'anello Colmi entra in FitMesh Sync: sonno, batteria e Trova anello",
      en: "Colmi ring joins FitMesh Sync: sleep stages, battery, and Find ring",
      es: "El anillo Colmi llega a FitMesh Sync: fases del sueño, batería y Encuentra tu anillo",
      de: "Der Colmi Ring kommt zu FitMesh Sync: Schlafphasen, Akku und Ring orten",
      pt: "O anel Colmi chega ao FitMesh Sync: fases do sono, bateria e Localizar anel",
      fr: "La bague Colmi rejoint FitMesh Sync: phases du sommeil, batterie et Localiser la bague",
      pl: "Anellito Colmi wchodzi w FitMesh Sync: sen, akumulator i Znajdź anellito",
      tr: "Anneli Colmi KVKK'ye girdi: uyku, bateri ve Anneli Bulma",
      nl: "Colmi ring in FitMesh Sync: slaapfasen, batterij en Ring zoeken",
      ja: "ColmiリングがFitMesh Syncに登場：睡眠ステージ、バッテリー、リングを探す",
      ko: "Colmi 링이 FitMesh Sync에 합류: 수면 단계, 배터리, 링 찾기",
    },
    subtitle: {
      it: "Con l'ultimo aggiornamento, FitMesh Sync legge direttamente l'anello Colmi: fasi del sonno complete, batteria sempre sotto controllo, e una funzione per trovarlo quando lo metti da qualche parte. Piu un traguardo speciale per chi inizia subito.",
      en: "With the latest update, FitMesh Sync reads the Colmi ring directly: full sleep stages, battery always in sight, and a feature to locate it when you put it down somewhere. Plus a special milestone for those who start right away.",
      es: "Con la última actualización, FitMesh Sync lee directamente el anillo Colmi: fases del sueño completas, batería siempre a la vista y una función para encontrarlo cuando lo dejas en algún lugar. Además, un hito especial para quienes empiezan ahora.",
      de: "Mit dem neuesten Update liest FitMesh Sync den Colmi Ring direkt: vollständige Schlafphasen, Akku immer im Blick und eine Funktion, um ihn zu orten, wenn man ihn irgendwo hingelegt hat. Dazu ein besonderer Meilenstein für alle, die sofort loslegen.",
      pt: "Com a última atualização, FitMesh Sync lê o anel Colmi diretamente: fases do sono completas, bateria sempre à vista e uma função para localizá-lo quando você o colocar em algum lugar. Além disso, um marco especial para quem começar agora.",
      fr: "Avec la dernière mise à jour, FitMesh Sync lit directement la bague Colmi: phases du sommeil complètes, batterie toujours sous contrôle et une fonction pour la localiser quand vous la posez quelque part. Plus un jalon spécial pour ceux qui démarrent tout de suite.",
      pl: "Za ostatnie aktualizacje, FitMesh Sync czyta bezpośrednio anell Colmi: pełne fazy senu, akumulator zawsze pod kontrolą, oraz funkcja pozwalająca znaleźć go, gdy go gdzieś położyłeś. Specjalne nagradzamy tych, którzy się zaczynają od razu.",
      tr: "Son laatımla FitMesh Sync direkt olarak Colmi okuyor: tam uyku fasları, pil her zaman izleniyor ve bir bulma özelliği var ki nereye koyduğunuzda arıyorsunuz. Başlayanlar için özel bir hedef de var.",
      nl: "Met de nieuwste update leest FitMesh Sync de Colmi ring rechtstreeks: volledige slaapfasen, batterij altijd in beeld en een functie om de ring te vinden als je hem ergens neerlegt. Plus een speciale mijlpaal voor wie meteen begint.",
      ja: "最新アップデートで、FitMesh SyncがColmiリングを直接読み取れるようになりました。完全な睡眠ステージ、バッテリー常時表示、どこかに置いたときに見つけるための機能。すぐに始める方への特別な達成条件もあります。",
      ko: "최신 업데이트로 FitMesh Sync가 Colmi 링을 직접 읽습니다. 전체 수면 단계, 배터리 항상 표시, 어딘가에 내려놓았을 때 찾을 수 있는 기능. 바로 시작하는 분들을 위한 특별 마일스톤도 있습니다.",
    },
  },
  body: [
    {
      type: "paragraph",
      text: {
        it: "Noi di FitMesh Sync abbiamo lavorato a lungo su questa integrazione, e oggi e pronta. L'anello Colmi si connette direttamente all'app via Bluetooth: niente app di terze parti nel mezzo, niente passaggi manuali. Una volta abbinato, l'anello porta i suoi dati nella stessa dashboard dove gia vivono i dati del tuo smartwatch.",
        en: "We at FitMesh Sync have worked on this integration for a long time, and today it is ready. The Colmi ring connects directly to the app via Bluetooth: no third-party apps in between, no manual steps. Once paired, the ring brings its data into the same dashboard where your smartwatch data already lives.",
        es: "En FitMesh Sync hemos trabajado durante mucho tiempo en esta integración, y hoy está lista. El anillo Colmi se conecta directamente a la app por Bluetooth: sin apps de terceros en el medio, sin pasos manuales. Una vez vinculado, el anillo lleva sus datos al mismo panel donde ya viven los datos de tu smartwatch.",
        de: "Wir bei FitMesh Sync haben lange an dieser Integration gearbeitet, und heute ist sie bereit. Der Colmi Ring verbindet sich direkt mit der App per Bluetooth: keine Drittanbieter-Apps dazwischen, keine manuellen Schritte. Nach der Kopplung bringt der Ring seine Daten in dieselbe Dashboard, in der bereits die Daten deines Smartwatch liegen.",
        pt: "Nós do FitMesh Sync trabalhamos muito tempo nessa integração e hoje ela está pronta. O anel Colmi se conecta diretamente ao app via Bluetooth: sem apps de terceiros no meio, sem etapas manuais. Após o pareamento, o anel traz seus dados para o mesmo painel onde já estão os dados do seu smartwatch.",
        fr: "Chez FitMesh Sync, nous avons travaillé longtemps sur cette intégration, et aujourd'hui elle est prête. La bague Colmi se connecte directement à l'application via Bluetooth: pas d'applications tierces au milieu, pas d'étapes manuelles. Une fois couplée, la bague apporte ses données dans le même tableau de bord où vivent déjà les données de votre montre connectée.",
        pl: "Mamy na FitMesh Sync pracowali długie miesiące nad tą integracją, a dzisiaj jest gotowa. Pierścień Colmi łączy się bezpośrednio z aplikacją poprzez Bluetooth: żadnych dodatkowych aplikacji trzecich w middle, żadnych ręcznych kroków. Po połączeniu pierścień przekazuje Twoje dane do tej samej panelu zarządzania, gdzie już leżą dane z Twojego smartwatcha.",
        tr: "Biz FitMesh Sync adımlarla bu entegrasyonu geliştirdik ve bugün hazır. Colmi halkası, Bluetooth: arayüze üçüncü taraf uygulaması veya manuel adımlar yok aracılığıyla doğrudan uygulamaya bağlanır. Bir kez eşleştirildikten sonra, halka verilerinizi zaten akıllı saatinizdeki aynı panelde bulunan verilere taşıyacaktır.",
        nl: "Wij bij FitMesh Sync hebben lang aan deze integratie gewerkt, en vandaag is hij klaar. De Colmi ring verbindt rechtstreeks met de app via Bluetooth: geen apps van derden tussendoor, geen handmatige stappen. Eenmaal gekoppeld brengt de ring zijn gegevens naar hetzelfde dashboard waar al je smartwatch-gegevens leven.",
        ja: "FitMesh Syncチームはこの統合に長い時間をかけて取り組み、今日ついに完成しました。ColmiリングはBluetoothでアプリに直接接続します。サードパーティのアプリも手動の手順も不要です。一度ペアリングすれば、リングのデータはスマートウォッチのデータと同じダッシュボードに表示されます。",
        ko: "FitMesh Sync 팀은 이 통합을 위해 오랫동안 작업해 왔으며, 오늘 드디어 완성되었습니다. Colmi 링은 Bluetooth를 통해 앱에 직접 연결됩니다. 중간에 서드파티 앱도, 수동 단계도 필요 없습니다. 한 번 페어링하면 링의 데이터가 스마트워치 데이터가 이미 있는 동일한 대시보드에 표시됩니다.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Sonno con fasi: profondo, REM e leggero",
        en: "Sleep with stages: deep, REM and light",
        es: "Sueño con fases: profundo, REM y ligero",
        de: "Schlaf mit Phasen: Tiefschlaf, REM und Leichtschlaf",
        pt: "Sono com fases: profundo, REM e leve",
        fr: "Sommeil avec phases: profond, REM et léger",
        pl: "Snytanie z fazami: głęboka, REM i lekka",
        tr: "Uyum fasları: derin, REM ve hafif uyku",
        nl: "Slaap met fasen: diep, REM en licht",
        ja: "睡眠ステージ：深い睡眠、REM、浅い睡眠",
        ko: "수면 단계: 깊은 수면, REM, 얕은 수면",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Il dato piu richiesto era il sonno dettagliato, e l'anello Colmi lo porta con tre livelli: sonno profondo, REM e leggero. Ogni mattina trovi nella dashboard la suddivisione completa della notte, con i minuti per ciascuna fase. I dati si integrano con quelli degli altri dispositivi collegati senza doppi conteggi: se indossi anche uno smartwatch, FitMesh Sync tiene il valore migliore e non somma erroneamente le stesse ore.",
        en: "The most requested data point was detailed sleep, and the Colmi ring delivers it with three levels: deep, REM and light sleep. Every morning you find a complete breakdown of the night in the dashboard, with minutes for each stage. The data integrates with those from other connected devices without double counting: if you also wear a smartwatch, FitMesh Sync keeps the best value and does not erroneously sum the same hours.",
        es: "El dato más solicitado era el sueño detallado, y el anillo Colmi lo aporta con tres niveles: sueño profundo, REM y ligero. Cada mañana encuentras en el panel el desglose completo de la noche, con los minutos de cada fase. Los datos se integran con los de los demás dispositivos conectados sin duplicaciones: si también llevas un smartwatch, FitMesh Sync conserva el mejor valor y no suma erróneamente las mismas horas.",
        de: "Der am häufigsten gewünschte Datenpunkt war der detaillierte Schlaf, und der Colmi Ring liefert ihn mit drei Stufen: Tiefschlaf, REM und Leichtschlaf. Jeden Morgen findest du in der Dashboard die vollständige Aufschlüsselung der Nacht, mit den Minuten für jede Phase. Die Daten integrieren sich mit denen anderer verbundener Geräte ohne Doppelzählung: Wenn du auch einen Smartwatch trägst, behält FitMesh Sync den besten Wert und addiert nicht fälschlicherweise dieselben Stunden.",
        pt: "O dado mais solicitado era o sono detalhado, e o anel Colmi o entrega com três níveis: sono profundo, REM e leve. Toda manhã você encontra no painel o detalhamento completo da noite, com os minutos de cada fase. Os dados se integram com os de outros dispositivos conectados sem duplicações: se você também usa um smartwatch, FitMesh Sync mantém o melhor valor e não soma erroneamente as mesmas horas.",
        fr: "La donnée la plus demandée était le sommeil détaillé, et la bague Colmi le fournit avec trois niveaux: sommeil profond, REM et léger. Chaque matin, vous trouvez dans le tableau de bord la répartition complète de la nuit, avec les minutes pour chaque phase. Les données s'intègrent avec celles des autres appareils connectés sans double comptage: si vous portez aussi une montre connectée, FitMesh Sync conserve la meilleure valeur et n'additionne pas par erreur les mêmes heures.",
        pl: "Najczęściej proszony był szczegółowy sen, a pęczek Colmi dostarcza go na trzech poziomach: sen głęboki, REM i lżejszy. Każdego ranka w panelu widokowym znajdziesz pełną podziałkę nocy, z minutami dla każdej fazы. Dane integrują się z innymi urządzeniami połączonego sprzętu bez powtarzania liczenia: jeśli nosisz również smartwatch, FitMesh Sync przechowuje najlepsze wartości i nie sumuje błędnie tych samych godzin.",
        tr: "Ensembledatum ist am häufigsten gefragt und wird vom Ring Colmi in drei Stufen angeboten: tiefes Schlafphasen, REM und leichtes Schlafphasen. Jeden Morgen findest du in der Dashboard die vollständige Aufteilung der Nacht, mit den Minuten für jede Phase. Die Daten integrieren sich mit denen anderer verbundener Geräte ohne Doppeltage: Wenn du auch einen akıllı saat FitMesh Sync trägst, hält es das beste Wert und fügt nicht falsch die gleichen Stunden hinzu.",
        nl: "Het meest gevraagde gegeven was gedetailleerde slaap, en de Colmi ring levert dat met drie niveaus: diepe slaap, REM en lichte slaap. Elke ochtend vind je in het dashboard een volledige uitsplitsing van de nacht, met minuten per fase. De gegevens worden geintegreerd met die van andere verbonden apparaten zonder dubbeltelling: als je ook een smartwatch draagt, behoudt FitMesh Sync de beste waarde en telt dezelfde uren niet foutief op.",
        ja: "最も要望の多かったのは詳細な睡眠データで、Colmiリングは3つのレベルで提供します。深い睡眠、REM、浅い睡眠です。毎朝ダッシュボードで夜間の完全な内訳を各ステージの分数とともに確認できます。他の接続デバイスのデータと二重カウントなしで統合されます。スマートウォッチも装着している場合、FitMesh Syncは最も詳細な値を保持し、同じ時間を誤って合算しません。",
        ko: "가장 많이 요청된 데이터는 상세한 수면이었으며, Colmi 링은 깊은 수면, REM, 얕은 수면의 세 가지 레벨로 제공합니다. 매일 아침 대시보드에서 각 단계별 분 단위로 밤 전체의 분석을 확인할 수 있습니다. 데이터는 이중 계산 없이 다른 연결 기기의 데이터와 통합됩니다. 스마트워치도 착용하는 경우 FitMesh Sync는 가장 상세한 값을 유지하며 동일한 시간을 잘못 합산하지 않습니다.",
      },
    },
    {
      type: "callout",
      variant: "info",
      title: {
        it: "Vuoi sapere come configurare l'anello al meglio?",
        en: "Want to know how to set up the ring optimally?",
        es: "¿Quieres saber cómo configurar el anillo de la mejor manera?",
        de: "Möchtest du wissen, wie du den Ring optimal einrichtest?",
        pt: "Quer saber como configurar o anel da melhor forma?",
        fr: "Vous voulez savoir comment configurer la bague de façon optimale?",
        pl: "Czy chcesz wiedzieć, jak najlepiej skonfigurować anellito?",
        tr: "İstediğiniz gibi anelini en iyi şekilde ayarlamak istiyor musunuz?",
        nl: "Wil je weten hoe je de ring optimaal instelt?",
        ja: "リングを最適にセットアップする方法を知りたいですか？",
        ko: "링을 최적으로 설정하는 방법을 알고 싶으신가요?",
      },
      body: {
        it: "Abbiamo scritto una [guida completa all'anello Colmi](/it/blog/colmi-ring-fitmesh) che copre abbinamento, permessi, risoluzione dei problemi piu comuni e consigli sul porto dell'anello per la migliore qualita del dato.",
        en: "We have written a [full Colmi ring guide](/en/blog/colmi-ring-fitmesh) that covers pairing, permissions, solving the most common issues, and tips on wearing the ring for the best data quality.",
        es: "Hemos escrito una [guía completa del anillo Colmi](/es/blog/colmi-ring-fitmesh) que cubre el emparejamiento, los permisos, la solución de los problemas más comunes y consejos sobre cómo llevar el anillo para obtener la mejor calidad de datos.",
        de: "Wir haben einen [vollständigen Leitfaden zum Colmi Ring](/de/blog/colmi-ring-fitmesh) verfasst, der Kopplung, Berechtigungen, Lösung der häufigsten Probleme und Tipps zum Tragen des Rings für die beste Datenqualität abdeckt.",
        pt: "Escrevemos um [guia completo do anel Colmi](/pt/blog/colmi-ring-fitmesh) que cobre pareamento, permissões, resolução dos problemas mais comuns e dicas sobre como usar o anel para obter a melhor qualidade de dados.",
        fr: "Nous avons rédigé un [guide complet de la bague Colmi](/fr/blog/colmi-ring-fitmesh) qui couvre le couplage, les autorisations, la résolution des problèmes les plus courants et des conseils sur le port de la bague pour la meilleure qualité de données.",
        pl: "Napisaliśmy pełny [przewodnik po pierścieniu Colmi](/pl/blog/colmi-ring-dane-panel) obejmujący parowanie, uprawnienia, rozwiązywanie najczęstszych problemów oraz wskazówki dotyczące noszenia pierścienia dla najlepszej jakości danych.",
        tr: "Parowanie, izinler, en sık karşılaşılan sorunların çözümü ve en iyi veri kalitesi için yüzüğü takma ipuçlarını kapsayan bir [Colmi yüzük tam rehberi](/tr/blog/colmi-ring-veri-panosu) yazdık.",
        nl: "We hebben een [volledige Colmi ring gids](/nl/blog/colmi-ring-fitmesh) geschreven die koppeling, machtigingen, het oplossen van de meest voorkomende problemen en tips over het dragen van de ring voor de beste gegevenskwaliteit behandelt.",
        ja: "ペアリング、権限、よくある問題の解決方法、最高のデータ品質を得るためのリングの装着のコツをまとめた[Colmiリング完全ガイド](/ja/blog/colmi-ring-fitmesh)を作成しました。",
        ko: "페어링, 권한, 가장 흔한 문제 해결 방법, 최상의 데이터 품질을 위한 링 착용 팁을 다룬 [Colmi 링 완전 가이드](/ko/blog/colmi-ring-fitmesh)를 작성했습니다.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Tre novita pratiche nell'app",
        en: "Three practical new features in the app",
        es: "Tres novedades prácticas en la app",
        de: "Drei praktische neue Funktionen in der App",
        pt: "Três novidades práticas no app",
        fr: "Trois nouvelles fonctionnalités pratiques dans l'application",
        pl: "Trzy nowe praktyczne funkcje w app",
        tr: "Yeni üç praktik ekran uygulaması",
        nl: "Drie praktische nieuwe functies in de app",
        ja: "アプリの3つの実用的な新機能",
        ko: "앱의 세 가지 실용적인 새 기능",
      },
    },
    {
      type: "list",
      items: {
        it: [
          "**Batteria sempre visibile.** Il livello di carica dell'anello compare nella schermata principale: non devi aprire nessuna app separata per sapere quando e ora di caricarlo.",
          "**Trova anello.** Hai messo giu l'anello e non lo trovi? Un tocco nell'app lo fa lampeggiare per qualche secondo, cosi lo individui subito.",
          "**Nessun doppio conteggio.** L'anello si aggiunge alle sorgenti gia presenti, ma FitMesh Sync gestisce le sovrapposizioni: ogni metrica viene contata una volta sola, con la fonte piu precisa disponibile.",
        ],
        en: [
          "**Battery always visible.** The ring charge level appears on the main screen: you do not need to open any separate app to know when it is time to charge.",
          "**Find ring.** Did you put the ring down and cannot find it? One tap in the app makes it blink for a few seconds so you locate it right away.",
          "**No double counting.** The ring is added to already-present sources, but FitMesh Sync handles overlaps: each metric is counted only once, with the most accurate source available.",
        ],
        es: [
          "**Batería siempre visible.** El nivel de carga del anillo aparece en la pantalla principal: no necesitas abrir ninguna app aparte para saber cuándo es hora de cargarlo.",
          "**Encuentra tu anillo.** ¿Dejaste el anillo en algún lugar y no lo encuentras? Un toque en la app lo hace parpadear unos segundos para que lo localices de inmediato.",
          "**Sin duplicación de datos.** El anillo se suma a las fuentes ya existentes, pero FitMesh Sync gestiona las superposiciones: cada métrica se cuenta una sola vez, con la fuente más precisa disponible.",
        ],
        de: [
          "**Akkustand immer sichtbar.** Der Ladestand des Rings erscheint auf dem Hauptbildschirm: Du musst keine separate App öffnen, um zu wissen, wann es Zeit zum Laden ist.",
          "**Ring orten.** Hast du den Ring irgendwo hingelegt und findest ihn nicht mehr? Ein Tippen in der App lässt ihn für einige Sekunden blinken, damit du ihn sofort findest.",
          "**Keine Doppelzählung.** Der Ring wird zu den bereits vorhandenen Quellen hinzugefügt, aber FitMesh Sync verwaltet Überschneidungen: Jede Metrik wird nur einmal gezählt, mit der präzisesten verfügbaren Quelle.",
        ],
        pt: [
          "**Bateria sempre visível.** O nível de carga do anel aparece na tela principal: você não precisa abrir nenhum app separado para saber quando é hora de carregá-lo.",
          "**Localizar anel.** Você colocou o anel em algum lugar e não consegue encontrá-lo? Um toque no app faz ele piscar por alguns segundos para você localizá-lo imediatamente.",
          "**Sem duplicação de dados.** O anel é adicionado às fontes já existentes, mas FitMesh Sync gerencia as sobreposições: cada métrica é contada apenas uma vez, com a fonte mais precisa disponível.",
        ],
        fr: [
          "**Batterie toujours visible.** Le niveau de charge de la bague apparaît sur l'écran principal: vous n'avez pas besoin d'ouvrir une application séparée pour savoir quand il est temps de la recharger.",
          "**Localiser la bague.** Vous avez posé la bague quelque part et vous ne la trouvez pas? Un simple appui dans l'application la fait clignoter pendant quelques secondes pour la repérer immédiatement.",
          "**Pas de double comptage.** La bague s'ajoute aux sources déjà présentes, mais FitMesh Sync gère les chevauchements: chaque métrique n'est comptée qu'une seule fois, avec la source la plus précise disponible.",
        ],
        pl: [
          "**Zawsze widoczna bateria.** Poziom naładowania anelku pojawia się na głównym ekranie: nie musisz otworzyć żadnej oddzielnej aplikacji, aby wiedzieć kiedy i jak często go naładować.",
          "**Znajdź pęczek.** Zsunąłeś pęczek i nie go znajdziesz? Nacisk na aplikację sprawia, że się chwyci za światło przez kilka sekund, dzięki czemu natychmiast go zauważysz.",
          "**Nie podwójny licznik.** Pierścień dodaje się do już istniejących źródeł, ale FitMesh Sync zarządza połączeniami: każda metryka jest zliczona tylko raz, korzystając z najbardziej precyzyjnego źródła dostępного.",
        ],
        tr: [
          "**Şarj her zaman görünür.** Döngü seviyesi şeridan ana ekranında görünür: her zaman ayrı bir uygulama açmamanız gerekmez, ne ve ne zaman şarj edileceği konusunda bilgi almanıza.",
          "**Bul Eşya.** Eşyanızı düşürdünüz ve bulamıyorsunuz? Uygulamada bir tık vererek birkaç saniye ışıltılı olacak ve hemen bulacaksınız.",
          "**Hiç çift sayım.** Anelit eklenir zaten mevcut kaynaklara, ancak FitMesh Sync çakışmaları yönetir: her metrik sadece en hassas kaynağıyla bir kez sayılır.",
        ],
        nl: [
          "**Batterij altijd zichtbaar.** Het laadniveau van de ring verschijnt op het hoofdscherm: je hoeft geen aparte app te openen om te weten wanneer het tijd is om op te laden.",
          "**Ring zoeken.** Heb je de ring neergelegd en kun je hem niet vinden? Een tik in de app laat hem enkele seconden knipperen zodat je hem meteen vindt.",
          "**Geen dubbeltelling.** De ring wordt toegevoegd aan al aanwezige bronnen, maar FitMesh Sync beheert overlappen: elke meting wordt slechts eenmaal geteld, met de meest nauwkeurige beschikbare bron.",
        ],
        ja: [
          "**バッテリー常時表示。** リングの充電残量がメイン画面に表示されます。充電時期を確認するために別のアプリを開く必要はありません。",
          "**リングを探す。** リングをどこかに置いて見つからない？アプリでワンタップすると数秒間点滅するので、すぐに見つけられます。",
          "**二重カウントなし。** リングは既存のソースに追加されますが、FitMesh Syncは重複を管理します。各指標は最も精度の高いソースで一度だけカウントされます。",
        ],
        ko: [
          "**배터리 항상 표시.** 링의 충전 잔량이 메인 화면에 표시됩니다. 언제 충전해야 하는지 알기 위해 별도의 앱을 열 필요가 없습니다.",
          "**링 찾기.** 링을 어딘가에 내려놓고 찾을 수 없나요? 앱에서 한 번 탭하면 몇 초간 깜빡여서 바로 찾을 수 있습니다.",
          "**이중 계산 없음.** 링은 이미 존재하는 소스에 추가되지만 FitMesh Sync가 중복을 관리합니다. 각 지표는 가장 정확한 소스로 한 번만 계산됩니다.",
        ],
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Traguardo lancio: 7 giorni di dati reali, 6 mesi di Pro gratis",
        en: "Launch milestone: 7 days of real data, 6 months of Pro free",
        es: "Hito de lanzamiento: 7 días de datos reales, 6 meses de Pro gratis",
        de: "Launch-Meilenstein: 7 Tage echte Daten, 6 Monate Pro kostenlos",
        pt: "Marco de lançamento: 7 dias de dados reais, 6 meses de Pro grátis",
        fr: "Jalon de lancement: 7 jours de données réelles, 6 mois de Pro gratuit",
        pl: "Tragódrowy start: 7 dni rzeczywistych danych, 6 miesięcy Pro za darmo",
        tr: "Tragetediklik tarihi: 7 gün gerçek veri, 6 ay ücretsiz Pro",
        nl: "Lanceringsmijlpaal: 7 dagen echte gegevens, 6 maanden Pro gratis",
        ja: "ローンチ達成条件：7日間の実データ、6か月のPro無料",
        ko: "출시 마일스톤: 7일간의 실제 데이터, 6개월 Pro 무료",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Per celebrare il lancio abbiamo aggiunto un traguardo speciale: collega l'anello Colmi e registra 7 giorni consecutivi di dati reali nell'app. Quando raggiungi il traguardo, sblocchi automaticamente 6 mesi di abbonamento Pro senza costi. L'offerta e valida per chi attiva la connessione con l'anello entro il periodo di lancio.",
        en: "To celebrate the launch we have added a special milestone: connect the Colmi ring and record 7 consecutive days of real data in the app. When you reach the milestone, you automatically unlock 6 months of Pro subscription at no cost. The offer is valid for those who activate the ring connection within the launch period.",
        es: "Para celebrar el lanzamiento hemos añadido un hito especial: conecta el anillo Colmi y registra 7 días consecutivos de datos reales en la app. Cuando alcances el hito, desbloqueas automáticamente 6 meses de suscripción Pro sin coste. La oferta es válida para quienes activen la conexión con el anillo dentro del período de lanzamiento.",
        de: "Zur Feier des Launches haben wir einen besonderen Meilenstein hinzugefügt: Verbinde den Colmi Ring und erfasse 7 aufeinanderfolgende Tage echte Daten in der App. Wenn du den Meilenstein erreichst, schaltest du automatisch 6 Monate Pro-Abonnement kostenlos frei. Das Angebot gilt für alle, die die Ring-Verbindung innerhalb des Launch-Zeitraums aktivieren.",
        pt: "Para celebrar o lançamento, adicionamos um marco especial: conecte o anel Colmi e registre 7 dias consecutivos de dados reais no app. Quando você atingir o marco, desbloqueará automaticamente 6 meses de assinatura Pro sem custo. A oferta é válida para quem ativar a conexão com o anel dentro do período de lançamento.",
        fr: "Pour célébrer le lancement, nous avons ajouté un jalon spécial: connectez la bague Colmi et enregistrez 7 jours consécutifs de données réelles dans l'application. Lorsque vous atteignez le jalon, vous débloquez automatiquement 6 mois d'abonnement Pro sans frais. L'offre est valable pour ceux qui activent la connexion avec la bague dans la période de lancement.",
        pl: "Aby z.ToShortCut() zaczerpnąć sukces, dodaliśmy specjalny cel: podłącz łańcuch Colmi i zapisz 7 kolejnych dni rzeczywistych danych w aplikacji. Gdy osiągniesz cel, automatycznie odblokujesz 6 miesięcy abonamentu Pro bez kosztów. Oferta jest dostępna dla tych, którzy aktywowają połączenie z łańcuchem podczas okresu startu.",
        tr: "KVKK uyumluluğunu kutlamak için özel bir hedef eklendı: Colmi halkasını bağlayıp uygulamada 7 günlük ardıl gerçek veri kaydını yap. Hedefi ulaştığınızda, otomatik olarak 6 ay Pro aboneliği alabilirsiniz ve ücret ödemeye gerek yok. Teknik olarak uygulamayı bağlamak için Colmi halkasıyla bağlantı kurulan kişi KVKK uyumluluğu süre zarfı içinde etkin olmalıdır.",
        nl: "Om de lancering te vieren hebben we een speciale mijlpaal toegevoegd: verbind de Colmi ring en registreer 7 opeenvolgende dagen echte gegevens in de app. Als je de mijlpaal bereikt, ontgrendel je automatisch 6 maanden Pro-abonnement zonder kosten. Het aanbod is geldig voor wie de ringverbinding activeert binnen de lanceringsperiode.",
        ja: "ローンチを祝うために特別な達成条件を追加しました。Colmiリングを接続してアプリに7日間連続の実データを記録してください。達成条件を満たすと、自動的に6か月のProサブスクリプションが無料になります。このオファーはローンチ期間内にリング接続を有効にした方が対象です。",
        ko: "출시를 기념하여 특별 마일스톤을 추가했습니다. Colmi 링을 연결하고 앱에 7일 연속 실제 데이터를 기록하세요. 마일스톤을 달성하면 자동으로 6개월 Pro 구독이 무료로 제공됩니다. 출시 기간 내에 링 연결을 활성화한 분들에게 유효한 혜택입니다.",
      },
    },
    {
      type: "callout",
      variant: "tip",
      title: {
        it: "Come funziona il conteggio dei 7 giorni",
        en: "How the 7-day count works",
        es: "Cómo funciona el conteo de los 7 días",
        de: "Wie die 7-Tage-Zählung funktioniert",
        pt: "Como funciona a contagem dos 7 dias",
        fr: "Comment fonctionne le décompte des 7 jours",
        pl: "Jak działa liczenie 7 dni",
        tr: "7 günlük sayımı nasıl çalışır",
        nl: "Hoe de 7-daagse telling werkt",
        ja: "7日間のカウントの仕組み",
        ko: "7일 카운트 작동 방식",
      },
      body: {
        it: "Servono 7 giorni con almeno un dato registrato dall'anello Colmi, non necessariamente consecutivi nella stessa settimana. L'app mostra il progresso nel pannello Traguardi. Ai 7 giorni, il Pro si attiva in automatico senza che tu faccia nulla.",
        en: "You need 7 days with at least one data point recorded from the Colmi ring, not necessarily consecutive in the same week. The app shows progress in the Milestones panel. At 7 days, Pro activates automatically without any action on your part.",
        es: "Necesitas 7 días con al menos un dato registrado desde el anillo Colmi, no necesariamente consecutivos en la misma semana. La app muestra el progreso en el panel de Hitos. Al llegar a los 7 días, el Pro se activa automáticamente sin que tengas que hacer nada.",
        de: "Du brauchst 7 Tage mit mindestens einem aufgezeichneten Datenpunkt vom Colmi Ring, nicht notwendigerweise aufeinanderfolgend in derselben Woche. Die App zeigt den Fortschritt im Meilenstein-Panel. Nach 7 Tagen aktiviert sich Pro automatisch, ohne dass du etwas tun musst.",
        pt: "Você precisa de 7 dias com pelo menos um dado registrado pelo anel Colmi, não necessariamente consecutivos na mesma semana. O app mostra o progresso no painel de Marcos. Ao completar os 7 dias, o Pro é ativado automaticamente sem que você precise fazer nada.",
        fr: "Il vous faut 7 jours avec au moins un point de données enregistré par la bague Colmi, pas nécessairement consécutifs dans la même semaine. L'application affiche la progression dans le panneau Jalons. Au bout de 7 jours, le Pro s'active automatiquement sans aucune action de votre part.",
        pl: "Trzeba 7 dni z przynajmniej jednym zapisanym danym z anella Colmi, niekoniecznie kolejnych w tej samej tygodniu. Aplikacja pokazuje postęp na panelu Cel. Po 7 dniach, Pro aktywuje się automatycznie bez twoich działań.",
        tr: "Gereksiz olarak aynı hafta boyunca süren ve ardışık olmayan en az bir veri kaydeden Colmi ile 7 gün gereklidir. Uygulama Hedefler panelinde ilerlemeyi gösterir. 7 gün tamamlandığında, Pro otomatik olarak aktif olur ve senin herhangi bir eylemi yapmanı gerektirmese de.",
        nl: "Je hebt 7 dagen nodig met minimaal een geregistreerd datapunt van de Colmi ring, niet per se aaneengesloten in dezelfde week. De app toont de voortgang in het Mijlpalen paneel. Na 7 dagen wordt Pro automatisch geactiveerd zonder dat je iets hoeft te doen.",
        ja: "同じ週に連続している必要はありませんが、Colmiリングから少なくとも1つのデータポイントが記録された7日間が必要です。アプリは達成条件パネルで進捗を表示します。7日間達成すると、何もしなくてもProが自動的に有効になります。",
        ko: "같은 주에 연속될 필요 없이 Colmi 링에서 최소 하나의 데이터 포인트가 기록된 7일이 필요합니다. 앱은 마일스톤 패널에서 진행 상황을 표시합니다. 7일이 완료되면 아무런 조치 없이 Pro가 자동으로 활성화됩니다.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Come iniziare",
        en: "How to get started",
        es: "Cómo empezar",
        de: "So fängst du an",
        pt: "Como começar",
        fr: "Comment démarrer",
        pl: "Jak zacząć",
        tr: "Başlamak Nasıl Başarılır",
        nl: "Hoe te beginnen",
        ja: "始め方",
        ko: "시작하는 방법",
      },
    },
    {
      type: "list",
      ordered: true,
      items: {
        it: [
          "Aggiorna FitMesh Sync all'ultima versione disponibile.",
          "Apri l'app e vai nella sezione Dispositivi.",
          "Tocca 'Aggiungi dispositivo' e scegli Anello Colmi dall'elenco.",
          "Segui le istruzioni di abbinamento Bluetooth: di solito bastano 30 secondi.",
          "I dati della notte precedente arrivano nella dashboard non appena la sincronizzazione e completata.",
        ],
        en: [
          "Update FitMesh Sync to the latest available version.",
          "Open the app and go to the Devices section.",
          "Tap 'Add device' and choose Colmi ring from the list.",
          "Follow the Bluetooth pairing instructions: usually takes 30 seconds.",
          "The previous night's data arrives in the dashboard as soon as synchronization is complete.",
        ],
        es: [
          "Actualiza FitMesh Sync a la última versión disponible.",
          "Abre la app y ve a la sección Dispositivos.",
          "Toca 'Añadir dispositivo' y elige Anillo Colmi de la lista.",
          "Sigue las instrucciones de emparejamiento Bluetooth: normalmente basta con 30 segundos.",
          "Los datos de la noche anterior llegan al panel en cuanto la sincronización se completa.",
        ],
        de: [
          "Aktualisiere FitMesh Sync auf die neueste verfügbare Version.",
          "Öffne die App und gehe zum Bereich Geräte.",
          "Tippe auf 'Gerät hinzufügen' und wähle Colmi Ring aus der Liste.",
          "Folge den Bluetooth-Kopplungsanweisungen: normalerweise dauert es 30 Sekunden.",
          "Die Daten der vorherigen Nacht erscheinen in der Dashboard, sobald die Synchronisierung abgeschlossen ist.",
        ],
        pt: [
          "Atualize FitMesh Sync para a versão mais recente disponível.",
          "Abra o app e vá para a seção Dispositivos.",
          "Toque em 'Adicionar dispositivo' e escolha Anel Colmi na lista.",
          "Siga as instruções de pareamento Bluetooth: normalmente leva 30 segundos.",
          "Os dados da noite anterior chegam ao painel assim que a sincronização é concluída.",
        ],
        fr: [
          "Mettez à jour FitMesh Sync vers la dernière version disponible.",
          "Ouvrez l'application et accédez à la section Appareils.",
          "Appuyez sur 'Ajouter un appareil' et choisissez Bague Colmi dans la liste.",
          "Suivez les instructions de couplage Bluetooth: cela prend généralement 30 secondes.",
          "Les données de la nuit précédente arrivent dans le tableau de bord dès que la synchronisation est terminée.",
        ],
        pl: [
          "Zaktualizuj FitMesh Sync do najnowszej dostępnej wersji.",
          "Otwórz aplikację i przejdź do sekcji Urządzenia.",
          "Dotknij 'Dodaj urządzenie' i wybierz Anellito Colmi z listy.",
          "Sledź instrukcje do dopasowania Bluetooth: zazwyczaj wystarczą 30 sekund.",
          "Dane z poprzedniej nocy pojawią się w panelu kontrolnym, jak tylko synchronizacja zostanie ukończona.",
        ],
        tr: [
          "Güncelle FitMesh Sync en son mevcut sürümü.",
          "Apl the app and go to the Devices section.",
          "Tıkla 'Cihaz Ekle' ve giyilebilir cihaz Colmi seçeneğini belirle.",
          "Uyumluluk kurulum girişi Bluetooth'a uygula: genellikle 30 saniye yeterli.",
          "Gecersiz gecen geceki veriler KVKK paneline sychronizasyon tamamlandığı anda gelir.",
        ],
        nl: [
          "Werk FitMesh Sync bij naar de nieuwste beschikbare versie.",
          "Open de app en ga naar de sectie Apparaten.",
          "Tik op 'Apparaat toevoegen' en kies Colmi ring uit de lijst.",
          "Volg de Bluetooth-koppelingsinstructies: meestal duurt het 30 seconden.",
          "De gegevens van de vorige nacht verschijnen in het dashboard zodra de synchronisatie is voltooid.",
        ],
        ja: [
          "FitMesh Syncを最新バージョンに更新してください。",
          "アプリを開き、デバイスセクションに移動します。",
          "「デバイスを追加」をタップし、リストからColmiリングを選択します。",
          "Bluetoothペアリング手順に従ってください。通常30秒かかります。",
          "同期が完了すると前夜のデータがダッシュボードに表示されます。",
        ],
        ko: [
          "FitMesh Sync를 최신 버전으로 업데이트하세요.",
          "앱을 열고 기기 섹션으로 이동합니다.",
          "'기기 추가'를 탭하고 목록에서 Colmi 링을 선택합니다.",
          "Bluetooth 페어링 지침을 따르세요. 보통 30초면 됩니다.",
          "동기화가 완료되는 즉시 전날 밤의 데이터가 대시보드에 표시됩니다.",
        ],
      },
    },
    {
      type: "cta",
      title: {
        it: "Prova FitMesh Sync con il tuo anello Colmi",
        en: "Try FitMesh Sync with your Colmi ring",
        es: "Prueba FitMesh Sync con tu anillo Colmi",
        de: "Probiere FitMesh Sync mit deinem Colmi Ring",
        pt: "Experimente FitMesh Sync com o seu anel Colmi",
        fr: "Essayez FitMesh Sync avec votre bague Colmi",
        pl: "Spróbuj FitMesh Sync z twoim łańcuchem Colmi",
        tr: "Denemeyi FitMesh Sync ile Colmi cihazınızla yapın.",
        nl: "Probeer FitMesh Sync met jouw Colmi ring",
        ja: "ColmiリングでFitMesh Syncを試す",
        ko: "Colmi 링으로 FitMesh Sync 체험하기",
      },
      body: {
        it: "Entra nella beta, collega l'anello e inizia a raccogliere i tuoi 7 giorni. Sei mesi di Pro ti aspettano.",
        en: "Join the beta, connect the ring, and start collecting your 7 days. Six months of Pro are waiting for you.",
        es: "Únete a la beta, conecta el anillo y empieza a acumular tus 7 días. Seis meses de Pro te esperan.",
        de: "Tritt der Beta bei, verbinde den Ring und beginne, deine 7 Tage zu sammeln. Sechs Monate Pro warten auf dich.",
        pt: "Entre na beta, conecte o anel e comece a acumular seus 7 dias. Seis meses de Pro estão esperando por você.",
        fr: "Rejoignez la bêta, connectez la bague et commencez à accumuler vos 7 jours. Six mois de Pro vous attendent.",
        pl: "Wejrzyj się do bêty, podłącz pasek i zacznij gromadzić swoje 7 dni. Sześć miesięcy Pro czekają na ciebie.",
        tr: "Beta'ya katıl, Colmi halkasını bağla ve 7 günlük verilerini toplamaya başla. Altı ay Pro seni bekliyor.",
        nl: "Doe mee met de beta, verbind de ring en begin je 7 dagen te verzamelen. Zes maanden Pro wachten op je.",
        ja: "ベータに参加して、リングを接続し、7日間のデータ収集を始めましょう。6か月分のProがあなたを待っています。",
        ko: "베타에 참여하고, 링을 연결하고, 7일간의 데이터 수집을 시작하세요. 6개월 Pro가 당신을 기다립니다.",
      },
      ctaLabel: {
        it: "Inizia la beta gratuita",
        en: "Start the free beta",
        es: "Empieza la beta gratuita",
        de: "Kostenlose Beta starten",
        pt: "Iniciar a beta gratuita",
        fr: "Démarrer la bêta gratuite",
        pl: "Zacznij bezpłatną betę",
        tr: "Başlat ücretsiz betanız",
        nl: "Start de gratis beta",
        ja: "無料ベータを開始する",
        ko: "무료 베타 시작하기",
      },
      ctaHref: {
        it: "/it/beta",
        en: "/en/beta",
      },
    },
  ],
  faq: [
    {
      q: {
        it: "L'anello Colmi funziona su iPhone o solo su Android?",
        en: "Does the Colmi ring work on iPhone or only on Android?",
        es: "¿El anillo Colmi funciona en iPhone o solo en Android?",
        de: "Funktioniert der Colmi Ring auf dem iPhone oder nur auf Android?",
        pt: "O anel Colmi funciona no iPhone ou apenas no Android?",
        fr: "La bague Colmi fonctionne-t-elle sur iPhone ou uniquement sur Android?",
        pl: "Anellito Colmi działa na iPhone lub tylko na Android?",
        tr: "Güneş tutku anlması Colmi sadece iPhone üzerinde mi çalışır yoksa Android üzerinde de mi?",
        nl: "Werkt de Colmi ring op iPhone of alleen op Android?",
        ja: "ColmiリングはiPhoneで動作しますか、それともAndroidのみですか？",
        ko: "Colmi 링은 iPhone에서 작동하나요, 아니면 Android에서만 작동하나요?",
      },
      a: {
        it: "FitMesh Sync con l'anello Colmi funziona su entrambe le piattaforme. Su Android i dati possono passare anche per Health Connect se preferisci. Su iPhone si integra con Apple Salute. La connessione Bluetooth diretta e disponibile su entrambi i sistemi.",
        en: "FitMesh Sync with the Colmi ring works on both platforms. On Android data can also go through Health Connect if you prefer. On iPhone it integrates with Apple Health. The direct Bluetooth connection is available on both systems.",
        es: "FitMesh Sync con el anillo Colmi funciona en ambas plataformas. En Android los datos también pueden pasar por Health Connect si lo prefieres. En iPhone se integra con Apple Health. La conexión Bluetooth directa está disponible en los dos sistemas.",
        de: "FitMesh Sync mit dem Colmi Ring funktioniert auf beiden Plattformen. Auf Android können die Daten auch über Health Connect gehen, wenn du das bevorzugst. Auf dem iPhone integriert es sich mit Apple Gesundheit. Die direkte Bluetooth-Verbindung ist auf beiden Systemen verfügbar.",
        pt: "FitMesh Sync com o anel Colmi funciona em ambas as plataformas. No Android os dados também podem passar pelo Health Connect se você preferir. No iPhone ele se integra com o Apple Saúde. A conexão Bluetooth direta está disponível nos dois sistemas.",
        fr: "FitMesh Sync avec la bague Colmi fonctionne sur les deux plateformes. Sur Android, les données peuvent également passer par Health Connect si vous préférez. Sur iPhone, il s'intègre avec Apple Santé. La connexion Bluetooth directe est disponible sur les deux systèmes.",
        pl: "FitMesh Sync z paszportem Colmi działa na obu platformach. Na Android dane mogą przepływać również przez Health Connect, jeśli preferujesz. Na iPhone integruje się z Apple Salute. Połączenie Bluetooth jest bezpośrednie i dostępne na obu systemach.",
        tr: "FitMesh Sync ile Colmi halkası, her iki platformda da çalışır. Android üzerinde verilerin Health Connect üzerinden de geçebilirsiniz eğer isterseniz. iPhone 'te ise Apple Sağlık ile entegre olabilir. Bağlantı Bluetooth doğrudan ve her iki sisteminde de mevcuttur.",
        nl: "FitMesh Sync met de Colmi ring werkt op beide platforms. Op Android kunnen gegevens ook via Health Connect gaan als je dat prefereert. Op iPhone integreert het met Apple Gezondheid. De directe Bluetooth-verbinding is beschikbaar op beide systemen.",
        ja: "ColmiリングとFitMesh Syncは両方のプラットフォームで動作します。Androidではご希望であればHealth Connect経由でデータを送ることもできます。iPhoneではAppleヘルスと統合されます。直接Bluetooth接続は両方のシステムで利用可能です。",
        ko: "Colmi 링과 FitMesh Sync는 두 플랫폼 모두에서 작동합니다. Android에서는 원하시면 Health Connect를 통해서도 데이터를 전송할 수 있습니다. iPhone에서는 Apple 건강과 통합됩니다. 직접 Bluetooth 연결은 두 시스템 모두에서 사용 가능합니다.",
      },
    },
    {
      q: {
        it: "Se indosso anche uno smartwatch, i dati del sonno si duplicano?",
        en: "If I also wear a smartwatch, does sleep data get duplicated?",
        es: "Si también llevo un smartwatch, ¿los datos del sueño se duplican?",
        de: "Wenn ich auch einen Smartwatch trage, werden die Schlafdaten dupliziert?",
        pt: "Se eu também usar um smartwatch, os dados do sono serão duplicados?",
        fr: "Si je porte aussi une montre connectée, les données de sommeil sont-elles dupliquées?",
        pl: "Je butam też na smartwatch, a dane dotyczące snu się podwójnie zwiększają?",
        tr: "Giardino anche un giyilebilir cihaz, uyku verileri kaksıya eşitlenir mi?",
        nl: "Als ik ook een smartwatch draag, worden de slaapgegevens dan gedupliceerd?",
        ja: "スマートウォッチも着けている場合、睡眠データは重複しますか？",
        ko: "스마트워치도 착용하면 수면 데이터가 중복되나요?",
      },
      a: {
        it: "No. FitMesh Sync riconosce le sovrapposizioni temporali e tiene un solo valore per ogni metrica, preferendo la fonte piu dettagliata disponibile. Se sia l'anello che lo smartwatch registrano la stessa notte, l'app usa i dati con le fasi piu complete senza sommare le ore.",
        en: "No. FitMesh Sync recognizes temporal overlaps and keeps a single value for each metric, preferring the most detailed source available. If both the ring and the smartwatch record the same night, the app uses the data with the most complete stages without summing the hours.",
        es: "No. FitMesh Sync detecta las superposiciones temporales y conserva un único valor por cada métrica, dando prioridad a la fuente más detallada disponible. Si tanto el anillo como el smartwatch registran la misma noche, la app usa los datos con las fases más completas sin sumar las horas.",
        de: "Nein. FitMesh Sync erkennt zeitliche Überschneidungen und behält einen einzigen Wert für jede Metrik, wobei die detaillierteste verfügbare Quelle bevorzugt wird. Wenn sowohl der Ring als auch der Smartwatch dieselbe Nacht aufzeichnen, verwendet die App die Daten mit den vollständigsten Schlafphasen ohne die Stunden zu addieren.",
        pt: "Não. FitMesh Sync reconhece sobreposições temporais e mantém um único valor para cada métrica, preferindo a fonte mais detalhada disponível. Se tanto o anel quanto o smartwatch registrarem a mesma noite, o app usa os dados com as fases mais completas sem somar as horas.",
        fr: "Non. FitMesh Sync reconnaît les chevauchements temporels et conserve une seule valeur par métrique, en préférant la source la plus détaillée disponible. Si la bague et la montre connectée enregistrent toutes les deux la même nuit, l'application utilise les données avec les phases les plus complètes sans additionner les heures.",
        pl: "No. FitMesh Sync rozpoznaje nadmiernych zapełnień czasowych i przechowuje tylko jedno wartości dla każdej metryki, preferując najbardziej szczegółową dostępne źródło. Jeśli oba: pierścień i smartwatch rejestrują tę samą noc, aplikacja używa danych z najpełniejszymi fazami bez dodawania godzin.",
        tr: "No. FitMesh Sync soylar zamanlı örtüşmeleri ve her metrik için tek bir değer tutar, mevcut detaylı kaynaktan tercih edilir. Eğer yüzük ve akıllı saat aynı geceyi kaydediyorsa, uygulama tam fasilere sahip olan verileri kullanır ve saatleri toplamaz.",
        nl: "Nee. FitMesh Sync herkent tijdoverlappen en behoudt een enkele waarde per meting, waarbij de meest gedetailleerde beschikbare bron de voorkeur krijgt. Als zowel de ring als de smartwatch dezelfde nacht registreren, gebruikt de app de gegevens met de meest volledige slaapfasen zonder de uren op te tellen.",
        ja: "いいえ。FitMesh Syncは時間的な重複を認識し、各指標に対して1つの値のみを保持します。利用可能な最も詳細なソースが優先されます。リングとスマートウォッチの両方が同じ夜を記録した場合、アプリは時間を合算せず、最も完全なステージを持つデータを使用します。",
        ko: "아니요. FitMesh Sync는 시간적 중복을 인식하고 각 지표에 대해 단일 값만 유지하며, 가장 상세한 소스를 우선합니다. 링과 스마트워치 모두 같은 밤을 기록하면 앱은 시간을 합산하지 않고 가장 완전한 단계의 데이터를 사용합니다.",
      },
    },
    {
      q: {
        it: "Il traguardo dei 7 giorni vale anche per chi aveva gia l'app prima?",
        en: "Does the 7-day milestone apply to existing users too?",
        es: "¿El hito de los 7 días también aplica a quienes ya tenían la app antes?",
        de: "Gilt der 7-Tage-Meilenstein auch für Nutzer, die die App bereits hatten?",
        pt: "O marco dos 7 dias vale também para quem já tinha o app antes?",
        fr: "Le jalon des 7 jours s'applique-t-il aussi aux utilisateurs existants?",
        pl: "Czy cel tygodniowy na 7 dni ma zastosowanie również dla osób, które już posiadały aplikację?",
        tr: "Günlük limitin 7 gün için de eski uygulamayı kullanan kişiler için geçerli mi?",
        nl: "Geldt de 7-dagen mijlpaal ook voor bestaande gebruikers?",
        ja: "7日間の達成条件は既存ユーザーにも適用されますか？",
        ko: "7일 마일스톤은 기존 사용자에게도 적용되나요?",
      },
      a: {
        it: "Si, il traguardo e disponibile per tutti gli utenti che connettono l'anello Colmi entro il periodo di lancio, indipendentemente da quando hanno scaricato l'app. I 7 giorni si contano dalla prima sincronizzazione con l'anello.",
        en: "Yes, the milestone is available to all users who connect the Colmi ring within the launch period, regardless of when they downloaded the app. The 7 days are counted from the first sync with the ring.",
        es: "Sí, el hito está disponible para todos los usuarios que conecten el anillo Colmi dentro del período de lanzamiento, independientemente de cuándo hayan descargado la app. Los 7 días se cuentan desde la primera sincronización con el anillo.",
        de: "Ja, der Meilenstein ist für alle Nutzer verfügbar, die den Colmi Ring innerhalb des Launch-Zeitraums verbinden, unabhängig davon, wann sie die App heruntergeladen haben. Die 7 Tage werden ab der ersten Synchronisierung mit dem Ring gezählt.",
        pt: "Sim, o marco está disponível para todos os usuários que conectarem o anel Colmi dentro do período de lançamento, independentemente de quando baixaram o app. Os 7 dias são contados a partir da primeira sincronização com o anel.",
        fr: "Oui, le jalon est disponible pour tous les utilisateurs qui connectent la bague Colmi dans la période de lancement, indépendamment du moment où ils ont téléchargé l'application. Les 7 jours sont comptés à partir de la première synchronisation avec la bague.",
        pl: "Tak, cel jest dostępny dla wszystkich użytkowników, którzy połączą anell Colmi w okresie startu, niezależnie od daty pobrania aplikacji. 7 dni liczą się od pierwszej synchronizacji z anellem.",
        tr: "Evet, hedef mevcut tüm kullanıcılara ait Colmi cihazını ilk başlangıç dönemine bağlayan kullanıcılar için ve ilk kez uygulamayı indirdikten sonra ilk eşleme işleminden 7 gün geçer.",
        nl: "Ja, de mijlpaal is beschikbaar voor alle gebruikers die de Colmi ring verbinden binnen de lanceringsperiode, ongeacht wanneer ze de app hebben gedownload. De 7 dagen worden geteld vanaf de eerste synchronisatie met de ring.",
        ja: "はい、達成条件はアプリをダウンロードした時期に関わらず、ローンチ期間内にColmiリングを接続したすべてのユーザーが対象です。7日間はリングとの最初の同期から数えます。",
        ko: "네, 마일스톤은 앱을 다운로드한 시기에 관계없이 출시 기간 내에 Colmi 링을 연결하는 모든 사용자에게 제공됩니다. 7일은 링과의 첫 번째 동기화부터 카운트됩니다.",
      },
    },
  ],
  related: ["colmi-ring-fitmesh", "piu-smartwatch-insieme-dati-doppi"],
  brandsMentioned: ["Colmi"],
};
