import type { BlogPost } from "../types";

export const post: BlogPost = {
  slug: "novita-fitmesh-su-app-store",
  category: "news",
  publishedAt: "2026-06-29",
  updatedAt: "2026-06-29",
  ldType: "BlogPosting",
  readMinutes: 3,
  primaryKeyword: {
    it: "fitmesh sync app store",
    en: "fitmesh sync app store",
    es: "fitmesh sync app store",
    de: "fitmesh sync app store",
    pt: "fitmesh sync app store",
    fr: "fitmesh sync app store",
    pl: "fitmesh sync app store",
    tr: "fitmesh sync app store",
    nl: "fitmesh sync app store",
    ja: "fitmesh sync app store",
    ko: "fitmesh sync app store",
  },
  secondaryKeywords: {
    it: [
      "fitmesh sync iphone",
      "app salute iphone smartwatch android",
      "ponte apple salute wearable android",
      "fitmesh sync ios disponibile",
      "dashboard salute android iphone",
    ],
    en: [
      "fitmesh sync iphone",
      "apple health android smartwatch sync",
      "apple health bridge wearable",
      "fitmesh sync ios available",
      "android iphone health dashboard",
    ],
    es: [
      "fitmesh sync iphone",
      "app salud iphone smartwatch android",
      "puente apple salud wearable android",
      "fitmesh sync ios disponible",
      "panel salud android iphone",
    ],
    de: [
      "fitmesh sync iphone",
      "apple health android smartwatch sync",
      "apple health brücke wearable",
      "fitmesh sync ios verfügbar",
      "gesundheits-dashboard android iphone",
    ],
    pt: [
      "fitmesh sync iphone",
      "app saúde iphone smartwatch android",
      "ponte apple saúde wearable android",
      "fitmesh sync ios disponível",
      "painel saúde android iphone",
    ],
    fr: [
      "fitmesh sync iphone",
      "app santé iphone smartwatch android",
      "passerelle apple santé wearable android",
      "fitmesh sync ios disponible",
      "tableau de bord santé android iphone",
    ],
    pl: [
      "fitmesh sync iphone",
      "aplikacja zdrowia iphone smartwatch android",
      "most apple health wearable android",
      "fitmesh sync ios dostępny",
      "panel zdrowia android iphone",
    ],
    tr: [
      "fitmesh sync iphone",
      "iphone sağlık uygulaması android akıllı saat",
      "apple health köprüsü wearable android",
      "fitmesh sync ios mevcut",
      "android iphone sağlık paneli",
    ],
    nl: [
      "fitmesh sync iphone",
      "apple gezondheid iphone sporthorloge android",
      "apple gezondheid brug wearable android",
      "fitmesh sync ios beschikbaar",
      "gezondheid dashboard android iphone",
    ],
    ja: [
      "fitmesh sync iphone",
      "apple health iphone androidスマートウォッチ 同期",
      "apple health ブリッジ wearable android",
      "fitmesh sync ios 配信",
      "健康データ ダッシュボード android iphone",
    ],
    ko: [
      "fitmesh sync iphone",
      "apple 건강 iphone android 스마트워치 동기화",
      "apple health 브릿지 웨어러블 android",
      "fitmesh sync ios 출시",
      "건강 데이터 대시보드 android iphone",
    ],
  },
  metaDescription: {
    it: "FitMesh Sync è ora su App Store, gratis con acquisto in-app. Un account per Android e iPhone, ponte di scrittura Apple Salute, cloud EU/GDPR. Live in gran parte del mondo; nell'UE in arrivo a giorni.",
    en: "FitMesh Sync is now on the App Store, free with in-app purchase. One account for Android and iPhone, Apple Health write bridge, EU/GDPR cloud. Live across most of the world; EU rolling out in days.",
    es: "FitMesh Sync ya está en App Store, gratis con compra integrada. Una cuenta para Android e iPhone, puente de escritura a Apple Salud, nube EU/GDPR. Disponible en gran parte del mundo; en la UE en días.",
    de: "FitMesh Sync ist jetzt im App Store, kostenlos mit In-App-Kauf. Ein Konto für Android und iPhone, Apple-Health-Schreibbrücke, EU/DSGVO-Cloud. Live in weiten Teilen der Welt; in der EU in wenigen Tagen.",
    pt: "FitMesh Sync já está na App Store, grátis com compra no app. Uma conta para Android e iPhone, ponte de escrita para o Apple Health, nuvem EU/GDPR. Disponível em grande parte do mundo; na UE em dias.",
    fr: "FitMesh Sync est maintenant sur l'App Store, gratuit avec achat intégré. Un compte pour Android et iPhone, pont d'écriture Apple Health, cloud EU/RGPD. Disponible dans la majeure partie du monde ; dans l'UE sous quelques jours.",
    pl: "FitMesh Sync jest już w App Store, za darmo z zakupem w aplikacji. Jedno konto dla Androida i iPhone'a, most zapisu Apple Health, chmura EU/RODO. Dostępny w większości świata; w UE w ciągu kilku dni.",
    tr: "FitMesh Sync artık App Store'da, uygulama içi satın almayla ücretsiz. Android ve iPhone için tek hesap, Apple Health yazma köprüsü, AB/GDPR bulutu. Dünyanın büyük bölümünde yayında; AB'de birkaç gün içinde.",
    nl: "FitMesh Sync staat nu in de App Store, gratis met in-app aankoop. Eén account voor Android en iPhone, Apple Health schrijfbrug, EU/AVG-cloud. Live in een groot deel van de wereld; in de EU binnen enkele dagen.",
    ja: "FitMesh SyncがApp Storeで配信開始、アプリ内課金ありで無料。AndroidとiPhoneを1つのアカウントで、Apple Health書き込みブリッジ、EU/GDPRクラウド。世界の大半で利用可能、EUは数日中に。",
    ko: "FitMesh Sync가 App Store에 출시, 인앱 구매 포함 무료. Android와 iPhone을 하나의 계정으로, Apple Health 쓰기 브릿지, EU/GDPR 클라우드. 전 세계 대부분에서 이용 가능, EU는 며칠 내.",
  },
  tldr: {
    it: [
      "FitMesh Sync è ora su App Store, gratis con acquisto in-app (Pro a vita 4,99 € su iPhone).",
      "Un solo account funziona su Android e iPhone insieme, con il ponte di scrittura Apple Salute opt-in.",
      "Disponibile in gran parte del mondo; nell'UE il rollout è in arrivo a giorni.",
    ],
    en: [
      "FitMesh Sync is now on the App Store, free with in-app purchase (Pro lifetime €4.99 on iPhone).",
      "One account works across Android and iPhone, with the opt-in Apple Health write bridge.",
      "Available across most of the world; the EU rollout is coming in the next few days.",
    ],
    es: [
      "FitMesh Sync ya está en App Store, gratis con compra integrada (Pro de por vida 4,99 € en iPhone).",
      "Una sola cuenta funciona en Android e iPhone a la vez, con el puente de escritura a Apple Salud opt-in.",
      "Disponible en gran parte del mundo; en la UE el despliegue llega en los próximos días.",
    ],
    de: [
      "FitMesh Sync ist jetzt im App Store, kostenlos mit In-App-Kauf (Pro lebenslang 4,99 € auf dem iPhone).",
      "Ein einziges Konto funktioniert auf Android und iPhone, mit der opt-in Apple-Health-Schreibbrücke.",
      "In weiten Teilen der Welt verfügbar; der EU-Rollout erfolgt in den nächsten Tagen.",
    ],
    pt: [
      "FitMesh Sync já está na App Store, grátis com compra no app (Pro vitalício € 4,99 no iPhone).",
      "Uma única conta funciona em Android e iPhone juntos, com a ponte de escrita para o Apple Health opt-in.",
      "Disponível em grande parte do mundo; na UE o lançamento chega nos próximos dias.",
    ],
    fr: [
      "FitMesh Sync est maintenant sur l'App Store, gratuit avec achat intégré (Pro à vie 4,99 € sur iPhone).",
      "Un seul compte fonctionne sur Android et iPhone, avec le pont d'écriture Apple Health en opt-in.",
      "Disponible dans la majeure partie du monde ; le déploiement dans l'UE arrive dans les prochains jours.",
    ],
    pl: [
      "FitMesh Sync jest już w App Store, za darmo z zakupem w aplikacji (Pro na zawsze 4,99 € na iPhone).",
      "Jedno konto działa na Androidzie i iPhonie razem, z opcjonalnym mostem zapisu Apple Health.",
      "Dostępny w większości krajów świata; w UE wdrożenie pojawia się w najbliższych dniach.",
    ],
    tr: [
      "FitMesh Sync artık App Store'da, uygulama içi satın almayla ücretsiz (iPhone'da ömür boyu Pro 4,99 €).",
      "Tek bir hesap Android ve iPhone'da birlikte çalışır; isteğe bağlı Apple Health yazma köprüsüyle.",
      "Dünyanın büyük bölümünde mevcut; AB'de dağıtım önümüzdeki günlerde geliyor.",
    ],
    nl: [
      "FitMesh Sync staat nu in de App Store, gratis met in-app aankoop (Pro levenslang € 4,99 op iPhone).",
      "Eén account werkt op zowel Android als iPhone, met de opt-in Apple Health schrijfbrug.",
      "Beschikbaar in een groot deel van de wereld; de EU-uitrol komt de komende dagen.",
    ],
    ja: [
      "FitMesh SyncがApp Storeで配信開始、アプリ内課金ありで無料（iPhoneのProは買い切り4.99ユーロ）。",
      "1つのアカウントでAndroidとiPhoneを併用でき、オプトインのApple Health書き込みブリッジに対応。",
      "世界の大半の国で利用可能、EUは近日中に順次対応。",
    ],
    ko: [
      "FitMesh Sync가 App Store에 출시, 인앱 구매 포함 무료(iPhone에서 평생 Pro 4.99유로).",
      "하나의 계정으로 Android와 iPhone을 함께 사용하며, 옵트인 Apple Health 쓰기 브릿지를 지원합니다.",
      "전 세계 대부분의 국가에서 이용 가능하며, EU는 며칠 내 순차 출시됩니다.",
    ],
  },
  hero: {
    kicker: {
      it: "Novità",
      en: "What's New",
      es: "Novedades",
      de: "Neuigkeit",
      pt: "Novidade",
      fr: "Nouveauté",
      pl: "Nowości",
      tr: "Yeni Özellikler",
      nl: "Nieuw",
      ja: "新着情報",
      ko: "새 소식",
    },
    title: {
      it: "FitMesh Sync è ora su App Store",
      en: "FitMesh Sync is now on the App Store",
      es: "FitMesh Sync ya está en App Store",
      de: "FitMesh Sync ist jetzt im App Store",
      pt: "FitMesh Sync já está na App Store",
      fr: "FitMesh Sync est maintenant sur l'App Store",
      pl: "FitMesh Sync jest już w App Store",
      tr: "FitMesh Sync artık App Store'da",
      nl: "FitMesh Sync staat nu in de App Store",
      ja: "FitMesh SyncがApp Storeに登場",
      ko: "FitMesh Sync, 이제 App Store에서",
    },
    subtitle: {
      it: "L'app iOS è ufficialmente live: scaricala gratis (con acquisto in-app), accedi con lo stesso account di Android e porta i dati del tuo wearable Android in Apple Salute. Disponibile in gran parte del mondo; nell'UE in arrivo a giorni.",
      en: "The iOS app is officially live: download it free (with in-app purchase), sign in with your same Android account, and bring your Android wearable data into Apple Health. Available across most of the world; rolling out across the EU in the coming days.",
      es: "La app para iOS ya está disponible oficialmente: descárgala gratis (con compra integrada), inicia sesión con tu misma cuenta de Android y lleva los datos de tu wearable Android a Apple Salud. Disponible en gran parte del mundo; en la UE llega en los próximos días.",
      de: "Die iOS-App ist offiziell live: Lade sie kostenlos herunter (mit In-App-Kauf), melde dich mit deinem Android-Konto an und bring deine Android-Wearable-Daten in Apple Health. In weiten Teilen der Welt verfügbar; in der EU in den kommenden Tagen.",
      pt: "O app iOS está oficialmente disponível: baixe grátis (com compra no app), entre com a mesma conta do Android e leve os dados do seu wearable Android para o Apple Health. Disponível em grande parte do mundo; na UE chega nos próximos dias.",
      fr: "L'app iOS est officiellement disponible : téléchargez-la gratuitement (avec achat intégré), connectez-vous avec votre compte Android et amenez vos données wearable Android dans Apple Health. Disponible dans la majeure partie du monde ; déploiement dans l'UE dans les prochains jours.",
      pl: "Aplikacja iOS jest oficjalnie dostępna: pobierz ją za darmo (z zakupem w aplikacji), zaloguj się tym samym kontem co na Androidzie i przenieś dane z wearable Android do Apple Health. Dostępna w większości świata; w UE w najbliższych dniach.",
      tr: "iOS uygulaması resmen yayında: ücretsiz indir (uygulama içi satın almayla), Android'deki aynı hesapla giriş yap ve Android giyilebilir cihaz verilerini Apple Health'e taşı. Dünyanın büyük bölümünde mevcut; AB'de önümüzdeki günlerde.",
      nl: "De iOS-app is officieel live: download hem gratis (met in-app aankoop), meld je aan met je Android-account en breng je Android-wearable gegevens naar Apple Gezondheid. Beschikbaar in een groot deel van de wereld; in de EU de komende dagen.",
      ja: "iOSアプリが正式に配信開始：無料でダウンロード（アプリ内課金あり）、Androidと同じアカウントでサインインし、AndroidウェアラブルのデータをApple Healthに取り込めます。世界の大半の国で利用可能、EUは近日中に順次対応。",
      ko: "iOS 앱이 정식으로 출시되었습니다: 무료로 다운로드(인앱 구매 포함)하고 Android와 동일한 계정으로 로그인하여 Android 웨어러블 데이터를 Apple Health로 가져오세요. 전 세계 대부분에서 이용 가능하며, EU는 며칠 내 순차 출시됩니다.",
    },
  },
  body: [
    {
      type: "paragraph",
      text: {
        it: "Ci siamo: FitMesh Sync è ora su App Store. La versione iOS porta tutto quello che già conosci dall'app Android — un solo account, dashboard unificata, sync su cloud EU — e aggiunge il pezzo che mancava agli utenti iPhone: il ponte di scrittura verso Apple Salute. L'app è gratis con acquisto in-app (Pro a vita 4,99 € su iPhone) ed è scaricabile in gran parte del mondo; nei 27 Paesi dell'UE il rollout è in corso e arriva a giorni.",
        en: "Here we are: FitMesh Sync is now on the App Store. The iOS version brings everything you already know from the Android app — one account, a unified dashboard, EU cloud sync — and adds the piece iPhone users were missing: the write bridge into Apple Health. The app is free with in-app purchase (Pro lifetime €4.99 on iPhone) and downloadable across most of the world; in the 27 EU countries the rollout is underway and arriving in the coming days.",
        es: "Ya está: FitMesh Sync está ahora en App Store. La versión para iOS trae todo lo que ya conoces de la app Android —una sola cuenta, panel unificado, sincronización en nube EU— y añade la pieza que les faltaba a los usuarios de iPhone: el puente de escritura a Apple Salud. La app es gratis con compra integrada (Pro de por vida 4,99 € en iPhone) y se puede descargar en gran parte del mundo; en los 27 países de la UE el despliegue está en marcha y llega en los próximos días.",
        de: "Es ist soweit: FitMesh Sync ist jetzt im App Store. Die iOS-Version bringt alles mit, was du bereits aus der Android-App kennst — ein Konto, ein einheitliches Dashboard, EU-Cloud-Sync — und ergänzt das, was iPhone-Nutzern bisher fehlte: die Schreibbrücke in Apple Health. Die App ist kostenlos mit In-App-Kauf (Pro lebenslang 4,99 € auf dem iPhone) und in weiten Teilen der Welt verfügbar; in den 27 EU-Ländern läuft der Rollout und kommt in den nächsten Tagen.",
        pt: "Chegou: FitMesh Sync agora está na App Store. A versão iOS traz tudo o que você já conhece do app Android — uma só conta, painel unificado, sincronização na nuvem EU — e adiciona a peça que faltava aos usuários de iPhone: a ponte de escrita para o Apple Health. O app é grátis com compra no app (Pro vitalício € 4,99 no iPhone) e pode ser baixado em grande parte do mundo; nos 27 países da UE o lançamento está em andamento e chega nos próximos dias.",
        fr: "Ça y est : FitMesh Sync est maintenant sur l'App Store. La version iOS reprend tout ce que vous connaissez déjà de l'app Android — un seul compte, un tableau de bord unifié, la synchronisation cloud EU — et ajoute la pièce qui manquait aux utilisateurs d'iPhone : le pont d'écriture vers Apple Health. L'app est gratuite avec achat intégré (Pro à vie 4,99 € sur iPhone) et téléchargeable dans la majeure partie du monde ; dans les 27 pays de l'UE, le déploiement est en cours et arrive dans les prochains jours.",
        pl: "Jest: FitMesh Sync jest już w App Store. Wersja iOS przynosi wszystko, co znasz z aplikacji Android — jedno konto, ujednolicony panel, synchronizację w chmurze EU — i dodaje element, którego brakowało użytkownikom iPhone'a: most zapisu do Apple Health. Aplikacja jest darmowa z zakupem w aplikacji (Pro na zawsze 4,99 € na iPhone) i można ją pobrać w większości krajów świata; w 27 krajach UE wdrożenie trwa i pojawi się w najbliższych dniach.",
        tr: "İşte burada: FitMesh Sync artık App Store'da. iOS sürümü, Android uygulamasından zaten bildiğiniz her şeyi getiriyor — tek hesap, birleşik panel, AB bulut senkronizasyonu — ve iPhone kullanıcılarında eksik olan parçayı ekliyor: Apple Health'e yazma köprüsü. Uygulama uygulama içi satın almayla ücretsiz (iPhone'da ömür boyu Pro 4,99 €) ve dünyanın büyük bölümünde indirilebiliyor; 27 AB ülkesinde dağıtım sürüyor ve önümüzdeki günlerde geliyor.",
        nl: "Het is zover: FitMesh Sync staat nu in de App Store. De iOS-versie brengt alles wat je al kent van de Android-app — één account, een unified dashboard, EU-cloudsynchronisatie — en voegt het stuk toe dat iPhone-gebruikers misten: de schrijfbrug naar Apple Gezondheid. De app is gratis met in-app aankoop (Pro levenslang € 4,99 op iPhone) en te downloaden in een groot deel van de wereld; in de 27 EU-landen is de uitrol bezig en komt hij de komende dagen.",
        ja: "ついに、FitMesh SyncがApp Storeに登場しました。iOS版はAndroidアプリでおなじみの機能をすべて備え（1つのアカウント、統合ダッシュボード、EUクラウド同期）、iPhoneユーザーに欠けていた要素であるApple Healthへの書き込みブリッジを追加します。アプリはアプリ内課金ありで無料（iPhoneのProは買い切り4.99ユーロ）、世界の大半の国でダウンロードでき、EU27か国では順次対応が進行中で、近日中に提供されます。",
        ko: "드디어 FitMesh Sync가 App Store에 출시되었습니다. iOS 버전은 Android 앱에서 이미 알고 있는 모든 기능(하나의 계정, 통합 대시보드, EU 클라우드 동기화)을 제공하고, iPhone 사용자에게 빠져 있던 요소인 Apple Health 쓰기 브릿지를 추가합니다. 앱은 인앱 구매가 포함된 무료(iPhone에서 평생 Pro 4.99유로)이며 전 세계 대부분의 국가에서 다운로드할 수 있고, EU 27개국에서는 순차 출시가 진행 중이며 며칠 내 제공됩니다.",
      },
    },
    {
      type: "cta",
      title: {
        it: "Disponibile ora su App Store",
        en: "Now on the App Store",
        es: "Ya disponible en App Store",
        de: "Jetzt im App Store",
        pt: "Já disponível na App Store",
        fr: "Maintenant sur l'App Store",
        pl: "Już w App Store",
        tr: "Şimdi App Store'da",
        nl: "Nu in de App Store",
        ja: "App Storeで配信中",
        ko: "지금 App Store에서",
      },
      body: {
        it: "FitMesh Sync è live su App Store, gratis con acquisto in-app. Live in gran parte del mondo; nell'UE in arrivo a giorni.",
        en: "FitMesh Sync is live on the App Store, free with in-app purchase. Live across most of the world; the EU is rolling out in the coming days.",
        es: "FitMesh Sync está disponible en App Store, gratis con compra integrada. Disponible en gran parte del mundo; en la UE llega en los próximos días.",
        de: "FitMesh Sync ist live im App Store, kostenlos mit In-App-Kauf. Live in weiten Teilen der Welt; in der EU in den kommenden Tagen.",
        pt: "FitMesh Sync está disponível na App Store, grátis com compra no app. Disponível em grande parte do mundo; na UE nos próximos dias.",
        fr: "FitMesh Sync est disponible sur l'App Store, gratuit avec achat intégré. Disponible dans la majeure partie du monde ; dans l'UE dans les prochains jours.",
        pl: "FitMesh Sync jest dostępny w App Store, za darmo z zakupem w aplikacji. Dostępny w większości świata; w UE w najbliższych dniach.",
        tr: "FitMesh Sync App Store'da yayında, uygulama içi satın almayla ücretsiz. Dünyanın büyük bölümünde mevcut; AB'de önümüzdeki günlerde.",
        nl: "FitMesh Sync is live in de App Store, gratis met in-app aankoop. Live in een groot deel van de wereld; in de EU de komende dagen.",
        ja: "FitMesh SyncはApp Storeで配信中、アプリ内課金ありで無料です。世界の大半の国で利用可能、EUは近日中に。",
        ko: "FitMesh Sync는 App Store에서 이용 가능하며 인앱 구매가 포함된 무료입니다. 전 세계 대부분에서 이용 가능하며, EU는 며칠 내.",
      },
      ctaLabel: {
        it: "Apri su App Store →",
        en: "View on the App Store →",
        es: "Ver en App Store →",
        de: "Im App Store ansehen →",
        pt: "Ver na App Store →",
        fr: "Voir sur l'App Store →",
        pl: "Zobacz w App Store →",
        tr: "App Store'da görüntüle →",
        nl: "Bekijk in de App Store →",
        ja: "App Storeで見る →",
        ko: "App Store에서 보기 →",
      },
      ctaHref: {
        it: "https://apps.apple.com/app/fitmesh-sync/id6779751708",
        en: "https://apps.apple.com/app/fitmesh-sync/id6779751708",
        es: "https://apps.apple.com/app/fitmesh-sync/id6779751708",
        de: "https://apps.apple.com/app/fitmesh-sync/id6779751708",
        pt: "https://apps.apple.com/app/fitmesh-sync/id6779751708",
        fr: "https://apps.apple.com/app/fitmesh-sync/id6779751708",
        pl: "https://apps.apple.com/app/fitmesh-sync/id6779751708",
        tr: "https://apps.apple.com/app/fitmesh-sync/id6779751708",
        nl: "https://apps.apple.com/app/fitmesh-sync/id6779751708",
        ja: "https://apps.apple.com/app/fitmesh-sync/id6779751708",
        ko: "https://apps.apple.com/app/fitmesh-sync/id6779751708",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Cosa trovi nella versione iOS",
        en: "What you get in the iOS version",
        es: "Qué encuentras en la versión para iOS",
        de: "Was die iOS-Version bietet",
        pt: "O que você encontra na versão iOS",
        fr: "Ce que vous trouvez dans la version iOS",
        pl: "Co znajdziesz w wersji iOS",
        tr: "iOS sürümünde neler var",
        nl: "Wat je krijgt in de iOS-versie",
        ja: "iOS版で使える機能",
        ko: "iOS 버전에서 제공되는 기능",
      },
    },
    {
      type: "list",
      items: {
        it: [
          "**Un account, Android e iPhone insieme**: accedi con lo stesso login Google o Apple e ritrovi la stessa dashboard su entrambi i telefoni e nel browser.",
          "**Ponte di scrittura Apple Salute** (opt-in): i dati del tuo smartwatch o anello Android arrivano via cloud e vengono scritti in Apple Salute, senza duplicati.",
          "**Cloud EU e GDPR**: i dati sono archiviati in datacenter europei, conformi GDPR. Nessuna vendita a terzi.",
          "**Anello Colmi via Bluetooth**: l'app iOS legge l'anello smart Colmi R02/R03 in BLE diretto, come fa la versione Android.",
        ],
        en: [
          "**One account, Android and iPhone together**: sign in with the same Google or Apple login and find the same dashboard on both phones and in the browser.",
          "**Apple Health write bridge** (opt-in): data from your Android smartwatch or ring arrives via cloud and gets written into Apple Health, with no duplicates.",
          "**EU cloud and GDPR**: data is stored in European datacenters, GDPR compliant. No third-party data sales.",
          "**Colmi ring via Bluetooth**: the iOS app reads the Colmi R02/R03 smart ring over direct BLE, just like the Android version.",
        ],
        es: [
          "**Una cuenta, Android e iPhone a la vez**: inicia sesión con el mismo login de Google o Apple y encuentra el mismo panel en ambos teléfonos y en el navegador.",
          "**Puente de escritura a Apple Salud** (opt-in): los datos de tu smartwatch o anillo Android llegan por la nube y se escriben en Apple Salud, sin duplicados.",
          "**Nube EU y GDPR**: los datos se almacenan en centros de datos europeos, conformes con el GDPR. Sin venta a terceros.",
          "**Anillo Colmi vía Bluetooth**: la app para iOS lee el anillo inteligente Colmi R02/R03 por BLE directo, igual que la versión Android.",
        ],
        de: [
          "**Ein Konto, Android und iPhone gemeinsam**: Melde dich mit demselben Google- oder Apple-Login an und finde dasselbe Dashboard auf beiden Smartphones und im Browser.",
          "**Apple-Health-Schreibbrücke** (opt-in): Daten deines Android-Smartwatchs oder -Rings kommen über die Cloud und werden ohne Duplikate in Apple Health geschrieben.",
          "**EU-Cloud und DSGVO**: Daten werden in europäischen Rechenzentren gespeichert, DSGVO-konform. Keine Datenweitergabe an Dritte.",
          "**Colmi-Ring per Bluetooth**: Die iOS-App liest den Colmi R02/R03 Smart-Ring per direktem BLE, genau wie die Android-Version.",
        ],
        pt: [
          "**Uma conta, Android e iPhone juntos**: entre com o mesmo login Google ou Apple e encontre o mesmo painel nos dois celulares e no navegador.",
          "**Ponte de escrita para o Apple Health** (opt-in): os dados do seu smartwatch ou anel Android chegam via nuvem e são gravados no Apple Health, sem duplicatas.",
          "**Nuvem EU e GDPR**: os dados são armazenados em datacenters europeus, em conformidade com o GDPR. Sem venda a terceiros.",
          "**Anel Colmi via Bluetooth**: o app iOS lê o anel inteligente Colmi R02/R03 por BLE direto, como a versão Android.",
        ],
        fr: [
          "**Un compte, Android et iPhone ensemble** : connectez-vous avec le même identifiant Google ou Apple et retrouvez le même tableau de bord sur les deux téléphones et dans le navigateur.",
          "**Pont d'écriture vers Apple Health** (opt-in) : les données de votre montre ou bague Android arrivent via le cloud et sont écrites dans Apple Health, sans doublons.",
          "**Cloud EU et RGPD** : les données sont stockées dans des datacenters européens, conformes au RGPD. Aucune vente à des tiers.",
          "**Bague Colmi via Bluetooth** : l'app iOS lit la bague connectée Colmi R02/R03 en BLE direct, comme la version Android.",
        ],
        pl: [
          "**Jedno konto, Android i iPhone razem**: zaloguj się tym samym loginem Google lub Apple i znajdź ten sam panel na obu telefonach i w przeglądarce.",
          "**Most zapisu Apple Health** (opt-in): dane z Twojego smartwatcha lub pierścienia Android trafiają przez chmurę i są zapisywane w Apple Health, bez duplikatów.",
          "**Chmura EU i RODO**: dane są przechowywane w europejskich centrach danych, zgodnych z RODO. Bez sprzedaży podmiotom trzecim.",
          "**Pierścień Colmi przez Bluetooth**: aplikacja iOS odczytuje pierścień smart Colmi R02/R03 przez bezpośrednie BLE, tak jak wersja Android.",
        ],
        tr: [
          "**Bir hesap, Android ve iPhone birlikte**: aynı Google veya Apple girişiyle oturum açın ve her iki telefonda ve tarayıcıda aynı paneli bulun.",
          "**Apple Health yazma köprüsü** (isteğe bağlı): Android akıllı saatinizin veya yüzüğünüzün verileri bulut üzerinden gelir ve yineleme olmadan Apple Health'e yazılır.",
          "**AB bulutu ve GDPR**: veriler Avrupa veri merkezlerinde, GDPR uyumlu şekilde saklanır. Üçüncü taraflara veri satışı yok.",
          "**Bluetooth üzerinden Colmi yüzük**: iOS uygulaması Colmi R02/R03 akıllı yüzüğü doğrudan BLE ile okur, tıpkı Android sürümü gibi.",
        ],
        nl: [
          "**Eén account, Android en iPhone samen**: meld je aan met dezelfde Google- of Apple-login en vind hetzelfde dashboard op beide telefoons en in de browser.",
          "**Apple Health schrijfbrug** (opt-in): gegevens van je Android-sporthorloge of -ring komen via de cloud binnen en worden zonder duplicaten in Apple Gezondheid geschreven.",
          "**EU-cloud en AVG**: gegevens worden opgeslagen in Europese datacenters, AVG-conform. Geen verkoop aan derden.",
          "**Colmi-ring via Bluetooth**: de iOS-app leest de Colmi R02/R03 slimme ring via directe BLE, net als de Android-versie.",
        ],
        ja: [
          "**1つのアカウントでAndroidとiPhoneを一緒に**：同じGoogleまたはAppleログインでサインインすると、両方のスマートフォンとブラウザで同じダッシュボードを利用できます。",
          "**Apple Health書き込みブリッジ**（オプトイン）：AndroidスマートウォッチやリングのデータがクラウドР経由で届き、重複なしにApple Healthに書き込まれます。",
          "**EUクラウドとGDPR**：データは欧州のデータセンターに保存され、GDPRに準拠。第三者への販売はありません。",
          "**BluetoothでColmiリング接続**：iOSアプリはColmi R02/R03スマートリングをAndroid版と同様に直接BLEで読み取ります。",
        ],
        ko: [
          "**하나의 계정으로 Android와 iPhone 함께**: 동일한 Google 또는 Apple 로그인으로 로그인하면 두 기기와 브라우저에서 동일한 대시보드를 사용할 수 있습니다.",
          "**Apple Health 쓰기 브릿지**(옵트인): Android 스마트워치나 링의 데이터가 클라우드를 통해 전달되어 중복 없이 Apple Health에 기록됩니다.",
          "**EU 클라우드와 GDPR**: 데이터는 유럽 데이터센터에 GDPR을 준수하여 저장됩니다. 제3자 판매 없음.",
          "**Bluetooth로 Colmi 링 연결**: iOS 앱이 Colmi R02/R03 스마트 링을 Android 버전처럼 직접 BLE로 읽습니다.",
        ],
      },
    },
    {
      type: "callout",
      variant: "info",
      title: {
        it: "Una nota sull'UE",
        en: "A note on the EU",
        es: "Una nota sobre la UE",
        de: "Ein Hinweis zur EU",
        pt: "Uma nota sobre a UE",
        fr: "Une note sur l'UE",
        pl: "Uwaga o UE",
        tr: "AB hakkında bir not",
        nl: "Een opmerking over de EU",
        ja: "EUについての注記",
        ko: "EU 관련 안내",
      },
      body: {
        it: "Al momento l'app è live in gran parte del mondo ma non ancora nei 27 Paesi dell'UE: la distribuzione europea è in attesa della verifica DSA dello stato di operatore commerciale da parte di Apple ed è in arrivo a giorni. Se sei nell'UE e non la trovi ancora, riprova tra qualche giorno.",
        en: "Right now the app is live across most of the world but not yet in the 27 EU countries: EU distribution is pending Apple's DSA trader-status verification and is rolling out in the coming days. If you're in the EU and don't see it yet, check back in a few days.",
        es: "Por ahora la app está disponible en gran parte del mundo pero todavía no en los 27 países de la UE: la distribución europea está pendiente de la verificación DSA del estado de operador comercial por parte de Apple y llega en los próximos días. Si estás en la UE y aún no la ves, vuelve a comprobarlo en unos días.",
        de: "Derzeit ist die App in weiten Teilen der Welt verfügbar, aber noch nicht in den 27 EU-Ländern: Die EU-Verteilung wartet auf die DSA-Verifizierung des Händlerstatus durch Apple und erfolgt in den kommenden Tagen. Wenn du in der EU bist und sie noch nicht siehst, schau in ein paar Tagen wieder vorbei.",
        pt: "No momento o app está disponível em grande parte do mundo, mas ainda não nos 27 países da UE: a distribuição europeia aguarda a verificação DSA do status de operador comercial pela Apple e chega nos próximos dias. Se você está na UE e ainda não o vê, verifique novamente em alguns dias.",
        fr: "Pour l'instant, l'app est disponible dans la majeure partie du monde mais pas encore dans les 27 pays de l'UE : la distribution européenne est en attente de la vérification DSA du statut de professionnel par Apple et se déploie dans les prochains jours. Si vous êtes dans l'UE et ne la voyez pas encore, revenez dans quelques jours.",
        pl: "Obecnie aplikacja jest dostępna w większości krajów świata, ale jeszcze nie w 27 krajach UE: dystrybucja w UE czeka na weryfikację DSA statusu przedsiębiorcy przez Apple i pojawia się w najbliższych dniach. Jeśli jesteś w UE i jeszcze jej nie widzisz, sprawdź za kilka dni.",
        tr: "Şu anda uygulama dünyanın büyük bölümünde mevcut ancak henüz 27 AB ülkesinde değil: AB dağıtımı, Apple'ın DSA tüccar statüsü doğrulamasını bekliyor ve önümüzdeki günlerde sunulacak. AB'deyseniz ve henüz görmüyorsanız birkaç gün sonra tekrar kontrol edin.",
        nl: "Op dit moment is de app live in een groot deel van de wereld maar nog niet in de 27 EU-landen: de EU-distributie wacht op Apple's DSA-verificatie van de handelaarsstatus en komt de komende dagen beschikbaar. Ben je in de EU en zie je hem nog niet, kijk dan over een paar dagen opnieuw.",
        ja: "現在、アプリは世界の大半の国で利用できますが、EU27か国ではまだ利用できません。EUでの配信はAppleによるDSAの取引者ステータスの確認待ちで、近日中に順次対応します。EUにお住まいでまだ表示されない場合は、数日後にもう一度ご確認ください。",
        ko: "현재 앱은 전 세계 대부분에서 이용할 수 있지만 EU 27개국에서는 아직 제공되지 않습니다. EU 배포는 Apple의 DSA 거래자 지위 확인을 기다리고 있으며 며칠 내 순차 출시됩니다. EU에 계시고 아직 보이지 않으면 며칠 후에 다시 확인하세요.",
      },
    },
  ],
  related: ["fitmesh-arriva-su-iphone", "fitmesh-sync-disponibile-google-play"],
  brandsMentioned: ["Apple"],
};
