import type { BlogPost } from "../types";

export const post: BlogPost = {
  slug: "novita-fonte-del-dato",
  category: "news",
  publishedAt: "2026-06-14",
  updatedAt: "2026-09-02",
  ldType: "BlogPosting",
  readMinutes: 4,
  primaryKeyword: {
    it: "da quale dispositivo arrivano i dati",
    en: "which device your data comes from",
    es: "de qué dispositivo provienen tus datos",
    de: "von welchem Gerät deine Daten stammen",
    pt: "de qual dispositivo vêm os seus dados",
    fr: "de quel appareil proviennent vos données",
    pl: "z jakiego urządzenia pochodzą dane",
    tr: "Hangi cihazdan veriler geliyor",
    nl: "van welk apparaat komen jouw gegevens",
    ja: "データがどのデバイスから来るか",
    ko: "데이터가 어떤 기기에서 오는지",
  },
  secondaryKeywords: {
    it: [
      "fonte dei dati salute",
      "orologio e anello insieme",
      "passi contati una volta sola",
      "FitMesh Sync trasparenza dati",
      "unire dati wearable senza doppioni",
    ],
    en: [
      "health data source",
      "watch and ring together",
      "steps counted only once",
      "FitMesh Sync data transparency",
      "merge wearable data without duplicates",
    ],
    pt: [
      "fonte dos dados de saúde",
      "relógio e anel juntos",
      "passos contados uma só vez",
      "FitMesh Sync transparência de dados",
      "unir dados wearable sem duplicatas",
    ],
    fr: [
      "source des données de santé",
      "montre et bague ensemble",
      "pas comptés une seule fois",
      "FitMesh Sync transparence des données",
      "fusionner les données wearable sans doublons",
    ],
    pl: [
      "źródło danych zdrowotnych",
      "zegarek i pierścień razem",
      "kroki liczone tylko raz",
      "FitMesh Sync przejrzystość danych",
      "łączenie danych z urządzeń bez duplikatów",
    ],
    tr: [
      "sağlık verileri kaynağı",
      "akıllı saat ve yüzük birlikte",
      "adımlar yalnızca bir kez sayılır",
      "FitMesh Sync veri şeffaflığı",
      "giyilebilir cihaz verilerini tekrar olmadan birleştirme",
    ],
    nl: [
      "bron van gezondheidsgegevens",
      "sporthorloge en slimme ring samen",
      "stappen slechts eenmaal geteld",
      "FitMesh Sync gegevenstransparantie",
      "wearable-gegevens samenvoegen zonder duplicaten",
    ],
    ja: [
      "健康データのソース",
      "スマートウォッチとスマートリングを同時に使用",
      "歩数は一度だけカウント",
      "FitMesh Syncのデータ透明性",
      "重複なしでウェアラブルデータを統合",
    ],
    ko: [
      "건강 데이터 출처",
      "스마트워치와 스마트 링 함께 사용",
      "걸음 수 한 번만 계산",
      "FitMesh Sync 데이터 투명성",
      "중복 없이 웨어러블 데이터 병합",
    ],
    de: [
      "Quelle der Gesundheitsdaten",
      "Uhr und Ring zusammen",
      "Schritte nur einmal gezählt",
      "FitMesh Sync Datentransparenz",
      "Wearable-Daten ohne Duplikate zusammenführen",
    ],
    es: [
      "fuente de los datos de salud",
      "reloj y anillo juntos",
      "pasos contados una sola vez",
      "transparencia de datos fitmesh sync",
      "unir datos wearable sin duplicados",
    ],
  },
  metaDescription: {
    it: "FitMesh Sync ora mostra da quale dispositivo arriva ogni dato salute: orologio, anello o altro. Una vista unica, senza doppioni, sempre chiara su chi misura cosa.",
    en: "FitMesh Sync now shows which device each health metric comes from: watch, ring or other. One clear view, no duplicates, always transparent about the source.",
    es: "FitMesh Sync ahora muestra de qué dispositivo proviene cada dato de salud: reloj, anillo u otro. Una vista única, sin duplicados, siempre clara sobre quién mide qué.",
    de: "FitMesh Sync zeigt jetzt, von welchem Gerät jeder Gesundheitswert stammt: Uhr, Ring oder anderes. Eine klare Übersicht, keine Duplikate, immer transparent über die Quelle.",
    pt: "FitMesh Sync agora mostra de qual dispositivo vem cada dado de saúde: relógio, anel ou outro. Uma visão única, sem duplicatas, sempre clara sobre a fonte.",
    fr: "FitMesh Sync indique maintenant de quel appareil provient chaque donnée de santé: montre, bague connectée ou autre. Une vue claire, sans doublons, toujours transparente sur la source.",
    pl: "FitMesh Sync pokazuje teraz, z którego urządzenia pochodzi każda metryka zdrowotna: zegarka, pierścienia lub innego źródła. Jeden przejrzysty widok, bez duplikatów, zawsze jasno pokazujący źródło danych.",
    tr: "FitMesh Sync artık her sağlık verisinin hangi cihazdan geldiğini gösteriyor: akıllı saat, yüzük ya da başka bir cihaz. Tek ve net bir görünüm, tekrar yok, kaynak konusunda her zaman şeffaf.",
    nl: "FitMesh Sync toont nu van welk apparaat elke gezondheidsmeting afkomstig is: sporthorloge, slimme ring of ander apparaat. Een duidelijk overzicht, geen duplicaten, altijd transparant over de bron.",
    ja: "FitMesh Syncは各健康指標がどのデバイスから来るかを表示するようになりました：スマートウォッチ、スマートリング、またはその他のデバイス。明確な1つのビュー、重複なし、常にソースについて透明です。",
    ko: "FitMesh Sync는 이제 각 건강 지표가 어떤 기기에서 오는지 표시합니다: 스마트워치, 스마트 링 또는 기타 기기. 하나의 명확한 화면, 중복 없음, 항상 출처에 대해 투명합니다.",
  },
  tldr: {
    it: [
      "Ogni metrica ora puo mostrare da dove arriva, per esempio 'Fonte: anello' sotto il Sonno.",
      "Se indossi orologio e anello insieme, i passi non vengono contati due volte.",
      "Quando un dispositivo e in carica, un altro copre quel periodo senza lasciare buchi.",
      "Funziona allo stesso modo su Android e iPhone, senza configurare nulla.",
    ],
    en: [
      "Each metric can now show where it comes from, for example 'Source: ring' under Sleep.",
      "If you wear a watch and a ring together, your steps are not counted twice.",
      "When one device is charging, another covers that window with no gaps.",
      "It works the same way on Android and iPhone, with nothing to configure.",
    ],
    es: [
      "Cada métrica ahora puede mostrar de dónde proviene, por ejemplo 'Fuente: anillo' bajo el Sueño.",
      "Si llevas reloj y anillo a la vez, los pasos no se cuentan dos veces.",
      "Cuando un dispositivo está cargando, otro cubre ese periodo sin dejar huecos.",
      "Funciona igual en Android y en iPhone, sin necesidad de configurar nada.",
    ],
    de: [
      "Jeder Messwert kann jetzt anzeigen, woher er stammt, zum Beispiel 'Quelle: Ring' unter Schlaf.",
      "Wenn du Uhr und Ring gleichzeitig trägst, werden deine Schritte nicht doppelt gezählt.",
      "Wenn ein Gerät lädt, übernimmt ein anderes diesen Zeitraum ohne Lücken.",
      "Funktioniert auf Android und iPhone gleich, ohne etwas einrichten zu müssen.",
    ],
    pt: [
      "Cada métrica agora pode mostrar de onde vem, por exemplo 'Fonte: anel' sob o Sono.",
      "Se você usa relógio e anel juntos, seus passos não são contados duas vezes.",
      "Quando um dispositivo está carregando, outro cobre esse período sem deixar lacunas.",
      "Funciona da mesma forma no Android e no iPhone, sem precisar configurar nada.",
    ],
    fr: [
      "Chaque métrique peut désormais indiquer sa source, par exemple 'Source: bague connectée' sous Sommeil.",
      "Si vous portez une montre et une bague connectée ensemble, vos pas ne sont pas comptés deux fois.",
      "Quand un appareil se recharge, un autre couvre cette période sans laisser de vide.",
      "Fonctionne de la même façon sur Android et iPhone, sans rien configurer.",
    ],
    pl: [
      "Każda metryka może teraz pokazać, skąd pochodzi, na przykład 'Źródło: pierścień' pod Snem.",
      "Jeśli nosisz zegarek i pierścień jednocześnie, kroki nie są liczone dwa razy.",
      "Gdy jedno urządzenie się ładuje, inne pokrywa ten czas bez żadnych luk.",
      "Działa tak samo na Androidzie i iPhonie, bez żadnej konfiguracji.",
    ],
    tr: [
      "Her metrik artık nereden geldiğini gösterebilir, örneğin Uyku altında 'Kaynak: yüzük'.",
      "Akıllı saat ve yüzüğü aynı anda takarsanız, adımlarınız iki kez sayılmaz.",
      "Bir cihaz şarj olurken, bir diğeri o zaman aralığını boşluk bırakmadan kapsar.",
      "Android ve iPhone'da aynı şekilde çalışır, hiçbir ayar gerektirmez.",
    ],
    nl: [
      "Elke meting kan nu tonen waar hij vandaan komt, bijvoorbeeld 'Bron: ring' onder Slaap.",
      "Als je een sporthorloge en een slimme ring samen draagt, worden je stappen niet dubbel geteld.",
      "Wanneer een apparaat oplaadt, neemt een ander dat tijdvenster over zonder hiaten.",
      "Werkt op dezelfde manier op Android en iPhone, zonder iets te hoeven instellen.",
    ],
    ja: [
      "各指標はどこから来たかを表示できるようになりました。例えば、睡眠の下に「ソース：リング」と表示されます。",
      "スマートウォッチとスマートリングを同時に装着しても、歩数は二重にカウントされません。",
      "一方のデバイスが充電中でも、もう一方がその時間帯をカバーし、空白が生じません。",
      "AndroidでもiPhoneでも同じように動作し、何も設定する必要がありません。",
    ],
    ko: [
      "이제 각 지표가 어디서 왔는지 표시할 수 있습니다. 예를 들어 수면 아래 '출처: 링'으로 표시됩니다.",
      "스마트워치와 스마트 링을 함께 착용해도 걸음 수가 두 번 계산되지 않습니다.",
      "한 기기가 충전 중일 때 다른 기기가 그 시간대를 빈틈없이 커버합니다.",
      "Android와 iPhone 모두 동일하게 작동하며, 아무것도 설정할 필요가 없습니다.",
    ],
  },
  hero: {
    kicker: { it: "Novità", en: "What's New", es: "Novedades", de: "Neuigkeiten", pt: "Novidades", fr: "Nouveautés", pl: "Nowości", tr: "Yeni Özellikler", nl: "Nieuw", ja: "新機能", ko: "새로운 기능" },
    title: {
      it: "Ora sai da quale dispositivo arriva ogni dato",
      en: "Now you know which device each metric comes from",
      es: "Ahora sabes de qué dispositivo proviene cada dato",
      de: "Jetzt siehst du, von welchem Gerät jeder Wert stammt",
      pt: "Agora você sabe de qual dispositivo vem cada dado",
      fr: "Vous savez maintenant de quel appareil provient chaque donnée",
      pl: "Teraz wiesz, z którego urządzenia pochodzi każdy dany pomiar",
      tr: "Şimdi her verinin hangi cihazdan geldiğini öğreniyorsunuz",
      nl: "Nu weet je van welk apparaat elke meting afkomstig is",
      ja: "各指標がどのデバイスから来るかわかるようになりました",
      ko: "이제 각 지표가 어떤 기기에서 오는지 알 수 있습니다",
    },
    subtitle: {
      it: "Orologio, anello e altri dispositivi nella stessa schermata, con l'indicazione chiara di chi ha misurato cosa. Una vista unica, senza conteggi doppi.",
      en: "Watch, ring and other devices in one screen, with a clear label of which one measured what. One view, no double counting.",
      es: "Reloj, anillo y otros dispositivos en una sola pantalla, con la indicación clara de cuál midió qué. Una vista única, sin conteos dobles.",
      de: "Uhr, Ring und andere Geräte auf einem Bildschirm, mit einer klaren Angabe, welches Gerät was gemessen hat. Eine Übersicht, keine Doppelzählungen.",
      pt: "Relógio, anel e outros dispositivos na mesma tela, com a indicação clara de quem mediu o quê. Uma visão única, sem contagens duplicadas.",
      fr: "Montre, bague connectée et autres appareils sur un seul écran, avec une indication claire de qui a mesuré quoi. Une vue unique, sans double comptage.",
      pl: "Zegarek, pierścień i inne urządzenia na jednym ekranie, z wyraźnym oznaczeniem, które z nich co zmierzyło. Jeden widok, bez podwójnego liczenia.",
      tr: "Akıllı saat, yüzük ve diğer cihazlar tek bir ekranda, hangisinin neyi ölçtüğünü belirten net bir etiketle. Tek bir görünüm, çift sayım yok.",
      nl: "Sporthorloge, slimme ring en andere apparaten op één scherm, met een duidelijk label wie wat heeft gemeten. Één overzicht, geen dubbele telling.",
      ja: "スマートウォッチ、スマートリング、その他のデバイスを1つの画面に表示し、どれが何を計測したかを明確にラベル付け。1つのビュー、二重カウントなし。",
      ko: "스마트워치, 스마트 링, 기타 기기를 하나의 화면에 표시하고 무엇이 무엇을 측정했는지 명확하게 표시합니다. 하나의 화면, 이중 계산 없음.",
    },
  },
  body: [
    {
      type: "paragraph",
      text: {
        it: "In FitMesh Sync i tuoi dispositivi lavorano insieme: orologio, anello e altri wearable confluiscono in un'unica schermata. Da oggi c'e una cosa in piu: vedi con chiarezza da quale dispositivo arriva ogni dato.",
        en: "In FitMesh Sync your devices work together: watch, ring and other wearables flow into one screen. From today there is something more: you can clearly see which device each metric comes from.",
        es: "En FitMesh Sync tus dispositivos trabajan juntos: reloj, anillo y otros wearables se reúnen en una sola pantalla. A partir de hoy hay algo más: puedes ver con claridad de qué dispositivo proviene cada dato.",
        de: "In FitMesh Sync arbeiten deine Geräte zusammen: Uhr, Ring und andere Wearables laufen in einem einzigen Bildschirm zusammen. Ab heute kommt etwas hinzu: Du siehst klar, von welchem Gerät jeder Wert stammt.",
        pt: "No FitMesh Sync os seus dispositivos trabalham juntos: relógio, anel e outros wearables se reúnem em uma única tela. A partir de hoje há algo a mais: você vê com clareza de qual dispositivo vem cada dado.",
        fr: "Dans FitMesh Sync, vos appareils fonctionnent ensemble: montre, bague connectée et autres wearables se retrouvent sur un seul écran. À partir d'aujourd'hui, il y a quelque chose de plus: vous voyez clairement de quel appareil provient chaque donnée.",
        pl: "W FitMesh Sync Twoje urządzenia pracują razem: zegarek, pierścień i inne urządzenia trafiają na jeden ekran. Od dziś jest coś więcej: widzisz wyraźnie, z którego urządzenia pochodzi każda metryka.",
        tr: "FitMesh Sync'te cihazlarınız birlikte çalışır: akıllı saat, yüzük ve diğer giyilebilir cihazlar tek bir ekranda toplanır. Bugünden itibaren bir şey daha var: her metriğin hangi cihazdan geldiğini net bir şekilde görürsünüz.",
        nl: "In FitMesh Sync werken je apparaten samen: sporthorloge, slimme ring en andere wearables komen samen op één scherm. Vanaf vandaag is er iets extra: je kunt duidelijk zien van welk apparaat elke meting afkomstig is.",
        ja: "FitMesh Syncではデバイスが連携して動作します：スマートウォッチ、スマートリング、その他のウェアラブルが1つの画面に集約されます。今日からさらに便利になりました：各指標がどのデバイスから来るかを明確に確認できます。",
        ko: "FitMesh Sync에서 기기들이 함께 작동합니다: 스마트워치, 스마트 링, 기타 웨어러블이 하나의 화면에 통합됩니다. 오늘부터 한 가지 더 추가되었습니다: 각 지표가 어떤 기기에서 오는지 명확하게 확인할 수 있습니다.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Vedi la fonte di ogni dato",
        en: "See the source of each metric",
        es: "Ve la fuente de cada dato",
        de: "Sieh die Quelle jedes Messwerts",
        pt: "Veja a fonte de cada dado",
        fr: "Voir la source de chaque donnée",
        pl: "Zobacz źródło każdej metryki",
        tr: "Her metriğin kaynağını görün",
        nl: "Zie de bron van elke meting",
        ja: "各指標のソースを確認する",
        ko: "각 지표의 출처 확인",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Sotto le metriche della giornata puo comparire una piccola etichetta, per esempio 'Fonte: anello' sotto il Sonno. Vuol dire che quel valore lo ha misurato l'anello, non l'orologio. Quando un dato arriva dal dispositivo che porti sempre al polso non serve dirlo, quindi l'etichetta compare solo quando e utile saperlo.",
        en: "Under the metrics for the day a small label can appear, for example 'Source: ring' under Sleep. It means that value was measured by the ring, not the watch. When a metric comes from the device you always wear there is no need to say it, so the label only shows up when it is useful to know.",
        es: "Bajo las métricas del día puede aparecer una pequeña etiqueta, por ejemplo 'Fuente: anillo' bajo el Sueño. Significa que ese valor lo midió el anillo, no el reloj. Cuando un dato proviene del dispositivo que siempre llevas puesto no hace falta indicarlo, por eso la etiqueta aparece solo cuando es útil saberlo.",
        de: "Unter den Messwerten des Tages kann ein kleines Label erscheinen, zum Beispiel 'Quelle: Ring' unter Schlaf. Das bedeutet, dass dieser Wert vom Ring gemessen wurde, nicht von der Uhr. Wenn ein Wert vom Gerät stammt, das du immer am Handgelenk trägst, muss das nicht angegeben werden. Das Label erscheint also nur, wenn es nützlich ist, es zu wissen.",
        pt: "Abaixo das métricas do dia pode aparecer uma pequena etiqueta, por exemplo 'Fonte: anel' sob o Sono. Significa que aquele valor foi medido pelo anel, não pelo relógio. Quando um dado vem do dispositivo que você sempre usa, não é preciso indicar. Então a etiqueta aparece apenas quando é útil saber.",
        fr: "Sous les métriques de la journée, une petite étiquette peut apparaître, par exemple 'Source: bague connectée' sous Sommeil. Cela signifie que cette valeur a été mesurée par la bague connectée, pas par la montre. Quand une donnée provient de l'appareil que vous portez toujours, il n'est pas nécessaire de le préciser. L'étiquette n'apparaît donc que quand c'est utile à savoir.",
        pl: "Pod metrykami danego dnia może pojawić się mała etykieta, na przykład 'Źródło: pierścień' pod Snem. Oznacza to, że tę wartość zmierzył pierścień, a nie zegarek. Gdy dana pochodzi z urządzenia, które zawsze nosisz na nadgarstku, nie trzeba tego mówić, więc etykieta pojawia się tylko wtedy, gdy warto o tym wiedzieć.",
        tr: "Günün metriklerinin altında küçük bir etiket görünebilir, örneğin Uyku altında 'Kaynak: yüzük'. Bu, o değerin akıllı saat tarafından değil, yüzük tarafından ölçüldüğü anlamına gelir. Bir metrik her zaman taktığınız cihazdan geldiğinde bunu belirtmeye gerek yoktur, bu yüzden etiket yalnızca bilinmesi faydalı olduğunda görünür.",
        nl: "Onder de metingen van de dag kan een klein label verschijnen, bijvoorbeeld 'Bron: ring' onder Slaap. Dat betekent dat die waarde door de ring is gemeten, niet door het sporthorloge. Als een meting afkomstig is van het apparaat dat je altijd draagt, hoeft dat niet vermeld te worden, dus het label verschijnt alleen wanneer het nuttig is om te weten.",
        ja: "その日の指標の下に小さなラベルが表示されることがあります。例えば、睡眠の下に「ソース：リング」と表示されます。これはその値がスマートウォッチではなくリングで計測されたことを意味します。常に装着しているデバイスからデータが来る場合は表示する必要がないため、知っておくと便利な場合にのみラベルが表示されます。",
        ko: "하루 지표 아래에 작은 레이블이 나타날 수 있습니다. 예를 들어 수면 아래 '출처: 링'으로 표시됩니다. 이는 해당 값이 스마트워치가 아닌 링으로 측정되었음을 의미합니다. 항상 착용하는 기기에서 데이터가 올 때는 표시할 필요가 없으므로, 알아두면 유용할 때만 레이블이 나타납니다.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Ora la fusione si vede nel grafico dei passi",
        en: "Now the fusion shows up in the steps chart",
        es: "Ahora la fusión se ve en el gráfico de pasos",
        de: "Jetzt siehst du die Fusion im Schritte-Diagramm",
        pt: "Agora a fusão aparece no gráfico de passos",
        fr: "La fusion apparaît maintenant dans le graphique des pas",
        pl: "Teraz fuzję widać na wykresie kroków",
        tr: "Birleştirme artık adım grafiğinde görünüyor",
        nl: "Nu zie je de samenvoeging in de stappengrafiek",
        ja: "歩数グラフでも統合が見えるようになりました",
        ko: "이제 걸음 수 그래프에서도 통합이 보입니다",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "C'è una novità concreta: quando disponibile, il grafico dei passi orari indica il dispositivo che ha misurato ogni ora (anello o orologio). Il grafico compare solo quando la somma delle ore combacia esattamente col totale ufficiale del giorno: se non combacia, FitMesh non lo forza, mostra comunque il totale del giorno. È lo stesso principio di trasparenza del battito orario, applicato ai passi: quando il grafico c'è, vedi come si è formato il totale, ora per ora.",
        en: "There is a concrete update: when available, the hourly steps chart shows which device measured each hour (ring or watch). The chart only appears when the sum of the hours matches the day's official total exactly; if it doesn't match, FitMesh does not force it, it still shows the day's total. It is the same transparency idea as the hourly heart rate, applied to steps: when the chart is there, you can see how the total was built, hour by hour.",
        es: "Hay una novedad concreta: cuando está disponible, el gráfico de pasos por hora indica qué dispositivo midió cada hora (anillo o reloj). El gráfico aparece solo cuando la suma de las horas coincide exactamente con el total oficial del día: si no coincide, FitMesh no lo fuerza, igualmente muestra el total del día. Es la misma idea de transparencia de la frecuencia cardíaca por hora, aplicada a los pasos: cuando el gráfico está, ves cómo se formó el total, hora a hora.",
        de: "Es gibt eine konkrete Neuerung: Wenn verfügbar, zeigt das Diagramm der stündlichen Schritte an, welches Gerät jede Stunde gemessen hat (Ring oder Uhr). Das Diagramm erscheint nur, wenn die Summe der Stunden exakt mit dem offiziellen Tagestotal übereinstimmt; stimmt sie nicht überein, erzwingt FitMesh es nicht, sondern zeigt weiterhin das Tagestotal. Es ist dieselbe Transparenz-Idee wie bei der stündlichen Herzfrequenz, angewendet auf die Schritte: Ist das Diagramm da, siehst du, wie das Total entstanden ist, Stunde für Stunde.",
        pt: "Há uma novidade concreta: quando disponível, o gráfico de passos por hora indica qual dispositivo mediu cada hora (anel ou relógio). O gráfico aparece apenas quando a soma das horas coincide exatamente com o total oficial do dia: se não coincidir, FitMesh não força, continua mostrando o total do dia. É a mesma ideia de transparência da frequência cardíaca por hora, aplicada aos passos: quando o gráfico existe, você vê como o total se formou, hora a hora.",
        fr: "Il y a une nouveauté concrète: quand il est disponible, le graphique des pas par heure indique quel appareil a mesuré chaque heure (bague connectée ou montre). Le graphique n'apparaît que lorsque la somme des heures correspond exactement au total officiel de la journée: si elle ne correspond pas, FitMesh ne le force pas, il continue d'afficher le total de la journée. C'est la même idée de transparence que pour la fréquence cardiaque par heure, appliquée aux pas: quand le graphique est là, vous voyez comment le total s'est construit, heure par heure.",
        pl: "Jest konkretna nowość: gdy jest dostępny, wykres kroków godzina po godzinie wskazuje, które urządzenie mierzyło w danej godzinie (pierścień lub zegarek). Wykres pojawia się tylko wtedy, gdy suma godzin dokładnie zgadza się z oficjalnym dziennym podsumowaniem: jeśli się nie zgadza, FitMesh go nie wymusza, nadal pokazuje sumę dnia. To ta sama zasada przejrzystości co przy tętnie godzinowym, zastosowana do kroków: gdy wykres jest widoczny, widzisz, jak powstała suma, godzina po godzinie.",
        tr: "Somut bir yenilik var: mevcut olduğunda, saatlik adım grafiği her saat hangi cihazın ölçüm yaptığını gösterir (yüzük ya da akıllı saat). Grafik yalnızca saatlerin toplamı günün resmi toplamıyla tam olarak örtüştüğünde görünür: örtüşmezse FitMesh grafiği zorlamaz, yine de günün toplamını gösterir. Bu, saatlik kalp atışındaki aynı şeffaflık fikrinin adımlara uygulanmasıdır: grafik varsa, toplamın saat saat nasıl oluştuğunu görürsünüz.",
        nl: "Er is een concrete vernieuwing: indien beschikbaar, geeft de grafiek met stappen per uur aan welk apparaat elk uur heeft gemeten (ring of horloge). De grafiek verschijnt alleen wanneer de som van de uren precies overeenkomt met het officiële dagtotaal: komt dat niet overeen, dan forceert FitMesh de grafiek niet en toont het gewoon het dagtotaal. Het is hetzelfde transparantie-idee als bij de hartslag per uur, toegepast op stappen: als de grafiek er is, zie je hoe het totaal is opgebouwd, uur voor uur.",
        ja: "具体的な新機能があります。利用できる場合、1時間ごとの歩数グラフには、その時間に計測していたデバイス（リングまたはスマートウォッチ）が示されます。このグラフは、各時間の合計がその日の公式な合計と正確に一致する場合にのみ表示されます。一致しない場合、FitMeshは無理にグラフを表示せず、その日の合計はそのまま表示されます。これは1時間ごとの心拍数と同じ透明性の考え方を歩数に適用したものです。グラフが表示されているときは、合計が1時間ごとにどう積み上がったかを確認できます。",
        ko: "구체적인 새 기능이 있습니다. 사용 가능한 경우, 시간별 걸음 수 그래프는 각 시간대에 어떤 기기가 측정했는지(링 또는 스마트워치) 보여줍니다. 이 그래프는 시간별 합계가 그날의 공식 총합과 정확히 일치할 때만 표시됩니다. 일치하지 않으면 FitMesh는 그래프를 억지로 표시하지 않고, 그날의 총합은 그대로 표시됩니다. 이는 시간별 심박수와 같은 투명성 원칙을 걸음 수에 적용한 것입니다. 그래프가 있을 때는 합계가 시간별로 어떻게 만들어졌는지 확인할 수 있습니다.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Niente conteggi doppi",
        en: "No double counting",
        es: "Sin conteos dobles",
        de: "Keine Doppelzählungen",
        pt: "Sem contagens duplicadas",
        fr: "Aucun double comptage",
        pl: "Bez podwójnego liczenia",
        tr: "Çift sayım yok",
        nl: "Geen dubbele telling",
        ja: "二重カウントなし",
        ko: "이중 계산 없음",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Se indossi piu dispositivi nello stesso momento, contano gli stessi passi reali. FitMesh Sync non li somma: tiene il quadro corretto della tua giornata, senza gonfiare i numeri.",
        en: "If you wear multiple devices at the same time, they count the same real steps. FitMesh Sync does not add them up: it keeps the correct picture of your day, without inflating the numbers.",
        es: "Si llevas varios dispositivos al mismo tiempo, todos cuentan los mismos pasos reales. FitMesh Sync no los suma: mantiene el cuadro correcto de tu día, sin inflar los números.",
        de: "Wenn du mehrere Geräte gleichzeitig trägst, zählen sie dieselben echten Schritte. FitMesh Sync addiert sie nicht: Es zeigt das korrekte Bild deines Tages, ohne die Zahlen aufzublähen.",
        pt: "Se você usa vários dispositivos ao mesmo tempo, eles contam os mesmos passos reais. FitMesh Sync não os soma: mantém o quadro correto do seu dia, sem inflar os números.",
        fr: "Si vous portez plusieurs appareils en même temps, ils comptent les mêmes pas réels. FitMesh Sync ne les additionne pas: il conserve le tableau correct de votre journée, sans gonfler les chiffres.",
        pl: "Jeśli nosisz kilka urządzeń jednocześnie, liczą one te same rzeczywiste kroki. FitMesh Sync ich nie sumuje: zachowuje poprawny obraz Twojego dnia, bez zawyżania liczb.",
        tr: "Aynı anda birden fazla cihaz takıyorsanız, hepsi aynı gerçek adımları sayar. FitMesh Sync bunları toplamaz: gününüzün doğru tablosunu korur, rakamları şişirmeden.",
        nl: "Als je meerdere apparaten tegelijk draagt, tellen ze dezelfde echte stappen. FitMesh Sync telt ze niet op: het behoudt het correcte beeld van je dag, zonder de cijfers op te blazen.",
        ja: "複数のデバイスを同時に装着しても、同じ実際の歩数をカウントします。FitMesh Syncはそれらを合計しません：数字を膨らませることなく、あなたの一日の正確な記録を保ちます。",
        ko: "여러 기기를 동시에 착용해도 동일한 실제 걸음 수를 계산합니다. FitMesh Sync는 이를 합산하지 않습니다: 숫자를 부풀리지 않고 하루의 정확한 기록을 유지합니다.",
      },
    },
    {
      type: "callout",
      variant: "info",
      title: {
        it: "Vuoi capire come gestiamo piu dispositivi nel dettaglio?",
        en: "Want to understand how we handle multiple devices in detail?",
        es: "¿Quieres entender cómo gestionamos varios dispositivos en detalle?",
        de: "Möchtest du verstehen, wie wir mit mehreren Geräten umgehen?",
        pt: "Quer entender como gerenciamos vários dispositivos em detalhes?",
        fr: "Vous souhaitez comprendre comment nous gérons plusieurs appareils en détail?",
        pl: "Chcesz dokładnie zrozumieć, jak obsługujemy wiele urządzeń?",
        tr: "Birden fazla cihazı ayrıntılı olarak nasıl yönettiğimizi anlamak ister misiniz?",
        nl: "Wil je begrijpen hoe we met meerdere apparaten omgaan in detail?",
        ja: "複数デバイスの詳細な管理方法を理解したいですか？",
        ko: "여러 기기를 어떻게 처리하는지 자세히 이해하고 싶으신가요?",
      },
      body: {
        it: "Abbiamo una guida dedicata che spiega tutto, con esempi per ogni combinazione: [piu smartwatch insieme senza dati doppi](/it/blog/piu-smartwatch-insieme-dati-doppi).",
        en: "We have a dedicated guide that explains everything, with examples for each combination: [multiple smartwatches together without double data](/en/blog/piu-smartwatch-insieme-dati-doppi).",
        es: "Tenemos una guía dedicada que explica todo, con ejemplos para cada combinación: [varios smartwatches a la vez sin datos duplicados](/es/blog/piu-smartwatch-insieme-dati-doppi).",
        de: "Wir haben eine eigene Anleitung, die alles erklärt, mit Beispielen für jede Kombination: [mehrere Smartwatches gleichzeitig ohne doppelte Daten](/de/blog/piu-smartwatch-insieme-dati-doppi).",
        pt: "Temos um guia dedicado que explica tudo, com exemplos para cada combinação: [vários smartwatches juntos sem dados duplicados](/pt/blog/piu-smartwatch-insieme-dati-doppi).",
        fr: "Nous avons un guide dédié qui explique tout, avec des exemples pour chaque combinaison: [plusieurs montres connectées ensemble sans données en double](/fr/blog/piu-smartwatch-insieme-dati-doppi).",
        pl: "Mamy dedykowany przewodnik, który wyjaśnia wszystko, z przykładami dla każdej kombinacji: [kilka smartwatchy razem bez podwójnych danych](/pl/blog/piu-smartwatch-insieme-dati-doppi).",
        tr: "Her kombinasyon için örneklerle her şeyi açıklayan özel bir rehberimiz var: [birden fazla akıllı saat birlikte, veriler iki kez sayılmadan](/tr/blog/piu-smartwatch-insieme-dati-doppi).",
        nl: "We hebben een speciale gids die alles uitlegt, met voorbeelden voor elke combinatie: [meerdere smartwatches samen zonder dubbele gegevens](/nl/blog/piu-smartwatch-insieme-dati-doppi).",
        ja: "すべてを説明した専用ガイドがあり、各組み合わせの例が含まれています：[複数のスマートウォッチを重複なしで使用](/ja/blog/piu-smartwatch-insieme-dati-doppi)。",
        ko: "모든 것을 설명하는 전용 가이드가 있으며 각 조합에 대한 예시가 포함되어 있습니다: [이중 데이터 없이 스마트워치 여러 개 함께 사용](/ko/blog/piu-smartwatch-insieme-dati-doppi).",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Orologio in carica? Ci pensa un altro dispositivo",
        en: "Watch charging? Another device covers it",
        es: "¿Reloj cargando? Otro dispositivo lo cubre",
        de: "Uhr lädt? Ein anderes Gerät übernimmt",
        pt: "Relógio carregando? Outro dispositivo cobre",
        fr: "Montre en charge? Un autre appareil prend le relais",
        pl: "Zegarek się ładuje? Zajmie się tym inne urządzenie",
        tr: "Akıllı saat şarjda mı? Başka bir cihaz devreye girer",
        nl: "Horloge aan het opladen? Een ander apparaat neemt het over",
        ja: "スマートウォッチが充電中？別のデバイスがカバーします",
        ko: "스마트워치 충전 중? 다른 기기가 커버합니다",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Capita di lasciare l'orologio in carica per qualche ora. In quel periodo, se indossi l'anello, e lui a tenere il conto. Quando guardi la giornata, le ore coperte da dispositivi diversi si uniscono in un quadro unico, senza buchi e senza doppioni.",
        en: "It happens to leave the watch charging for a few hours. During that time, if you wear the ring, the ring keeps count. When you look at your day, the hours covered by different devices come together into one picture, with no gaps and no duplicates.",
        es: "A veces dejas el reloj cargando durante unas horas. En ese tiempo, si llevas el anillo, es él quien lleva la cuenta. Cuando consultas tu día, las horas cubiertas por distintos dispositivos se unen en un cuadro único, sin huecos y sin duplicados.",
        de: "Es kommt vor, dass du die Uhr ein paar Stunden lädt. In dieser Zeit übernimmt der Ring die Aufzeichnung, wenn du ihn trägst. Wenn du deinen Tag abrufst, werden die von verschiedenen Geräten abgedeckten Stunden zu einem einzigen Bild zusammengefügt, ohne Lücken und ohne Duplikate.",
        pt: "Às vezes você deixa o relógio carregando por algumas horas. Nesse período, se você estiver usando o anel, é ele que mantém o registro. Quando você consulta o seu dia, as horas cobertas por dispositivos diferentes se unem em um quadro único, sem lacunas e sem duplicatas.",
        fr: "Il arrive de laisser la montre se recharger pendant quelques heures. Pendant ce temps, si vous portez la bague connectée, c'est elle qui enregistre. Quand vous consultez votre journée, les heures couvertes par différents appareils se réunissent en une seule vue, sans lacune et sans doublons.",
        pl: "Zdarza się zostawić zegarek na ładowaniu na kilka godzin. W tym czasie, jeśli nosisz pierścień, to on prowadzi licznik. Gdy spojrzysz na swój dzień, godziny pokryte przez różne urządzenia łączą się w jeden obraz, bez luk i bez duplikatów.",
        tr: "Akıllı saati birkaç saat şarjda bırakmak olur. Bu süre boyunca yüzüğü takıyorsanız, sayımı o tutar. Gününüze baktığınızda, farklı cihazların kapsadığı saatler tek bir tablo halinde birleşir, boşluk olmadan ve tekrar olmadan.",
        nl: "Het komt voor dat je het sporthorloge een paar uur oplaadt. In die tijd houdt de slimme ring de telling bij, als je hem draagt. Wanneer je je dag bekijkt, komen de uren die door verschillende apparaten zijn gedekt samen in één beeld, zonder hiaten en zonder duplicaten.",
        ja: "スマートウォッチを数時間充電することがあります。その間、スマートリングを着けていれば、リングが記録を続けます。一日を確認するとき、異なるデバイスがカバーした時間帯が一つの記録にまとまり、空白も重複もありません。",
        ko: "스마트워치를 몇 시간 동안 충전하는 경우가 있습니다. 그 시간 동안 스마트 링을 착용하고 있으면 링이 기록을 이어갑니다. 하루를 확인할 때 서로 다른 기기가 커버한 시간들이 하나의 기록으로 통합되어 빈틈도 중복도 없습니다.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Lo stesso su Android e iPhone",
        en: "The same on Android and iPhone",
        es: "Lo mismo en Android y en iPhone",
        de: "Gleich auf Android und iPhone",
        pt: "O mesmo no Android e no iPhone",
        fr: "Pareil sur Android et iPhone",
        pl: "Tak samo na Androidzie i iPhonie",
        tr: "Android ve iPhone'da aynı",
        nl: "Hetzelfde op Android en iPhone",
        ja: "AndroidでもiPhoneでも同じ",
        ko: "Android와 iPhone 모두 동일",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Che tu usi un telefono Android o un iPhone, il comportamento e identico: i dati dei tuoi dispositivi si uniscono nella stessa vista, con la stessa trasparenza sulla fonte. Se usi entrambi, trovi qualche dettaglio in piu nella pagina dedicata ai [due telefoni sullo stesso account](/it/lp/due-telefoni).",
        en: "Whether you use an Android phone or an iPhone, the behavior is identical: your devices' data come together in the same view, with the same transparency about the source. If you use both, you can find more details on the page about [two phones on the same account](/en/lp/due-telefoni).",
        es: "Tanto si usas un teléfono Android como un iPhone, el comportamiento es idéntico: los datos de tus dispositivos se unen en la misma vista, con la misma transparencia sobre la fuente. Si usas ambos, encontrarás más detalles en la página sobre [dos teléfonos en la misma cuenta](/es/lp/due-telefoni).",
        de: "Ob du ein Android-Telefon oder ein iPhone verwendest, das Verhalten ist identisch: Die Daten deiner Geräte werden in derselben Ansicht zusammengeführt, mit derselben Transparenz über die Quelle. Wenn du beide nutzt, findest du weitere Details auf der Seite über [zwei Telefone auf demselben Konto](/de/lp/due-telefoni).",
        pt: "Seja você usar um telefone Android ou um iPhone, o comportamento é idêntico: os dados dos seus dispositivos se unem na mesma visão, com a mesma transparência sobre a fonte. Se você usa os dois, encontrará mais detalhes na página sobre [dois telefones na mesma conta](/pt/lp/due-telefoni).",
        fr: "Que vous utilisiez un téléphone Android ou un iPhone, le comportement est identique: les données de vos appareils se réunissent dans la même vue, avec la même transparence sur la source. Si vous utilisez les deux, vous trouverez plus de détails sur la page [deux téléphones sur le même compte](/fr/lp/due-telefoni).",
        pl: "Niezależnie od tego, czy używasz telefonu z Androidem czy iPhone'a, działanie jest identyczne: dane Twoich urządzeń łączą się w tym samym widoku, z taką samą przejrzystością źródła. Jeśli używasz obu, więcej szczegółów znajdziesz na stronie poświęconej [dwóm telefonom na tym samym koncie](/pl/lp/due-telefoni).",
        tr: "İster Android telefon ister iPhone kullanın, davranış aynıdır: cihazlarınızın verileri aynı görünümde birleşir, kaynak konusunda aynı şeffaflıkla. İkisini birden kullanıyorsanız, [aynı hesapta iki telefon](/tr/lp/due-telefoni) sayfasında daha fazla ayrıntı bulabilirsiniz.",
        nl: "Of je nu een Android-telefoon of een iPhone gebruikt, het gedrag is identiek: de gegevens van je apparaten komen samen in dezelfde weergave, met dezelfde transparantie over de bron. Als je beide gebruikt, vind je meer details op de pagina over [twee telefoons op hetzelfde account](/nl/lp/due-telefoni).",
        ja: "AndroidスマートフォンでもiPhoneでも、動作は同じです：デバイスのデータが同じビューにまとめられ、ソースについて同じ透明性が保たれます。両方を使用している場合は、[同じアカウントで2台のスマートフォン](/ja/lp/due-telefoni)のページで詳細をご確認いただけます。",
        ko: "Android 스마트폰이든 iPhone이든 동작은 동일합니다: 기기 데이터가 동일한 화면에 통합되며 출처에 대해 동일한 투명성이 유지됩니다. 두 가지를 모두 사용한다면 [같은 계정의 스마트폰 두 대](/ko/lp/due-telefoni) 페이지에서 더 자세한 내용을 확인할 수 있습니다.",
      },
    },
    {
      type: "cta",
      title: {
        it: "Provalo con i tuoi dispositivi",
        en: "Try it with your devices",
        es: "Pruébalo con tus dispositivos",
        de: "Probiere es mit deinen Geräten",
        pt: "Experimente com os seus dispositivos",
        fr: "Essayez-le avec vos appareils",
        pl: "Wypróbuj to na swoich urządzeniach",
        tr: "Kendi cihazlarınızla deneyin",
        nl: "Probeer het met je apparaten",
        ja: "あなたのデバイスで試してみる",
        ko: "기기로 사용해 보기",
      },
      body: {
        it: "Scarica FitMesh, collega orologio e anello e guarda la giornata unita in un solo posto, con la fonte di ogni dato sempre chiara.",
        en: "Download FitMesh, connect your watch and ring, and see your day brought together in one place, with the source of each metric always clear.",
        es: "Descarga FitMesh, conecta tu reloj y tu anillo, y ve cómo tu día se reúne en un solo lugar, con la fuente de cada dato siempre clara.",
        de: "Lade FitMesh herunter, verbinde Uhr und Ring und sieh, wie dein Tag an einem Ort zusammengeführt wird, mit der Quelle jedes Messwerts immer klar sichtbar.",
        pt: "Baixe o FitMesh, conecte o relógio e o anel e veja o seu dia reunido em um só lugar, com a fonte de cada dado sempre clara.",
        fr: "Téléchargez FitMesh, connectez votre montre et votre bague connectée et voyez votre journée réunie en un seul endroit, avec la source de chaque donnée toujours clairement indiquée.",
        pl: "Pobierz FitMesh, połącz zegarek i pierścień i zobacz cały swój dzień w jednym miejscu, z zawsze jasnym źródłem każdej metryki.",
        tr: "FitMesh'i indirin, akıllı saatinizi ve yüzüğünüzü bağlayın ve gününüzü tek bir yerde toplanmış olarak görün, her metriğin kaynağı her zaman net.",
        nl: "Download FitMesh, verbind je sporthorloge en slimme ring, en zie je dag samengebracht op één plek, met de bron van elke meting altijd duidelijk.",
        ja: "FitMeshをダウンロードし、スマートウォッチとスマートリングを接続して、各指標のソースが常に明確な状態で、あなたの一日が一か所にまとまるのを確認してください。",
        ko: "FitMesh를 다운로드하고, 스마트워치와 스마트 링을 연결하여 각 지표의 출처가 항상 명확하게 표시되는 하나의 화면으로 하루를 확인해 보세요.",
      },
      ctaLabel: {
        it: "Scarica FitMesh e prova gratis",
        en: "Download FitMesh and try it free",
        es: "Descarga FitMesh y pruébala gratis",
        de: "FitMesh herunterladen und kostenlos testen",
        pt: "Baixe o FitMesh e experimente grátis",
        fr: "Télécharger FitMesh et l'essayer gratuitement",
        pl: "Pobierz FitMesh i wypróbuj za darmo",
        tr: "FitMesh'i indir ve ücretsiz dene",
        nl: "Download FitMesh en probeer het gratis",
        ja: "FitMesh をダウンロードして無料で試す",
        ko: "FitMesh 다운로드하고 무료로 사용해 보기",
      },
      ctaHref: {
        it: "/it#download",
        en: "/en#download",
      },
    },
  ],
  faq: [
    {
      q: {
        it: "Perche alcune metriche mostrano la fonte e altre no?",
        en: "Why do some metrics show the source and others do not?",
        es: "¿Por qué algunas métricas muestran la fuente y otras no?",
        de: "Warum zeigen manche Messwerte die Quelle und andere nicht?",
        pt: "Por que algumas métricas mostram a fonte e outras não?",
        fr: "Pourquoi certaines métriques affichent la source et d'autres non?",
        pl: "Dlaczego niektóre metryki pokazują źródło, a inne nie?",
        tr: "Neden bazı metrikler kaynak gösteriyorken, diğeri ise göstermiyor?",
        nl: "Waarom tonen sommige metingen de bron en andere niet?",
        ja: "なぜ一部の指標はソースを表示し、他は表示しないのですか？",
        ko: "왜 일부 지표는 출처를 표시하고 다른 것들은 표시하지 않나요?",
      },
      a: {
        it: "L'etichetta appare solo quando il dato arriva da un dispositivo diverso da quello che indossi di solito, cosi resta un'informazione utile e non rumore. Quando il dato arriva dal dispositivo principale, l'etichetta non serve.",
        en: "The label only appears when the metric comes from a device different from the one you usually wear, so it stays useful information and not noise. When the metric comes from your main device, the label is not needed.",
        es: "La etiqueta aparece solo cuando el dato proviene de un dispositivo distinto al que llevas normalmente, para que sea información útil y no ruido. Cuando el dato proviene de tu dispositivo principal, la etiqueta no es necesaria.",
        de: "Das Label erscheint nur, wenn der Wert von einem anderen Gerät als dem stammt, das du normalerweise trägst. So bleibt es eine nützliche Information und kein Lärm. Wenn der Wert vom Hauptgerät kommt, wird das Label nicht benötigt.",
        pt: "A etiqueta aparece apenas quando o dado vem de um dispositivo diferente do que você costuma usar, para que continue sendo uma informação útil e não ruído. Quando o dado vem do dispositivo principal, a etiqueta não é necessária.",
        fr: "L'étiquette n'apparaît que lorsque la donnée provient d'un appareil différent de celui que vous portez habituellement, pour rester une information utile et non du bruit. Quand la donnée vient de votre appareil principal, l'étiquette n'est pas nécessaire.",
        pl: "Etykieta pojawia się tylko wtedy, gdy metryka pochodzi z urządzenia innego niż to, które zwykle nosisz, dzięki czemu pozostaje użyteczną informacją, a nie szumem. Gdy metryka pochodzi z głównego urządzenia, etykieta nie jest potrzebna.",
        tr: "Etiket yalnızca, metrik genellikle taktığınız cihazdan farklı bir cihazdan geldiğinde görünür, böylece gürültü değil, faydalı bir bilgi olarak kalır. Metrik ana cihazınızdan geldiğinde etikete gerek kalmaz.",
        nl: "Het label verschijnt alleen wanneer de meting afkomstig is van een ander apparaat dan het apparaat dat je gewoonlijk draagt, zodat het nuttige informatie blijft en geen ruis. Wanneer de meting van je hoofdapparaat komt, is het label niet nodig.",
        ja: "ラベルは、通常着用しているデバイスとは異なるデバイスから指標が来る場合にのみ表示されるため、有用な情報として残り、ノイズになりません。指標がメインデバイスから来る場合は、ラベルは必要ありません。",
        ko: "레이블은 평소에 착용하는 기기와 다른 기기에서 지표가 올 때만 표시되어, 유용한 정보로 유지되고 노이즈가 되지 않습니다. 주 기기에서 지표가 올 때는 레이블이 필요하지 않습니다.",
      },
    },
    {
      q: {
        it: "Se ho orologio e anello, i passi si sommano?",
        en: "If I have a watch and a ring, are steps added up?",
        es: "Si tengo reloj y anillo, ¿los pasos se suman?",
        de: "Werden die Schritte addiert, wenn ich Uhr und Ring trage?",
        pt: "Se eu tiver relógio e anel, os passos são somados?",
        fr: "Si j'ai une montre et une bague connectée, les pas sont-ils additionnés?",
        pl: "Jeśli mam zegarek i pierścień, czy kroki się sumują?",
        tr: "Akıllı saatim ve yüzüğüm varsa, adımlar toplanır mı?",
        nl: "Als ik een sporthorloge en een slimme ring heb, worden de stappen bij elkaar opgeteld?",
        ja: "スマートウォッチとスマートリングを持っている場合、歩数は合算されますか？",
        ko: "스마트워치와 스마트 링이 있으면 걸음 수가 합산되나요?",
      },
      a: {
        it: "No. Contano gli stessi passi reali, quindi FitMesh Sync li unisce senza raddoppiarli. Il numero che vedi e il quadro corretto della giornata, non la somma dei dispositivi.",
        en: "No. They count the same real steps, so FitMesh Sync brings them together without doubling them. The number you see is the correct picture of your day, not the sum of the devices.",
        es: "No. Cuentan los mismos pasos reales, así que FitMesh Sync los une sin duplicarlos. El número que ves es el cuadro correcto de tu día, no la suma de los dispositivos.",
        de: "Nein. Sie zählen dieselben echten Schritte, also führt FitMesh Sync sie zusammen, ohne sie zu verdoppeln. Die Zahl, die du siehst, ist das korrekte Bild deines Tages, nicht die Summe der Geräte.",
        pt: "Não. Eles contam os mesmos passos reais, então FitMesh Sync os une sem duplicá-los. O número que você vê é o quadro correto do seu dia, não a soma dos dispositivos.",
        fr: "Non. Ils comptent les mêmes pas réels, donc FitMesh Sync les regroupe sans les doubler. Le chiffre que vous voyez est le tableau correct de votre journée, pas la somme des appareils.",
        pl: "Nie. Liczą one te same rzeczywiste kroki, więc FitMesh Sync łączy je bez podwajania. Liczba, którą widzisz, to poprawny obraz Twojego dnia, a nie suma urządzeń.",
        tr: "Hayır. Aynı gerçek adımlar sayılır, bu nedenle FitMesh Sync onları çift saymaz. Gördüğün sayı, cihazların toplamı değil, günün doğru tablosudur.",
        nl: "Nee. Ze tellen dezelfde echte stappen, dus FitMesh Sync brengt ze samen zonder ze te verdubbelen. Het getal dat je ziet is het correcte beeld van je dag, niet de som van de apparaten.",
        ja: "いいえ。同じ実際の歩数をカウントするため、FitMesh Syncはそれらを二重にすることなく統合します。表示される数字はあなたの一日の正確な記録であり、デバイスの合計ではありません。",
        ko: "아니요. 동일한 실제 걸음 수를 계산하므로 FitMesh Sync는 이를 두 배로 늘리지 않고 통합합니다. 표시되는 숫자는 기기의 합이 아닌 하루의 정확한 기록입니다.",
      },
    },
    {
      q: {
        it: "Funziona se uso due telefoni, Android e iPhone?",
        en: "Does it work if I use two phones, Android and iPhone?",
        es: "¿Funciona si uso dos teléfonos, Android e iPhone?",
        de: "Funktioniert es, wenn ich zwei Telefone benutze, Android und iPhone?",
        pt: "Funciona se eu usar dois telefones, Android e iPhone?",
        fr: "Cela fonctionne-t-il si j'utilise deux téléphones, Android et iPhone?",
        pl: "Czy działa, jeśli używam dwóch telefonów, Android i iPhone?",
        tr: "Android ve iPhone olmak üzere iki telefon kullanırsam çalışır mı?",
        nl: "Werkt het als ik twee telefoons gebruik, Android en iPhone?",
        ja: "AndroidとiPhoneの2台のスマートフォンを使用する場合でも機能しますか？",
        ko: "Android와 iPhone 두 대의 스마트폰을 사용하는 경우에도 작동하나요?",
      },
      a: {
        it: "Si. I dati confluiscono nello stesso account e si uniscono nella stessa vista, con la fonte di ogni metrica indicata dove serve.",
        en: "Yes. The data flow into the same account and come together in the same view, with the source of each metric shown where it helps.",
        es: "Sí. Los datos fluyen hacia la misma cuenta y se unen en la misma vista, con la fuente de cada métrica indicada donde corresponde.",
        de: "Ja. Die Daten laufen in dasselbe Konto und werden in derselben Ansicht zusammengeführt, mit der Quelle jedes Messwerts dort angegeben, wo es hilfreich ist.",
        pt: "Sim. Os dados fluem para a mesma conta e se unem na mesma visão, com a fonte de cada métrica indicada onde for útil.",
        fr: "Oui. Les données confluent vers le même compte et se retrouvent dans la même vue, avec la source de chaque métrique indiquée là où c'est utile.",
        pl: "Tak. Dane trafiają na to samo konto i łączą się w tym samym widoku, ze wskazaniem źródła każdej metryki tam, gdzie jest to przydatne.",
        tr: "Evet. Veriler aynı hesapta toplanır ve aynı görünümde birleşir; her metriğin kaynağı faydalı olduğu yerlerde gösterilir.",
        nl: "Ja. De gegevens stromen naar hetzelfde account en komen samen in dezelfde weergave, met de bron van elke meting weergegeven waar het helpt.",
        ja: "はい。データは同じアカウントに流れ込み、同じビューにまとめられ、各指標のソースが役立つ場所に表示されます。",
        ko: "예. 데이터는 같은 계정으로 흘러들어 동일한 화면에 통합되며, 각 지표의 출처가 도움이 되는 곳에 표시됩니다.",
      },
    },
    {
      q: {
        it: "Devo configurare qualcosa?",
        en: "Do I need to configure anything?",
        es: "¿Tengo que configurar algo?",
        de: "Muss ich etwas einrichten?",
        pt: "Preciso configurar alguma coisa?",
        fr: "Dois-je configurer quelque chose?",
        pl: "Czy muszę coś konfigurować?",
        tr: "Herhangi bir ayar yapmam gerekir mi?",
        nl: "Moet ik iets instellen?",
        ja: "何か設定する必要がありますか？",
        ko: "무언가를 설정해야 하나요?",
      },
      a: {
        it: "No. Basta avere i dispositivi collegati: l'unione dei dati e l'indicazione della fonte sono automatiche.",
        en: "No. Just have your devices connected: merging the data and showing the source happen automatically.",
        es: "No. Solo tienes que tener los dispositivos conectados: la unión de los datos y la indicación de la fuente son automáticas.",
        de: "Nein. Verbinde einfach deine Geräte: Die Zusammenführung der Daten und die Anzeige der Quelle erfolgen automatisch.",
        pt: "Não. Basta ter os dispositivos conectados: a fusão dos dados e a indicação da fonte são automáticas.",
        fr: "Non. Il suffit d'avoir vos appareils connectés: la fusion des données et l'indication de la source se font automatiquement.",
        pl: "Nie. Wystarczy połączyć urządzenia: łączenie danych i wskazanie źródła odbywa się automatycznie.",
        tr: "Hayır. Cihazlarınızın bağlı olması yeterli: verilerin birleştirilmesi ve kaynağın gösterilmesi otomatik olarak gerçekleşir.",
        nl: "Nee. Je hoeft alleen je apparaten te verbinden: het samenvoegen van de gegevens en het tonen van de bron gebeuren automatisch.",
        ja: "いいえ。デバイスを接続するだけです：データの統合とソースの表示は自動的に行われます。",
        ko: "아니요. 기기를 연결하기만 하면 됩니다: 데이터 병합과 출처 표시가 자동으로 이루어집니다.",
      },
    },
  ],
  related: [
    "piu-smartwatch-insieme-dati-doppi",
    "sync-them-all",
    "colmi-ring-fitmesh",
    "anello-vs-smartwatch",
    "steps-total-vs-hourly-chart",
  ],
};
