import type { BlogPost } from "../types";

export const post: BlogPost = {
  slug: "novita-fitmesh-su-app-store",
  category: "news",
  publishedAt: "2026-06-29",
  updatedAt: "2026-06-29",
  ldType: "BlogPosting",
  readMinutes: 3,
  primaryKeyword: {
    it: "fitmesh sync app store",
    en: "fitmesh sync app store",
    es: "fitmesh sync app store",
    de: "fitmesh sync app store",
    pt: "fitmesh sync app store",
    fr: "fitmesh sync app store",
    pl: "fitmesh sync app store",
    tr: "fitmesh sync app store",
    nl: "fitmesh sync app store",
    ja: "fitmesh sync app store",
    ko: "fitmesh sync app store",
  },
  secondaryKeywords: {
    it: [
      "fitmesh sync iphone",
      "app salute iphone smartwatch android",
      "ponte apple salute wearable android",
      "fitmesh sync ios disponibile",
      "dashboard salute android iphone",
    ],
    en: [
      "fitmesh sync iphone",
      "apple health android smartwatch sync",
      "apple health bridge wearable",
      "fitmesh sync ios available",
      "android iphone health dashboard",
    ],
    es: [
      "fitmesh sync iphone",
      "app salud iphone smartwatch android",
      "puente apple salud wearable android",
      "fitmesh sync ios disponible",
      "panel salud android iphone",
    ],
    de: [
      "fitmesh sync iphone",
      "apple health android smartwatch sync",
      "apple health brücke wearable",
      "fitmesh sync ios verfügbar",
      "gesundheits-dashboard android iphone",
    ],
    pt: [
      "fitmesh sync iphone",
      "app saúde iphone smartwatch android",
      "ponte apple saúde wearable android",
      "fitmesh sync ios disponível",
      "painel saúde android iphone",
    ],
    fr: [
      "fitmesh sync iphone",
      "app santé iphone smartwatch android",
      "passerelle apple santé wearable android",
      "fitmesh sync ios disponible",
      "tableau de bord santé android iphone",
    ],
    pl: [
      "fitmesh sync iphone",
      "aplikacja zdrowia iphone smartwatch android",
      "most apple health wearable android",
      "fitmesh sync ios dostępny",
      "panel zdrowia android iphone",
    ],
    tr: [
      "fitmesh sync iphone",
      "iphone sağlık uygulaması android akıllı saat",
      "apple health köprüsü wearable android",
      "fitmesh sync ios mevcut",
      "android iphone sağlık paneli",
    ],
    nl: [
      "fitmesh sync iphone",
      "apple gezondheid iphone sporthorloge android",
      "apple gezondheid brug wearable android",
      "fitmesh sync ios beschikbaar",
      "gezondheid dashboard android iphone",
    ],
    ja: [
      "fitmesh sync iphone",
      "apple health iphone androidスマートウォッチ 同期",
      "apple health ブリッジ wearable android",
      "fitmesh sync ios 配信",
      "健康データ ダッシュボード android iphone",
    ],
    ko: [
      "fitmesh sync iphone",
      "apple 건강 iphone android 스마트워치 동기화",
      "apple health 브릿지 웨어러블 android",
      "fitmesh sync ios 출시",
      "건강 데이터 대시보드 android iphone",
    ],
  },
  metaDescription: {
    it: "FitMesh Sync è ora su App Store, gratis con acquisto in-app. Un account per Android e iPhone, ponte di scrittura Apple Salute, cloud EU/GDPR. Live in tutti i Paesi supportati, incluse le storefront UE.",
    en: "FitMesh Sync is now on the App Store, free with in-app purchase. One account for Android and iPhone, Apple Health write bridge, EU/GDPR cloud. Live in all supported storefronts, including the EU.",
    es: "FitMesh Sync ya está en App Store, gratis con compra integrada. Una cuenta para Android e iPhone, puente de escritura a Apple Salud, nube EU/GDPR. Disponible en todas las tiendas compatibles, incluida la UE.",
    de: "FitMesh Sync ist jetzt im App Store, kostenlos mit In-App-Kauf. Ein Konto für Android und iPhone, Apple-Health-Schreibbrücke, EU/DSGVO-Cloud. Live in allen unterstützten Ländern, einschließlich der EU.",
    pt: "FitMesh Sync já está na App Store, grátis com compra no app. Uma conta para Android e iPhone, ponte de escrita para o Apple Health, nuvem EU/GDPR. Disponível em todos os países compatíveis, incluindo a UE.",
    fr: "FitMesh Sync est maintenant sur l'App Store, gratuit avec achat intégré. Un compte pour Android et iPhone, pont d'écriture Apple Health, cloud EU/RGPD. Disponible dans tous les pays pris en charge, y compris l'UE.",
    pl: "FitMesh Sync jest już w App Store, za darmo z zakupem w aplikacji. Jedno konto dla Androida i iPhone'a, most zapisu Apple Health, chmura EU/RODO. Dostępny we wszystkich obsługiwanych krajach, w tym w UE.",
    tr: "FitMesh Sync artık App Store'da, uygulama içi satın almayla ücretsiz. Android ve iPhone için tek hesap, Apple Health yazma köprüsü, AB/GDPR bulutu. AB dahil, tüm desteklenen ülkelerde yayında.",
    nl: "FitMesh Sync staat nu in de App Store, gratis met in-app aankoop. Eén account voor Android en iPhone, Apple Health schrijfbrug, EU/AVG-cloud. Live in alle ondersteunde landen, inclusief de EU.",
    ja: "FitMesh SyncがApp Storeで配信開始、アプリ内課金ありで無料。AndroidとiPhoneを1つのアカウントで、Apple Health書き込みブリッジ、EU/GDPRクラウド。EUを含む対応国すべてで利用可能です。",
    ko: "FitMesh Sync가 App Store에 출시, 인앱 구매 포함 무료. Android와 iPhone을 하나의 계정으로, Apple Health 쓰기 브릿지, EU/GDPR 클라우드. EU를 포함한 모든 지원 국가에서 이용 가능합니다.",
  },
  tldr: {
    it: [
      "FitMesh Sync è ora su App Store, gratis con acquisto in-app (Pro a vita 4,99 € su iPhone).",
      "Un solo account funziona su Android e iPhone insieme, con il ponte di scrittura Apple Salute opt-in.",
      "Disponibile in tutti i Paesi supportati, incluse le storefront UE.",
    ],
    en: [
      "FitMesh Sync is now on the App Store, free with in-app purchase (Pro lifetime €4.99 on iPhone).",
      "One account works across Android and iPhone, with the opt-in Apple Health write bridge.",
      "Available in all supported storefronts, including the EU.",
    ],
    es: [
      "FitMesh Sync ya está en App Store, gratis con compra integrada (Pro de por vida 4,99 € en iPhone).",
      "Una sola cuenta funciona en Android e iPhone a la vez, con el puente de escritura a Apple Salud opt-in.",
      "Disponible en todas las tiendas compatibles, incluida la UE.",
    ],
    de: [
      "FitMesh Sync ist jetzt im App Store, kostenlos mit In-App-Kauf (Pro lebenslang 4,99 € auf dem iPhone).",
      "Ein einziges Konto funktioniert auf Android und iPhone, mit der opt-in Apple-Health-Schreibbrücke.",
      "In allen unterstützten Ländern verfügbar, einschließlich der EU.",
    ],
    pt: [
      "FitMesh Sync já está na App Store, grátis com compra no app (Pro vitalício € 4,99 no iPhone).",
      "Uma única conta funciona em Android e iPhone juntos, com a ponte de escrita para o Apple Health opt-in.",
      "Disponível em todos os países compatíveis, incluindo a UE.",
    ],
    fr: [
      "FitMesh Sync est maintenant sur l'App Store, gratuit avec achat intégré (Pro à vie 4,99 € sur iPhone).",
      "Un seul compte fonctionne sur Android et iPhone, avec le pont d'écriture Apple Health en opt-in.",
      "Disponible dans tous les pays pris en charge, y compris l'UE.",
    ],
    pl: [
      "FitMesh Sync jest już w App Store, za darmo z zakupem w aplikacji (Pro na zawsze 4,99 € na iPhone).",
      "Jedno konto działa na Androidzie i iPhonie razem, z opcjonalnym mostem zapisu Apple Health.",
      "Dostępny we wszystkich obsługiwanych krajach, w tym w UE.",
    ],
    tr: [
      "FitMesh Sync artık App Store'da, uygulama içi satın almayla ücretsiz (iPhone'da ömür boyu Pro 4,99 €).",
      "Tek bir hesap Android ve iPhone'da birlikte çalışır; isteğe bağlı Apple Health yazma köprüsüyle.",
      "AB dahil, tüm desteklenen ülkelerde mevcut.",
    ],
    nl: [
      "FitMesh Sync staat nu in de App Store, gratis met in-app aankoop (Pro levenslang € 4,99 op iPhone).",
      "Eén account werkt op zowel Android als iPhone, met de opt-in Apple Health schrijfbrug.",
      "Beschikbaar in alle ondersteunde landen, inclusief de EU.",
    ],
    ja: [
      "FitMesh SyncがApp Storeで配信開始、アプリ内課金ありで無料（iPhoneのProは買い切り4.99ユーロ）。",
      "1つのアカウントでAndroidとiPhoneを併用でき、オプトインのApple Health書き込みブリッジに対応。",
      "EUを含む対応国すべてで利用可能です。",
    ],
    ko: [
      "FitMesh Sync가 App Store에 출시, 인앱 구매 포함 무료(iPhone에서 평생 Pro 4.99유로).",
      "하나의 계정으로 Android와 iPhone을 함께 사용하며, 옵트인 Apple Health 쓰기 브릿지를 지원합니다.",
      "EU를 포함한 모든 지원 국가에서 이용 가능합니다.",
    ],
  },
  hero: {
    kicker: {
      it: "Novità",
      en: "What's New",
      es: "Novedades",
      de: "Neuigkeit",
      pt: "Novidade",
      fr: "Nouveauté",
      pl: "Nowości",
      tr: "Yeni Özellikler",
      nl: "Nieuw",
      ja: "新着情報",
      ko: "새 소식",
    },
    title: {
      it: "FitMesh Sync è ora su App Store",
      en: "FitMesh Sync is now on the App Store",
      es: "FitMesh Sync ya está en App Store",
      de: "FitMesh Sync ist jetzt im App Store",
      pt: "FitMesh Sync já está na App Store",
      fr: "FitMesh Sync est maintenant sur l'App Store",
      pl: "FitMesh Sync jest już w App Store",
      tr: "FitMesh Sync artık App Store'da",
      nl: "FitMesh Sync staat nu in de App Store",
      ja: "FitMesh SyncがApp Storeに登場",
      ko: "FitMesh Sync, 이제 App Store에서",
    },
    subtitle: {
      it: "L'app iOS è ufficialmente live: scaricala gratis (con acquisto in-app), accedi con lo stesso account di Android e porta i dati del tuo wearable Android in Apple Salute. Disponibile in tutti i Paesi supportati, incluse le storefront UE.",
      en: "The iOS app is officially live: download it free (with in-app purchase), sign in with your same Android account, and bring your Android wearable data into Apple Health. Available in all supported storefronts, including the EU.",
      es: "La app para iOS ya está disponible oficialmente: descárgala gratis (con compra integrada), inicia sesión con tu misma cuenta de Android y lleva los datos de tu wearable Android a Apple Salud. Disponible en todas las tiendas compatibles, incluida la UE.",
      de: "Die iOS-App ist offiziell live: Lade sie kostenlos herunter (mit In-App-Kauf), melde dich mit deinem Android-Konto an und bring deine Android-Wearable-Daten in Apple Health. In allen unterstützten Ländern verfügbar, einschließlich der EU.",
      pt: "O app iOS está oficialmente disponível: baixe grátis (com compra no app), entre com a mesma conta do Android e leve os dados do seu wearable Android para o Apple Health. Disponível em todos os países compatíveis, incluindo a UE.",
      fr: "L'app iOS est officiellement disponible : téléchargez-la gratuitement (avec achat intégré), connectez-vous avec votre compte Android et amenez vos données wearable Android dans Apple Health. Disponible dans tous les pays pris en charge, y compris l'UE.",
      pl: "Aplikacja iOS jest oficjalnie dostępna: pobierz ją za darmo (z zakupem w aplikacji), zaloguj się tym samym kontem co na Androidzie i przenieś dane z wearable Android do Apple Health. Dostępna we wszystkich obsługiwanych krajach, w tym w UE.",
      tr: "iOS uygulaması resmen yayında: ücretsiz indir (uygulama içi satın almayla), Android'deki aynı hesapla giriş yap ve Android giyilebilir cihaz verilerini Apple Health'e taşı. AB dahil, tüm desteklenen ülkelerde mevcut.",
      nl: "De iOS-app is officieel live: download hem gratis (met in-app aankoop), meld je aan met je Android-account en breng je Android-wearable gegevens naar Apple Gezondheid. Beschikbaar in alle ondersteunde landen, inclusief de EU.",
      ja: "iOSアプリが正式に配信開始：無料でダウンロード（アプリ内課金あり）、Androidと同じアカウントでサインインし、AndroidウェアラブルのデータをApple Healthに取り込めます。EUを含む対応国すべてで利用可能です。",
      ko: "iOS 앱이 정식으로 출시되었습니다: 무료로 다운로드(인앱 구매 포함)하고 Android와 동일한 계정으로 로그인하여 Android 웨어러블 데이터를 Apple Health로 가져오세요. EU를 포함한 모든 지원 국가에서 이용 가능합니다.",
    },
  },
  body: [
    {
      type: "paragraph",
      text: {
        it: "Ci siamo: FitMesh Sync è ora su App Store. La versione iOS porta tutto quello che già conosci dall'app Android — un solo account, dashboard unificata, sync su cloud EU — e aggiunge il pezzo che mancava agli utenti iPhone: il ponte di scrittura verso Apple Salute. L'app è gratis con acquisto in-app (Pro a vita 4,99 € su iPhone) ed è scaricabile in tutti i Paesi supportati, incluse le storefront dei 27 Paesi UE.",
        en: "Here we are: FitMesh Sync is now on the App Store. The iOS version brings everything you already know from the Android app — one account, a unified dashboard, EU cloud sync — and adds the piece iPhone users were missing: the write bridge into Apple Health. The app is free with in-app purchase (Pro lifetime €4.99 on iPhone) and downloadable in all supported storefronts, including all 27 EU countries.",
        es: "Ya está: FitMesh Sync está ahora en App Store. La versión para iOS trae todo lo que ya conoces de la app Android —una sola cuenta, panel unificado, sincronización en nube EU— y añade la pieza que les faltaba a los usuarios de iPhone: el puente de escritura a Apple Salud. La app es gratis con compra integrada (Pro de por vida 4,99 € en iPhone) y se puede descargar en todas las tiendas compatibles, incluidos los 27 países de la UE.",
        de: "Es ist soweit: FitMesh Sync ist jetzt im App Store. Die iOS-Version bringt alles mit, was du bereits aus der Android-App kennst — ein Konto, ein einheitliches Dashboard, EU-Cloud-Sync — und ergänzt das, was iPhone-Nutzern bisher fehlte: die Schreibbrücke in Apple Health. Die App ist kostenlos mit In-App-Kauf (Pro lebenslang 4,99 € auf dem iPhone) und in allen unterstützten Ländern verfügbar, einschließlich aller 27 EU-Länder.",
        pt: "Chegou: FitMesh Sync agora está na App Store. A versão iOS traz tudo o que você já conhece do app Android — uma só conta, painel unificado, sincronização na nuvem EU — e adiciona a peça que faltava aos usuários de iPhone: a ponte de escrita para o Apple Health. O app é grátis com compra no app (Pro vitalício € 4,99 no iPhone) e pode ser baixado em todos os países compatíveis, incluindo os 27 países da UE.",
        fr: "Ça y est : FitMesh Sync est maintenant sur l'App Store. La version iOS reprend tout ce que vous connaissez déjà de l'app Android — un seul compte, un tableau de bord unifié, la synchronisation cloud EU — et ajoute la pièce qui manquait aux utilisateurs d'iPhone : le pont d'écriture vers Apple Health. L'app est gratuite avec achat intégré (Pro à vie 4,99 € sur iPhone) et téléchargeable dans tous les pays pris en charge, y compris les 27 pays de l'UE.",
        pl: "Jest: FitMesh Sync jest już w App Store. Wersja iOS przynosi wszystko, co znasz z aplikacji Android — jedno konto, ujednolicony panel, synchronizację w chmurze EU — i dodaje element, którego brakowało użytkownikom iPhone'a: most zapisu do Apple Health. Aplikacja jest darmowa z zakupem w aplikacji (Pro na zawsze 4,99 € na iPhone) i można ją pobrać we wszystkich obsługiwanych krajach, w tym we wszystkich 27 krajach UE.",
        tr: "İşte burada: FitMesh Sync artık App Store'da. iOS sürümü, Android uygulamasından zaten bildiğiniz her şeyi getiriyor — tek hesap, birleşik panel, AB bulut senkronizasyonu — ve iPhone kullanıcılarında eksik olan parçayı ekliyor: Apple Health'e yazma köprüsü. Uygulama uygulama içi satın almayla ücretsiz (iPhone'da ömür boyu Pro 4,99 €) ve 27 AB ülkesi dahil, tüm desteklenen ülkelerde indirilebiliyor.",
        nl: "Het is zover: FitMesh Sync staat nu in de App Store. De iOS-versie brengt alles wat je al kent van de Android-app — één account, een unified dashboard, EU-cloudsynchronisatie — en voegt het stuk toe dat iPhone-gebruikers misten: de schrijfbrug naar Apple Gezondheid. De app is gratis met in-app aankoop (Pro levenslang € 4,99 op iPhone) en te downloaden in alle ondersteunde landen, inclusief alle 27 EU-landen.",
        ja: "ついに、FitMesh SyncがApp Storeに登場しました。iOS版はAndroidアプリでおなじみの機能をすべて備え（1つのアカウント、統合ダッシュボード、EUクラウド同期）、iPhoneユーザーに欠けていた要素であるApple Healthへの書き込みブリッジを追加します。アプリはアプリ内課金ありで無料（iPhoneのProは買い切り4.99ユーロ）、EU加盟27カ国を含む対応国すべてでダウンロードできます。",
        ko: "드디어 FitMesh Sync가 App Store에 출시되었습니다. iOS 버전은 Android 앱에서 이미 알고 있는 모든 기능(하나의 계정, 통합 대시보드, EU 클라우드 동기화)을 제공하고, iPhone 사용자에게 빠져 있던 요소인 Apple Health 쓰기 브릿지를 추가합니다. 앱은 인앱 구매가 포함된 무료(iPhone에서 평생 Pro 4.99유로)이며 EU 27개국을 포함한 모든 지원 국가에서 다운로드할 수 있습니다.",
      },
    },
    {
      type: "cta",
      title: {
        it: "Disponibile ora su App Store",
        en: "Now on the App Store",
        es: "Ya disponible en App Store",
        de: "Jetzt im App Store",
        pt: "Já disponível na App Store",
        fr: "Maintenant sur l'App Store",
        pl: "Już w App Store",
        tr: "Şimdi App Store'da",
        nl: "Nu in de App Store",
        ja: "App Storeで配信中",
        ko: "지금 App Store에서",
      },
      body: {
        it: "FitMesh Sync è live su App Store, gratis con acquisto in-app. Live in tutti i Paesi supportati, incluse le storefront UE.",
        en: "FitMesh Sync is live on the App Store, free with in-app purchase. Live in all supported storefronts, including the EU.",
        es: "FitMesh Sync está disponible en App Store, gratis con compra integrada. Disponible en todas las tiendas compatibles, incluida la UE.",
        de: "FitMesh Sync ist live im App Store, kostenlos mit In-App-Kauf. Live in allen unterstützten Ländern, einschließlich der EU.",
        pt: "FitMesh Sync está disponível na App Store, grátis com compra no app. Disponível em todos os países compatíveis, incluindo a UE.",
        fr: "FitMesh Sync est disponible sur l'App Store, gratuit avec achat intégré. Disponible dans tous les pays pris en charge, y compris l'UE.",
        pl: "FitMesh Sync jest dostępny w App Store, za darmo z zakupem w aplikacji. Dostępny we wszystkich obsługiwanych krajach, w tym w UE.",
        tr: "FitMesh Sync App Store'da yayında, uygulama içi satın almayla ücretsiz. AB dahil, tüm desteklenen ülkelerde mevcut.",
        nl: "FitMesh Sync is live in de App Store, gratis met in-app aankoop. Live in alle ondersteunde landen, inclusief de EU.",
        ja: "FitMesh SyncはApp Storeで配信中、アプリ内課金ありで無料です。EUを含む対応国すべてで利用可能です。",
        ko: "FitMesh Sync는 App Store에서 이용 가능하며 인앱 구매가 포함된 무료입니다. EU를 포함한 모든 지원 국가에서 이용 가능합니다.",
      },
      ctaLabel: {
        it: "Apri su App Store →",
        en: "View on the App Store →",
        es: "Ver en App Store →",
        de: "Im App Store ansehen →",
        pt: "Ver na App Store →",
        fr: "Voir sur l'App Store →",
        pl: "Zobacz w App Store →",
        tr: "App Store'da görüntüle →",
        nl: "Bekijk in de App Store →",
        ja: "App Storeで見る →",
        ko: "App Store에서 보기 →",
      },
      ctaHref: {
        it: "https://apps.apple.com/app/fitmesh-sync/id6779751708",
        en: "https://apps.apple.com/app/fitmesh-sync/id6779751708",
        es: "https://apps.apple.com/app/fitmesh-sync/id6779751708",
        de: "https://apps.apple.com/app/fitmesh-sync/id6779751708",
        pt: "https://apps.apple.com/app/fitmesh-sync/id6779751708",
        fr: "https://apps.apple.com/app/fitmesh-sync/id6779751708",
        pl: "https://apps.apple.com/app/fitmesh-sync/id6779751708",
        tr: "https://apps.apple.com/app/fitmesh-sync/id6779751708",
        nl: "https://apps.apple.com/app/fitmesh-sync/id6779751708",
        ja: "https://apps.apple.com/app/fitmesh-sync/id6779751708",
        ko: "https://apps.apple.com/app/fitmesh-sync/id6779751708",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Cosa trovi nella versione iOS",
        en: "What you get in the iOS version",
        es: "Qué encuentras en la versión para iOS",
        de: "Was die iOS-Version bietet",
        pt: "O que você encontra na versão iOS",
        fr: "Ce que vous trouvez dans la version iOS",
        pl: "Co znajdziesz w wersji iOS",
        tr: "iOS sürümünde neler var",
        nl: "Wat je krijgt in de iOS-versie",
        ja: "iOS版で使える機能",
        ko: "iOS 버전에서 제공되는 기능",
      },
    },
    {
      type: "list",
      items: {
        it: [
          "**Un account, Android e iPhone insieme**: accedi con lo stesso login Google o Apple e ritrovi la stessa dashboard su entrambi i telefoni e nel browser.",
          "**Ponte di scrittura Apple Salute** (opt-in): i dati del tuo smartwatch o anello Android arrivano via cloud e vengono scritti in Apple Salute, senza duplicati.",
          "**Cloud EU e GDPR**: i dati sono archiviati in datacenter europei, conformi GDPR. Nessuna vendita a terzi.",
          "**Anello Colmi via Bluetooth**: l'app iOS legge l'anello smart Colmi R02/R03 in BLE diretto, come fa la versione Android.",
        ],
        en: [
          "**One account, Android and iPhone together**: sign in with the same Google or Apple login and find the same dashboard on both phones and in the browser.",
          "**Apple Health write bridge** (opt-in): data from your Android smartwatch or ring arrives via cloud and gets written into Apple Health, with no duplicates.",
          "**EU cloud and GDPR**: data is stored in European datacenters, GDPR compliant. No third-party data sales.",
          "**Colmi ring via Bluetooth**: the iOS app reads the Colmi R02/R03 smart ring over direct BLE, just like the Android version.",
        ],
        es: [
          "**Una cuenta, Android e iPhone a la vez**: inicia sesión con el mismo login de Google o Apple y encuentra el mismo panel en ambos teléfonos y en el navegador.",
          "**Puente de escritura a Apple Salud** (opt-in): los datos de tu smartwatch o anillo Android llegan por la nube y se escriben en Apple Salud, sin duplicados.",
          "**Nube EU y GDPR**: los datos se almacenan en centros de datos europeos, conformes con el GDPR. Sin venta a terceros.",
          "**Anillo Colmi vía Bluetooth**: la app para iOS lee el anillo inteligente Colmi R02/R03 por BLE directo, igual que la versión Android.",
        ],
        de: [
          "**Ein Konto, Android und iPhone gemeinsam**: Melde dich mit demselben Google- oder Apple-Login an und finde dasselbe Dashboard auf beiden Smartphones und im Browser.",
          "**Apple-Health-Schreibbrücke** (opt-in): Daten deines Android-Smartwatchs oder -Rings kommen über die Cloud und werden ohne Duplikate in Apple Health geschrieben.",
          "**EU-Cloud und DSGVO**: Daten werden in europäischen Rechenzentren gespeichert, DSGVO-konform. Keine Datenweitergabe an Dritte.",
          "**Colmi-Ring per Bluetooth**: Die iOS-App liest den Colmi R02/R03 Smart-Ring per direktem BLE, genau wie die Android-Version.",
        ],
        pt: [
          "**Uma conta, Android e iPhone juntos**: entre com o mesmo login Google ou Apple e encontre o mesmo painel nos dois celulares e no navegador.",
          "**Ponte de escrita para o Apple Health** (opt-in): os dados do seu smartwatch ou anel Android chegam via nuvem e são gravados no Apple Health, sem duplicatas.",
          "**Nuvem EU e GDPR**: os dados são armazenados em datacenters europeus, em conformidade com o GDPR. Sem venda a terceiros.",
          "**Anel Colmi via Bluetooth**: o app iOS lê o anel inteligente Colmi R02/R03 por BLE direto, como a versão Android.",
        ],
        fr: [
          "**Un compte, Android et iPhone ensemble** : connectez-vous avec le même identifiant Google ou Apple et retrouvez le même tableau de bord sur les deux téléphones et dans le navigateur.",
          "**Pont d'écriture vers Apple Health** (opt-in) : les données de votre montre ou bague Android arrivent via le cloud et sont écrites dans Apple Health, sans doublons.",
          "**Cloud EU et RGPD** : les données sont stockées dans des datacenters européens, conformes au RGPD. Aucune vente à des tiers.",
          "**Bague Colmi via Bluetooth** : l'app iOS lit la bague connectée Colmi R02/R03 en BLE direct, comme la version Android.",
        ],
        pl: [
          "**Jedno konto, Android i iPhone razem**: zaloguj się tym samym loginem Google lub Apple i znajdź ten sam panel na obu telefonach i w przeglądarce.",
          "**Most zapisu Apple Health** (opt-in): dane z Twojego smartwatcha lub pierścienia Android trafiają przez chmurę i są zapisywane w Apple Health, bez duplikatów.",
          "**Chmura EU i RODO**: dane są przechowywane w europejskich centrach danych, zgodnych z RODO. Bez sprzedaży podmiotom trzecim.",
          "**Pierścień Colmi przez Bluetooth**: aplikacja iOS odczytuje pierścień smart Colmi R02/R03 przez bezpośrednie BLE, tak jak wersja Android.",
        ],
        tr: [
          "**Bir hesap, Android ve iPhone birlikte**: aynı Google veya Apple girişiyle oturum açın ve her iki telefonda ve tarayıcıda aynı paneli bulun.",
          "**Apple Health yazma köprüsü** (isteğe bağlı): Android akıllı saatinizin veya yüzüğünüzün verileri bulut üzerinden gelir ve yineleme olmadan Apple Health'e yazılır.",
          "**AB bulutu ve GDPR**: veriler Avrupa veri merkezlerinde, GDPR uyumlu şekilde saklanır. Üçüncü taraflara veri satışı yok.",
          "**Bluetooth üzerinden Colmi yüzük**: iOS uygulaması Colmi R02/R03 akıllı yüzüğü doğrudan BLE ile okur, tıpkı Android sürümü gibi.",
        ],
        nl: [
          "**Eén account, Android en iPhone samen**: meld je aan met dezelfde Google- of Apple-login en vind hetzelfde dashboard op beide telefoons en in de browser.",
          "**Apple Health schrijfbrug** (opt-in): gegevens van je Android-sporthorloge of -ring komen via de cloud binnen en worden zonder duplicaten in Apple Gezondheid geschreven.",
          "**EU-cloud en AVG**: gegevens worden opgeslagen in Europese datacenters, AVG-conform. Geen verkoop aan derden.",
          "**Colmi-ring via Bluetooth**: de iOS-app leest de Colmi R02/R03 slimme ring via directe BLE, net als de Android-versie.",
        ],
        ja: [
          "**1つのアカウントでAndroidとiPhoneを一緒に**：同じGoogleまたはAppleログインでサインインすると、両方のスマートフォンとブラウザで同じダッシュボードを利用できます。",
          "**Apple Health書き込みブリッジ**（オプトイン）：Androidスマートウォッチやリングのデータがクラウド経由で届き、重複なしにApple Healthに書き込まれます。",
          "**EUクラウドとGDPR**：データは欧州のデータセンターに保存され、GDPRに準拠。第三者への販売はありません。",
          "**BluetoothでColmiリング接続**：iOSアプリはColmi R02/R03スマートリングをAndroid版と同様に直接BLEで読み取ります。",
        ],
        ko: [
          "**하나의 계정으로 Android와 iPhone 함께**: 동일한 Google 또는 Apple 로그인으로 로그인하면 두 기기와 브라우저에서 동일한 대시보드를 사용할 수 있습니다.",
          "**Apple Health 쓰기 브릿지**(옵트인): Android 스마트워치나 링의 데이터가 클라우드를 통해 전달되어 중복 없이 Apple Health에 기록됩니다.",
          "**EU 클라우드와 GDPR**: 데이터는 유럽 데이터센터에 GDPR을 준수하여 저장됩니다. 제3자 판매 없음.",
          "**Bluetooth로 Colmi 링 연결**: iOS 앱이 Colmi R02/R03 스마트 링을 Android 버전처럼 직접 BLE로 읽습니다.",
        ],
      },
    },
    {
      type: "callout",
      variant: "info",
      title: {
        it: "Una nota sull'UE",
        en: "A note on the EU",
        es: "Una nota sobre la UE",
        de: "Ein Hinweis zur EU",
        pt: "Uma nota sobre a UE",
        fr: "Une note sur l'UE",
        pl: "Uwaga o UE",
        tr: "AB hakkında bir not",
        nl: "Een opmerking over de EU",
        ja: "EUについての注記",
        ko: "EU 관련 안내",
      },
      body: {
        it: "L'app è live in tutti i Paesi supportati, incluse tutte le storefront dei 27 Paesi UE (verificato 2026-07-13).",
        en: "The app is live in all supported storefronts, including all 27 EU countries (verified 2026-07-13).",
        es: "La app está disponible en todas las tiendas compatibles, incluidos los 27 países de la UE (verificado el 13/07/2026).",
        de: "Die App ist in allen unterstützten Ländern verfügbar, einschließlich aller 27 EU-Länder (verifiziert am 13.07.2026).",
        pt: "O app está disponível em todos os países compatíveis, incluindo os 27 países da UE (verificado em 13/07/2026).",
        fr: "L'app est disponible dans tous les pays pris en charge, y compris les 27 pays de l'UE (vérifié le 13/07/2026).",
        pl: "Aplikacja jest dostępna we wszystkich obsługiwanych krajach, w tym we wszystkich 27 krajach UE (zweryfikowano 13.07.2026).",
        tr: "Uygulama, 27 AB ülkesi dahil tüm desteklenen ülkelerde kullanılabilir (13.07.2026 tarihinde doğrulandı).",
        nl: "De app is live in alle ondersteunde landen, inclusief alle 27 EU-landen (geverifieerd op 13-07-2026).",
        ja: "アプリはEU加盟27カ国を含む、対応するすべての国で利用可能です（2026年7月13日確認済み）。",
        ko: "앱은 EU 27개국을 포함한 모든 지원 국가에서 이용 가능합니다 (2026년 7월 13일 확인).",
      },
    },
  ],
  related: ["fitmesh-arriva-su-iphone", "fitmesh-sync-disponibile-google-play"],
  brandsMentioned: ["Apple"],
};
