import type { BlogPost } from "../types";

export const post: BlogPost = {
  slug: "sincronizzare-withings",
  category: "guides",
  publishedAt: "2026-06-18",
  updatedAt: "2026-06-18",
  readMinutes: 8,
  tldr: {
    it: [
      "Withings sincronizza peso, composizione corporea, attività e sonno verso la propria app Health Mate: da lì puoi portare tutto in una dashboard unificata.",
      "Su Android i dati Withings arrivano tramite Health Connect; su iOS tramite HealthKit: basta connettere l'app Health Mate alla piattaforma che usi.",
      "Per una dashboard personalizzata accessibile da browser, serve un'app che legga sia Health Connect/HealthKit sia altri dispositivi che usi in parallelo.",
      "I dati sono tuoi: Withings è un brand europeo, e i server sono in Europa. Prendi nota di dove altri servizi archiviano i tuoi dati prima di condividerli.",
      "Il limite principale: alcune metriche avanzate di composizione corporea rimangono solo nell'app Withings e non vengono trasmesse a terze parti.",
    ],
    en: [
      "Withings syncs weight, body composition, activity and sleep to its own Health Mate app: from there you can bring everything into a unified dashboard.",
      "On Android, Withings data arrives via Health Connect; on iOS via HealthKit: just connect the Health Mate app to whichever platform you use.",
      "For a personal dashboard accessible from a browser, you need an app that reads both Health Connect/HealthKit and the other devices you use in parallel.",
      "Your data is yours: Withings is a European brand, and servers are in Europe. Check where other services store your data before sharing it.",
      "The main limitation: some advanced body composition metrics stay only in the Withings app and are not transmitted to third parties.",
    ],
    es: [
      "Withings sincroniza peso, composición corporal, actividad y sueño con su propia app Health Mate: desde ahí puedes llevar todo a un panel centralizado.",
      "En Android, los datos de Withings llegan a través de Health Connect; en iOS, a través de HealthKit: solo tienes que conectar la app Health Mate a la plataforma que uses.",
      "Para un panel personal accesible desde el navegador, necesitas una app que lea tanto Health Connect/HealthKit como los otros dispositivos que uses.",
      "Tus datos te pertenecen: Withings es una marca europea y sus servidores están en Europa. Comprueba dónde almacenan tus datos otros servicios antes de compartirlos.",
      "El límite principal: algunas métricas avanzadas de composición corporal solo están disponibles en la app de Withings y no se transmiten a terceros.",
    ],
    de: [
      "Withings synchronisiert Gewicht, Körperzusammensetzung, Aktivität und Schlaf mit der eigenen Health Mate App: Von dort kannst du alles in ein einheitliches Dashboard bringen.",
      "Auf Android kommen Withings-Daten über Health Connect; auf iOS über HealthKit: Verbinde einfach die Health Mate App mit der Plattform, die du verwendest.",
      "Für ein persönliches Dashboard, das du im Browser aufrufen kannst, brauchst du eine App, die sowohl Health Connect/HealthKit als auch deine anderen Geräte ausliest.",
      "Deine Daten gehören dir: Withings ist eine europäische Marke, die Server stehen in Europa. Prüfe, wo andere Dienste deine Daten speichern, bevor du sie weitergibst.",
      "Die wichtigste Einschränkung: Einige erweiterte Körperzusammensetzungs-Werte bleiben nur in der Withings App und werden nicht an Dritte übermittelt.",
    ],
    pt: [
      "A Withings sincroniza peso, composição corporal, atividade e sono com seu próprio app Health Mate: de lá, você pode levar tudo para um painel unificado.",
      "No Android, os dados da Withings chegam pelo Health Connect; no iOS, pelo HealthKit: basta conectar o app Health Mate à plataforma que você usa.",
      "Para um painel pessoal acessível pelo navegador, você precisa de um app que leia tanto o Health Connect/HealthKit quanto os outros dispositivos que usa.",
      "Seus dados são seus: a Withings é uma marca europeia e os servidores ficam na Europa. Verifique onde outros serviços armazenam seus dados antes de compartilhá-los.",
      "O limite principal: algumas métricas avançadas de composição corporal ficam apenas no app da Withings e não são transmitidas a terceiros.",
    ],
    fr: [
      "Withings synchronise le poids, la composition corporelle, l'activité et le sommeil vers sa propre application Health Mate: de là, vous pouvez tout regrouper dans un tableau de bord unifié.",
      "Sur Android, les données Withings transitent par Health Connect; sur iOS par HealthKit: il suffit de connecter l'application Health Mate à la plateforme que vous utilisez.",
      "Pour un tableau de bord personnel accessible depuis un navigateur, il vous faut une application qui lit à la fois Health Connect/HealthKit et les autres appareils que vous utilisez.",
      "Vos données vous appartiennent: Withings est une marque européenne et ses serveurs sont en Europe. Vérifiez où les autres services stockent vos données avant de les partager.",
      "La principale limite: certaines métriques avancées de composition corporelle restent uniquement dans l'application Withings et ne sont pas transmises à des tiers.",
    ],
  },
  primaryKeyword: {
    it: "sincronizzare dati Withings",
    en: "sync Withings data",
    es: "sincronizar datos Withings",
    de: "Withings Daten synchronisieren",
    pt: "sincronizar dados Withings",
    fr: "synchroniser données Withings",
  },
  secondaryKeywords: {
    it: [
      "withings health mate dashboard",
      "withings body+ composizione corporea",
      "withings health connect",
      "esportare dati withings",
      "withings privacy dati europa",
    ],
    en: [
      "withings health mate dashboard",
      "withings body+ body composition",
      "withings health connect",
      "export withings data",
      "withings data privacy europe",
    ],
    es: [
      "withings health mate panel",
      "withings body+ composición corporal",
      "withings health connect",
      "exportar datos withings",
      "withings privacidad datos europa",
    ],
    de: [
      "withings health mate dashboard",
      "withings body+ körperzusammensetzung",
      "withings health connect",
      "withings daten exportieren",
      "withings datenschutz europa",
    ],
    pt: [
      "withings health mate painel",
      "withings body+ composição corporal",
      "withings health connect",
      "exportar dados withings",
      "withings privacidade dados europa",
    ],
    fr: [
      "withings health mate tableau de bord",
      "withings body+ composition corporelle",
      "withings health connect",
      "exporter données withings",
      "withings confidentialité données europe",
    ],
  },
  metaDescription: {
    it: "Come sincronizzare i dati Withings (bilancia, orologio ibrido, sensori) verso una dashboard personale unificata. Guida pratica con Health Connect, HealthKit e privacy EU.",
    en: "How to sync Withings data (scale, hybrid watch, sensors) to a unified personal dashboard. Practical guide covering Health Connect, HealthKit and EU privacy.",
    es: "Cómo sincronizar los datos de Withings (báscula, reloj híbrido, sensores) en un panel personal unificado. Guía práctica con Health Connect, HealthKit y privacidad europea.",
    de: "Withings Daten synchronisieren (Waage, Hybrid-Uhr, Sensoren) auf einem einheitlichen persönlichen Dashboard. Praxisanleitung mit Health Connect, HealthKit und EU-Datenschutz.",
    pt: "Como sincronizar os dados da Withings (balança, relógio híbrido, sensores) em um painel pessoal unificado. Guia prático com Health Connect, HealthKit e privacidade europeia.",
    fr: "Comment synchroniser les données Withings (balance, montre hybride, capteurs) vers un tableau de bord personnel unifié. Guide pratique avec Health Connect, HealthKit et confidentialité EU.",
  },
  hero: {
    kicker: {
      it: "Guida",
      en: "Guide",
      es: "Guía",
      de: "Anleitung",
      pt: "Guia",
      fr: "Guide",
    },
    title: {
      it: "Sincronizzare i dati Withings: peso, attività e sonno in un'unica dashboard",
      en: "Syncing Withings data: weight, activity and sleep in one dashboard",
      es: "Sincronizar los datos de Withings: peso, actividad y sueño en un solo panel",
      de: "Withings Daten synchronisieren: Gewicht, Aktivität und Schlaf in einem Dashboard",
      pt: "Sincronizar os dados da Withings: peso, atividade e sono em um único painel",
      fr: "Synchroniser les données Withings: poids, activité et sommeil dans un seul tableau de bord",
    },
    subtitle: {
      it: "Withings raccoglie informazioni preziose sul tuo benessere, ma restano chiuse nell'app Health Mate. Ecco come portarle fuori, unirle agli altri tuoi dispositivi e vederle in un posto solo, con onestà sui limiti.",
      en: "Withings collects valuable wellness data, but it stays locked in the Health Mate app. Here is how to get it out, combine it with your other devices and view it all in one place, with honest notes on its limits.",
      es: "Withings recopila datos valiosos sobre tu bienestar, pero quedan encerrados en la app Health Mate. Aquí te explicamos cómo sacarlos, unirlos con los datos de tus otros dispositivos y verlos en un solo lugar, siendo honestos sobre sus limitaciones.",
      de: "Withings sammelt wertvolle Wellness-Daten, die aber in der Health Mate App eingeschlossen bleiben. Hier zeigen wir dir, wie du sie herausholst, mit deinen anderen Geräten kombinierst und an einem Ort anzeigst, ehrlich über die Grenzen.",
      pt: "A Withings coleta dados valiosos sobre o seu bem-estar, mas eles ficam presos no app Health Mate. Veja como extraí-los, combiná-los com seus outros dispositivos e visualizá-los em um só lugar, com honestidade sobre os limites.",
      fr: "Withings collecte des données précieuses sur votre bien-être, mais elles restent enfermées dans l'application Health Mate. Voici comment les en extraire, les combiner avec vos autres appareils et les visualiser au même endroit, avec honnêteté sur les limites.",
    },
  },
  body: [
    {
      type: "paragraph",
      text: {
        it: "Withings è uno dei brand europei più rispettati nel settore dei dispositivi connessi per la salute: bilance intelligenti come la Body+, orologi ibridi come lo ScanWatch, e sensori per pressione, sonno e temperatura. Il punto forte è che i dati non finiscono solo in un cloud remoto negli USA: Withings è francese, i server sono in Europa e l'approccio alla privacy è storicamente più attento rispetto ad alcune alternative americane. Il punto debole è lo stesso di quasi tutti i brand: i dati restano chiusi nell'app dedicata, Health Mate, e per vederli insieme agli altri dispositivi che potresti usare (un orologio sportivo, un wearable diverso) serve un passo in più.",
        en: "Withings is one of the most respected European brands in connected health devices: smart scales like the Body+, hybrid watches like the ScanWatch, and sensors for blood pressure, sleep and temperature. The strength is that data does not end up in a remote US cloud: Withings is French, the servers are in Europe, and the approach to privacy has historically been more careful than some American alternatives. The weak point is the same as for almost all brands: data stays locked in the dedicated app, Health Mate, and to see it alongside other devices you might use (a sports watch, a different wearable) you need an extra step.",
        es: "Withings es una de las marcas europeas más respetadas en el sector de los dispositivos conectados para la salud: básculas inteligentes como la Body+, relojes híbridos como el ScanWatch, y sensores de presión arterial, sueño y temperatura. El punto fuerte es que los datos no acaban en un servidor remoto en EE.UU.: Withings es francesa, los servidores están en Europa y su enfoque de privacidad ha sido históricamente más cuidadoso que el de algunas alternativas americanas. El punto débil es el mismo que en casi todas las marcas: los datos quedan encerrados en la app dedicada, Health Mate, y para verlos junto a otros dispositivos que puedas usar (un reloj deportivo, otro wearable) hace falta un paso más.",
        de: "Withings ist eine der angesehensten europäischen Marken im Bereich vernetzter Gesundheitsgeräte: Smarte Waagen wie die Body+, Hybrid-Uhren wie die ScanWatch, und Sensoren für Blutdruck, Schlaf und Temperatur. Der Stärke: Die Daten landen nicht in einer US-Cloud. Withings ist französisch, die Server stehen in Europa, und der Datenschutzansatz war historisch sorgfältiger als bei manchen amerikanischen Alternativen. Die Schwäche ist dieselbe wie bei fast allen Marken: Die Daten bleiben in der eigenen App Health Mate gesperrt, und um sie gemeinsam mit anderen Geräten zu sehen (eine Sportuhr, ein anderes Wearable), braucht es einen zusätzlichen Schritt.",
        pt: "A Withings é uma das marcas europeias mais respeitadas no setor de dispositivos conectados para a saúde: balanças inteligentes como a Body+, relógios híbridos como o ScanWatch e sensores de pressão arterial, sono e temperatura. O ponto forte é que os dados não vão parar em um servidor remoto nos EUA: a Withings é francesa, os servidores ficam na Europa e a abordagem à privacidade tem sido historicamente mais cuidadosa do que algumas alternativas americanas. O ponto fraco é o mesmo de quase todas as marcas: os dados ficam presos no app dedicado, o Health Mate, e para vê-los junto aos outros dispositivos que você usa (um relógio esportivo, um wearable diferente) é preciso um passo a mais.",
        fr: "Withings est l'une des marques européennes les plus respectées dans le domaine des appareils connectés pour la santé: balances intelligentes comme la Body+, montres hybrides comme la ScanWatch, et capteurs de tension artérielle, de sommeil et de température. Le point fort est que les données ne finissent pas dans un cloud américain distant: Withings est français, les serveurs sont en Europe, et l'approche de la confidentialité a historiquement été plus soigneuse que celle de certaines alternatives américaines. Le point faible est le même que pour presque toutes les marques: les données restent enfermées dans l'application dédiée, Health Mate, et pour les voir aux côtés de vos autres appareils (une montre sportive, un autre wearable), il faut une étape supplémentaire.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Cosa misura Withings e cosa passa alle altre app",
        en: "What Withings measures and what it passes to other apps",
        es: "Qué mide Withings y qué datos comparte con otras apps",
        de: "Was Withings misst und was es an andere Apps weitergibt",
        pt: "O que a Withings mede e o que passa para outros apps",
        fr: "Ce que Withings mesure et ce qu'il transmet aux autres applications",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Prima di parlare di come sincronizzare, vale la pena capire cosa hai a disposizione. I dispositivi Withings raccolgono dati su più aree: il corpo (peso, indice di massa corporea, percentuale di grasso, massa muscolare, idratazione, frequenza cardiaca da bilancia), l'attività (passi, distanza, calorie, allenamenti con certi modelli di orologio), il sonno (durata, fasi, frequenza cardiaca notturna, respirazione) e in alcuni modelli la pressione arteriosa e la saturazione dell'ossigeno.",
        en: "Before talking about how to sync, it is worth understanding what you have available. Withings devices collect data across multiple areas: body (weight, body mass index, fat percentage, muscle mass, hydration, heart rate from the scale), activity (steps, distance, calories, workouts with certain watch models), sleep (duration, phases, overnight heart rate, breathing) and in some models blood pressure and blood oxygen saturation.",
        es: "Antes de hablar de cómo sincronizar, vale la pena entender qué tienes a tu disposición. Los dispositivos Withings recopilan datos en varias áreas: cuerpo (peso, índice de masa corporal, porcentaje de grasa, masa muscular, hidratación, frecuencia cardíaca desde la báscula), actividad (pasos, distancia, calorías, entrenamientos con ciertos modelos de reloj), sueño (duración, fases, frecuencia cardíaca nocturna, respiración) y en algunos modelos presión arterial y saturación de oxígeno en sangre.",
        de: "Bevor wir über das Synchronisieren sprechen, lohnt es sich zu verstehen, was dir zur Verfügung steht. Withings-Geräte erfassen Daten in mehreren Bereichen: Körper (Gewicht, Body-Mass-Index, Körperfettanteil, Muskelmasse, Hydratation, Herzfrequenz von der Waage), Aktivität (Schritte, Distanz, Kalorien, Trainings bei bestimmten Uhrenmodellen), Schlaf (Dauer, Phasen, nächtliche Herzfrequenz, Atmung) und bei einigen Modellen Blutdruck und Blutsauerstoffsättigung.",
        pt: "Antes de falar sobre como sincronizar, vale entender o que você tem disponível. Os dispositivos Withings coletam dados em várias áreas: corpo (peso, índice de massa corporal, percentual de gordura, massa muscular, hidratação, frequência cardíaca pela balança), atividade (passos, distância, calorias, treinos com certos modelos de relógio), sono (duração, fases, frequência cardíaca noturna, respiração) e em alguns modelos pressão arterial e saturação de oxigênio no sangue.",
        fr: "Avant de parler de synchronisation, il vaut la peine de comprendre ce dont vous disposez. Les appareils Withings collectent des données dans plusieurs domaines: le corps (poids, indice de masse corporelle, pourcentage de graisse, masse musculaire, hydratation, fréquence cardiaque depuis la balance), l'activité (pas, distance, calories, séances d'entraînement avec certains modèles de montre), le sommeil (durée, phases, fréquence cardiaque nocturne, respiration) et sur certains modèles la tension artérielle et la saturation en oxygène.",
      },
    },
    {
      type: "callout",
      variant: "warning",
      title: {
        it: "Non tutte le metriche escono dall'app Withings",
        en: "Not all metrics leave the Withings app",
        es: "No todas las métricas salen de la app de Withings",
        de: "Nicht alle Messwerte verlassen die Withings App",
        pt: "Nem todas as métricas saem do app da Withings",
        fr: "Toutes les métriques ne quittent pas l'application Withings",
      },
      body: {
        it: "Withings condivide dati di base come peso, passi e frequenza cardiaca con Health Connect e HealthKit. Alcune metriche avanzate della bilancia (composizione corporea dettagliata, idratazione, massa ossea) potrebbero non essere trasmesse verso app di terze parti. Per quelle, l'app Health Mate rimane il punto di riferimento. Questo è un limite tecnico che vale per quasi tutti i brand di bilance smart, non solo Withings.",
        en: "Withings shares basic data like weight, steps and heart rate with Health Connect and HealthKit. Some advanced scale metrics (detailed body composition, hydration, bone mass) may not be transmitted to third-party apps. For those, the Health Mate app remains the reference point. This is a technical limitation that applies to almost all smart scale brands, not just Withings.",
        es: "Withings comparte datos básicos como peso, pasos y frecuencia cardíaca con Health Connect y HealthKit. Algunas métricas avanzadas de la báscula (composición corporal detallada, hidratación, masa ósea) pueden no transmitirse a apps de terceros. Para esas, la app Health Mate sigue siendo el punto de referencia. Esta es una limitación técnica aplicable a casi todas las marcas de básculas inteligentes, no solo Withings.",
        de: "Withings teilt grundlegende Daten wie Gewicht, Schritte und Herzfrequenz mit Health Connect und HealthKit. Einige erweiterte Waagenmesswerte (detaillierte Körperzusammensetzung, Hydratation, Knochenmasse) werden möglicherweise nicht an Drittanbieter-Apps übertragen. Für diese bleibt die Health Mate App die Referenz. Dies ist eine technische Einschränkung, die für fast alle Smart-Waagen-Marken gilt, nicht nur für Withings.",
        pt: "A Withings compartilha dados básicos como peso, passos e frequência cardíaca com o Health Connect e o HealthKit. Algumas métricas avançadas da balança (composição corporal detalhada, hidratação, massa óssea) podem não ser transmitidas para apps de terceiros. Para essas métricas, o app Health Mate continua sendo o ponto de referência. Esta é uma limitação técnica que vale para quase todas as marcas de balanças inteligentes, não apenas a Withings.",
        fr: "Withings partage des données de base comme le poids, les pas et la fréquence cardiaque avec Health Connect et HealthKit. Certaines métriques avancées de la balance (composition corporelle détaillée, hydratation, masse osseuse) peuvent ne pas être transmises aux applications tierces. Pour celles-ci, l'application Health Mate reste la référence. Il s'agit d'une limitation technique qui s'applique à presque toutes les marques de balances connectées, pas seulement Withings.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Come connettere Withings a Health Connect (Android)",
        en: "How to connect Withings to Health Connect (Android)",
        es: "Cómo conectar Withings a Health Connect (Android)",
        de: "So verbindest du Withings mit Health Connect (Android)",
        pt: "Como conectar a Withings ao Health Connect (Android)",
        fr: "Comment connecter Withings à Health Connect (Android)",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Su Android, il collegamento avviene tramite Health Connect, la piattaforma di Google che fa da punto di raccolta per i dati di salute di app diverse. Una volta configurato, ogni volta che Health Mate aggiorna i dati, queste informazioni diventano disponibili per tutte le altre app che hai autorizzato a leggerle su Health Connect.",
        en: "On Android, the connection happens through Health Connect, Google's platform that acts as a collection point for health data from different apps. Once set up, whenever Health Mate updates data, that information becomes available to all other apps you have authorised to read it on Health Connect.",
        es: "En Android, la conexión se realiza a través de Health Connect, la plataforma de Google que actúa como punto de recopilación de datos de salud de distintas apps. Una vez configurado, cada vez que Health Mate actualiza los datos, esa información queda disponible para todas las demás apps que hayas autorizado a leerlos en Health Connect.",
        de: "Auf Android erfolgt die Verbindung über Health Connect, Googles Plattform, die als Sammelstelle für Gesundheitsdaten verschiedener Apps dient. Nach der Einrichtung werden immer dann, wenn Health Mate Daten aktualisiert, diese Informationen für alle anderen Apps verfügbar, die du zur Lektüre auf Health Connect autorisiert hast.",
        pt: "No Android, a conexão acontece pelo Health Connect, a plataforma do Google que funciona como ponto de coleta de dados de saúde de diferentes apps. Uma vez configurado, sempre que o Health Mate atualiza os dados, essas informações ficam disponíveis para todos os outros apps que você autorizou a lê-los no Health Connect.",
        fr: "Sur Android, la connexion se fait via Health Connect, la plateforme de Google qui sert de point de collecte pour les données de santé de différentes applications. Une fois configuré, chaque fois que Health Mate met à jour les données, ces informations deviennent disponibles pour toutes les autres applications que vous avez autorisées à les lire dans Health Connect.",
      },
    },
    {
      type: "list",
      ordered: true,
      items: {
        it: [
          "Apri l'app **Health Mate** sul tuo telefono Android.",
          "Vai su Profilo (icona in basso a destra) e poi Impostazioni.",
          "Cerca la sezione 'App e servizi connessi' oppure 'Integrazioni di terze parti'.",
          "Seleziona **Health Connect** e tocca 'Connetti' o 'Autorizza'.",
          "Nella schermata di Health Connect, scegli quali dati Withings può scrivere (peso, passi, sonno, frequenza cardiaca).",
          "Conferma. Da questo momento Health Mate scriverà i tuoi dati su Health Connect ogni volta che si sincronizza.",
        ],
        en: [
          "Open the **Health Mate** app on your Android phone.",
          "Go to Profile (icon bottom right) then Settings.",
          "Find the 'Connected apps and services' or 'Third-party integrations' section.",
          "Select **Health Connect** and tap 'Connect' or 'Authorise'.",
          "In the Health Connect screen, choose which Withings data it can write (weight, steps, sleep, heart rate).",
          "Confirm. From now on Health Mate will write your data to Health Connect each time it syncs.",
        ],
        es: [
          "Abre la app **Health Mate** en tu teléfono Android.",
          "Ve a Perfil (icono abajo a la derecha) y luego Ajustes.",
          "Busca la sección 'Apps y servicios conectados' o 'Integraciones de terceros'.",
          "Selecciona **Health Connect** y toca 'Conectar' o 'Autorizar'.",
          "En la pantalla de Health Connect, elige qué datos de Withings puede escribir (peso, pasos, sueño, frecuencia cardíaca).",
          "Confirma. Desde ese momento, Health Mate escribirá tus datos en Health Connect cada vez que se sincronice.",
        ],
        de: [
          "Öffne die **Health Mate** App auf deinem Android-Telefon.",
          "Gehe zu Profil (Symbol unten rechts) und dann Einstellungen.",
          "Suche den Bereich 'Verbundene Apps und Dienste' oder 'Drittanbieter-Integrationen'.",
          "Wähle **Health Connect** und tippe auf 'Verbinden' oder 'Autorisieren'.",
          "Im Health Connect-Bildschirm wähle aus, welche Withings-Daten geschrieben werden dürfen (Gewicht, Schritte, Schlaf, Herzfrequenz).",
          "Bestätige. Ab sofort schreibt Health Mate deine Daten bei jeder Synchronisierung in Health Connect.",
        ],
        pt: [
          "Abra o app **Health Mate** no seu telefone Android.",
          "Vá em Perfil (ícone no canto inferior direito) e depois Configurações.",
          "Encontre a seção 'Apps e serviços conectados' ou 'Integrações de terceiros'.",
          "Selecione **Health Connect** e toque em 'Conectar' ou 'Autorizar'.",
          "Na tela do Health Connect, escolha quais dados da Withings ele pode escrever (peso, passos, sono, frequência cardíaca).",
          "Confirme. A partir de agora, o Health Mate vai escrever seus dados no Health Connect a cada sincronização.",
        ],
        fr: [
          "Ouvrez l'application **Health Mate** sur votre téléphone Android.",
          "Allez dans Profil (icône en bas à droite) puis Paramètres.",
          "Recherchez la section 'Applications et services connectés' ou 'Intégrations tierces'.",
          "Sélectionnez **Health Connect** et appuyez sur 'Connecter' ou 'Autoriser'.",
          "Dans l'écran Health Connect, choisissez quelles données Withings peut écrire (poids, pas, sommeil, fréquence cardiaque).",
          "Confirmez. Désormais, Health Mate écrira vos données dans Health Connect à chaque synchronisation.",
        ],
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Come connettere Withings a HealthKit (iPhone)",
        en: "How to connect Withings to HealthKit (iPhone)",
        es: "Cómo conectar Withings a HealthKit (iPhone)",
        de: "So verbindest du Withings mit HealthKit (iPhone)",
        pt: "Como conectar a Withings ao HealthKit (iPhone)",
        fr: "Comment connecter Withings à HealthKit (iPhone)",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Su iPhone il flusso è simile ma passa per HealthKit, l'equivalente Apple di Health Connect. L'app Salute di Apple fa da raccoglitore centrale e puoi decidere, per ogni app, esattamente quali dati può leggere o scrivere.",
        en: "On iPhone the flow is similar but goes through HealthKit, Apple's equivalent of Health Connect. The Apple Health app acts as a central collector and you can decide, for each app, exactly which data it can read or write.",
        es: "En iPhone el proceso es similar pero pasa por HealthKit, el equivalente de Apple a Health Connect. La app Salud de Apple actúa como recopilador central y puedes decidir, para cada app, exactamente qué datos puede leer o escribir.",
        de: "Auf dem iPhone ist der Ablauf ähnlich, geht aber über HealthKit, Apples Entsprechung zu Health Connect. Die Apple Gesundheit App dient als zentraler Sammler, und du kannst für jede App genau festlegen, welche Daten sie lesen oder schreiben darf.",
        pt: "No iPhone o fluxo é semelhante, mas passa pelo HealthKit, o equivalente da Apple ao Health Connect. O app Saúde da Apple funciona como coletor central e você pode decidir, para cada app, exatamente quais dados ele pode ler ou escrever.",
        fr: "Sur iPhone, le processus est similaire mais passe par HealthKit, l'équivalent Apple de Health Connect. L'application Santé d'Apple sert de collecteur central et vous pouvez décider, pour chaque application, exactement quelles données elle peut lire ou écrire.",
      },
    },
    {
      type: "list",
      ordered: true,
      items: {
        it: [
          "Apri **Health Mate** su iPhone.",
          "Vai su Profilo (icona in basso a destra) e poi Impostazioni.",
          "Trova 'Sincronizza con Salute' o 'Connetti a HealthKit'.",
          "Tocca per aprire la schermata di autorizzazione di Apple.",
          "Scegli i dati da condividere (peso, frequenza cardiaca, sonno, passi) e tocca 'Consenti'.",
          "Da quel momento i dati Withings appaiono nell'app Salute di iPhone e sono disponibili per le altre app autorizzate.",
        ],
        en: [
          "Open **Health Mate** on iPhone.",
          "Go to Profile (icon bottom right) then Settings.",
          "Find 'Sync with Health' or 'Connect to HealthKit'.",
          "Tap to open Apple's authorisation screen.",
          "Choose the data to share (weight, heart rate, sleep, steps) and tap 'Allow'.",
          "From that moment Withings data appears in the iPhone Health app and is available to other authorised apps.",
        ],
        es: [
          "Abre **Health Mate** en iPhone.",
          "Ve a Perfil (icono abajo a la derecha) y luego Ajustes.",
          "Busca 'Sincronizar con Salud' o 'Conectar a HealthKit'.",
          "Toca para abrir la pantalla de autorización de Apple.",
          "Elige los datos a compartir (peso, frecuencia cardíaca, sueño, pasos) y toca 'Permitir'.",
          "A partir de ese momento los datos de Withings aparecen en la app Salud del iPhone y están disponibles para las demás apps autorizadas.",
        ],
        de: [
          "Öffne **Health Mate** auf dem iPhone.",
          "Gehe zu Profil (Symbol unten rechts) und dann Einstellungen.",
          "Suche 'Mit Gesundheit synchronisieren' oder 'Mit HealthKit verbinden'.",
          "Tippe, um Apples Autorisierungsbildschirm zu öffnen.",
          "Wähle die zu teilenden Daten aus (Gewicht, Herzfrequenz, Schlaf, Schritte) und tippe auf 'Erlauben'.",
          "Ab diesem Moment erscheinen die Withings-Daten in der iPhone Gesundheit App und stehen anderen autorisierten Apps zur Verfügung.",
        ],
        pt: [
          "Abra o **Health Mate** no iPhone.",
          "Vá em Perfil (ícone no canto inferior direito) e depois Configurações.",
          "Encontre 'Sincronizar com Saúde' ou 'Conectar ao HealthKit'.",
          "Toque para abrir a tela de autorização da Apple.",
          "Escolha os dados a compartilhar (peso, frequência cardíaca, sono, passos) e toque em 'Permitir'.",
          "A partir desse momento, os dados da Withings aparecem no app Saúde do iPhone e ficam disponíveis para outros apps autorizados.",
        ],
        fr: [
          "Ouvrez **Health Mate** sur iPhone.",
          "Allez dans Profil (icône en bas à droite) puis Paramètres.",
          "Trouvez 'Synchroniser avec Santé' ou 'Connecter à HealthKit'.",
          "Appuyez pour ouvrir l'écran d'autorisation d'Apple.",
          "Choisissez les données à partager (poids, fréquence cardiaque, sommeil, pas) et appuyez sur 'Autoriser'.",
          "Dès ce moment, les données Withings apparaissent dans l'application Santé de l'iPhone et sont disponibles pour les autres applications autorisées.",
        ],
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Tutti i tuoi dispositivi in una dashboard: come funziona",
        en: "All your devices in one dashboard: how it works",
        es: "Todos tus dispositivos en un panel: cómo funciona",
        de: "Alle deine Geräte in einem Dashboard: So funktioniert es",
        pt: "Todos os seus dispositivos em um painel: como funciona",
        fr: "Tous vos appareils dans un tableau de bord: comment ça marche",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Connettere Withings a Health Connect o HealthKit è il primo passo. Poi serve qualcosa che legga quei dati e li mostri in modo utile, insieme a tutto il resto: il tuo orologio sportivo, i passi registrati dallo smartphone, eventuali altri wearable. L'idea di una dashboard unificata è che non devi più aprire tre app diverse per avere un quadro completo della tua giornata.",
        en: "Connecting Withings to Health Connect or HealthKit is the first step. Then you need something that reads those data and displays them usefully, together with everything else: your sports watch, steps recorded by the smartphone, any other wearables. The idea of a unified dashboard is that you no longer need to open three different apps to get a full picture of your day.",
        es: "Conectar Withings a Health Connect o HealthKit es el primer paso. Luego necesitas algo que lea esos datos y los muestre de forma útil, junto con todo lo demás: tu reloj deportivo, los pasos registrados por el smartphone, otros wearables que puedas tener. La idea de un panel unificado es que ya no tengas que abrir tres apps diferentes para tener una visión completa de tu día.",
        de: "Withings mit Health Connect oder HealthKit zu verbinden ist der erste Schritt. Dann brauchst du etwas, das diese Daten ausliest und nützlich anzeigt, zusammen mit allem anderen: deiner Sportuhr, den vom Smartphone erfassten Schritten, anderen Wearables. Die Idee eines einheitlichen Dashboards ist, dass du nicht mehr drei verschiedene Apps öffnen musst, um ein vollständiges Bild deines Tages zu erhalten.",
        pt: "Conectar a Withings ao Health Connect ou ao HealthKit é o primeiro passo. Depois você precisa de algo que leia esses dados e os exiba de forma útil, junto com tudo o mais: seu relógio esportivo, os passos registrados pelo smartphone, outros wearables que você tenha. A ideia de um painel unificado é que você não precise mais abrir três apps diferentes para ter uma visão completa do seu dia.",
        fr: "Connecter Withings à Health Connect ou HealthKit est la première étape. Ensuite, vous avez besoin de quelque chose qui lise ces données et les affiche de façon utile, avec tout le reste: votre montre sportive, les pas enregistrés par le smartphone, d'autres wearables éventuels. L'idée d'un tableau de bord unifié est de ne plus avoir à ouvrir trois applications différentes pour avoir une vue d'ensemble de votre journée.",
      },
    },
    {
      type: "table",
      caption: {
        it: "Cosa vedi in una dashboard unificata da Withings",
        en: "What you see in a unified dashboard from Withings",
        es: "Qué ves en un panel unificado con datos de Withings",
        de: "Was du in einem einheitlichen Dashboard aus Withings siehst",
        pt: "O que você vê em um painel unificado com dados da Withings",
        fr: "Ce que vous voyez dans un tableau de bord unifié depuis Withings",
      },
      headers: {
        it: ["Fonte dati", "Cosa arriva in dashboard", "Note"],
        en: ["Data source", "What arrives in dashboard", "Notes"],
        es: ["Fuente de datos", "Qué llega al panel", "Notas"],
        de: ["Datenquelle", "Was ins Dashboard kommt", "Hinweise"],
        pt: ["Fonte de dados", "O que chega ao painel", "Observações"],
        fr: ["Source de données", "Ce qui arrive dans le tableau de bord", "Notes"],
      },
      rows: [
        {
          it: ["Bilancia Withings (Body+)", "Peso, indice di massa corporea, grasso, muscolo (base)", "Le metriche avanzate restano in Health Mate"],
          en: ["Withings scale (Body+)", "Weight, body mass index, fat, muscle (basic)", "Advanced metrics stay in Health Mate"],
          es: ["Báscula Withings (Body+)", "Peso, índice de masa corporal, grasa, músculo (básico)", "Las métricas avanzadas permanecen en Health Mate"],
          de: ["Withings Waage (Body+)", "Gewicht, Body-Mass-Index, Fett, Muskel (Basis)", "Erweiterte Messwerte bleiben in Health Mate"],
          pt: ["Balança Withings (Body+)", "Peso, índice de massa corporal, gordura, músculo (básico)", "As métricas avançadas ficam no Health Mate"],
          fr: ["Balance Withings (Body+)", "Poids, indice de masse corporelle, graisse, muscle (basique)", "Les métriques avancées restent dans Health Mate"],
        },
        {
          it: ["ScanWatch / orologio ibrido", "Passi, distanza, frequenza cardiaca, calorie", "GPS solo se il modello lo supporta"],
          en: ["ScanWatch / hybrid watch", "Steps, distance, heart rate, calories", "GPS only if the model supports it"],
          es: ["ScanWatch / reloj híbrido", "Pasos, distancia, frecuencia cardíaca, calorías", "GPS solo si el modelo lo admite"],
          de: ["ScanWatch / Hybrid-Uhr", "Schritte, Distanz, Herzfrequenz, Kalorien", "GPS nur wenn das Modell es unterstützt"],
          pt: ["ScanWatch / relógio híbrido", "Passos, distância, frequência cardíaca, calorias", "GPS apenas se o modelo suportar"],
          fr: ["ScanWatch / montre hybride", "Pas, distance, fréquence cardiaque, calories", "GPS uniquement si le modèle le prend en charge"],
        },
        {
          it: ["Withings Sleep (sensore materasso)", "Durata sonno, fasi, frequenza cardiaca notturna", "Dati di qualità; funziona senza indossare nulla"],
          en: ["Withings Sleep (mattress sensor)", "Sleep duration, phases, overnight heart rate", "Quality data; works without wearing anything"],
          es: ["Withings Sleep (sensor de colchón)", "Duración del sueño, fases, frecuencia cardíaca nocturna", "Datos de calidad; funciona sin llevar nada puesto"],
          de: ["Withings Sleep (Matratzen-Sensor)", "Schlafdauer, Phasen, nächtliche Herzfrequenz", "Qualitätsdaten; funktioniert ohne etwas zu tragen"],
          pt: ["Withings Sleep (sensor de colchão)", "Duração do sono, fases, frequência cardíaca noturna", "Dados de qualidade; funciona sem usar nada"],
          fr: ["Withings Sleep (capteur de matelas)", "Durée du sommeil, phases, fréquence cardiaque nocturne", "Données de qualité; fonctionne sans rien porter"],
        },
        {
          it: ["BPM Connect (pressione)", "Pressione sistolica, diastolica, frequenza cardiaca", "Lettura manuale: i dati arrivano dopo ogni misurazione"],
          en: ["BPM Connect (blood pressure)", "Systolic, diastolic pressure, heart rate", "Manual reading: data arrives after each measurement"],
          es: ["BPM Connect (tensión arterial)", "Tensión sistólica, diastólica, frecuencia cardíaca", "Lectura manual: los datos llegan tras cada medición"],
          de: ["BPM Connect (Blutdruck)", "Systolischer, diastolischer Druck, Herzfrequenz", "Manuelle Messung: Daten kommen nach jeder Messung"],
          pt: ["BPM Connect (pressão arterial)", "Pressão sistólica, diastólica, frequência cardíaca", "Leitura manual: os dados chegam após cada medição"],
          fr: ["BPM Connect (tension artérielle)", "Pression systolique, diastolique, fréquence cardiaque", "Lecture manuelle: les données arrivent après chaque mesure"],
        },
      ],
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Privacy e cloud EU: perché conta scegliere bene",
        en: "Privacy and EU cloud: why choosing wisely matters",
        es: "Privacidad y nube europea: por qué importa elegir bien",
        de: "Datenschutz und EU-Cloud: Warum die richtige Wahl wichtig ist",
        pt: "Privacidade e nuvem europeia: por que é importante escolher bem",
        fr: "Confidentialité et cloud européen: pourquoi le bon choix compte",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Withings è stata fondata a Parigi nel 2008 e i suoi server sono in Europa. Questo non è un dettaglio: per i dati di salute, la localizzazione dei server e le leggi applicabili fanno una differenza concreta. Il Regolamento europeo sulla protezione dei dati (GDPR) impone requisiti precisi su come i dati personali vengono raccolti, conservati e condivisi, con diritto alla cancellazione e alla portabilità. Quando scegli dove far vivere i tuoi dati di peso, sonno e attività, vale la pena controllare dove si trovano fisicamente i server dell'app che usi.",
        en: "Withings was founded in Paris in 2008 and its servers are in Europe. This is not a minor detail: for health data, the location of servers and applicable laws make a concrete difference. The European data protection regulation (GDPR) sets precise requirements on how personal data is collected, stored and shared, with rights to erasure and portability. When you choose where your weight, sleep and activity data lives, it is worth checking where the servers of the app you use are physically located.",
        es: "Withings fue fundada en París en 2008 y sus servidores están en Europa. Esto no es un detalle menor: para los datos de salud, la ubicación de los servidores y las leyes aplicables marcan una diferencia concreta. El Reglamento europeo de protección de datos (RGPD) establece requisitos precisos sobre cómo se recopilan, almacenan y comparten los datos personales, con derechos de supresión y portabilidad. Cuando eliges dónde viven tus datos de peso, sueño y actividad, merece la pena comprobar dónde están físicamente los servidores de la app que usas.",
        de: "Withings wurde 2008 in Paris gegründet und seine Server stehen in Europa. Das ist kein Nebendetail: Bei Gesundheitsdaten machen der Serverstandort und die geltenden Gesetze einen konkreten Unterschied. Die europäische Datenschutzverordnung (DSGVO) stellt genaue Anforderungen an die Erfassung, Speicherung und Weitergabe personenbezogener Daten, mit Rechten auf Löschung und Portabilität. Wenn du entscheidest, wo deine Gewichts-, Schlaf- und Aktivitätsdaten gespeichert werden, lohnt es sich zu prüfen, wo die Server der App, die du verwendest, physisch stehen.",
        pt: "A Withings foi fundada em Paris em 2008 e seus servidores ficam na Europa. Isso não é um detalhe menor: para dados de saúde, a localização dos servidores e as leis aplicáveis fazem uma diferença concreta. O regulamento europeu de proteção de dados (RGPD) estabelece requisitos precisos sobre como os dados pessoais são coletados, armazenados e compartilhados, com direito ao apagamento e à portabilidade. Quando você escolhe onde ficam seus dados de peso, sono e atividade, vale verificar onde os servidores do app que você usa estão fisicamente localizados.",
        fr: "Withings a été fondée à Paris en 2008 et ses serveurs sont en Europe. Ce n'est pas un détail mineur: pour les données de santé, la localisation des serveurs et les lois applicables font une différence concrète. Le règlement européen sur la protection des données (RGPD) impose des exigences précises sur la façon dont les données personnelles sont collectées, conservées et partagées, avec des droits à l'effacement et à la portabilité. Lorsque vous choisissez où vivent vos données de poids, de sommeil et d'activité, il vaut la peine de vérifier où se trouvent physiquement les serveurs de l'application que vous utilisez.",
      },
    },
    {
      type: "callout",
      variant: "tip",
      title: {
        it: "Withings e il GDPR",
        en: "Withings and GDPR",
        es: "Withings y el RGPD",
        de: "Withings und die DSGVO",
        pt: "Withings e o RGPD",
        fr: "Withings et le RGPD",
      },
      body: {
        it: "In quanto azienda con sede in Francia, Withings è soggetta al GDPR e alla supervisione della CNIL (l'autorità francese per la protezione dei dati). Puoi richiedere l'export completo dei tuoi dati o la cancellazione dell'account direttamente dall'app Health Mate nelle impostazioni dell'account. Questo è un diritto, non un favore.",
        en: "As a company headquartered in France, Withings is subject to GDPR and oversight by the CNIL (the French data protection authority). You can request a full export of your data or account deletion directly from the Health Mate app in account settings. This is a right, not a favour.",
        es: "Como empresa con sede en Francia, Withings está sujeta al RGPD y a la supervisión de la CNIL (la autoridad francesa de protección de datos). Puedes solicitar un export completo de tus datos o la eliminación de la cuenta directamente desde la app Health Mate en los ajustes de cuenta. Es un derecho, no un favor.",
        de: "Als in Frankreich ansässiges Unternehmen unterliegt Withings der DSGVO und der Aufsicht der CNIL (der französischen Datenschutzbehörde). Du kannst einen vollständigen Export deiner Daten oder die Kontolöschung direkt in der Health Mate App unter den Kontoeinstellungen anfordern. Das ist ein Recht, keine Gefälligkeit.",
        pt: "Como empresa com sede na França, a Withings está sujeita ao RGPD e à supervisão da CNIL (a autoridade francesa de proteção de dados). Você pode solicitar um export completo dos seus dados ou a exclusão da conta diretamente no app Health Mate nas configurações da conta. Este é um direito, não um favor.",
        fr: "En tant qu'entreprise dont le siège est en France, Withings est soumise au RGPD et à la supervision de la CNIL (l'autorité française de protection des données). Vous pouvez demander un export complet de vos données ou la suppression de votre compte directement depuis l'application Health Mate dans les paramètres du compte. C'est un droit, pas une faveur.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Unire Withings agli altri dispositivi: il quadro completo",
        en: "Combining Withings with other devices: the full picture",
        es: "Combinar Withings con otros dispositivos: el panorama completo",
        de: "Withings mit anderen Geräten kombinieren: das Gesamtbild",
        pt: "Combinar a Withings com outros dispositivos: o quadro completo",
        fr: "Combiner Withings avec d'autres appareils: le tableau complet",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Molte persone usano Withings in combinazione con un altro dispositivo: un orologio sportivo per gli allenamenti, o semplicemente lo smartphone per i passi quotidiani. La sfida è che ogni brand tende a creare il proprio ecosistema chiuso, e passare da un'app all'altra per capire come è andata la settimana non è pratico. Una dashboard unificata risolve proprio questo: aggrega i dati da fonti diverse in un unico posto, accessibile da browser senza dover aprire ogni singola app.",
        en: "Many people use Withings in combination with another device: a sports watch for workouts, or simply the smartphone for daily steps. The challenge is that each brand tends to create its own closed ecosystem, and switching between apps to understand how the week went is not practical. A unified dashboard solves exactly this: it aggregates data from different sources in one place, accessible from a browser without having to open each individual app.",
        es: "Mucha gente usa Withings junto con otro dispositivo: un reloj deportivo para los entrenamientos, o simplemente el smartphone para los pasos diarios. El reto es que cada marca tiende a crear su propio ecosistema cerrado, y pasar de una app a otra para entender cómo ha ido la semana no es nada práctico. Un panel unificado resuelve exactamente esto: agrupa los datos de distintas fuentes en un solo lugar, accesible desde el navegador sin necesidad de abrir cada app por separado.",
        de: "Viele Menschen verwenden Withings in Kombination mit einem anderen Gerät: einer Sportuhr für Trainings oder einfach dem Smartphone für tägliche Schritte. Die Herausforderung ist, dass jede Marke dazu neigt, ihr eigenes geschlossenes Ökosystem zu schaffen, und das Wechseln zwischen Apps, um zu verstehen, wie die Woche gelaufen ist, ist nicht praktisch. Ein einheitliches Dashboard löst genau das: Es aggregiert Daten aus verschiedenen Quellen an einem Ort, über einen Browser zugänglich, ohne jede einzelne App öffnen zu müssen.",
        pt: "Muitas pessoas usam a Withings em combinação com outro dispositivo: um relógio esportivo para os treinos ou simplesmente o smartphone para os passos diários. O desafio é que cada marca tende a criar seu próprio ecossistema fechado, e ficar trocando de app para entender como foi a semana não é prático. Um painel unificado resolve exatamente isso: agrega dados de fontes diferentes em um único lugar, acessível pelo navegador sem precisar abrir cada app separadamente.",
        fr: "Beaucoup de personnes utilisent Withings en combinaison avec un autre appareil: une montre sportive pour les séances d'entraînement, ou simplement le smartphone pour les pas quotidiens. Le défi est que chaque marque tend à créer son propre écosystème fermé, et passer d'une application à l'autre pour comprendre comment s'est passée la semaine n'est pas pratique. Un tableau de bord unifié résout exactement cela: il agrège les données de différentes sources en un seul endroit, accessible depuis un navigateur sans avoir à ouvrir chaque application séparément.",
      },
    },
    {
      type: "comparison",
      aTitle: {
        it: "Cosa funziona bene con Withings",
        en: "What works well with Withings",
        es: "Qué funciona bien con Withings",
        de: "Was mit Withings gut funktioniert",
        pt: "O que funciona bem com a Withings",
        fr: "Ce qui fonctionne bien avec Withings",
      },
      aItems: {
        it: [
          "Dati di peso e composizione corporea costanti nel tempo (misuri ogni mattina, hai una serie storica)",
          "Sonno automatico senza indossare nulla (con il sensore da materasso)",
          "Frequenza cardiaca passiva rilevata dalla bilancia (non solo da orologio)",
          "Privacy: brand europeo, server in Europa, diritti GDPR applicabili",
          "Batteria lunga (orologi ibridi durano settimane, bilance mesi)",
        ],
        en: [
          "Consistent weight and body composition data over time (you measure every morning, you have a historical series)",
          "Automatic sleep without wearing anything (with the mattress sensor)",
          "Passive heart rate detected by the scale (not just from the watch)",
          "Privacy: European brand, servers in Europe, applicable GDPR rights",
          "Long battery life (hybrid watches last weeks, scales last months)",
        ],
        es: [
          "Datos constantes de peso y composición corporal a lo largo del tiempo (mides cada mañana y tienes una serie histórica)",
          "Seguimiento del sueño automático sin llevar nada puesto (con el sensor de colchón)",
          "Frecuencia cardíaca pasiva detectada por la báscula (no solo desde el reloj)",
          "Privacidad: marca europea, servidores en Europa, derechos RGPD aplicables",
          "Batería de larga duración (los relojes híbridos duran semanas, las básculas meses)",
        ],
        de: [
          "Konsistente Gewichts- und Körperzusammensetzungsdaten über Zeit (du misst jeden Morgen, du hast eine historische Reihe)",
          "Automatischer Schlaf ohne etwas zu tragen (mit dem Matratzen-Sensor)",
          "Passive Herzfrequenz von der Waage erfasst (nicht nur von der Uhr)",
          "Datenschutz: europäische Marke, Server in Europa, anwendbare DSGVO-Rechte",
          "Lange Akkulaufzeit (Hybrid-Uhren halten Wochen, Waagen Monate)",
        ],
        pt: [
          "Dados consistentes de peso e composição corporal ao longo do tempo (você mede toda manhã e tem uma série histórica)",
          "Monitoramento de sono automático sem usar nada (com o sensor de colchão)",
          "Frequência cardíaca passiva detectada pela balança (não apenas pelo relógio)",
          "Privacidade: marca europeia, servidores na Europa, direitos RGPD aplicáveis",
          "Bateria de longa duração (relógios híbridos duram semanas, balanças meses)",
        ],
        fr: [
          "Données de poids et de composition corporelle constantes dans le temps (vous vous pesez chaque matin, vous disposez d'une série historique)",
          "Suivi du sommeil automatique sans rien porter (avec le capteur de matelas)",
          "Fréquence cardiaque passive détectée par la balance (pas uniquement par la montre)",
          "Confidentialité: marque européenne, serveurs en Europe, droits RGPD applicables",
          "Longue autonomie (les montres hybrides durent des semaines, les balances des mois)",
        ],
      },
      bTitle: {
        it: "Limiti onesti da conoscere",
        en: "Honest limits to know",
        es: "Limitaciones honestas que conviene conocer",
        de: "Ehrliche Grenzen, die du kennen solltest",
        pt: "Limites honestos que você deve conhecer",
        fr: "Limites honnêtes à connaître",
      },
      bItems: {
        it: [
          "Alcune metriche avanzate di composizione corporea non escono dall'app Health Mate verso terze parti",
          "Gli orologi ibridi non hanno GPS integrato in tutti i modelli: attività outdoor potrebbero non avere traccia GPS",
          "La sincronizzazione verso Health Connect non è sempre in tempo reale: può richiedere che l'app Health Mate sia aperta",
          "Per vedere i dati Withings su browser (non solo su app) serve una soluzione di terze parti che li legga da Health Connect",
          "Il sensore da materasso Withings Sleep richiede una spesa aggiuntiva rispetto alla sola bilancia",
        ],
        en: [
          "Some advanced body composition metrics do not leave the Health Mate app toward third parties",
          "Hybrid watches do not have built-in GPS in all models: outdoor activities might lack GPS tracking",
          "Syncing to Health Connect is not always real-time: it may require the Health Mate app to be open",
          "To view Withings data in a browser (not just on the app) you need a third-party solution that reads it from Health Connect",
          "The Withings Sleep mattress sensor requires additional spending beyond the scale alone",
        ],
        es: [
          "Algunas métricas avanzadas de composición corporal no salen de la app Health Mate hacia terceros",
          "Los relojes híbridos no tienen GPS integrado en todos los modelos: las actividades al aire libre pueden carecer de seguimiento GPS",
          "La sincronización con Health Connect no es siempre en tiempo real: puede requerir que la app Health Mate esté abierta",
          "Para ver los datos de Withings en un navegador (no solo en la app) se necesita una solución de terceros que los lea desde Health Connect",
          "El sensor de colchón Withings Sleep requiere un gasto adicional más allá de la báscula",
        ],
        de: [
          "Einige erweiterte Körperzusammensetzungs-Messwerte verlassen die Health Mate App nicht in Richtung Drittanbieter",
          "Hybrid-Uhren haben nicht in allen Modellen integriertes GPS: Outdoor-Aktivitäten könnten ohne GPS-Tracking sein",
          "Die Synchronisierung mit Health Connect ist nicht immer in Echtzeit: Es kann erforderlich sein, dass die Health Mate App geöffnet ist",
          "Um Withings-Daten im Browser zu sehen (nicht nur in der App), brauchst du eine Drittanbieter-Lösung, die sie aus Health Connect liest",
          "Der Withings Sleep Matratzen-Sensor erfordert zusätzliche Ausgaben über die Waage hinaus",
        ],
        pt: [
          "Algumas métricas avançadas de composição corporal não saem do app Health Mate para terceiros",
          "Os relógios híbridos não têm GPS integrado em todos os modelos: atividades ao ar livre podem não ter rastreamento GPS",
          "A sincronização com o Health Connect nem sempre é em tempo real: pode exigir que o app Health Mate esteja aberto",
          "Para ver os dados da Withings no navegador (não apenas no app) você precisa de uma solução de terceiros que os leia do Health Connect",
          "O sensor de colchão Withings Sleep requer um gasto adicional além da balança",
        ],
        fr: [
          "Certaines métriques avancées de composition corporelle ne quittent pas l'application Health Mate vers des tiers",
          "Les montres hybrides n'ont pas de GPS intégré sur tous les modèles: les activités en extérieur peuvent manquer de suivi GPS",
          "La synchronisation vers Health Connect n'est pas toujours en temps réel: elle peut nécessiter que l'application Health Mate soit ouverte",
          "Pour consulter les données Withings dans un navigateur (pas seulement dans l'app), il vous faut une solution tierce qui les lise depuis Health Connect",
          "Le capteur de matelas Withings Sleep nécessite une dépense supplémentaire au-delà de la simple balance",
        ],
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "FitMesh Sync e Withings: cosa puoi aspettarti",
        en: "FitMesh Sync and Withings: what to expect",
        es: "FitMesh Sync y Withings: qué puedes esperar",
        de: "FitMesh Sync und Withings: Was du erwarten kannst",
        pt: "FitMesh Sync e Withings: o que esperar",
        fr: "FitMesh Sync et Withings: à quoi s'attendre",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "FitMesh Sync legge i dati da Health Connect (Android) e da HealthKit (iOS) e li mostra in una dashboard web accessibile da qualsiasi browser, anche da PC o tablet, senza dover aprire l'app dello smartphone ogni volta. Se hai già connesso Withings a Health Connect o HealthKit seguendo i passi qui sopra, i dati di peso, passi, sonno e frequenza cardiaca da Withings arriveranno automaticamente nella dashboard insieme a quelli degli altri dispositivi che usi.",
        en: "FitMesh Sync reads data from Health Connect (Android) and HealthKit (iOS) and displays it in a web dashboard accessible from any browser, including from a PC or tablet, without having to open the smartphone app each time. If you have already connected Withings to Health Connect or HealthKit following the steps above, weight, steps, sleep and heart rate data from Withings will automatically arrive in the dashboard alongside data from other devices you use.",
        es: "FitMesh Sync lee los datos de Health Connect (Android) y HealthKit (iOS) y los muestra en un panel web accesible desde cualquier navegador, incluido PC o tablet, sin necesidad de abrir la app del smartphone cada vez. Si ya has conectado Withings a Health Connect o HealthKit siguiendo los pasos anteriores, los datos de peso, pasos, sueño y frecuencia cardíaca de Withings llegarán automáticamente al panel junto con los de los demás dispositivos que uses.",
        de: "FitMesh Sync liest Daten aus Health Connect (Android) und HealthKit (iOS) und zeigt sie in einem Web-Dashboard an, das von jedem Browser aus zugänglich ist, auch von PC oder Tablet, ohne jedes Mal die Smartphone-App öffnen zu müssen. Wenn du Withings bereits gemäß den obigen Schritten mit Health Connect oder HealthKit verbunden hast, kommen Gewichts-, Schritt-, Schlaf- und Herzfrequenzdaten von Withings automatisch im Dashboard an, zusammen mit Daten von anderen Geräten, die du verwendest.",
        pt: "O FitMesh Sync lê os dados do Health Connect (Android) e do HealthKit (iOS) e os exibe em um painel web acessível por qualquer navegador, inclusive pelo PC ou tablet, sem precisar abrir o app do smartphone a cada vez. Se você já conectou a Withings ao Health Connect ou ao HealthKit seguindo os passos acima, os dados de peso, passos, sono e frequência cardíaca da Withings chegarão automaticamente ao painel junto com os dos outros dispositivos que você usa.",
        fr: "FitMesh Sync lit les données de Health Connect (Android) et HealthKit (iOS) et les affiche dans un tableau de bord web accessible depuis n'importe quel navigateur, y compris depuis un PC ou une tablette, sans avoir à ouvrir l'application smartphone à chaque fois. Si vous avez déjà connecté Withings à Health Connect ou HealthKit en suivant les étapes ci-dessus, les données de poids, de pas, de sommeil et de fréquence cardiaque de Withings arriveront automatiquement dans le tableau de bord aux côtés des données de vos autres appareils.",
      },
    },
    {
      type: "callout",
      variant: "info",
      title: {
        it: "Withings è supportato tramite Health Connect e HealthKit",
        en: "Withings is supported via Health Connect and HealthKit",
        es: "Withings es compatible a través de Health Connect y HealthKit",
        de: "Withings wird über Health Connect und HealthKit unterstützt",
        pt: "Withings é suportado pelo Health Connect e pelo HealthKit",
        fr: "Withings est pris en charge via Health Connect et HealthKit",
      },
      body: {
        it: "FitMesh Sync si collega a Withings tramite le piattaforme standard (Health Connect su Android, HealthKit su iOS): non serve connettere direttamente l'account Withings né condividere le credenziali Health Mate. Il flusso è: Withings scrive su Health Connect/HealthKit, FitMesh Sync legge da lì. I tuoi dati rimangono sempre sotto il tuo controllo, in un cloud con server europei.",
        en: "FitMesh Sync connects to Withings via standard platforms (Health Connect on Android, HealthKit on iOS): there is no need to connect your Withings account directly or share Health Mate credentials. The flow is: Withings writes to Health Connect/HealthKit, FitMesh Sync reads from there. Your data always remains under your control, in a cloud with European servers.",
        es: "FitMesh Sync se conecta a Withings a través de las plataformas estándar (Health Connect en Android, HealthKit en iOS): no es necesario conectar directamente la cuenta de Withings ni compartir las credenciales de Health Mate. El flujo es: Withings escribe en Health Connect/HealthKit, FitMesh Sync lee desde ahí. Tus datos permanecen siempre bajo tu control, en una nube con servidores europeos.",
        de: "FitMesh Sync verbindet sich über Standardplattformen mit Withings (Health Connect auf Android, HealthKit auf iOS): Es ist nicht nötig, dein Withings-Konto direkt zu verbinden oder Health Mate-Anmeldedaten zu teilen. Der Ablauf ist: Withings schreibt in Health Connect/HealthKit, FitMesh Sync liest von dort. Deine Daten bleiben immer unter deiner Kontrolle, in einer Cloud mit europäischen Servern.",
        pt: "O FitMesh Sync se conecta à Withings pelas plataformas padrão (Health Connect no Android, HealthKit no iOS): não é necessário conectar diretamente a conta da Withings nem compartilhar as credenciais do Health Mate. O fluxo é: a Withings escreve no Health Connect/HealthKit, o FitMesh Sync lê de lá. Seus dados sempre permanecem sob seu controle, em uma nuvem com servidores europeus.",
        fr: "FitMesh Sync se connecte à Withings via les plateformes standard (Health Connect sur Android, HealthKit sur iOS): il n'est pas nécessaire de connecter directement votre compte Withings ni de partager les identifiants Health Mate. Le flux est le suivant: Withings écrit dans Health Connect/HealthKit, FitMesh Sync lit depuis là. Vos données restent toujours sous votre contrôle, dans un cloud avec des serveurs européens.",
      },
    },
    {
      type: "cta",
      title: {
        it: "Vuoi vedere peso, sonno e attività Withings in un'unica dashboard?",
        en: "Want to see Withings weight, sleep and activity in one dashboard?",
        es: "¿Quieres ver el peso, el sueño y la actividad de Withings en un solo panel?",
        de: "Möchtest du Withings-Gewicht, Schlaf und Aktivität in einem Dashboard sehen?",
        pt: "Quer ver peso, sono e atividade da Withings em um único painel?",
        fr: "Vous souhaitez voir le poids, le sommeil et l'activité Withings dans un seul tableau de bord?",
      },
      body: {
        it: "FitMesh Sync raccoglie i dati da Health Connect e HealthKit (dove Withings scrive automaticamente) e li unisce in una dashboard web accessibile da browser. Niente export manuale, niente app aggiuntive: funziona da quando autorizzi Health Connect la prima volta. Server europei, privacy EU, nessun abbonamento per iniziare.",
        en: "FitMesh Sync collects data from Health Connect and HealthKit (where Withings writes automatically) and combines them in a browser-accessible web dashboard. No manual export, no extra apps: it works from the moment you authorise Health Connect for the first time. European servers, EU privacy, no subscription to get started.",
        es: "FitMesh Sync recopila datos de Health Connect y HealthKit (donde Withings escribe automáticamente) y los une en un panel web accesible desde el navegador. Sin exportaciones manuales, sin apps adicionales: funciona desde el momento en que autorizas Health Connect por primera vez. Servidores europeos, privacidad europea, sin suscripción para empezar.",
        de: "FitMesh Sync sammelt Daten aus Health Connect und HealthKit (wo Withings automatisch schreibt) und kombiniert sie in einem browser-zugänglichen Web-Dashboard. Kein manueller Export, keine zusätzlichen Apps: Es funktioniert ab dem Moment, in dem du Health Connect zum ersten Mal autorisierst. Europäische Server, EU-Datenschutz, kein Abonnement für den Einstieg.",
        pt: "O FitMesh Sync coleta dados do Health Connect e do HealthKit (onde a Withings escreve automaticamente) e os combina em um painel web acessível pelo navegador. Sem export manual, sem apps extras: funciona desde o momento em que você autoriza o Health Connect pela primeira vez. Servidores europeus, privacidade europeia, sem assinatura para começar.",
        fr: "FitMesh Sync collecte les données de Health Connect et HealthKit (où Withings écrit automatiquement) et les combine dans un tableau de bord web accessible depuis le navigateur. Aucun export manuel, aucune application supplémentaire: cela fonctionne dès que vous autorisez Health Connect pour la première fois. Serveurs européens, confidentialité européenne, aucun abonnement pour démarrer.",
      },
      ctaLabel: {
        it: "Entra nel programma fondatori di FitMesh Sync",
        en: "Join the FitMesh Sync founders programme",
        es: "Únete al programa de fundadores de FitMesh Sync",
        de: "Dem FitMesh Sync Gründerprogramm beitreten",
        pt: "Entre no programa de fundadores do FitMesh Sync",
        fr: "Rejoindre le programme fondateurs de FitMesh Sync",
      },
      ctaHref: {
        it: "/it/beta",
        en: "/en/beta",
        es: "/es/beta",
        de: "/de/beta",
        pt: "/pt/beta",
        fr: "/fr/beta",
      },
    },
  ],
  faq: [
    {
      q: {
        it: "Withings si connette direttamente a Health Connect o devo fare qualcosa?",
        en: "Does Withings connect directly to Health Connect or do I need to do something?",
        es: "¿Withings se conecta directamente a Health Connect o tengo que hacer algo?",
        de: "Verbindet sich Withings direkt mit Health Connect oder muss ich etwas tun?",
        pt: "A Withings se conecta diretamente ao Health Connect ou preciso fazer algo?",
        fr: "Withings se connecte-t-il directement à Health Connect ou dois-je faire quelque chose?",
      },
      a: {
        it: "Non è automatico: devi attivare la connessione una volta dall'app Health Mate. Vai su Profilo, poi Impostazioni, poi cerca 'App connesse' o 'Health Connect' e segui la procedura di autorizzazione. Una volta fatto, la sincronizzazione avviene in automatico ogni volta che Health Mate si aggiorna.",
        en: "It is not automatic: you need to activate the connection once from the Health Mate app. Go to Profile, then Settings, then find 'Connected apps' or 'Health Connect' and follow the authorisation procedure. Once done, syncing happens automatically each time Health Mate updates.",
        es: "No es automático: tienes que activar la conexión una vez desde la app Health Mate. Ve a Perfil, luego Ajustes, luego busca 'Apps conectadas' o 'Health Connect' y sigue el proceso de autorización. Una vez hecho, la sincronización se produce automáticamente cada vez que Health Mate se actualiza.",
        de: "Es ist nicht automatisch: Du musst die Verbindung einmalig über die Health Mate App aktivieren. Gehe zu Profil, dann Einstellungen, dann suche 'Verbundene Apps' oder 'Health Connect' und folge dem Autorisierungsverfahren. Danach erfolgt die Synchronisierung automatisch, jedes Mal wenn Health Mate aktualisiert.",
        pt: "Não é automático: você precisa ativar a conexão uma vez pelo app Health Mate. Vá em Perfil, depois Configurações, depois procure 'Apps conectados' ou 'Health Connect' e siga o procedimento de autorização. Uma vez feito isso, a sincronização acontece automaticamente toda vez que o Health Mate atualiza.",
        fr: "Ce n'est pas automatique: vous devez activer la connexion une fois depuis l'application Health Mate. Allez dans Profil, puis Paramètres, puis cherchez 'Applications connectées' ou 'Health Connect' et suivez la procédure d'autorisation. Une fois cela fait, la synchronisation s'effectue automatiquement chaque fois que Health Mate se met à jour.",
      },
    },
    {
      q: {
        it: "I dati della composizione corporea di Withings (grasso, muscolo) arrivano su Health Connect?",
        en: "Does Withings body composition data (fat, muscle) reach Health Connect?",
        es: "¿Los datos de composición corporal de Withings (grasa, músculo) llegan a Health Connect?",
        de: "Kommen Withings Körperzusammensetzungsdaten (Fett, Muskel) bei Health Connect an?",
        pt: "Os dados de composição corporal da Withings (gordura, músculo) chegam ao Health Connect?",
        fr: "Les données de composition corporelle Withings (graisse, muscle) arrivent-elles dans Health Connect?",
      },
      a: {
        it: "In parte. Il peso arriva regolarmente. Per grasso, muscolo e idratazione dipende dal modello di bilancia e dalla versione dell'app: alcune metriche vengono trasmesse, altre rimangono solo in Health Mate. Puoi verificarlo aprendo Health Connect e guardando quali tipi di dati Withings ha scritto. Per la composizione corporea dettagliata, l'app Health Mate rimane il posto dove vedi tutto.",
        en: "Partly. Weight arrives regularly. For fat, muscle and hydration it depends on the scale model and app version: some metrics are transmitted, others remain only in Health Mate. You can check by opening Health Connect and looking at which data types Withings has written. For detailed body composition, the Health Mate app remains the place where you see everything.",
        es: "En parte. El peso llega de manera regular. Para grasa, músculo e hidratación depende del modelo de báscula y de la versión de la app: algunas métricas se transmiten, otras se quedan solo en Health Mate. Puedes comprobarlo abriendo Health Connect y viendo qué tipos de datos ha escrito Withings. Para la composición corporal detallada, la app Health Mate sigue siendo donde ves todo.",
        de: "Teilweise. Das Gewicht kommt regelmäßig an. Bei Fett, Muskel und Hydratation hängt es vom Waagenmodell und der App-Version ab: Einige Messwerte werden übertragen, andere bleiben nur in Health Mate. Du kannst dies überprüfen, indem du Health Connect öffnest und schaust, welche Datentypen Withings geschrieben hat. Für detaillierte Körperzusammensetzung bleibt die Health Mate App der Ort, wo du alles siehst.",
        pt: "Em parte. O peso chega regularmente. Para gordura, músculo e hidratação depende do modelo de balança e da versão do app: algumas métricas são transmitidas, outras ficam apenas no Health Mate. Você pode verificar abrindo o Health Connect e vendo quais tipos de dados a Withings escreveu. Para composição corporal detalhada, o app Health Mate continua sendo o lugar onde você vê tudo.",
        fr: "En partie. Le poids arrive régulièrement. Pour la graisse, le muscle et l'hydratation, cela dépend du modèle de balance et de la version de l'application: certaines métriques sont transmises, d'autres restent uniquement dans Health Mate. Vous pouvez vérifier en ouvrant Health Connect et en regardant quels types de données Withings a écrits. Pour la composition corporelle détaillée, l'application Health Mate reste l'endroit où vous voyez tout.",
      },
    },
    {
      q: {
        it: "Withings funziona anche senza telefono Android o iPhone nelle vicinanze?",
        en: "Does Withings work even without an Android phone or iPhone nearby?",
        es: "¿Withings funciona incluso sin un teléfono Android o iPhone cerca?",
        de: "Funktioniert Withings auch ohne Android-Telefon oder iPhone in der Nähe?",
        pt: "A Withings funciona mesmo sem um telefone Android ou iPhone por perto?",
        fr: "Withings fonctionne-t-il même sans téléphone Android ou iPhone à proximité?",
      },
      a: {
        it: "Sì, la maggior parte dei dispositivi Withings (bilance incluse) si connette direttamente alla rete Wi-Fi di casa e carica i dati sul cloud Withings senza passare dallo smartphone. Il telefono serve per la configurazione iniziale e per autorizzare le connessioni con Health Connect. Una volta configurato, puoi pesarti al mattino e i dati arrivano nell'app anche se il telefono è in un'altra stanza.",
        en: "Yes, most Withings devices (scales included) connect directly to the home Wi-Fi and upload data to the Withings cloud without going through the smartphone. The phone is needed for initial setup and authorising connections with Health Connect. Once configured, you can weigh yourself in the morning and the data arrives in the app even if the phone is in another room.",
        es: "Sí, la mayoría de los dispositivos Withings (incluidas las básculas) se conectan directamente a la red Wi-Fi del hogar y suben los datos a la nube de Withings sin pasar por el smartphone. El teléfono se necesita para la configuración inicial y para autorizar las conexiones con Health Connect. Una vez configurado, puedes pesarte por la mañana y los datos llegan a la app aunque el teléfono esté en otra habitación.",
        de: "Ja, die meisten Withings-Geräte (einschließlich Waagen) verbinden sich direkt mit dem Heim-WLAN und laden Daten in die Withings-Cloud hoch, ohne das Smartphone zu durchlaufen. Das Telefon wird für die Ersteinrichtung und die Autorisierung von Verbindungen mit Health Connect benötigt. Nach der Einrichtung kannst du dich morgens wiegen und die Daten kommen in der App an, auch wenn das Telefon in einem anderen Zimmer ist.",
        pt: "Sim, a maioria dos dispositivos Withings (incluindo balanças) se conecta diretamente à rede Wi-Fi de casa e faz upload dos dados para a nuvem da Withings sem passar pelo smartphone. O telefone é necessário para a configuração inicial e para autorizar as conexões com o Health Connect. Uma vez configurado, você pode se pesar de manhã e os dados chegam no app mesmo que o telefone esteja em outro cômodo.",
        fr: "Oui, la plupart des appareils Withings (balances incluses) se connectent directement au réseau Wi-Fi domestique et téléchargent les données vers le cloud Withings sans passer par le smartphone. Le téléphone est nécessaire pour la configuration initiale et pour autoriser les connexions avec Health Connect. Une fois configuré, vous pouvez vous peser le matin et les données arrivent dans l'application même si le téléphone est dans une autre pièce.",
      },
    },
    {
      q: {
        it: "Posso vedere i dati Withings su PC o tablet, non solo su smartphone?",
        en: "Can I view Withings data on PC or tablet, not just on smartphone?",
        es: "¿Puedo ver los datos de Withings en PC o tablet, no solo en smartphone?",
        de: "Kann ich Withings-Daten auf PC oder Tablet ansehen, nicht nur auf dem Smartphone?",
        pt: "Posso ver os dados da Withings no PC ou tablet, não apenas no smartphone?",
        fr: "Puis-je consulter les données Withings sur PC ou tablette, pas seulement sur smartphone?",
      },
      a: {
        it: "L'app Health Mate è pensata principalmente per smartphone. Sul sito web withings.com hai una vista base dei dati, ma non una dashboard avanzata. Per vedere peso, sonno e attività in una dashboard web completa su browser, la strada è usare un'app di terze parti che legga i dati da Health Connect o HealthKit (dove Withings li ha già depositati) e li mostri in formato web.",
        en: "The Health Mate app is designed mainly for smartphones. On the withings.com website you have a basic data view, but not an advanced dashboard. To view weight, sleep and activity in a full web dashboard on a browser, the path is to use a third-party app that reads data from Health Connect or HealthKit (where Withings has already deposited them) and displays them in web format.",
        es: "La app Health Mate está pensada principalmente para smartphones. En el sitio web withings.com tienes una vista básica de los datos, pero no un panel avanzado. Para ver peso, sueño y actividad en un panel web completo en el navegador, la opción es usar una app de terceros que lea los datos de Health Connect o HealthKit (donde Withings ya los ha depositado) y los muestre en formato web.",
        de: "Die Health Mate App ist hauptsächlich für Smartphones konzipiert. Auf der Webseite withings.com hast du eine grundlegende Datensicht, aber kein erweitertes Dashboard. Um Gewicht, Schlaf und Aktivität in einem vollständigen Web-Dashboard im Browser zu sehen, ist der Weg, eine Drittanbieter-App zu verwenden, die Daten aus Health Connect oder HealthKit liest (wo Withings sie bereits hinterlegt hat) und sie im Webformat anzeigt.",
        pt: "O app Health Mate é pensado principalmente para smartphones. No site withings.com você tem uma visualização básica dos dados, mas não um painel avançado. Para ver peso, sono e atividade em um painel web completo no navegador, o caminho é usar um app de terceiros que leia os dados do Health Connect ou HealthKit (onde a Withings já os depositou) e os exiba em formato web.",
        fr: "L'application Health Mate est principalement conçue pour les smartphones. Sur le site web withings.com, vous disposez d'une vue basique des données, mais pas d'un tableau de bord avancé. Pour consulter le poids, le sommeil et l'activité dans un tableau de bord web complet sur un navigateur, la solution consiste à utiliser une application tierce qui lit les données de Health Connect ou HealthKit (où Withings les a déjà déposées) et les affiche au format web.",
      },
    },
    {
      q: {
        it: "Withings ScanWatch sincronizza gli allenamenti su Health Connect?",
        en: "Does the Withings ScanWatch sync workouts to Health Connect?",
        es: "¿El Withings ScanWatch sincroniza los entrenamientos en Health Connect?",
        de: "Synchronisiert die Withings ScanWatch Trainings mit Health Connect?",
        pt: "O Withings ScanWatch sincroniza os treinos no Health Connect?",
        fr: "La Withings ScanWatch synchronise-t-elle les séances d'entraînement dans Health Connect?",
      },
      a: {
        it: "Sì, la ScanWatch trasmette passi, calorie, frequenza cardiaca e i dati degli allenamenti registrati (camminata, corsa, nuoto nei modelli compatibili) verso Health Mate, che a sua volta li condivide con Health Connect. Il GPS non è integrato in tutti i modelli: per le attività che richiedono tracciamento GPS, alcune versioni usano il GPS del telefono tramite l'app. I dettagli precisi dipendono dal modello e dalla versione del firmware.",
        en: "Yes, the ScanWatch transmits steps, calories, heart rate and recorded workout data (walking, running, swimming on compatible models) to Health Mate, which then shares them with Health Connect. GPS is not built into all models: for activities requiring GPS tracking, some versions use the phone's GPS via the app. The precise details depend on the model and firmware version.",
        es: "Sí, la ScanWatch transmite pasos, calorías, frecuencia cardíaca y los datos de los entrenamientos registrados (caminar, correr, nadar en los modelos compatibles) a Health Mate, que a su vez los comparte con Health Connect. El GPS no está integrado en todos los modelos: para las actividades que requieren seguimiento GPS, algunas versiones usan el GPS del teléfono a través de la app. Los detalles precisos dependen del modelo y la versión del firmware.",
        de: "Ja, die ScanWatch überträgt Schritte, Kalorien, Herzfrequenz und aufgezeichnete Trainingsdaten (Gehen, Laufen, Schwimmen bei kompatiblen Modellen) an Health Mate, das sie dann mit Health Connect teilt. GPS ist nicht in alle Modelle integriert: Bei Aktivitäten, die GPS-Tracking erfordern, verwenden einige Versionen das GPS des Telefons über die App. Die genauen Details hängen vom Modell und der Firmware-Version ab.",
        pt: "Sim, o ScanWatch transmite passos, calorias, frequência cardíaca e os dados dos treinos registrados (caminhada, corrida, natação nos modelos compatíveis) para o Health Mate, que por sua vez os compartilha com o Health Connect. O GPS não está integrado em todos os modelos: para atividades que exigem rastreamento GPS, algumas versões usam o GPS do telefone pelo app. Os detalhes precisos dependem do modelo e da versão do firmware.",
        fr: "Oui, la ScanWatch transmet les pas, les calories, la fréquence cardiaque et les données des séances enregistrées (marche, course, natation sur les modèles compatibles) à Health Mate, qui les partage ensuite avec Health Connect. Le GPS n'est pas intégré à tous les modèles: pour les activités nécessitant un suivi GPS, certaines versions utilisent le GPS du téléphone via l'application. Les détails précis dépendent du modèle et de la version du firmware.",
      },
    },
    {
      q: {
        it: "I miei dati Withings sono al sicuro? Dove vengono archiviati?",
        en: "Is my Withings data safe? Where is it stored?",
        es: "¿Están seguros mis datos de Withings? ¿Dónde se almacenan?",
        de: "Sind meine Withings-Daten sicher? Wo werden sie gespeichert?",
        pt: "Meus dados da Withings estão seguros? Onde são armazenados?",
        fr: "Mes données Withings sont-elles en sécurité? Où sont-elles stockées?",
      },
      a: {
        it: "Withings è un'azienda francese e i suoi server principali sono in Europa. Come azienda che opera nell'UE è soggetta al GDPR, che ti garantisce il diritto di accedere ai tuoi dati, correggerli, cancellarli e portarli altrove (portabilità). Puoi richiedere l'export completo dei dati dall'app Health Mate o dal sito withings.com. Per i dati che passi verso terze parti (come Health Connect o app di dashboard), le politiche di privacy di quelle app si applicano separatamente: controlla sempre dove finiscono i dati che condividi.",
        en: "Withings is a French company and its main servers are in Europe. As a company operating in the EU it is subject to GDPR, which guarantees you the right to access your data, correct it, delete it and take it elsewhere (portability). You can request a full data export from the Health Mate app or from withings.com. For data you pass to third parties (such as Health Connect or dashboard apps), the privacy policies of those apps apply separately: always check where data you share ends up.",
        es: "Withings es una empresa francesa y sus servidores principales están en Europa. Como empresa que opera en la UE está sujeta al RGPD, que te garantiza el derecho de acceder a tus datos, corregirlos, eliminarlos y llevarlos a otro lugar (portabilidad). Puedes solicitar un export completo de tus datos desde la app Health Mate o desde withings.com. Para los datos que compartes con terceros (como Health Connect o apps de panel), las políticas de privacidad de esas apps se aplican por separado: comprueba siempre adónde van los datos que compartes.",
        de: "Withings ist ein französisches Unternehmen und seine Hauptserver stehen in Europa. Als Unternehmen, das in der EU tätig ist, unterliegt es der DSGVO, die dir das Recht garantiert, auf deine Daten zuzugreifen, sie zu korrigieren, zu löschen und mitzunehmen (Portabilität). Du kannst einen vollständigen Datenexport über die Health Mate App oder von withings.com anfordern. Für Daten, die du an Dritte weitergibst (wie Health Connect oder Dashboard-Apps), gelten die Datenschutzrichtlinien dieser Apps separat: Überprüfe immer, wohin die Daten gelangen, die du teilst.",
        pt: "A Withings é uma empresa francesa e seus servidores principais ficam na Europa. Como empresa que opera na UE, está sujeita ao RGPD, que garante a você o direito de acessar seus dados, corrigi-los, excluí-los e levá-los para outro lugar (portabilidade). Você pode solicitar um export completo dos dados pelo app Health Mate ou pelo site withings.com. Para os dados que você passa para terceiros (como o Health Connect ou apps de painel), as políticas de privacidade desses apps se aplicam separadamente: sempre verifique onde os dados que você compartilha vão parar.",
        fr: "Withings est une entreprise française et ses serveurs principaux sont en Europe. En tant qu'entreprise opérant dans l'UE, elle est soumise au RGPD, qui vous garantit le droit d'accéder à vos données, de les corriger, de les supprimer et de les transférer ailleurs (portabilité). Vous pouvez demander un export complet de vos données depuis l'application Health Mate ou depuis withings.com. Pour les données que vous transmettez à des tiers (comme Health Connect ou des applications de tableau de bord), les politiques de confidentialité de ces applications s'appliquent séparément: vérifiez toujours où finissent les données que vous partagez.",
      },
    },
  ],
  related: [
    "come-funziona-health-connect",
    "sync-them-all",
    "vedere-dati-wearable-browser-pc",
  ],
  brandsMentioned: ["Withings"],
  ldType: "BlogPosting",
};
