// AGGIORNARE ogni estate: verificare waterproofing ratings, prezzi, compatibilità Health Connect
import type { BlogPost } from "../types";

export const post: BlogPost = {
  slug: "smartwatch-estate-2026",
  category: "guides",
  publishedAt: "2026-05-30",
  updatedAt: "2026-05-30",
  readMinutes: 9,
  tldr: {
    it: [
      "Per nuotare serve almeno 5ATM: IP68 non basta per il nuoto continuativo. Sciacqua sempre con acqua dolce dopo il mare.",
      "Il caldo sopra i 35°C riduce l'autonomia del 15-25%: disabilita l'always-on display, passa la frequenza cardiaca a ogni 10 minuti e non caricare al sole.",
      "Health Connect è on-device: i dati si accumulano in locale anche senza internet e si sincronizzano appena torni connesso. Nessun buco nello storico.",
      "Per la salute estiva monitora la frequenza cardiaca a riposo (segnale di disidratazione se sale oltre 10 bpm dalla baseline) e l'HRV mattutino.",
      "Budget estivo: Xiaomi Mi Band 9 Pro (sotto 60 euro, 5ATM, 14 giorni di autonomia) copre il 90% dei casi d'uso in vacanza.",
    ],
    en: [
      "Swimming requires at least 5ATM: IP68 is not enough for continuous swimming. Always rinse with fresh water after the sea.",
      "Heat above 35°C cuts autonomy by 15-25%: disable always-on display, switch heart rate to every 10 minutes and never charge in the sun.",
      "Health Connect is on-device: data accumulates locally even without internet and syncs as soon as you reconnect. No gaps in history.",
      "For summer health, monitor resting heart rate (a dehydration signal if it rises over 10 bpm from baseline) and morning HRV.",
      "Summer budget pick: Xiaomi Mi Band 9 Pro (under 60 euros, 5ATM, 14-day battery) covers 90% of vacation use cases.",
    ],
    es: [
      "Para nadar necesitas al menos 5ATM: IP68 no es suficiente para el nado continuo. Aclara siempre con agua dulce después del mar.",
      "El calor por encima de 35°C reduce la autonomía un 15-25%: desactiva la pantalla siempre encendida, pasa la frecuencia cardíaca a cada 10 minutos y no cargues al sol.",
      "Health Connect funciona en el dispositivo: los datos se acumulan de forma local aunque no tengas internet y se sincronizan en cuanto te reconectas. Sin huecos en el historial.",
      "Para la salud en verano, controla la frecuencia cardíaca en reposo (señal de deshidratación si sube más de 10 bpm respecto a tu línea base) y el HRV matutino.",
      "Opción económica para el verano: Xiaomi Mi Band 9 Pro (menos de 60 euros, 5ATM, 14 días de autonomía) cubre el 90% de los casos de uso en vacaciones.",
    ],
    de: [
      "Zum Schwimmen sind mindestens 5ATM erforderlich: IP68 reicht für kontinuierliches Schwimmen nicht aus. Nach dem Meer immer mit Süßwasser abspülen.",
      "Hitze über 35°C reduziert die Akkulaufzeit um 15-25%: deaktiviere das Always-on-Display, stelle die Herzfrequenz auf alle 10 Minuten um und lade das Gerät nie in der Sonne.",
      "Health Connect läuft auf dem Gerät: Die Daten werden lokal gespeichert, auch ohne Internetverbindung, und synchronisieren sich, sobald du wieder verbunden bist. Keine Lücken im Verlauf.",
      "Für die Gesundheit im Sommer: Ruheherzfrequenz überwachen (Hinweis auf Dehydrierung, wenn sie mehr als 10 bpm über deiner Baseline steigt) und morgendliche HRV-Werte prüfen.",
      "Günstige Sommeroption: Xiaomi Mi Band 9 Pro (unter 60 Euro, 5ATM, 14 Tage Akkulaufzeit) deckt 90% der Urlaubsanwendungsfälle ab.",
    ],
    pt: [
      "Para nadar você precisa de pelo menos 5ATM: IP68 não é suficiente para natação contínua. Sempre enxágue com água doce após o mar.",
      "O calor acima de 35°C reduz a autonomia em 15-25%: desative o always-on display, mude a frequência cardíaca para a cada 10 minutos e nunca carregue ao sol.",
      "O Health Connect funciona no próprio dispositivo: os dados se acumulam localmente mesmo sem internet e sincronizam assim que você se reconecta. Sem lacunas no histórico.",
      "Para a saúde no verão, monitore a frequência cardíaca em repouso (sinal de desidratação se subir mais de 10 bpm acima da sua linha de base) e a HRV matinal.",
      "Opção econômica para o verão: Xiaomi Mi Band 9 Pro (menos de 60 euros, 5ATM, 14 dias de autonomia) cobre 90% dos casos de uso nas férias.",
    ],
    fr: [
      "Pour nager, il faut au moins 5ATM : IP68 ne suffit pas pour la natation continue. Rincez toujours à l'eau douce après la mer.",
      "La chaleur au-dessus de 35°C réduit l'autonomie de 15 à 25% : désactivez l'affichage toujours allumé, passez la fréquence cardiaque à toutes les 10 minutes et ne chargez jamais au soleil.",
      "Health Connect fonctionne sur l'appareil : les données s'accumulent localement même sans internet et se synchronisent dès que vous vous reconnectez. Aucune lacune dans l'historique.",
      "Pour la santé estivale, surveillez la fréquence cardiaque au repos (signe de déshydratation si elle dépasse de 10 bpm votre ligne de base) et la HRV matinale.",
      "Option économique pour l'été : Xiaomi Mi Band 9 Pro (moins de 60 euros, 5ATM, 14 jours d'autonomie) couvre 90% des cas d'usage en vacances.",
    ],
    pl: [
      "Aby pływać, potrzebne są przynajmniej 5ATM: IP68 nie wystarcza dla kontinuowanychgiatan wody. Wyschuj zawsze w słodkiej wodzie po wybrukowaniu.",
      "Wysokie temperatury powyżej 35°C zmniejszają autonomiczną trwałość o 15-25%: dezaktywują wyświetlanie zawsze włączone, zmieniają częstotliwość pomiaru pulsu na co 10 minut i nie ładowanie w słońcu.",
      "Health Connect jest lokalny: dane akumuluje się na urządzeniu nawet bez połączenia z Internetem i synchronizuje się, jak tylko ponownie zostaniesz połączony. Brak wad w historii.",
      "Dla zdrowie wiosenne monitoruj częstotliwość serca podczas spoczynku (sygnał dehidratacji, jeśli przekroczy 10 bpm wartości bazowej) i HRV rano.",
      "Budżet letni: Xiaomi Mi Band 9 Pro (pod 60 euro, 5ATM, 14 dni niezależności) pokrywa 90% przypadków użycia podczas urlopu.",
    ],
    tr: [
      "Yüzme için en az 5ATM gerekli: IP68 yüzme devam etmek için yeterli değildir. Denizden sonra her zaman suyla temizle.",
      "Güçlü sıcaklık seviyeleri (35°C üzerinde) 15-25% kadar önbellek süresini azaltabilir: her zaman açık ekranı devre dışı bırakır, kalp atışını her 10 dakikada bir kontrol eder ve güneş altında şarj etmeyin.",
      "Health Connect KVKK içinde yerel olarak depolanır: veriler internet olmadan da yerel olarak toplanır ve tekrar bağlantılı olduğunda sychronize edilir. Geçmişinizde hiçbir boya yok.",
      "Yaz sağlığı için dinlenme kalp atış hızını izleyin (bazal değerinizin 10 bpm üzerine çıkması dehidrasyon sinyali olabilir) ve sabah HRV'sini takip edin.",
      "Bütçe yazılımı: Xiaomi Mi Band 9 Pro (60 euro altı, 5ATM, 14 gün süresiyle şarj) tatillerde %90'u kaplayan kullanım durumu kapsıyor.",
    ],
  },
  primaryKeyword: {
    it: "smartwatch estate 2026",
    en: "smartwatch summer 2026",
    es: "smartwatch verano 2026",
    de: "Smartwatch Sommer 2026",
    pt: "smartwatch verão 2026",
    fr: "montre connectée été 2026",
    pl: "smartwatch estate 2026",
    tr: "akıllı saat miras 2026",
  },
  secondaryKeywords: {
    it: [
      "smartwatch resistente all'acqua nuoto",
      "smartwatch caldo batteria",
      "sincronizzare dati salute vacanza",
      "smartwatch spiaggia 2026",
      "waterproof smartwatch estate",
    ],
    en: [
      "waterproof smartwatch summer",
      "smartwatch heat battery tips",
      "sync health data on vacation",
      "best smartwatch for beach 2026",
      "smartwatch swimming waterproof",
    ],
    pt: [
      "smartwatch à prova d'água natação",
      "smartwatch calor bateria",
      "sincronizar dados de saúde nas férias",
      "smartwatch praia 2026",
      "smartwatch à prova d'água verão",
    ],
    fr: [
      "montre connectée étanche natation",
      "montre connectée chaleur batterie",
      "synchroniser les données de santé en vacances",
      "montre connectée plage 2026",
      "montre connectée étanche été",
    ],
    pl: [
      "smartwatch odporný na wodę pływanie",
      "smartwatch ciepła bateria",
      "synkronizować dane zdrowia wypadek",
      "smartwatch plaża 2026",
      "wodoodporność smartwatch nieruchomość",
    ],
    tr: [
      "akıllı saat suya dayalı yüzmek için resmen",
      "akıllı saat sıcak bateria",
      "veri ve gerçeklik vakansiyeteki sağlık verilerini eşleştirmek",
      "akıllı saat pişagi 2026",
      "güvenli suya dayanıklı akıllı saat malzeme",
    ],
  },
  metaDescription: {
    it: "Smartwatch in estate 2026: resistenza all'acqua, autonomia sotto il sole, e come non perdere i tuoi dati salute in vacanza. Guida pratica con consigli reali.",
    en: "Smartwatch in summer 2026: water resistance, battery in heat, and how to keep your health data safe on vacation. Practical guide with real-world advice.",
    es: "Smartwatch en verano 2026: resistencia al agua, autonomía bajo el sol y cómo no perder tus datos de salud en vacaciones. Guía práctica con consejos reales.",
    de: "Smartwatch im Sommer 2026: Wasserresistenz, Akkulaufzeit bei Hitze und wie du deine Gesundheitsdaten im Urlaub sicherst. Praktischer Leitfaden mit echten Tipps.",
    pt: "Smartwatch no verão de 2026: resistência à água, autonomia no calor e como não perder seus dados de saúde nas férias. Guia prático com dicas reais.",
    fr: "Montre connectée en été 2026 : résistance à l'eau, autonomie sous la chaleur et comment protéger vos données de santé en vacances. Guide pratique avec des conseils concrets.",
    pl: "Smartwatch w roku 2026: odporność na wodę, autonomyja pod słońcem, a jak nie stracić Twoich danych zdrowia w przerwie roboczej. Praktyczna wskazówki z rzeczywistymi poradami.",
    tr: "Akıllı Saat 2026'da:Evinde: Su dayanıklı, güneş altında enerji bağımsızlığı, ve tatilinizdeki sağlık verilerinizi kaybetmemek. Uygulamalı rehberlik ile gerçek tavsiyeler.",
  },
  hero: {
    kicker: {
      it: "Guida estate",
      en: "Summer guide",
      es: "Guía de verano",
      de: "Sommer-Ratgeber",
      pt: "Guia de verão",
      fr: "Guide été",
      pl: "Przewodnik letni",
      tr: "Eğim Zamanı Kılavuzu",
    },
    title: {
      it: "Smartwatch d'estate 2026: acqua, caldo e dati salute in vacanza",
      en: "Smartwatch in summer 2026: water, heat, and health data on vacation",
      es: "Smartwatch en verano 2026: agua, calor y datos de salud en vacaciones",
      de: "Smartwatch im Sommer 2026: Wasser, Hitze und Gesundheitsdaten im Urlaub",
      pt: "Smartwatch no verão de 2026: água, calor e dados de saúde nas férias",
      fr: "Montre connectée en été 2026 : eau, chaleur et données de santé en vacances",
      pl: "Smartwatch letnie 2026: woda, ciepło i zdrowe dane w przerwie roboczej",
      tr: "Giyilebilir Cihaz 2026 Yaz Akıllı Saati: Su, Sıcaklık ve Sağlık Verileri Pisoлина",
    },
    subtitle: {
      it: "Tra piscina, caldo e wifi assente, l'estate è il periodo più duro per uno smartwatch. Ecco come scegliere bene e non perdere nemmeno un dato.",
      en: "Between the pool, the heat, and absent WiFi, summer is the hardest season for a smartwatch. Here's how to choose well and not lose a single data point.",
      es: "Entre la piscina, el calor y la ausencia de WiFi, el verano es la temporada más exigente para un smartwatch. Aquí te explicamos cómo elegir bien y no perder ni un solo dato.",
      de: "Zwischen Schwimmbad, Hitze und fehlendem WLAN ist der Sommer die härteste Jahreszeit für ein Smartwatch. So wählst du richtig und verlierst keinen einzigen Datenpunkt.",
      pt: "Entre a piscina, o calor e a ausência de WiFi, o verão é a estação mais difícil para um smartwatch. Veja como escolher bem e não perder nenhum dado.",
      fr: "Entre la piscine, la chaleur et l'absence de WiFi, l'été est la saison la plus éprouvante pour une montre connectée. Voici comment bien choisir et ne perdre aucune donnée.",
      pl: "Pod.getOwnPropertyNames is the method to use in JavaScript to get the names of the properties of an object. Otoż letnia pora roku sprawia, że smartwatch ma najtrudniejsze doświadczenie. Oto jak dobrze wybrać i nie przegapić żadnego danych.\nTra pływacką baseniem, brakiem internetu bezprzewodowego i ciepłem, lato to najtrudniejszy okres dla smartwatcha. Oto jak je dobrze wybrac i nie przegapić żadnych danych.",
      tr: "Pisikondan, ısınma ve wifi olmayan bir yaz, akıllı saat için en zor zaman periodasıdır. KVKK uyumluluğunu sağlayacak ve her veriyi kaybetmeyi önleyeceğiniz nasıl bir akıllı saat seçtiğinizi öğrenin.",
    },
  },
  body: [
    {
      type: "paragraph",
      text: {
        it: "L'estate è il periodo più duro per uno smartwatch: piscine, caldo sopra i 35°C e wifi assente in vacanza mettono a rischio sia il dispositivo che la continuità dei tuoi dati. Un rating 5ATM basta per nuotare, Health Connect salva i dati offline in locale, e tre accorgimenti sulla batteria evitano che l'autonomia crolli del 25%. Questa guida risponde a tutto questo in modo diretto.",
        en: "Summer is the hardest season for a smartwatch: pools, heat above 35°C, and absent WiFi on vacation put both the device and your data continuity at risk. A 5ATM rating is enough for swimming, Health Connect saves data locally offline, and three battery habits prevent a 25% autonomy drop. This guide addresses all of this directly.",
        es: "El verano es la temporada más dura para un smartwatch: piscinas, calor por encima de 35°C y WiFi ausente en vacaciones ponen en riesgo tanto el dispositivo como la continuidad de tus datos. Un rating 5ATM es suficiente para nadar, Health Connect guarda los datos de forma local sin conexión, y tres hábitos de batería evitan que la autonomía caiga un 25%. Esta guía responde a todo esto de forma directa.",
        de: "Der Sommer ist die härteste Jahreszeit für ein Smartwatch: Schwimmbäder, Hitze über 35°C und fehlendes WLAN im Urlaub gefährden sowohl das Gerät als auch die Kontinuität deiner Daten. Ein 5ATM-Rating reicht zum Schwimmen aus, Health Connect speichert Daten lokal ohne Internetverbindung, und drei Akku-Gewohnheiten verhindern einen Rückgang der Laufzeit um 25%. Dieser Leitfaden beantwortet all das direkt.",
        pt: "O verão é a estação mais difícil para um smartwatch: piscinas, calor acima de 35°C e WiFi ausente nas férias colocam em risco tanto o dispositivo quanto a continuidade dos seus dados. Uma classificação 5ATM é suficiente para nadar, o Health Connect salva os dados localmente offline, e três hábitos de bateria evitam uma queda de 25% na autonomia. Este guia responde a tudo isso de forma direta.",
        fr: "L'été est la saison la plus difficile pour une montre connectée : piscines, chaleur supérieure à 35°C et WiFi absent en vacances mettent en danger à la fois l'appareil et la continuité de vos données. Une certification 5ATM suffit pour nager, Health Connect sauvegarde les données localement sans connexion, et trois habitudes pour la batterie évitent une chute d'autonomie de 25%. Ce guide répond à tout cela directement.",
        pl: "Latołowy jest najtrudniejszym okresem dla smartwatcha: baseny, gorąco powyżej 35°C i brak wi-fi wczasach zagranicznych mogą zagrozić zarówno urządzeniem, jak i kontynuacją Twoich danych. Rating 5ATM wystarcza do nurty, Health Connect zapisuje dane offline lokalnie, a trzy uwagi dotyczące baterii unikają spadku autonomii o 25%. Ta instrukcja odpowiada na wszystko to prosto.",
        tr: "Güneşçiçek zamanı bir akıllı saat için en zor dönemdir: havuzlar, 35°C üzerindeki sıcaklık ve tatillerde eksik Wi-Fi, cihazınızı ve verilerinizin devam etmesini tehlikeye atar. 5ATM puanı sadece yüzmek için yeterlidir, Health Connect verileri yerel olarak otomatik olarak saklar ve üç akıllı enerji yönetimi ipucu, baterinin dayanımını %25 azaltmadan korur. Bu rehber bu konuları doğrudan cevaplı bir şekilde ele alır.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Resistenza all'acqua: cosa significano davvero IP68, ATM e 5ATM",
        en: "Water resistance: what IP68, ATM, and 5ATM actually mean",
        es: "Resistencia al agua: qué significan realmente IP68, ATM y 5ATM",
        de: "Wasserresistenz: Was IP68, ATM und 5ATM wirklich bedeuten",
        pt: "Resistência à água: o que IP68, ATM e 5ATM realmente significam",
        fr: "Résistance à l'eau : ce que signifient vraiment IP68, ATM et 5ATM",
        pl: "Odporność wodna: o czym naprawdę mówią IP68, ATM i 5ATM",
        tr: "Suçlamaya dayanıklılık: gerçekten ne anlama geliyor IP68, ATM ve 5ATM",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Non tutti i 'waterproof' sono uguali. Ecco la traduzione pratica delle certificazioni che trovi nelle schede tecniche:",
        en: "Not all 'waterproof' ratings are equal. Here's the practical translation of the certifications you'll find in tech specs:",
        es: "No todos los ratings 'waterproof' son iguales. Aquí tienes la traducción práctica de las certificaciones que encontrarás en las fichas técnicas:",
        de: "Nicht alle Wasserschutz-Ratings sind gleich. Hier ist die praktische Übersetzung der Zertifizierungen, die du in den technischen Daten findest:",
        pt: "Nem todas as classificações de resistência à água são iguais. Aqui está a tradução prática das certificações que você encontra nas especificações técnicas:",
        fr: "Toutes les certifications waterproof ne se valent pas. Voici la traduction pratique des certifications que vous trouvez dans les fiches techniques :",
        pl: "Nie wszystkie 'wodoodporne' są równocześnie takie same. Oto praktyczna tłumaczenie oznaczeń, które znajdziesz w specyfikacjach:",
        tr: "Hepsi olmayan 'su resmen' eşit değildir. İşte teknik kayıtlarda bulunan sertifikaların praktik çevirisi:",
      },
    },
    {
      type: "table",
      caption: {
        it: "Certificazioni waterproof smartwatch",
        en: "Smartwatch waterproof certifications",
        es: "Certificaciones waterproof para smartwatch",
        de: "Wasserschutz-Zertifizierungen für Smartwatches",
        pt: "Certificações de resistência à água para smartwatch",
        fr: "Certifications waterproof pour montres connectées",
        pl: "Certificacje防水智能手表",
        tr: "Güvenlik Sertifikaları Giyilebilir Cihaz Akıllı Saat",
      },
      headers: {
        it: ["Rating", "Cosa puoi fare", "Cosa NON puoi fare"],
        en: ["Rating", "What you can do", "What you CANNOT do"],
        es: ["Rating", "Qué puedes hacer", "Qué NO puedes hacer"],
        de: ["Rating", "Was du tun kannst", "Was du NICHT tun kannst"],
        pt: ["Rating", "O que você pode fazer", "O que você NÃO pode fazer"],
        fr: ["Rating", "Ce que vous pouvez faire", "Ce que vous NE POUVEZ PAS faire"],
        pl: [
          "Ocena",
          "Coś, czym możesz się zająć",
          "Czego NIE MOŻESZ ZROBIĆ",
        ],
        tr: [
          "Değerlendirme",
          "Ne yapabilirsiniz",
          "Ne yapAMAYIZ",
        ],
      },
      rows: [
        {
          it: ["IP67", "Pioggia, spruzzi, brevissima immersione (<1m, <30 min)", "Nuoto, doccia prolungata, surf"],
          en: ["IP67", "Rain, splashes, very brief immersion (<1m, <30 min)", "Swimming, prolonged shower, surfing"],
          es: ["IP67", "Lluvia, salpicaduras, inmersión muy breve (<1m, <30 min)", "Natación, ducha prolongada, surf"],
          de: ["IP67", "Regen, Spritzer, sehr kurzes Untertauchen (<1m, <30 Min.)", "Schwimmen, längeres Duschen, Surfen"],
          pt: ["IP67", "Chuva, respingos, imersão muito breve (<1m, <30 min)", "Natação, banho prolongado, surf"],
          fr: ["IP67", "Pluie, éclaboussures, immersion très brève (<1m, <30 min)", "Natation, douche prolongée, surf"],
          pl: [
            "IP67",
            "Deszcz, splendorze, krótka wplątanie (<1m, <30min)",
            "Pływanie, długie prysztrwy, surfer",
          ],
          tr: [
            "IP67",
            "Yaşamış olabilecek yağmur, sularak, çok kısa süreli ıslama (<1m, <30 dk)",
            "Yüzme, uzun ducha, surffing",
          ],
        },
        {
          it: ["IP68", "Immersione fino a 1,5m per 30 min", "Nuoto prolungato, surf, acque mosse"],
          en: ["IP68", "Immersion up to 1.5m for 30 min", "Prolonged swimming, surfing, rough water"],
          es: ["IP68", "Inmersión de hasta 1,5m durante 30 min", "Natación prolongada, surf, aguas agitadas"],
          de: ["IP68", "Untertauchen bis 1,5m für 30 Min.", "Längeres Schwimmen, Surfen, aufgewühltes Wasser"],
          pt: ["IP68", "Imersão até 1,5m por 30 min", "Natação prolongada, surf, águas agitadas"],
          fr: ["IP68", "Immersion jusqu'à 1,5m pendant 30 min", "Natation prolongée, surf, eaux agitées"],
          pl: [
            "IP68",
            "Wygryzanie do głębokości 1,5 m przez 30 minut",
            "Naginata, surfer, wody ruchome",
          ],
          tr: [
            "IP68",
            "Gidreksizlik 1,5 m için 30 dakika",
            "Yenilmez nuot, surff, hareketli sular",
          ],
        },
        {
          it: ["5ATM (≈50m)", "Nuoto in piscina, snorkeling leggero", "Immersioni con bombola, surf ad alta velocità"],
          en: ["5ATM (≈50m)", "Pool swimming, light snorkeling", "Scuba diving, high-speed surfing"],
          es: ["5ATM (≈50m)", "Natación en piscina, snorkel ligero", "Buceo con tanque, surf a alta velocidad"],
          de: ["5ATM (≈50m)", "Schwimmbad, leichtes Schnorcheln", "Gerätetauchen, Surfen mit hoher Geschwindigkeit"],
          pt: ["5ATM (≈50m)", "Natação em piscina, snorkeling leve", "Mergulho com cilindro, surf em alta velocidade"],
          fr: ["5ATM (≈50m)", "Natation en piscine, snorkeling léger", "Plongée sous-marine, surf à grande vitesse"],
          pl: [
            "5ATM (≈50m)",
            "Pływanie w basenie, lekki snokierowanie",
            "Wygrywające długotrwałe treningi, surferzy na wysokich prędkości",
          ],
          tr: [
            "5ATM (≈50m)",
            "Yüzme suyunda, hafif snorkeling",
            "Dugunlar ile dalış, yüksek hızda surferi",
          ],
        },
        {
          it: ["10ATM (≈100m)", "Nuoto, surf, snorkeling avanzato", "Immersioni profonde con bombola"],
          en: ["10ATM (≈100m)", "Swimming, surfing, advanced snorkeling", "Deep scuba diving"],
          es: ["10ATM (≈100m)", "Natación, surf, snorkel avanzado", "Buceo profundo con tanque"],
          de: ["10ATM (≈100m)", "Schwimmen, Surfen, fortgeschrittenes Schnorcheln", "Tiefes Gerätetauchen"],
          pt: ["10ATM (≈100m)", "Natação, surf, snorkeling avançado", "Mergulho profundo com cilindro"],
          fr: ["10ATM (≈100m)", "Natation, surf, snorkeling avancé", "Plongée profonde en scaphandre"],
          pl: [
            "10ATM (≈100m)",
            "Pływanie, surfer, diveding zaawansowane",
            "Profundne immersje z butelką gazów",
          ],
          tr: [
            "10ATM (≈100m)",
            "Yüzme, surffting, ileri seviye akvadiving",
            "Derin dalŻile ile bomba ile",
          ],
        },
        {
          it: ["MIL-STD-810H", "Resistenza agli urti, temperature estreme, sabbia", "Non è una certificazione waterproof in sé"],
          en: ["MIL-STD-810H", "Shock resistance, extreme temps, sand", "Not a waterproof cert by itself"],
          es: ["MIL-STD-810H", "Resistencia a golpes, temperaturas extremas, arena", "No es una certificación waterproof en sí misma"],
          de: ["MIL-STD-810H", "Stoßfestigkeit, extreme Temperaturen, Sand", "Keine eigenständige Wasserschutz-Zertifizierung"],
          pt: ["MIL-STD-810H", "Resistência a impactos, temperaturas extremas, areia", "Não é uma certificação de resistência à água por si só"],
          fr: ["MIL-STD-810H", "Résistance aux chocs, températures extrêmes, sable", "N'est pas une certification waterproof en soi"],
          pl: [
            "MIL-STD-810H",
            "Odpor na uderzenia, ekstremalne temperature, piasek",
            "To nie jest autentyczna zabezpieczenie przed wodą",
          ],
          tr: [
            "MIL-STD-810H",
            "Röktürün dayanıklılığı, aşırı sıcaklıklar, kuru sandallar",
            "Bu bir suya dayanıklı olma sertifikatı değil",
          ],
        },
      ],
    },
    {
      type: "callout",
      variant: "warning",
      title: {
        it: "L'acqua salata è più aggressiva di quella dolce",
        en: "Saltwater is more corrosive than freshwater",
        es: "El agua salada es más agresiva que el agua dulce",
        de: "Salzwasser ist aggressiver als Süßwasser",
        pt: "A água salgada é mais corrosiva do que a água doce",
        fr: "L'eau salée est plus agressive que l'eau douce",
        pl: "Woda solana jest bardziej agresywna od słodkiej __FM_PH_0__ __FM_URL_0__ __FM_HTML_0__ __FM_LINK_0__ __FM_CODE_0__ __FM_FENCE_0__ __FM_BRAND_0__ __FM_TERM_0__ __FM_PH_0__ __FM_URL_0__ __FM_HTML_0__ __FM_LINK_0__ __FM_CODE_0__ __FM_FENCE_0__",
        tr: "Tuzlu su daha agresif olur suyu.",
      },
      body: {
        it: "Se nuoti in mare, sciacqua il watch con acqua dolce dopo ogni immersione, anche se è certificato 5ATM. Il sale corrosivo nel tempo deteriora le guarnizioni e i sensori ottici. La stessa precauzione vale per la crema solare: non applicarla direttamente sotto il watch.",
        en: "If you swim in the sea, rinse the watch with fresh water after every dip, even if it's 5ATM certified. Salt gradually corrodes seals and optical sensors. The same applies to sunscreen: don't apply it directly under the watch.",
        es: "Si nadas en el mar, aclara el reloj con agua dulce después de cada inmersión, aunque esté certificado 5ATM. La sal deteriora con el tiempo las juntas y los sensores ópticos. La misma precaución aplica con el protector solar: no lo apliques directamente bajo el reloj.",
        de: "Wenn du im Meer schwimmst, spüle die Uhr nach jedem Bad mit Süßwasser ab, auch wenn sie 5ATM-zertifiziert ist. Salz korrodiert mit der Zeit Dichtungen und optische Sensoren. Dasselbe gilt für Sonnencreme: Trage sie nicht direkt unter der Uhr auf.",
        pt: "Se você nada no mar, enxágue o relógio com água doce após cada mergulho, mesmo que seja certificado 5ATM. O sal corrói progressivamente as vedações e os sensores ópticos. O mesmo vale para o protetor solar: não o aplique diretamente sob o relógio.",
        fr: "Si vous nagez en mer, rincez la montre à l'eau douce après chaque baignade, même si elle est certifiée 5ATM. Le sel corrode progressivement les joints et les capteurs optiques. La même précaution s'applique à la crème solaire : ne l'appliquez pas directement sous la montre.",
        pl: "Jeżeli schwytasz się w morzu, przysacinij zegarek do słodkiej wody po każdej wypłynięciu, nawet jeśli jest zatwierdzony 5ATM. Solowa kwasowość odbiera się na obudowy i czujniki optyczne w ciągu czasu. Podobna ostrożność należy zachować w sprawie soku słonecznego: nie masz mu bezpośrednio pod zegarek.",
        tr: "Denizde yüzüyorsanız, 5ATM sertifikalı olsa bile her girişten sonra watch'u tatlı suyla durulayın. Tuz zamanla contaları ve optik sensörleri aşındırır. Güneş kremi için de aynı kural geçerlidir: doğrudan watch'un altına sürmeyin.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Batteria e caldo: cosa aspettarsi",
        en: "Battery and heat: what to expect",
        es: "Batería y calor: qué esperar",
        de: "Akku und Hitze: Was zu erwarten ist",
        pt: "Bateria e calor: o que esperar",
        fr: "Batterie et chaleur : à quoi s'attendre",
        pl: "Bateria i ciepło: co się spodziewać",
        tr: "Bateriye ve ısınma: beklemeye değerler",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Le batterie agli ioni di litio lavorano in modo ottimale tra 16°C e 22°C. Sopra i 35°C (temperatura tipica di una giornata estiva con il watch al sole) l'autonomia cala del 15-25% e la degradazione a lungo termine accelera. Non ci sono trucchi magici, ma ci sono abitudini che aiutano:",
        en: "Lithium-ion batteries work optimally between 16°C and 22°C. Above 35°C (typical on a summer day with the watch in the sun) autonomy drops 15-25% and long-term degradation accelerates. There are no magic tricks, but there are habits that help:",
        es: "Las baterías de iones de litio funcionan de forma óptima entre 16°C y 22°C. Por encima de 35°C (temperatura habitual en un día de verano con el reloj al sol) la autonomía baja un 15-25% y la degradación a largo plazo se acelera. No hay trucos mágicos, pero sí hábitos que ayudan:",
        de: "Lithium-Ionen-Akkus arbeiten optimal zwischen 16°C und 22°C. Über 35°C (typisch an einem Sommertag mit der Uhr in der Sonne) sinkt die Akkulaufzeit um 15-25% und die Langzeitdegradation beschleunigt sich. Es gibt keine Wundermittel, aber es gibt Gewohnheiten, die helfen:",
        pt: "As baterias de íons de lítio funcionam de forma ideal entre 16°C e 22°C. Acima de 35°C (temperatura comum em um dia de verão com o relógio ao sol) a autonomia cai 15-25% e a degradação a longo prazo se acelera. Não existem truques mágicos, mas existem hábitos que ajudam:",
        fr: "Les batteries lithium-ion fonctionnent de manière optimale entre 16°C et 22°C. Au-dessus de 35°C (température typique d'une journée d'été avec la montre au soleil) l'autonomie chute de 15-25% et la dégradation à long terme s'accélère. Il n'y a pas de solution miracle, mais il y a des habitudes qui aident :",
        pl: "Baterie naładowane elektrolitamiфункционально оптимально функционируют w temperaturze od 16°C do 22°C. Powyżej 35°C (temperatura typowa dnia letniego z smartwatchem na słońcu) spadek autonomii wynosi 15-25%, a degradacja w długotrwałą perspektywę przyspiesza. Nie ma magicznych trików, ale istnieją zwyczaje, które pomagają:",
        tr: "Le batterileri iyonları litium çalışır en uygun şekilde 16°C ve 22°C arasında. 35°C'den yüksek sıcaklıklarda (yağmurdan korunmamış saat bir yaz gününde tipik sıcaklık) dayanım %15-25 azalır ve uzun vadeli degradasyon hızlanır. Sırlı teknikler yok, ancak bazı alışkanlıklar yardımcı olur:",
      },
    },
    {
      type: "list",
      items: {
        it: [
          "**Non caricare al sole**: metti il watch all'ombra quando lo ricarichi. Caricare a 40°C+ può innescare protezioni termiche che rallentano o bloccano la carica.",
          "**Always-on display off**: in estate l'AOD consuma il 20-30% di batteria in più rispetto a un display che si accende al gesto. Disabilitalo se non ti serve.",
          "**Frequenza HR continua → ridotta**: monitoraggio continuo della frequenza cardiaca consuma più batteria. Se sei in vacanza e non in training, passa a 'ogni 10 minuti' per guadagnare 30-40% di autonomia.",
          "**Brightness ridotta**: schermo al 50% invece del massimo allunga l'autonomia e non fa differenza sotto il sole (il sole è già più luminoso dello schermo).",
          "**GPS solo in allenamento**: il GPS attivo continuamente drena la batteria in 8-12 ore. Attivalo solo quando stai davvero registrando un'attività.",
        ],
        en: [
          "**Don't charge in direct sun**: put the watch in the shade when charging. Charging at 40°C+ can trigger thermal protections that slow or stop charging.",
          "**Always-on display off**: in summer, AOD consumes 20-30% more battery than a gesture-activated display. Disable it if you don't need it.",
          "**Continuous HR → reduced frequency**: continuous heart rate monitoring uses more battery. If you're on vacation and not training, switch to 'every 10 minutes' to gain 30-40% more battery.",
          "**Reduced brightness**: screen at 50% instead of max extends battery and makes no difference in the sun (the sun is already brighter than the screen).",
          "**GPS only during workouts**: active GPS continuously drains battery in 8-12 hours. Enable it only when you're actually recording an activity.",
        ],
        es: [
          "**No cargues al sol**: pon el reloj a la sombra cuando lo cargues. Cargar a 40°C o más puede activar protecciones térmicas que ralentizan o bloquean la carga.",
          "**Pantalla siempre encendida, desactivada**: en verano, la pantalla always-on consume un 20-30% más de batería que una pantalla que se activa con el gesto. Desactívala si no la necesitas.",
          "**Frecuencia cardíaca continua a reducida**: el monitoreo continuo de la frecuencia cardíaca consume más batería. Si estás de vacaciones y no entrenando, pasa a 'cada 10 minutos' para ganar un 30-40% de autonomía.",
          "**Brillo reducido**: la pantalla al 50% en lugar del máximo alarga la autonomía y no hace diferencia bajo el sol (el sol ya es más brillante que la pantalla).",
          "**GPS solo en entrenamientos**: el GPS activo de forma continua agota la batería en 8-12 horas. Actívalo solo cuando estés registrando una actividad.",
        ],
        de: [
          "**Nicht in der Sonne laden**: Lege die Uhr beim Laden in den Schatten. Das Laden bei 40°C+ kann Thermoschutzfunktionen auslösen, die den Ladevorgang verlangsamen oder stoppen.",
          "**Always-on-Display deaktivieren**: Im Sommer verbraucht das AOD 20-30% mehr Akku als ein gestengesteuertes Display. Deaktiviere es, wenn du es nicht brauchst.",
          "**Kontinuierliche Herzfrequenz reduzieren**: Die kontinuierliche Herzfrequenzüberwachung verbraucht mehr Akku. Wenn du im Urlaub und nicht im Training bist, wechsle zu 'alle 10 Minuten', um 30-40% mehr Akkulaufzeit zu gewinnen.",
          "**Helligkeit reduzieren**: Bildschirm auf 50% statt Maximum verlängert die Akkulaufzeit und macht in der Sonne keinen Unterschied (die Sonne ist ohnehin heller als der Bildschirm).",
          "**GPS nur beim Training**: Aktives GPS entleert den Akku kontinuierlich in 8-12 Stunden. Aktiviere es nur, wenn du wirklich eine Aktivität aufzeichnest.",
        ],
        pt: [
          "**Não carregue ao sol**: coloque o relógio na sombra ao carregar. Carregar a 40°C ou mais pode acionar proteções térmicas que desaceleram ou bloqueiam o carregamento.",
          "**Always-on display desativado**: no verão, o AOD consome 20-30% mais bateria do que um display ativado por gesto. Desative-o se não precisar.",
          "**Frequência cardíaca contínua reduzida**: o monitoramento contínuo da frequência cardíaca consome mais bateria. Se você está de férias e não está treinando, mude para 'a cada 10 minutos' para ganhar 30-40% de autonomia.",
          "**Brilho reduzido**: tela a 50% em vez do máximo aumenta a autonomia e não faz diferença ao sol (o sol já é mais brilhante do que a tela).",
          "**GPS apenas durante os treinos**: o GPS ativo continuamente esgota a bateria em 8-12 horas. Ative-o apenas quando estiver realmente registrando uma atividade.",
        ],
        fr: [
          "**Ne chargez pas au soleil**: mettez la montre à l'ombre lors de la charge. Charger à 40°C ou plus peut déclencher des protections thermiques qui ralentissent ou bloquent la charge.",
          "**Désactiver l'affichage toujours allumé**: en été, l'AOD consomme 20-30% de batterie en plus par rapport à un affichage activé par geste. Désactivez-le si vous n'en avez pas besoin.",
          "**Fréquence cardiaque continue réduite**: la surveillance continue de la fréquence cardiaque consomme plus de batterie. Si vous êtes en vacances et non en entraînement, passez à 'toutes les 10 minutes' pour gagner 30-40% d'autonomie.",
          "**Luminosité réduite**: écran à 50% au lieu du maximum prolonge l'autonomie et ne fait aucune différence au soleil (le soleil est déjà plus lumineux que l'écran).",
          "**GPS uniquement pendant les séances**: le GPS actif en continu vide la batterie en 8-12 heures. Activez-le uniquement lorsque vous enregistrez vraiment une activité.",
        ],
        pl: [
          "**Nie ładowanie na słońcu**: umieść smartwatch w cieniu podczas jego ładowania. Ładowanie przy temperaturze 40°C+ może wyzwalić mechanizmy termiczne, które hamują lub zatrzymują ładowanie.",
          "**Zawsze włączona wyświetlenie wyłączona**: podczas pracy AOD zużywa od 20 do 30% więcej baterii w porównaniu do wyświetlenia, które włącza się na gest. Wyłącz ją, jeśli nie jest Ci potrzebna.",
          "**Frequenza HR continua → zmienna**: monitoraggio kontynuowany częstotliwości cuerdorowej zużywa więcej baterii. Jeśli jesteś w przerwie roboczej i nie wykonujesz treningu, przełącz na 'co 10 minut' aby uzyskać zwiększoną o 30-40% autonomiczność.",
          "**Zmniejszona jasność**: ekran działa na poziomie 50% zamiast maksymalnego, co daje większą trwałość akumulatora i nie ma znaczenia pod słońcem (słoneczne światło jest już bardziej jasne niż ekran).",
          "**GPS tylko w trakcie treningu**: aktywne GPS ciągle wyczerpują baterię w okresie 8-12 godzin. Włącz je tylko wtedy, gdy naprawdę rejestrujesz aktywność.",
        ],
        tr: [
          "**Güneş altında yükleme yok**: watch'ı yüklemeden önce karanlıkta koyun. 40°C+'da yükleme, termik koruma mekanizmalarını tetikleyebilir ve yükleme hızını azaltabilir veya durdurabilir.",
          "**Aşırı süren gösterge devre dışı bırakıldı**: ESTATE L'AGD (Always-on Display) %20-30 daha fazla bateri tüketimi ile bir ekranın sadece hareket edildiğinde yanıp söndüğünü karşılaştırırken daha fazla bateri tüketir. Gereksiz olduğunda devre dışı bırakabilirsiniz.",
          "**Frekans HR devam → azınlık**: kalp atış hızının sürekli izlenmesi daha fazla bateri tüketir. İyileştiğin veya egzersiz yapmıyorsunuzsa, 'her 10 dakikada bir' olarak ayarlanabilirsiniz ve 30-40% daha uzun bateri ömrü elde edebilirsiniz.",
          "**Açıklama azaltılarak**: ekranı %50 olarak ayarladığınızda, en yüksek değerden daha uzun süredir şarj gerektirmeden çalışır ve güneş altında bir fark göstermez (güneş zaten ekranın çok daha parlaktır).",
          "**GPS sadece egzersizde kullanılsın**: aktif GPS 8-12 saat içinde pilinizi sürekli olarak tüketecek. Gerçek bir egzersiz kaydını yaparken sadece bunu açın.",
        ],
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Il problema dati in vacanza: come non perdere lo storico",
        en: "The vacation data problem: how not to lose your history",
        es: "El problema de los datos en vacaciones: cómo no perder el historial",
        de: "Das Datenproblem im Urlaub: So verlierst du deinen Verlauf nicht",
        pt: "O problema dos dados nas férias: como não perder seu histórico",
        fr: "Le problème des données en vacances : comment ne pas perdre son historique",
        pl: "Problem z danymi w przerwie roboczej: jak nie stracić historii",
        tr: "Veri ve verilerin tatil sırasında sorunları: nasıl tarihi kaybetmeyecekleriniz?",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Se usi Health Connect, le buone notizie: Health Connect è on-device. I tuoi dati di passi, sonno, frequenza cardiaca vengono scritti localmente anche senza internet. Non perdono nulla finché il telefono funziona. Il problema arriva quando usi un'app di sync cloud che non riesce a inviare i dati: se l'app ha logica di retry limitata, dopo alcuni giorni senza connessione potrebbe saltare dei record.",
        en: "If you use Health Connect, good news: Health Connect is on-device. Your steps, sleep, and heart rate data are written locally even without internet. Nothing is lost as long as your phone works. The problem comes when you use a cloud sync app that can't send data: if the app has limited retry logic, after a few days offline it might skip records.",
        es: "Si usas Health Connect, buenas noticias: Health Connect funciona en el dispositivo. Tus datos de pasos, sueño y frecuencia cardíaca se escriben de forma local aunque no tengas internet. No se pierde nada mientras el teléfono funcione. El problema aparece cuando usas una app de sincronización en la nube que no puede enviar los datos: si la app tiene una lógica de reintento limitada, después de varios días sin conexión podría saltarse registros.",
        de: "Wenn du Health Connect verwendest, gute Nachrichten: Health Connect läuft auf dem Gerät. Deine Schritte, Schlafdaten und Herzfrequenz werden lokal gespeichert, auch ohne Internetverbindung. Solange dein Telefon funktioniert, geht nichts verloren. Das Problem entsteht, wenn du eine Cloud-Sync-App verwendest, die keine Daten senden kann: Hat die App eine begrenzte Wiederholungslogik, könnten nach einigen Tagen ohne Verbindung Datensätze fehlen.",
        pt: "Se você usa o Health Connect, boas notícias: o Health Connect funciona no próprio dispositivo. Seus dados de passos, sono e frequência cardíaca são gravados localmente mesmo sem internet. Nada se perde enquanto o telefone funcionar. O problema surge quando você usa um app de sincronização em nuvem que não consegue enviar os dados: se o app tem lógica de reenvio limitada, após alguns dias sem conexão ele pode pular registros.",
        fr: "Si vous utilisez Health Connect, bonne nouvelle : Health Connect fonctionne sur l'appareil. Vos données de pas, sommeil et fréquence cardiaque sont écrites localement même sans internet. Rien n'est perdu tant que votre téléphone fonctionne. Le problème survient lorsque vous utilisez une application de synchronisation cloud qui ne parvient pas à envoyer les données : si l'application a une logique de réessai limitée, après quelques jours hors ligne, elle pourrait sauter des enregistrements.",
        pl: "Je korzystasz z Health Connect, dobre wiadomości: Health Connect jest on-device. Twoje dane dotyczące kroki, snu i częstotliwości serca są zapisywane lokalnie nawet bez internetu. Nie stracają niczego dopóki telefon działa. Problem pojawia się, gdy używasz aplikacji synchronizacyjnej w chmurze, która nie jest w stanie wysłać danych: jeśli aplikacja ma ograniczoną logikę zwracania się ponownie, po kilku dniach bez połączenia może pominąć niektóre rekordy.",
        tr: "Kullanırken Health Connect, iyi haberler: Health Connect cihazda yerel olarak kurulmuştur. Adımların, uyku senaryolarının ve kalp atış hızınız verileri internet olmadan da yerel olarak kaydedilir. Telefon işleyene kadar hiçbir şey kaybetmez. Sorun, cloud sync uygulamasının verileri gönderme mantığı sınırlı olmasında ortaya çıkar: birkaç gün internet bağlantısı yoksa, bazı kayıtlar atlayabilir.",
      },
    },
    {
      type: "callout",
      variant: "tip",
      title: {
        it: "Connettiti alla rete dell'hotel una volta al giorno",
        en: "Connect to hotel WiFi once a day",
        es: "Conéctate al WiFi del hotel una vez al día",
        de: "Einmal täglich mit dem WLAN des Hotels verbinden",
        pt: "Conecte-se ao WiFi do hotel uma vez por dia",
        fr: "Connectez-vous au WiFi de l'hôtel une fois par jour",
        pl: "Połącz się z siecią hotelową raz na dzień",
        tr: "Günlük olarak otel ağına bağlanın",
      },
      body: {
        it: "Anche 2-3 minuti di connessione ogni sera bastano per sincronizzare la giornata. Se usi FitMesh Sync, il background sync scatta automaticamente appena torna la connettività. Non devi aprire l'app: il sistema riprende dal punto in cui si era interrotto.",
        en: "Even 2-3 minutes of connection each evening is enough to sync the day's data. If you use FitMesh Sync, background sync fires automatically as soon as connectivity returns. You don't have to open the app: the system resumes from where it left off.",
        es: "Con 2-3 minutos de conexión cada noche es suficiente para sincronizar el día. Si usas FitMesh Sync, la sincronización en segundo plano se activa automáticamente en cuanto vuelve la conectividad. No tienes que abrir la app: el sistema retoma desde donde se quedó.",
        de: "Bereits 2-3 Minuten Verbindung jeden Abend reichen aus, um die Tagesdaten zu synchronisieren. Wenn du FitMesh Sync verwendest, startet die Hintergrundsynchronisierung automatisch, sobald die Verbindung zurückkehrt. Du musst die App nicht öffnen: Das System setzt dort fort, wo es unterbrochen wurde.",
        pt: "Mesmo 2-3 minutos de conexão por noite são suficientes para sincronizar os dados do dia. Se você usa o FitMesh Sync, a sincronização em segundo plano é ativada automaticamente assim que a conectividade retorna. Você não precisa abrir o app: o sistema retoma de onde parou.",
        fr: "Même 2-3 minutes de connexion chaque soir suffisent pour synchroniser la journée. Si vous utilisez FitMesh Sync, la synchronisation en arrière-plan se déclenche automatiquement dès que la connectivité revient. Vous n'avez pas à ouvrir l'application : le système reprend là où il s'était arrêté.",
        pl: "Ani 2-3 minuty połączenia touszki każdego wieczoru wystarczą do zsynchronizowania dnia. Jeśli używasz FitMesh Sync, automatyczne synchronizowanie w tle zaczyna działać, jak tylko powróci połączenie. Nie musisz otwierać aplikacji: system kontynuuje od miejsca, gdzie został przerwany.",
        tr: "Herhangi bir günün sonunda 2-3 dakika bağlantının sağlanması yeterli olacaktır verilerin sychronizasyonu için. Eğer FitMesh Sync kullanıyorsanız, bağlantı yeniden sağlanınca arka planda sync otomatik olarak devam eder. Uygulamayı açmaya gerek yok: sistem sonrudan kesilme noktasından devam eder.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Quale wearable per l'estate: profili d'uso",
        en: "Which wearable for summer: use profiles",
        es: "Qué wearable elegir para el verano: perfiles de uso",
        de: "Welches Wearable für den Sommer: Nutzungsprofile",
        pt: "Qual wearable para o verão: perfis de uso",
        fr: "Quel appareil connecté pour l'été : profils d'utilisation",
        pl: "Jak wybrnąć zegarek na letni dzień: profil użycia",
        tr: "Hangi giyilebilir cihaz için yazılım: kullanım öngörüleri",
      },
    },
    {
      type: "list",
      items: {
        it: [
          "**Beach + casual**: Galaxy Watch 7 / Pixel Watch 3: ottimo equilibrio waterproofing (5ATM), design da indossare tutto il giorno, AMOLED visibile al sole, Health Connect nativo.",
          "**Nuoto + triathlon**: Garmin Forerunner 165 / 265: GPS multi-band, 5ATM, metriche specifiche nuoto (vasche, stile), autonomia 11-13 giorni in smartwatch mode.",
          "**Trekking + montagna**: Garmin Instinct 2: MIL-STD-810H, 10ATM, altimetro barometrico, bussola, autonomia fino a 28 giorni.",
          "**Salute passiva + eleganza**: Oura Ring: nessun schermo, impermeabile, rileva sonno e recupero in modo discreto. Perfetto se vuoi dati senza portare un watch in spiaggia.",
          "**Budget estivo**: Xiaomi Mi Band 9 Pro: 5ATM, GPS, SpO2, autonomia 14 giorni, meno di €60. Fa quasi tutto quello che serve per un'estate.",
        ],
        en: [
          "**Beach + casual**: Galaxy Watch 7 / Pixel Watch 3: great waterproofing balance (5ATM), all-day wearable design, AMOLED visible in sun, native Health Connect.",
          "**Swimming + triathlon**: Garmin Forerunner 165 / 265: multi-band GPS, 5ATM, swim-specific metrics (laps, stroke), 11-13 day autonomy in smartwatch mode.",
          "**Trekking + mountains**: Garmin Instinct 2: MIL-STD-810H, 10ATM, barometric altimeter, compass, up to 28 days battery.",
          "**Passive health + elegance**: Oura Ring: no screen, waterproof, tracks sleep and recovery discreetly. Perfect if you want data without wearing a watch at the beach.",
          "**Budget summer pick**: Xiaomi Mi Band 9 Pro: 5ATM, GPS, SpO2, 14-day battery, under €60. Does almost everything you need for a summer.",
        ],
        es: [
          "**Playa + casual**: Galaxy Watch 7 / Pixel Watch 3: excelente equilibrio de waterproofing (5ATM), diseño para llevar todo el día, AMOLED visible al sol, Health Connect nativo.",
          "**Natación + triatlón**: Garmin Forerunner 165 / 265: GPS multibanda, 5ATM, métricas específicas de natación (largos, estilo), autonomía de 11-13 días en modo smartwatch.",
          "**Senderismo + montaña**: Garmin Instinct 2: MIL-STD-810H, 10ATM, altímetro barométrico, brújula, autonomía de hasta 28 días.",
          "**Salud pasiva + elegancia**: Oura Ring: sin pantalla, impermeable, registra el sueño y la recuperación de forma discreta. Perfecto si quieres datos sin llevar un reloj en la playa.",
          "**Opción económica para el verano**: Xiaomi Mi Band 9 Pro: 5ATM, GPS, SpO2, autonomía de 14 días, menos de 60 €. Cubre casi todo lo que necesitas para un verano.",
        ],
        de: [
          "**Strand + Alltag**: Galaxy Watch 7 / Pixel Watch 3: ausgewogener Wasserschutz (5ATM), ganztägig tragbares Design, AMOLED in der Sonne gut ablesbar, natives Health Connect.",
          "**Schwimmen + Triathlon**: Garmin Forerunner 165 / 265: Multi-Band-GPS, 5ATM, schwimmspezifische Metriken (Bahnen, Stil), 11-13 Tage Akkulaufzeit im Smartwatch-Modus.",
          "**Trekking + Berge**: Garmin Instinct 2: MIL-STD-810H, 10ATM, barometrischer Höhenmesser, Kompass, bis zu 28 Tage Akkulaufzeit.",
          "**Passive Gesundheit + Eleganz**: Oura Ring: kein Display, wasserdicht, erfasst Schlaf und Erholung diskret. Perfekt, wenn du Daten willst, ohne am Strand eine Uhr zu tragen.",
          "**Günstige Sommeroption**: Xiaomi Mi Band 9 Pro: 5ATM, GPS, SpO2, 14 Tage Akkulaufzeit, unter 60 €. Deckt fast alles ab, was du für einen Sommer brauchst.",
        ],
        pt: [
          "**Praia + casual**: Galaxy Watch 7 / Pixel Watch 3: ótimo equilíbrio de resistência à água (5ATM), design para usar o dia todo, AMOLED visível ao sol, Health Connect nativo.",
          "**Natação + triatlo**: Garmin Forerunner 165 / 265: GPS multibanda, 5ATM, métricas específicas de natação (voltas, estilo), autonomia de 11-13 dias no modo smartwatch.",
          "**Trilha + montanha**: Garmin Instinct 2: MIL-STD-810H, 10ATM, altímetro barométrico, bússola, autonomia de até 28 dias.",
          "**Saúde passiva + elegância**: Oura Ring: sem tela, à prova d'água, monitora sono e recuperação de forma discreta. Perfeito se você quer dados sem usar um relógio na praia.",
          "**Opção econômica para o verão**: Xiaomi Mi Band 9 Pro: 5ATM, GPS, SpO2, autonomia de 14 dias, menos de €60. Faz quase tudo que você precisa para um verão.",
        ],
        fr: [
          "**Plage + casual**: Galaxy Watch 7 / Pixel Watch 3: excellent équilibre waterproofing (5ATM), design à porter toute la journée, AMOLED lisible au soleil, Health Connect natif.",
          "**Natation + triathlon**: Garmin Forerunner 165 / 265: GPS multi-bande, 5ATM, métriques spécifiques natation (longueurs, nage), autonomie 11-13 jours en mode montre connectée.",
          "**Randonnée + montagne**: Garmin Instinct 2: MIL-STD-810H, 10ATM, altimètre barométrique, boussole, autonomie jusqu'à 28 jours.",
          "**Santé passive + élégance**: Oura Ring: pas d'écran, étanche, suit le sommeil et la récupération discrètement. Parfait si vous voulez des données sans porter une montre à la plage.",
          "**Option économique pour l'été**: Xiaomi Mi Band 9 Pro: 5ATM, GPS, SpO2, autonomie 14 jours, moins de 60 €. Couvre presque tout ce dont vous avez besoin pour un été.",
        ],
        pl: [
          "**Plaża + casual**: Galaxy Watch 7 / Pixel Watch 3: doskonały równowagowy ochrona przed wodą (5ATM), projekt do noszenia przez cały dzień, AMOLED widoczny na słońcu, Health Connect lokalny.",
          "**Pływatek + triathlon**: Garmin Forerunner 165 / 265: GPS wielobandaż, 5ATM, specyficzne dla pływania (poolszczek, style), trwałość akku 11-13 dni w trybie smartwatch.",
          "**Trekking + montagna**: Garmin Instinct 2: MIL-STD-810H, 10ATM, barometriczny altymetraz, kompas, autonomiczność do 28 dni.",
          "**Passywa + elegancja**: Oura Ring: bez ekranu, wodoodporny, dyskretnie śledzi sen i odzyskiwanie energii. Idealny, jeśli chcesz danych bez noszenia smartwatcha na plaży.",
          "**Budżetowa letnia oferta**: Xiaomi Mi Band 9 Pro: 5ATM, GPS, SpO2, autonomia 14 dni, za mniej niż 60 zł. Rozwiązuje prawie wszystko, co potrzebujesz na letni okres.",
        ],
        tr: [
          "**Plaj + non-formale**: Galaxy Watch 7 / Pixel Watch 3: harika suyu koruması (5ATM), gün boyu takılabilir tasarım, güneş altında görünen AMOLED, Health Connect yerel.",
          "**Yüzme + triathlon**: Garmin Forerunner 165 / 265: GPS çoklu bandlı, 5ATM, yüzme spesifik metrikleri (piscineler, şıklık), akıllı saat modunda 11-13 gün süresi arası bağımlılık.",
          "**Yürüyüş + dağcılık**: Garmin Instinct 2: KVKK uyumlu, 10ATM, basınçlı altımlık çelik, kompas, en fazla 28 gün boyunca bağımsız.",
          "**Pasif Selamlaşma + Elegans**: Oura Çarpı: ekran yok, suya dayanıklı, gizli bir şekilde uyku ve rehberlik algılar. Plajda bir watch giymek istemiyorsanız idealdir.",
          "**Yaz bütçesi**: Xiaomi Mi Band 9 Pro: 5ATM, GPS, SpO2, 14 gün bağımsızlık, €60'u geçmez. Bir yaz için gerekenleri yapar hala çok fazlasını yapar.",
        ],
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Cosa tracciare in estate che non tracci d'inverno",
        en: "What to track in summer that you don't in winter",
        es: "Qué registrar en verano que no registras en invierno",
        de: "Was du im Sommer tracken solltest, was du im Winter nicht trackst",
        pt: "O que monitorar no verão que você não monitora no inverno",
        fr: "Ce qu'il faut suivre en été que vous ne suivez pas en hiver",
        pl: "Czego śledzić w latach letnich, co nie śledzi się zimą",
        tr: "Güneşin altında giyilebilir cihazınızda traciren çokça farklı özelliklerinizi izleyebilirsiniz ki, kışa gelince bunları izlemiyorsunuz.",
      },
    },
    {
      type: "list",
      items: {
        it: [
          "**Idratazione + frequenza cardiaca a riposo**: un BPM a riposo più alto del solito (>10 bpm rispetto alla tua baseline) può essere un segnale di disidratazione o eccessivo stress termico.",
          "**SpO2 in quota**: se vai in montagna sopra i 2000m, la saturazione ossigeno è un indicatore utile di adattamento altitudinale.",
          "**Variabilità frequenza cardiaca (HRV)**: in estate l'HRV tende a peggiorare con il caldo. Un buon tracker (Oura, Garmin Fenix, Galaxy Watch 6+) te lo mostra ogni mattina.",
          "**Qualità del sonno senza aria condizionata**: il caldo disturba le fasi di sonno profondo. Avere i dati ti aiuta a capire se conviene investire in un ventilatore, cambiare orario di sonno, o adattare l'allenamento serale.",
        ],
        en: [
          "**Hydration + resting heart rate**: a resting HR higher than usual (>10 bpm above your baseline) can signal dehydration or excessive heat stress.",
          "**SpO2 at altitude**: if you go above 2000m, blood oxygen saturation is a useful indicator of altitude adaptation.",
          "**Heart rate variability (HRV)**: in summer HRV tends to worsen with heat. A good tracker (Oura, Garmin Fenix, Galaxy Watch 6+) shows you every morning.",
          "**Sleep quality without AC**: heat disrupts deep sleep phases. Having the data helps you understand whether to invest in a fan, change sleep time, or adjust evening training.",
        ],
        es: [
          "**Hidratación + frecuencia cardíaca en reposo**: una frecuencia cardíaca en reposo más alta de lo habitual (más de 10 bpm por encima de tu línea base) puede indicar deshidratación o estrés térmico excesivo.",
          "**SpO2 en altitud**: si subes por encima de los 2000m, la saturación de oxígeno en sangre es un indicador útil de adaptación a la altitud.",
          "**Variabilidad de la frecuencia cardíaca (HRV)**: en verano el HRV tiende a empeorar con el calor. Un buen tracker (Oura, Garmin Fenix, Galaxy Watch 6+) te lo muestra cada mañana.",
          "**Calidad del sueño sin aire acondicionado**: el calor altera las fases de sueño profundo. Tener los datos te ayuda a entender si vale la pena invertir en un ventilador, cambiar el horario de sueño o ajustar el entrenamiento nocturno.",
        ],
        de: [
          "**Hydratation + Ruheherzfrequenz**: Eine Ruheherzfrequenz, die höher als üblich ist (mehr als 10 bpm über deiner Baseline), kann ein Hinweis auf Dehydrierung oder übermäßigen Hitzestress sein.",
          "**SpO2 in der Höhe**: Wenn du über 2000m gehst, ist die Blutsauerstoffsättigung ein nützlicher Indikator für die Höhenanpassung.",
          "**Herzfrequenzvariabilität (HRV)**: Im Sommer verschlechtert sich die HRV tendenziell mit der Hitze. Ein gutes Wearable (Oura, Garmin Fenix, Galaxy Watch 6+) zeigt dir das jeden Morgen.",
          "**Schlafqualität ohne Klimaanlage**: Die Hitze stört die Tiefschlafphasen. Die Daten helfen dir zu verstehen, ob es sich lohnt, in einen Ventilator zu investieren, die Schlafenszeit zu ändern oder das Abendtraining anzupassen.",
        ],
        pt: [
          "**Hidratação + frequência cardíaca em repouso**: uma frequência cardíaca em repouso mais alta do que o normal (mais de 10 bpm acima da sua linha de base) pode ser um sinal de desidratação ou estresse térmico excessivo.",
          "**SpO2 em altitude**: se você for acima de 2000m, a saturação de oxigênio no sangue é um indicador útil de adaptação à altitude.",
          "**Variabilidade da frequência cardíaca (HRV)**: no verão, a HRV tende a piorar com o calor. Um bom wearable (Oura, Garmin Fenix, Galaxy Watch 6+) mostra isso para você toda manhã.",
          "**Qualidade do sono sem ar-condicionado**: o calor prejudica as fases de sono profundo. Ter os dados ajuda você a entender se vale a pena investir em um ventilador, mudar o horário de dormir ou ajustar o treino noturno.",
        ],
        fr: [
          "**Hydratation + fréquence cardiaque au repos**: une fréquence cardiaque au repos plus élevée que d'habitude (plus de 10 bpm au-dessus de votre ligne de base) peut signaler une déshydratation ou un stress thermique excessif.",
          "**SpO2 en altitude**: si vous montez au-dessus de 2000m, la saturation en oxygène est un indicateur utile d'adaptation à l'altitude.",
          "**Variabilité de la fréquence cardiaque (HRV)**: en été la HRV tend à se dégrader avec la chaleur. Un bon appareil (Oura, Garmin Fenix, Galaxy Watch 6+) vous l'affiche chaque matin.",
          "**Qualité du sommeil sans climatisation**: la chaleur perturbe les phases de sommeil profond. Avoir les données vous aide à comprendre s'il vaut mieux investir dans un ventilateur, changer les horaires de sommeil ou adapter l'entraînement du soir.",
        ],
        pl: [
          "**Wodna zasatura + częstotliwość serca w spoczynku**: wyższa BPM w spoczynku niż zwykle (>10 bpm w stosunku do Twojej bazowej wartości) może być sygnałem dehidratacji lub nadmiernego ciężaru termicznego.",
          "**SpO2 w granulacji**: jeśli pojeżdżasz na górę powyżej 2000m, satelizacja tlenu jest przydatnym indykatorом adaptywności wysokościowej.",
          "**Variabilità częstotliwości sercowej (HRV):** w lato HRV tenduje do pogorszenia ze wzrostem temperatury. Dobry tracker (Oura, Garmin Fenix, Galaxy Watch 6+) to pokazuje tousko rano.",
          "**Jakość snu bez chłodzenia**: ciepło przeszkadza w osiąganiu głębokich faz senu. Posiadanie tych danych pomaga zrozumieć, czy warto nakupić ventilatora, zmienić porę senną lub dostosować trening popołudniowy.",
        ],
        tr: [
          "**İdratasyon + dinlenme kalp hızı**: daha yüksek bir dinlenme kalp hızı (>10 bpm senin baz lineden fazla) genellikle idrakasyon veya aşırı ısınma stresi bir işareti olabilir.",
          "**SpO2 quota içinde**: da montagne sopra i 2000m, l'ossigenazione del sangue è un indicatore utile dell'adattamento all'altezza.",
          "**Günlük kalp atış hızı değişimi (HRV):** yaz gecesi HRV sıcaklıkta kötüleşir. Bir iyi takipci (Oura, Garmin Fenix, Galaxy Watch 6+) her sabah bunu gösterecektir.",
          "**Uygunluğunuza Uyan Uykunuz için Soğutma Yoksa**: sıcaklık derin uykunun faslarını bozabilir. Verileri biliyor olmak, bir hava koşulayıcısına yatırım yapıp yapmayacağınızı, uyku saatlerinizi değiştirmeyi veya gecenin egzersiz programınızı uyarlamayı anlamaya yardımcı olur.",
        ],
      },
    },
    {
      type: "callout",
      variant: "tip",
      title: {
        it: "Il consiglio che fa la differenza in vacanza",
        en: "The advice that makes the difference on vacation",
        es: "El consejo que marca la diferencia en vacaciones",
        de: "Der Tipp, der im Urlaub den Unterschied macht",
        pt: "O conselho que faz a diferença nas férias",
        fr: "Le conseil qui fait la différence en vacances",
        pl: "Rozporządzanie, które robi różnicę w urlopie",
        tr: "Açıklanan tatil tavsiyesiDifference-making vacation advice",
      },
      body: {
        it: "Non portare il caricabatterie del watch vicino alla spiaggia o lasciarlo in auto al sole: è il modo più rapido per dimezzare la vita della batteria in modo permanente. Carica sempre all'ombra, preferibilmente di notte. È banale ma il 90% delle lamentele su 'batteria peggiorata d'estate' ha questa origine.",
        en: "Don't bring the watch charger near the beach or leave it in a sun-baked car: this is the fastest way to permanently halve battery life. Always charge in the shade, preferably at night. It sounds obvious, but 90% of 'battery got worse in summer' complaints trace back to exactly this.",
        es: "No lleves el cargador del reloj a la playa ni lo dejes en el coche al sol: es la forma más rápida de reducir la vida de la batería de forma permanente. Carga siempre a la sombra, preferiblemente de noche. Puede parecer obvio, pero el 90% de las quejas sobre 'la batería empeoró en verano' tienen este mismo origen.",
        de: "Bringe das Ladegerät der Uhr nicht an den Strand und lass es nicht in einem sonnenbeschienenen Auto: Das ist der schnellste Weg, die Akkulebensdauer dauerhaft zu halbieren. Lade immer im Schatten, vorzugsweise nachts. Es klingt selbstverständlich, aber 90% der Beschwerden über 'schlechtere Akkuleistung im Sommer' haben genau diese Ursache.",
        pt: "Não leve o carregador do relógio perto da praia nem o deixe no carro ao sol: essa é a forma mais rápida de reduzir permanentemente a vida útil da bateria pela metade. Carregue sempre na sombra, de preferência à noite. Pode parecer óbvio, mas 90% das reclamações sobre 'bateria piorou no verão' têm essa origem.",
        fr: "N'apportez pas le chargeur de la montre près de la plage et ne le laissez pas dans une voiture exposée au soleil : c'est le moyen le plus rapide de réduire de moitié la durée de vie de la batterie de façon permanente. Chargez toujours à l'ombre, de préférence la nuit. Cela paraît évident, mais 90% des plaintes sur 'la batterie a empiré en été' trouvent leur origine exactement ici.",
        pl: "Nie przywódz carricabaterii zegarka blisko plaży lub go zostaw w samochodzie na słońcu: jest to najwyrazitszy sposób na zmniejszenie trwałości akumulatorki o pół. Zawsze ładowaj w cieniu, najlepiej nocą. Jest to banalne, ale 90% skarg na 'zgorączkowaną akumulator dnia letniego' ma tę przyczynę.",
        tr: "Giyilebilir cihazın şarj kutusunu plajda veya arabanızda güneş altında tutmamak: bu, şarj sisteminin en hızlı yolu ile yarıya indirmesi için. Her zaman yanık olmaktan uzakta şarj etmek, özellikle gece saatlerinde yapmanızı öneriyoruz. Basit bir ipucu olsa da, yaz aylarında 'şarj durumu kötüleşti' şikayetleri %90'si bu sebepten kaynaklanıyor.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "In sintesi",
        en: "In summary",
        es: "En resumen",
        de: "Zusammenfassung",
        pt: "Em resumo",
        fr: "En résumé",
        pl: "W syntezie",
        tr: "Özetle",
      },
    },
    {
      type: "list",
      items: {
        it: [
          "Per il nuoto serve almeno 5ATM: IP68 non è sufficiente per nuotare in modo continuativo. Sciacqua sempre con acqua dolce dopo il mare.",
          "Il caldo sopra i 35°C riduce l'autonomia del 15-25%: disabilita always-on display, passa da HR continua a ogni 10 minuti, e non caricare al sole.",
          "Health Connect è on-device: i dati si accumulano in locale anche senza internet e si sincronizzano appena torni connesso. Nessun buco nello storico.",
          "Per la salute estiva, monitora BPM a riposo (segnale di disidratazione se sale >10 bpm dalla baseline) e HRV mattutino (cala con il caldo).",
          "Budget estivo imbattibile: Xiaomi Mi Band 9 Pro (sotto €60, 5ATM, 14 giorni di autonomia) copre il 90% dei casi d'uso vacanza.",
        ],
        en: [
          "Swimming requires at least 5ATM: IP68 is not enough for continuous swimming. Always rinse with fresh water after the sea.",
          "Heat above 35°C reduces autonomy by 15-25%: disable always-on display, switch from continuous HR to every 10 minutes, and never charge in the sun.",
          "Health Connect is on-device: data accumulates locally even without internet and syncs as soon as you reconnect. No gaps in history.",
          "For summer health tracking, monitor resting HR (signal of dehydration if it rises >10 bpm from baseline) and morning HRV (drops with heat).",
          "Unbeatable summer budget pick: Xiaomi Mi Band 9 Pro (under €60, 5ATM, 14-day battery) covers 90% of vacation use cases.",
        ],
        es: [
          "Para nadar necesitas al menos 5ATM: IP68 no es suficiente para el nado continuo. Aclara siempre con agua dulce después del mar.",
          "El calor por encima de 35°C reduce la autonomía un 15-25%: desactiva la pantalla siempre encendida, pasa de frecuencia cardíaca continua a cada 10 minutos y no cargues al sol.",
          "Health Connect funciona en el dispositivo: los datos se acumulan de forma local aunque no tengas internet y se sincronizan en cuanto te reconectas. Sin huecos en el historial.",
          "Para el seguimiento de salud en verano, controla la frecuencia cardíaca en reposo (señal de deshidratación si sube más de 10 bpm respecto a tu línea base) y el HRV matutino (baja con el calor).",
          "La mejor opción económica para el verano: Xiaomi Mi Band 9 Pro (menos de 60 €, 5ATM, 14 días de autonomía) cubre el 90% de los casos de uso en vacaciones.",
        ],
        de: [
          "Zum Schwimmen sind mindestens 5ATM erforderlich: IP68 reicht für kontinuierliches Schwimmen nicht aus. Nach dem Meer immer mit Süßwasser abspülen.",
          "Hitze über 35°C reduziert die Akkulaufzeit um 15-25%: deaktiviere das Always-on-Display, wechsle von kontinuierlicher Herzfrequenz zu alle 10 Minuten und lade nie in der Sonne.",
          "Health Connect läuft auf dem Gerät: Daten werden lokal gespeichert, auch ohne Internet, und synchronisieren sich, sobald du wieder verbunden bist. Keine Lücken im Verlauf.",
          "Für die Sommergesundheit: Ruheherzfrequenz überwachen (Hinweis auf Dehydrierung, wenn sie mehr als 10 bpm über die Baseline steigt) und morgendliche HRV prüfen (sinkt bei Hitze).",
          "Unschlagbare günstige Sommeroption: Xiaomi Mi Band 9 Pro (unter 60 €, 5ATM, 14 Tage Akkulaufzeit) deckt 90% der Urlaubsanwendungsfälle ab.",
        ],
        pt: [
          "Para nadar você precisa de pelo menos 5ATM: IP68 não é suficiente para natação contínua. Sempre enxágue com água doce após o mar.",
          "O calor acima de 35°C reduz a autonomia em 15-25%: desative o always-on display, mude de frequência cardíaca contínua para a cada 10 minutos e nunca carregue ao sol.",
          "O Health Connect funciona no dispositivo: os dados se acumulam localmente mesmo sem internet e sincronizam assim que você se reconecta. Sem lacunas no histórico.",
          "Para o acompanhamento da saúde no verão, monitore a frequência cardíaca em repouso (sinal de desidratação se subir mais de 10 bpm acima da linha de base) e a HRV matinal (cai com o calor).",
          "A melhor opção econômica para o verão: Xiaomi Mi Band 9 Pro (menos de €60, 5ATM, 14 dias de autonomia) cobre 90% dos casos de uso nas férias.",
        ],
        fr: [
          "Pour nager, il faut au moins 5ATM : IP68 ne suffit pas pour la natation continue. Rincez toujours à l'eau douce après la mer.",
          "La chaleur au-dessus de 35°C réduit l'autonomie de 15-25% : désactivez l'affichage toujours allumé, passez de la fréquence cardiaque continue à toutes les 10 minutes, et ne chargez jamais au soleil.",
          "Health Connect fonctionne sur l'appareil : les données s'accumulent localement même sans internet et se synchronisent dès que vous vous reconnectez. Aucune lacune dans l'historique.",
          "Pour le suivi de santé estival, surveillez la fréquence cardiaque au repos (signe de déshydratation si elle dépasse de 10 bpm votre ligne de base) et la HRV matinale (diminue avec la chaleur).",
          "Option économique imbattable pour l'été : Xiaomi Mi Band 9 Pro (moins de 60 €, 5ATM, 14 jours d'autonomie) couvre 90% des cas d'usage en vacances.",
        ],
        pl: [
          "Dla pływanie wymagane są przynajmniej 5ATM: IP68 nie jest wystarczający dla kontynuowanego pływania. Wyschuj zawsze wodą słoną po przymknięciu oczu pod wodą.",
          "W temperatury powyżej 35°C spadek autonomii wynosi 15-25%: wyłączana jest funkcja zawsze włączonego wyświetlacza, częstotliwość pomiaru HR zmniejsza się do co 10 minut, a nie wolno ładować na słońcu.",
          "Health Connect jest lokalny: dane akumuluje się na urządzeniu nawet bez połączenia z Internetem i synchronizuje się, jak tylko ponownie zostaniesz połączony. Brak wyciszenia historii.",
          "Dla letniej zdrowotnej ochrony, monitoruj BPM podczas odpoczynku (sygnał dezidratacji, jeśli wzrosie >10 bpm w porównaniu z bazową wartością) i HRV rano (zmaleje ze wzrostem temperatury).",
          "Budżetowa oferta letnia niepodważalna: Xiaomi Mi Band 9 Pro (poniżej 60 €, 5ATM, 14 dni autonomii) pokrywa 90% przypadków użycia wczasowe.",
        ],
        tr: [
          "Günlük yüzmek için en az 5ATM gerekli: IP68 süzgeci devamlı yüzmek için yeterli değildir. Denizden sonra her zaman suyla temizle.",
          "Güçlükler 35°C üzerindeyse, автономия до 15-25% azalır: всегда-он отображение devre dışı bırakılır, HR sürekli her 10 dakikada bir olur ve güneş altında şarj etme yapma.",
          "Health Connect KVKK içinde yerel olarak: veriler internet olmadan da yerel olarak toplanır ve tekrar bağlantılı olduğunda sychronize edilir. Geçmişinizde hiçbir boya yok.",
          "Kışkaza uygun sağlık izlemesi için, dinlenme sırasında BPM'i (disidrasyon belirtisi: sebeze >10 bpm artışından sonra sinyal) ve sabah kalp atış hızını (HRV'ı) takip etmeye devam edin.",
          "Bütçe yazimi muhtemel en iyi seçeneğe: Xiaomi Mi Band 9 Pro (60€ altı, 5ATM, 14 gün dayanıklılık) tatil kullanım durumlarının %90'ını kaplar.",
        ],
      },
    },
    {
      type: "cta",
      title: {
        it: "Tieni i tuoi dati salute al sicuro anche in vacanza",
        en: "Keep your health data safe even on vacation",
        es: "Mantén tus datos de salud seguros también en vacaciones",
        de: "Halte deine Gesundheitsdaten auch im Urlaub sicher",
        pt: "Mantenha seus dados de saúde seguros mesmo nas férias",
        fr: "Gardez vos données de santé en sécurité même en vacances",
        pl: "Zachowaj Twoje dane zdrowotne bezpiecznie nawet wczasami",
        tr: "Bilgi ve sağlık verilerinizi tatillerde de güvenli tutun.",
      },
      body: {
        it: "FitMesh Sync sincronizza automaticamente Galaxy Watch, Garmin, Fitbit, Oura e altri wearable su una dashboard web accessibile da browser. Funziona anche dopo giorni offline: appena torni connesso, riprende dal punto in cui si era fermato.",
        en: "FitMesh Sync automatically syncs Galaxy Watch, Garmin, Fitbit, Oura and other wearables to a browser-accessible web dashboard. Works even after days offline: as soon as connectivity returns, it picks up from where it left off.",
        es: "FitMesh Sync sincroniza automáticamente Galaxy Watch, Garmin, Fitbit, Oura y otros wearables en un panel web accesible desde el navegador. Funciona incluso después de varios días sin conexión: en cuanto vuelves a conectarte, retoma desde donde se quedó.",
        de: "FitMesh Sync synchronisiert automatisch Galaxy Watch, Garmin, Fitbit, Oura und andere Wearables in ein browserzugängliches Web-Dashboard. Funktioniert auch nach Tagen offline: Sobald die Verbindung zurückkommt, setzt es dort fort, wo es aufgehört hat.",
        pt: "FitMesh Sync sincroniza automaticamente Galaxy Watch, Garmin, Fitbit, Oura e outros wearables em um painel web acessível pelo navegador. Funciona mesmo após dias offline: assim que a conectividade retorna, retoma de onde parou.",
        fr: "FitMesh Sync synchronise automatiquement Galaxy Watch, Garmin, Fitbit, Oura et d'autres wearables vers un tableau de bord web accessible depuis le navigateur. Fonctionne même après des jours hors ligne : dès que la connectivité revient, il reprend là où il s'était arrêté.",
        pl: "FitMesh Sync synchronizuje automatycznie Galaxy Watch, Garmin, Fitbit, Oura oraz inne wearable na interfejsie użytkownika internetowym dostępny z przeglądarki. Funkcjonuje również po dniach bezpołątnych: jak tylko ponownie zostaniesz połączony, kontynuuje się od miejsca, w którym się zatrzymało.",
        tr: "FitMesh Sync otomatik olarak Galaxy Watch, Garmin, Fitbit, Oura ve diğer giyilebilir cihazları bir web tabanlı panelde sunar, bu panel tarayıcılar aracılığıyla erişilebilir. Offline günlerden sonra da çalışır: tekrar bağlantılı hale geldiğinde, son durumdan devam eder.",
      },
      ctaLabel: {
        it: "Entra in beta gratis →",
        en: "Join free beta →",
        es: "Únete a la beta gratis →",
        de: "Kostenlos zur Beta →",
        pt: "Entre na beta grátis →",
        fr: "Rejoindre la bêta gratuite →",
        pl: "Wejście do bêta bezpłatnie →",
        tr: "Ücretsiz beta'ya katıl →",
      },
      ctaHref: {
        it: "/it/beta",
        en: "/en/beta",
      },
    },
  ],
  faq: [
    {
      q: {
        it: "Posso nuotare con il Galaxy Watch 7?",
        en: "Can I swim with the Galaxy Watch 7?",
        es: "¿Puedo nadar con el Galaxy Watch 7?",
        de: "Kann ich mit der Galaxy Watch 7 schwimmen?",
        pt: "Posso nadar com o Galaxy Watch 7?",
        fr: "Puis-je nager avec la Galaxy Watch 7 ?",
        pl: "Czy mogę pływać z Galaxy Watch 7?",
        tr: "Giyilebilir cihazım Galaxy Watch 7 ile yüzeyebilirim mı?",
      },
      a: {
        it: "Sì. Galaxy Watch 7 è certificato 5ATM (≈50m) e ha una modalità nuoto integrata che traccia vasche in piscina e nuoto libero. Dopo il nuoto in mare, sciacqualo con acqua dolce.",
        en: "Yes. Galaxy Watch 7 is 5ATM certified (≈50m) and has a built-in swim mode that tracks pool laps and open water. After sea swimming, rinse with fresh water.",
        es: "Sí. Galaxy Watch 7 tiene certificación 5ATM (≈50m) y cuenta con un modo natación integrado que registra largos en piscina y natación en aguas abiertas. Después de nadar en el mar, acláralo con agua dulce.",
        de: "Ja. Die Galaxy Watch 7 ist 5ATM-zertifiziert (≈50m) und hat einen integrierten Schwimmmodus, der Bahnen im Pool und Freiwasserschwimmen aufzeichnet. Nach dem Schwimmen im Meer mit Süßwasser abspülen.",
        pt: "Sim. O Galaxy Watch 7 tem certificação 5ATM (≈50m) e possui um modo de natação integrado que registra voltas na piscina e natação em águas abertas. Após nadar no mar, enxágue com água doce.",
        fr: "Oui. La Galaxy Watch 7 est certifiée 5ATM (≈50m) et dispose d'un mode natation intégré qui suit les longueurs en piscine et la nage en eau libre. Après avoir nagé en mer, rincez-la à l'eau douce.",
        pl: "Tak. Galaxy Watch 7 jest certyfikowany 5ATM (≈50m) i posiada wbudowaną tryb nośności, która śledzi baseny w naddwornie oraz wolny styl nośności. Po nośności w morzu spryskaj go słodką wodą.",
        tr: "Evet. Galaxy Watch 7 KVKK ile uyumlu 5ATM (≈50m) ve plaj suyunun dışına çıkınca izlenen yüzme faaliyetlerini takip eden bir banyo modülü ile sunulmaktadır. Denizde yüzme yapmadan sonra, doygun suyla temizleyin.",
      },
    },
    {
      q: {
        it: "Il caldo può danneggiare permanentemente lo smartwatch?",
        en: "Can heat permanently damage a smartwatch?",
        es: "¿El calor puede dañar permanentemente un smartwatch?",
        de: "Kann Hitze einen Smartwatch dauerhaft beschädigen?",
        pt: "O calor pode danificar permanentemente um smartwatch?",
        fr: "La chaleur peut-elle endommager définitivement une montre connectée ?",
        pl: "Czy ciepło może wzmocnioć trwale uszkodzić smartwatch?",
        tr: "Güçlü sıcaklıklar akıllı saatin kalıcı şekilde zararlı olabilir?",
      },
      a: {
        it: "Temperature sopra i 60°C (es. abitacolo auto al sole) possono danneggiare la batteria in modo permanente e ridurne la capacità. Tenere lo smartwatch in auto al sole d'estate è il modo più rapido per rovinare la batteria. Temperatura operativa sicura: generalmente -20°C a +55°C per la maggior parte dei modelli.",
        en: "Temperatures above 60°C (e.g. car interior in the sun) can permanently damage the battery and reduce its capacity. Leaving a smartwatch in a sun-exposed car in summer is the fastest way to ruin the battery. Safe operating temperature: generally -20°C to +55°C for most models.",
        es: "Las temperaturas por encima de 60°C (por ejemplo, el interior de un coche al sol) pueden dañar la batería de forma permanente y reducir su capacidad. Dejar un smartwatch en el coche al sol en verano es la forma más rápida de estropear la batería. Temperatura operativa segura: generalmente entre -20°C y +55°C para la mayoría de los modelos.",
        de: "Temperaturen über 60°C (z.B. Fahrzeuginnenraum in der Sonne) können den Akku dauerhaft beschädigen und seine Kapazität reduzieren. Einen Smartwatch im Sommer in einem sonnenbeschienenen Auto zu lassen, ist der schnellste Weg, den Akku zu ruinieren. Sichere Betriebstemperatur: generell -20°C bis +55°C für die meisten Modelle.",
        pt: "Temperaturas acima de 60°C (por exemplo, interior de carro ao sol) podem danificar a bateria permanentemente e reduzir sua capacidade. Deixar um smartwatch em um carro exposto ao sol no verão é a forma mais rápida de estragar a bateria. Temperatura de operação segura: geralmente de -20°C a +55°C para a maioria dos modelos.",
        fr: "Des températures supérieures à 60°C (par exemple, l'intérieur d'une voiture au soleil) peuvent endommager la batterie de façon permanente et réduire sa capacité. Laisser une montre connectée dans une voiture exposée au soleil en été est le moyen le plus rapide d'abîmer la batterie. Température de fonctionnement sûre : généralement de -20°C à +55°C pour la plupart des modèles.",
        pl: "Temperatura powyżej 60°C (np. wnętrze samochodu na słońcu) może w sposób trwały uszkodzić baterię i zmniejszyć jej pojemność. Trzymanie smartwatcha w samochodzie pod słońcem w letni dzień to najwygodniejszy sposób na spowodowanie uszkodzenia baterii. Bezpieczna temperatura pracy: zazwyczaj -20°C do +55°C dla większości modeli.",
        tr: "60°C'nin üzerindeki sıcaklıklar (örn. güneş altındaki araç içi) pili kalıcı olarak hasar verebilir ve kapasitesini düşürebilir. Yazın akıllı saati güneş gören bir arabada bırakmak pili mahvetmenin en hızlı yoludur. Güvenli çalışma sıcaklığı: çoğu model için -20°C ile +55°C arasıdır.",
      },
    },
    {
      q: {
        it: "Health Connect funziona senza internet?",
        en: "Does Health Connect work without internet?",
        es: "¿Health Connect funciona sin internet?",
        de: "Funktioniert Health Connect ohne Internet?",
        pt: "O Health Connect funciona sem internet?",
        fr: "Health Connect fonctionne-t-il sans internet ?",
        pl: "Czy Health Connect działa bez internetu?",
        tr: "KVKK içindeki Health Connect internet olmadan nasıl çalışır?",
      },
      a: {
        it: "Sì. Health Connect è completamente on-device: scrive e legge dati in locale sul telefono Android. Internet è necessario solo per sincronizzare quei dati verso un cloud o un'app server-side (come FitMesh Sync). Se sei in vacanza senza connessione, i tuoi dati si accumulano localmente e vengono inviati appena torni online.",
        en: "Yes. Health Connect is completely on-device: it writes and reads data locally on the Android phone. Internet is only needed to sync that data to a cloud or server-side app (like FitMesh Sync). If you're on vacation without connection, your data accumulates locally and is sent as soon as you're online again.",
        es: "Sí. Health Connect funciona completamente en el dispositivo: escribe y lee datos de forma local en el teléfono Android. Internet solo es necesario para sincronizar esos datos con la nube o una app con servidor (como FitMesh Sync). Si estás de vacaciones sin conexión, tus datos se acumulan localmente y se envían en cuanto vuelves a estar online.",
        de: "Ja. Health Connect läuft vollständig auf dem Gerät: Es schreibt und liest Daten lokal auf dem Android-Telefon. Internet wird nur benötigt, um diese Daten mit einer Cloud oder einer serverseitigen App (wie FitMesh Sync) zu synchronisieren. Wenn du im Urlaub ohne Verbindung bist, sammeln sich deine Daten lokal an und werden gesendet, sobald du wieder online bist.",
        pt: "Sim. O Health Connect funciona completamente no dispositivo: ele grava e lê dados localmente no telefone Android. A internet só é necessária para sincronizar esses dados com uma nuvem ou um app com servidor (como o FitMesh Sync). Se você estiver de férias sem conexão, seus dados se acumulam localmente e são enviados assim que você voltar a ficar online.",
        fr: "Oui. Health Connect fonctionne entièrement sur l'appareil : il écrit et lit des données localement sur le téléphone Android. Internet n'est nécessaire que pour synchroniser ces données vers un cloud ou une application côté serveur (comme FitMesh Sync). Si vous êtes en vacances sans connexion, vos données s'accumulent localement et sont envoyées dès que vous revenez en ligne.",
        pl: "Tak. Health Connect jest całkowicie on-device: pisze i czyta dane lokalnie na telefonie Android. Internet jest potrzebny tylko do synchronizacji tych danych w kierunku chmury lub serwerowej aplikacji (jak FitMesh Sync). Jeśli jesteś w urlopie bez połączenia, Twoje dane akumulują się lokalnie i są wysyłane, jak tylko ponownie wrócisz online.",
        tr: "Evet. Health Connect tamamen cihata dayalı: yerel olarak telefon Android üzerinde verileri yazar ve okur. İnternet sadece bu verilerin bulut ya da arka uç uygulama (örneğin FitMesh Sync) yönlendirilmesi için gereklidir. Bağlantısız bir tatilinizdeyseniz, verilerinizi yerel olarak saklar ve çevrimine geri döndüğünüzde göndermeye başlarsınız.",
      },
    },
    {
      q: {
        it: "Quali waterproofing resistono alla crema solare?",
        en: "Which waterproofing ratings handle sunscreen?",
        es: "¿Qué ratings de waterproofing resisten el protector solar?",
        de: "Welche Wasserschutz-Ratings halten Sonnencreme stand?",
        pt: "Quais classificações de resistência à água suportam o protetor solar?",
        fr: "Quelles certifications waterproof résistent à la crème solaire ?",
        pl: "Jaki podwójny warstwy są odpowiadające na krem sunarny?",
        tr: "Hangi pişotlar güneş kremine karşı dayanıklı?",
      },
      a: {
        it: "Nessuna certificazione protegge specificamente dai prodotti chimici della crema solare. La crema può deteriorare le guarnizioni in gomma nel tempo, indipendentemente dal rating. Consiglio pratico: applica la crema, aspetta che sia assorbita, poi indossa il watch. Evita di applicarla mentre il watch è già al polso.",
        en: "No certification specifically protects against sunscreen chemicals. Sunscreen can deteriorate rubber seals over time, regardless of the rating. Practical advice: apply sunscreen, wait for it to absorb, then put on the watch. Avoid applying it while the watch is already on your wrist.",
        es: "Ninguna certificación protege específicamente contra los productos químicos del protector solar. El protector puede deteriorar las juntas de goma con el tiempo, independientemente del rating. Consejo práctico: aplica el protector solar, espera a que se absorba y luego ponte el reloj. Evita aplicarlo mientras el reloj ya está en la muñeca.",
        de: "Keine Zertifizierung schützt speziell vor den Chemikalien der Sonnencreme. Sonnencreme kann Gummidichtungen mit der Zeit verschlechtern, unabhängig vom Rating. Praktischer Tipp: Trage Sonnencreme auf, warte bis sie eingezogen ist, dann lege die Uhr an. Vermeide das Auftragen, während die Uhr bereits am Handgelenk sitzt.",
        pt: "Nenhuma certificação protege especificamente contra os produtos químicos do protetor solar. O protetor pode deteriorar as vedações de borracha com o tempo, independentemente da classificação. Dica prática: aplique o protetor solar, espere ser absorvido e depois coloque o relógio. Evite aplicar enquanto o relógio já está no pulso.",
        fr: "Aucune certification ne protège spécifiquement contre les produits chimiques de la crème solaire. La crème peut détériorer les joints en caoutchouc avec le temps, quel que soit le niveau de certification. Conseil pratique : appliquez la crème solaire, attendez qu'elle soit absorbée, puis mettez la montre. Évitez de l'appliquer pendant que la montre est déjà au poignet.",
        pl: "Brak specjalnej uwagi dotyczącej chronienia przed substancjami chemicznymi z kremu solarnego. Krem może uszkodzić obudowy z gumy o czasie, niezależnie od oceny. Przydatne porady: nakładaj krem, poczekaj aż się wchłonie, a następnie od🔎dziel smartwatch. Unikaj nakładania go podczas gdy smartwatch jest już na nad🚀luku.",
        tr: "Yetki verilmediği bir сертификация, güneş kreminden giyilebilir cihazlara özel koruma sağlamaz. Krem, zaman içinde gummu kablolarını bozabilecektir, rehberlik derecelendirmesine bakılmaksızın. Uygulanan pratik tavsiye: Kremi uygula, kaburması tamamlandığında pisolini tak. Pisolinin zaten cebinde olduğunda kremi uygamayın.",
      },
    },
  ],
  related: [
    "scegliere-smartwatch-dati-2026",
    "guida-sync-wearable-2026",
    "hrv-cose-significato-valori",
  ],
  brandsMentioned: ["Samsung", "Google", "Garmin", "Oura", "Xiaomi", "Fitbit"],
  ldType: "BlogPosting",
};
