import type { BlogPost } from "../types";

export const post: BlogPost = {
  slug: "sync-samsung-health-google-fit",
  category: "guides",
  publishedAt: "2026-05-23",
  updatedAt: "2026-05-23",
  readMinutes: 8,
  tldr: {
    it: [
      "Il sync diretto Samsung Health→Google Fit non esiste più dal 2024: Google ha deprecato Google Fit e spostato l'ecosistema Android su Health Connect.",
      "Il percorso corretto oggi: Samsung Health scrive su Health Connect, le app di destinazione leggono da lì. Funziona per la maggior parte dei dati standard.",
      "Non disponibili via Health Connect: metriche proprietarie Samsung, GPS dettagliato degli allenamenti, dati storici precedenti all'autorizzazione.",
      "Se l'app di destinazione non supporta Health Connect nel 2026, probabilmente non viene mantenuta: valuta di cambiarla.",
      "I dati storici in Samsung Health restano al sicuro nel cloud Samsung. Per portarli altrove usa l'export manuale (CSV/XML).",
    ],
    en: [
      "Direct Samsung Health to Google Fit sync has not existed since 2024: Google deprecated Google Fit and moved the Android ecosystem to Health Connect.",
      "The correct path today: Samsung Health writes to Health Connect, destination apps read from there. Works for most standard data.",
      "Not available via Health Connect: Samsung proprietary metrics, detailed workout GPS, historical data predating authorization.",
      "If the destination app does not support Health Connect in 2026, it is probably not maintained: consider switching.",
      "Historical data in Samsung Health stays safe in Samsung cloud. To port it elsewhere, use manual export (CSV/XML).",
    ],
    es: [
      "La sincronización directa de Samsung Health con Google Fit ya no existe desde 2024: Google deprecó Google Fit y trasladó el ecosistema Android a Health Connect.",
      "El camino correcto hoy: Samsung Health escribe en Health Connect y las apps de destino leen desde ahí. Funciona para la mayoría de los datos estándar.",
      "No disponibles a través de Health Connect: métricas propietarias de Samsung, GPS detallado de los entrenamientos y datos históricos anteriores a la autorización.",
      "Si la app de destino no es compatible con Health Connect en 2026, probablemente no está siendo mantenida: considera cambiarla.",
      "Los datos históricos de Samsung Health están seguros en la nube de Samsung. Para trasladarlos a otro sitio, usa la exportación manual (CSV/XML).",
    ],
    de: [
      "Die direkte Synchronisierung von Samsung Health mit Google Fit gibt es seit 2024 nicht mehr: Google hat Google Fit abgekündigt und das Android-Ökosystem auf Health Connect umgestellt.",
      "Der richtige Weg heute: Samsung Health schreibt in Health Connect, Ziel-Apps lesen von dort. Funktioniert für die meisten Standard-Daten.",
      "Nicht über Health Connect verfügbar: proprietäre Samsung-Metriken, detailliertes GPS der Trainings, historische Daten vor der Autorisierung.",
      "Wenn die Ziel-App Health Connect im Jahr 2026 nicht unterstützt, wird sie wahrscheinlich nicht mehr gepflegt: ziehe einen Wechsel in Betracht.",
      "Historische Daten in Samsung Health bleiben sicher in der Samsung-Cloud. Um sie woanders zu übertragen, nutze den manuellen Export (CSV/XML).",
    ],
    pt: [
      "A sincronização direta do Samsung Health com o Google Fit não existe mais desde 2024: o Google descontinuou o Google Fit e migrou o ecossistema Android para o Health Connect.",
      "O caminho correto hoje: o Samsung Health grava no Health Connect e os apps de destino leem de lá. Funciona para a maioria dos dados padrão.",
      "Não disponíveis via Health Connect: métricas proprietárias da Samsung, GPS detalhado dos treinos, dados históricos anteriores à autorização.",
      "Se o app de destino não suporta Health Connect em 2026, provavelmente não está sendo mantido: considere trocá-lo.",
      "Os dados históricos do Samsung Health ficam seguros na nuvem da Samsung. Para levá-los a outro lugar, use a exportação manual (CSV/XML).",
    ],
    fr: [
      "La synchronisation directe de Samsung Health vers Google Fit n'existe plus depuis 2024: Google a abandonné Google Fit et a migré l'écosystème Android vers Health Connect.",
      "Le bon chemin aujourd'hui: Samsung Health écrit dans Health Connect, les applications de destination lisent depuis là. Fonctionne pour la plupart des données standard.",
      "Non disponibles via Health Connect: métriques propriétaires Samsung, GPS détaillé des séances d'entraînement, données historiques antérieures à l'autorisation.",
      "Si l'application de destination ne prend pas en charge Health Connect en 2026, elle n'est probablement plus maintenue: envisagez d'en changer.",
      "Les données historiques de Samsung Health restent en sécurité dans le cloud Samsung. Pour les transférer ailleurs, utilisez l'export manuel (CSV/XML).",
    ],
  },
  primaryKeyword: {
    it: "sync samsung health google fit",
    en: "sync samsung health google fit",
    es: "sincronizar samsung health google fit",
    de: "samsung health google fit synchronisieren",
    pt: "sincronizar samsung health google fit",
    fr: "synchroniser samsung health google fit",
  },
  secondaryKeywords: {
    it: [
      "sincronizzare samsung health google fit",
      "samsung health google fit 2026",
      "health connect samsung health google",
      "trasferire dati samsung health",
      "samsung health google fit workaround",
    ],
    en: [
      "samsung health google fit sync",
      "health connect samsung health google",
      "transfer samsung health data to google",
      "samsung health google fit 2026",
    ],
    pt: [
      "sincronizar samsung health google fit",
      "samsung health google fit 2026",
      "health connect samsung health google",
      "transferir dados samsung health",
      "samsung health google fit solução",
    ],
    fr: [
      "synchroniser samsung health google fit",
      "samsung health google fit 2026",
      "health connect samsung health google",
      "transférer les données samsung health",
      "samsung health google fit solution",
    ],
  },
  metaDescription: {
    it: "Sync Samsung Health → Google Fit nel 2026: il sync diretto non esiste più, ma c'è un workaround via Health Connect. Spiegazione onesta di cosa funziona, cosa no, e perché.",
    en: "Samsung Health to Google Fit sync in 2026: direct sync no longer exists, but there's a workaround via Health Connect. Honest explanation of what works, what doesn't, and why.",
    es: "Sincronizar Samsung Health con Google Fit en 2026: la sincronización directa ya no existe, pero hay una solución a través de Health Connect. Explicación honesta de qué funciona y qué no.",
    de: "Samsung Health mit Google Fit synchronisieren im Jahr 2026: Die direkte Synchronisierung gibt es nicht mehr, aber es gibt einen Workaround über Health Connect. Ehrliche Erklärung, was funktioniert und was nicht.",
    pt: "Sincronizar Samsung Health com Google Fit em 2026: a sincronização direta não existe mais, mas há uma alternativa via Health Connect. Explicação honesta do que funciona e do que não funciona.",
    fr: "Synchroniser Samsung Health avec Google Fit en 2026: la synchronisation directe n'existe plus, mais il existe une solution via Health Connect. Explication honnête de ce qui fonctionne et de ce qui ne fonctionne pas.",
  },
  hero: {
    kicker: { it: "Guida", en: "Guide", es: "Guía", de: "Anleitung", pt: "Guia", fr: "Guide" },
    title: {
      it: "Sync Samsung Health ↔ Google Fit nel 2026",
      en: "Syncing Samsung Health and Google Fit in 2026: what actually works",
      es: "Sincronizar Samsung Health con Google Fit en 2026: qué funciona realmente",
      de: "Samsung Health und Google Fit synchronisieren im Jahr 2026: was wirklich funktioniert",
      pt: "Sincronizar Samsung Health e Google Fit em 2026: o que realmente funciona",
      fr: "Synchroniser Samsung Health et Google Fit en 2026: ce qui fonctionne vraiment",
    },
    subtitle: {
      it: "Il sync diretto Samsung Health → Google Fit non esiste più. Ecco cosa è successo, il workaround via Health Connect che funziona oggi, e i limiti che devi conoscere.",
      en: "Direct Samsung Health → Google Fit sync no longer exists. Here's what happened, the Health Connect workaround that works today, and the limits you need to know.",
      es: "La sincronización directa de Samsung Health con Google Fit ya no existe. Aquí te explicamos qué pasó, la solución a través de Health Connect que funciona hoy y los límites que debes conocer.",
      de: "Die direkte Synchronisierung von Samsung Health mit Google Fit gibt es nicht mehr. Hier erfährst du, was passiert ist, welcher Workaround über Health Connect heute funktioniert und welche Einschränkungen du kennen musst.",
      pt: "A sincronização direta do Samsung Health com o Google Fit não existe mais. Veja o que aconteceu, qual alternativa via Health Connect funciona hoje e quais são os limites que você precisa conhecer.",
      fr: "La synchronisation directe de Samsung Health vers Google Fit n'existe plus. Voici ce qui s'est passé, la solution via Health Connect qui fonctionne aujourd'hui et les limites à connaître.",
    },
  },
  body: [
    {
      type: "paragraph",
      text: {
        it: "Il sync diretto Samsung Health con Google Fit non esiste più dal 2024: Google ha deprecato Google Fit e spostato l'intero ecosistema Android su Health Connect. Il workaround funzionante oggi è Samsung Health che scrive su Health Connect, con le altre app che leggono da lì. Funziona per la maggior parte dei dati standard, con alcune eccezioni note che spieghiamo in questo articolo.",
        en: "Direct Samsung Health to Google Fit sync has not existed since 2024: Google deprecated Google Fit and moved the entire Android ecosystem to Health Connect. The working workaround today is Samsung Health writing to Health Connect, with other apps reading from there. It works for most standard data, with some known exceptions explained in this article.",
        es: "La sincronización directa de Samsung Health con Google Fit ya no existe desde 2024: Google deprecó Google Fit y trasladó todo el ecosistema Android a Health Connect. La solución que funciona hoy es que Samsung Health escribe en Health Connect y las demás apps leen desde ahí. Funciona para la mayoría de los datos estándar, con algunas excepciones conocidas que explicamos en este artículo.",
        de: "Die direkte Synchronisierung von Samsung Health mit Google Fit gibt es seit 2024 nicht mehr: Google hat Google Fit abgekündigt und das gesamte Android-Ökosystem auf Health Connect umgestellt. Der heute funktionierende Workaround besteht darin, dass Samsung Health in Health Connect schreibt und andere Apps von dort lesen. Es funktioniert für die meisten Standard-Daten, mit einigen bekannten Ausnahmen, die wir in diesem Artikel erläutern.",
        pt: "A sincronização direta do Samsung Health com o Google Fit não existe desde 2024: o Google descontinuou o Google Fit e migrou todo o ecossistema Android para o Health Connect. O workaround que funciona hoje é o Samsung Health gravando no Health Connect, com outros apps lendo de lá. Funciona para a maioria dos dados padrão, com algumas exceções conhecidas que explicamos neste artigo.",
        fr: "La synchronisation directe de Samsung Health vers Google Fit n'existe plus depuis 2024: Google a abandonné Google Fit et a migré l'ensemble de l'écosystème Android vers Health Connect. La solution qui fonctionne aujourd'hui est que Samsung Health écrit dans Health Connect, et les autres applications lisent depuis là. Cela fonctionne pour la plupart des données standard, avec quelques exceptions connues expliquées dans cet article.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "La storia breve: Google Fit è stato deprecato",
        en: "The short story: Google Fit was deprecated",
        es: "El resumen: Google Fit fue deprecado",
        de: "Kurz zusammengefasst: Google Fit wurde abgekündigt",
        pt: "O resumo: o Google Fit foi descontinuado",
        fr: "En bref: Google Fit a été abandonné",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Google Fit esisteva come API di scambio dati salute per Android dal 2014. Nel 2022, Google ha annunciato che avrebbe spostato tutto l'ecosistema su Health Connect, la nuova piattaforma on-device che sostituisce il ruolo che aveva Google Fit come intermediario cloud. L'integrazione diretta Samsung Health ↔ Google Fit è stata dismessa nel corso del 2024, quando Google ha ufficialmente smesso di sviluppare Google Fit come prodotto.",
        en: "Google Fit existed as an Android health data exchange API since 2014. In 2022, Google announced it would move the entire ecosystem to Health Connect, the new on-device platform replacing Google Fit's role as cloud intermediary. The direct Samsung Health ↔ Google Fit integration was discontinued during 2024, when Google officially stopped developing Google Fit as a product.",
        es: "Google Fit existía como API de intercambio de datos de salud para Android desde 2014. En 2022, Google anunció que trasladaría todo el ecosistema a Health Connect, la nueva plataforma en el dispositivo que reemplaza el papel de Google Fit como intermediario en la nube. La integración directa Samsung Health con Google Fit se discontinuó durante 2024, cuando Google dejó oficialmente de desarrollar Google Fit como producto.",
        de: "Google Fit existierte seit 2014 als API für den Austausch von Gesundheitsdaten auf Android. Im Jahr 2022 kündigte Google an, das gesamte Ökosystem auf Health Connect zu verlagern, die neue On-Device-Plattform, die die Rolle von Google Fit als Cloud-Vermittler übernimmt. Die direkte Integration von Samsung Health mit Google Fit wurde im Laufe des Jahres 2024 eingestellt, als Google die Entwicklung von Google Fit als Produkt offiziell beendete.",
        pt: "O Google Fit existia como API de troca de dados de saúde para Android desde 2014. Em 2022, o Google anunciou que migraria todo o ecossistema para o Health Connect, a nova plataforma no dispositivo que substitui o papel do Google Fit como intermediário na nuvem. A integração direta do Samsung Health com o Google Fit foi descontinuada ao longo de 2024, quando o Google parou oficialmente de desenvolver o Google Fit como produto.",
        fr: "Google Fit existait en tant qu'API d'échange de données de santé pour Android depuis 2014. En 2022, Google a annoncé qu'il allait migrer l'ensemble de l'écosystème vers Health Connect, la nouvelle plateforme sur l'appareil qui remplace le rôle de Google Fit en tant qu'intermédiaire cloud. L'intégration directe de Samsung Health avec Google Fit a été abandonnée au cours de 2024, lorsque Google a officiellement cessé de développer Google Fit en tant que produit.",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Google Fit come app esiste ancora sui telefoni (e sul Play Store), ma non riceve aggiornamenti significativi e Google ha dichiarato che il suo futuro è incerto. Non è un prodotto morto ufficialmente, ma non è neanche un prodotto su cui puntare.",
        en: "Google Fit as an app still exists on phones (and the Play Store), but receives no significant updates and Google has stated its future is uncertain. It's not an officially dead product, but it's not one to bet on either.",
        es: "Google Fit como app todavía existe en los teléfonos (y en Google Play), pero no recibe actualizaciones significativas y Google ha reconocido que su futuro es incierto. No es un producto oficialmente muerto, pero tampoco es uno en el que valga la pena confiar.",
        de: "Google Fit als App existiert noch auf Telefonen (und im Google Play Store), erhält aber keine wesentlichen Updates mehr. Google hat erklärt, dass seine Zukunft ungewiss ist. Es ist kein offiziell eingestelltes Produkt, aber auch keines, auf das man setzen sollte.",
        pt: "O Google Fit como app ainda existe nos celulares (e no Google Play), mas não recebe atualizações significativas e o Google declarou que seu futuro é incerto. Não é um produto oficialmente descontinuado, mas também não é um no qual valha a pena apostar.",
        fr: "Google Fit en tant qu'application existe encore sur les téléphones (et sur Google Play), mais ne reçoit plus de mises à jour significatives et Google a déclaré que son avenir est incertain. Ce n'est pas un produit officiellement abandonné, mais ce n'est pas non plus sur lequel miser.",
      },
    },
    {
      type: "callout",
      variant: "info",
      title: {
        it: "Perché Health Connect è la risposta",
        en: "Why Health Connect is the answer",
        es: "Por qué Health Connect es la solución",
        de: "Warum Health Connect die Lösung ist",
        pt: "Por que o Health Connect é a resposta",
        fr: "Pourquoi Health Connect est la réponse",
      },
      body: {
        it: "Health Connect è il sostituto architetturale di Google Fit. Non è un'app con una dashboard, è uno strato di scambio dati on-device. Samsung Health scrive su Health Connect, le altre app (incluso ciò che prima leggeva da Google Fit) leggono da Health Connect. Il risultato finale per i dati è lo stesso, ma il flusso è diverso.",
        en: "Health Connect is the architectural replacement for Google Fit. It's not an app with a dashboard, it's an on-device data exchange layer. Samsung Health writes to Health Connect, other apps (including what previously read from Google Fit) read from Health Connect. The end result for the data is the same, but the flow is different.",
        es: "Health Connect es el reemplazo de Google Fit. No es una app con un panel, sino una capa de intercambio de datos en el dispositivo. Samsung Health escribe en Health Connect y las demás apps (incluidas las que antes leían de Google Fit) leen desde Health Connect. El resultado final para los datos es el mismo, pero el flujo es diferente.",
        de: "Health Connect ist der architektonische Nachfolger von Google Fit. Es ist keine App mit einer Dashboard, sondern eine On-Device-Datenaustausch-Schicht. Samsung Health schreibt in Health Connect, andere Apps (einschließlich solcher, die zuvor von Google Fit gelesen haben) lesen von Health Connect. Das Endergebnis für die Daten ist dasselbe, aber der Datenfluss ist anders.",
        pt: "O Health Connect é o substituto arquitetural do Google Fit. Não é um app com painel, mas uma camada de troca de dados no próprio dispositivo. O Samsung Health grava no Health Connect, outros apps (incluindo os que antes liam do Google Fit) leem do Health Connect. O resultado final para os dados é o mesmo, mas o fluxo é diferente.",
        fr: "Health Connect est le successeur architectural de Google Fit. Ce n'est pas une application avec un tableau de bord, c'est une couche d'échange de données sur l'appareil. Samsung Health écrit dans Health Connect, les autres applications (y compris celles qui lisaient auparavant depuis Google Fit) lisent depuis Health Connect. Le résultat final pour les données est le même, mais le flux est différent.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Il workaround via Health Connect: step pratici",
        en: "The Health Connect workaround: practical steps",
        es: "La solución a través de Health Connect: pasos prácticos",
        de: "Der Workaround über Health Connect: praktische Schritte",
        pt: "A alternativa via Health Connect: passos práticos",
        fr: "La solution via Health Connect: étapes pratiques",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Se la tua esigenza è che i dati di Samsung Health (Galaxy Watch) siano leggibili da un'altra app che prima usava Google Fit, il percorso è questo. Funziona per la maggior parte dei dati, con alcune eccezioni che spieghiamo dopo.",
        en: "If your need is for Samsung Health (Galaxy Watch) data to be readable by another app that previously used Google Fit, here's the path. It works for most data, with some exceptions we explain after.",
        es: "Si necesitas que los datos de Samsung Health (Galaxy Watch) sean accesibles desde otra app que antes usaba Google Fit, este es el camino a seguir. Funciona para la mayoría de los datos, con algunas excepciones que explicamos más adelante.",
        de: "Wenn du möchtest, dass die Daten von Samsung Health (Galaxy Watch) von einer anderen App lesbar sind, die zuvor Google Fit verwendet hat, ist das der richtige Weg. Er funktioniert für die meisten Daten, mit einigen Ausnahmen, die wir weiter unten erläutern.",
        pt: "Se você precisa que os dados do Samsung Health (Galaxy Watch) sejam lidos por outro app que antes usava o Google Fit, este é o caminho. Funciona para a maioria dos dados, com algumas exceções que explicamos mais adiante.",
        fr: "Si vous avez besoin que les données de Samsung Health (Galaxy Watch) soient lisibles par une autre application qui utilisait auparavant Google Fit, voici la marche à suivre. Cela fonctionne pour la plupart des données, avec quelques exceptions expliquées plus loin.",
      },
    },
    {
      type: "list",
      ordered: true,
      items: {
        it: [
          "Verifica che Health Connect sia installato sul tuo telefono Android (su Android 14+ è preinstallato; su Android 12-13 cerca 'Health Connect' sul Play Store).",
          "Apri Samsung Health → tocca il tuo profilo in alto a destra → Impostazioni → Gestione dati.",
          "Trova 'Health Connect' nella lista e tocca per aprire le impostazioni.",
          "Abilita la sincronizzazione con Health Connect e seleziona i tipi di dato che vuoi condividere: passi, frequenza cardiaca, sonno, calorie, allenamenti.",
          "Apri l'app di destinazione (quella che leggeva da Google Fit) e trova nelle sue impostazioni la sezione Health Connect o Sorgente dati.",
          "Autorizza quella app a leggere da Health Connect per i tipi di dato che ti servono.",
          "Verifica che i dati fluiscano: di solito entro 30-60 minuti le app vedono i nuovi dati.",
        ],
        en: [
          "Verify Health Connect is installed on your Android phone (on Android 14+ it's preinstalled; on Android 12-13 search 'Health Connect' on the Play Store).",
          "Open Samsung Health → tap your profile top right → Settings → Data management.",
          "Find 'Health Connect' in the list and tap to open settings.",
          "Enable sync with Health Connect and select the data types you want to share: steps, heart rate, sleep, calories, workouts.",
          "Open the destination app (the one that read from Google Fit) and find the Health Connect or Data Source section in its settings.",
          "Authorize that app to read from Health Connect for the data types you need.",
          "Verify data flows: usually within 30-60 minutes apps see new data.",
        ],
        es: [
          "Comprueba que Health Connect esté instalado en tu teléfono Android (en Android 14 o superior viene preinstalado; en Android 12-13 busca 'Health Connect' en Google Play).",
          "Abre Samsung Health, toca tu perfil en la esquina superior derecha y ve a Ajustes y luego a Gestión de datos.",
          "Busca 'Health Connect' en la lista y tócalo para abrir los ajustes.",
          "Activa la sincronización con Health Connect y selecciona los tipos de datos que quieres compartir: pasos, frecuencia cardíaca, sueño, calorías y entrenamientos.",
          "Abre la app de destino (la que leía de Google Fit) y busca en sus ajustes la sección Health Connect o Fuente de datos.",
          "Autoriza a esa app a leer desde Health Connect para los tipos de datos que necesitas.",
          "Verifica que los datos se transfieran: por lo general, las apps reciben los nuevos datos en un plazo de 30 a 60 minutos.",
        ],
        de: [
          "Prüfe, ob Health Connect auf deinem Android-Telefon installiert ist (auf Android 14+ ist es vorinstalliert; auf Android 12-13 suche 'Health Connect' im Google Play Store).",
          "Öffne Samsung Health, tippe oben rechts auf dein Profil, gehe zu Einstellungen und dann zu Datenverwaltung.",
          "Suche 'Health Connect' in der Liste und tippe darauf, um die Einstellungen zu öffnen.",
          "Aktiviere die Synchronisierung mit Health Connect und wähle die Datentypen aus, die du teilen möchtest: Schritte, Herzfrequenz, Schlaf, Kalorien, Trainings.",
          "Öffne die Ziel-App (diejenige, die von Google Fit gelesen hat) und finde in deren Einstellungen den Bereich Health Connect oder Datenquelle.",
          "Erteile dieser App die Leseberechtigung für Health Connect für die benötigten Datentypen.",
          "Prüfe, ob die Daten fließen: In der Regel sehen Apps die neuen Daten innerhalb von 30 bis 60 Minuten.",
        ],
        pt: [
          "Verifique se o Health Connect está instalado no seu celular Android (no Android 14+ ele vem pré-instalado; no Android 12-13 procure 'Health Connect' no Google Play).",
          "Abra o Samsung Health, toque no seu perfil no canto superior direito, vá em Configurações e depois em Gerenciamento de dados.",
          "Encontre 'Health Connect' na lista e toque para abrir as configurações.",
          "Ative a sincronização com o Health Connect e selecione os tipos de dados que deseja compartilhar: passos, frequência cardíaca, sono, calorias, treinos.",
          "Abra o app de destino (o que lia do Google Fit) e encontre nas configurações a seção Health Connect ou Fonte de dados.",
          "Autorize esse app a ler do Health Connect para os tipos de dados que você precisa.",
          "Verifique se os dados estão fluindo: normalmente em até 30 a 60 minutos os apps enxergam os novos dados.",
        ],
        fr: [
          "Vérifiez que Health Connect est installé sur votre téléphone Android (sur Android 14+, il est préinstallé; sur Android 12-13, recherchez 'Health Connect' sur Google Play).",
          "Ouvrez Samsung Health, appuyez sur votre profil en haut à droite, allez dans Paramètres puis Gestion des données.",
          "Trouvez 'Health Connect' dans la liste et appuyez pour ouvrir les paramètres.",
          "Activez la synchronisation avec Health Connect et sélectionnez les types de données à partager: pas, fréquence cardiaque, sommeil, calories, séances d'entraînement.",
          "Ouvrez l'application de destination (celle qui lisait depuis Google Fit) et trouvez dans ses paramètres la section Health Connect ou Source de données.",
          "Autorisez cette application à lire depuis Health Connect pour les types de données dont vous avez besoin.",
          "Vérifiez que les données circulent: en général, les applications voient les nouvelles données dans les 30 à 60 minutes.",
        ],
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Cosa funziona e cosa no: la mappa onesta",
        en: "What works and what doesn't: the honest map",
        es: "Qué funciona y qué no: el mapa honesto",
        de: "Was funktioniert und was nicht: die ehrliche Übersicht",
        pt: "O que funciona e o que não funciona: o mapa honesto",
        fr: "Ce qui fonctionne et ce qui ne fonctionne pas: la carte honnête",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Via Health Connect, Samsung Health espone la maggior parte dei dati standard. Ci sono però gap specifici da conoscere prima di affidarsi a questa soluzione per usi critici.",
        en: "Via Health Connect, Samsung Health exposes most standard data. However, there are specific gaps to know about before relying on this solution for critical uses.",
        es: "A través de Health Connect, Samsung Health expone la mayoría de los datos estándar. Sin embargo, hay limitaciones específicas que debes conocer antes de depender de esta solución para usos importantes.",
        de: "Über Health Connect stellt Samsung Health die meisten Standard-Daten bereit. Es gibt jedoch spezifische Lücken, die du kennen solltest, bevor du dich für kritische Anwendungen auf diese Lösung verlässt.",
        pt: "Via Health Connect, o Samsung Health expõe a maioria dos dados padrão. No entanto, existem lacunas específicas que você deve conhecer antes de depender dessa solução para usos importantes.",
        fr: "Via Health Connect, Samsung Health expose la plupart des données standard. Cependant, il existe des lacunes spécifiques à connaître avant de s'appuyer sur cette solution pour des usages importants.",
      },
    },
    {
      type: "comparison",
      aTitle: {
        it: "Dati disponibili via HC",
        en: "Data available via HC",
        es: "Datos disponibles a través de HC",
        de: "Verfügbare Daten über HC",
        pt: "Dados disponíveis via HC",
        fr: "Données disponibles via HC",
      },
      aItems: {
        it: [
          "Passi giornalieri e conteggio orario",
          "Frequenza cardiaca (letture continue e riepilogo)",
          "Dati di sonno (durata, fasi principali)",
          "Calorie bruciate",
          "Distanza percorsa",
          "Dati di allenamento base (durata, tipo, calorie)",
          "Peso e composizione corporea (se inseriti in SH)",
          "SpO2 (se misurato)",
        ],
        en: [
          "Daily steps and hourly count",
          "Heart rate (continuous readings and summary)",
          "Sleep data (duration, main phases)",
          "Calories burned",
          "Distance walked/run",
          "Basic workout data (duration, type, calories)",
          "Weight and body composition (if entered in SH)",
          "SpO2 (if measured)",
        ],
        es: [
          "Pasos diarios y recuento por hora",
          "Frecuencia cardíaca (lecturas continuas y resumen)",
          "Datos de sueño (duración y fases principales)",
          "Calorías quemadas",
          "Distancia recorrida",
          "Datos básicos de entrenamiento (duración, tipo y calorías)",
          "Peso y composición corporal (si se han introducido en Samsung Health)",
          "SpO2 (si se ha medido)",
        ],
        de: [
          "Tägliche Schritte und stündliche Zählung",
          "Herzfrequenz (kontinuierliche Messungen und Zusammenfassung)",
          "Schlafdaten (Dauer, Hauptphasen)",
          "Verbrannte Kalorien",
          "Zurückgelegte Distanz",
          "Basis-Trainingsdaten (Dauer, Typ, Kalorien)",
          "Gewicht und Körperzusammensetzung (wenn in Samsung Health eingetragen)",
          "SpO2 (wenn gemessen)",
        ],
        pt: [
          "Passos diários e contagem por hora",
          "Frequência cardíaca (leituras contínuas e resumo)",
          "Dados de sono (duração, fases principais)",
          "Calorias queimadas",
          "Distância percorrida",
          "Dados básicos de treino (duração, tipo, calorias)",
          "Peso e composição corporal (se inseridos no Samsung Health)",
          "SpO2 (se medido)",
        ],
        fr: [
          "Pas quotidiens et comptage horaire",
          "Fréquence cardiaque (lectures continues et résumé)",
          "Données de sommeil (durée, phases principales)",
          "Calories brûlées",
          "Distance parcourue",
          "Données d'entraînement de base (durée, type, calories)",
          "Poids et composition corporelle (si saisis dans Samsung Health)",
          "SpO2 (si mesuré)",
        ],
      },
      bTitle: {
        it: "Dati non disponibili / limitati",
        en: "Unavailable / limited data",
        es: "Datos no disponibles o limitados",
        de: "Nicht verfügbare / eingeschränkte Daten",
        pt: "Dados não disponíveis / limitados",
        fr: "Données non disponibles / limitées",
      },
      bItems: {
        it: [
          "Samsung Score e metriche proprietarie Samsung",
          "Dati GPS completi degli allenamenti (traccia, velocità per km)",
          "Energy score e Recovery metrics di Samsung Health",
          "Fasi di sonno granulari (REM vs profondo vs leggero): esposte solo in forma aggregata",
          "Dati storici precedenti all'autorizzazione HC (non retroattivi)",
          "Body Battery e metriche di stress proprietarie",
        ],
        en: [
          "Samsung Score and Samsung proprietary metrics",
          "Full workout GPS data (track, pace per km)",
          "Samsung Health Energy score and Recovery metrics",
          "Granular sleep phases (REM vs deep vs light): exposed in aggregate form only",
          "Historical data predating HC authorization (not retroactive)",
          "Body Battery and proprietary stress metrics",
        ],
        es: [
          "Samsung Score y métricas propietarias de Samsung",
          "Datos GPS completos de los entrenamientos (recorrido y ritmo por km)",
          "Energy score y métricas de recuperación de Samsung Health",
          "Fases del sueño detalladas (REM, profundo y ligero): solo disponibles de forma agregada",
          "Datos históricos anteriores a la autorización en HC (no retroactivos)",
          "Body Battery y métricas de estrés propietarias",
        ],
        de: [
          "Samsung Score und proprietäre Samsung-Metriken",
          "Vollständige GPS-Trainingsdaten (Strecke, Tempo pro km)",
          "Samsung Health Energy Score und Recovery-Metriken",
          "Granulare Schlafphasen (REM vs. Tiefschlaf vs. Leichtschlaf): nur in aggregierter Form verfügbar",
          "Historische Daten vor der HC-Autorisierung (nicht rückwirkend)",
          "Body Battery und proprietäre Stress-Metriken",
        ],
        pt: [
          "Samsung Score e métricas proprietárias da Samsung",
          "Dados GPS completos dos treinos (percurso, ritmo por km)",
          "Energy Score e métricas de recuperação do Samsung Health",
          "Fases do sono detalhadas (REM vs. profundo vs. leve): disponíveis apenas de forma agregada",
          "Dados históricos anteriores à autorização do HC (não retroativos)",
          "Body Battery e métricas de estresse proprietárias",
        ],
        fr: [
          "Samsung Score et métriques propriétaires Samsung",
          "Données GPS complètes des séances d'entraînement (parcours, allure par km)",
          "Energy Score et métriques de récupération de Samsung Health",
          "Phases de sommeil granulaires (REM vs profond vs léger): disponibles uniquement sous forme agrégée",
          "Données historiques antérieures à l'autorisation HC (non rétroactives)",
          "Body Battery et métriques de stress propriétaires",
        ],
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Se la tua app non supporta Health Connect: alternative",
        en: "If your app doesn't support Health Connect: alternatives",
        es: "Si tu app no es compatible con Health Connect: alternativas",
        de: "Wenn deine App Health Connect nicht unterstützt: Alternativen",
        pt: "Se o seu app não suporta Health Connect: alternativas",
        fr: "Si votre application ne prend pas en charge Health Connect: alternatives",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Non tutte le app che leggevano da Google Fit hanno aggiornato il loro codice per leggere da Health Connect. Alcune app più vecchie o con sviluppo lento sono rimaste ferme al vecchio paradigma. Se ti trovi in questa situazione, hai alcune opzioni.",
        en: "Not all apps that read from Google Fit have updated their code to read from Health Connect. Some older or slow-developing apps have remained on the old paradigm. If you find yourself in this situation, you have some options.",
        es: "No todas las apps que leían de Google Fit han actualizado su código para leer desde Health Connect. Algunas apps más antiguas o con desarrollo lento han seguido con el antiguo sistema. Si te encuentras en esta situación, tienes varias opciones.",
        de: "Nicht alle Apps, die von Google Fit gelesen haben, haben ihren Code aktualisiert, um von Health Connect zu lesen. Einige ältere oder langsam entwickelte Apps sind beim alten Paradigma geblieben. Wenn du dich in dieser Situation befindest, hast du einige Möglichkeiten.",
        pt: "Nem todos os apps que liam do Google Fit atualizaram seu código para ler do Health Connect. Alguns apps mais antigos ou com desenvolvimento lento permaneceram no paradigma antigo. Se você se encontra nessa situação, tem algumas opções.",
        fr: "Toutes les applications qui lisaient depuis Google Fit n'ont pas mis à jour leur code pour lire depuis Health Connect. Certaines applications plus anciennes ou à développement lent sont restées sur l'ancien paradigme. Si vous vous trouvez dans cette situation, vous avez plusieurs options.",
      },
    },
    {
      type: "list",
      items: {
        it: [
          "**Verifica se l'app ha un aggiornamento**: cerca su Play Store → dettaglio app → aggiornamenti recenti. Leggi le note di versione per vedere se menzionano 'Health Connect'.",
          "**Usa un bridge**: alcune app come FitMesh Sync leggono da Health Connect e possono esportare i dati in formati o verso piattaforme che ancora usano il vecchio sistema.",
          "**Export manuale**: Samsung Health permette di esportare i dati in CSV o XML. Utile per import una tantum ma non per sincronizzazione continua.",
          "**Considera di cambiare app**: se l'app di destinazione non supporta ancora Health Connect nel 2026, è un segnale che non viene mantenuta attivamente. Esistono alternative più aggiornate.",
        ],
        en: [
          "**Check if the app has an update**: look on Play Store → app detail → recent updates. Read version notes to see if they mention 'Health Connect'.",
          "**Use a bridge**: some apps like FitMesh Sync read from Health Connect and can export data in formats or to platforms that still use the old system.",
          "**Manual export**: Samsung Health allows exporting data in CSV or XML. Useful for one-time imports but not for continuous sync.",
          "**Consider switching apps**: if the destination app doesn't support Health Connect by 2026, it's a sign it's not actively maintained. More updated alternatives exist.",
        ],
        es: [
          "**Comprueba si la app tiene una actualización**: busca en Google Play, entra al detalle de la app y revisa las actualizaciones recientes. Lee las notas de versión para ver si mencionan 'Health Connect'.",
          "**Usa una app puente**: algunas apps como FitMesh Sync leen desde Health Connect y pueden exportar los datos en formatos o hacia plataformas que aún usan el sistema anterior.",
          "**Exportación manual**: Samsung Health permite exportar los datos en CSV o XML. Es útil para importaciones puntuales, pero no para una sincronización continua.",
          "**Considera cambiar de app**: si la app de destino todavía no es compatible con Health Connect en 2026, es una señal de que no está siendo mantenida activamente. Existen alternativas más actualizadas.",
        ],
        de: [
          "**Prüfe, ob die App ein Update hat**: Suche im Google Play Store, öffne die App-Details und schau unter aktuelle Updates. Lies die Versionshinweise, um zu sehen, ob 'Health Connect' erwähnt wird.",
          "**Verwende einen Bridge-Dienst**: Einige Apps wie FitMesh Sync lesen von Health Connect und können Daten in Formate oder zu Plattformen exportieren, die noch das alte System verwenden.",
          "**Manueller Export**: Samsung Health ermöglicht den Export von Daten im CSV- oder XML-Format. Nützlich für einmalige Importe, aber nicht für eine kontinuierliche Synchronisierung.",
          "**Ziehe einen App-Wechsel in Betracht**: Wenn die Ziel-App Health Connect bis 2026 nicht unterstützt, ist das ein Zeichen dafür, dass sie nicht aktiv gepflegt wird. Es gibt aktuellere Alternativen.",
        ],
        pt: [
          "**Verifique se o app tem uma atualização**: procure no Google Play, abra os detalhes do app e veja as atualizações recentes. Leia as notas de versão para ver se mencionam 'Health Connect'.",
          "**Use um app ponte**: alguns apps como o FitMesh Sync leem do Health Connect e podem exportar dados em formatos ou para plataformas que ainda usam o sistema antigo.",
          "**Exportação manual**: o Samsung Health permite exportar dados em CSV ou XML. Útil para importações únicas, mas não para sincronização contínua.",
          "**Considere trocar de app**: se o app de destino ainda não suporta Health Connect em 2026, é um sinal de que não está sendo mantido ativamente. Existem alternativas mais atualizadas.",
        ],
        fr: [
          "**Vérifiez si l'application a une mise à jour**: cherchez sur Google Play, ouvrez le détail de l'application et regardez les mises à jour récentes. Lisez les notes de version pour voir si elles mentionnent 'Health Connect'.",
          "**Utilisez une application relais**: certaines applications comme FitMesh Sync lisent depuis Health Connect et peuvent exporter des données dans des formats ou vers des plateformes qui utilisent encore l'ancien système.",
          "**Export manuel**: Samsung Health permet d'exporter les données en CSV ou XML. Utile pour des imports ponctuels, mais pas pour une synchronisation continue.",
          "**Envisagez de changer d'application**: si l'application de destination ne prend toujours pas en charge Health Connect en 2026, c'est un signe qu'elle n'est pas activement maintenue. Des alternatives plus récentes existent.",
        ],
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "Troubleshooting: i problemi più comuni",
        en: "Troubleshooting: the most common problems",
        es: "Solución de problemas: los errores más frecuentes",
        de: "Fehlerbehebung: die häufigsten Probleme",
        pt: "Solução de problemas: os erros mais comuns",
        fr: "Résolution de problèmes: les problèmes les plus courants",
      },
    },
    {
      type: "paragraph",
      text: {
        it: "Ecco i problemi che emergono più frequentemente e le relative soluzioni.",
        en: "Here are the most frequently encountered problems and their solutions.",
        es: "Estos son los problemas que aparecen con más frecuencia y cómo resolverlos.",
        de: "Hier sind die am häufigsten auftretenden Probleme und ihre Lösungen.",
        pt: "Aqui estão os problemas que surgem com mais frequência e suas soluções.",
        fr: "Voici les problèmes les plus fréquemment rencontrés et leurs solutions.",
      },
    },
    {
      type: "list",
      items: {
        it: [
          "**Samsung Health non appare in Health Connect**: apri Samsung Health → Impostazioni → Gestione dati → Health Connect → attiva la sincronizzazione. Se ancora non appare, aggiorna Samsung Health a l'ultima versione.",
          "**I passi ci sono ma le attività no**: Samsung Health espone i passi automaticamente, ma le sessioni di allenamento richiedono autorizzazioni separate. In Health Connect → Autorizzazioni app → Samsung Health, verifica che 'Allenamento' sia abilitato in scrittura.",
          "**I dati appaiono in ritardo**: il sync tra Samsung Health e Health Connect non è in tempo reale. Avviene periodicamente, di solito ogni 30-60 minuti. Puoi accelerarlo aprendo manualmente Samsung Health.",
          "**I dati storici mancano**: Health Connect non sincronizza retroattivamente. Le attività di prima dell'autorizzazione non appariranno. Usa l'export manuale di Samsung Health per recuperare lo storico.",
          "**App di destinazione non vede niente**: verifica che l'app abbia il permesso di LETTURA su Health Connect. Non basta che Samsung Health abbia il permesso di scrittura.",
        ],
        en: [
          "**Samsung Health doesn't appear in Health Connect**: open Samsung Health → Settings → Data management → Health Connect → enable sync. If it still doesn't appear, update Samsung Health to the latest version.",
          "**Steps are there but activities aren't**: Samsung Health exposes steps automatically, but workout sessions require separate permissions. In Health Connect → App permissions → Samsung Health, verify 'Exercise' is enabled for writing.",
          "**Data appears delayed**: sync between Samsung Health and Health Connect isn't real-time. It happens periodically, usually every 30-60 minutes. You can speed it up by manually opening Samsung Health.",
          "**Historical data is missing**: Health Connect doesn't sync retroactively. Activities before authorization won't appear. Use Samsung Health manual export to recover historical data.",
          "**Destination app sees nothing**: verify the app has READ permission on Health Connect. Samsung Health having write permission isn't enough.",
        ],
        es: [
          "**Samsung Health no aparece en Health Connect**: abre Samsung Health, ve a Ajustes, luego a Gestión de datos y después a Health Connect, y activa la sincronización. Si sigue sin aparecer, actualiza Samsung Health a la última versión.",
          "**Los pasos aparecen pero las actividades no**: Samsung Health expone los pasos de forma automática, pero las sesiones de entrenamiento requieren permisos adicionales. En Health Connect, ve a Permisos de apps, selecciona Samsung Health y verifica que 'Entrenamiento' esté habilitado para escritura.",
          "**Los datos llegan con retraso**: la sincronización entre Samsung Health y Health Connect no es en tiempo real. Se produce de forma periódica, normalmente cada 30 a 60 minutos. Puedes acelerarla abriendo Samsung Health manualmente.",
          "**Faltan los datos históricos**: Health Connect no sincroniza de forma retroactiva. Las actividades anteriores a la autorización no aparecerán. Usa la exportación manual de Samsung Health para recuperar el historial.",
          "**La app de destino no ve nada**: verifica que la app tenga permiso de LECTURA en Health Connect. No es suficiente con que Samsung Health tenga permiso de escritura.",
        ],
        de: [
          "**Samsung Health erscheint nicht in Health Connect**: Öffne Samsung Health, gehe zu Einstellungen, dann Datenverwaltung, dann Health Connect und aktiviere die Synchronisierung. Wenn es immer noch nicht erscheint, aktualisiere Samsung Health auf die neueste Version.",
          "**Schritte sind vorhanden, aber Aktivitäten nicht**: Samsung Health gibt Schritte automatisch weiter, aber Trainingseinheiten erfordern separate Berechtigungen. In Health Connect unter App-Berechtigungen für Samsung Health: prüfe, ob 'Training' für die Schreibberechtigung aktiviert ist.",
          "**Daten erscheinen verzögert**: Die Synchronisierung zwischen Samsung Health und Health Connect erfolgt nicht in Echtzeit. Sie findet regelmäßig statt, normalerweise alle 30 bis 60 Minuten. Du kannst sie beschleunigen, indem du Samsung Health manuell öffnest.",
          "**Historische Daten fehlen**: Health Connect synchronisiert nicht rückwirkend. Aktivitäten vor der Autorisierung werden nicht angezeigt. Verwende den manuellen Export von Samsung Health, um historische Daten abzurufen.",
          "**Ziel-App sieht nichts**: Prüfe, ob die App eine LESE-Berechtigung für Health Connect hat. Es reicht nicht aus, dass Samsung Health eine Schreibberechtigung hat.",
        ],
        pt: [
          "**Samsung Health não aparece no Health Connect**: abra o Samsung Health, vá em Configurações, depois em Gerenciamento de dados, depois em Health Connect e ative a sincronização. Se ainda não aparecer, atualize o Samsung Health para a última versão.",
          "**Os passos aparecem mas as atividades não**: o Samsung Health expõe os passos automaticamente, mas as sessões de treino exigem permissões separadas. No Health Connect, em Permissões de apps, no Samsung Health, verifique se 'Exercício' está habilitado para escrita.",
          "**Os dados aparecem com atraso**: a sincronização entre o Samsung Health e o Health Connect não é em tempo real. Ela ocorre periodicamente, geralmente a cada 30 a 60 minutos. Você pode acelerar abrindo o Samsung Health manualmente.",
          "**Os dados históricos estão faltando**: o Health Connect não sincroniza de forma retroativa. Atividades anteriores à autorização não vão aparecer. Use a exportação manual do Samsung Health para recuperar o histórico.",
          "**O app de destino não vê nada**: verifique se o app tem permissão de LEITURA no Health Connect. Não basta que o Samsung Health tenha permissão de escrita.",
        ],
        fr: [
          "**Samsung Health n'apparaît pas dans Health Connect**: ouvrez Samsung Health, allez dans Paramètres, puis Gestion des données, puis Health Connect et activez la synchronisation. S'il n'apparaît toujours pas, mettez Samsung Health à jour vers la dernière version.",
          "**Les pas sont présents mais les activités non**: Samsung Health expose les pas automatiquement, mais les séances d'entraînement nécessitent des autorisations séparées. Dans Health Connect, sous Autorisations des applications pour Samsung Health, vérifiez que 'Exercice' est activé en écriture.",
          "**Les données apparaissent en retard**: la synchronisation entre Samsung Health et Health Connect n'est pas en temps réel. Elle se produit périodiquement, généralement toutes les 30 à 60 minutes. Vous pouvez l'accélérer en ouvrant manuellement Samsung Health.",
          "**Les données historiques sont manquantes**: Health Connect ne synchronise pas de manière rétroactive. Les activités antérieures à l'autorisation n'apparaîtront pas. Utilisez l'export manuel de Samsung Health pour récupérer l'historique.",
          "**L'application de destination ne voit rien**: vérifiez que l'application dispose de la permission de LECTURE sur Health Connect. Il ne suffit pas que Samsung Health ait la permission d'écriture.",
        ],
      },
    },
    {
      type: "callout",
      variant: "tip",
      title: {
        it: "Il segnale che stai perdendo tempo",
        en: "The sign you're wasting time",
        es: "La señal de que estás perdiendo el tiempo",
        de: "Das Zeichen, dass du Zeit verschwendest",
        pt: "O sinal de que você está perdendo tempo",
        fr: "Le signe que vous perdez votre temps",
      },
      body: {
        it: "Se la tua app di destinazione non supporta ancora Health Connect nel 2026, non è un problema di configurazione: è un'app abbandonata. Due anni dopo la deprecazione di Google Fit, qualsiasi app attivamente mantenuta ha già implementato il supporto HC. Cambia app invece di cercare workaround per un prodotto che non riceve aggiornamenti.",
        en: "If your destination app still doesn't support Health Connect in 2026, this isn't a configuration problem: it's an abandoned app. Two years after Google Fit's deprecation, any actively maintained app has already implemented HC support. Switch apps instead of hunting for workarounds for a product that no longer receives updates.",
        es: "Si tu app de destino todavía no es compatible con Health Connect en 2026, no es un problema de configuración: es una app abandonada. Dos años después de la deprecación de Google Fit, cualquier app que se mantenga activamente ya ha implementado el soporte para HC. Cambia de app en lugar de buscar soluciones para un producto que ya no recibe actualizaciones.",
        de: "Wenn deine Ziel-App Health Connect im Jahr 2026 immer noch nicht unterstützt, ist das kein Konfigurationsproblem: Es ist eine aufgegebene App. Zwei Jahre nach der Abkündigung von Google Fit hat jede aktiv gepflegte App bereits HC-Unterstützung implementiert. Wechsle die App, anstatt nach Workarounds für ein Produkt zu suchen, das keine Updates mehr erhält.",
        pt: "Se o seu app de destino ainda não suporta Health Connect em 2026, não é um problema de configuração: é um app abandonado. Dois anos após a descontinuação do Google Fit, qualquer app ativamente mantido já implementou suporte ao HC. Troque de app em vez de procurar workarounds para um produto que não recebe mais atualizações.",
        fr: "Si votre application de destination ne prend toujours pas en charge Health Connect en 2026, ce n'est pas un problème de configuration: c'est une application abandonnée. Deux ans après l'abandon de Google Fit, toute application activement maintenue a déjà implémenté la prise en charge de HC. Changez d'application plutôt que de chercher des solutions de contournement pour un produit qui ne reçoit plus de mises à jour.",
      },
    },
    {
      type: "heading",
      level: 2,
      text: {
        it: "In sintesi",
        en: "In summary",
        es: "En resumen",
        de: "Zusammenfassung",
        pt: "Em resumo",
        fr: "En résumé",
      },
    },
    {
      type: "list",
      items: {
        it: [
          "Il sync diretto Samsung Health→Google Fit non esiste più dal 2024: Google ha deprecato Google Fit e spostato l'ecosistema Android su Health Connect.",
          "Il percorso corretto oggi è: Samsung Health scrive su Health Connect, le app di destinazione leggono da Health Connect. Funziona per la maggior parte dei dati standard.",
          "Dati non disponibili via Health Connect: metriche proprietarie Samsung, GPS dettagliato degli allenamenti, dati storici precedenti all'autorizzazione.",
          "Se l'app di destinazione non supporta Health Connect nel 2026, probabilmente non viene mantenuta: considera di cambiarla.",
          "I dati storici in Samsung Health sono al sicuro nel cloud Samsung indipendentemente da Google Fit. Per portarli altrove usa l'export manuale (CSV/XML).",
        ],
        en: [
          "Direct Samsung Health to Google Fit sync has not existed since 2024: Google deprecated Google Fit and moved the Android ecosystem to Health Connect.",
          "The correct path today is: Samsung Health writes to Health Connect, destination apps read from Health Connect. Works for most standard data.",
          "Data not available via Health Connect: Samsung proprietary metrics, detailed workout GPS, historical data predating authorization.",
          "If the destination app doesn't support Health Connect in 2026, it's probably not being maintained: consider switching.",
          "Historical data in Samsung Health is safe in Samsung cloud independent of Google Fit. To port it elsewhere, use manual export (CSV/XML).",
        ],
        es: [
          "La sincronización directa de Samsung Health con Google Fit ya no existe desde 2024: Google deprecó Google Fit y trasladó el ecosistema Android a Health Connect.",
          "El camino correcto hoy es: Samsung Health escribe en Health Connect y las apps de destino leen desde Health Connect. Funciona para la mayoría de los datos estándar.",
          "Datos no disponibles a través de Health Connect: métricas propietarias de Samsung, GPS detallado de los entrenamientos y datos históricos anteriores a la autorización.",
          "Si la app de destino no es compatible con Health Connect en 2026, probablemente no está siendo mantenida: considera cambiarla.",
          "Los datos históricos de Samsung Health están seguros en la nube de Samsung, independientemente de Google Fit. Para trasladarlos a otra plataforma, usa la exportación manual (CSV/XML).",
        ],
        de: [
          "Die direkte Synchronisierung von Samsung Health mit Google Fit gibt es seit 2024 nicht mehr: Google hat Google Fit abgekündigt und das Android-Ökosystem auf Health Connect umgestellt.",
          "Der richtige Weg heute: Samsung Health schreibt in Health Connect, Ziel-Apps lesen von Health Connect. Funktioniert für die meisten Standard-Daten.",
          "Nicht über Health Connect verfügbare Daten: proprietäre Samsung-Metriken, detailliertes GPS der Trainings, historische Daten vor der Autorisierung.",
          "Wenn die Ziel-App Health Connect im Jahr 2026 nicht unterstützt, wird sie wahrscheinlich nicht mehr gepflegt: ziehe einen Wechsel in Betracht.",
          "Historische Daten in Samsung Health sind unabhängig von Google Fit sicher in der Samsung-Cloud. Um sie woanders zu übertragen, nutze den manuellen Export (CSV/XML).",
        ],
        pt: [
          "A sincronização direta do Samsung Health com o Google Fit não existe desde 2024: o Google descontinuou o Google Fit e migrou o ecossistema Android para o Health Connect.",
          "O caminho correto hoje é: o Samsung Health grava no Health Connect e os apps de destino leem do Health Connect. Funciona para a maioria dos dados padrão.",
          "Dados não disponíveis via Health Connect: métricas proprietárias da Samsung, GPS detalhado dos treinos, dados históricos anteriores à autorização.",
          "Se o app de destino não suporta Health Connect em 2026, provavelmente não está sendo mantido: considere trocá-lo.",
          "Os dados históricos do Samsung Health estão seguros na nuvem da Samsung, independentemente do Google Fit. Para levá-los a outro lugar, use a exportação manual (CSV/XML).",
        ],
        fr: [
          "La synchronisation directe de Samsung Health vers Google Fit n'existe plus depuis 2024: Google a abandonné Google Fit et a migré l'écosystème Android vers Health Connect.",
          "Le bon chemin aujourd'hui: Samsung Health écrit dans Health Connect, les applications de destination lisent depuis Health Connect. Fonctionne pour la plupart des données standard.",
          "Données non disponibles via Health Connect: métriques propriétaires Samsung, GPS détaillé des séances d'entraînement, données historiques antérieures à l'autorisation.",
          "Si l'application de destination ne prend pas en charge Health Connect en 2026, elle n'est probablement plus maintenue: envisagez d'en changer.",
          "Les données historiques de Samsung Health sont en sécurité dans le cloud Samsung, indépendamment de Google Fit. Pour les transférer ailleurs, utilisez l'export manuel (CSV/XML).",
        ],
      },
    },
    {
      type: "cta",
      title: {
        it: "Vuoi leggere i dati Samsung Health da browser senza Google Fit?",
        en: "Want to read Samsung Health data from browser without Google Fit?",
        es: "¿Quieres ver tus datos de Samsung Health desde el navegador sin Google Fit?",
        de: "Möchtest du deine Samsung Health-Daten im Browser anzeigen, ohne Google Fit?",
        pt: "Quer ver seus dados do Samsung Health no navegador sem o Google Fit?",
        fr: "Vous souhaitez consulter vos données Samsung Health depuis le navigateur sans Google Fit?",
      },
      body: {
        it: "Tra le opzioni che semplificano questo c'è FitMesh Sync: legge da Health Connect (dove Samsung Health scrive) e mostra i tuoi dati in una dashboard web accessibile da qualsiasi browser, senza dipendere da Google Fit o da infrastrutture proprietarie.",
        en: "Among the options that simplify this is FitMesh Sync: it reads from Health Connect (where Samsung Health writes) and shows your data in a web dashboard accessible from any browser, without depending on Google Fit or proprietary infrastructure.",
        es: "Entre las opciones que simplifican esto está FitMesh Sync: lee desde Health Connect (donde Samsung Health escribe) y muestra tus datos en un panel web accesible desde cualquier navegador, sin depender de Google Fit ni de infraestructuras propietarias.",
        de: "Eine der Optionen, die dies vereinfacht, ist FitMesh Sync: Es liest von Health Connect (wo Samsung Health schreibt) und zeigt deine Daten in einem Web-Dashboard an, das von jedem Browser aus zugänglich ist, ohne von Google Fit oder proprietären Infrastrukturen abhängig zu sein.",
        pt: "Entre as opções que simplificam isso está o FitMesh Sync: ele lê do Health Connect (onde o Samsung Health grava) e exibe seus dados em um painel web acessível de qualquer navegador, sem depender do Google Fit ou de infraestruturas proprietárias.",
        fr: "Parmi les options qui simplifient cela figure FitMesh Sync: il lit depuis Health Connect (où Samsung Health écrit) et affiche vos données dans un tableau de bord web accessible depuis n'importe quel navigateur, sans dépendre de Google Fit ni d'infrastructures propriétaires.",
      },
      ctaLabel: {
        it: "Scopri FitMesh Sync per Samsung Health →",
        en: "Discover FitMesh Sync for Samsung Health →",
        es: "Descubre FitMesh Sync para Samsung Health →",
        de: "FitMesh Sync für Samsung Health entdecken →",
        pt: "Conheça o FitMesh Sync para Samsung Health →",
        fr: "Découvrir FitMesh Sync pour Samsung Health →",
      },
      ctaHref: {
        it: "/it/sync/samsung-health",
        en: "/en/sync/samsung-health",
      },
    },
  ],
  faq: [
    {
      q: {
        it: "Perché Samsung Health non si sincronizza con Google Fit nel 2026?",
        en: "Why doesn't Samsung Health sync with Google Fit in 2026?",
        es: "¿Por qué Samsung Health no se sincroniza con Google Fit en 2026?",
        de: "Warum synchronisiert sich Samsung Health im Jahr 2026 nicht mit Google Fit?",
        pt: "Por que o Samsung Health não sincroniza com o Google Fit em 2026?",
        fr: "Pourquoi Samsung Health ne se synchronise-t-il pas avec Google Fit en 2026?",
      },
      a: {
        it: "Perché Google ha deprecato Google Fit e ha spostato l'ecosistema Android su Health Connect. Samsung ha seguito questo cambiamento: Samsung Health ora scrive su Health Connect invece di Google Fit. Se hai app che leggevano da Google Fit, devono aggiornarsi per leggere da Health Connect.",
        en: "Because Google deprecated Google Fit and moved the Android ecosystem to Health Connect. Samsung followed this change: Samsung Health now writes to Health Connect instead of Google Fit. If you have apps that read from Google Fit, they need to update to read from Health Connect.",
        es: "Porque Google deprecó Google Fit y trasladó el ecosistema Android a Health Connect. Samsung siguió este cambio: Samsung Health ahora escribe en Health Connect en lugar de Google Fit. Si tienes apps que leían de Google Fit, necesitan actualizarse para leer desde Health Connect.",
        de: "Weil Google Google Fit abgekündigt und das Android-Ökosystem auf Health Connect umgestellt hat. Samsung hat diese Änderung mitgemacht: Samsung Health schreibt nun in Health Connect statt in Google Fit. Wenn du Apps hast, die von Google Fit gelesen haben, müssen diese aktualisiert werden, um von Health Connect zu lesen.",
        pt: "Porque o Google descontinuou o Google Fit e migrou o ecossistema Android para o Health Connect. A Samsung acompanhou essa mudança: o Samsung Health agora grava no Health Connect em vez do Google Fit. Se você tem apps que liam do Google Fit, eles precisam ser atualizados para ler do Health Connect.",
        fr: "Parce que Google a abandonné Google Fit et a migré l'écosystème Android vers Health Connect. Samsung a suivi ce changement: Samsung Health écrit désormais dans Health Connect au lieu de Google Fit. Si vous avez des applications qui lisaient depuis Google Fit, elles doivent être mises à jour pour lire depuis Health Connect.",
      },
    },
    {
      q: {
        it: "Devo disinstallare Google Fit?",
        en: "Do I need to uninstall Google Fit?",
        es: "¿Tengo que desinstalar Google Fit?",
        de: "Muss ich Google Fit deinstallieren?",
        pt: "Preciso desinstalar o Google Fit?",
        fr: "Dois-je désinstaller Google Fit?",
      },
      a: {
        it: "Non necessariamente. Google Fit è innocua anche se installata. Ma se stai cercando di usarla come intermediario per ricevere dati da Samsung Health, non funzionerà più come prima. Health Connect è il percorso corretto. Google Fit può rimanere installata ma non è più il punto centrale dell'ecosistema salute Android.",
        en: "Not necessarily. Google Fit is harmless even if installed. But if you're trying to use it as an intermediary to receive data from Samsung Health, it won't work as before. Health Connect is the correct path. Google Fit can remain installed but is no longer the central point of the Android health ecosystem.",
        es: "No necesariamente. Google Fit no causa ningún problema aunque esté instalada. Pero si intentas usarla como intermediario para recibir datos de Samsung Health, ya no funcionará como antes. Health Connect es el camino correcto. Google Fit puede quedarse instalada, pero ya no es el punto central del ecosistema de salud de Android.",
        de: "Nicht unbedingt. Google Fit ist harmlos, auch wenn es installiert ist. Aber wenn du versuchst, es als Vermittler zu nutzen, um Daten von Samsung Health zu empfangen, wird es nicht mehr wie zuvor funktionieren. Health Connect ist der richtige Weg. Google Fit kann installiert bleiben, ist aber nicht mehr der zentrale Punkt des Android-Gesundheitsökosystems.",
        pt: "Não necessariamente. O Google Fit é inofensivo mesmo que esteja instalado. Mas se você tentar usá-lo como intermediário para receber dados do Samsung Health, não vai funcionar como antes. O Health Connect é o caminho correto. O Google Fit pode ficar instalado, mas não é mais o ponto central do ecossistema de saúde Android.",
        fr: "Pas nécessairement. Google Fit est inoffensif même s'il est installé. Mais si vous essayez de l'utiliser comme intermédiaire pour recevoir des données de Samsung Health, cela ne fonctionnera plus comme avant. Health Connect est le bon chemin. Google Fit peut rester installé, mais il n'est plus le point central de l'écosystème de santé Android.",
      },
    },
    {
      q: {
        it: "Health Connect funziona su tutti i telefoni Android?",
        en: "Does Health Connect work on all Android phones?",
        es: "¿Health Connect funciona en todos los teléfonos Android?",
        de: "Funktioniert Health Connect auf allen Android-Telefonen?",
        pt: "O Health Connect funciona em todos os celulares Android?",
        fr: "Health Connect fonctionne-t-il sur tous les téléphones Android?",
      },
      a: {
        it: "Health Connect richiede Android 9 o superiore (ma alcune funzioni richiedono Android 12+). Su Android 14 e superiori è integrato nel sistema operativo. Su Android 12-13 deve essere installato separatamente dal Play Store. Su versioni più vecchie di Android 9, non è disponibile. La maggior parte dei telefoni Samsung in commercio oggi (Galaxy S e A series) supporta Health Connect senza problemi.",
        en: "Health Connect requires Android 9 or higher (but some features require Android 12+). On Android 14 and above it's integrated into the operating system. On Android 12-13 it must be installed separately from the Play Store. On versions older than Android 9, it's not available. Most Samsung phones on sale today (Galaxy S and A series) support Health Connect without problems.",
        es: "Health Connect requiere Android 9 o superior (aunque algunas funciones necesitan Android 12 o más). En Android 14 y versiones superiores está integrado en el sistema operativo. En Android 12-13 hay que instalarlo por separado desde Google Play. En versiones anteriores a Android 9 no está disponible. La mayoría de los teléfonos Samsung actuales (serie Galaxy S y A) son compatibles con Health Connect sin problemas.",
        de: "Health Connect erfordert Android 9 oder höher (einige Funktionen benötigen jedoch Android 12+). Auf Android 14 und höher ist es in das Betriebssystem integriert. Auf Android 12-13 muss es separat aus dem Google Play Store installiert werden. Auf Versionen älter als Android 9 ist es nicht verfügbar. Die meisten Samsung-Telefone, die heute erhältlich sind (Galaxy S und A Series), unterstützen Health Connect ohne Probleme.",
        pt: "O Health Connect requer Android 9 ou superior (mas algumas funções exigem Android 12+). No Android 14 e superior, ele está integrado ao sistema operacional. No Android 12-13, deve ser instalado separadamente pelo Google Play. Em versões anteriores ao Android 9, não está disponível. A maioria dos celulares Samsung disponíveis hoje (série Galaxy S e A) suporta o Health Connect sem problemas.",
        fr: "Health Connect nécessite Android 9 ou supérieur (mais certaines fonctionnalités nécessitent Android 12+). Sur Android 14 et supérieur, il est intégré au système d'exploitation. Sur Android 12-13, il doit être installé séparément depuis Google Play. Sur les versions antérieures à Android 9, il n'est pas disponible. La plupart des téléphones Samsung disponibles aujourd'hui (série Galaxy S et A) prennent en charge Health Connect sans problème.",
      },
    },
    {
      q: {
        it: "I miei dati storici di Samsung Health sono persi se Google Fit smette di funzionare?",
        en: "Is my historical Samsung Health data lost if Google Fit stops working?",
        es: "¿Pierdo mis datos históricos de Samsung Health si Google Fit deja de funcionar?",
        de: "Gehen meine historischen Samsung Health-Daten verloren, wenn Google Fit aufhört zu funktionieren?",
        pt: "Meus dados históricos do Samsung Health se perdem se o Google Fit parar de funcionar?",
        fr: "Mes données historiques Samsung Health sont-elles perdues si Google Fit cesse de fonctionner?",
      },
      a: {
        it: "No. I dati storici in Samsung Health sono nel cloud di Samsung (Samsung Cloud), indipendentemente da Google Fit. Il fatto che Google Fit non funzioni più come intermediario non tocca i dati in Samsung Health. Se vuoi portare lo storico su un'altra piattaforma, usa l'export Samsung Health (CSV/XML) o le nuove integrazioni via Health Connect per il dato recente.",
        en: "No. Historical data in Samsung Health is in Samsung's cloud (Samsung Cloud), independent of Google Fit. The fact that Google Fit no longer works as intermediary doesn't touch data in Samsung Health. If you want to port historical data to another platform, use Samsung Health export (CSV/XML) or new Health Connect integrations for recent data.",
        es: "No. Los datos históricos de Samsung Health están en la nube de Samsung (Samsung Cloud), de forma independiente a Google Fit. El hecho de que Google Fit ya no funcione como intermediario no afecta a los datos de Samsung Health. Si quieres trasladar el historial a otra plataforma, usa la exportación de Samsung Health (CSV/XML) o las nuevas integraciones a través de Health Connect para los datos recientes.",
        de: "Nein. Historische Daten in Samsung Health befinden sich in der Samsung-Cloud (Samsung Cloud), unabhängig von Google Fit. Die Tatsache, dass Google Fit nicht mehr als Vermittler funktioniert, berührt die Daten in Samsung Health nicht. Wenn du historische Daten auf eine andere Plattform übertragen möchtest, verwende den Samsung Health-Export (CSV/XML) oder die neuen Health Connect-Integrationen für aktuelle Daten.",
        pt: "Não. Os dados históricos no Samsung Health estão na nuvem da Samsung (Samsung Cloud), independentemente do Google Fit. O fato de o Google Fit não funcionar mais como intermediário não afeta os dados no Samsung Health. Se você quiser transferir o histórico para outra plataforma, use a exportação do Samsung Health (CSV/XML) ou as novas integrações via Health Connect para dados recentes.",
        fr: "Non. Les données historiques dans Samsung Health se trouvent dans le cloud de Samsung (Samsung Cloud), indépendamment de Google Fit. Le fait que Google Fit ne fonctionne plus comme intermédiaire ne touche pas les données dans Samsung Health. Si vous souhaitez transférer l'historique vers une autre plateforme, utilisez l'export Samsung Health (CSV/XML) ou les nouvelles intégrations via Health Connect pour les données récentes.",
      },
    },
    {
      q: {
        it: "Samsung Health può sincronizzarsi direttamente con Google Health?",
        en: "Can Samsung Health sync directly with Google Health?",
        es: "¿Samsung Health puede sincronizarse directamente con Google Health?",
        de: "Kann sich Samsung Health direkt mit Google Health synchronisieren?",
        pt: "O Samsung Health pode sincronizar diretamente com o Google Health?",
        fr: "Samsung Health peut-il se synchroniser directement avec Google Health?",
      },
      a: {
        it: "Google Health non è una piattaforma pubblica separata: è il marchio ombrello per i prodotti salute di Google (che include Health Connect, Fitbit, Google Fit). Il punto di integrazione tecnico è Health Connect. Samsung Health scrive su Health Connect, e qualsiasi app (incluse quelle di Google) può leggere da lì. Non esiste un sync diretto Samsung Health → un cloud Google specifico al di fuori di questo meccanismo.",
        en: "Google Health isn't a separate public platform: it's the umbrella brand for Google's health products (which includes Health Connect, Fitbit, Google Fit). The technical integration point is Health Connect. Samsung Health writes to Health Connect, and any app (including Google's) can read from there. There's no direct Samsung Health → specific Google cloud sync outside this mechanism.",
        es: "Google Health no es una plataforma pública independiente: es la marca paraguas para los productos de salud de Google (que incluye Health Connect, Fitbit y Google Fit). El punto de integración técnico es Health Connect. Samsung Health escribe en Health Connect y cualquier app (incluidas las de Google) puede leer desde ahí. No existe una sincronización directa de Samsung Health con una nube específica de Google fuera de este mecanismo.",
        de: "Google Health ist keine separate öffentliche Plattform: Es ist die Dachmarke für Googles Gesundheitsprodukte (einschließlich Health Connect, Fitbit, Google Fit). Der technische Integrationspunkt ist Health Connect. Samsung Health schreibt in Health Connect, und jede App (einschließlich Googles Apps) kann von dort lesen. Es gibt keine direkte Synchronisierung von Samsung Health mit einer spezifischen Google-Cloud außerhalb dieses Mechanismus.",
        pt: "O Google Health não é uma plataforma pública separada: é a marca guarda-chuva para os produtos de saúde do Google (que inclui Health Connect, Fitbit, Google Fit). O ponto de integração técnico é o Health Connect. O Samsung Health grava no Health Connect e qualquer app (incluindo os do Google) pode ler de lá. Não existe uma sincronização direta do Samsung Health com uma nuvem específica do Google fora desse mecanismo.",
        fr: "Google Health n'est pas une plateforme publique séparée: c'est la marque ombrelle pour les produits de santé de Google (qui inclut Health Connect, Fitbit, Google Fit). Le point d'intégration technique est Health Connect. Samsung Health écrit dans Health Connect, et n'importe quelle application (y compris celles de Google) peut lire depuis là. Il n'existe pas de synchronisation directe de Samsung Health vers un cloud Google spécifique en dehors de ce mécanisme.",
      },
    },
  ],
  related: [
    "come-funziona-health-connect",
    "health-connect-vs-samsung-health",
    "passi-non-si-sincronizzano-galaxy-watch",
  ],
  brandsMentioned: ["Samsung", "Google", "Fitbit"],
  ldType: "BlogPosting",
};
