import type { BlogPost } from "../types";

export const post: BlogPost = {
  slug: "vo2-max-wearable-comparison-2026",
  category: "comparisons",
  publishedAt: "2026-06-20",
  updatedAt: "2026-06-20",
  readMinutes: 8,
  hero: {
    kicker: {
        it: "Confronto",
        en: "Comparison",
        es: "Comparación",
        de: "Vergleich",
        pt: "Comparação",
        fr: "Comparaison",
        pl: "Porównanie",
        tr: "Karşılaştırma",
        nl: "Vergelijking",
        ja: "比較",
        ko: "비교",
      },
    title: {
        it: "L'VO2 Max da un portatile nel 2026: quanto è davvero accurato?",
        en: "VO2 Max from a wearable in 2026: how accurate is it really?",
        es: "VO2 Max desde un wearable en 2026: ¿cuánto se mantiene su precisión?",
        de: "VO2 Max aus einem Wearable im Jahr 2026: Wie genau ist er wirklich?",
        pt: "VO2 Max de uma pulseira em 2026: como é preciso ele realmente é?",
        fr: "VO2 Max d'un bracelet connecté en 2026 : est-il vraiment précis ?",
        pl: "VO2 Max z przewornika w 2026 roku: jak dokładne jest to naprawdę?",
        tr: "2026'da bir takı cihazından VO2 Max: ne kadar doğru?",
        nl: "VO2 Max van een draagbare in 2026: hoe nauwkeurig is het werkelijk?",
        ja: "2026年のウェアラブルからVO2 Max：どれだけ正確ですか？",
        ko: "2026년 스마트워치에서의 VO2 Max: 얼마나 정확한가요?",
      },
    subtitle: {
        it: "Garmin, Polar, Galaxy Watch e Apple Watch stima il tuo VO2 Max. Spiegiamo come lo calcolano, quanta affidabilità ha e cosa fare con il numero.",
        en: "Garmin, Polar, Galaxy Watch, and Apple Watch all estimate your VO2 Max. We explain how they calculate it, how reliable it is, and what to do with the number.",
        es: "Garmin, Polar, Galaxy Watch y Apple Watch estiman tu VO2 Max. Explicamos cómo lo calculan, cuán confiable es y qué hacer con el número.",
        de: "Garmin, Polar, Galaxy Watch und Apple Watch schätzen Ihre VO2 Max. Wir erklären, wie sie es berechnen, wie zuverlässig es ist und was man mit dem Wert anfangen soll.",
        pt: "Garmin, Polar, Galaxy Watch e Apple Watch estimam seu VO2 Max. Explicamos como eles calculam isso, quão confiável é e o que fazer com esse número.",
        fr: "Garmin, Polar, Galaxy Watch et Apple Watch estimate votre VO2 Max. Nous expliquons comment ils le calculent, quelle est sa fiabilité et ce à quoi servir ce nombre.",
        pl: "Garmin, Polar, Galaxy Watch i Apple Watch szacują Twoje VO2 Max. wyjaśniamy, jak oni go liczą, jak wiarygodny jest ten wynik oraz co z tym numerem powinieneś zrobić.",
        tr: "Garmin, Polar, Galaxy Watch ve Apple Watch tümü VO2 Max'u tahmin ediyor. Bu sayı ne anlama geliyor, güvenilirliği nasıl olup da bunu yapmanıza yardımcı olacağız.",
        nl: "Garmin, Polar, Galaxy Watch en Apple Watch schatten je VO2 Max. We leggen uit hoe ze het berekenen, hoe betrouwbaar het is en wat je met het getal moet doen.",
        ja: "Garmin, Polar, Galaxy Watch, Apple WatchはすべてあなたのVO2 Maxを推定します。その計算方法、信頼性、数値の扱いについて説明します。",
        ko: "Garmin, Polar, Galaxy Watch 및 Apple Watch는 모두 당신의 VO2 Max를 추정합니다. 숫자가 어떻게 계산되는지, 얼마나 신뢰할 수 있는지 그리고 숫자에 대해 무엇을 해야 하는지 설명합니다.",
      },
  },
  metaDescription: {
      it: "Quanto è accurato l'VO2 Max da un smartwatch nel 2026? Confrontiamo Garmin, Polar, Galaxy Watch e spiegiamo cosa significa il numero e quando fidarsi di esso.",
      en: "How accurate is VO2 Max from a smartwatch in 2026? We compare Garmin, Polar, Galaxy Watch and explain what the number means and when to trust it.",
      es: "¿Cuánto se mantiene la precisión del VO2 Max en un smartwatch en 2026? Comparamos Garmin, Polar, Galaxy Watch y explicamos qué significa el número y cuándo merece la pena confiar en él.",
      de: "Wie genau ist die VO2 Max aus einem Smartwatch im Jahr 2026? Wir vergleichen Garmin, Polar, Galaxy Watch und erklären, was der Wert bedeutet und wann man ihn vertrauen kann.",
      pt: "Como é preciso o VO2 Max de um relógio inteligente em 2026? Comparamos Garmin, Polar, Galaxy Watch e explicamos o que esse número significa e quando confiar nele.",
      fr: "Quelle est l'exactitude du VO2 Max d'un bracelet connecté en 2026 ? Nous comparons Garmin, Polar, Galaxy Watch et expliquons ce que signifie ce nombre et quand le croire.",
      pl: "Jaka jest dokładność VO2 Max z zegarka w 2026 roku? Porównujemy Garmin, Polar, Galaxy Watch i wyjaśniamy, co oznacza ta liczba i kiedy można na nią polegać.",
      tr: "2026'da smarthWATCH'tan elde edilen VO2 Max ne kadar doğru? Garmin, Polar, Galaxy Watch ve Apple Watch'u karşılaştırıyoruz ve bu sayı ne anlama geliyor, güvenilirliği nerede olduğunu açıklıyoruz.",
      nl: "Hoe nauwkeurig is VO2 Max van een smartwatch in 2026? We vergelijken Garmin, Polar, Galaxy Watch en leggen uit wat het getal betekent en wanneer je erop mag vertrouwen.",
      ja: "2026年でスマートウォッチのVO2 Maxはどれだけ正確ですか？Garmin, Polar, Galaxy Watch, Apple Watchを比較し、その数値が何を意味するか、信頼すべきかどうかを説明します。",
      ko: "2026년 스마트워치에서의 VO2 Max 정확도는 어떻게 되나요? Garmin, Polar, Galaxy Watch 및 Apple Watch를 비교하고 숫자가 의미하는 바와 언제 신뢰할 수 있는지 설명합니다.",
    },
  primaryKeyword: {
      it: "accuratezza dell'VO2 Max portatile 2026",
      en: "vo2 max wearable accuracy 2026",
      es: "precisión de VO2 Max wearable 2026",
      de: "vo2 max wearable accuracy 2026",
      pt: "precisão do VO2 Max nas pulseiras em 2026",
      fr: "exactitude du VO2 Max des appareils wearables 2026",
      pl: "dokładność VO2 Max z przewornika 2026",
      tr: "2026 vo2 max wearable doğruluğu",
      nl: "vo2 max wearable accuracy 2026",
      ja: "vo2 max wearable accuracy 2026",
      ko: "vo2 maxearable accuracy 2026",
    },
  secondaryKeywords: {
      it: [
        "garmin vo2 max accuratezza",
        "polar vo2 max stimazione corsa",
        "smartwatch vo2 max galaxy watch",
        "health connect vo2 max android",
      ],
      en: [
        "garmin vo2 max how accurate",
        "polar vo2 max estimation running",
        "smartwatch vo2 max galaxy watch",
        "health connect vo2 max android",
      ],
      es: [
        "vo2 max de Garmin ¿cuánto se mantiene su precisión",
        "vo2 max de Polar estimación corriendo",
        "vo2 max smartwatch Galaxy Watch",
        "Health Connect vo2 max Android",
      ],
      de: [
        "garmin vo2 max how accurate",
        "polar vo2 max estimation running",
        "smartwatch vo2 max galaxy watch",
        "health connect vo2 max android",
      ],
      pt: [
        "precisão do VO2 Max da Garmin",
        "estimativa de VO2 Max Polar para corredores",
        "VO2 Max nas pulseiras inteligentes Galaxy Watch",
        "Health Connect e VO2 Max no Android",
      ],
      fr: [
        "exactitude du VO2 Max Garmin",
        "estimation du VO2 Max Polar course à pied",
        "VO2 Max bracelet connecté Galaxy Watch",
        "Health Connect VO2 Max Android",
      ],
      pl: [
        "dokładność VO2 Max Garmin",
        "szacowanie VO2 Max Polar bieganie",
        "smartwatch i szacowanie VO2 Max Galaxy Watch",
        "Health Connect i szacowanie VO2 Max na Androidzie",
      ],
      tr: [
        "garmin vo2 max doğruluğu",
        "polar vo2 max tahmini koşu",
        "takipci vo2 max galaxy watch",
        "health connect vo2 max android",
      ],
      nl: [
        "garmin vo2 max hoe nauwkeurig",
        "polar vo2 max schatting lopen",
        "smartwatch vo2 max galaxy watch",
        "health connect vo2 max android",
      ],
      ja: [
        "garmin vo2 max どれだけ正確",
        "polar vo2 max 跑步估算",
        "スマートウォッチ vo2 max galaxy watch",
        "health connect vo2 max android",
      ],
      ko: [
        "garmin vo2 max 정확도",
        "polar vo2 max 추정 러닝",
        "스마트워치 vo2 max galaxy watch",
        "health connect vo2 max 안드로이드",
      ],
    },
  tldr: {
      it: [
        "L'VO2 Max portatile è un'istantanea basata su tassi cardiaco e velocità durante la corsa, non una misurazione di laboratorio.",
        "Garmin e Polar hanno gli algoritmi più validati. Galaxy Watch e Apple Watch sono vicine ma meno testate.",
        "L'accuratezza è generalmente all'interno di 3-5 ml/kg/min rispetto a una misurazione di laboratorio per i corredini, più ampio per gli iniziati.",
        "Il trend conta più del numero assoluto. Un VO2 Max che aumenta negli otto settimane significa che la tua forma fisica migliora.",
        "Health Connect memorizza l'VO2 Max su Android. FitMesh può visualizzare il trend nel tempo attraverso diversi dispositivi.",
      ],
      en: [
        "Wearable VO2 Max is an estimate based on heart rate and pace during running, not a lab measurement.",
        "Garmin and Polar have the most validated algorithms. Galaxy Watch and Apple Watch are close but less tested.",
        "Accuracy is typically within 3-5 ml/kg/min of a lab test for trained runners, wider for beginners.",
        "The trend matters more than the absolute number. A rising VO2 Max over 8 weeks means your fitness is improving.",
        "Health Connect stores VO2 Max on Android. FitMesh can display the trend over time across devices.",
      ],
      es: [
        "El VO2 Max wearable es una estimación basada en la frecuencia cardíaca y el ritmo durante el running, no una medición de laboratorio.",
        "Garmin y Polar tienen los algoritmos más validados. Galaxy Watch y Apple Watch son cercanas pero menos probadas.",
        "La precisión suele estar dentro del rango de 3-5 ml/kg/min respecto a una prueba de laboratorio para corredores entrenados, más amplio para principiantes.",
        "Lo que importa es la tendencia más que el número absoluto. Un VO2 Max en aumento durante 8 semanas significa que tu condición física está mejorando.",
        "Health Connect almacena el VO2 Max en Android. FitMesh puede mostrar la tendencia a lo largo del tiempo entre dispositivos.",
      ],
      de: [
        "Wearable VO2 Max ist eine Schätzung basierend auf Herzfrequenz und Tempo während des Laufens, keine Labormessung.",
        "Garmin und Polar haben die am besten validierten Algorithmen. Galaxy Watch und Apple Watch sind nahe dran, aber weniger getestet.",
        "Die Genauigkeit beträgt typischerweise 3-5 ml/kg/min in Bezug auf eine Labormessung für trainierte Läufer, breiter für Anfänger.",
        "Der Trend zählt mehr als der absolute Wert. Eine steigende VO2 Max über 8 Wochen bedeutet, dass Ihre Fitness verbessert wird.",
        "Health Connect speichert die VO2 Max auf Android. FitMesh kann den Trend über Zeit auf verschiedenen Geräten anzeigen.",
      ],
      pt: [
        "O VO2 Max nas pulseiras é uma estimativa baseada em ritmo cardíaco e velocidade durante a corrida, não um teste laboratorial.",
        "Garmin e Polar têm os algoritmos mais validados. Galaxy Watch e Apple Watch estão próximos mas menos testados.",
        "A precisão é geralmente entre 3-5 ml/kg/min de um teste laboratorial para corredores treinados, maior para iniciantes.",
        "O que importa mais do que o número absoluto é a tendência. Um VO2 Max em aumento ao longo de 8 semanas significa que sua condicionamento físico está melhorando.",
        "Health Connect armazena o VO2 Max no Android. FitMesh pode exibir essa tendência ao longo do tempo entre dispositivos.",
      ],
      fr: [
        "Le VO2 Max des appareils wearables est une estimation basée sur le taux cardiaque et la vitesse pendant la course, pas une mesure d'un laboratoire.",
        "Garmin et Polar ont les algorithmes les plus validés. Galaxy Watch et Apple Watch sont proches mais moins testés.",
        "L'exactitude est généralement comprise entre 3-5 ml/kg/min d'une mesure de laboratoire pour des coureurs entraînés, plus large pour les débutants.",
        "La tendance compte plus que le nombre absolu. Un VO2 Max en hausse sur 8 semaines signifie que votre forme s'améliore.",
        "Health Connect stocke le VO2 Max sur Android. FitMesh peut afficher la tendance au fil du temps sur différents appareils.",
      ],
      pl: [
        "Szacowany VO2 Max z przewornika opiera się na frekwencji serca i prędkości podczas biegu, nie jest to pomiar laboratorium.",
        "Garmin i Polar mają najbardziej walidowane algorytmiczne metody. Galaxy Watch i Apple Watch są blisko, ale mniej przetestowane.",
        "Dokładność wynika zazwyczaj w granicach 3-5 ml/kg/min od pomiaru laboratorium dla biegaczy treningowych, szerokość jest większa dla początkujących.",
        "Znaczek ma więcej znaczenia niż absolutna liczba. Zniesienie VO2 Max w ciągu 8 tygodni oznacza poprawę fitnessu.",
        "Health Connect zapisuje VO2 Max na Androidzie. FitMesh może wyświetlać trend po czasie na różnych urządzeniach.",
      ],
      tr: [
        "Takı cihazlı VO2 Max, koşulma hızı ve koşu sırasında kalp atış hızına dayanan bir tahmindir, laboratuvar ölçümü değildir.",
        "Garmin ve Polar en doğrulanmış algoritmaları kullanıyor. Galaxy Watch ve Apple Watch yaklaşımda ancak daha az test edilmiş.",
        "Bilindiğine göre, deneyimli koşucular için laboratuvar testi ile 3-5 ml/kg/min arasındaki doğruluk, basıncı düşünenler için genişlier.",
        "Sayının mutlak değerinden daha önemlidir. 8 hafta içinde artan VO2 Max, performansınız iyileştiğini gösteriyor.",
        "Health Connect Android'de VO2 Max'u saklar. FitMesh zamanla cihazlardaki eğilimleri gösterebilir.",
      ],
      nl: [
        "Wearable VO2 Max is een schatting gebaseerd op hartslag en snelheid tijdens het lopen, niet een laboratoriummeetings.",
        "Garmin en Polar hebben de meest gevalideerde algoritmen. Galaxy Watch en Apple Watch zijn dichtbij maar minder getest.",
        "Nauwkeurigheid is meestal binnen 3-5 ml/kg/min van een laboratoriumtest voor gerichte lopers, breder voor beginners.",
        "De trend telt meer dan het absolute getal. Een stijgende VO2 Max over 8 weken betekent dat je fitness verbetert.",
        "Health Connect slaat VO2 Max op in Android. FitMesh kan de trend over tijd toonbaar maken over meerdere apparaten.",
      ],
      ja: [
        "ウェアラブルVO2 Maxはランニング中の心拍数とペースに基づく推定であり、実験室測定ではありません。",
        "GarminとPolarは最も検証されたアルゴリズムを持っています。Galaxy WatchとApple Watchも近いですがテストが少ないです。",
        "訓練されたランナーの場合、実験室測定から3-5 ml/kg/min以内の精度が通常です。初心者の場合、範囲は広くなります。",
        "傾向よりも絶対的な数値の方が重要です。8週間でVO2 Maxが上昇している場合、フィットネスが向上していることを意味します。",
        "Health ConnectはAndroidでVO2 Maxを保存します。FitMeshは複数のデバイスでの時間経過による傾向を表示できます。",
      ],
      ko: [
        "스마트워치 VO2 Max는 달리기 중 심박수와 속도를 기반으로 추정되는 임상 실험과는 다르게 추정된 값입니다.",
        "Garmin과 Polar는 가장 검증된 알고리즘을 가지고 있습니다. Galaxy Watch와 Apple Watch는 비슷하지만 테스트가 덜 되었습니다.",
        "훈련된 러너의 경우 실험실 측정값 대비 정확도는 보통 3-5 ml/kg/min 내외로, 초보자의 경우 더 넓습니다.",
        "절대 값보다 추세가 중요합니다. 8주 동안 VO2 Max가 상승하는 것은 체력이 향상되고 있다는 의미입니다.",
        "Health Connect는 안드로이드에서 VO2 Max를 저장합니다. FitMesh는 장치 간에 시간을 걸쳐 추세를 표시할 수 있습니다.",
      ],
    },
  body: [
    {
      type: "paragraph",
      text: {
          it: "L'VO2 Max è il volume massimo di ossigeno che il tuo corpo può utilizzare durante un'esercizio intensivo. È uno dei predittori più forti della salute cardiovascolare a lungo termine e della resistenza aerobica. La misurazione in laboratorio richiede una tapis roulant, un analizzatore di gas e un cardiologo, ed costa centinaia d'euro. I portatili lo stimano gratuitamente utilizzando i dati del tassi cardiaco e della velocità GPS. La domanda è: quanto vicini sono?",
          en: "VO2 Max is the maximum volume of oxygen your body can use during intense exercise. It is one of the strongest predictors of long-term cardiovascular health and aerobic fitness. Lab testing requires a treadmill, a gas analyzer, and a cardiologist, and costs several hundred euros. Wearables estimate it for free using heart rate and GPS pace data. The question is: how close are they?",
          es: "El VO2 Max es el volumen máximo de oxígeno que tu cuerpo puede utilizar durante un ejercicio intenso. Es uno de los mejores predictores de la salud cardiovascular a largo plazo y la condición aeróbica. La prueba en laboratorio requiere una cinta elevadora, un analizador gaseoso y un cardiólogo, y cuesta varios cientos de euros. Los wearables lo estiman gratis utilizando datos de frecuencia cardíaca y velocidad GPS. La pregunta es: ¿cómo cerca están?",
          de: "Die VO2 Max ist der maximale Volumen von Sauerstoff, das Ihr Körper während intensiver Bewegung nutzen kann. Sie ist einer der stärksten Vorhersagewerte für die langfristige Herz-Kreislaufgesundheit und den aeroben Fitnessgrad. Labormessungen erfordern einen Laufband, eine Gasanalyse und einen Kardiologen und kosten mehrere Hundert Euro. Wearables schätzen sie kostenlos anhand von Herzfrequenz- und GPS-Geschwindigkeitsdaten. Die Frage ist: Wie genau sind sie?",
          pt: "O VO2 Max é a maior quantidade de oxigênio que seu corpo pode usar durante exercícios intensos. É um dos principais preditores da saúde cardíaca e fitness aeróbico à longo prazo. Testes laboratoriais exigem uma esteira, um analisador de gás e um cardiologista, custando several hundred euros. Os dispositivos wearables estimam isso gratuitamente usando dados de ritmo cardíaco e GPS de velocidade. A pergunta é: quão próximos eles estão?",
          fr: "Le VO2 Max est le volume maximal d'oxygène que votre corps peut utiliser pendant un exercice intense. C'est l'un des meilleurs prédicteurs de la santé cardiovasculaire à long terme et de la condition physique aerobique. Les tests en laboratoire nécessitent une tapisserie, un analyseur de gaz et un cardiologue, et coûtent plusieurs centaines d'euros. Les appareils wearables l'estiment gratuitement à partir des données du taux cardiaque et de la vitesse GPS. La question est : combien sont-ils proches ?",
          pl: "VO2 Max to maksymalny objętość tlenu, jaki jest w stanie wykorzystać ciało podczas intensywnego ćwiczenia. Jest jednym z najmocniejszych predykatorów długoterminowej zdrowia serca i krwi oraz fitnessu aerobycznego. Testowanie laboratorium wymaga tarczy biegunowej, analizatora gazowego i kardiologa, kosztuje kilka setek euro. Przeworniki szacują go za darmo wykorzystując dane frekwencji serca i prędkości GPS. Pytanie jest: jak blisko są one?",
          tr: "VO2 Max, yoğun bir egzersiz sırasında vücudun en fazla oksijen kullanımını ifade eder. Bu, uzun vadeli kalp ve damar sağlığına ve aerobik performansı için en güçlü öngörüleyici parametrelerden biridir. Laboratuvar testi, telsiz kullanır, gaz analizi gerektirir ve bir cardiolog tarafından gerçekleştirilir ve birkaç yüz euro maliyetlidir. Takı cihazları kalp atış hızı ve GPS hızı verilerini kullanarak bunu ücretsiz olarak tahmin ederler. Sorun şu: ne kadar yakın?",
          nl: "**VO2 Max** is het maximum volume van zuurstof dat je lichaam tijdens intensieve oefening kan gebruiken. Het is een van de sterkste voorspellende factoren voor langdurige cardiovasculaire gezondheid en aerobische fitness. Laboratoriumtests vereisen een looptrap, een gasanalyser en een cardioloog en kosten meerdere honderden euro's. Wearables schatten het gratis met behulp van hartslag- en GPS-snelheidsgegevens. De vraag is: hoe nauwkeurig zijn ze?",
          ja: "VO2 Maxは、激しい運動中にあなたの体が使用できる最大酸素量です。これは長期的な心臓血管健康と有酸素フィットネスの最も強い予測子の一つです。実験室でのテストには treadmill, ガス分析器, 心脏病专家が必要で、数百ユーロがかかります。ウェアラブルは心拍数とGPSペースデータを使用して無料で推定します。問題は：どれだけ正確か？",
          ko: "VO2 Max는 근간 강도 운동 중에 몸이 사용할 수 있는 최대 산소량입니다. 이는 장기 심혈관 건강과 유산지형 피트니스의 가장 강력한 예측 인자 중 하나입니다. 실험실 측정은 테드미널, 가스 분석기 및 심장내과 의사가 필요하며 수백 유로를 비용으로 들입니다. 스마트워치는 심박수와 GPS 속도 데이터를 사용하여 무료로 추정합니다. 문제는 얼마나 정확한지 입니다?",
        },
    },
    {
      type: "heading",
      level: 2,
      text: {
          it: "Come i portatili stima l'VO2 Max",
          en: "How wearables estimate VO2 Max",
          es: "Cómo los wearables estiman el VO2 Max",
          de: "Wie Wearables die VO2 Max schätzen",
          pt: "Como os wearables estimam o VO2 Max",
          fr: "Comment les appareils wearables estimate le VO2 Max",
          pl: "Jak przeworniki szacują VO2 Max",
          tr: "Takı cihazlarının VO2 Max'u nasıl tahmin ettikleri",
          nl: "Hoe wearables VO2 Max schatten",
          ja: "ウェアラブルがVO2 Maxをどのように推定するか",
          ko: "스마트워치에서 VO2 Max를 어떻게 추정하는가",
        },
    },
    {
      type: "paragraph",
      text: {
          it: "Il principio fondamentale è semplice: a una data velocità di corsa, un atleta più allenato ha un tassi cardiaco più basso. Garmin e Polar usano algoritmi sviluppati con eserciziologi che confrontano il tuo tassi cardiaco con la tua velocità nel tempo. Più consistenti sono i tuoi allenamenti, meglio sarà l'istantanea. Un singolo allenamento su un percorso collinoso in caldo è una base pessima. Un mese di allenamenti variati dà all'algoritmo abbastanza dati per convergere su un'istantanea stabile.",
          en: "The core principle is simple: at a given running pace, a fitter person has a lower heart rate. Garmin and Polar use algorithms developed with exercise physiologists that compare your heart rate to your speed over time. The more consistent your runs, the better the estimate. One run on a hilly route in the heat is a poor basis. A month of varied runs gives the algorithm enough data to converge on a stable estimate.",
          es: "El principio central es simple: a una determinada velocidad de running, una persona más apta tiene un ritmo cardíaco más bajo. Garmin y Polar utilizan algoritmos desarrollados con ejercicios fisiólogos que comparan tu frecuencia cardíaca con tu velocidad en el tiempo. Cuanto más consistentes sean tus entrenamientos, mejor será la estimación. Un solo entrenamiento en una ruta montañosa en calor es un mal punto de partida. Un mes de entrenamientos variados proporciona algoritmos suficientes datos para converger en una estimación estable.",
          de: "Der Kernprinzip ist einfach: Bei einem gegebenen Lauftempo hat ein fitterer Mensch eine niedrigere Herzfrequenz. Garmin und Polar verwenden Algorithmen, die mit Sportphysiologen entwickelt wurden, um Ihre Herzfrequenz zu Ihrem Tempo im Verlauf der Zeit zu vergleichen. Je konsistent Ihre Laufgänge sind, desto besser ist die Schätzung. Ein Lauf auf einer hohen Route in der Hitze ist ein schlechter Grundstein. Eine Monatsmenge an variablen Laufgängen gibt dem Algorithmus genügend Daten, um eine stabile Schätzung zu erzielen.",
          pt: "O princípio central é simples: a um determinado ritmo de corrida, uma pessoa mais apta tem um ritmo cardíaco menor. Garmin e Polar usam algoritmos desenvolvidos com exerciciosiologistas que comparam seu ritmo cardíaco à sua velocidade ao longo do tempo. Quanto mais consistente forem seus treinos, melhor será a estimativa. Uma única corrida em uma rota montanhosa no calor é um bom fundamento. Um mês de treinos variados dá ao algoritmo o suficiente dados para convergir em uma estimativa estável.",
          fr: "Le principe fondamental est simple : pour une même vitesse de course, une personne plus en forme a un taux cardiaque plus bas. Garmin et Polar utilisent des algorithmes développés avec des physiologistes du sport qui comparent votre taux cardiaque à votre vitesse au fil du temps. Plus vos courses sont cohérentes, mieux est l'estimation. Une seule course sur une route pentue dans la chaleur constitue un mauvais fondement. Un mois de courses variées donne suffisamment de données à l'algorithme pour converger vers une estimation stable.",
          pl: "Podstawowa zasada jest prosta: na dana prędkość biegu, bardziej treningowy osoba ma niższą frekwencję serca. Garmin i Polar używają algorytmów opracowanych wraz z fizjologami ćwiczeń, które porównują Twoją frekwencję serca do prędkości po czasie. Im więcej zróżnicowanych biegów wykonasz, tym lepsza jest szacunek. Jedna turba na trase z górskimi drogami w ciepłe dni to słabe podstawy. Miesiąc z różnorodnych biegów daje algorytmowi wystarczające dane do osiągnięcia stabilnego szacunku.",
          tr: "Temel prensip basit: belirli bir koşu hızında daha iyi koşucular düşük kalp atış hızına sahiptir. Garmin ve Polar egzersiz fizyolojistler ile geliştirilmiş algoritmalar kullanır ki bunlar zamanla hızınız ve kalp atışınızı karşılaştırır. Daha fazla koşu yapmanız, tahminin daha iyi olması için yeterli veri sağlar. Bir kere bir hırsızlıktaki yolda sıcak koştuğunuzda basit bir temel. Bir ay boyunca çeşitli koşular yaparak algoritma yeterince veri edinebilir ve sabit bir tahmin elde etmeye başlayabilir.",
          nl: "Het kernprincipe is eenvoudig: bij een bepaalde lopensnelheid heeft een fittere persoon een lagere hartslag. Garmin en Polar gebruiken algoritmen ontwikkeld met sportfysiologen die je hartslag vergelijken met je snelheid over tijd. Hoe meer variëerde runs je doet, hoe beter de schatting. Een run op een hellingachtige route in het warme weer is een slecht basis. Een maand vol variëerde runs geeft het algoritme genoeg gegevens om op te convergeren naar een stabiele schatting.",
          ja: "基本的な原理は単純です：特定の走行速度において、よりフィットな人は心拍数が低いです。GarminとPolarは運動生理学者と共に開発されたアルゴリズムを使用し、あなたの心拍数を時間とともに速度と比較します。ランニングのパターンがより一貫しているほど、推定値も正確になります。山道での1回のランや暑い日のランは良い基準ではありません。1ヶ月間の多様なランニングでアルゴリズムに十分なデータを与えることができます。",
          ko: "핵심 원리는 간단합니다: 같은 달리기 속도에서 더 건강한 사람은 심박수가 낮습니다. Garmin과 Polar는 운동 생리학자들과 협력하여 시간에 따른 속도와 심박수를 비교하는 알고리즘을 사용합니다. 달리기를 일관되게 하는 것이 추정의 정확성을 높입니다. 한 번의 산길 달리기는 열이 나는 상황에서 나쁜 기반일 수 있습니다. 다양한 달리기 1개월 동안 알고리즘에 충분한 데이터를 제공할 수 있습니다.",
        },
    },
    {
      type: "callout",
      variant: "info",
      title: {
          it: "Quando l'VO2 Max portatile non è affidabile",
          en: "When wearable VO2 Max is unreliable",
          es: "Cuándo el VO2 Max wearable es inreliables",
          de: "Wann ist die Wearable-VO2 Max unzuverlässig",
          pt: "Quando o VO2 Max nas pulseiras não é confiável",
          fr: "Quand le VO2 Max des appareils wearables est peu fiable",
          pl: "Kiedy szacowany VO2 Max z przewornika jest niepewny",
          tr: "Takı cihazlı VO2 Max'un güvenilir olmayan zamanları",
          nl: "Wanneer wearable VO2 Max onbetrouwbaar is",
          ja: "ウェアラブルVO2 Maxが不確実なとき",
          ko: "스마트워치 VO2 Max가 불확실한 경우",
        },
      body: {
          it: "La stima è meno precisa se esegui solo allenamenti indoor (senza GPS di velocità), se hai un tasso cardiaco riposante elevato a causa di una malattia o farmaci, se utilizzi percorsi off road con grande perdita d'altitudine, o se hai appena iniziato a correre e le tue metriche sono ancora altamente variabili.",
          en: "The estimate is least accurate if you only do indoor workouts (no GPS pace), if you have a high resting heart rate from illness or medication, if you use trail routes with large elevation gain, or if you have just started running and your metrics are still highly variable.",
          es: "La estimación es menos precisa si solo realizas trabajos de indoor (sin GPS de velocidad), si tienes un ritmo cardíaco en reposo alto debido a una enfermedad o medicamentos, si usas rutas de senderismo con gran ganancia de altitud, o si has comenzado a correr y tus métricas aún son muy variables.",
          de: "Die Schätzung ist am ungenauesten, wenn Sie nur indoor-Arbeitssätze (kein GPS-Geschwindigkeitsmessung) durchführen, wenn Sie eine hohe Ruheherzrate infolge Krankheit oder Medikamente haben, wenn Sie auf Wegen mit großer Höhenunterschiede laufen oder wenn Sie erst begonnen haben zu rennen und Ihre Metriken noch sehr variabel sind.",
          pt: "A estimativa é menos precisa se você apenas fizer treinos internos (sem GPS de velocidade), se tiver um ritmo cardíaco repouso alto devido a uma doença ou medicamento, se usar rotas de trilha com ganho elevacional significativo, ou se acabar de começar a correr e suas métricas ainda forem altamente variáveis.",
          fr: "L'estimation est la moins précise si vous faites uniquement des entraînements intérieurs (sans GPS de vitesse), si vous avez un taux cardiaque au repos élevé en raison d'une maladie ou de médicaments, si vous utilisez des itinéraires de sentier avec une forte perte d'altitude, ou si vous venez de commencer à courir et que vos métriques sont encore très variables.",
          pl: "Oceniając, najmniej precyzyjna jest ocena, jeśli prowadzisz tylko treningi wewnątrzdomowe (bez GPS prędkości), masz wysoki rytm odpoczynek ze względu na chorobę lub leki, korzystasz z tras terenowych z dużym zwinięciem wysokościowego, lub niedawno zacząłeś biegać i Twoje metryki nadal są bardzo niepewne.",
          tr: "Etkinlik sadece iç egzersizlerde (GPS hız yok) yapıldığında, hastalıklar veya ilaçlardan yüksek dinlenme kalp hızı durumunda, büyük yük artışıyla yürüyüş yolları kullanıldığında veya yeni bir koşu başlattığınızda ve ölçümler hala çok değişken olduğunda en az doğru tahmin verir.",
          nl: "De schatting is het minst nauwkeurig als je alleen indoor workoutjes doet (geen GPS-pace), als je een hoge rusthartslag hebt vanwege ziekte of medicatie, als je trajecten volgt met grote hellingen, of als je net begonnen bent te rennen en je meetwaarden nog zeer variabel zijn.",
          ja: "推定は、GPSペースなしの室内トレーニングのみ、病気や薬から高い静息心拍数、大きな標高差があるトレールルートを使用、またはまだ高度な変動性を持つメトリクスで初めてランニングを始めた場合など、最も正確ではありません。",
          ko: "실내 운동만 할 경우(위치 정보 없음), 기저 심박수가 높은 질병이나 약물로 인한 것, 큰 고도 상승을 가진 트레일 경로를 사용할 경우, 최근에 시작하여 메트릭이 여전히 매우 변동성이 큰 경우 예측은 가장 정확하지 않을 수 있습니다.",
        },
    },
    {
      type: "heading",
      level: 2,
      text: {
          it: "Quali dispositivi lo fanno meglio",
          en: "Which devices do it best",
          es: "¿Cuáles dispositivos lo hacen mejor",
          de: "Welche Geräte leisten es am besten",
          pt: "Quais dispositivos fazem melhor",
          fr: "Quels appareils le font le mieux",
          pl: "Jakie urządzenia to najlepiej robią",
          tr: "Hangi cihazlar en iyi",
          nl: "Welke apparaten doen het beste",
          ja: "どのデバイスが最適か",
          ko: "가장 잘하는 기기",
        },
    },
    {
      type: "table",
      caption: {
          it: "Confronto della stima di VO2 Max per piattaforma",
          en: "VO2 Max estimation comparison by platform",
          es: "Comparación de la estimación de VO2 Max por plataforma",
          de: "Vergleich der VO2-Max-Schätzungen nach Plattform",
          pt: "Comparações da estimativa de VO2 Max por plataforma",
          fr: "Comparaison de l'estimation du VO2 Max par plateforme",
          pl: "Porównanie ocen estymacji VO2 Maxa według platformy",
          tr: "Platforma göre VO2 Max tahmini karşılaştırması",
          nl: "Comparatie VO2 Max schatting per platform",
          ja: "プラットフォーム別VO2 Max推定比較",
          ko: "플랫폼별 VO2 Max 추정 비교",
        },
      headers: {
          it: [
            "Dispositivo / Piattaforma",
            "Metodo",
            "Precisione validata",
            "Supporto ciclismo",
            "Sincronizzazione HC",
          ],
          en: [
            "Device / Platform",
            "Method",
            "Validated accuracy",
            "Cycling support",
            "HC sync",
          ],
          es: [
            "Dispositivo / Plataforma",
            "Método",
            "Precisión validada",
            "Soporte para ciclismo",
            "Sincronización de HC",
          ],
          de: [
            "Gerät / Plattform",
            "Verfahren",
            "Bestätigte Genauigkeit",
            "Radunterstützung",
            "HC-Synchronisierung",
          ],
          pt: [
            "Dispositivo / Plataforma",
            "Método",
            "Precisão validada",
            "Suporte a ciclismo",
            "Sincronização HC",
          ],
          fr: [
            "Appareil / Plateforme",
            "Méthode",
            "Précision validée",
            "Support cyclisme",
            "Synchronisation HC",
          ],
          pl: [
            "Urządzenie / Platforma",
            "Metoda",
            "Zweryfikowana precyzja",
            "Wsparcie dla jazdy na rowerze",
            "Synchronizacja z HC",
          ],
          tr: [
            "Cihaz / Platform",
            "Yöntem",
            "Geçerli doğruluk",
            "Çikolata desteği",
            "HC senkronizasyonu",
          ],
          nl: [
            "Apparaat / Platform",
            "Methode",
            "Geverifieerde nauwkeurigheid",
            "Fietsondersteuning",
            "HC-synchronisatie",
          ],
          ja: [
            "デバイス/プラットフォーム",
            "方法",
            "検証済みの精度",
            "自転車サポート",
            "HC同期",
          ],
          ko: [
            "기기 / 플랫폼",
            "방법",
            "검증된 정확성",
            "자전거 지원",
            "HC 동기화",
          ],
        },
      rows: [
        {
            it: [
              "Orologi da corsa Garmin",
              "Algoritmo Firstbeat, GPS + HR + velocità",
              "Entro 3-5 ml/kg/min (peer-reviewed)",
              "Sì (con esigenza di potenza)",
              "Sì",
            ],
            en: [
              "Garmin running watches",
              "Firstbeat algorithm, GPS + HR + pace",
              "Within 3-5 ml/kg/min (peer-reviewed)",
              "Yes (power meter needed)",
              "Yes",
            ],
            es: [
              "Reloj de running Garmin",
              "Algoritmo Firstbeat, GPS + HR + velocidad",
              "Dentro de 3-5 ml/kg/min (revisiones peer-reviewed)",
              "Sí (se necesita un medidor de potencia)",
              "Sí",
            ],
            de: [
              "Garmin-Running-Uhr",
              "Firstbeat-Algorithmus, GPS + HR + Geschwindigkeitsmessung",
              "Innerhalb von 3-5 ml/kg/min (peer-reviewed)",
              "Ja (mit Leistungssteuerung erforderlich)",
              "Ja",
            ],
            pt: [
              "Relógios de corrida da Garmin",
              "Algoritmo Firstbeat, GPS + HR + velocidade",
              "Dentro de 3-5 ml/kg/min (revista peer-reviewed)",
              "Sim (medição de potência necessária)",
              "Sim",
            ],
            fr: [
              "Montres de running Garmin",
              "Algorithme Firstbeat, GPS + HR + vitesse",
              "Entre 3-5 ml/kg/min (revue par pair)",
              "Oui (mètre de puissance nécessaire)",
              "Oui",
            ],
            pl: [
              "Zegarki biegowo-rowerowe Garmin",
              "Algorytm Firstbeat, GPS + HR + prędkość",
              "W granicach 3-5 ml/kg/min (przegląd naukowy)",
              "Tak (potrzeba metra mocy)",
              "Tak",
            ],
            tr: [
              "Garmin koşu saatleri",
              "Firstbeat algoritması, GPS + HR + hız",
              "3-5 ml/kg/min içinde (diğer araştırmalara dayalı)",
              "Evet (güç metni gereklidir)",
              "Evet",
            ],
            nl: [
              "Garmin-runtijdsapparaten",
              "Firstbeat-algoritme, GPS + HR + pace",
              "Binnen 3-5 ml/kg/min (peer-reviewed)",
              "Ja (powermeter nodig)",
              "Ja",
            ],
            ja: [
              "Garminランニングウォッチ",
              "Firstbeatアルゴリズム、GPS + HR + ペース",
              "3-5 ml/kg/min以内（学術レビュー済み）",
              "はい（パワーメータが必要）",
              "はい",
            ],
            ko: [
              "가디언 러닝 워치",
              "Firstbeat 알고리즘, GPS + HR + 속도",
              "3-5 ml/kg/min 내외 (학술 리뷰)",
              "예 (파워 메터 필요)",
              "예",
            ],
          },
        {
            it: [
              "Polar (Vantage, Grit)",
              "Test di Performance in corsa, HR + velocità",
              "Entro 4-6 ml/kg/min",
              "Tramite test FTP",
              "Sì",
            ],
            en: [
              "Polar (Vantage, Grit)",
              "Running Performance Test, HR + pace",
              "Within 4-6 ml/kg/min",
              "Via FTP test",
              "Yes",
            ],
            es: [
              "Polar (Vantage, Grit)",
              "Prueba de rendimiento de running, HR + velocidad",
              "Dentro de 4-6 ml/kg/min",
              "A través de una prueba de FTP",
              "Sí",
            ],
            de: [
              "Polar (Vantage, Grit)",
              "Laufleistungstest, HR + Geschwindigkeitsmessung",
              "Innerhalb von 4-6 ml/kg/min",
              "Durch FTP-Test",
              "Ja",
            ],
            pt: [
              "Polar (Vantage, Grit)",
              "Teste de Desempenho em Corrida, HR + velocidade",
              "Dentro de 4-6 ml/kg/min",
              "Via teste FTP",
              "Sim",
            ],
            fr: [
              "Polar (Vantage, Grit)",
              "Test de performance de la course, HR + vitesse",
              "Entre 4-6 ml/kg/min",
              "Via le test FTP",
              "Oui",
            ],
            pl: [
              "Polar (Vantage, Grit)",
              "Test Performancji Biegowej, HR + prędkość",
              "W granicach 4-6 ml/kg/min",
              "Poprzez test FTP",
              "Tak",
            ],
            tr: [
              "Polar (Vantage, Grit)",
              "Yürüme Performans Testi, HR + hız",
              "4-6 ml/kg/min içinde",
              "FTP testi aracılığıyla",
              "Evet",
            ],
            nl: [
              "Polar (Vantage, Grit)",
              "Running Performance Test, HR + pace",
              "Binnen 4-6 ml/kg/min",
              "Via FTP-test",
              "Ja",
            ],
            ja: [
              "Polar (Vantage, Grit)",
              "ランニング性能テスト、HR + ペース",
              "4-6 ml/kg/min以内",
              "FTPテストを介して",
              "はい",
            ],
            ko: [
              "폴라 (Vantage, Grit)",
              "런닝 성능 테스트, HR + 속도",
              "4-6 ml/kg/min 내외",
              "FTP 테스트를 통해",
              "예",
            ],
          },
        {
            it: [
              "Galaxy Watch 6/7",
              "Samsung proprietario, HR + velocità",
              "Limitata recensione a peer, medesimo range",
              "Limitato",
              "Sì",
            ],
            en: [
              "Galaxy Watch 6/7",
              "Samsung proprietary, HR + pace",
              "Limited peer review, similar range",
              "Limited",
              "Yes",
            ],
            es: [
              "Reloj Galaxy Watch 6/7",
              "Propiedad de Samsung, HR + ritmo",
              "Revisión limitada entre pares, rango similar",
              "Limitado",
              "Sí",
            ],
            de: [
              "Galaxy Watch 6/7",
              "Samsung eigenverantwortlich, Herzfrequenz + Tempo",
              "Eingeschränkte Peer-Review, vergleichbare Reichweite",
              "Eingeschränkt",
              "Ja",
            ],
            pt: [
              "Galaxy Watch 6/7",
              "Samsung proprietário, HR + ritmo",
              "Revisão limitada entre pares, faixa semelhante",
              "Limitado",
              "Sim",
            ],
            fr: [
              "Galaxy Watch 6/7",
              "propriété Samsung, fréquence cardiaque + vitesse",
              "Revues limitées par pairs, même gamme",
              "Limitée",
              "Oui",
            ],
            pl: [
              "Samsung Galaxy Watch 6/7",
              "Zwłaszcza Samsung, HR + prędkość",
              "Ograniczona recenzja tożsamościowej, podobny zakres",
              "Ograniczone",
              "Tak",
            ],
            tr: [
              "Galaxy Watch 6/7",
              "Samsung özelleştirilmiş, HR + hız",
              "Sınırlı arkadaşı incelemesi, benzer aralık",
              "Sınırlı",
              "Evet",
            ],
            nl: [
              "Galaxy Watch 6/7",
              "Samsung-eigen, HR + tempo",
              "Beperkte medische beoordeling, vergelijkbare bereik",
              "Beperkt",
              "Ja",
            ],
            ja: [
              "ギャラクシーウォッチ6/7",
              "サムスンの独自技術、心拍数＋ペース",
              "限定的な同僚レビュー、類似範囲",
              "限定的",
              "はい",
            ],
            ko: [
              "Galaxy Watch 6/7",
              "Samsung proprietary, HR + pace",
              "Limited peer review, similar range",
              "Limited",
              "Yes",
            ],
          },
        {
            it: [
              "Apple Watch (iOS)",
              "Proprietario di Apple, HR + velocità",
              "Dentro 4-5 ml/kg/min (studio interno di Apple)",
              "No",
              "No (solo Apple Health)",
            ],
            en: [
              "Apple Watch (iOS)",
              "Apple proprietary, HR + pace",
              "Within 4-5 ml/kg/min (Apple's own study)",
              "No",
              "No (Apple Health only)",
            ],
            es: [
              "Reloj Apple (iOS)",
              "Propiedad de Apple, HR + ritmo",
              "Dentro del rango de 4-5 ml/kg/min (estudio propio de Apple)",
              "No",
              "No (solo Apple Health)",
            ],
            de: [
              "Apple Watch (iOS)",
              "Apple eigenverantwortlich, Herzfrequenz + Tempo",
              "Innerhalb von 4-5 ml/kg/min (eigenes Studium von Apple)",
              "Nein",
              "Nein (nur Apple Health)",
            ],
            pt: [
              "Apple Watch (iOS)",
              "Propriedade da Apple, HR + ritmo",
              "Dentro de 4-5 ml/kg/min (estudo próprio da Apple)",
              "Não",
              "Não (apenas Apple Health)",
            ],
            fr: [
              "Apple Watch (iOS)",
              "propriété Apple, fréquence cardiaque + vitesse",
              "Dans l'intervalle de 4-5 ml/kg/min (étude propre d'Apple)",
              "Non",
              "Non (seulement Apple Health)",
            ],
            pl: [
              "Samsung Galaxy Watch (iOS)",
              "Zwłaszcza Apple, HR + prędkość",
              "W zakresie 4-5 ml/kg/min (badanie własnego Apple)",
              "Nie",
              "Nie (tylko Apple Health)",
            ],
            tr: [
              "Apple Watch (iOS)",
              "Apple özelleştirilmiş, HR + hız",
              "4-5 ml/kg/min arasında (Apple kendi çalışması)",
              "Hayır",
              "Hayır (sadece Apple Health)",
            ],
            nl: [
              "Apple Watch (iOS)",
              "Apple-eigen, HR + tempo",
              "Binnen 4-5 ml/kg/min (Apple's eigen onderzoek)",
              "Nee",
              "Nee (alleen Apple Health)",
            ],
            ja: [
              "アبلウォッチ（iOS）",
              "アプルの独自技術、心拍数＋ペース",
              "4-5 ml/kg/min以内（アプルの OWN の研究）",
              "いいえ",
              "いいえ（アプルヘルスのみ）",
            ],
            ko: [
              "Apple Watch (iOS)",
              "Apple proprietary, HR + pace",
              "Within 4-5 ml/kg/min (Apple's own study)",
              "No",
              "No (Apple Health only)",
            ],
          },
        {
            it: [
              "Oura Ring",
              "Non stima il VO2 Max",
              "N/D",
              "N/D",
              "N/D",
            ],
            en: [
              "Oura Ring",
              "Does not estimate VO2 Max",
              "N/A",
              "N/A",
              "N/A",
            ],
            es: [
              "Anillo Oura",
              "No estima el VO2 Max",
              "N/A",
              "N/A",
              "N/A",
            ],
            de: [
              "Oura Ring",
              "Schätzt das VO2 Max nicht",
              "N/A",
              "N/A",
              "N/A",
            ],
            pt: [
              "Oura Ring",
              "Não estima o VO2 Max",
              "N/A",
              "N/A",
              "N/A",
            ],
            fr: [
              "Oura Ring",
              "Ne n'est pas une estimation du VO2 Max",
              "N/A",
              "N/A",
              "N/A",
            ],
            pl: [
              "Oura Ring",
              "Nie szacuje VO2 Max",
              "N/A",
              "N/A",
              "N/A",
            ],
            tr: [
              "Oura Çenglesi",
              "VO2 Max tahmini yapmaz",
              "Yok",
              "Yok",
              "Yok",
            ],
            nl: [
              "Oura Ring",
              "Schat VO2 Max niet",
              "N/B",
              "N/B",
              "N/B",
            ],
            ja: [
              "オーラリング",
              "VO2 Maxの推定は行わない",
              "N/A",
              "N/A",
              "N/A",
            ],
            ko: [
              "Oura Ring",
              "Does not estimate VO2 Max",
              "N/A",
              "N/A",
              "N/A",
            ],
          },
      ],
    },
    {
      type: "heading",
      level: 2,
      text: {
          it: "Quello che il numero effettivamente significa",
          en: "What the number actually means",
          es: "Lo que realmente significa el número",
          de: "Was der Wert tatsächlich bedeutet",
          pt: "O que o número realmente significa",
          fr: "Ce que le nombre signifie réellement",
          pl: "Co ta liczba na prawdę oznacza",
          tr: "Sayı asıl ne anlama geldiğini",
          nl: "Wat het getal in feite betekent",
          ja: "その数字が意味するのは何か",
          ko: "What the number actually means",
        },
    },
    {
      type: "list",
      items: {
          it: [
            "**Under 35 ml/kg/min (men) / under 30 (women):** di livello fisico inferiore alla media per un adulto sedentario. Un addestramento aerobico regolare per 8-12 settimane migliorerà questo fino a 5-10%.",
            "**35-45 ml/kg/min (men) / 30-40 (women):** livello fisico medio-buono. Gli corredatori regolari e le persone attive si trovano solitamente in questa fascia.",
            "**45-55 ml/kg/min (uomini) / 40-50 (donne):** sopra la media. Tipico di corredori e ciclisti dilettanti specializzati.",
            "**Sopra i 55 ml/kg/min (uomini) / sopra i 50 (donne):** territorio degli elite. Gli marathoner professionisti sono solitamente sopra i 65 anni (uomini) e sopra i 60 anni (donne).",
          ],
          en: [
            "**Under 35 ml/kg/min (men) / under 30 (women):** below average fitness for a sedentary adult. Consistent aerobic training for 8-12 weeks will typically improve this by 5-10%.",
            "**35-45 ml/kg/min (men) / 30-40 (women):** average to good fitness. Regular runners and active people typically land here.",
            "**45-55 ml/kg/min (men) / 40-50 (women):** above average. Typical of dedicated amateur runners and cyclists.",
            "**Above 55 ml/kg/min (men) / above 50 (women):** elite territory. Elite marathon runners are typically 65+ (men) and 60+ (women).",
          ],
          es: [
            "**Menos de 35 ml/kg/min (hombres) / menos de 30 (mujeres):** por debajo del promedio en términos de condición física para adultos sedentarios. Un entrenamiento aeróbico consistente durante 8-12 semanas generalmente mejorará esto en un 5-10%.",
            "**35-45 ml/kg/min (hombres) / 30-40 (mujeres):** condición física promedio a buena. Los corredores regulares y las personas activas suelen encontrarse en este rango.",
            "**45-55 ml/kg/min (hombres) / 40-50 (mujeres):** por encima del promedio. Es típico de corredores y ciclistas aficionados dedicados.",
            "**Más de 55 ml/kg/min (hombres) / más de 50 (mujeres):** territorio de elite. Los maratonianos elites suelen tener valores de 65+ (hombres) y 60+ (mujeres).",
          ],
          de: [
            "**Unter 35 ml/kg/min (Männer) / unter 30 (Frauen):** Untermittleres Fitnessniveau für einen sedentären Erwachsenen. Konsistente aerobes Training über 8-12 Wochen verbessert dies typischerweise um 5-10%.",
            "**35-45 ml/kg/min (Männer) / 30-40 (Frauen):** Durchschnittliches bis gutes Fitnessniveau. Regelmäßige Läufer und aktive Personen landen in dieser Kategorie.",
            "**45-55 ml/kg/min (männer) / 40-50 (frauen):** überdurchschnittlich. Typisch für verpflichtete Amateurräderfahrer und Läufer.",
            "**Über 55 ml/kg/min (männer) / über 50 (frauen):** Elite-Territorium. Elite-Marathonläufer sind typischerweise 65+ (männer) und 60+ (frauen).",
          ],
          pt: [
            "**Abaixo de 35 ml/kg/min (homens) / abaixo de 30 (mulheres):** abaixo da média em termos de condicionamento físico para adultos sedentários. Treinamento aeróbico consistente por 8 a 12 semanas geralmente melhora isso em 5-10%.",
            "**35-45 ml/kg/min (homens) / 30-40 (mulheres):** condicionamento físico médio a bom. Corredores regulares e pessoas ativas costumam se encaixar nessa categoria.",
            "**45-55 ml/kg/min (homens) / 40-50 (mulheres):** acima da média. Comum entre corredores e ciclistas amadores dedicados.",
            "**Acima de 55 ml/kg/min (homens) / acima de 50 (mulheres):** território elite. Corredores maratonenses elites geralmente são 65+ (homens) e 60+ (mulheres).",
          ],
          fr: [
            "**En dessous de 35 ml/kg/min (hommes) / en dessous de 30 (femmes):** niveau de condition physique inférieur à la moyenne pour un adulte sédentaire. Un entraînement aérobique régulier de 8 à 12 semaines améliore généralement cela de 5 à 10 %.",
            "**35-45 ml/kg/min (hommes) / 30-40 (femmes):** niveau de condition physique moyen à bon. Les courir et les personnes actives se trouvent généralement dans cette catégorie.",
            "**45-55 ml/kg/min (hommes) / 40-50 (femmes):** au-dessus de la moyenne. Typique des amateurs dédiés à la course et au cyclisme.",
            "**Plus de 55 ml/kg/min (hommes) / plus de 50 (femmes):** territoire élite. Les marathoniens professionnels sont généralement supérieurs à 65 ans (hommes) et 60 ans (femmes).",
          ],
          pl: [
            "**Poniżej 35 ml/kg/min (mężczyźni) / poniżej 30 (kobiety):** poniższy odśrodkowy poziom fitness dla dorosłego, który jest nieaktywny. Regularne treningi aerobiczne przez 8-12 tygodni zazwyczaj poprawią to o 5-10%.",
            "**35-45 ml/kg/min (mężczyźni) / 30-40 (kobiety):** średni do dobry poziom fitness. Regularni biegacze i aktywi ludzie zazwyczaj znajdują się w tej kategorii.",
            "**45-55 ml/kg/min (mężczyźni) / 40-50 (kobiety):** powyżej sredniokompetencyjne. Cechą typową są zatytułowani amatorzy biegacze i cyklisty.",
            "**Powyżej 55 ml/kg/min (mężczyźni) / powyżej 50 (kobiety):** teren mistrzostw. Mistrzowie maratonów są zwykle 65+ (mężczyźni) i 60+ (kobiety).",
          ],
          tr: [
            "**35 ml/kg/min altında (erkekler) / 30 ml/kg/min altında (kadınlar):** sedentary bir yetişkin için ortalamadan düşük performans. 8-12 hafta boyunca tutarlı aerobik egzersiz genellikle bu durumu %5-%10 daha iyi yapabilir.",
            "**35-45 ml/kg/min (erkekler) / 30-40 (kadınlar):** orta seviye ile iyi performans. Genel olarak düzenli koşucular ve aktif kişiler bu aralığa düşerler.",
            "**45-55 ml/kg/min (erkek) / 40-50 (kadın):** üst orta seviye. Bu, serbest zaman koşucuları ve bisikletçilerin genellikle normal durumudur.",
            "**55 ml/kg/min (erkek) üzerinde / 50 (kadın) üzerinde:** el altı seviyesi. El altı maraton koşucuları genellikle erkekler için 65+ ve kadınlar için 60+ seviyedir.",
          ],
          nl: [
            "**Onder 35 ml/kg/min (mannen) / onder 30 (vrouwen):** beneden gemiddelde fitness voor een zittend volwassene. Consistente aerober training van 8-12 weken verbeterd dit meestal met 5-10%.",
            "**35-45 ml/kg/min (mannen) / 30-40 (vrouwen):** gemiddelde tot goede fitness. Reguliere renners en actieve mensen vallen hier meestal binnen.",
            "**45-55 ml/kg/min (mannen) / 40-50 (vrouwen):** boven gemiddeld. Typisch voor geïndereerde amateurloper en -fietsers.",
            "**Boven de 55 ml/kg/min (mannen) / boven de 50 (vrouwen):** elite gebied. Elite marathonloper zijn meestal 65+ (mannen) en 60+ (vrouwen).",
          ],
          ja: [
            "**35 ml/kg/min未満（男性）/30 ml/kg/min未満（女性）:** 側坐成人の平均的なフィットネス以下。8-12週間の継続的な有酸素トレーニングで、この数値は通常5-10%向上します。",
            "**35-45 ml/kg/min（男性）/30-40 ml/kg/min（女性）:** 平均から良いフィットネス。定期的なランナーとアクティブな人々がここにいます。",
            "**45-55 ml/kg/min (men) / 40-50 (women):** 平均以上。専門的なアマチュアランナーと自転車競技者の典型です。",
            "**55 ml/kg/min（men）以上 / 50（women）以上:** 最高の域。プロのマラソン選手は男性で65歳以上、女性で60歳以上が一般的です。",
          ],
          ko: [
            "**Under 35 ml/kg/min (men) / under 30 (women):** below average fitness for a sedentary adult. Consistent aerobic training for 8-12 weeks will typically improve this by 5-10%.",
            "**35-45 ml/kg/min (men) / 30-40 (women):** average to good fitness. Regular runners and active people typically land here.",
            "**45-55 ml/kg/min (남성) / 40-50 (여성):** 평균 이상. 전문 아마추어 러너와 사이클리스트에게 흔합니다.",
            "**55 ml/kg/min (남성) 초과 / 50 (여성) 초과:** 엘ITE 영역입니다. 엘ITE 마라톤 선수들은 대체로 남성 65+(여성 60+) 이상입니다.",
          ],
        },
    },
    {
      type: "callout",
      variant: "tip",
      title: {
          it: "Come migliorare l'accuratezza della stima del VO2 Max del tuo dispositivo portatile",
          en: "How to improve your wearable's VO2 Max estimate accuracy",
          es: "Cómo mejorar la precisión del estimado de VO2 Max en tu dispositivo portátil",
          de: "Wie Sie die Genauigkeit der VO2 Max-Schätzung Ihres Wearables verbessern können",
          pt: "Como melhorar a precisão da estimativa de VO2 Max do seu wearable",
          fr: "Comment améliorer l'estimation de votre VO2 Max sur vos appareils connectés",
          pl: "Jak poprawić dokładność estymacji VO2 Max twojej przestrzeni na zegarku?",
          tr: "Nasıl Wearable'nizin VO2 Max tahmini doğruluğunu artıracaksınız",
          nl: "Hoe je de nauwkeurigheid van je wearable's VO2 Max schatting kunt verbeteren",
          ja: "ウェアラブルのVO2 Max推定精度を向上する方法",
          ko: "웨어러블의 VO2 Max 추정 정확도 향상을 위한 방법",
        },
      body: {
          it: "Corri almeno due volte alla settimana con GPS e tasso di battito cardiaco abilitati. Include almeno una corsa dove spingi un sostenuto sforzo per 20 minuti. Evita di controllare lo schermo del tuo orologio durante l'efforto (influenza la puntuazione e quindi i dati). Dopo 4-6 settimane, l'accuratezza si stabilizza.",
          en: "Run at least twice a week with GPS and heart rate enabled. Include at least one run where you push a sustained effort for 20 minutes. Avoid checking your watch display during the effort (it affects pacing and therefore the data). After 4-6 weeks, the estimate stabilizes.",
          es: "Corre al menos dos veces por semana con GPS y ritmo cardíaco activados. Incluye una sesión donde hagas un esfuerzo sostenido durante 20 minutos. Evita comprobar la pantalla de tu reloj durante el esfuerzo (afecta a la puesta en marcha y por lo tanto a los datos). Tras 4-6 semanas, el estimado se estabiliza.",
          de: "Laufen Sie mindestens zweimal pro Woche mit GPS und Herzfrequenzmessung aktiviert. Fügen Sie mindestens eine Strecke hinzu, bei der Sie einen anhaltenden Anstrengungsversuch für 20 Minuten durchführen. Überprüfen Sie während des Anstrengungsprozesses nicht Ihre Armbanduhranzeige (es beeinflusst die Pacing und somit die Daten). Nach 4-6 Wochen stabilisiert sich die Schätzung.",
          pt: "Corra pelo menos duas vezes por semana com GPS e frequência cardíaca ativado. Inclua uma corrida onde você empurre um esforço sustentado por 20 minutos. Evite verificar a tela do relógio durante o esforço (afeta o ritmo e, portanto, os dados). Após 4-6 semanas, a estimativa se estabiliza.",
          fr: "Faites au moins deux courses par semaine avec GPS et le taux cardiaque activé. Incluez une course où vous faites un effort soutenu pendant 20 minutes. Évitez de vérifier l'affichage de votre montre pendant l'effort (ça affecte la régulation et donc les données). Après 4 à 6 semaines, l'estimation se stabilise.",
          pl: "Biegaj co najmniej dwa razy w tygodniu z GPS i czujnikiem pulsowym włączonymi. Włączaj co najmniej jedną biegadnię, gdzie naciskasz na utrzymywany wysiłek przez 20 minut. Unikaj sprawdzania wyświetlacza zegarka podczas wysiłku (wpływa to na tempo i zatem na dane). Po 4-6 tygodniach estymacja stabilizuje się.",
          tr: "GPS ve kalp hızı izleyici açık olan en az iki kez haftada koş. En az bir koşuda, 20 dakika süren bir sürekli çaba dahil et. Çabasız sırasında saat ekranınızı kontrol etmeyin (bu, ilerleme ve bu nedenle veriye etkiler). 4-6 hafta sonra tahmin sabitlenir.",
          nl: "Loop ten minste twee keer per week met GPS en hartslag aan. Voeg tenminste één loop toe waarin je een gedurende 20 minuten houdende inspanning doet. Controleer niet tijdens het inspannen de weergave van je horloge (het beïnvloedt de tempo's en daarmee de data). Na 4-6 weken stabiliseert de schatting.",
          ja: "週に少なくとも2回、GPSと心拍数を有効にして走ります。少なくとも1回は20分間の持続的な努力を含めます。努力中にウォッチディスプレイをチェックしないでください（これはペースに影響し、データも変わります）。4-6週間後には推定値が安定します。",
          ko: "주간에 최소 두 번씩 GPS와 심박수 모니터링을 활성화한 상태에서 달리세요. 최소 한 번은 지속적인 노력을 20분 동안 하는 런을 포함하세요. 노력 중 시계 표시판을 확인하지 마세요(이것은 페이싱에 영향을 미치고 따라서 데이터를 변화시킵니다). 4-6주 후 추정값이 안정화됩니다.",
        },
    },
    {
      type: "heading",
      level: 2,
      text: {
          it: "Seguire il VO2 Max nel tempo su diversi dispositivi",
          en: "Tracking VO2 Max over time across devices",
          es: "Seguimiento del VO2 Max a lo largo del tiempo entre dispositivos",
          de: "VO2 Max-Schätzungen über die Zeit auf verschiedenen Geräten verfolgen",
          pt: "Rastreando VO2 Max ao longo do tempo em vários dispositivos",
          fr: "Suivez vos estimations de VO2 Max sur plusieurs périodes",
          pl: "Śledzenie VO2 Max w czasie nad wieloma urządzeniami",
          tr: "Zaman içinde cihazlar arasında VO2 Max'i izleme",
          nl: "Vo2 Max over de tijd bij meerdere apparaten volgen",
          ja: "デバイスごとに時間経過とともにVO2 Maxの追跡",
          ko: "장시간에 걸친 VO2 Max 추적",
        },
    },
    {
      type: "paragraph",
      text: {
          it: "Garmin e Polar scrivono le stime del VO2 Max in Health Connect sotto il tipo di dati 'Vo2Max'. Questo significa che la tua storia non è bloccata all'interno dell'app della marca. Se passi da un dispositivo Garmin a uno Polar, le tue stime precedenti sono ancora accessibili attraverso app compatibili con Health Connect. I numeri assoluti differiscono lievemente tra piattaforme perché gli algoritmi sono diversi, ma la tendenza sarà paragonabile.",
          en: "Garmin and Polar both write VO2 Max estimates to Health Connect under the 'Vo2Max' data type. This means your history is not locked inside the manufacturer's app. If you switch from a Garmin to a Polar device, your previous estimates are still accessible through Health Connect-compatible apps. The absolute numbers will differ slightly between platforms because the algorithms are different, but the trend will be comparable.",
          es: "Garmin y Polar escriben los estimados de VO2 Max en Health Connect bajo el tipo de datos 'Vo2Max'. Esto significa que tu historial no está atrapado dentro de la aplicación del fabricante. Si pasas de un dispositivo Garmin a uno Polar, tus estimaciones anteriores siguen siendo accesibles a través de aplicaciones compatibles con Health Connect. Los números absolutos variarán ligeramente entre las plataformas porque los algoritmos son diferentes, pero la tendencia será comparable.",
          de: "Garmin und Polar speichern beide VO2 Max-Schätzungen in Health Connect unter der Datentypenbezeichnung 'Vo2Max'. Dies bedeutet, dass Ihre Geschichte nicht im Eigentümer-App-Framework eingeschlossen ist. Wenn Sie von einem Garmin auf ein Polar-Gerät wechseln, sind Ihre vorherigen Schätzungen über Health Connect-kompatible Apps weiterhin zugänglich. Die absoluten Zahlen unterscheiden sich leicht zwischen Plattformen, da die Algorithmen unterschiedlich sind, aber der Trend ist vergleichbar.",
          pt: "Garmin e Polar escrevem as estimativas de VO2 Max no Health Connect sob o tipo de dados 'Vo2Max'. Isso significa que sua história não está presa dentro da aplicação do fabricante. Se você trocar de um dispositivo Garmin para um Polar, suas estimativas anteriores ainda estão acessíveis por meio de apps compatíveis com Health Connect. Os números absolutos variam ligeiramente entre as plataformas porque os algoritmos são diferentes, mas a tendência será comparável.",
          fr: "Garmin et Polar écrivent toutes deux leurs estimations de VO2 Max dans Health Connect sous le type de données 'Vo2Max'. Cela signifie que votre historique n'est pas enfermé dans l'application du fabricant. Si vous passez d'un Garmin à un appareil Polar, vos estimations précédentes sont toujours accessibles via des applications compatibles Health Connect. Les chiffres absolus varient légèrement entre les plateformes car les algorithmes diffèrent, mais la tendance sera comparable.",
          pl: "Garmin i Polar zapisują estymacje VO2 Max do Health Connect jako typ danych 'Vo2Max'. To oznacza, że historia nie jest zamknięta w aplikacji producenta. Jeśli przejdziesz od urządzenia Garmin do Polar, poprzednie estymacje nadal są dostępne poprzez aplikacje kompatybilne z Health Connect. Absolutne liczby mogą się różnić lekko między platformami, ponieważ algorytmy są różne, ale trend będzie porównywalny.",
          tr: "Garmin ve Polar hem de Health Connect'te 'Vo2Max' veri tipinde VO2 Max tahmini yazıyor. Bu, tarihinizi üreticinin uygulaması dışına kilitli olmaz demektir. Garmin'dan bir cihaza Polar'a geçerseniz, önceki tahminler Health Connect uyumlu uygulamalardan hala erişilebilir. Mutlak sayılar farklı platformlardaki algoritma farklı olduğu için biraz farklı olabilir, ancak eğilim benzer olacaktır.",
          nl: "Garmin en Polar schrijven allebei VO2 Max schattingen naar Health Connect onder het 'Vo2Max' gegevenstype. Dit betekent dat je geschiedenis niet opgesloten is in de fabrikantse app. Als je van een Garmin naar een Polar-apparaat overgaat, zijn je vorige schattingen nog steeds toegankelijk via Health Connect-compatibele apps. De absolute cijfers verschillen licht omdat de algoritmen verschillen, maar het trendpatroon is vergelijkbaar.",
          ja: "GarminとPolarはともに、VO2 Max推定値をHealth Connectの「Vo2Max」データタイプとして記録します。これにより、製造元アプリ内でのみ保存される履歴がロックされません。GarminからPolarのデバイスに切り替えた場合でも、Health Connect互換アプリを通じて以前の推定値はアクセスできます。絶対的な数字はプラットフォームによって異なるためわずかに異なりますが、トレンドは比較可能です。",
          ko: "가민과 파올리는 가든 'Vo2Max' 데이터 타입으로 헥스 콘nect에 VO2 Max 추정값을 기록합니다. 이것은 제조사 앱 내부에 잠겨있는 역사가 아니라, 가든에서 파올리로 장치를 변경하더라도 헥스 콘nect 호환 앱을 통해 이전 추정값이 여전히 접근 가능합니다. 절대 숫자는 플랫폼마다 약간 다릅니다(알고리즘이 다르기 때문), 그러나 추세는 비슷합니다.",
        },
    },
    {
      type: "cta",
      title: {
          it: "Segui la tua tendenza VO2 Max su diversi dispositivi",
          en: "Track your VO2 Max trend across devices",
          es: "Seguir tu tendencia de VO2 Max entre dispositivos",
          de: "Ihren VO2 Max-Trend auf verschiedenen Geräten verfolgen",
          pt: "Rastreie sua tendência de VO2 Max em vários dispositivos",
          fr: "Suivez votre tendance de VO2 Max sur plusieurs périodes",
          pl: "Śledź trend VO2 Max na różnych urządzeniach",
          tr: "Cihazların arası VO2 Max trendini izleme",
          nl: "Volg je Vo2 Max-trend over meerdere apparaten",
          ja: "デバイス間のVO2 Maxトレンドを追跡",
          ko: "장치 간의 VO2 Max 추세를 추적해보세요",
        },
      body: {
          it: "FitMesh legge la storia del VO2 Max da Health Connect e mostra il tuo progresso nei mesi, indipendentemente dal dispositivo che l'ha registrata.",
          en: "FitMesh reads VO2 Max history from Health Connect and shows your progress over months, regardless of which device recorded it.",
          es: "FitMesh lee el historial de VO2 Max desde Health Connect y muestra tu progreso a lo largo de los meses, sin importar qué dispositivo lo registró.",
          de: "FitMesh liest die VO2 Max-Geschichte aus Health Connect ein und zeigt Ihren Fortschritt über Monate hinweg an, unabhängig davon, welches Gerät die Messung durchgeführt hat.",
          pt: "FitMesh lê a história de VO2 Max do Health Connect e mostra seu progresso ao longo dos meses, independentemente do dispositivo que registrou.",
          fr: "FitMesh lit l'historique de vos estimations de VO2 Max depuis Health Connect et montre votre progression au fil des mois, peu importe quel appareil l'a enregistrée.",
          pl: "FitMesh czyta historię VO2 Max z Health Connect i pokazuje Twoje postępy w ciągu miesięcy, niezależnie od urządzenia, które je zarejestrowało.",
          tr: "FitMesh Health Connect'ten VO2 Max tarihçisini okur ve ayıncılarda hangi cihazda kaydedildi olmaksızın aylar boyunca ilerlemenizi gösterir.",
          nl: "FitMesh leest Vo2 Max geschiedenis uit Health Connect en toont je vooruitgang over maanden, ongeacht welk apparaat het heeft gemeten.",
          ja: "FitMeshはHealth ConnectからVO2 Max履歴を読み取り、どのデバイスが記録した場合でも数ヶ月間の進歩を表示します。",
          ko: "FitMesh는 헥스 콘nect에서 VO2 Max 역사 데이터를 읽어 들여 몇 개월 동안 어떤 장치가 기록했든 관계없이 진행 상황을 보여줍니다.",
        },
      ctaLabel: {
          it: "Prova FitMesh gratuitamente",
          en: "Try FitMesh free",
          es: "Prueba FitMesh gratis",
          de: "Versuchen Sie FitMesh kostenlos",
          pt: "Experimente o FitMesh gratuitamente",
          fr: "Essayez FitMesh gratuitement",
          pl: "Spróbuj FitMesh za darmo",
          tr: "Ücretsiz olarak FitMesh'i deneyin",
          nl: "Probeer FitMesh gratis",
          ja: "無料で試す",
          ko: "무료로 FitMesh 시도해보기",
        },
      ctaHref: {
          it: "/beta",
          en: "/beta",
          es: "/beta",
          de: "/beta",
          pt: "/beta",
          fr: "/beta",
          pl: "/beta",
          tr: "/beta",
          nl: "/beta",
          ja: "/beta",
          ko: "/beta",
        },
    },
  ],
  faq: [
    {
      q: {
          it: "Quanto è accurato il VO2 Max di Garmin rispetto a un test in laboratorio?",
          en: "How accurate is Garmin VO2 Max compared to a lab test?",
          es: "¿Cuán precisa es el VO2 Max de Garmin en comparación con un test en laboratorio?",
          de: "Wie genau ist Garmin VO2 Max verglichen mit einer Labortestung?",
          pt: "Quão preciso é a VO2 Max da Garmin em comparação com um teste laboratorial?",
          fr: "Quelle est la précision de Garmin VO2 Max par rapport à un test en laboratoire ?",
          pl: "Jak dokładne jest estymacja VO2 Max Garmin w porównaniu do testu laboratorium?",
          tr: "Garmin VO2 Max'un laboratuvar testine kıyasla ne kadar doğru?",
          nl: "Hoe nauwkeurig is Garmin VO2 Max vergeleken met een labo-test?",
          ja: "GarminのVO2 Maxはラボテストと比べてどれほど正確ですか？",
          ko: "가민의 VO2 Max는 실험실 테스트와 얼마나 정확한가요?",
        },
      a: {
          it: "L'algoritmo Firstbeat di Garmin è stato validato in studi indipendenti. Per corredori allenati che usano GPS in modo costante, l'accuratezza è solitamente entro 3-5 ml/kg/min rispetto a un test massimale di assorbimento d'ossigeno in laboratorio. Per utenti casual o quelli che fanno principalmente esercizi indoor, la margine è più ampio.",
          en: "Garmin's Firstbeat algorithm has been validated in multiple independent studies. For trained runners who use GPS consistently, accuracy is typically within 3-5 ml/kg/min of a laboratory maximal oxygen uptake test. For casual users or those who mostly do indoor workouts, the margin is wider.",
          es: "El algoritmo Firstbeat de Garmin ha sido validado en múltiples estudios independientes. Para corredores entrenados que usan GPS de manera consistente, la precisión suele estar dentro de 3-5 ml/kg/min de un test de absorción máxima de oxígeno en laboratorio. Para usuarios casuales o aquellos que realizan principalmente ejercicios indoor, el margen es mayor.",
          de: "Garmins Firstbeat-Algorithmus wurde in mehreren unabhängigen Studien validiert. Für trainierte Läufer, die GPS konsistent verwenden, liegt die Genauigkeit typischerweise innerhalb von 3-5 ml/kg/min eines laboratoriumsbasierenden maximalen Sauerstoffaufnahmestests. Für Anfänger oder Menschen, die hauptsächlich innen arbeiten, ist der Abstand breiter.",
          pt: "O algoritmo Firstbeat da Garmin foi validado em múltiplos estudos independentes. Para corredores treinados que usam GPS consistentemente, a precisão é geralmente de 3-5 ml/kg/min em comparação com um teste laboratorial de absorção máxima de oxigênio. Para usuários casuais ou aqueles que fazem principalmente exercícios internos, o intervalo é maior.",
          fr: "L'algorithme Firstbeat de Garmin a été validé dans plusieurs études indépendantes. Pour des coureurs entraînés qui utilisent le GPS de manière constante, la précision est généralement d'environ 3-5 ml/kg/min par rapport à un test maximal d'absorption d'oxygène en laboratoire. Pour les utilisateurs occasionnels ou ceux qui font principalement des entraînements indoor, l'écart est plus large.",
          pl: "Algorytm Firstbeat Garminu został zweryfikowany w wielu niezależnych badaniach. Dla zatytułowanych biegaczy, którzy używają GPS regularnie, dokładność jest zwykle w granicach 3-5 ml/kg/min od testu maksymalnego zużycia tlenu w laboratorium. Dla użytkowników niezależnych lub tych, którzy głównie wykonują treningi wewnątrzdomowe, margines może być szerzej.",
          tr: "Garmin'ın Firstbeat algoritması birçok bağımsız çalışmanın doğrulanmış hale gelmiş. Sınırlı koşullarda ve GPS'i sürekli olarak kullanan eğitimli koşucular için, laboratuvar maksimum oksijen alma testine kıyasla genellikle 3-5 ml/kg/min içinde doğrudur. Kasıtlı kullanıcılara veya sadece içeriğe odaklanmış çalışanlara yönelik olan, bu aralığı genişletir.",
          nl: "Garmin's Firstbeat-algoritme is gevalideerd in meerdere onafhankelijke studies. Voor getrainde loper die GPS consistent gebruiken, is de nauwkeurigheid typisch binnen 3-5 ml/kg/min van een laboratorium maximal oxygen uptake test. Voor casual users of die voornamelijk indoor workouts doen, is het marginale verschil groter.",
          ja: "GarminのFirstbeatアルゴリズムは複数の独立した研究で検証されています。トレーニングされたランナーがGPSを一貫して使用する場合、精度はラボ最大酸素摂取量テストと3-5 ml/kg/min以内です。 Casualユーザーまたは主に室内でのワークアウトをする人では、その差は広がります。",
          ko: "가민의 Firstbeat 알고리즘은 여러 독립 연구에서 검증되었습니다. 트레이닝 러너가 GPS를 일관되게 사용하는 경우, 정확도는 실험실 최대 산소 소비량 테스트와 비교해 3-5 ml/kg/min 내외입니다. 주말 운동이나 실내 운동을 주로 하는 비트레이닝 유저의 경우에는 이 범위가 더 넓습니다.",
        },
    },
    {
      q: {
          it: "Perché il mio stima del VO2 Max scende nel caldo estivo?",
          en: "Why does my VO2 Max estimate drop in summer heat?",
          es: "¿Por qué mi estimado de VO2 Max baja en verano con calor?",
          de: "Warum fällt meine VO2 Max-Schätzung im Sommerhitze ab?",
          pt: "Por que minha estimativa de VO2 Max diminui no calor do verão?",
          fr: "Pourquoi mon estimation de VO2 Max baisse-elle en été dans une chaleur intense ?",
          pl: "Dlaczego moja estymacja VO2 Max spada w ciepłym letnim klimacie?",
          tr: "Neden yazgısının sıcak bir hava koşulu sırasında VO2 Max tahmini düşer?",
          nl: "Waarom neemt mijn VO2 Max schatting af in zomerhitte?",
          ja: "なぜ夏場はVO2 Maxの推定値が下がるのですか？",
          ko: "왜 여름에는 VO2 Max 추정값이 떨어지나요?",
        },
      a: {
          it: "Il calore aumenta il tasso di battito cardiaco a qualsiasi velocità data, che fa sì che l'algoritmo pensi che tu stai lavorando più duramente rispetto alla tua velocità. Questo sembra una diminuzione della fitness. Garmin ha un'opzione per l'acclimatazione al calore che compensa parzialmente questo effetto. L'algoritmo di Polar è simile a quello affetto. È normale e non è una reale diminuzione della fitness.",
          en: "Heat increases heart rate at any given pace, which makes the algorithm think you are working harder relative to your speed. This looks like a fitness decline. Garmin has a heat acclimatization feature that partially compensates for this. Polar's algorithm is similarly affected. It is normal and not a real fitness drop.",
          es: "El calor aumenta la frecuencia cardíaca a cualquier ritmo dado, lo cual hace que el algoritmo piense que estás trabajando más duro en relación a tu velocidad. Esto se ve como una disminución de la condición física. Garmin tiene una función de acostumbramiento al calor que compensa parcialmente esto. El algoritmo de Polar está igualmente afectado. Es normal y no es una verdadera pérdida de condición.",
          de: "Hitze erhöht den Herzschlag bei jedem gegebenen Tempo, was den Algorithmus dazu bringt zu glauben, dass Sie in Bezug auf Ihre Geschwindigkeit härter arbeiten. Dies sieht wie eine Fitnessabnahme aus. Garmin hat ein Wärmetastrimulationsfeature, das diesen Effekt teilweise kompensiert. Die Algorithmen von Polar sind vergleichbar beeinträchtigt. Es ist normal und kein echtes Fitnessnachlassen.",
          pt: "O calor aumenta a frequência cardíaca em qualquer velocidade dada, o que faz o algoritmo pensar que você está trabalhando mais duro em relação à sua velocidade. Isso parece uma declínio de condicionamento físico. A Garmin tem um recurso de acclimatação ao calor que compensa parcialmente isso. O algoritmo da Polar é afetado de forma semelhante. É normal e não representa uma verdadeira queda no condicionamento físico.",
          fr: "La chaleur augmente le taux cardiaque à tout rythme donné, ce qui fait que l'algorithme pense que vous travaillez plus fort par rapport à votre vitesse. Cela donne l'impression d'une déclin de la forme physique. Garmin a une fonction d'acclimatation thermique qui partiellement compensent cela. L'algorithme de Polar est également affecté de manière similaire. C'est normal et ne représente pas un véritable déclin de forme.",
          pl: "Ciepło zwiększa częstość serca na dany bieg, co sprawia, że algorytm myśli, że pracujesz bardziej w stosunku do prędkości. To wygląda jak spadek fitnessu. Garmin ma funkcję akclimatyzacji do ciepła, która częściowo kompensuje to. Algorytm Polar jest podobnie zarażony. Jest to normalne i nie oznacza rzeczywistego spadku fitnessu.",
          tr: "Sıcaklık her verimli hızda kalp hızını artırır, bu yüzden algoritma hızınızla göreli olarak daha zor çalıştığınız gibi düşünür. Bu, performans azalmasına benzer bir görünüm oluşturur. Garmin sıcaklık uyumlu özelliği bu durumu kısmen korelere. Polar'ın algoritması da benzer etkilidir. Normaldir ve gerçek performans azalmasının bir parçası değildir.",
          nl: "Hitte verhoogt de hartslag op elke gegeven snelheid, wat het algoritme maakt denken dat je harder werkt ten opzichte van je snelheid. Dit lijkt een fitnessdecline. Garmin heeft een hitte-acclimatiseerfunctie die dit gedeeltelijk compenseert. Polar's algoritme is eveneens beïnvloed. Het is normaal en geen echte fitnessdecline.",
          ja: "熱は速度に関係なく心拍数を増加させます。これによりアルゴリズムは、速さに対する努力量が大きくなっていると判断し、これはフィットネスの低下に見えます。Garminには熱の適応機能があり、これで一部補正されます。Polarのアルゴリズムも同様に影響を受けます。これは正常な現象であり、実際のフィットネスの低下ではありません。",
          ko: "온도는 속도에 따른 심장 박동수를 증가시켜, 알고리즘은 속도 대비 노력을 더 힘들게 보고합니다. 이것은 피트니스 저하처럼 보이지만 실제로는 피트니스 저하가 아닙니다. 가민은 열 적응 기능을 통해 이 영향을 부분적으로 보상합니다. 파올리의 알고리즘도 비슷하게 영향을 받습니다. 이는 자연스럽고 실제 피트니스 저하가 아닙니다.",
        },
    },
    {
      q: {
          it: "Ha importanza il VO2 Max da un dispositivo portatile se non sono un corredore?",
          en: "Does VO2 Max from a wearable matter if I am not a runner?",
          es: "¿Importa el VO2 Max en un dispositivo portátil si no soy corredor?",
          de: "Ist die VO2 Max-Schätzung aus einem Wearable für Nicht-Läufer wichtig?",
          pt: "A VO2 Max de um wearable importa se eu não for corredor?",
          fr: "Le VO2 Max mesuré par un appareil connecté compte-t-il si je ne suis pas coureur ?",
          pl: "Czy estymacja VO2 Max z przestrzeni ma znaczenie, jeśli nie jestem biegacz?",
          tr: "Eğer koşucu olmayan bir kişiyseniz, Wearable'dan elde edilen VO2 Max ne önemi var?",
          nl: "Heeft VO2 Max van een wearable zin als ik geen loper ben?",
          ja: "ランナー以外の人にとってVO2 Maxの推定値は重要ですか？",
          ko: "如果不是跑步者，穿戴设备的VO2 Max估算值有意义吗？",
        },
      a: {
          it: "La stima è più affidabile per i corredori, ma anche un numero approssimativo ha valore. Una tendenza in aumento nei mesi indica una migliorazione della fitness cardiovascolare indipendentemente dall'accuratezza assoluta. Per i ciclisti, alcuni dispositivi Garmin possono stimare il VO2 Max utilizzando dati di potenza, che sono più accurati rispetto alla stima basata su GPS.",
          en: "The estimate is most reliable for runners, but even a rough number has value. A rising trend over months indicates improving cardiovascular fitness regardless of the absolute accuracy. For cyclists, some Garmin devices can estimate VO2 Max using power meter data, which is more accurate than GPS-based estimation.",
          es: "El estimado es más preciso para corredores, pero incluso un número aproximado tiene valor. Una tendencia ascendente a lo largo del tiempo indica una mejora de la condición cardiovascular sin importar la precisión absoluta. Para ciclistas, algunos dispositivos Garmin pueden estimar el VO2 Max utilizando datos de potencia, lo cual es más preciso que la estimación basada en GPS.",
          de: "Die Schätzung ist am besten für Läufer zuverlässig, aber selbst eine grobe Zahl hat Wert. Ein steigender Trend über Monate zeigt Verbesserungen der kardiovaskulären Fitness unabhängig von der absoluten Genauigkeit. Für Radfahrer können einige Garmin-Geräte die VO2 Max-Schätzung mit Powermeterdaten schätzen, was genauer ist als GPS-basierte Schätzung.",
          pt: "A estimativa é mais confiável para corredores, mas até mesmo um número aproximado tem valor. Uma tendência crescente ao longo dos meses indica melhorar a condicionamento cardiovascular independentemente da precisão absoluta. Para ciclistas, alguns dispositivos Garmin podem estimar VO2 Max usando dados de potência, que são mais precisos do que a estimativa baseada em GPS.",
          fr: "L'estimation est la plus fiable pour les coureurs, mais même un chiffre approximatif a de la valeur. Une tendance en augmentation sur plusieurs mois indique une amélioration de la forme cardiaque et vasculaire indépendamment de l'exactitude absolue. Pour les cyclistes, certains appareils Garmin peuvent estimer le VO2 Max à partir des données d'un puissancemètre, ce qui est plus précis que l'estimation GPS.",
          pl: "Estymacja jest najbardziej wiarygodna dla biegaczy, ale nawet przybliżona liczba ma wartość. Znajdujący się w rosnącym trendzie przez miesiące oznacza poprawę fitnessu kardio-żylnego niezależnie od dokładności absolutnej. Dla cyklistów niektóre urządzenia Garmin mogą estymować VO2 Max na podstawie danych z mocy, co jest bardziej dokładne niż estymacja oparta na GPS.",
          tr: "Tahmin en çok koşucular için güvenilir, ancak bir tahminin de değeri vardır. Aylar boyunca artan eğilim, mutlak doğruluğa bakılmaksızın genel kardiyovasküler performans iyileşmesini gösterir. Bicycler için bazı Garmin cihazları güç ölçümü veri kullanarak VO2 Max tahmini yapabilirler, bu GPS bazlı tahminden daha doğru.",
          nl: "De schatting is meest betrouwbaar voor lopers, maar zelfs een ruwe waarde heeft waarde. Een stijgende trend over de maanden geeft aan verbeterende cardiovasculaire fitness ongeacht de absolute nauwkeurigheid. Voor fietsers kunnen sommige Garmin apparaten VO2 Max schatten met behulp van powermeterdata, wat betrouwbaarder is dan GPS-beschikbare schattingen.",
          ja: "この推定値は主にランナー向けですが、粗い数値でも価値があります。数ヶ月間の上昇トレンドは、絶対的な正確さに関係なく心肺機能が向上していることを示します。自転車競技者にとって、一部のGarminデバイスではパワーメーターデータを使用してVO2 Maxを推定し、GPSベースの推定よりも正確です。",
          ko: "该估算值对于跑步者来说最可靠，但即使是一个粗略的数字也有价值。几个月内呈上升趋势表明心血管健康有所改善，尽管绝对准确性可能有所不同。对于骑自行车的人来说，一些加利曼设备可以使用功率计数据来估算VO2 Max，这比基于GPS的估算更准确。",
        },
    },
    {
      q: {
          it: "Posso confrontare il mio VO2 Max su diversi dispositivi portatili?",
          en: "Can I compare my VO2 Max across different wearables?",
          es: "¿Puedo comparar mi VO2 Max entre diferentes dispositivos portátiles?",
          de: "Kann ich meine VO2 Max-Wertungen auf verschiedenen Wearables vergleichen?",
          pt: "Posso comparar minha VO2 Max em diferentes wearables?",
          fr: "Peut-on comparer son VO2 Max sur différents appareils connectés ?",
          pl: "Czy mogę porównywać moje VO2 Max między różnymi przestrzeniami?",
          tr: "Farklı Wearable'lardan benim VO2 Max'ımı karşılaştırabilirim mi?",
          nl: "Kan ik mijn VO2 Max vergelijken over verschillende wearables?",
          ja: "異なるウェアラブル間でVO2 Maxを比較できますか？",
          ko: "不同穿戴设备之间能否比较我的VO2 Max？",
        },
      a: {
          it: "Puoi confrontare la tendenza, ma non il numero assoluto direttamente. Garmin e Polar usano algoritmi diversi che spesso producono numeri differenti per lo stesso livello di fitness. Se passi da un dispositivo all'altro, aspetta una perioda di 2-4 settimane prima che la nuova stima converga a un valore stabile.",
          en: "You can compare the trend, but not the absolute number directly. Garmin and Polar use different algorithms that often produce different numbers for the same level of fitness. If you switch devices, expect a period of 2-4 weeks before the new estimate converges to a stable value.",
          es: "Puedes comparar la tendencia, pero no el número absoluto directamente. Garmin y Polar usan algoritmos diferentes que a menudo producen diferentes números para el mismo nivel de condición física. Si cambias de dispositivo, espera un período de 2-4 semanas antes de que el nuevo estimado converja a un valor estable.",
          de: "Sie können den Trend vergleichen, aber nicht die absolute Zahl direkt. Garmin und Polar verwenden unterschiedliche Algorithmen, die oft für das gleiche Niveau der Fitness unterschiedliche Zahlen erzeugen. Wenn Sie ein Gerät wechseln, erwarten Sie einen Zeitraum von 2-4 Wochen, bis die neue Schätzung zu einem stabilen Wert konvergiert.",
          pt: "Você pode comparar a tendência, mas não o número absoluto diretamente. Garmin e Polar usam algoritmos diferentes que frequentemente produzem números diferentes para o mesmo nível de condicionamento físico. Se você trocar de dispositivo, espere um período de 2-4 semanas antes que a nova estimativa se estabilize.",
          fr: "Vous pouvez comparer la tendance, mais pas le chiffre absolu directement. Garmin et Polar utilisent des algorithmes différents qui produisent souvent des chiffres différents pour le même niveau de forme physique. Si vous changez d'appareil, attendez une période de 2 à 4 semaines avant que l'estimation nouvelle ne converge vers une valeur stable.",
          pl: "Możesz porównywać trend, ale nie można bezpośrednio porównywać absolutnej liczby. Garmin i Polar używają różnych algorytmów, które często produkują różne liczby dla tego samego poziomu fitnessu. Jeśli zmienisz urządzenie, oczekuj okresu 2-4 tygodni przed tym, gdy nowa estymacja zasięgnie stabilnej wartości.",
          tr: "Eğilimi karşılaştıracaksınız ancak mutlak sayıları doğrudan karşılamazsınız. Garmin ve Polar farklı algoritmalar kullanarak aynı seviyede bir performans için genellikle farklı sayılar üretirler. Cihaz değiştirdiğinizde, yeni tahminin sabitleşmesine 2-4 hafta süre olabilir.",
          nl: "Je kunt de trend vergelijken, maar niet direct het absolute cijfer. Garmin en Polar gebruiken verschillende algoritmen die vaak verschillende cijfers produceren voor dezelfde fitnessniveau. Als je apparaten wisselt, verwacht een periode van 2-4 weken voordat de nieuwe schatting stabiliseert.",
          ja: "トレンドは比較できますが、絶対的な数値は直接比較できません。GarminとPolarは異なるアルゴリズムを使用し、同じレベルのフィットネスでも異なる数字を生成することがあります。デバイスを切り替えた場合、新しい推定値が安定するまで2-4週間程度かかることがあります。",
          ko: "您可以比较趋势，但不能直接比较绝对数值。加利曼和帕奥里使用不同的算法，即使健身水平相同也会产生不同的数字。如果您更换设备，请预期需要2-4周的时间才能使新估算值稳定下来。",
        },
    },
    {
      q: {
          it: "Stima il VO2 Max l'Ora Anello?",
          en: "Does Oura Ring estimate VO2 Max?",
          es: "¿Estima el Anillo Oura el VO2 Max?",
          de: "Schätzt der Oura-Ring den VO2 Max?",
          pt: "O Relógio Oura estima o VO2 Max?",
          fr: "Estime-t-il l'VO2 Max le Collier Oura ?",
          pl: "Czy przycisk Oura szacuje VO2 Max?",
          tr: "Oura Çenglesi VO2 Max tahmin eder mi?",
          nl: "Schat Oura Ring de VO2 Max?",
          ja: "OuraリングはVO2 Maxを推定しますか？",
          ko: "Oura 반지가 VO2 Max를 추정합니까?",
        },
      a: {
          it: "No. L'Ora Anello non dispone di GPS o di un metrica di ritmo, quindi non può stimare il VO2 Max. Si concentra invece sui parametri di recupero e sonno. Per il VO2 Max, hai bisogno di un braccialetto GPS.",
          en: "No. Oura Ring does not have GPS or a pace metric, so it cannot estimate VO2 Max. It focuses on recovery and sleep metrics instead. For VO2 Max, you need a GPS-enabled watch.",
          es: "No. El Anillo Oura no tiene GPS ni un métrico de ritmo, por lo que no puede estimar el VO2 Max. En su lugar, se centra en métricas de recuperación y sueño. Para el VO2 Max, necesitas un reloj con GPS.",
          de: "Nein. Der Oura-Ring hat kein GPS oder ein Tempo-Maß, sodass er den VO2 Max nicht schätzen kann. Er konzentriert sich stattdessen auf Rekuperations- und Schlafmaße. Für den VO2 Max benötigst du einen GPS-befestigten Armbanduhr.",
          pt: "Não. O Relógio Oura não possui GPS ou uma métrica de ritmo, então não pode estimar o VO2 Max. Ele se concentra nas métricas de recuperação e sono em vez disso. Para o VO2 Max, você precisa de um relógio com GPS.",
          fr: "Non. Le Collier Oura n'a pas de GPS ou une métrique de vitesse, donc il ne peut pas estimer l'VO2 Max. Il se concentre plutôt sur les métriques de récupération et de sommeil. Pour l'VO2 Max, vous avez besoin d'un bracelet avec GPS.",
          pl: "Nie. Przycisk Oura nie ma GPS ani metryki prędkości, więc nie może szacować VO2 Max. Zamiast tego skupia się na miernikach recyrklu i snu. Dla VO2 Max potrzebujesz zainstalowanego GPS w zegarku.",
          tr: "Hayır. Oura Çenglesi GPS veya hız metriği bulunmamakta, bu yüzden VO2 Max tahmin edemez. Yenileme ve uyku metrikleri üzerine odaklanmaktadır. VO2 Max için GPS sahip bir saat gereklidir.",
          nl: "Nee. De Oura Ring heeft geen GPS of een snelheidsmeetfunctie, dus kan ze de VO2 Max niet schatten. Ze focust op herstel- en slaapmetriken in plaats daarvan. Voor de VO2 Max heb je een GPS-gevoelige klok nodig.",
          ja: "いいえ。OuraリングにはGPSやペースメトリックがなく、そのためVO2 Maxを推定することはできません。代わりに回復と睡眠のメトリックに焦点を当てています。VO2 MaxはGPS搭載のウォッチが必要です。",
          ko: "아니요. Oura 반지는 GPS 또는 속도 메트릭이 없으므로 VO2 Max를 추정할 수 없습니다. 대신 회복과 수면 메트릭에 집중하고 있습니다. VO2 Max는 GPS가 있는 시계가 필요합니다.",
        },
    },
  ],
  brandsMentioned: ["Garmin", "Polar", "Samsung", "Apple"],
  related: ["hrv-cose-significato-valori", "anello-vs-smartwatch", "scegliere-smartwatch-dati-2026"],
};
